import { supabase } from '../../core/supabase/client';
import './cash-rain-catcher.css';

type Drop={x:number;y:number;speed:number;type:'cash'|'gold'|'hazard'|'shield'|'magnet'};
const GAME_ID='4e45fcfd-f886-4047-a257-4e6f5e64339a';
const SAVE='rb-cash-rain-v1';
const app=document.querySelector<HTMLElement>('#app')!;
app.innerHTML=`<main class="crc-shell"><div class="crc-wrap"><header class="crc-top"><a href="/gaming.html">← GAMING HQ</a><div class="crc-brand"><small>ELITE ARCADE 03 / 04</small><h1>CASH RAIN CATCHER</h1></div><span class="crc-status" id="net">OFFLINE READY</span></header><section class="crc-hero"><div><small class="crc-kicker">MOVE • CATCH • DODGE • BOOST • REALTIME</small><h2>OWN THE<br>CASH STORM.</h2><p>Control the collector, chain precision catches, dodge debt hazards, activate shield and magnet power-ups, survive escalating storm phases, and build a ranked Rich XP career.</p></div><div class="crc-stats"><article><small>RICH XP</small><strong id="xp">0</strong></article><article><small>LEVEL</small><strong id="level">1</strong></article><article><small>WINS</small><strong id="wins">0</strong></article><article><small>BEST</small><strong id="best">0</strong></article></div></section><section class="crc-grid"><div class="crc-stage"><div class="crc-hud"><div><small>SCORE</small><b id="score">0</b></div><div><small>COMBO</small><b id="combo">x1</b></div><div><small>SHIELD</small><b id="shield">0</b></div><div><small>TIME</small><b id="time">60</b></div></div><canvas id="storm" width="1280" height="800"></canvas><div class="crc-controls"><button class="crc-btn" data-move="-1">LEFT</button><button class="crc-btn" data-move="1">RIGHT</button><button class="crc-btn primary" id="dash">SMOKE DASH</button><button class="crc-btn gold" id="magnet">MAGNET</button><button class="crc-btn" id="armor">SHIELD</button></div></div><aside class="crc-side"><section class="crc-card"><h3>STORM COMMAND</h3><select class="crc-select" id="mode"><option value="career">CASH STORM CAREER</option><option value="endless">ENDLESS MONSOON</option><option value="local">LOCAL SCORE DUEL</option><option value="online">REALTIME RANKED</option></select><select class="crc-select" id="difficulty"><option value="1">ROOKIE RAIN</option><option value="2" selected>ELITE STORM</option><option value="3">BOSS MONSOON</option></select><button class="crc-btn primary" id="start">START STORM</button><p class="crc-log" id="log">Choose a mode and enter the storm.</p></section><section class="crc-card"><h3>STORM PRESSURE</h3><div class="crc-meter"><i id="pressure"></i></div></section><section class="crc-card"><h3>REALTIME ROOM</h3><input class="crc-input" id="roomCode" maxlength="8" placeholder="ROOM CODE"/><div class="crc-row"><button class="crc-btn primary" id="createRoom">CREATE</button><button class="crc-btn" id="joinRoom">JOIN</button></div><p class="crc-log" id="roomState">Tap In required for ranked storms.</p></section><section class="crc-card"><h3>CASH LEADERS</h3><div class="crc-list" id="leaders"></div></section></aside></section><footer class="crc-footer">CASH RAIN CATCHER v1.0 • GAMING + PROFILE SYNC</footer></div></main>`;
const $=<T extends HTMLElement>(q:string)=>document.querySelector<T>(q)!;
const canvas=$<HTMLCanvasElement>('#storm'),ctx=canvas.getContext('2d')!;
let user:any=null,channel:any=null,running=false,score=0,combo=1,best=0,xp=0,level=1,wins=0,time=60,shield=0,magnet=0,dash=0,x=640,difficulty=2,spawn=0,last=0,started=0;
const drops:Drop[]=[];const keys=new Set<string>();
function sync(){const saved=JSON.parse(localStorage.getItem(SAVE)||'{}');if(!running){best=saved.best||0;xp=saved.xp||0;level=saved.level||1;wins=saved.wins||0}$('#score').textContent=String(score);$('#combo').textContent=`x${combo}`;$('#shield').textContent=String(shield);$('#time').textContent=String(Math.ceil(time));$('#xp').textContent=String(xp);$('#level').textContent=String(level);$('#wins').textContent=String(wins);$('#best').textContent=String(Math.max(best,score));($('#pressure') as HTMLElement).style.transform=`scaleX(${Math.min(1,(60-time)/60)})`}
function addDrop(){const r=Math.random();const type:Drop['type']=r<.58?'cash':r<.7?'gold':r<.84?'hazard':r<.92?'shield':'magnet';drops.push({x:40+Math.random()*1200,y:-30,speed:210+difficulty*55+Math.random()*120,type})}
function startGame(){running=true;score=0;combo=1;time=($('#mode') as HTMLSelectElement).value==='endless'?9999:60;shield=0;magnet=0;dash=0;difficulty=Number(($('#difficulty') as HTMLSelectElement).value);drops.length=0;started=Date.now();$('#log').textContent='Storm active. Catch value and avoid debt hazards.';requestAnimationFrame(loop)}
function catchDrop(d:Drop){if(d.type==='hazard'){if(shield)shield--;else{score=Math.max(0,score-400);combo=1}return}if(d.type==='shield'){shield+=2;return}if(d.type==='magnet'){magnet=7;return}combo=Math.min(20,combo+1);score+=(d.type==='gold'?220:80)*combo}
function update(dt:number){time-=dt;spawn-=dt;if(spawn<=0){addDrop();spawn=Math.max(.09,.42-difficulty*.06-(60-Math.min(60,time))*.004)}const speed=420*(dash>0?1.8:1);if(keys.has('arrowleft')||keys.has('a'))x-=speed*dt;if(keys.has('arrowright')||keys.has('d'))x+=speed*dt;x=Math.max(70,Math.min(1210,x));dash=Math.max(0,dash-dt);magnet=Math.max(0,magnet-dt);for(let i=drops.length-1;i>=0;i--){const d=drops[i];if(magnet>0&&d.type!=='hazard')d.x+=(x-d.x)*Math.min(1,dt*3);d.y+=d.speed*dt;if(Math.abs(d.x-x)<85&&d.y>650&&d.y<760){catchDrop(d);drops.splice(i,1)}else if(d.y>840){if(d.type==='cash'||d.type==='gold')combo=1;drops.splice(i,1)}}if(time<=0)void finish();sync()}
function draw(){ctx.fillStyle='#031006';ctx.fillRect(0,0,1280,800);for(let i=0;i<25;i++){ctx.strokeStyle='rgba(49,255,99,.08)';ctx.beginPath();ctx.moveTo((i*97+Date.now()/15)%1280,0);ctx.lineTo((i*97+Date.now()/15)%1280-90,800);ctx.stroke()}for(const d of drops){ctx.fillStyle=d.type==='hazard'?'#ff3b30':d.type==='gold'?'#f7c948':d.type==='shield'?'#4ab8ff':d.type==='magnet'?'#d56bff':'#31ff63';ctx.beginPath();ctx.arc(d.x,d.y,d.type==='hazard'?22:17,0,Math.PI*2);ctx.fill();ctx.fillStyle='#041007';ctx.font='900 15px system-ui';ctx.textAlign='center';ctx.fillText(d.type==='hazard'?'!':d.type==='shield'?'S':d.type==='magnet'?'M':'$',d.x,d.y+5)}ctx.fillStyle='#f7c948';ctx.fillRect(x-64,700,128,34);ctx.fillStyle='#31ff63';ctx.fillRect(x-42,680,84,22);if(shield){ctx.strokeStyle='#4ab8ff';ctx.lineWidth=5;ctx.beginPath();ctx.arc(x,705,92,Math.PI,Math.PI*2);ctx.stroke()}}
function loop(t:number){if(!running)return;const dt=Math.min(.034,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}
async function finish(){if(!running)return;running=false;best=Math.max(best,score);if(score>2500*difficulty)wins++;const gain=Math.max(60,Math.round(score/15));xp+=gain;level=1+Math.floor(xp/1200);localStorage.setItem(SAVE,JSON.stringify({best,xp,level,wins}));sync();$('#log').textContent=`Storm complete • +${gain} XP`;if(!user)return;const duration=Math.round((Date.now()-started)/1000);await Promise.allSettled([supabase.from('game_scores').insert({game_id:GAME_ID,user_id:user.id,score,score_type:'cash_storm'}),supabase.from('game_sessions').insert({game_id:GAME_ID,user_id:user.id,status:'completed',score,duration_seconds:duration}),supabase.from('game_player_progress').upsert({game_id:GAME_ID,user_id:user.id,xp,best_score:best,progress_data:{level,wins}},{onConflict:'game_id,user_id'})]);void leaders()}
async function leaders(){const {data}=await supabase.from('game_scores').select('score,profiles(display_name)').eq('game_id',GAME_ID).order('score',{ascending:false}).limit(5);$('#leaders').innerHTML=(data||[]).map((r:any,i)=>`<div class="crc-item"><b>#${i+1} ${r.profiles?.display_name||'COLLECTOR'}</b><span>${r.score}</span></div>`).join('')||'<p class="crc-log">No ranked storms yet.</p>'}
function connect(code:string){if(!user)return;channel=supabase.channel(`cash-rain:${code}`,{config:{presence:{key:user.id}}}).on('broadcast',{event:'score'},({payload})=>{$('#roomState').textContent=`RIVAL ${payload.score}`}).subscribe(async s=>{if(s==='SUBSCRIBED'){await channel.track({score});$('#roomState').textContent=`ROOM ${code} LIVE`}})}
$('#start').onclick=startGame;document.querySelectorAll<HTMLButtonElement>('[data-move]').forEach(b=>{const k=b.dataset.move==='-1'?'arrowleft':'arrowright';b.onpointerdown=()=>keys.add(k);b.onpointerup=()=>keys.delete(k)});$('#dash').onclick=()=>dash=1.2;$('#magnet').onclick=()=>magnet=7;$('#armor').onclick=()=>shield++;addEventListener('keydown',e=>keys.add(e.key.toLowerCase()));addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));canvas.onpointermove=e=>{const r=canvas.getBoundingClientRect();x=(e.clientX-r.left)/r.width*1280};$('#createRoom').onclick=()=>connect(Math.random().toString(36).slice(2,8).toUpperCase());$('#joinRoom').onclick=()=>connect(($('#roomCode') as HTMLInputElement).value.trim().toUpperCase());setInterval(()=>{if(channel&&running)void channel.send({type:'broadcast',event:'score',payload:{score}})},1200);supabase.auth.getUser().then(({data})=>{user=data.user;if(user)$('#net').textContent='CLOUD ONLINE'});sync();void leaders();draw();