import { supabase } from '../../core/supabase/client';
import './crown-connect-four.css';

type Cell=0|1|2; type Mode='solo'|'local'|'online';
const GAME='crown-connect-four', ROWS=6, COLS=7;
const root=document.querySelector<HTMLElement>('#app')!; const $=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
if(root.dataset.gameOwner==='crown-connect-four-v4') throw new Error('Crown Connect Four already mounted');
root.dataset.gameOwner='crown-connect-four-v4';
let board:Cell[][]=empty(),turn:1|2=1,mode:Mode='solo',over=false,winCells:number[][]=[],started=Date.now(),user:any=null,room:any=null,channel:any=null,history:Cell[][][]=[],streak=0,sessionKey:string|null=null,lastDrop:{r:number;c:number}|null=null,animating=false;
const empty=()=>Array.from({length:ROWS},()=>Array<Cell>(COLS).fill(0));
root.innerHTML=`<main class="ccf-shell"><div class="ccf-wrap"><header class="ccf-top"><a href="/gaming.html" aria-label="Back to Gaming">←</a><div class="ccf-brand"><small>RICH BIZNESS ELITE GAME 28 / 28</small><h1>CROWN CONNECT FOUR</h1></div><span id="net" class="ccf-status">OFFLINE READY</span></header><section class="ccf-hero"><div><small class="ccf-kicker">SOLO • LOCAL • REALTIME • OFFLINE • TOURNAMENT</small><h2>CONNECT.<br>CONTROL.<br>CROWN.</h2><p>Precision gravity strategy with cinematic disc motion, adaptive Grandmaster AI, ranked rooms, persistent Rich XP and elite tournament scoring.</p></div><div class="ccf-stats"><article><small>RICH XP</small><strong id="xp">0</strong></article><article><small>BEST SCORE</small><strong id="best">0</strong></article><article><small>WINS</small><strong id="wins">0</strong></article><article><small>STREAK</small><strong id="streak">0</strong></article></div></section><section class="ccf-layout"><section class="ccf-board-shell"><div class="ccf-playerbar"><article><span class="ccf-token gold"></span><div><small>RICH PLAYER</small><strong id="p1Name">YOU</strong></div></article><div id="turn" class="ccf-turn">GOLD CROWN TURN</div><article><div><small>CPU RIVAL</small><strong id="p2Name">GRANDMASTER</strong></div><span class="ccf-token green"></span></article></div><div id="columns" class="ccf-column-controls"></div><div id="board" class="ccf-board" aria-label="Crown Connect Four board"></div><div class="ccf-board-glow"></div></section><aside class="ccf-side"><section class="ccf-card"><h3>PLAY MODE</h3><div class="ccf-modes"><button class="ccf-btn active" data-mode="solo">SOLO AI</button><button class="ccf-btn" data-mode="local">LOCAL</button><button class="ccf-btn" data-mode="online">ONLINE</button></div><select id="difficulty" class="ccf-select"><option value="rookie">ROOKIE</option><option value="hustler">HUSTLER</option><option value="boss">BOSS</option><option value="grandmaster" selected>GRANDMASTER</option></select><div class="ccf-controls"><button id="newGame" class="ccf-btn primary">NEW MATCH</button><button id="undo" class="ccf-btn">UNDO</button><button id="resign" class="ccf-btn danger">RESIGN</button></div><p id="log" class="ccf-log">Drop a Gold Crown disc to begin.</p></section><section class="ccf-card"><h3>RANKED ROOM</h3><input id="roomCode" class="ccf-input" maxlength="8" placeholder="ROOM CODE"><div class="ccf-controls"><button id="createRoom" class="ccf-btn primary">CREATE</button><button id="joinRoom" class="ccf-btn">JOIN</button><button id="leaveRoom" class="ccf-btn">LEAVE</button></div><p id="roomState" class="ccf-log">Tap In required for realtime play.</p></section><section class="ccf-card"><h3>ELITE LEADERBOARD</h3><div id="leaders" class="ccf-board-list"></div></section></aside></section><footer class="ccf-footer">CROWN CONNECT FOUR v4 • GRAVITY MOTION • GRANDMASTER AI • SUPABASE REALTIME • RICH XP</footer></div></main>`;
function validCols(b=board){return [...Array(COLS).keys()].filter(c=>b[0][c]===0)}
function rowFor(c:number,b=board){for(let r=ROWS-1;r>=0;r--)if(b[r][c]===0)return r;return -1}
function clone(b=board){return b.map(r=>[...r]) as Cell[][]}
function lineWin(b=board){const ds=[[0,1],[1,0],[1,1],[1,-1]];for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++){const p=b[r][c];if(!p)continue;for(const[dr,dc]of ds){const cells:number[][]=[];for(let k=0;k<4;k++){const rr=r+dr*k,cc=c+dc*k;if(rr<0||rr>=ROWS||cc<0||cc>=COLS||b[rr][cc]!==p)break;cells.push([rr,cc])}if(cells.length===4)return{player:p as 1|2,cells}}}return null}
function immediate(player:1|2,b=board){for(const c of validCols(b)){const x=clone(b),r=rowFor(c,x);x[r][c]=player;if(lineWin(x))return c}return null}
function scoreWindow(a:Cell[],p:1|2){const o=p===1?2:1,n=a.filter(x=>x===p).length,e=a.filter(x=>x===0).length,q=a.filter(x=>x===o).length;return n===4?100000:n===3&&e===1?160:n===2&&e===2?24:q===3&&e===1?-190:q===2&&e===2?-20:0}
function evaluate(b:Cell[][],p:1|2){let s=0;for(let r=0;r<ROWS;r++)if(b[r][3]===p)s+=12;const w:Cell[][]=[];for(let r=0;r<ROWS;r++)for(let c=0;c<COLS-3;c++)w.push(b[r].slice(c,c+4));for(let c=0;c<COLS;c++)for(let r=0;r<ROWS-3;r++)w.push([b[r][c],b[r+1][c],b[r+2][c],b[r+3][c]]);for(let r=0;r<ROWS-3;r++)for(let c=0;c<COLS-3;c++)w.push([b[r][c],b[r+1][c+1],b[r+2][c+2],b[r+3][c+3]]);for(let r=0;r<ROWS-3;r++)for(let c=3;c<COLS;c++)w.push([b[r][c],b[r+1][c-1],b[r+2][c-2],b[r+3][c-3]]);return s+w.reduce((a,z)=>a+scoreWindow(z,p),0)}
function minimax(b:Cell[][],d:number,max:boolean,a=-Infinity,z=Infinity):number{const w=lineWin(b);if(w)return w.player===2?1000000+d:-1000000-d;if(!d||!validCols(b).length)return evaluate(b,2);if(max){let v=-Infinity;for(const c of validCols(b)){const x=clone(b),r=rowFor(c,x);x[r][c]=2;v=Math.max(v,minimax(x,d-1,false,a,z));a=Math.max(a,v);if(a>=z)break}return v}let v=Infinity;for(const c of validCols(b)){const x=clone(b),r=rowFor(c,x);x[r][c]=1;v=Math.min(v,minimax(x,d-1,true,a,z));z=Math.min(z,v);if(a>=z)break}return v}
function aiColumn(){const win=immediate(2);if(win!==null)return win;const block=immediate(1);if(block!==null)return block;const level=$<HTMLSelectElement>('#difficulty').value,depth=level==='rookie'?1:level==='hustler'?2:level==='boss'?4:5;let best=-Infinity,choices:number[]=[];for(const c of validCols()){const x=clone(),r=rowFor(c,x);x[r][c]=2;const s=minimax(x,depth-1,false)+(3-Math.abs(3-c))*2+Math.random()*1.5;if(s>best){best=s;choices=[c]}else if(Math.abs(s-best)<.01)choices.push(c)}return choices[Math.floor(Math.random()*choices.length)]??3}
function render(){const threats=new Set<string>();for(const c of validCols()){const r=rowFor(c);for(const p of [1,2] as const){const x=clone();x[r][c]=p;if(lineWin(x))threats.add(`${r}-${c}`)}}$('#columns').innerHTML=[...Array(COLS).keys()].map(c=>`<button data-col="${c}" ${over||animating||rowFor(c)<0?'disabled':''} aria-label="Drop in column ${c+1}">▼</button>`).join('');$('#board').innerHTML=board.flatMap((row,r)=>row.map((v,c)=>`<div class="ccf-cell ${winCells.some(x=>x[0]===r&&x[1]===c)?'win':''} ${lastDrop?.r===r&&lastDrop?.c===c?'last':''}">${v?`<span class="ccf-disc p${v}"></span>`:''}${!v&&threats.has(`${r}-${c}`)?'<span class="ccf-threat"></span>':''}</div>`)).join('');$('#turn').textContent=over?'MATCH COMPLETE':turn===1?'GOLD CROWN TURN':'GREEN EMPIRE TURN';$('#streak').textContent=String(streak);document.querySelectorAll<HTMLButtonElement>('[data-col]').forEach(b=>b.onclick=()=>void play(Number(b.dataset.col)));localStorage.setItem('rb-crown-connect-four',JSON.stringify({streak,mode}))}
async function startSession(){if(!user)return;const {data}=await supabase.rpc('rb_game_action',{p_action:'start_session',p_game_slug:GAME,p_payload:{platform_type:'web',device_info:{mobile:matchMedia('(max-width:760px)').matches},metadata:{mode,difficulty:$<HTMLSelectElement>('#difficulty').value}}});sessionKey=(data as any)?.session_key??null}
async function play(c:number,remote=false){if(over||animating||rowFor(c)<0)return;if(!remote&&mode==='online'&&turn===2)return;animating=true;history.push(clone());const r=rowFor(c);board[r][c]=turn;lastDrop={r,c};render();await new Promise(x=>setTimeout(x,260));animating=false;const w=lineWin();if(w){winCells=w.cells;over=true;const result=w.player===1?'win':'loss';streak=result==='win'?streak+1:0;$('#log').textContent=result==='win'?'CROWN CONNECTION COMPLETE.':'GREEN EMPIRE TOOK THE BOARD.';render();await finish(result);if(mode==='online'&&!remote)await broadcast();return}if(!validCols().length){over=true;$('#log').textContent='DRAW — BOARD LOCKED.';render();await finish('draw');return}turn=turn===1?2:1;render();if(mode==='online'&&!remote)await broadcast();if(mode==='solo'&&turn===2&&!over)setTimeout(()=>void play(aiColumn(),true),320)}
async function finish(result:string){const score=result==='win'?3000+streak*300:result==='draw'?900:300,duration=Math.max(1,Math.floor((Date.now()-started)/1000)),xp=result==='win'?180:60;if(user&&sessionKey){await supabase.rpc('rb_game_action',{p_action:'finish_session',p_game_slug:GAME,p_payload:{session_key:sessionKey,score,duration_seconds:duration,result,xp,mode,platform_type:'web',metadata:{streak,difficulty:$<HTMLSelectElement>('#difficulty').value,moves:board.flat().filter(Boolean).length}}});sessionKey=null;await stats()}}
async function reset(){board=empty();turn=1;over=false;winCells=[];history=[];lastDrop=null;started=Date.now();$('#log').textContent='New Crown match ready.';render();await startSession();if(mode==='online')void broadcast()}
function undo(){if(mode==='online'||!history.length)return;board=history.pop()!;turn=turn===1?2:1;over=false;winCells=[];lastDrop=null;render()}
async function stats(){const{data:s}=await supabase.from('game_scores').select('display_name,username,score').eq('game_slug',GAME).order('score',{ascending:false}).limit(8);$('#leaders').innerHTML=(s||[]).map((x:any,i)=>`<article><b>#${i+1}</b><span>${x.display_name||x.username||'Rich Player'}</span><strong>${Number(x.score||0).toLocaleString()}</strong></article>`).join('')||'<p class="ccf-log">No ranked scores yet.</p>';if(user){const{data:p}=await supabase.from('game_player_progress').select('*').eq('game_id','2b34e521-036b-4a04-9b4e-41741f9a4e7f').eq('user_id',user.id).maybeSingle();$('#xp').textContent=Number(p?.xp||0).toLocaleString();$('#best').textContent=Number(p?.best_score||0).toLocaleString();$('#wins').textContent=Number(p?.progress?.wins||0).toLocaleString()}}
async function createRoom(){if(!user)return $('#roomState').textContent='Tap In required.';const code=Math.random().toString(36).slice(2,8).toUpperCase();const{data:r,error}=await supabase.from('game_rooms').insert({room_code:code,game_key:GAME,host_user_id:user.id,status:'active',game_state:{board,turn}}).select().single();if(error)return $('#roomState').textContent=error.message;room=r;$<HTMLInputElement>('#roomCode').value=code;$('#roomState').textContent=`ROOM ${code} OPEN`;subscribe()}
async function joinRoom(){if(!user)return $('#roomState').textContent='Tap In required.';const code=$<HTMLInputElement>('#roomCode').value.trim().toUpperCase();const{data:r}=await supabase.from('game_rooms').select('*').eq('room_code',code).eq('game_key',GAME).maybeSingle();if(!r)return $('#roomState').textContent='Room not found.';room=r;board=(r.game_state?.board||empty()) as Cell[][];turn=r.game_state?.turn||1;mode='online';$('#roomState').textContent=`JOINED ${code}`;subscribe();render()}
function subscribe(){if(channel)void supabase.removeChannel(channel);channel=supabase.channel(`${GAME}:${room.id}`).on('broadcast',{event:'state'},({payload}:any)=>{if(payload?.user===user?.id)return;board=payload.board;turn=payload.turn;over=payload.over;winCells=payload.winCells||[];lastDrop=payload.lastDrop||null;render()}).subscribe(s=>$('#net').textContent=s==='SUBSCRIBED'?'REALTIME LIVE':s)}
async function broadcast(){if(channel)await channel.send({type:'broadcast',event:'state',payload:{user:user?.id,board,turn,over,winCells,lastDrop}})}
function leave(){if(channel)void supabase.removeChannel(channel);channel=null;room=null;$('#roomState').textContent='Left realtime room.';$('#net').textContent='OFFLINE READY'}
document.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode as Mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));if(mode!=='online')leave();void reset()});$('#newGame').onclick=()=>void reset();$('#undo').onclick=undo;$('#resign').onclick=()=>{if(!over){over=true;$('#log').textContent='MATCH RESIGNED';render();void finish('resign')}};$('#createRoom').onclick=()=>void createRoom();$('#joinRoom').onclick=()=>void joinRoom();$('#leaveRoom').onclick=leave;
(async()=>{try{streak=Number(JSON.parse(localStorage.getItem('rb-crown-connect-four')||'{}').streak||0)}catch{}const{data:{session}}=await supabase.auth.getSession();user=session?.user||null;await stats();render();await startSession()})();window.addEventListener('beforeunload',()=>{if(channel)void supabase.removeChannel(channel)});