import { supabase } from '../../core/supabase/client';
import './crown-connect-four.css';

type Cell=0|1|2; type Mode='solo'|'local'|'online';
const GAME_ID='2b34e521-036b-4a04-9b4e-41741f9a4e7f', GAME='crown-connect-four', ROWS=6, COLS=7;
const root=document.querySelector<HTMLElement>('#app')!; const $=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
let board:Cell[][]=empty(),turn:1|2=1,mode:Mode='solo',over=false,wins:number[][]=[],started=Date.now(),user:any=null,profile:any=null,room:any=null,channel:any=null,powers={crown:1,swap:1},history:Cell[][][]=[],streak=0;
function empty(){return Array.from({length:ROWS},()=>Array<Cell>(COLS).fill(0))}
root.innerHTML=`<main class="ccf-shell"><div class="ccf-wrap"><header class="ccf-top"><a href="/gaming.html">←</a><div class="ccf-brand"><small>RICH BIZNESS ELITE GAME 28 / 28</small><h1>CROWN CONNECT FOUR</h1></div><span id="net" class="ccf-status">OFFLINE READY</span></header><section class="ccf-hero"><div><small class="ccf-kicker">SOLO • LOCAL • REALTIME • OFFLINE • TOURNAMENT</small><h2>CONNECT.<br>CONTROL.<br>CROWN.</h2><p>Advanced gravity strategy with tactical threat mapping, adaptive AI, power moves, ranked rooms, persistent Rich XP and elite tournament scoring.</p></div><div class="ccf-stats"><article><small>RICH XP</small><strong id="xp">0</strong></article><article><small>BEST SCORE</small><strong id="best">0</strong></article><article><small>WINS</small><strong id="wins">0</strong></article><article><small>STREAK</small><strong id="streak">0</strong></article></div></section><section class="ccf-layout"><section class="ccf-board-shell"><div id="turn" class="ccf-turn">GOLD CROWN TURN</div><div id="columns" class="ccf-column-controls"></div><div id="board" class="ccf-board" aria-label="Crown Connect Four board"></div></section><aside class="ccf-side"><section class="ccf-card"><h3>PLAY MODE</h3><div class="ccf-modes"><button class="ccf-btn active" data-mode="solo">SOLO AI</button><button class="ccf-btn" data-mode="local">LOCAL</button><button class="ccf-btn" data-mode="online">ONLINE</button></div><select id="difficulty" class="ccf-select"><option value="rookie">ROOKIE</option><option value="elite" selected>ELITE</option><option value="crown">CROWN AI</option></select><button id="newGame" class="ccf-btn primary">NEW MATCH</button><p id="log" class="ccf-log">Drop a Gold Crown disc to begin.</p></section><section class="ccf-card"><h3>CROWN POWERS</h3><div class="ccf-power"><button id="crownPower" class="ccf-btn">CROWN DROP ×1</button><button id="swapPower" class="ccf-btn">ROYAL SWAP ×1</button></div><button id="undo" class="ccf-btn">PRACTICE UNDO</button><p class="ccf-log">Crown Drop clears a full column before dropping. Royal Swap converts one exposed rival disc.</p></section><section class="ccf-card"><h3>RANKED ROOM</h3><input id="roomCode" class="ccf-input" maxlength="8" placeholder="ROOM CODE"><div class="ccf-controls"><button id="createRoom" class="ccf-btn primary">CREATE</button><button id="joinRoom" class="ccf-btn">JOIN</button><button id="leaveRoom" class="ccf-btn">LEAVE</button></div><p id="roomState" class="ccf-log">Tap In required for realtime play.</p></section><section class="ccf-card"><h3>ELITE LEADERBOARD</h3><div id="leaders" class="ccf-board-list"></div></section></aside></section><footer class="ccf-footer">CROWN CONNECT FOUR v1.0 • GRAVITY ENGINE • THREAT AI • SUPABASE REALTIME • RICH XP</footer></div></main>`;
function validCols(b=board){return [...Array(COLS).keys()].filter(c=>b[0][c]===0)}
function rowFor(c:number,b=board){for(let r=ROWS-1;r>=0;r--)if(b[r][c]===0)return r;return -1}
function clone(b=board){return b.map(r=>[...r]) as Cell[][]}
function lineWin(b=board){const dirs=[[0,1],[1,0],[1,1],[1,-1]];for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++){const p=b[r][c];if(!p)continue;for(const[dR,dC]of dirs){const cells=[];for(let k=0;k<4;k++){const rr=r+dR*k,cc=c+dC*k;if(rr<0||rr>=ROWS||cc<0||cc>=COLS||b[rr][cc]!==p)break;cells.push([rr,cc])}if(cells.length===4)return{player:p,cells}}}return null}
function immediate(player:1|2,b=board){for(const c of validCols(b)){const x=clone(b),r=rowFor(c,x);x[r][c]=player;if(lineWin(x))return c}return null}
function scoreWindow(a:Cell[],p:1|2){const o=p===1?2:1,n=a.filter(x=>x===p).length,e=a.filter(x=>x===0).length,q=a.filter(x=>x===o).length;return n===4?100000:n===3&&e===1?120:n===2&&e===2?18:q===3&&e===1?-140:0}
function evaluate(b:Cell[][],p:1|2){let s=0;for(let r=0;r<ROWS;r++)if(b[r][3]===p)s+=8;const windows:Cell[][]=[];for(let r=0;r<ROWS;r++)for(let c=0;c<COLS-3;c++)windows.push(b[r].slice(c,c+4));for(let c=0;c<COLS;c++)for(let r=0;r<ROWS-3;r++)windows.push([b[r][c],b[r+1][c],b[r+2][c],b[r+3][c]]);for(let r=0;r<ROWS-3;r++)for(let c=0;c<COLS-3;c++)windows.push([b[r][c],b[r+1][c+1],b[r+2][c+2],b[r+3][c+3]]);for(let r=0;r<ROWS-3;r++)for(let c=3;c<COLS;c++)windows.push([b[r][c],b[r+1][c-1],b[r+2][c-2],b[r+3][c-3]]);return s+windows.reduce((a,w)=>a+scoreWindow(w,p),0)}
function minimax(b:Cell[][],depth:number,max:boolean,alpha=-Infinity,beta=Infinity):number{const w=lineWin(b);if(w)return w.player===2?1000000+depth:-1000000-depth;if(depth===0||!validCols(b).length)return evaluate(b,2);if(max){let v=-Infinity;for(const c of validCols(b)){const x=clone(b),r=rowFor(c,x);x[r][c]=2;v=Math.max(v,minimax(x,depth-1,false,alpha,beta));alpha=Math.max(alpha,v);if(alpha>=beta)break}return v}else{let v=Infinity;for(const c of validCols(b)){const x=clone(b),r=rowFor(c,x);x[r][c]=1;v=Math.min(v,minimax(x,depth-1,true,alpha,beta));beta=Math.min(beta,v);if(alpha>=beta)break}return v}}
function aiColumn(){const win=immediate(2);if(win!==null)return win;const block=immediate(1);if(block!==null)return block;const d=$<HTMLSelectElement>('#difficulty').value==='rookie'?1:$<HTMLSelectElement>('#difficulty').value==='crown'?5:3;let best=-Infinity,choices:number[]=[];for(const c of validCols()){const x=clone(),r=rowFor(c,x);x[r][c]=2;const s=minimax(x,d-1,false);if(s>best){best=s;choices=[c]}else if(s===best)choices.push(c)}return choices[Math.floor(Math.random()*choices.length)]??3}
function threatCells(){const out=new Set<string>();for(const c of validCols()){const r=rowFor(c);for(const p of [1,2] as const){const x=clone();x[r][c]=p;if(lineWin(x))out.add(`${r}-${c}`)}}return out}
function render(){const threats=threatCells();$('#columns').innerHTML=[...Array(COLS).keys()].map(c=>`<button data-col="${c}" ${over||rowFor(c)<0?'disabled':''}>▼</button>`).join('');$('#board').innerHTML=board.flatMap((row,r)=>row.map((v,c)=>`<div class="ccf-cell ${wins.some(x=>x[0]===r&&x[1]===c)?'win':''}">${v?`<span class="ccf-disc p${v}"></span>`:''}${!v&&threats.has(`${r}-${c}`)?'<span class="ccf-threat"></span>':''}</div>`)).join('');$('#turn').textContent=over?'MATCH COMPLETE':turn===1?'GOLD CROWN TURN':'GREEN EMPIRE TURN';$('#streak').textContent=String(streak);$('#crownPower').textContent=`CROWN DROP ×${powers.crown}`;$('#swapPower').textContent=`ROYAL SWAP ×${powers.swap}`;$('#crownPower').toggleAttribute('disabled',powers.crown<1||over);$('#swapPower').toggleAttribute('disabled',powers.swap<1||over);document.querySelectorAll<HTMLButtonElement>('[data-col]').forEach(b=>b.onclick=()=>void play(Number(b.dataset.col)));saveLocal()}
async function play(c:number,remote=false){if(over||rowFor(c)<0)return;if(!remote&&mode==='online'&&turn===2)return;history.push(clone());const r=rowFor(c);board[r][c]=turn;const w=lineWin();if(w){wins=w.cells;over=true;const result=w.player===1?'win':'loss';streak=result==='win'?streak+1:0;$('#log').textContent=result==='win'?'CROWN CONNECTION COMPLETE.':'GREEN EMPIRE TOOK THE BOARD.';render();await syncResult(result);if(mode==='online'&&!remote)await broadcast();return}if(!validCols().length){over=true;$('#log').textContent='DRAW — BOARD LOCKED.';render();await syncResult('draw');return}turn=turn===1?2:1;render();if(mode==='online'&&!remote)await broadcast();if(mode==='solo'&&turn===2&&!over)setTimeout(()=>void play(aiColumn(),true),260)}
function reset(){board=empty();turn=1;over=false;wins=[];history=[];powers={crown:1,swap:1};started=Date.now();$('#log').textContent='New Crown match ready.';render();if(mode==='online')void broadcast()}
function crownDrop(){if(!powers.crown||over)return;const c=Number(prompt('Choose column 1–7 for Crown Drop:'))-1;if(c<0||c>=COLS)return;history.push(clone());for(let r=0;r<ROWS;r++)board[r][c]=0;powers.crown--;void play(c)}
function royalSwap(){if(!powers.swap||over)return;for(let r=ROWS-1;r>=0;r--)for(let c=0;c<COLS;c++)if(board[r][c]===2){history.push(clone());board[r][c]=1;powers.swap--;$('#log').textContent='Royal Swap converted an exposed rival disc.';render();return}$('#log').textContent='No rival disc available.'}
function undo(){if(mode==='online'||!history.length)return;board=history.pop()!;turn=turn===1?2:1;over=false;wins=[];render()}
function saveLocal(){localStorage.setItem('rb-crown-connect-four',JSON.stringify({streak,powers,mode}))}
async function syncResult(result:string){if(!user)return;const score=result==='win'?2500+streak*250:result==='draw'?700:250,duration=Math.max(1,Math.floor((Date.now()-started)/1000));await supabase.from('game_sessions').insert({game_id:GAME_ID,game_slug:GAME,user_id:user.id,username:profile?.username,display_name:profile?.display_name,ended_at:new Date().toISOString(),duration_seconds:duration,result,score,platform_type:'web',metadata:{mode,streak,powers}});await supabase.from('game_scores').insert({game_id:GAME_ID,game_slug:GAME,user_id:user.id,username:profile?.username,display_name:profile?.display_name,score,mode,platform_type:'web',metadata:{result,streak,duration}});const{data:o}=await supabase.from('game_player_progress').select('*').eq('game_id',GAME_ID).eq('user_id',user.id).maybeSingle();const xp=Number(o?.xp||0)+(result==='win'?150:50),winCount=Number(o?.progress?.wins||0)+(result==='win'?1:0);await supabase.from('game_player_progress').upsert({game_id:GAME_ID,user_id:user.id,current_level:Math.floor(xp/600)+1,xp,best_score:Math.max(Number(o?.best_score||0),score),progress:{...(o?.progress||{}),wins:winCount,matches:Number(o?.progress?.matches||0)+1,best_streak:Math.max(Number(o?.progress?.best_streak||0),streak)},settings:o?.settings||{},inventory:o?.inventory||{},achievements:o?.achievements||[],last_checkpoint:{streak,mode},total_play_seconds:Number(o?.total_play_seconds||0)+duration,last_played_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'game_id,user_id'});await supabase.rpc('rb_award_xp',{p_event_key:result==='win'?'game_win':'game_completed',p_section:'gaming',p_source_table:'game_scores',p_source_id:null,p_amount:result==='win'?150:50});await stats()}
async function stats(){const{data:s}=await supabase.from('game_scores').select('display_name,username,score').eq('game_slug',GAME).order('score',{ascending:false}).limit(8);$('#leaders').innerHTML=(s||[]).map((x:any,i)=>`<article><b>#${i+1}</b><span>${x.display_name||x.username||'Rich Player'}</span><strong>${Number(x.score||0).toLocaleString()}</strong></article>`).join('')||'<p class="ccf-log">No ranked scores yet.</p>';if(user){const{data:p}=await supabase.from('game_player_progress').select('*').eq('game_id',GAME_ID).eq('user_id',user.id).maybeSingle();$('#xp').textContent=Number(p?.xp||0).toLocaleString();$('#best').textContent=Number(p?.best_score||0).toLocaleString();$('#wins').textContent=Number(p?.progress?.wins||0).toLocaleString()}}
async function createRoom(){if(!user)return $('#roomState').textContent='Tap In required.';const code=Math.random().toString(36).slice(2,8).toUpperCase();const{data:r,error}=await supabase.from('game_rooms').insert({room_code:code,game_key:GAME,host_user_id:user.id,status:'active',game_state:{board,turn}}).select().single();if(error)return $('#roomState').textContent=error.message;await supabase.from('game_room_members').insert({room_id:r.id,user_id:user.id,username:profile?.username,display_name:profile?.display_name,role:'host',status:'active'});room=r;$<HTMLInputElement>('#roomCode').value=code;$('#roomState').textContent=`ROOM ${code} OPEN`;subscribe()}
async function joinRoom(){if(!user)return $('#roomState').textContent='Tap In required.';const code=$<HTMLInputElement>('#roomCode').value.trim().toUpperCase();const{data:r}=await supabase.from('game_rooms').select('*').eq('room_code',code).eq('game_key',GAME).maybeSingle();if(!r)return $('#roomState').textContent='Room not found.';await supabase.from('game_room_members').insert({room_id:r.id,user_id:user.id,username:profile?.username,display_name:profile?.display_name,role:'player',status:'active'});room=r;board=(r.game_state?.board||empty()) as Cell[][];turn=r.game_state?.turn||1;$('#roomState').textContent=`JOINED ${code}`;subscribe();render()}
function subscribe(){if(channel)void supabase.removeChannel(channel);channel=supabase.channel(`${GAME}:${room.id}`).on('broadcast',{event:'state'},({payload}:any)=>{if(payload?.user===user?.id)return;board=payload.board;turn=payload.turn;over=payload.over;wins=payload.wins||[];powers=payload.powers||powers;render()}).subscribe(s=>$('#net').textContent=s==='SUBSCRIBED'?'REALTIME LIVE':s)}
async function broadcast(){if(channel)await channel.send({type:'broadcast',event:'state',payload:{user:user?.id,board,turn,over,wins,powers}})}
function leave(){if(channel)void supabase.removeChannel(channel);channel=null;room=null;$('#roomState').textContent='Left realtime room.';$('#net').textContent='OFFLINE READY'}
document.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode as Mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(mode!=='online')leave();reset()});$('#newGame').onclick=reset;$('#crownPower').onclick=crownDrop;$('#swapPower').onclick=royalSwap;$('#undo').onclick=undo;$('#createRoom').onclick=()=>void createRoom();$('#joinRoom').onclick=()=>void joinRoom();$('#leaveRoom').onclick=leave;
(async()=>{try{const s=JSON.parse(localStorage.getItem('rb-crown-connect-four')||'{}');streak=Number(s.streak||0)}catch{}const{data:{session}}=await supabase.auth.getSession();user=session?.user||null;if(user){const{data:p}=await supabase.from('profiles').select('username,display_name').eq('id',user.id).maybeSingle();profile=p}await stats();render()})();window.addEventListener('beforeunload',()=>{if(channel)void supabase.removeChannel(channel)});