import { supabase } from '../../core/supabase/client';
import './dj-radio-run.css';

type Note={lane:number,y:number,speed:number,hit:boolean};
const GAME_ID='d5610516-feca-4b78-9c8a-fdad8e58926a';
const GAME_SLUG='dj-radio-run';
const root=document.querySelector<HTMLElement>('#app');
if(!root)throw new Error('Missing #app mount');
root.innerHTML=`<main class="drr-shell"><div class="drr-wrap"><header class="drr-top"><a href="/gaming.html">←</a><div class="drr-brand"><small>RICH BIZNESS ELITE GAME 03 / 24</small><h1>DJ RADIO RUN</h1></div><span id="netState" class="drr-status">OFFLINE READY</span></header><section class="drr-hero"><div class="drr-copy"><small>RHYTHM • RUNNER • SOLO • LOCAL • REALTIME SCORE RACE</small><h2>RUN<br/>THE BEAT.</h2><p>Hit four neon lanes on rhythm, build elite combos, survive escalating speed, chase tournaments, and sync high scores and Rich XP through Gaming.</p></div><div class="drr-stats"><article><small>SCORE</small><strong id="score">0</strong></article><article><small>COMBO</small><strong id="combo">0</strong></article><article><small>BEST</small><strong id="best">0</strong></article><article><small>LIVES</small><strong id="lives">3</strong></article></div></section><section class="drr-layout"><div class="drr-stage"><canvas id="gameCanvas"></canvas><div class="drr-overlay"><span class="drr-chip" id="modeChip">SOLO</span><span class="drr-chip" id="songChip">RICH FREQUENCY 01</span></div><div class="drr-lanes">${['A','S','K','L'].map((k,i)=>`<button data-lane="${i}">${k}</button>`).join('')}</div></div><aside class="drr-side"><section class="drr-card"><h3>PLAY CONTROL</h3><select id="mode" class="drr-select"><option value="solo">SOLO RUN</option><option value="local">LOCAL SCORE DUEL</option><option value="online">ONLINE SCORE RACE</option></select><select id="difficulty" class="drr-select"><option value="1">ROOKIE BPM</option><option value="2" selected>ELITE BPM</option><option value="3">BOSS BPM</option></select><div class="drr-controls"><button id="start" class="drr-btn primary">START RUN</button><button id="pause" class="drr-btn">PAUSE</button><button id="reset" class="drr-btn">RESET</button><button id="end" class="drr-btn danger">END RUN</button></div><p id="log" class="drr-log">Tap Start Run. Use A S K L or the four touch pads.</p></section><section class="drr-card"><h3>ONLINE ROOM</h3><input id="roomCode" class="drr-input" maxlength="8" placeholder="ROOM CODE"/><div class="drr-controls"><button id="createRoom" class="drr-btn primary">CREATE</button><button id="joinRoom" class="drr-btn">JOIN</button></div><p id="roomState" class="drr-log">Tap In required for realtime score racing.</p></section><section class="drr-card"><h3>ELITE LEADERBOARD</h3><div id="leaders" class="drr-board"></div></section></aside></section><footer class="drr-footer">DJ RADIO RUN v1.0 • OFFLINE SAVE • SUPABASE REALTIME • RICH XP</footer></div></main>`;

const $=<T extends HTMLElement>(q:string)=>document.querySelector<T>(q)!;
const canvas=$<HTMLCanvasElement>('#gameCanvas');
const ctx=canvas.getContext('2d')!;
let notes:Note[]=[],running=false,paused=false,score=0,combo=0,lives=3,best=Number(localStorage.getItem('rb-dj-radio-run-best')||0),difficulty=2,mode='solo',last=0,spawn=0,started=0,user:any=null,profile:any=null,room:any=null,channel:any=null,moveNo=0,remoteScore=0;
function resize(){const r=canvas.getBoundingClientRect();canvas.width=Math.max(320,Math.floor(r.width*devicePixelRatio));canvas.height=Math.max(480,Math.floor(r.height*devicePixelRatio));ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}
function stats(){$('#score').textContent=score.toLocaleString();$('#combo').textContent=String(combo);$('#best').textContent=best.toLocaleString();$('#lives').textContent=String(lives)}
function draw(t:number){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#07130a');g.addColorStop(1,'#010201');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);for(let i=0;i<4;i++){const x=i*w/4;ctx.fillStyle=i%2?'rgba(247,201,72,.045)':'rgba(49,255,99,.045)';ctx.fillRect(x,0,w/4,h);ctx.strokeStyle='rgba(255,255,255,.08)';ctx.strokeRect(x,0,w/4,h)}ctx.fillStyle='rgba(49,255,99,.18)';ctx.fillRect(0,h-115,w,8);for(const n of notes){const x=n.lane*w/4+12,y=n.y,width=w/4-24;const ng=ctx.createLinearGradient(x,y,x+width,y+32);ng.addColorStop(0,n.lane%2?'#f7c948':'#31ff63');ng.addColorStop(1,'#ffffff');ctx.fillStyle=ng;ctx.shadowBlur=22;ctx.shadowColor=n.lane%2?'#f7c948':'#31ff63';ctx.fillRect(x,y,width,32);ctx.shadowBlur=0}ctx.fillStyle='rgba(255,255,255,.08)';for(let i=0;i<24;i++){const y=(i*48+(t*.03))%h;ctx.fillRect((i*83)%w,y,2,2)}}
function loop(t:number){if(!last)last=t;const dt=Math.min(34,t-last);last=t;if(running&&!paused){spawn+=dt;const interval=[850,620,430][difficulty-1];if(spawn>interval){spawn=0;notes.push({lane:Math.floor(Math.random()*4),y:-40,speed:[.22,.31,.42][difficulty-1],hit:false})}for(const n of notes)n.y+=n.speed*dt;const miss=notes.filter(n=>n.y>canvas.clientHeight-65);if(miss.length){lives-=miss.length;combo=0;notes=notes.filter(n=>n.y<=canvas.clientHeight-65);stats();if(lives<=0)void finish('out')}if(mode==='online'&&room&&t%500<34)void syncScore()}draw(t);requestAnimationFrame(loop)}
function hit(lane:number){if(!running||paused)return;const target=canvas.clientHeight-115;let chosen=-1,dist=999;notes.forEach((n,i)=>{if(n.lane===lane){const d=Math.abs(n.y-target);if(d<dist){dist=d;chosen=i}}});const button=document.querySelector<HTMLButtonElement>(`[data-lane="${lane}"]`);button?.classList.add('hit');setTimeout(()=>button?.classList.remove('hit'),100);if(chosen>=0&&dist<72){notes.splice(chosen,1);combo++;score+=Math.round((120-dist)*Math.max(1,combo/5)*difficulty);best=Math.max(best,score);localStorage.setItem('rb-dj-radio-run-best',String(best));$('#log').textContent=dist<20?'PERFECT DROP!':dist<42?'ELITE HIT!':'GOOD HIT';stats()}else{combo=0;score=Math.max(0,score-25);$('#log').textContent='MISS — catch the next beat.';stats()}}
function startRun(){difficulty=Number(($<HTMLSelectElement>('#difficulty')).value);mode=($<HTMLSelectElement>('#mode')).value;score=0;combo=0;lives=3;notes=[];started=Date.now();running=true;paused=false;$('#modeChip').textContent=mode.toUpperCase();$('#log').textContent='Frequency live. Run the beat.';stats()}
async function finish(result:string){if(!running)return;running=false;paused=false;const duration=Math.floor((Date.now()-started)/1000);$('#log').textContent=`RUN COMPLETE — ${score.toLocaleString()} POINTS`;if(user){await supabase.from('game_sessions').insert({game_id:GAME_ID,game_slug:GAME_SLUG,user_id:user.id,username:profile?.username,display_name:profile?.display_name,ended_at:new Date().toISOString(),duration_seconds:duration,result,score,platform_type:'web',metadata:{mode,difficulty,combo}});await supabase.from('game_scores').insert({game_id:GAME_ID,game_slug:GAME_SLUG,user_id:user.id,username:profile?.username,display_name:profile?.display_name,score,mode,platform_type:'web',metadata:{difficulty,max_combo:combo,duration}});const {data:p}=await supabase.from('game_player_progress').select('*').eq('game_id',GAME_ID).eq('user_id',user.id).maybeSingle();const gain=Math.max(25,Math.floor(score/100));await supabase.from('game_player_progress').upsert({game_id:GAME_ID,user_id:user.id,current_level:Math.floor((Number(p?.xp||0)+gain)/500)+1,xp:Number(p?.xp||0)+gain,best_score:Math.max(Number(p?.best_score||0),score),progress:{...(p?.progress||{}),runs:Number(p?.progress?.runs||0)+1,high_combo:Math.max(Number(p?.progress?.high_combo||0),combo)},settings:p?.settings||{},inventory:p?.inventory||{},achievements:p?.achievements||[],last_checkpoint:{score,combo,difficulty},total_play_seconds:Number(p?.total_play_seconds||0)+duration,last_played_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'game_id,user_id'});await supabase.rpc('rb_award_xp',{p_event_key:'game_completed',p_section:'gaming',p_source_table:'game_scores',p_source_id:null,p_amount:gain})}await leaderboard()}
async function leaderboard(){const {data}=await supabase.from('game_scores').select('display_name,username,score').eq('game_slug',GAME_SLUG).order('score',{ascending:false}).limit(8);$('#leaders').innerHTML=(data||[]).map((x:any,i)=>`<article><b>#${i+1}</b><span>${x.display_name||x.username||'Rich Player'}</span><strong>${Number(x.score||0).toLocaleString()}</strong></article>`).join('')||'<p class="drr-log">No ranked runs yet.</p>'}
async function createRoom(){if(!user)return $('#roomState').textContent='Tap In required.';const code=Math.random().toString(36).slice(2,8).toUpperCase();const {data:r,error}=await supabase.from('game_rooms').insert({room_code:code,game_key:GAME_SLUG,host_user_id:user.id,status:'active',current_turn:'race',game_state:{type:'score-race'}}).select().single();if(error)return $('#roomState').textContent=error.message;await supabase.from('game_room_members').insert({room_id:r.id,user_id:user.id,username:profile?.username,display_name:profile?.display_name,role:'host',status:'active'});room=r;($<HTMLInputElement>('#roomCode')).value=code;$('#roomState').textContent=`ROOM ${code} — LIVE SCORE RACE`;subscribe()}
async function joinRoom(){if(!user)return $('#roomState').textContent='Tap In required.';const code=($<HTMLInputElement>('#roomCode')).value.trim().toUpperCase();const {data:r}=await supabase.from('game_rooms').select('*').eq('room_code',code).eq('game_key',GAME_SLUG).maybeSingle();if(!r)return $('#roomState').textContent='Room not found.';await supabase.from('game_room_members').insert({room_id:r.id,user_id:user.id,username:profile?.username,display_name:profile?.display_name,role:'player',status:'active'});room=r;$('#roomState').textContent=`JOINED ${code} — RACE READY`;subscribe()}
function subscribe(){if(channel)void supabase.removeChannel(channel);channel=supabase.channel(`dj-radio-run:${room.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'game_moves',filter:`room_id=eq.${room.id}`},(p:any)=>{if(p.new.user_id!==user?.id){remoteScore=Number(p.new.move_data?.score||0);$('#roomState').textContent=`RIVAL ${remoteScore.toLocaleString()} • YOU ${score.toLocaleString()}`}}).subscribe();$('#netState').textContent='REALTIME LIVE'}
async function syncScore(){if(!user||!room)return;moveNo++;await supabase.from('game_moves').insert({room_id:room.id,game_key:GAME_SLUG,user_id:user.id,username:profile?.username,display_name:profile?.display_name,move_number:moveNo,move_data:{score,combo,lives},turn:'race'})}

document.querySelectorAll<HTMLButtonElement>('[data-lane]').forEach(b=>b.onclick=()=>hit(Number(b.dataset.lane)));
window.addEventListener('keydown',e=>{const map:Record<string,number>={a:0,s:1,k:2,l:3,ArrowLeft:0,ArrowDown:1,ArrowUp:2,ArrowRight:3};if(map[e.key]!==undefined){e.preventDefault();hit(map[e.key])}});
$('#start').onclick=startRun;$('#pause').onclick=()=>{if(running){paused=!paused;$('#pause').textContent=paused?'RESUME':'PAUSE'}};$('#reset').onclick=startRun;$('#end').onclick=()=>void finish('ended');$('#createRoom').onclick=()=>void createRoom();$('#joinRoom').onclick=()=>void joinRoom();
window.addEventListener('resize',resize);window.addEventListener('beforeunload',()=>{if(channel)void supabase.removeChannel(channel)});
resize();stats();requestAnimationFrame(loop);
void (async()=>{const {data:{session}}=await supabase.auth.getSession();user=session?.user||null;if(user){const {data}=await supabase.from('profiles').select('username,display_name').eq('id',user.id).maybeSingle();profile=data;$('#netState').textContent='SYNC READY'}await leaderboard()})();
