import { supabase } from '../../core/supabase/client';
import './market-flip.css';

type Asset={key:string;name:string;sector:string;base:number;vol:number;trend:number;price:number;history:number[]};
const GAME_ID='50e0fe54-a6c2-40c6-ba09-20ee45771241';
const assets:Asset[]=[
 {key:'smoke',name:'SMOKE TECH',sector:'TECH',base:120,vol:.09,trend:.012,price:120,history:[]},
 {key:'gold',name:'RICH GOLD',sector:'COMMODITY',base:88,vol:.055,trend:.008,price:88,history:[]},
 {key:'beats',name:'BIZ BEATS',sector:'MEDIA',base:64,vol:.13,trend:.018,price:64,history:[]},
 {key:'meta',name:'META LAND',sector:'VIRTUAL',base:150,vol:.16,trend:.01,price:150,history:[]},
 {key:'sport',name:'ARENA SHARES',sector:'SPORTS',base:73,vol:.1,trend:.006,price:73,history:[]},
 {key:'store',name:'RICH RETAIL',sector:'COMMERCE',base:102,vol:.07,trend:.009,price:102,history:[]}
];
let selected=assets[0],cash=10000,day=1,score=0,streak=0,best=0,mode='campaign',difficulty=2,running=false,tick=0,marketTimer=0,user:any=null,profile:any=null,room:any=null,channel:any=null,started=Date.now();
let holdings:Record<string,{qty:number;avg:number}>={},unlocked=new Set<string>(),intel=0;
const app=document.querySelector<HTMLElement>('#app')!;
app.innerHTML=`<main class="mf-shell"><div class="mf-wrap"><header class="mf-top"><a href="/gaming.html">← GAMING</a><div class="mf-brand"><small>ELITE STRATEGY 03 / 05</small><h1>MARKET FLIP</h1></div><span class="mf-status" id="net">OFFLINE READY</span></header><section class="mf-hero"><div><small class="mf-kicker">LIVE PRICE ENGINE • AI RIVALS • PORTFOLIO CONTROL • REALTIME • OFFLINE</small><h2>BUY LOW.<br>RULE HIGH.</h2><p>Advanced controllable market strategy with six volatile sectors, trend cycles, breaking events, leverage risk, portfolio upgrades, AI rivals, realtime score rooms and persistent Rich XP.</p></div><div class="mf-stats"><article><small>NET WORTH</small><strong id="worth">$10,000</strong></article><article><small>DAY</small><strong id="day">1</strong></article><article><small>SCORE</small><strong id="score">0</strong></article><article><small>STREAK</small><strong id="streak">0</strong></article></div></section><section class="mf-grid"><div class="mf-market"><div class="mf-tape" id="tape"></div><div class="mf-chart"><canvas id="chart"></canvas><div class="mf-overlay"><div><small id="sector">TECH</small><strong id="symbol">SMOKE TECH</strong></div><strong id="price">$120.00</strong></div></div><div class="mf-order"><button class="mf-btn" id="buy1">BUY 1</button><button class="mf-btn" id="buy5">BUY 5</button><button class="mf-btn danger" id="sell1">SELL 1</button><button class="mf-btn danger" id="sellAll">SELL ALL</button><button class="mf-btn primary" id="next">NEXT DAY</button></div></div><aside class="mf-side"><section class="mf-card"><h3>MARKET COMMAND</h3><select class="mf-select" id="mode"><option value="campaign">30-DAY CAMPAIGN</option><option value="survival">MARKET SURVIVAL</option><option value="local">LOCAL CAPITAL DUEL</option><option value="online">ONLINE RANKED</option></select><select class="mf-select" id="difficulty"><option value="1">ROOKIE RIVALS</option><option value="2" selected>ELITE RIVALS</option><option value="3">BOSS MARKET</option></select><button class="mf-btn primary" id="start">START MARKET</button><p class="mf-log" id="log">Build your portfolio and beat the market.</p></section><section class="mf-card"><h3>PORTFOLIO</h3><div class="mf-portfolio" id="portfolio"></div></section><section class="mf-card"><h3>TRADER UPGRADES</h3><div id="upgrades"></div><p class="mf-log">Intel points: <b id="intel">0</b></p></section><section class="mf-card"><h3>REALTIME EXCHANGE</h3><input class="mf-input" id="roomCode" maxlength="8" placeholder="ROOM CODE"/><div class="mf-order"><button class="mf-btn primary" id="createRoom">CREATE</button><button class="mf-btn" id="joinRoom">JOIN</button></div><p class="mf-log" id="roomState">Tap In required for ranked rooms.</p></section><section class="mf-card"><h3>ELITE LEADERBOARD</h3><div class="mf-leaders" id="leaders"></div></section></aside></section></div></main>`;
const $=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const toast=(t:string)=>{const e=document.createElement('div');e.className='mf-toast';e.textContent=t;document.body.append(e);setTimeout(()=>e.remove(),1350)};
function worth(){return cash+assets.reduce((n,a)=>n+(holdings[a.key]?.qty||0)*a.price,0)}
function renderTape(){ $('#tape').innerHTML=assets.map(a=>{const old=a.history.at(-2)||a.price;const pct=(a.price-old)/old*100;return `<button class="mf-ticker ${a===selected?'active':''}" data-asset="${a.key}"><b>${a.name}</b><small>${money(a.price)} <span class="${pct>=0?'up':'down'}">${pct>=0?'+':''}${pct.toFixed(1)}%</span></small></button>`}).join('');document.querySelectorAll<HTMLButtonElement>('[data-asset]').forEach(b=>b.onclick=()=>{selected=assets.find(a=>a.key===b.dataset.asset)||assets[0];render()})}
function renderPortfolio(){const rows=assets.filter(a=>holdings[a.key]?.qty).map(a=>{const h=holdings[a.key],p=(a.price-h.avg)*h.qty;return `<div class="mf-holding"><span><b>${a.name}</b><small>${h.qty} @ ${money(h.avg)}</small></span><strong>${money(a.price*h.qty)}</strong><b class="${p>=0?'up':'down'}">${p>=0?'+':''}${money(p)}</b></div>`});$('#portfolio').innerHTML=rows.join('')||'<p class="mf-log">No positions. Choose an asset and buy.</p>'}
function renderUpgrades(){const list:[string,string,number][]=[['scanner','TREND SCANNER',2],['fees','ZERO-FEE DESK',3],['hedge','RISK HEDGE',4],['insider','ELITE SIGNAL',6]];$('#upgrades').innerHTML=list.map(([k,n,c])=>`<div class="mf-row"><span><b>${n}</b><small>${unlocked.has(k)?'UNLOCKED':`${c} INTEL`}</small></span><button class="mf-btn" data-upgrade="${k}" data-cost="${c}" ${unlocked.has(k)?'disabled':''}>${unlocked.has(k)?'✓':'UNLOCK'}</button></div>`).join('');$('#intel').textContent=String(intel);document.querySelectorAll<HTMLButtonElement>('[data-upgrade]').forEach(b=>b.onclick=()=>{const c=Number(b.dataset.cost);if(intel<c)return toast('MORE INTEL REQUIRED');intel-=c;unlocked.add(b.dataset.upgrade!);save();renderUpgrades()})}
function draw(){const canvas=$<HTMLCanvasElement>('#chart'),ctx=canvas.getContext('2d')!,r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,2);canvas.width=r.width*dpr;canvas.height=r.height*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,r.width,r.height);ctx.strokeStyle='rgba(255,255,255,.08)';ctx.lineWidth=1;for(let i=1;i<6;i++){ctx.beginPath();ctx.moveTo(0,r.height*i/6);ctx.lineTo(r.width,r.height*i/6);ctx.stroke()}const h=selected.history.slice(-60);if(h.length<2)return;const min=Math.min(...h)*.96,max=Math.max(...h)*1.04;ctx.beginPath();h.forEach((v,i)=>{const x=i/(h.length-1)*r.width,y=r.height-(v-min)/(max-min||1)*r.height;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});const grad=ctx.createLinearGradient(0,0,r.width,0);grad.addColorStop(0,'#31ff63');grad.addColorStop(1,'#f7c948');ctx.strokeStyle=grad;ctx.lineWidth=4;ctx.shadowColor='#31ff63';ctx.shadowBlur=16;ctx.stroke()}
function render(){renderTape();renderPortfolio();$('#symbol').textContent=selected.name;$('#sector').textContent=selected.sector;$('#price').textContent=`$${selected.price.toFixed(2)}`;$('#worth').textContent=money(worth());$('#day').textContent=String(day);$('#score').textContent=Math.round(score).toLocaleString();$('#streak').textContent=String(streak);draw()}
function evolve(){tick++;assets.forEach((a,i)=>{const cycle=Math.sin((tick+i*3)/7)*a.vol*.45;const shock=(Math.random()-.5)*a.vol*(difficulty*.75);const signal=unlocked.has('insider')&&a===selected?.006:0;a.price=Math.max(4,a.price*(1+a.trend+cycle+shock+signal));a.history.push(a.price);if(a.history.length>100)a.history.shift()});if(Math.random()<.18){const a=assets[Math.floor(Math.random()*assets.length)],boost=Math.random()>.48?1:-1;a.price*=1+boost*(.08+Math.random()*.16);$('#log').textContent=`BREAKING: ${a.name} ${boost>0?'SURGES':'SELLS OFF'} after a major market event.`}score=Math.max(score,worth()-10000+day*80);render();if(mode==='online'&&room)void sendState()}
function trade(qty:number){if(!running)return toast('START THE MARKET');const fee=unlocked.has('fees')?0:Math.max(2,Math.abs(qty)*selected.price*.005);const h=holdings[selected.key]||{qty:0,avg:0};if(qty>0){const cost=selected.price*qty+fee;if(cost>cash)return toast('NOT ENOUGH CASH');h.avg=(h.avg*h.qty+selected.price*qty)/(h.qty+qty);h.qty+=qty;cash-=cost}else{const sell=Math.min(h.qty,Math.abs(qty));if(!sell)return toast('NO POSITION');const pnl=(selected.price-h.avg)*sell;cash+=selected.price*sell-fee;h.qty-=sell;streak=pnl>0?streak+1:0;if(pnl>0){intel+=pnl>500?2:1;score+=pnl*2}}holdings[selected.key]=h;save();render();renderUpgrades()}
function start(){mode=($<HTMLSelectElement>('#mode')).value;difficulty=Number(($<HTMLSelectElement>('#difficulty')).value);running=true;started=Date.now();$('#log').textContent=`${mode.toUpperCase()} OPEN • OUTPERFORM THE RIVALS`;clearInterval(marketTimer);marketTimer=window.setInterval(()=>{if(running)evolve()},1700-difficulty*220);render()}
async function nextDay(){if(!running)return;day++;for(let i=0;i<3+difficulty;i++)evolve();if(day>30&&mode==='campaign')await finish();save()}
async function finish(){running=false;clearInterval(marketTimer);const net=worth(),won=net>=16000+difficulty*3500,points=Math.max(250,Math.round(net-7000+score));best=Math.max(best,points);$('#log').textContent=`${won?'MARKET DOMINATED':'MARKET CLOSED'} • ${money(net)} NET WORTH`;toast(won?'EMPIRE PROFITS':'REGROUP AND REBUILD');save();if(user)await persist(points,won)}
async function persist(points:number,won:boolean){const duration=Math.floor((Date.now()-started)/1000);await supabase.from('game_sessions').insert({game_id:GAME_ID,game_slug:'market-flip',user_id:user.id,username:profile?.username,display_name:profile?.display_name,ended_at:new Date().toISOString(),duration_seconds:duration,result:won?'VICTORY':'COMPLETE',score:points,platform_type:'web',metadata:{mode,day,net_worth:worth(),streak}});await supabase.from('game_scores').insert({game_id:GAME_ID,game_slug:'market-flip',user_id:user.id,username:profile?.username,display_name:profile?.display_name,score:points,mode,platform_type:'web',metadata:{day,net_worth:worth(),streak}});const {data:o}=await supabase.from('game_player_progress').select('*').eq('game_id',GAME_ID).eq('user_id',user.id).maybeSingle();const xp=Number(o?.xp||0)+(won?220:80);await supabase.from('game_player_progress').upsert({game_id:GAME_ID,user_id:user.id,current_level:Math.floor(xp/700)+1,xp,best_score:Math.max(Number(o?.best_score||0),points),progress:{...(o?.progress||{}),runs:Number(o?.progress?.runs||0)+1,wins:Number(o?.progress?.wins||0)+(won?1:0),best_worth:Math.max(Number(o?.progress?.best_worth||0),worth())},settings:o?.settings||{},inventory:{unlocked:[...unlocked],intel},achievements:o?.achievements||[],last_checkpoint:{day,cash,holdings,unlocked:[...unlocked],intel},total_play_seconds:Number(o?.total_play_seconds||0)+duration,last_played_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'game_id,user_id'});await supabase.rpc('rb_award_xp',{p_event_key:won?'game_win':'game_completed',p_section:'gaming',p_source_table:'game_scores',p_source_id:null,p_amount:won?220:80});await loadLeaders()}
function save(){localStorage.setItem('rb-market-flip',JSON.stringify({cash,day,score,streak,best,holdings,unlocked:[...unlocked],intel,prices:Object.fromEntries(assets.map(a=>[a.key,a.price]))}))}
function restore(){try{const s=JSON.parse(localStorage.getItem('rb-market-flip')||'{}');cash=Number(s.cash||10000);day=Number(s.day||1);score=Number(s.score||0);streak=Number(s.streak||0);best=Number(s.best||0);holdings=s.holdings||{};unlocked=new Set(s.unlocked||[]);intel=Number(s.intel||0);assets.forEach(a=>{a.price=Number(s.prices?.[a.key]||a.base);a.history=Array.from({length:30},(_,i)=>a.price*(.9+i/300+Math.sin(i/4)*.03))})}catch{}renderUpgrades();render()}
async function loadLeaders(){const {data}=await supabase.from('game_scores').select('display_name,username,score').eq('game_slug','market-flip').order('score',{ascending:false}).limit(8);$('#leaders').innerHTML=(data||[]).map((x:any,i)=>`<article><b>#${i+1}</b><span>${x.display_name||x.username||'Rich Trader'}</span><strong>${Number(x.score||0).toLocaleString()}</strong></article>`).join('')||'<p class="mf-log">First elite trader sets the board.</p>'}
async function createRoom(){if(!user)return $('#roomState').textContent='Tap In required.';const code=Math.random().toString(36).slice(2,8).toUpperCase();const {data:r,error}=await supabase.from('game_rooms').insert({game_key:'market-flip',room_code:code,host_user_id:user.id,status:'waiting',mode:'ranked',max_players:2,metadata:{day,cash}}).select().single();if(error||!r)return $('#roomState').textContent='Room creation failed.';await supabase.from('game_room_members').insert({room_id:r.id,user_id:user.id,username:profile?.username,display_name:profile?.display_name,role:'host',status:'active'});room={...r,role:'host'};($<HTMLInputElement>('#roomCode')).value=code;$('#roomState').textContent=`ROOM ${code} READY`;subscribe()}
async function joinRoom(){if(!user)return $('#roomState').textContent='Tap In required.';const code=($<HTMLInputElement>('#roomCode')).value.trim().toUpperCase();const {data:r}=await supabase.from('game_rooms').select('*').eq('room_code',code).eq('game_key','market-flip').maybeSingle();if(!r)return $('#roomState').textContent='Room not found.';await supabase.from('game_room_members').insert({room_id:r.id,user_id:user.id,username:profile?.username,display_name:profile?.display_name,role:'guest',status:'active'});room={...r,role:'guest'};mode='online';$('#roomState').textContent=`JOINED ${code}`;subscribe();start()}
function subscribe(){if(channel)void supabase.removeChannel(channel);channel=supabase.channel(`market-flip:${room.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'game_moves',filter:`room_id=eq.${room.id}`},(p:any)=>{if(p.new.user_id===user?.id)return;const rival=p.new.move_data||{};$('#roomState').textContent=`RIVAL ${money(Number(rival.worth||0))} • DAY ${rival.day||1}`}).subscribe(s=>$('#net').textContent=s==='SUBSCRIBED'?'REALTIME READY':'SYNCING')}
async function sendState(){if(!room||!user)return;await supabase.from('game_moves').insert({room_id:room.id,game_key:'market-flip',user_id:user.id,username:profile?.username,display_name:profile?.display_name,move_number:Date.now(),move_data:{worth:worth(),day,score},turn:room.role,metadata:{mode}})}
async function boot(){restore();const {data:{user:u}}=await supabase.auth.getUser();user=u;if(user){const {data:p}=await supabase.from('profiles').select('username,display_name').eq('id',user.id).maybeSingle();profile=p;$('#net').textContent='SIGNED IN'}await loadLeaders();window.addEventListener('resize',draw)}
$('#buy1').onclick=()=>trade(1);$('#buy5').onclick=()=>trade(5);$('#sell1').onclick=()=>trade(-1);$('#sellAll').onclick=()=>trade(-(holdings[selected.key]?.qty||0));$('#next').onclick=()=>void nextDay();$('#start').onclick=start;$('#createRoom').onclick=()=>void createRoom();$('#joinRoom').onclick=()=>void joinRoom();window.addEventListener('keydown',e=>{const map:Record<string,()=>void>={b:()=>trade(1),B:()=>trade(5),s:()=>trade(-1),n:()=>void nextDay(),ArrowRight:()=>{selected=assets[(assets.indexOf(selected)+1)%assets.length];render()},ArrowLeft:()=>{selected=assets[(assets.indexOf(selected)-1+assets.length)%assets.length];render()}};if(map[e.key]){e.preventDefault();map[e.key]()}});window.addEventListener('beforeunload',()=>{clearInterval(marketTimer);if(channel)void supabase.removeChannel(channel)});void boot();