import { supabase } from '../../core/supabase/client';
import './money-road-runner.css';

type Kind='cash'|'car'|'boost'|'barrier'|'magnet';
type ObjectRow={lane:number;y:number;kind:Kind;size:number;spin:number};
const SLUG='money-road-runner';
const root=document.querySelector<HTMLElement>('#app')!;
root.dataset.gameOwner='money-road-runner-v4';
root.innerHTML=`<main class="mrr-shell"><div class="mrr-wrap">
<header class="mrr-top"><a href="/gaming.html" aria-label="Back to Gaming">←</a><div><small>RICH BIZNESS ELITE GAME 14 / 28</small><h1>MONEY ROAD RUNNER</h1></div><span id="net" class="mrr-pill">OFFLINE READY</span></header>
<section class="mrr-hero"><div><small>ENDLESS RUNNER • SCORE RACE • OFFLINE • REALTIME</small><h2>OWN THE<br>MONEY ROAD.</h2><p>Switch lanes, jump traffic, slide barriers, chain cash streaks, trigger Rich Rush and outrun the city.</p></div><div class="mrr-stats"><article><small>SCORE</small><strong id="score">0</strong></article><article><small>BEST</small><strong id="best">0</strong></article><article><small>COMBO</small><strong id="combo">x1</strong></article><article><small>RICH RUSH</small><strong id="rush">0%</strong></article><article><small>DISTANCE</small><strong id="distance">0m</strong></article><article><small>RIVAL</small><strong id="rival">0</strong></article></div></section>
<section class="mrr-grid"><div class="mrr-stage"><canvas id="game" aria-label="Money Road Runner game"></canvas><div class="mrr-hud"><span id="lives">♥♥♥</span><span id="speed">1.0X</span><span id="mission">COLLECT 20 CASH</span></div><div id="countdown" class="mrr-countdown" hidden></div><div class="mrr-mobile"><button class="mrr-btn" data-a="left">←</button><button class="mrr-btn" data-a="jump">↑</button><button class="mrr-btn" data-a="slide">↓</button><button class="mrr-btn" data-a="right">→</button></div></div>
<aside class="mrr-side"><section class="mrr-card"><h3>RUN CONTROL</h3><select id="difficulty" class="mrr-select"><option value="1">ROOKIE STREET</option><option value="2" selected>ELITE CITY</option><option value="3">BOSS HIGHWAY</option></select><div class="mrr-controls"><button id="start" class="mrr-btn primary">START RUN</button><button id="pause" class="mrr-btn">PAUSE</button><button id="local" class="mrr-btn">LOCAL CHALLENGE</button><button id="end" class="mrr-btn danger">END RUN</button></div><p id="log" class="mrr-log">Arrows, WASD, swipe or touch controls.</p></section><section class="mrr-card"><h3>ONLINE SCORE RACE</h3><input id="roomCode" class="mrr-input" maxlength="8" placeholder="ROOM CODE"><div class="mrr-controls"><button id="createRoom" class="mrr-btn primary">CREATE</button><button id="joinRoom" class="mrr-btn">JOIN</button></div><p id="roomState" class="mrr-log">Tap In required for realtime score races.</p></section><section class="mrr-card"><h3>LEADERBOARD</h3><div id="leaders" class="mrr-board"></div></section></aside></section>
</div></main>`;
const $=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
const canvas=$<HTMLCanvasElement>('#game'); const ctx=canvas.getContext('2d')!;
let lane=1,objects:ObjectRow[]=[],running=false,paused=false,jump=0,slide=0,score=0,combo=1,lives=3,speed=8,spawn=0,last=0,user:any=null,sessionKey:string|null=null,startAt=0,room:any=null,channel:any=null,rival=0,rush=0,distance=0,cashCount=0,invincible=0,magnet=0,localTarget=0,swipeX=0,swipeY=0;
const best=()=>Number(localStorage.getItem('rb-mrr-best')||0);
function size(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,r.width*d);canvas.height=Math.max(1,r.height*d);ctx.setTransform(d,0,0,d,0,0)}
function hud(){$('#score').textContent=Math.floor(score).toLocaleString();$('#best').textContent=best().toLocaleString();$('#combo').textContent=`x${combo}`;$('#rush').textContent=`${Math.floor(rush)}%`;$('#distance').textContent=`${Math.floor(distance)}m`;$('#lives').textContent='♥'.repeat(lives)+'♡'.repeat(3-lives);$('#speed').textContent=`${(speed/8).toFixed(1)}X`;$('#rival').textContent=Math.floor(rival).toLocaleString();$('#mission').textContent=cashCount<20?`COLLECT ${20-cashCount} CASH`:'MISSION COMPLETE'}
function reset(){lane=1;objects=[];jump=slide=score=rush=distance=cashCount=invincible=magnet=0;combo=1;lives=3;speed=7+Number($<HTMLSelectElement>('#difficulty').value)*1.5;startAt=Date.now();hud()}
const laneX=(l:number,y:number,w:number,h:number)=>w/2+(l-1)*(w*.17+w*.11*y/h);
function road(w:number,h:number,t:number){const sky=ctx.createLinearGradient(0,0,0,h);sky.addColorStop(0,'#071d0b');sky.addColorStop(.45,'#041007');sky.addColorStop(1,'#010201');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);ctx.fillStyle='rgba(247,201,72,.08)';for(let i=0;i<18;i++){const px=(i*137+t*.02)%w;ctx.fillRect(px,70+(i%4)*24,2,70)}ctx.fillStyle='#111612';ctx.beginPath();ctx.moveTo(w*.34,0);ctx.lineTo(w*.66,0);ctx.lineTo(w*.98,h);ctx.lineTo(w*.02,h);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(247,201,72,.58)';ctx.lineWidth=3;ctx.stroke();ctx.setLineDash([18,22]);ctx.lineDashOffset=-(t*.12)%40;ctx.strokeStyle='rgba(255,255,255,.24)';for(let i=1;i<3;i++){ctx.beginPath();ctx.moveTo(w*(.34+.16*i),0);ctx.lineTo(w*(.02+.96*i/3),h);ctx.stroke()}ctx.setLineDash([])}
function drawObject(o:ObjectRow,w:number,h:number){const s=o.size+o.y/h*44,px=laneX(o.lane,o.y,w,h);ctx.save();ctx.translate(px,o.y);ctx.rotate(o.spin);ctx.shadowBlur=18;ctx.shadowColor=o.kind==='cash'?'#f7c948':o.kind==='boost'||o.kind==='magnet'?'#31ff63':'#ff485d';ctx.fillStyle=o.kind==='cash'?'#f7c948':o.kind==='boost'?'#31ff63':o.kind==='magnet'?'#67e8f9':o.kind==='barrier'?'#f59e0b':'#d93645';ctx.fillRect(-s/2,-s/2,s,s);ctx.shadowBlur=0;ctx.fillStyle='#031006';ctx.font=`900 ${s*.48}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(o.kind==='cash'?'$':o.kind==='boost'?'⚡':o.kind==='magnet'?'◎':o.kind==='barrier'?'▰':'◆',0,0);ctx.restore()}
function draw(t=performance.now()){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);road(w,h,t);objects.forEach(o=>drawObject(o,w,h));const py=h*.83-jump,px=laneX(lane,h*.83,w,h);ctx.save();ctx.translate(px,py);ctx.shadowColor=invincible>0?'#f7c948':'#31ff63';ctx.shadowBlur=28;ctx.fillStyle=invincible>0?'#f7c948':'#31ff63';ctx.fillRect(-25,-(slide?15:68),50,slide?28:68);ctx.fillStyle='#031006';ctx.fillRect(-13,-(slide?9:54),26,18);ctx.restore();if(!running){ctx.fillStyle='rgba(0,0,0,.58)';ctx.fillRect(0,0,w,h);ctx.fillStyle='#fff';ctx.font='900 30px system-ui';ctx.textAlign='center';ctx.fillText('MONEY ROAD RUNNER',w/2,h*.44);ctx.fillStyle='#f7c948';ctx.font='800 14px system-ui';ctx.fillText(localTarget?`BEAT ${localTarget.toLocaleString()}`:'PRESS START RUN',w/2,h*.5)}}
function act(a:string){if(a==='left')lane=Math.max(0,lane-1);if(a==='right')lane=Math.min(2,lane+1);if(a==='jump'&&jump<2)jump=96;if(a==='slide')slide=520}
function spawnObject(){const r=Math.random(),difficulty=Number($<HTMLSelectElement>('#difficulty').value);const kind:Kind=r<.46?'cash':r<.60?'boost':r<.69?'magnet':r<.83+(difficulty-1)*.03?'barrier':'car';objects.push({lane:Math.floor(Math.random()*3),y:-40,kind,size:22,spin:0})}
async function startRun(local=false){reset();localTarget=local?best():0;running=true;paused=false;$('#pause').textContent='PAUSE';$('#log').textContent=local?`Beat ${localTarget.toLocaleString()} points.`:'Run live.';if(user){const {data,error}=await supabase.rpc('rb_game_action',{p_action:'start_session',p_game_slug:SLUG,p_payload:{platform_type:'web',device_info:{mobile:matchMedia('(max-width:760px)').matches},metadata:{difficulty:Number($<HTMLSelectElement>('#difficulty').value),mode:room?'online':local?'local':'solo'}}});if(!error)sessionKey=String((data as any)?.session_key||'')||null}}
function hit(o:ObjectRow){if(o.kind==='cash'){score+=120*combo;combo=Math.min(20,combo+1);rush=Math.min(100,rush+9);cashCount++;return}if(o.kind==='boost'){score+=300*combo;speed=Math.min(23,speed+1.8);rush=Math.min(100,rush+18);combo=Math.min(20,combo+2);return}if(o.kind==='magnet'){magnet=6000;score+=180;return}const safe=o.kind==='car'?jump>40:o.kind==='barrier'?slide>0:false;if(safe){score+=90*combo;combo=Math.min(20,combo+1);return}if(invincible>0)return;lives--;combo=1;rush=Math.max(0,rush-30);speed=Math.max(7,speed-1.4);invincible=1300}
function loop(t:number){const dt=Math.min(34,t-last||16);last=t;if(running&&!paused){spawn+=dt;distance+=dt*speed*.006;invincible=Math.max(0,invincible-dt);magnet=Math.max(0,magnet-dt);if(rush>=100){invincible=Math.max(invincible,3500);speed=Math.min(24,speed+2);rush=0;$('#log').textContent='RICH RUSH ACTIVATED.'}if(spawn>Math.max(250,820-speed*23)){spawn=0;spawnObject()}jump=Math.max(0,jump-dt*.29);slide=Math.max(0,slide-dt);score+=dt*.02*speed*combo;objects.forEach(o=>{o.y+=speed*dt*.092;o.spin+=dt*.0018;if(magnet>0&&o.kind==='cash'&&o.y>canvas.clientHeight*.25)o.lane=lane});objects=objects.filter(o=>{if(o.y>canvas.clientHeight*.72&&o.y<canvas.clientHeight*.93&&o.lane===lane){hit(o);return false}return o.y<canvas.clientHeight+80});speed=Math.min(23,speed+dt*.00095);if(room&&Math.floor(score)%350<5)void syncRoom();if(lives<=0)void finish('crash');hud()}draw(t);requestAnimationFrame(loop)}
async function finish(result:string){if(!running)return;running=false;const final=Math.floor(score),duration=Math.max(1,Math.floor((Date.now()-startAt)/1000)),xp=Math.max(35,Math.min(300,Math.floor(final/220)));localStorage.setItem('rb-mrr-best',String(Math.max(best(),final)));if(user&&sessionKey){await supabase.rpc('rb_game_action',{p_action:'finish_session',p_game_slug:SLUG,p_payload:{session_key:sessionKey,score:final,duration_seconds:duration,result,xp,mode:room?'online':localTarget?'local':'solo',platform_type:'web',metadata:{combo,cash_count:cashCount,distance:Math.floor(distance),difficulty:Number($<HTMLSelectElement>('#difficulty').value)}}});sessionKey=null}$('#log').textContent=`Run complete — ${final.toLocaleString()} points · ${Math.floor(distance)}m.`;await leaders();hud()}
async function leaders(){const {data}=await supabase.from('game_scores').select('display_name,username,score').eq('game_slug',SLUG).order('score',{ascending:false}).limit(8);$('#leaders').innerHTML=(data||[]).map((v:any,i)=>`<article><b>#${i+1}</b><span>${v.display_name||v.username||'Rich Runner'}</span><strong>${Number(v.score||0).toLocaleString()}</strong></article>`).join('')||'<p class="mrr-log">No ranked runs yet.</p>'}
async function makeRoom(){if(!user)return $('#roomState').textContent='Tap In required.';const code=Math.random().toString(36).slice(2,8).toUpperCase();const {data,error}=await supabase.from('game_rooms').insert({room_code:code,game_key:SLUG,host_user_id:user.id,status:'active',game_state:{scores:{[user.id]:0}}}).select().single();if(error)return $('#roomState').textContent=error.message;room=data;$<HTMLInputElement>('#roomCode').value=code;watchRoom();$('#roomState').textContent=`ROOM ${code} READY`}
async function joinRoom(){if(!user)return $('#roomState').textContent='Tap In required.';const code=$<HTMLInputElement>('#roomCode').value.trim().toUpperCase();const {data}=await supabase.from('game_rooms').select('*').eq('room_code',code).eq('game_key',SLUG).maybeSingle();if(!data)return $('#roomState').textContent='Room not found.';room=data;watchRoom();$('#roomState').textContent=`JOINED ${code}`}
function watchRoom(){if(channel)void supabase.removeChannel(channel);channel=supabase.channel(`mrr:${room.id}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'game_rooms',filter:`id=eq.${room.id}`},(p:any)=>{const scores=p.new?.game_state?.scores||{};rival=Math.max(0,...Object.entries(scores).filter(([id])=>id!==user?.id).map(([,v])=>Number(v||0)));hud()}).subscribe();$('#net').textContent='REALTIME RACE'}
async function syncRoom(){if(!room||!user)return;const {data}=await supabase.from('game_rooms').select('game_state').eq('id',room.id).single();await supabase.from('game_rooms').update({game_state:{...(data?.game_state||{}),scores:{...(data?.game_state?.scores||{}),[user.id]:Math.floor(score)}}}).eq('id',room.id)}
$('#start').onclick=()=>void startRun(false);$('#pause').onclick=()=>{paused=!paused;$('#pause').textContent=paused?'RESUME':'PAUSE'};$('#local').onclick=()=>void startRun(true);$('#end').onclick=()=>void finish('ended');$('#createRoom').onclick=()=>void makeRoom();$('#joinRoom').onclick=()=>void joinRoom();document.querySelectorAll<HTMLButtonElement>('[data-a]').forEach(b=>{b.onclick=()=>act(String(b.dataset.a));b.onpointerdown=e=>{e.preventDefault();act(String(b.dataset.a))}});addEventListener('keydown',e=>{if(['ArrowLeft','a','A'].includes(e.key))act('left');if(['ArrowRight','d','D'].includes(e.key))act('right');if(['ArrowUp','w','W',' '].includes(e.key))act('jump');if(['ArrowDown','s','S'].includes(e.key))act('slide')});canvas.addEventListener('pointerdown',e=>{swipeX=e.clientX;swipeY=e.clientY});canvas.addEventListener('pointerup',e=>{const dx=e.clientX-swipeX,dy=e.clientY-swipeY;if(Math.abs(dx)>Math.abs(dy)&&Math.abs(dx)>28)act(dx>0?'right':'left');else if(Math.abs(dy)>28)act(dy<0?'jump':'slide')});addEventListener('resize',size);addEventListener('pagehide',()=>{if(channel)void supabase.removeChannel(channel);if(running)void finish('exit')},{once:true});size();requestAnimationFrame(loop);void(async()=>{const {data:{session}}=await supabase.auth.getSession();user=session?.user||null;$('#net').textContent=user?'RICH ID SYNC':'OFFLINE READY';await leaders();hud()})();