import { supabase } from '../../core/supabase/client';
import './money-road-runner.css';

type O={lane:number,y:number,type:'cash'|'car'|'boost'};
const GAME='9cc35fe3-647a-4b53-a649-ccdb85c66d04';
const root=document.querySelector<HTMLElement>('#app')!;
root.innerHTML=`<main class="mrr-shell"><div class="mrr-wrap"><header class="mrr-top"><a href="/gaming.html">←</a><div><small>ELITE GAME 04 / 24</small><h1>MONEY ROAD RUNNER</h1></div><span id="net" class="mrr-pill">OFFLINE READY</span></header><section class="mrr-hero"><div><small>SOLO • LOCAL • REALTIME • OFFLINE</small><h2>RUN THE<br>MONEY ROAD.</h2><p>Dodge traffic, collect cash, chain combos and race for Rich XP.</p></div><div class="mrr-stats"><article><small>SCORE</small><strong id="score">0</strong></article><article><small>BEST</small><strong id="best">0</strong></article><article><small>COMBO</small><strong id="combo">x1</strong></article><article><small>RIVAL</small><strong id="rival">0</strong></article></div></section><section class="mrr-grid"><div class="mrr-stage"><canvas id="game"></canvas><div class="mrr-hud"><span id="lives">♥♥♥</span><span id="speed">1.0X</span></div><div class="mrr-mobile"><button class="mrr-btn" data-a="left">←</button><button class="mrr-btn" data-a="jump">↑</button><button class="mrr-btn" data-a="slide">↓</button><button class="mrr-btn" data-a="right">→</button></div></div><aside class="mrr-side"><section class="mrr-card"><h3>RUN CONTROL</h3><select id="difficulty" class="mrr-select"><option value="1">ROOKIE STREET</option><option value="2" selected>ELITE CITY</option><option value="3">BOSS HIGHWAY</option></select><div class="mrr-controls"><button id="start" class="mrr-btn primary">START RUN</button><button id="pause" class="mrr-btn">PAUSE</button><button id="local" class="mrr-btn">LOCAL CHALLENGE</button><button id="end" class="mrr-btn danger">END RUN</button></div><p id="log" class="mrr-log">Use arrows, WASD or touch.</p></section><section class="mrr-card"><h3>ONLINE SCORE RACE</h3><input id="roomCode" class="mrr-input" maxlength="8" placeholder="ROOM CODE"><div class="mrr-controls"><button id="createRoom" class="mrr-btn primary">CREATE</button><button id="joinRoom" class="mrr-btn">JOIN</button></div><p id="roomState" class="mrr-log">Tap In required.</p></section><section class="mrr-card"><h3>LEADERBOARD</h3><div id="leaders" class="mrr-board"></div></section></aside></section></div></main>`;
const $=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
const c=$<HTMLCanvasElement>('#game'),x=c.getContext('2d')!;
let lane=1,items:O[]=[],run=false,pause=false,jump=0,slide=0,score=0,combo=1,lives=3,speed=7,spawn=0,last=0,user:any=null,profile:any=null,startAt=0,room:any=null,ch:any=null,rival=0;
const best=()=>Number(localStorage.getItem('rb-mrr-best')||0);
function size(){const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=r.width*d;c.height=r.height*d;x.setTransform(d,0,0,d,0,0)}
function hud(){$('#score').textContent=Math.floor(score).toLocaleString();$('#best').textContent=best().toLocaleString();$('#combo').textContent=`x${combo}`;$('#lives').textContent='♥'.repeat(lives)+'♡'.repeat(3-lives);$('#speed').textContent=`${(speed/7).toFixed(1)}X`;$('#rival').textContent=Math.floor(rival).toLocaleString()}
function reset(){lane=1;items=[];jump=slide=score=0;combo=1;lives=3;speed=7+Number(($<HTMLSelectElement>('#difficulty')).value)*1.2;startAt=Date.now();hud()}
function draw(){const w=c.clientWidth,h=c.clientHeight;x.clearRect(0,0,w,h);const g=x.createLinearGradient(0,0,0,h);g.addColorStop(0,'#07200c');g.addColorStop(1,'#020402');x.fillStyle=g;x.fillRect(0,0,w,h);x.fillStyle='#101512';x.beginPath();x.moveTo(w*.36,0);x.lineTo(w*.64,0);x.lineTo(w*.96,h);x.lineTo(w*.04,h);x.closePath();x.fill();x.strokeStyle='rgba(247,201,72,.34)';x.setLineDash([16,20]);for(let i=1;i<3;i++){x.beginPath();x.moveTo(w*(.36+.14*i),0);x.lineTo(w*(.04+.92*i/3),h);x.stroke()}x.setLineDash([]);const lx=(l:number,y:number)=>w/2+(l-1)*(w*.18+w*.1*y/h);for(const o of items){const s=22+o.y/h*40,px=lx(o.lane,o.y);x.fillStyle=o.type==='cash'?'#f7c948':o.type==='boost'?'#31ff63':'#d93645';x.fillRect(px-s/2,o.y-s/2,s,s);x.fillStyle='#071008';x.font=`900 ${s*.6}px system-ui`;x.textAlign='center';x.textBaseline='middle';x.fillText(o.type==='cash'?'$':o.type==='boost'?'⚡':'■',px,o.y)}const py=h*.84-jump,px=lx(lane,h*.84);x.fillStyle='#31ff63';x.shadowColor='#31ff63';x.shadowBlur=20;x.fillRect(px-24,py-(slide?10:65),48,slide?24:65);x.shadowBlur=0;if(!run){x.fillStyle='rgba(0,0,0,.5)';x.fillRect(0,0,w,h);x.fillStyle='#fff';x.font='900 26px system-ui';x.textAlign='center';x.fillText('MONEY ROAD RUNNER',w/2,h*.45);x.fillStyle='#f7c948';x.font='700 14px system-ui';x.fillText('PRESS START RUN',w/2,h*.5)}}
function act(a:string){if(a==='left')lane=Math.max(0,lane-1);if(a==='right')lane=Math.min(2,lane+1);if(a==='jump'&&!jump)jump=82;if(a==='slide')slide=500}
function loop(t:number){const dt=Math.min(34,t-last||16);last=t;if(run&&!pause){spawn+=dt;if(spawn>Math.max(320,850-speed*25)){spawn=0;const r=Math.random();items.push({lane:Math.floor(Math.random()*3),y:-30,type:r<.58?'cash':r<.78?'boost':'car'})}jump=Math.max(0,jump-dt*.24);slide=Math.max(0,slide-dt);score+=dt*.018*speed*combo;items.forEach(o=>o.y+=speed*dt*.09);items=items.filter(o=>{if(o.y>c.clientHeight*.76&&o.y<c.clientHeight*.92&&o.lane===lane){if(o.type==='car'&&jump<35&&slide<=0){lives--;combo=1}else if(o.type==='cash'){score+=100*combo;combo=Math.min(12,combo+1)}else if(o.type==='boost'){score+=250*combo;speed=Math.min(19,speed+1);combo=Math.min(12,combo+2)}else return o.y<c.clientHeight+60;return false}return o.y<c.clientHeight+60});speed=Math.min(19,speed+dt*.0008);if(room&&Math.floor(score)%300<4)void sync();if(lives<=0)void finish('crash');hud()}draw();requestAnimationFrame(loop)}
async function finish(result:string){if(!run)return;run=false;const final=Math.floor(score),duration=Math.floor((Date.now()-startAt)/1000);localStorage.setItem('rb-mrr-best',String(Math.max(best(),final)));if(user){await supabase.from('game_sessions').insert({game_id:GAME,game_slug:'money-road-runner',user_id:user.id,username:profile?.username,display_name:profile?.display_name,ended_at:new Date().toISOString(),duration_seconds:duration,result,score:final,platform_type:'web'});await supabase.from('game_scores').insert({game_id:GAME,game_slug:'money-road-runner',user_id:user.id,username:profile?.username,display_name:profile?.display_name,score:final,mode:room?'online':'solo',platform_type:'web'});const {data:p}=await supabase.from('game_player_progress').select('*').eq('game_id',GAME).eq('user_id',user.id).maybeSingle();const gain=Math.max(35,Math.min(250,Math.floor(final/250)));await supabase.from('game_player_progress').upsert({game_id:GAME,user_id:user.id,current_level:Math.floor((Number(p?.xp||0)+gain)/500)+1,xp:Number(p?.xp||0)+gain,best_score:Math.max(Number(p?.best_score||0),final),progress:{...(p?.progress||{}),runs:Number(p?.progress?.runs||0)+1,highest_combo:Math.max(Number(p?.progress?.highest_combo||0),combo)},settings:p?.settings||{},inventory:p?.inventory||{},achievements:p?.achievements||[],last_checkpoint:{score:final},total_play_seconds:Number(p?.total_play_seconds||0)+duration,last_played_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'game_id,user_id'});await supabase.rpc('rb_award_xp',{p_event_key:'game_completed',p_section:'gaming',p_source_table:'game_scores',p_source_id:null,p_amount:gain})}$('#log').textContent=`Run complete — ${final.toLocaleString()} points.`;await leaders();hud()}
async function leaders(){const {data}=await supabase.from('game_scores').select('display_name,username,score').eq('game_slug','money-road-runner').order('score',{ascending:false}).limit(8);$('#leaders').innerHTML=(data||[]).map((v:any,i)=>`<article><b>#${i+1}</b><span>${v.display_name||v.username||'Rich Runner'}</span><strong>${Number(v.score||0).toLocaleString()}</strong></article>`).join('')||'<p class="mrr-log">No ranked runs yet.</p>'}
async function makeRoom(){if(!user)return $('#roomState').textContent='Tap In required.';const code=Math.random().toString(36).slice(2,8).toUpperCase();const {data:r,error}=await supabase.from('game_rooms').insert({room_code:code,game_key:'money-road-runner',host_user_id:user.id,status:'active',game_state:{scores:{[user.id]:0}}}).select().single();if(error)return $('#roomState').textContent=error.message;room=r;($<HTMLInputElement>('#roomCode')).value=code;watch();$('#roomState').textContent=`ROOM ${code} READY`}
async function join(){if(!user)return $('#roomState').textContent='Tap In required.';const code=$<HTMLInputElement>('#roomCode').value.trim().toUpperCase();const {data:r}=await supabase.from('game_rooms').select('*').eq('room_code',code).eq('game_key','money-road-runner').maybeSingle();if(!r)return $('#roomState').textContent='Room not found.';room=r;watch();$('#roomState').textContent=`JOINED ${code}`}
function watch(){if(ch)void supabase.removeChannel(ch);ch=supabase.channel(`mrr:${room.id}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'game_rooms',filter:`id=eq.${room.id}`},(p:any)=>{const s=p.new?.game_state?.scores||{};rival=Math.max(0,...Object.entries(s).filter(([id])=>id!==user?.id).map(([,v])=>Number(v||0)));hud()}).subscribe();$('#net').textContent='REALTIME RACE'}
async function sync(){if(!room||!user)return;const {data:r}=await supabase.from('game_rooms').select('game_state').eq('id',room.id).single();await supabase.from('game_rooms').update({game_state:{...(r?.game_state||{}),scores:{...(r?.game_state?.scores||{}),[user.id]:Math.floor(score)}}}).eq('id',room.id)}
$('#start').onclick=()=>{reset();run=true;pause=false;$('#log').textContent='Run live.'};$('#pause').onclick=()=>{pause=!pause;$('#pause').textContent=pause?'RESUME':'PAUSE'};$('#local').onclick=()=>{reset();run=true;$('#log').textContent=`Beat the local best: ${best().toLocaleString()}.`};$('#end').onclick=()=>void finish('ended');$('#createRoom').onclick=()=>void makeRoom();$('#joinRoom').onclick=()=>void join();document.querySelectorAll<HTMLButtonElement>('[data-a]').forEach(b=>b.onclick=()=>act(String(b.dataset.a)));addEventListener('keydown',e=>{if(['ArrowLeft','a','A'].includes(e.key))act('left');if(['ArrowRight','d','D'].includes(e.key))act('right');if(['ArrowUp','w','W',' '].includes(e.key))act('jump');if(['ArrowDown','s','S'].includes(e.key))act('slide')});addEventListener('resize',size);addEventListener('beforeunload',()=>{if(ch)void supabase.removeChannel(ch)});size();requestAnimationFrame(loop);void(async()=>{const {data:{session}}=await supabase.auth.getSession();user=session?.user||null;if(user){const {data}=await supabase.from('profiles').select('username,display_name').eq('id',user.id).maybeSingle();profile=data}await leaders();hud()})();