import { supabase } from '../../core/supabase/client';
import './portal-room-rush.css';

type Room={id:number;type:'empty'|'portal'|'resource'|'trap'|'enemy'|'core';owner:'player'|'enemy'|'neutral';energy:number;squad:number;revealed:boolean};
const GAME_ID='aeb72c86-1bac-424c-9372-bad451bddbbc';
const SIZE=36;
let rooms:Room[]=[],selected=0,turn=1,energy=120,intel=3,squad=8,score=0,best=Number(localStorage.getItem('prr-best')||0),mode='campaign',difficulty=2,chapter=1,running=false,user:any=null,profile:any=null,room:any=null,channel:any=null,started=Date.now(),upgradePoints=0,unlocked=new Set<string>();
const app=document.querySelector<HTMLElement>('#app')!;
app.innerHTML=`<main class="prr-shell"><div class="prr-wrap"><header class="prr-top"><a href="/gaming.html">← GAMING</a><div class="prr-brand"><small>ELITE STRATEGY 05 / 05</small><h1>PORTAL ROOM RUSH</h1></div><span class="prr-status" id="net">OFFLINE READY</span></header><section class="prr-hero"><div><small class="prr-kicker">TACTICAL SQUADS • SHIFTING ROOMS • TRAPS • AI RIVALS • REALTIME • OFFLINE</small><h2>CONTROL<br>THE GRID.</h2><p>Command a strike squad through a living portal labyrinth. Capture rooms, stabilize portals, collect energy, reveal hidden threats, outthink rival commanders and seize the dimensional core.</p></div><div class="prr-stats"><article><small>RICH XP</small><strong id="xp">0</strong></article><article><small>CHAPTER</small><strong id="chapter">1</strong></article><article><small>BEST</small><strong id="best">0</strong></article><article><small>WINS</small><strong id="wins">0</strong></article></div></section><section class="prr-grid"><div class="prr-stage"><div class="prr-hud"><article><small>ENERGY</small><strong id="energy">120</strong></article><article><small>SQUAD</small><strong id="squad">8</strong></article><article><small>INTEL</small><strong id="intel">3</strong></article><article><small>TURN</small><strong id="turn">1</strong></article></div><div class="prr-board" id="board"></div><div class="prr-controls"><button class="prr-btn" data-action="move">MOVE SQUAD</button><button class="prr-btn" data-action="scan">SCAN ROOM</button><button class="prr-btn" data-action="stabilize">STABILIZE</button><button class="prr-btn gold" data-action="rush">PORTAL RUSH</button></div></div><aside class="prr-side"><section class="prr-card"><h3>MISSION COMMAND</h3><select class="prr-select" id="mode"><option value="campaign">CAMPAIGN</option><option value="survival">ENDLESS LABYRINTH</option><option value="local">LOCAL SCORE DUEL</option><option value="online">ONLINE RANKED</option></select><select class="prr-select" id="difficulty"><option value="1">ROOKIE ARCHITECT</option><option value="2" selected>ELITE ARCHITECT</option><option value="3">VOID ARCHITECT</option></select><button class="prr-btn primary" id="start">START MISSION</button><p class="prr-log" id="log">Select a room and begin the tactical sweep.</p></section><section class="prr-card"><h3>PORTAL TECH TREE</h3><div id="upgrades"></div></section><section class="prr-card"><h3>REALTIME WAR ROOM</h3><input class="prr-input" id="roomCode" maxlength="8" placeholder="ROOM CODE"/><div class="prr-row"><button class="prr-btn primary" id="createRoom">CREATE</button><button class="prr-btn" id="joinRoom">JOIN</button></div><p class="prr-log" id="roomState">Tap In required for ranked rooms.</p></section><section class="prr-card"><h3>ELITE LEADERBOARD</h3><div class="prr-leaders" id="leaders"></div></section></aside></section><footer class="prr-footer">PORTAL ROOM RUSH v1.0 • PROCEDURAL GRID • TACTICAL AI • SUPABASE REALTIME</footer></div></main>`;
const $=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
const rand=(n:number)=>Math.floor(Math.random()*n);
const toast=(t:string)=>{const e=document.createElement('div');e.className='prr-toast';e.textContent=t;document.body.append(e);setTimeout(()=>e.remove(),1300)};
function makeRooms(){rooms=Array.from({length:SIZE},(_,id)=>({id,type:'empty',owner:'neutral',energy:0,squad:0,revealed:id===0}));rooms[0]={id:0,type:'portal',owner:'player',energy:15,squad, revealed:true};rooms[SIZE-1]={id:SIZE-1,type:'core',owner:'enemy',energy:50,squad:5+difficulty*2,revealed:true};const used=new Set([0,SIZE-1]);for(const type of ['portal','portal','resource','resource','resource','trap','trap','trap','enemy','enemy','enemy','enemy'] as Room['type'][]){let i=rand(SIZE);while(used.has(i))i=rand(SIZE);used.add(i);rooms[i]={id:i,type,owner:type==='enemy'?'enemy':'neutral',energy:type==='resource'?20+rand(25):type==='portal'?10:0,squad:type==='enemy'?2+difficulty+rand(3):0,revealed:false}}}
function icon(r:Room){return r.type==='portal'?'◎':r.type==='resource'?'✦':r.type==='trap'?'⚠':r.type==='enemy'?'◆':r.type==='core'?'⬢':'·'}
function renderBoard(){const labels:{[k:string]:string}={portal:'PORTAL',resource:'ENERGY',trap:'TRAP',enemy:'RIVAL',core:'CORE',empty:'ROOM'};$('#board').innerHTML=rooms.map(r=>`<button class="prr-room ${r.owner==='enemy'?'enemy':''} ${r.type==='portal'?'portal':''} ${r.type==='trap'&&r.revealed?'trap':''} ${selected===r.id?'active':''}" data-room="${r.id}"><span class="icon">${r.revealed?icon(r):'?'}</span><b>${r.revealed?labels[r.type]:'UNKNOWN'}</b><small>${r.owner.toUpperCase()} • ${r.energy}E</small><span class="prr-squad">${Array.from({length:Math.min(6,r.squad)},()=>'<i></i>').join('')}</span></button>`).join('');document.querySelectorAll<HTMLButtonElement>('[data-room]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.room);renderBoard();describe()})}
function describe(){const r=rooms[selected];$('#log').textContent=`ROOM ${selected+1} • ${r.revealed?r.type.toUpperCase():'UNKNOWN'} • ${r.owner.toUpperCase()} • ${r.squad} UNITS`}
function syncHud(){$('#energy').textContent=String(energy);$('#squad').textContent=String(squad);$('#intel').textContent=String(intel);$('#turn').textContent=String(turn);$('#chapter').textContent=String(chapter);$('#best').textContent=String(Math.max(best,score));$('#wins').textContent=String(Number(localStorage.getItem('prr-wins')||0));}
function renderUpgrades(){const list:[string,string,number][]=[['scanner','DEEP SCANNER',2],['shield','PORTAL SHIELD',2],['squad','ELITE SQUAD',3],['warp','QUANTUM WARP',5]];$('#upgrades').innerHTML=list.map(([k,n,c])=>`<div class="prr-upgrade"><div><b>${n}</b><small>${unlocked.has(k)?'UNLOCKED':`${c} POINTS`}</small></div><button class="prr-btn" data-upgrade="${k}" data-cost="${c}" ${unlocked.has(k)?'disabled':''}>${unlocked.has(k)?'✓':'UNLOCK'}</button></div>`).join('')+`<p class="prr-log">Upgrade points: <b>${upgradePoints}</b></p>`;document.querySelectorAll<HTMLButtonElement>('[data-upgrade]').forEach(b=>b.onclick=()=>{const c=Number(b.dataset.cost);if(upgradePoints<c)return toast('NOT ENOUGH POINTS');upgradePoints-=c;unlocked.add(b.dataset.upgrade!);saveLocal();renderUpgrades()})}
function adjacent(a:number,b:number){const ax=a%6,ay=Math.floor(a/6),bx=b%6,by=Math.floor(b/6);return Math.abs(ax-bx)+Math.abs(ay-by)===1}
function playerRoom(){return rooms.find(r=>r.owner==='player'&&r.squad>0)||rooms[0]}
function act(kind:string){if(!running)return toast('START A MISSION');const target=rooms[selected],origin=playerRoom();if(kind==='scan'){const cost=unlocked.has('scanner')?0:1;if(intel<cost)return toast('NO INTEL');intel-=cost;target.revealed=true;score+=40;afterTurn('ROOM SCANNED');return}
if(kind==='stabilize'){if(target.type!=='portal'||target.owner!=='player')return toast('CAPTURE A PORTAL FIRST');if(energy<20)return toast('NEED 20 ENERGY');energy-=20;target.energy+=30;score+=180;afterTurn('PORTAL STABILIZED');return}
if(kind==='rush'){if(!unlocked.has('warp')&&energy<45)return toast('NEED 45 ENERGY');if(!target.revealed)return toast('SCAN TARGET FIRST');energy-=unlocked.has('warp')?25:45;resolveMove(origin,target,true);return}
if(kind==='move'){if(!adjacent(origin.id,target.id))return toast('SELECT AN ADJACENT ROOM');resolveMove(origin,target,false)}}
function resolveMove(origin:Room,target:Room,warp:boolean){if(target.owner==='player')return toast('ROOM ALREADY CONTROLLED');const force=squad+(unlocked.has('squad')?3:0)+rand(5);const defense=target.squad+(target.type==='core'?difficulty*3:0)+rand(4);if(target.type==='trap'&&target.revealed){const loss=unlocked.has('shield')?1:2+difficulty;squad=Math.max(1,squad-loss);score=Math.max(0,score-90);target.type='empty';toast(`TRAP HIT -${loss} SQUAD`)}if(force>=defense){origin.squad=0;origin.owner='player';target.owner='player';target.revealed=true;target.squad=squad;energy+=target.energy;score+=120+target.energy*4+(warp?160:0);if(target.type==='core')return void finish(true);afterTurn('ROOM CAPTURED')}else{squad=Math.max(1,squad-Math.max(1,Math.ceil(defense/3)));score=Math.max(0,score-50);afterTurn('ASSAULT REPELLED')}}
function enemyTurn(){const owned=rooms.filter(r=>r.owner==='enemy');const candidates=rooms.filter(r=>r.owner!=='enemy'&&owned.some(o=>adjacent(o.id,r.id)));if(!candidates.length)return;const t=candidates[rand(candidates.length)];if(Math.random()<.38+difficulty*.12){t.owner='enemy';t.squad=2+difficulty+rand(3);t.revealed=true;if(t.owner==='player')squad=Math.max(1,squad-1)}if(Math.random()<.25){const shift=rooms[rand(SIZE)],other=rooms[rand(SIZE)];[shift.type,other.type]=[other.type,shift.type]}}
function afterTurn(msg:string){turn++;enemyTurn();energy+=3+(rooms.filter(r=>r.owner==='player'&&r.type==='portal').length*2);score+=10;syncHud();renderBoard();describe();$('#log').textContent=`${msg} • TURN ${turn}`;saveLocal();if(mode==='online'&&room)void sendState()}
function reset(){mode=($('#mode') as HTMLSelectElement).value;difficulty=Number(($('#difficulty') as HTMLSelectElement).value);turn=1;energy=120+(unlocked.has('shield')?10:0);intel=3+(unlocked.has('scanner')?2:0);squad=8+(unlocked.has('squad')?3:0);score=0;selected=0;started=Date.now();makeRooms();running=true;renderBoard();syncHud();$('#log').textContent=`CHAPTER ${chapter} • ${mode.toUpperCase()} • CAPTURE THE CORE`}
async function finish(won:boolean){if(!running)return;running=false;const points=Math.max(250,score+(won?1400:300)+chapter*180+energy*3+squad*80);best=Math.max(best,points);localStorage.setItem('prr-best',String(best));if(won){chapter=Math.min(30,chapter+1);upgradePoints+=chapter%2===0?2:1;localStorage.setItem('prr-wins',String(Number(localStorage.getItem('prr-wins')||0)+1))}saveLocal();renderUpgrades();syncHud();$('#log').textContent=`${won?'DIMENSION SECURED':'MISSION FAILED'} • ${points.toLocaleString()} SCORE`;toast(won?'CORE CAPTURED':'PORTAL LOST');if(user)await persist(points,won)}
function saveLocal(){localStorage.setItem('rb-portal-room-rush',JSON.stringify({chapter,upgradePoints,unlocked:[...unlocked],best}))}
function restore(){try{const s=JSON.parse(localStorage.getItem('rb-portal-room-rush')||'{}');chapter=Number(s.chapter||1);upgradePoints=Number(s.upgradePoints||0);unlocked=new Set(s.unlocked||[]);best=Number(s.best||best)}catch{}renderUpgrades();syncHud()}
async function persist(points:number,won:boolean){const duration=Math.floor((Date.now()-started)/1000);await supabase.from('game_sessions').insert({game_id:GAME_ID,game_slug:'portal-room-rush',user_id:user.id,username:profile?.username,display_name:profile?.display_name,ended_at:new Date().toISOString(),duration_seconds:duration,result:won?'VICTORY':'DEFEAT',score:points,platform_type:'web',metadata:{mode,chapter,turn,energy,squad}});await supabase.from('game_scores').insert({game_id:GAME_ID,game_slug:'portal-room-rush',user_id:user.id,username:profile?.username,display_name:profile?.display_name,score:points,mode,platform_type:'web',metadata:{won,chapter,turn,energy,squad}});const {data:o}=await supabase.from('game_player_progress').select('*').eq('game_id',GAME_ID).eq('user_id',user.id).maybeSingle();const xp=Number(o?.xp||0)+(won?220:75);await supabase.from('game_player_progress').upsert({game_id:GAME_ID,user_id:user.id,current_level:Math.floor(xp/650)+1,xp,best_score:Math.max(Number(o?.best_score||0),points),progress:{...(o?.progress||{}),wins:Number(o?.progress?.wins||0)+(won?1:0),missions:Number(o?.progress?.missions||0)+1,chapter:Math.max(Number(o?.progress?.chapter||1),chapter)},settings:o?.settings||{},inventory:{unlocked:[...unlocked],upgradePoints},achievements:o?.achievements||[],last_checkpoint:{chapter,unlocked:[...unlocked],upgradePoints},total_play_seconds:Number(o?.total_play_seconds||0)+duration,last_played_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'game_id,user_id'});await supabase.rpc('rb_award_xp',{p_event_key:won?'game_win':'game_completed',p_section:'gaming',p_source_table:'game_scores',p_source_id:null,p_amount:won?220:75});await loadStats()}
async function loadStats(){const {data:s}=await supabase.from('game_scores').select('display_name,username,score').eq('game_slug','portal-room-rush').order('score',{ascending:false}).limit(8);$('#leaders').innerHTML=(s||[]).map((x:any,i)=>`<article><b>#${i+1}</b><span>${x.display_name||x.username||'Portal Commander'}</span><strong>${Number(x.score||0).toLocaleString()}</strong></article>`).join('')||'<p class="prr-log">No ranked scores yet.</p>';if(user){const {data:p}=await supabase.from('game_player_progress').select('xp,current_level').eq('game_id',GAME_ID).eq('user_id',user.id).maybeSingle();$('#xp').textContent=String(Number(p?.xp||0))}}
async function createRoom(){if(!user)return $('#roomState').textContent='Tap In required.';const code=Math.random().toString(36).slice(2,8).toUpperCase();const {data:r}=await supabase.from('game_rooms').insert({game_id:GAME_ID,game_key:'portal-room-rush',room_code:code,name:`Portal War ${code}`,room_type:'ranked',status:'waiting',host_user_id:user.id,max_players:2,settings:{difficulty}}).select().single();if(!r)return;await supabase.from('game_room_members').insert({room_id:r.id,user_id:user.id,username:profile?.username,display_name:profile?.display_name,role:'host',status:'active'});room=r;($('#roomCode') as HTMLInputElement).value=code;$('#roomState').textContent=`ROOM ${code} READY`;subscribe()}
async function joinRoom(){if(!user)return $('#roomState').textContent='Tap In required.';const code=($('#roomCode') as HTMLInputElement).value.trim().toUpperCase();const {data:r}=await supabase.from('game_rooms').select('*').eq('room_code',code).eq('game_key','portal-room-rush').maybeSingle();if(!r)return $('#roomState').textContent='Room not found.';await supabase.from('game_room_members').insert({room_id:r.id,user_id:user.id,username:profile?.username,display_name:profile?.display_name,role:'guest',status:'active'});room=r;mode='online';($('#mode') as HTMLSelectElement).value='online';$('#roomState').textContent=`JOINED ${code}`;subscribe();reset()}
function subscribe(){if(channel)void supabase.removeChannel(channel);channel=supabase.channel(`portal-rush:${room.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'game_moves',filter:`room_id=eq.${room.id}`},(p:any)=>{if(p.new.user_id===user?.id)return;const s=p.new.move_data?.state;if(!s)return;rooms=s.rooms;turn=s.turn;energy=s.energy;squad=s.squad;score=s.score;renderBoard();syncHud()}).subscribe(s=>$('#net').textContent=s==='SUBSCRIBED'?'REALTIME READY':'SYNCING')}
async function sendState(){if(!room||!user)return;await supabase.from('game_moves').insert({room_id:room.id,game_key:'portal-room-rush',user_id:user.id,username:profile?.username,display_name:profile?.display_name,move_number:Date.now(),move_data:{state:{rooms,turn,energy,squad,score}},turn:String(turn),metadata:{chapter}})}
async function boot(){restore();makeRooms();renderBoard();const {data:{user:u}}=await supabase.auth.getUser();user=u;if(user){const {data:p}=await supabase.from('profiles').select('username,display_name').eq('id',user.id).maybeSingle();profile=p;$('#net').textContent='SIGNED IN'}await loadStats()}
document.querySelectorAll<HTMLButtonElement>('[data-action]').forEach(b=>b.onclick=()=>act(b.dataset.action!));$('#start').onclick=reset;$('#createRoom').onclick=()=>void createRoom();$('#joinRoom').onclick=()=>void joinRoom();window.addEventListener('keydown',e=>{const map:Record<string,string>={m:'move',s:'scan',p:'stabilize',r:'rush'};const a=map[e.key.toLowerCase()];if(a){e.preventDefault();act(a)}});window.addEventListener('beforeunload',()=>{if(channel)void supabase.removeChannel(channel)});void boot();