import { supabase } from '../../core/supabase/client';
import './rich-samurais-son-ninja.css';

type Mode='solo'|'local'|'online';
const GAME_ID='9a4f1eaf-9447-479a-879f-de1a7f84252c';
const root=document.querySelector<HTMLElement>('#app')!;
let mode:Mode='solo',difficulty=2,user:any=null,profile:any=null,room:any=null,channel:any=null;
let p1=100,p2=100,energy1=0,energy2=0,score=0,combo=0,bestCombo=0,round=1,active=false,started=0,timer=90,clock:any=null,guard1=false,guard2=false;
root.innerHTML=`<main class="rs-shell"><div class="rs-wrap"><header class="rs-top"><a href="/gaming.html">←</a><div class="rs-brand"><small>RICH BIZNESS ELITE FIGHTER 01 / 05</small><h1>RICH SAMURAI'S SON NINJA 🥷</h1></div><span id="net" class="rs-status">OFFLINE READY</span></header><section class="rs-hero"><div class="rs-panel rs-copy"><small class="rs-kicker">SOLO • LOCAL VERSUS • REALTIME DUEL • OFFLINE</small><h2>DEFEND THE<br>RICH BLOODLINE.</h2><p>Original anime-style sword and aura combat with adaptive rivals, combo chains, special techniques, ranked scores, Rich XP and tournament-ready rooms.</p></div><div class="rs-panel rs-stats"><article><small>RICH XP</small><strong id="xp">0</strong></article><article><small>BEST</small><strong id="best">0</strong></article><article><small>WINS</small><strong id="wins">0</strong></article><article><small>COMBO</small><strong id="combo">0</strong></article></div></section><section class="rs-layout"><div class="rs-panel rs-arena" id="arena"><div class="rs-hud"><div><b>RICH NINJA</b><div class="rs-life"><span id="p1Life"></span></div></div><strong id="timer" class="rs-timer">90</strong><div style="text-align:right"><b id="enemyName">SHADOW RIVAL</b><div class="rs-life enemy"><span id="p2Life"></span></div></div></div><div class="rs-stage"><div class="rs-aura"></div><div id="fighter1" class="fighter"></div><div class="rs-aura enemy"></div><div id="fighter2" class="fighter enemy"></div></div><div class="rs-controls"><button class="rs-btn" data-action="quick">QUICK STRIKE</button><button class="rs-btn" data-action="heavy">HEAVY SLASH</button><button class="rs-btn" data-action="guard">GUARD</button><button class="rs-btn special" data-action="special">AURA TECHNIQUE</button></div></div><aside class="rs-side"><section class="rs-panel rs-card"><h3>FIGHT MODE</h3><select id="mode"><option value="solo">SOLO</option><option value="local">LOCAL VERSUS</option><option value="online">ONLINE DUEL</option></select><select id="difficulty"><option value="1">ROOKIE RIVAL</option><option value="2" selected>ELITE RIVAL</option><option value="3">BOSS RIVAL</option></select><div class="rs-grid"><button id="start" class="rs-btn primary">START FIGHT</button><button id="reset" class="rs-btn">RESET</button></div><p id="log" class="rs-log">Choose a mode and enter the arena.</p></section><section class="rs-panel rs-card"><h3>ONLINE DOJO</h3><input id="roomCode" maxlength="8" placeholder="ROOM CODE"/><div class="rs-grid"><button id="create" class="rs-btn primary">CREATE</button><button id="join" class="rs-btn">JOIN</button></div><p id="roomState" class="rs-log">Tap In required for realtime duels.</p></section><section class="rs-panel rs-card"><h3>ELITE RANKING</h3><div id="leaders" class="rs-board"></div></section></aside></section><footer class="rs-footer">RICH SAMURAI'S SON NINJA v1.0 • OFFLINE SAVE • REALTIME DOJO • GAMING XP</footer></div></main>`;
const $=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
function paint(){($<HTMLElement>('#p1Life')).style.width=`${Math.max(0,p1)}%`;($<HTMLElement>('#p2Life')).style.width=`${Math.max(0,p2)}%`;$('#combo').textContent=String(combo);$('#timer').textContent=String(timer)}
function flash(){const f=document.createElement('i');f.className='flash';$('#arena').appendChild(f);setTimeout(()=>f.remove(),260)}
function animate(id:string,kind:string){const el=$(id);el.classList.add(kind);setTimeout(()=>el.classList.remove(kind),180)}
function damage(base:number,guard:boolean){return Math.max(1,Math.round(base*(guard?.38:1)*(0.85+Math.random()*.3)))}
function action(who:1|2,kind:string,remote=false){if(!active)return;let atk=kind==='quick'?7:kind==='heavy'?13:kind==='special'?22:0;if(kind==='guard'){if(who===1)guard1=true;else guard2=true;$('#log').textContent=`${who===1?'Rich Ninja':'Rival'} enters guard stance.`;return}if(kind==='special'){const e=who===1?energy1:energy2;if(e<60){$('#log').textContent='Build 60 aura energy first.';return}if(who===1)energy1=0;else energy2=0;flash()}if(who===1){p2-=damage(atk,guard2);energy1=Math.min(100,energy1+14);combo++;bestCombo=Math.max(bestCombo,combo);score+=atk*combo;guard2=false;animate('#fighter1','attack');animate('#fighter2','hit')}else{p1-=damage(atk,guard1);energy2=Math.min(100,energy2+14);combo=0;guard1=false;animate('#fighter2','attack');animate('#fighter1','hit')}paint();$('#log').textContent=`${who===1?'Rich Ninja':'Shadow Rival'} used ${kind.toUpperCase()}.`;if(mode==='online'&&room&&!remote)void sendMove(kind);if(p1<=0||p2<=0)void finish(p2<=0?'win':'loss')}
function rival(){if(!active||mode!=='solo')return;const delay=Math.max(420,1000-difficulty*170);setTimeout(()=>{if(!active)return;const roll=Math.random();action(2,roll>.82?'special':roll>.45?'heavy':roll>.16?'quick':'guard');rival()},delay)}
function start(){p1=p2=100;energy1=energy2=0;score=0;combo=0;bestCombo=0;timer=90;round++;active=true;started=Date.now();clearInterval(clock);clock=setInterval(()=>{timer--;paint();if(timer<=0)void finish(p1>=p2?'win':'loss')},1000);paint();$('#log').textContent='FIGHT! Chain attacks and build aura.';if(mode==='solo')rival()}
async function finish(result:'win'|'loss'){if(!active)return;active=false;clearInterval(clock);const points=Math.max(100,score+(result==='win'?1000:250)+p1*5);$('#log').textContent=result==='win'?'RICH NINJA WINS THE DUEL!':'THE SHADOW RIVAL WINS.';localStorage.setItem('rb-rich-samurai-best',String(Math.max(points,Number(localStorage.getItem('rb-rich-samurai-best')||0))));if(!user)return;const duration=Math.floor((Date.now()-started)/1000);await supabase.from('game_sessions').insert({game_id:GAME_ID,game_slug:'rich-samurais-son-ninja',user_id:user.id,username:profile?.username,display_name:profile?.display_name,ended_at:new Date().toISOString(),duration_seconds:duration,result,score:points,platform_type:'web',metadata:{mode,best_combo:bestCombo,round}});await supabase.from('game_scores').insert({game_id:GAME_ID,game_slug:'rich-samurais-son-ninja',user_id:user.id,username:profile?.username,display_name:profile?.display_name,score:points,mode,platform_type:'web',metadata:{result,best_combo:bestCombo,duration}});await supabase.rpc('rb_award_xp',{p_event_key:result==='win'?'game_win':'game_completed',p_section:'gaming',p_source_table:'game_scores',p_source_id:null,p_amount:result==='win'?175:60});const {data:o}=await supabase.from('game_player_progress').select('*').eq('game_id',GAME_ID).eq('user_id',user.id).maybeSingle();const xp=Number(o?.xp||0)+(result==='win'?175:60);await supabase.from('game_player_progress').upsert({game_id:GAME_ID,user_id:user.id,current_level:Math.floor(xp/600)+1,xp,best_score:Math.max(Number(o?.best_score||0),points),progress:{...(o?.progress||{}),wins:Number(o?.progress?.wins||0)+(result==='win'?1:0),fights:Number(o?.progress?.fights||0)+1,best_combo:Math.max(Number(o?.progress?.best_combo||0),bestCombo)},settings:o?.settings||{},inventory:o?.inventory||{},achievements:o?.achievements||[],last_checkpoint:{p1,p2,score,combo},total_play_seconds:Number(o?.total_play_seconds||0)+duration,last_played_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'game_id,user_id'});await stats()}
async function stats(){const {data:s}=await supabase.from('game_scores').select('display_name,username,score').eq('game_slug','rich-samurais-son-ninja').order('score',{ascending:false}).limit(8);$('#leaders').innerHTML=(s||[]).map((x:any,i)=>`<article><b>#${i+1}</b><span>${x.display_name||x.username||'Rich Fighter'}</span><strong>${Number(x.score||0).toLocaleString()}</strong></article>`).join('')||'<p class="rs-log">No ranked duels yet.</p>';if(user){const {data:p}=await supabase.from('game_player_progress').select('*').eq('game_id',GAME_ID).eq('user_id',user.id).maybeSingle();$('#xp').textContent=Number(p?.xp||0).toLocaleString();$('#best').textContent=Number(p?.best_score||0).toLocaleString();$('#wins').textContent=Number(p?.progress?.wins||0).toLocaleString()}}
async function createRoom(){if(!user)return $('#roomState').textContent='Tap In required.';const code=Math.random().toString(36).slice(2,8).toUpperCase();const {data:r,error}=await supabase.from('game_rooms').insert({room_code:code,game_key:'rich-samurais-son-ninja',host_user_id:user.id,status:'active',current_turn:'p1',game_state:{p1:100,p2:100}}).select().single();if(error)return $('#roomState').textContent=error.message;await supabase.from('game_room_members').insert({room_id:r.id,user_id:user.id,username:profile?.username,display_name:profile?.display_name,role:'p1',status:'active'});room={...r,side:'p1'};($<HTMLInputElement>('#roomCode')).value=code;$('#roomState').textContent=`DOJO ${code} — WAITING`;subscribe()}
async function joinRoom(){if(!user)return $('#roomState').textContent='Tap In required.';const code=$<HTMLInputElement>('#roomCode').value.trim().toUpperCase();const {data:r}=await supabase.from('game_rooms').select('*').eq('room_code',code).eq('game_key','rich-samurais-son-ninja').maybeSingle();if(!r)return $('#roomState').textContent='Dojo not found.';await supabase.from('game_room_members').insert({room_id:r.id,user_id:user.id,username:profile?.username,display_name:profile?.display_name,role:'p2',status:'active'});room={...r,side:'p2'};mode='online';($<HTMLSelectElement>('#mode')).value='online';$('#roomState').textContent=`JOINED ${code}`;subscribe();start()}
function subscribe(){if(channel)void supabase.removeChannel(channel);channel=supabase.channel(`samurai:${room.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'game_moves',filter:`room_id=eq.${room.id}`},(e:any)=>{if(e.new.user_id!==user?.id)action(room.side==='p1'?2:1,e.new.move_data?.action||'quick',true)}).subscribe()}
async function sendMove(kind:string){await supabase.from('game_moves').insert({room_id:room.id,game_key:'rich-samurais-son-ninja',user_id:user.id,username:profile?.username,display_name:profile?.display_name,move_number:Date.now(),move_data:{action:kind},turn:room.side})}
document.querySelectorAll<HTMLButtonElement>('[data-action]').forEach(b=>b.onclick=()=>action(mode==='local'&&b.dataset.action==='guard'?2:1,b.dataset.action||'quick'));
$('#start').onclick=start;$('#reset').onclick=start;$('#create').onclick=()=>void createRoom();$('#join').onclick=()=>void joinRoom();($<HTMLSelectElement>('#mode')).onchange=e=>{mode=(e.target as HTMLSelectElement).value as Mode;$('#enemyName').textContent=mode==='local'?'PLAYER TWO':mode==='online'?'ONLINE RIVAL':'SHADOW RIVAL'};($<HTMLSelectElement>('#difficulty')).onchange=e=>difficulty=Number((e.target as HTMLSelectElement).value);
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='j')action(1,'quick');if(k==='k')action(1,'heavy');if(k==='l')action(1,'guard');if(k==='i')action(1,'special');if(mode==='local'){if(k==='a')action(2,'quick');if(k==='s')action(2,'heavy');if(k==='d')action(2,'guard');if(k==='w')action(2,'special')}});
(async()=>{const {data:{session}}=await supabase.auth.getSession();user=session?.user||null;if(user){const {data:p}=await supabase.from('profiles').select('username,display_name').eq('id',user.id).maybeSingle();profile=p;$('#net').textContent='GAMING SYNCED'}await stats();paint()})();
addEventListener('beforeunload',()=>{clearInterval(clock);if(channel)void supabase.removeChannel(channel)});