import { supabase } from '../../core/supabase/client';
import './rich-checkers-elite.css';

type Side='gold'|'green'; type Piece={side:Side;king:boolean}|null; type Move={from:number;to:number;capture?:number};
const GAME_ID='a0af0645-8098-46db-90a4-ee7a0e081c1c'; const GAME='rich-checkers-elite';
const root=document.querySelector<HTMLElement>('#app')!; const $=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
let board:Piece[]=[],turn:Side='gold',selected:number|null=null,forcedFrom:number|null=null,mode='solo',difficulty='elite',history:Piece[][]=[],started=Date.now(),user:any=null,profile:any=null,room:any=null,channel:any=null,gameOver=false;
const other=(s:Side):Side=>s==='gold'?'green':'gold';
function initial(){const b:Piece[]=Array(64).fill(null);for(let r=0;r<3;r++)for(let c=0;c<8;c++)if((r+c)%2)b[r*8+c]={side:'green',king:false};for(let r=5;r<8;r++)for(let c=0;c<8;c++)if((r+c)%2)b[r*8+c]={side:'gold',king:false};return b}
function dirs(p:NonNullable<Piece>){return p.king?[[-1,-1],[-1,1],[1,-1],[1,1]]:p.side==='gold'?[[-1,-1],[-1,1]]:[[1,-1],[1,1]]}
function movesFor(i:number,capturesOnly=false){const p=board[i];if(!p)return[];const r=Math.floor(i/8),c=i%8,out:Move[]=[];for(const [dr,dc] of dirs(p)){const r1=r+dr,c1=c+dc;if(r1<0||r1>7||c1<0||c1>7)continue;const n=r1*8+c1;if(!board[n]&&!capturesOnly)out.push({from:i,to:n});else if(board[n]?.side===other(p.side)){const r2=r+dr*2,c2=c+dc*2;if(r2>=0&&r2<8&&c2>=0&&c2<8&&!board[r2*8+c2])out.push({from:i,to:r2*8+c2,capture:n})}}return out}
function allMoves(side:Side){const caps:Move[]=[];const normal:Move[]=[];board.forEach((p,i)=>{if(p?.side===side){const ms=movesFor(i);ms.forEach(m=>m.capture!==undefined?caps.push(m):normal.push(m))}});return caps.length?caps:normal}
function count(side:Side){return board.filter(p=>p?.side===side).length}
root.innerHTML=`<main class="rce-shell"><div class="rce-wrap"><header class="rce-top"><a href="/gaming.html">←</a><div class="rce-brand"><small>RICH BIZNESS ELITE GAME 27 / 28</small><h1>RICH CHECKERS ELITE</h1></div><span id="net" class="rce-status">OFFLINE READY</span></header><section class="rce-hero"><div><small class="rce-kicker">SOLO • LOCAL • REALTIME • OFFLINE</small><h2>RULE<br>THE BOARD.</h2><p>Precision checkers with forced captures, multi-jumps, kings, adaptive AI, ranked rooms, persistent Rich XP and tournament-ready scoring.</p></div><div class="rce-stats"><article><small>RICH XP</small><strong id="xp">0</strong></article><article><small>BEST SCORE</small><strong id="best">0</strong></article><article><small>WINS</small><strong id="wins">0</strong></article><article><small>PIECES</small><strong id="pieces">12–12</strong></article></div></section><section class="rce-layout"><section class="rce-board-wrap"><div class="rce-meta"><span id="turn" class="rce-turn">GOLD TO MOVE</span><span id="rule">FORCED CAPTURES ON</span></div><div id="board" class="rce-board" aria-label="Rich Checkers board"></div></section><aside class="rce-side"><section class="rce-panel"><h3>PLAY MODE</h3><div class="rce-modes"><button class="rce-btn active" data-mode="solo">SOLO</button><button class="rce-btn" data-mode="local">LOCAL</button><button class="rce-btn" data-mode="online">ONLINE</button></div><select id="difficulty" class="rce-select"><option value="rookie">ROOKIE AI</option><option value="elite" selected>ELITE AI</option><option value="boss">CROWN AI</option></select><button id="newGame" class="rce-btn primary">NEW MATCH</button><button id="undo" class="rce-btn gold">UNDO PRACTICE MOVE</button><p id="log" class="rce-log">Select a gold piece. Captures are mandatory.</p></section><section class="rce-panel"><h3>RANKED ROOM</h3><input id="roomCode" class="rce-input" maxlength="8" placeholder="ROOM CODE"><button id="createRoom" class="rce-btn primary">CREATE ROOM</button><button id="joinRoom" class="rce-btn">JOIN ROOM</button><button id="leaveRoom" class="rce-btn">LEAVE ROOM</button><p id="roomState" class="rce-log">Tap In required for realtime play.</p></section><section class="rce-panel"><h3>ELITE LEADERBOARD</h3><div id="leaders" class="rce-board-list"></div></section></aside></section><footer class="rce-footer">RICH CHECKERS ELITE v1.0 • FORCED CAPTURES • MULTI-JUMPS • SUPABASE REALTIME • RICH XP</footer></div></main>`;
function render(){const legal=selected===null?[]:(forcedFrom===selected?movesFor(selected,true):allMoves(turn).filter(m=>m.from===selected));$('#board').innerHTML=board.map((p,i)=>`<button class="rce-square ${(Math.floor(i/8)+i%8)%2?'dark':'light'} ${selected===i?'selected':''} ${legal.some(m=>m.to===i)?'legal':''}" data-i="${i}" aria-label="square ${i}">${p?`<span class="rce-piece ${p.side}">${p.king?'♛':''}</span>`:''}</button>`).join('');$('#turn').textContent=`${turn.toUpperCase()} TO MOVE`;$('#pieces').textContent=`${count('gold')}–${count('green')}`;document.querySelectorAll<HTMLButtonElement>('.rce-square').forEach(b=>b.onclick=()=>clickSquare(Number(b.dataset.i)));saveLocal()}
function clickSquare(i:number){if(gameOver)return;const p=board[i];if(selected===null){if(p?.side===turn){const forced=allMoves(turn);if(forced.some(m=>m.from===i)){selected=i;render()}else $('#log').textContent='Another piece has a required capture.'}return}const allowed=(forcedFrom===selected?movesFor(selected,true):allMoves(turn).filter(m=>m.from===selected));const move=allowed.find(m=>m.to===i);if(move){applyMove(move,true);return}if(p?.side===turn&&forcedFrom===null){selected=i;render()}else{selected=null;render()}}
function applyMove(m:Move,human=false){history.push(board.map(p=>p?{...p}:null));const p=board[m.from]!;board[m.to]=p;board[m.from]=null;if(m.capture!==undefined)board[m.capture]=null;const row=Math.floor(m.to/8);if((p.side==='gold'&&row===0)||(p.side==='green'&&row===7))p.king=true;if(m.capture!==undefined&&movesFor(m.to,true).length){forcedFrom=m.to;selected=m.to;$('#log').textContent='MULTI-JUMP AVAILABLE — KEEP CAPTURING.';render();if(mode==='online')void broadcast();return}forcedFrom=null;selected=null;turn=other(turn);$('#log').textContent=m.capture!==undefined?'CROWN CAPTURE LANDED.':'POSITION ADVANCED.';render();void checkEnd();if(mode==='online')void broadcast();if(mode==='solo'&&turn==='green'&&!gameOver)setTimeout(aiTurn,human?420:160)}
function aiTurn(){if(gameOver||turn!=='green')return;const ms=allMoves('green');if(!ms.length)return void finish('gold');let pick=ms[Math.floor(Math.random()*ms.length)];const ranked=ms.map(m=>({m,score:(m.capture!==undefined?40:0)+(board[m.from]?.king?8:0)+(Math.floor(m.to/8)===7?20:0)+Math.random()*10})).sort((a,b)=>b.score-a.score);if(difficulty==='elite')pick=ranked[Math.min(1,ranked.length-1)].m;if(difficulty==='boss')pick=ranked[0].m;applyMove(pick)}
async function checkEnd(){const ms=allMoves(turn);if(!count(turn)||!ms.length)await finish(other(turn))}
async function finish(winner:Side){gameOver=true;const win=winner==='gold';const score=(count('gold')*300)+(board.filter(p=>p?.side==='gold'&&p.king).length*500)+(win?5000:500);$('#log').textContent=win?'YOU RULED THE BOARD.':'GREEN TOOK THE CROWN.';await syncResult(win?'win':'loss',score)}
function newGame(){board=initial();turn='gold';selected=null;forcedFrom=null;history=[];started=Date.now();gameOver=false;$('#log').textContent='Select a gold piece. Captures are mandatory.';render();if(mode==='online')void broadcast()}
function undo(){if(mode==='online'||!history.length)return;board=history.pop()!;turn='gold';selected=null;forcedFrom=null;gameOver=false;$('#log').textContent='Practice move restored.';render()}
function saveLocal(){localStorage.setItem('rb-rich-checkers-elite',JSON.stringify({board,turn,mode,difficulty,gameOver}))}
async function syncResult(result:string,score:number){if(!user)return;const duration=Math.max(1,Math.floor((Date.now()-started)/1000));await supabase.from('game_sessions').insert({game_id:GAME_ID,game_slug:GAME,user_id:user.id,username:profile?.username,display_name:profile?.display_name,ended_at:new Date().toISOString(),duration_seconds:duration,result,score,platform_type:'web',metadata:{mode,difficulty,gold:count('gold'),green:count('green')}});await supabase.from('game_scores').insert({game_id:GAME_ID,game_slug:GAME,user_id:user.id,username:profile?.username,display_name:profile?.display_name,score,mode,platform_type:'web',metadata:{result,difficulty}});const {data:o}=await supabase.from('game_player_progress').select('*').eq('game_id',GAME_ID).eq('user_id',user.id).maybeSingle();const xp=Number(o?.xp||0)+(result==='win'?180:55),wins=Number(o?.progress?.wins||0)+(result==='win'?1:0);await supabase.from('game_player_progress').upsert({game_id:GAME_ID,user_id:user.id,current_level:Math.floor(xp/600)+1,xp,best_score:Math.max(Number(o?.best_score||0),score),progress:{...(o?.progress||{}),wins,matches:Number(o?.progress?.matches||0)+1},settings:o?.settings||{},inventory:o?.inventory||{},achievements:o?.achievements||[],last_checkpoint:{mode,difficulty},total_play_seconds:Number(o?.total_play_seconds||0)+duration,last_played_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'game_id,user_id'});await supabase.rpc('rb_award_xp',{p_event_key:result==='win'?'game_win':'game_completed',p_section:'gaming',p_source_table:'game_scores',p_source_id:null,p_amount:result==='win'?180:55});await stats()}
async function stats(){const {data:s}=await supabase.from('game_scores').select('display_name,username,score').eq('game_slug',GAME).order('score',{ascending:false}).limit(8);$('#leaders').innerHTML=(s||[]).map((x:any,i)=>`<article><b>#${i+1}</b><span>${x.display_name||x.username||'Rich Player'}</span><strong>${Number(x.score||0).toLocaleString()}</strong></article>`).join('')||'<p class="rce-log">No ranked scores yet.</p>';if(user){const {data:p}=await supabase.from('game_player_progress').select('*').eq('game_id',GAME_ID).eq('user_id',user.id).maybeSingle();$('#xp').textContent=Number(p?.xp||0).toLocaleString();$('#best').textContent=Number(p?.best_score||0).toLocaleString();$('#wins').textContent=Number(p?.progress?.wins||0).toLocaleString()}}
async function createRoom(){if(!user)return $('#roomState').textContent='Tap In required.';const code=Math.random().toString(36).slice(2,8).toUpperCase();const {data:r,error}=await supabase.from('game_rooms').insert({room_code:code,game_key:GAME,host_user_id:user.id,status:'active',game_state:{board,turn}}).select().single();if(error)return $('#roomState').textContent=error.message;await supabase.from('game_room_members').insert({room_id:r.id,user_id:user.id,username:profile?.username,display_name:profile?.display_name,role:'host',status:'active'});room=r;$<HTMLInputElement>('#roomCode').value=code;$('#roomState').textContent=`ROOM ${code} OPEN`;subscribe()}
async function joinRoom(){if(!user)return $('#roomState').textContent='Tap In required.';const code=$<HTMLInputElement>('#roomCode').value.trim().toUpperCase();const {data:r}=await supabase.from('game_rooms').select('*').eq('room_code',code).eq('game_key',GAME).maybeSingle();if(!r)return $('#roomState').textContent='Room not found.';await supabase.from('game_room_members').insert({room_id:r.id,user_id:user.id,username:profile?.username,display_name:profile?.display_name,role:'player',status:'active'});room=r;mode='online';if(r.game_state?.board){board=r.game_state.board;turn=r.game_state.turn||'gold'}$('#roomState').textContent=`JOINED ${code}`;subscribe();render()}
function subscribe(){if(channel)void supabase.removeChannel(channel);channel=supabase.channel(`${GAME}:${room.id}`).on('broadcast',{event:'state'},({payload}:any)=>{if(payload?.user===user?.id)return;if(Array.isArray(payload?.board)){board=payload.board;turn=payload.turn;selected=null;forcedFrom=null;$('#log').textContent='REMOTE MOVE SYNCED';render()}}).subscribe(s=>$('#net').textContent=s==='SUBSCRIBED'?'REALTIME LIVE':s)}
async function broadcast(){if(channel)await channel.send({type:'broadcast',event:'state',payload:{board,turn,user:user?.id}});if(room)await supabase.from('game_rooms').update({game_state:{board,turn},updated_at:new Date().toISOString()}).eq('id',room.id)}
function leave(){if(channel)void supabase.removeChannel(channel);channel=null;room=null;$('#roomState').textContent='Left realtime room.';$('#net').textContent='OFFLINE READY'}
document.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode!;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(mode!=='online')leave();newGame()});
$('#difficulty').onchange=()=>{difficulty=$<HTMLSelectElement>('#difficulty').value};$('#newGame').onclick=newGame;$('#undo').onclick=undo;$('#createRoom').onclick=()=>void createRoom();$('#joinRoom').onclick=()=>void joinRoom();$('#leaveRoom').onclick=leave;
(async()=>{try{const s=JSON.parse(localStorage.getItem('rb-rich-checkers-elite')||'{}');if(Array.isArray(s.board)&&s.board.length===64){board=s.board;turn=s.turn||'gold';mode=s.mode||'solo';difficulty=s.difficulty||'elite';gameOver=!!s.gameOver}else board=initial()}catch{board=initial()}const {data:{session}}=await supabase.auth.getSession();user=session?.user||null;if(user){const {data:p}=await supabase.from('profiles').select('username,display_name').eq('id',user.id).maybeSingle();profile=p}await stats();render()})();
window.addEventListener('beforeunload',()=>{if(channel)void supabase.removeChannel(channel)});