import { supabase } from '../../core/supabase/client';
import './rich-chess.css';

type C='w'|'b'; type K='k'|'q'|'r'|'b'|'n'|'p'; type P={c:C;k:K}; type M={from:number;to:number;piece:P;capture?:P|null;promotion?:K};
const G='d23b71a5-86ea-4164-9057-7d688b9e1af6', icons={w:{k:'♔',q:'♕',r:'♖',b:'♗',n:'♘',p:'♙'},b:{k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'}} as const;
const vals:Record<K,number>={p:100,n:320,b:330,r:500,q:900,k:20000};
const name=(i:number)=>`${'abcdefgh'[i%8]}${8-Math.floor(i/8)}`;
const fresh=()=>{const b:Array<P|null>=Array(64).fill(null), back:K[]=['r','n','b','q','k','b','n','r'];for(let i=0;i<8;i++){b[i]={c:'b',k:back[i]};b[i+8]={c:'b',k:'p'};b[i+48]={c:'w',k:'p'};b[i+56]={c:'w',k:back[i]};}return b;};
let board=fresh(),turn:C='w',pick:number|null=null,legal:M[]=[],history:M[]=[],mode='solo',difficulty=2,over=false,last:M|null=null,user:any=null,profile:any=null,started=Date.now(),room:any=null,channel:any=null,flipped=false;
const root=document.querySelector<HTMLElement>('#app')!;
root.innerHTML=`<main class="rc-shell"><div class="rc-wrap"><header class="rc-top"><a href="/gaming.html">←</a><div class="rc-brand"><small>RICH BIZNESS ELITE GAME 01 / 24</small><h1>RICH CHESS</h1></div><span id="netState" class="rc-status">SYNCING</span></header><section class="rc-hero"><div class="rc-hero-copy"><small class="rc-kicker">SOLO • LOCAL • REALTIME MULTIPLAYER • OFFLINE</small><h2>CHECKMATE<br>THE EMPIRE.</h2><p>Playable legal chess with adaptive AI, local two-player, realtime rooms, offline saves, ranked scores and Rich XP.</p></div><div class="rc-hero-stats"><article><small>RICH XP</small><strong id="xp">0</strong></article><article><small>BEST</small><strong id="best">0</strong></article><article><small>WINS</small><strong id="wins">0</strong></article><article><small>MODE</small><strong id="modeStat">SOLO</strong></article></div></section><section class="rc-layout"><div class="rc-game"><div class="rc-board-shell"><div class="rc-player"><b id="blackName">RICH AI</b><span>BLACK</span></div><div id="board" class="rc-board"></div><div class="rc-player bottom"><b id="whiteName">YOU</b><span>WHITE</span></div></div><aside class="rc-side"><section class="rc-card"><h3>PLAY MODE</h3><div class="rc-mode"><button class="rc-btn active" data-mode="solo">SOLO</button><button class="rc-btn" data-mode="local">LOCAL</button><button class="rc-btn" data-mode="online">ONLINE</button></div><select id="difficulty" class="rc-select"><option value="1">ROOKIE AI</option><option value="2" selected>ELITE AI</option><option value="3">BOSS AI</option></select><div class="rc-controls"><button id="newGame" class="rc-btn primary">NEW GAME</button><button id="undo" class="rc-btn">UNDO</button><button id="resign" class="rc-btn danger">RESIGN</button><button id="flip" class="rc-btn">FLIP</button></div><p id="log" class="rc-log">Make the first move.</p></section><section class="rc-card"><h3>MOVE HISTORY</h3><div id="moves" class="rc-moves"></div></section></aside></div><aside class="rc-network"><section class="rc-card"><h3>ONLINE ROOM</h3><input id="roomCode" class="rc-input" maxlength="8" placeholder="ROOM CODE"><div class="rc-controls"><button id="createRoom" class="rc-btn primary">CREATE</button><button id="joinRoom" class="rc-btn">JOIN</button></div><p id="roomState" class="rc-log">Tap In required for realtime multiplayer.</p></section><section class="rc-card"><h3>ELITE LEADERBOARD</h3><div id="leaders" class="rc-leaderboard"></div></section><section class="rc-card"><h3>TOURNAMENT READY</h3><p class="rc-log">Verified sessions, ranked scores and Rich XP sync through Gaming.</p><a class="rc-btn primary" style="display:grid;place-items:center;text-decoration:none" href="/gaming.html">GAMING HQ</a></section></aside></section><footer class="rc-footer">RICH CHESS v1.0 • OFFLINE SAVE • SUPABASE REALTIME</footer></div></main>`;
const $=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
const valid=(r:number,c:number)=>r>=0&&r<8&&c>=0&&c<8;
function pseudo(b:Array<P|null>,from:number){const p=b[from];if(!p)return[] as M[];const out:M[]=[],r=Math.floor(from/8),c=from%8;const add=(rr:number,cc:number)=>{if(!valid(rr,cc))return false;const to=rr*8+cc,t=b[to];if(!t){out.push({from,to,piece:p});return true}if(t.c!==p.c)out.push({from,to,piece:p,capture:t});return false};if(p.k==='p'){const d=p.c==='w'?-1:1,s=p.c==='w'?6:1,one=(r+d)*8+c;if(valid(r+d,c)&&!b[one]){out.push({from,to:one,piece:p,promotion:r+d===0||r+d===7?'q':undefined});const two=(r+2*d)*8+c;if(r===s&&!b[two])out.push({from,to:two,piece:p})}for(const dc of[-1,1]){const rr=r+d,cc=c+dc;if(valid(rr,cc)){const to=rr*8+cc,t=b[to];if(t&&t.c!==p.c)out.push({from,to,piece:p,capture:t,promotion:rr===0||rr===7?'q':undefined})}}}if(p.k==='n')for(const[a,z]of[[2,1],[2,-1],[-2,1],[-2,-1],[1,2],[1,-2],[-1,2],[-1,-2]])add(r+a,c+z);if(p.k==='k')for(let a=-1;a<=1;a++)for(let z=-1;z<=1;z++)if(a||z)add(r+a,c+z);if('brq'.includes(p.k)){const ds:number[][]=[];if(p.k!=='r')ds.push([1,1],[1,-1],[-1,1],[-1,-1]);if(p.k!=='b')ds.push([1,0],[-1,0],[0,1],[0,-1]);for(const[a,z]of ds){let rr=r+a,cc=c+z;while(valid(rr,cc)){if(!add(rr,cc))break;rr+=a;cc+=z}}}return out}
function apply(b:Array<P|null>,m:M){const n=b.map(p=>p?{...p}:null);n[m.to]={...m.piece,k:m.promotion||m.piece.k};n[m.from]=null;return n}
function attacked(b:Array<P|null>,i:number,c:C){const e=c==='w'?'b':'w';return b.some((p,x)=>p?.c===e&&pseudo(b,x).some(m=>m.to===i))}
function check(b:Array<P|null>,c:C){const k=b.findIndex(p=>p?.c===c&&p.k==='k');return k>=0&&attacked(b,k,c)}
function all(b:Array<P|null>,c:C){const out:M[]=[];b.forEach((p,i)=>{if(p?.c===c)for(const m of pseudo(b,i))if(!check(apply(b,m),c))out.push(m)});return out}
function render(){const order=flipped?[...Array(64).keys()].reverse():[...Array(64).keys()],king=check(board,turn)?board.findIndex(p=>p?.c===turn&&p.k==='k'):-1;$('#board').innerHTML=order.map(i=>{const p=board[i],r=Math.floor(i/8),c=i%8,m=legal.find(x=>x.to===i);return `<button class="rc-square ${(r+c)%2?'dark':'light'} ${pick===i?'selected':''} ${m?(m.capture?'capture':'legal'):''} ${last&&(last.from===i||last.to===i)?'last':''} ${king===i?'in-check':''}" data-i="${i}">${p?`<span class="rc-piece ${p.c==='w'?'white':'black'}">${icons[p.c][p.k]}</span>`:''}<span class="rc-file">${r===7?'abcdefgh'[c]:''}</span></button>`}).join('');document.querySelectorAll<HTMLButtonElement>('[data-i]').forEach(b=>b.onclick=()=>tap(Number(b.dataset.i)));$('#moves').innerHTML=history.map((m,i)=>`<div class="rc-move"><b>${i+1}.</b> ${name(m.from)}→${name(m.to)}${m.capture?' ×':''}</div>`).join('')}
function tap(i:number){if(over||(mode==='solo'&&turn==='b'))return;const p=board[i];if(pick!==null){const m=legal.find(x=>x.to===i);if(m){void move(m,false);return}}if(p?.c===turn){pick=i;legal=all(board,turn).filter(m=>m.from===i)}else{pick=null;legal=[]}render()}
function score(b:Array<P|null>){return b.reduce((s,p)=>s+(p?(p.c==='w'?1:-1)*vals[p.k]:0),0)}
function ai(){const list=all(board,'b');if(!list.length)return;let best=list[0],low=Infinity;for(const m of list){let n=score(apply(board,m));if(difficulty>1){const reply=all(apply(board,m),'w');if(reply.length)n=Math.max(...reply.slice(0,30).map(x=>score(apply(apply(board,m),x))))}n+=Math.random()*15;if(n<low){low=n;best=m}}setTimeout(()=>void move(best,true),380)}
async function move(m:M,remote:boolean){board=apply(board,m);history.push(m);last=m;pick=null;legal=[];turn=turn==='w'?'b':'w';save();render();if(mode==='online'&&room&&!remote)await sendMove(m);const next=all(board,turn);if(!next.length){over=true;const result=check(board,turn)?`${turn==='w'?'BLACK':'WHITE'} WINS`:'STALEMATE';$('#log').textContent=result;await finish(result,result.includes('WHITE')?1200:result.includes('BLACK')?800:400);return}$('#log').textContent=`${turn==='w'?'WHITE':'BLACK'} TO MOVE${check(board,turn)?' — CHECK':''}`;if(mode==='solo'&&turn==='b')ai()}
function reset(){board=fresh();turn='w';pick=null;legal=[];history=[];last=null;over=false;started=Date.now();save();render();$('#log').textContent='New match started.'}
function save(){localStorage.setItem('rb-rich-chess',JSON.stringify({board,turn,history,last,mode,difficulty}))}
function restore(){try{const s=JSON.parse(localStorage.getItem('rb-rich-chess')||'null');if(s?.board?.length===64){board=s.board;turn=s.turn;history=s.history||[];last=s.last}}catch{}render()}
async function finish(result:string,points:number){if(!user)return;const duration=Math.floor((Date.now()-started)/1000);await supabase.from('game_sessions').insert({game_id:G,game_slug:'rich-chess',user_id:user.id,username:profile?.username,display_name:profile?.display_name,ended_at:new Date().toISOString(),duration_seconds:duration,result,score:points,platform_type:'web',metadata:{mode,moves:history.length}});await supabase.from('game_scores').insert({game_id:G,game_slug:'rich-chess',user_id:user.id,username:profile?.username,display_name:profile?.display_name,score:points,mode,platform_type:'web',metadata:{result,moves:history.length,duration}});await supabase.rpc('rb_award_xp',{p_event_key:points>=1000?'game_win':'game_completed',p_section:'gaming',p_source_table:'game_scores',p_source_id:null,p_amount:points>=1000?150:50});await progress(points,result.includes('WHITE'));await stats()}
async function progress(points:number,win:boolean){const {data:o}=await supabase.from('game_player_progress').select('*').eq('game_id',G).eq('user_id',user.id).maybeSingle();const xp=Number(o?.xp||0)+(win?150:50);await supabase.from('game_player_progress').upsert({game_id:G,user_id:user.id,current_level:Math.floor(xp/500)+1,xp,best_score:Math.max(Number(o?.best_score||0),points),progress:{...(o?.progress||{}),wins:Number(o?.progress?.wins||0)+(win?1:0),games:Number(o?.progress?.games||0)+1},settings:o?.settings||{},inventory:o?.inventory||{},achievements:o?.achievements||[],last_checkpoint:{board,turn,history},total_play_seconds:Number(o?.total_play_seconds||0)+Math.floor((Date.now()-started)/1000),last_played_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'game_id,user_id'})}
async function stats(){const {data:s}=await supabase.from('game_scores').select('display_name,username,score').eq('game_slug','rich-chess').order('score',{ascending:false}).limit(8);$('#leaders').innerHTML=(s||[]).map((x:any,i)=>`<article><b>#${i+1}</b><span>${x.display_name||x.username||'Rich Player'}</span><strong>${Number(x.score||0).toLocaleString()}</strong></article>`).join('')||'<p class="rc-log">No ranked scores yet.</p>';if(user){const {data:p}=await supabase.from('game_player_progress').select('*').eq('game_id',G).eq('user_id',user.id).maybeSingle();$('#xp').textContent=Number(p?.xp||0).toLocaleString();$('#best').textContent=Number(p?.best_score||0).toLocaleString();$('#wins').textContent=Number(p?.progress?.wins||0).toLocaleString()}}
async function createRoom(){if(!user)return $('#roomState').textContent='Tap In required.';const code=Math.random().toString(36).slice(2,8).toUpperCase();const {data:r,error}=await supabase.from('game_rooms').insert({room_code:code,game_key:'rich-chess',host_user_id:user.id,status:'active',current_turn:'w',board_state:board,game_state:{history:[]}}).select().single();if(error)return $('#roomState').textContent=error.message;await supabase.from('game_room_members').insert({room_id:r.id,user_id:user.id,username:profile?.username,display_name:profile?.display_name,role:'white',status:'active'});room={...r,color:'w'};($<HTMLInputElement>('#roomCode')).value=code;$('#roomState').textContent=`ROOM ${code} — WAITING`;subscribe()}
async function joinRoom(){if(!user)return $('#roomState').textContent='Tap In required.';const code=$<HTMLInputElement>('#roomCode').value.trim().toUpperCase();const {data:r}=await supabase.from('game_rooms').select('*').eq('room_code',code).eq('game_key','rich-chess').maybeSingle();if(!r)return $('#roomState').textContent='Room not found.';await supabase.from('game_room_members').insert({room_id:r.id,user_id:user.id,username:profile?.username,display_name:profile?.display_name,role:'black',status:'active'});room={...r,color:'b'};board=r.board_state||fresh();turn=r.current_turn||'w';history=r.game_state?.history||[];render();$('#roomState').textContent=`JOINED ${code} AS BLACK`;subscribe()}
function subscribe(){if(channel)void supabase.removeChannel(channel);channel=supabase.channel(`rich-chess:${room.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'game_moves',filter:`room_id=eq.${room.id}`},(x:any)=>{if(x.new.user_id===user.id)return;void move(x.new.move_data as M,true)}).subscribe()}
async function sendMove(m:M){await supabase.from('game_moves').insert({room_id:room.id,game_key:'rich-chess',user_id:user.id,username:profile?.username,display_name:profile?.display_name,move_number:history.length,move_data:m,from_square:name(m.from),to_square:name(m.to),piece:`${m.piece.c}${m.piece.k}`,captured_piece:m.capture?`${m.capture.c}${m.capture.k}`:null,turn:m.piece.c});if(room.color==='w')await supabase.from('game_rooms').update({current_turn:turn,board_state:board,game_state:{history},updated_at:new Date().toISOString()}).eq('id',room.id)}
async function boot(){const {data:{session}}=await supabase.auth.getSession();user=session?.user;if(user){profile=(await supabase.from('profiles').select('username,display_name').eq('id',user.id).maybeSingle()).data;$('#whiteName').textContent=profile?.display_name||profile?.username||'YOU';$('#netState').textContent='ONLINE SYNC'}else $('#netState').textContent='OFFLINE PLAY';restore();await stats()}
document.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode||'solo';document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));$('#modeStat').textContent=mode.toUpperCase();reset()});$<HTMLSelectElement>('#difficulty').onchange=e=>difficulty=Number((e.target as HTMLSelectElement).value);$('#newGame').onclick=reset;$('#undo').onclick=()=>{if(mode==='online'||!history.length)return;history.pop();if(mode==='solo'&&history.length)history.pop();const replay=[...history];board=fresh();history=[];turn='w';for(const m of replay){board=apply(board,m);history.push(m);turn=turn==='w'?'b':'w'}last=history.at(-1)||null;render();save()};$('#resign').onclick=()=>{over=true;$('#log').textContent='MATCH RESIGNED';void finish('RESIGN',0)};$('#flip').onclick=()=>{flipped=!flipped;render()};$('#createRoom').onclick=()=>void createRoom();$('#joinRoom').onclick=()=>void joinRoom();window.addEventListener('beforeunload',()=>{if(channel)void supabase.removeChannel(channel)});void boot();
