import { supabase } from '../../core/supabase/client';
import './smoke-room-cards.css';

type Card={r:string;s:string;v:number};
const GAME_ID='a7a3507e-cd4e-49e6-87cd-4b76a5c24290';
const GAME='smoke-room-cards';
const suits=['♠','♥','♦','♣'];
const ranks=[['A',11],['2',2],['3',3],['4',4],['5',5],['6',6],['7',7],['8',8],['9',9],['10',10],['J',10],['Q',10],['K',10]] as const;
const root=document.querySelector<HTMLElement>('#app')!;
let deck:Card[]=[],player:Card[]=[],dealer:Card[]=[],mode='solo',roundOver=true,hideDealer=true,streak=0,started=Date.now(),user:any=null,profile:any=null,room:any=null,channel:any=null;
const $=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
const shuffle=(cards:Card[])=>{for(let i=cards.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]]}return cards};
const newDeck=()=>shuffle(suits.flatMap(s=>ranks.map(([r,v])=>({r,s,v}))));
const total=(hand:Card[])=>{let n=hand.reduce((a,c)=>a+c.v,0),aces=hand.filter(c=>c.r==='A').length;while(n>21&&aces--){n-=10}return n};
const card=(c:Card,back=false,i=0)=>back?`<div class="src-playing-card back" style="--tilt:${(i-2)*2}deg">RB</div>`:`<div class="src-playing-card ${c.s==='♥'||c.s==='♦'?'red':''}" style="--tilt:${(i-2)*2}deg"><div>${c.r}${c.s}</div><div style="display:grid;place-items:center;height:70%;font-size:2em">${c.s}</div></div>`;
root.innerHTML=`<main class="src-shell"><div class="src-wrap"><header class="src-top"><a href="/gaming.html">←</a><div class="src-brand"><small>RICH BIZNESS ELITE GAME 02 / 24</small><h1>SMOKE ROOM CARDS</h1></div><span id="net" class="src-status">OFFLINE READY</span></header><section class="src-hero"><div><small class="src-kicker">SOLO • LOCAL • REALTIME ROOM • OFFLINE</small><h2>RUN<br>THE TABLE.</h2><p>Elite 21 card battles with dealer AI, local pass-and-play challenges, realtime rooms, ranked streaks, Rich XP, persistent progress and tournament-ready scores.</p></div><div class="src-stats"><article><small>RICH XP</small><strong id="xp">0</strong></article><article><small>BEST SCORE</small><strong id="best">0</strong></article><article><small>WINS</small><strong id="wins">0</strong></article><article><small>STREAK</small><strong id="streak">0</strong></article></div></section><section class="src-layout"><section class="src-table"><div class="src-seat src-dealer"><h3>HOUSE • <span id="dealerLabel">DEALER</span></h3><div id="dealerHand" class="src-hand"></div><div id="dealerScore" class="src-score">—</div></div><div class="src-pot"><small>RICH POT</small><strong id="pot">250</strong></div><div class="src-seat src-player"><h3 id="playerLabel">YOU • PLAYER</h3><div id="playerHand" class="src-hand"></div><div id="playerScore" class="src-score">0</div></div><div class="src-actions"><button id="deal" class="src-btn primary">DEAL</button><button id="hit" class="src-btn">HIT</button><button id="stand" class="src-btn">STAND</button><button id="double" class="src-btn">DOUBLE</button></div></section><aside class="src-side"><section class="src-card"><h3>PLAY MODE</h3><div class="src-modes"><button class="src-btn active" data-mode="solo">SOLO</button><button class="src-btn" data-mode="local">LOCAL</button><button class="src-btn" data-mode="online">ONLINE</button></div><select id="difficulty" class="src-select"><option value="rookie">ROOKIE HOUSE</option><option value="elite" selected>ELITE HOUSE</option><option value="boss">BOSS HOUSE</option></select><p id="log" class="src-log">Deal the first hand.</p></section><section class="src-card"><h3>ONLINE TABLE</h3><input id="roomCode" class="src-input" maxlength="8" placeholder="ROOM CODE"><div class="src-controls"><button id="createRoom" class="src-btn primary">CREATE</button><button id="joinRoom" class="src-btn">JOIN</button><button id="leaveRoom" class="src-btn">LEAVE</button></div><p id="roomState" class="src-log">Tap In required for realtime play.</p></section><section class="src-card"><h3>ELITE LEADERBOARD</h3><div id="leaders" class="src-board"></div></section></aside></section><footer class="src-footer">SMOKE ROOM CARDS v1.0 • OFFLINE SAVE • SUPABASE REALTIME • RICH XP</footer></div></main>`;
function render(){ $('#playerHand').innerHTML=player.map((c,i)=>card(c,false,i)).join('');$('#dealerHand').innerHTML=dealer.map((c,i)=>card(c,hideDealer&&i===1,i)).join('');$('#playerScore').textContent=String(total(player));$('#dealerScore').textContent=hideDealer&&dealer.length?'?':String(total(dealer));$('#streak').textContent=String(streak);const active=!roundOver;$('#hit').toggleAttribute('disabled',!active);$('#stand').toggleAttribute('disabled',!active);$('#double').toggleAttribute('disabled',!active||player.length!==2);saveLocal()}
function saveLocal(){localStorage.setItem('rb-smoke-room-cards',JSON.stringify({streak,mode}))}
function start(){deck=newDeck();player=[deck.pop()!,deck.pop()!];dealer=[deck.pop()!,deck.pop()!];roundOver=false;hideDealer=true;started=Date.now();$('#log').textContent='Your move. Chase 21 without busting.';render();if(total(player)===21)void finishRound()}
function draw(){if(roundOver)return;player.push(deck.pop()!);render();if(total(player)>=21)void finishRound()}
async function stand(){if(roundOver)return;hideDealer=false;const level=($<HTMLSelectElement>('#difficulty')).value;const stop=level==='rookie'?16:level==='boss'?18:17;while(total(dealer)<stop)dealer.push(deck.pop()!);await finishRound()}
async function finishRound(){roundOver=true;hideDealer=false;const p=total(player),d=total(dealer);let result='push',score=250;if(p>21){result='loss';score=100}else if(d>21||p>d){result='win';score=1000+Math.max(0,21-p)*50+streak*100;streak++}else if(p<d){result='loss';score=100;streak=0}else{score=400}$('#log').textContent=result==='win'?'YOU RAN THE TABLE.':result==='loss'?'THE HOUSE TOOK THIS ROUND.':'PUSH — RUN IT BACK.';$('#pot').textContent=String(score);render();await syncResult(result,score);if(mode==='online'&&room)await broadcast({type:'result',player,dealer,result,score,streak})}
async function syncResult(result:string,score:number){if(!user)return;const duration=Math.max(1,Math.floor((Date.now()-started)/1000));await supabase.from('game_sessions').insert({game_id:GAME_ID,game_slug:GAME,user_id:user.id,username:profile?.username,display_name:profile?.display_name,ended_at:new Date().toISOString(),duration_seconds:duration,result,score,platform_type:'web',metadata:{mode,player_total:total(player),dealer_total:total(dealer),streak}});await supabase.from('game_scores').insert({game_id:GAME_ID,game_slug:GAME,user_id:user.id,username:profile?.username,display_name:profile?.display_name,score,mode,platform_type:'web',metadata:{result,streak,duration}});const {data:o}=await supabase.from('game_player_progress').select('*').eq('game_id',GAME_ID).eq('user_id',user.id).maybeSingle();const xp=Number(o?.xp||0)+(result==='win'?125:40),wins=Number(o?.progress?.wins||0)+(result==='win'?1:0);await supabase.from('game_player_progress').upsert({game_id:GAME_ID,user_id:user.id,current_level:Math.floor(xp/500)+1,xp,best_score:Math.max(Number(o?.best_score||0),score),progress:{...(o?.progress||{}),wins,games:Number(o?.progress?.games||0)+1,best_streak:Math.max(Number(o?.progress?.best_streak||0),streak)},settings:o?.settings||{},inventory:o?.inventory||{},achievements:o?.achievements||[],last_checkpoint:{streak,mode},total_play_seconds:Number(o?.total_play_seconds||0)+duration,last_played_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'game_id,user_id'});await supabase.rpc('rb_award_xp',{p_event_key:result==='win'?'game_win':'game_completed',p_section:'gaming',p_source_table:'game_scores',p_source_id:null,p_amount:result==='win'?125:40});await stats()}
async function stats(){const {data:s}=await supabase.from('game_scores').select('display_name,username,score').eq('game_slug',GAME).order('score',{ascending:false}).limit(8);$('#leaders').innerHTML=(s||[]).map((x:any,i)=>`<article><b>#${i+1}</b><span>${x.display_name||x.username||'Rich Player'}</span><strong>${Number(x.score||0).toLocaleString()}</strong></article>`).join('')||'<p class="src-log">No ranked scores yet.</p>';if(user){const {data:p}=await supabase.from('game_player_progress').select('*').eq('game_id',GAME_ID).eq('user_id',user.id).maybeSingle();$('#xp').textContent=Number(p?.xp||0).toLocaleString();$('#best').textContent=Number(p?.best_score||0).toLocaleString();$('#wins').textContent=Number(p?.progress?.wins||0).toLocaleString()}}
async function createRoom(){if(!user)return $('#roomState').textContent='Tap In required.';const code=Math.random().toString(36).slice(2,8).toUpperCase();const {data:r,error}=await supabase.from('game_rooms').insert({room_code:code,game_key:GAME,host_user_id:user.id,status:'active',game_state:{}}).select().single();if(error)return $('#roomState').textContent=error.message;await supabase.from('game_room_members').insert({room_id:r.id,user_id:user.id,username:profile?.username,display_name:profile?.display_name,role:'host',status:'active'});room=r;($<HTMLInputElement>('#roomCode')).value=code;$('#roomState').textContent=`TABLE ${code} OPEN`;subscribe()}
async function joinRoom(){if(!user)return $('#roomState').textContent='Tap In required.';const code=$<HTMLInputElement>('#roomCode').value.trim().toUpperCase();const {data:r}=await supabase.from('game_rooms').select('*').eq('room_code',code).eq('game_key',GAME).maybeSingle();if(!r)return $('#roomState').textContent='Table not found.';await supabase.from('game_room_members').insert({room_id:r.id,user_id:user.id,username:profile?.username,display_name:profile?.display_name,role:'player',status:'active'});room=r;$('#roomState').textContent=`JOINED TABLE ${code}`;subscribe()}
function subscribe(){if(channel)void supabase.removeChannel(channel);channel=supabase.channel(`${GAME}:${room.id}`).on('broadcast',{event:'state'},({payload}:any)=>{if(payload?.user===user?.id)return;if(payload?.type==='result'){player=payload.player;dealer=payload.dealer;hideDealer=false;roundOver=true;streak=payload.streak||0;$('#log').textContent='REMOTE ROUND SYNCED';render()}}).subscribe(s=>$('#net').textContent=s==='SUBSCRIBED'?'REALTIME LIVE':s)}
async function broadcast(payload:any){if(channel)await channel.send({type:'broadcast',event:'state',payload:{...payload,user:user?.id}})}
function leave(){if(channel)void supabase.removeChannel(channel);channel=null;room=null;$('#roomState').textContent='Left realtime table.';$('#net').textContent='OFFLINE READY'}
document.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode!;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#log').textContent=`${mode.toUpperCase()} MODE READY`;if(mode!=='online')leave()});
$('#deal').onclick=start;$('#hit').onclick=draw;$('#stand').onclick=()=>void stand();$('#double').onclick=()=>{draw();if(!roundOver)void stand()};$('#createRoom').onclick=()=>void createRoom();$('#joinRoom').onclick=()=>void joinRoom();$('#leaveRoom').onclick=leave;
(async()=>{try{const saved=JSON.parse(localStorage.getItem('rb-smoke-room-cards')||'{}');streak=Number(saved.streak||0)}catch{}const {data:{session}}=await supabase.auth.getSession();user=session?.user||null;if(user){const {data:p}=await supabase.from('profiles').select('username,display_name').eq('id',user.id).maybeSingle();profile=p;$('#playerLabel').textContent=`${p?.display_name||p?.username||'YOU'} • PLAYER`}await stats();render()})();
window.addEventListener('beforeunload',()=>{if(channel)void supabase.removeChannel(channel)});