import { supabase } from '../../src/supabase-client.js';
import { getAuthoritativeIdentity } from '../../src/rb-identity.js?v=profile-avatar-separate-1';
import { awardXp } from '../../src/rb-xp.js?v=xp-idempotent-1';

const $=id=>document.getElementById(id),canvas=$('game'),g=canvas.getContext('2d');
let hole=1,strokes=0,score=0,wind=0,power=0,charging=false,aim=0,ball={x:170,y:420,vx:0,vy:0,moving:false},target={x:820,y:330},user=null,profile=null,finished=false;
const missions={underPar:false,perfect:false,finish:false};
function sync(){
  $('hole').textContent=hole;$('strokes').textContent=strokes;$('score').textContent=score;$('wind').textContent=`${wind>0?'+':''}${wind}`;$('powerFill').style.width=`${power}%`;
  $('missionUnder').textContent=missions.underPar?'DONE':'OPEN';$('missionPerfect').textContent=missions.perfect?'DONE':'OPEN';$('missionFinish').textContent=missions.finish?'DONE':'OPEN';
}
function resetHole(){power=0;aim=0;wind=Math.round(Math.random()*12-6);ball={x:170,y:420,vx:0,vy:0,moving:false};target={x:760+Math.random()*100,y:300+Math.random()*70};finished=false;sync()}
function resetGame(){hole=1;strokes=0;score=0;missions.underPar=false;missions.perfect=false;missions.finish=false;resetHole();$('status').textContent='READY TO TEE OFF'}
function swing(){if(ball.moving||finished)return;strokes++;const accuracy=1-Math.abs(power-82)/82;const angle=(-0.68)+(aim*0.012);const speed=8+power*.16;ball.vx=Math.cos(angle)*speed+wind*.08;ball.vy=Math.sin(angle)*speed;ball.moving=true;if(power>=79&&power<=85){missions.perfect=true;score+=250;$('status').textContent='PERFECT GREEN RELEASE'}else $('status').textContent='BALL IN FLIGHT';power=0;sync()}
function finishHole(){finished=true;const par=3,delta=strokes-par;score+=Math.max(200,1200-delta*250);if(strokes<=par)missions.underPar=true;if(hole>=9){missions.finish=true;$('status').textContent='COURSE COMPLETE';saveRun();return}hole++;setTimeout(()=>{strokes=0;resetHole();$('status').textContent=`HOLE ${hole} READY`},900)}
function physics(){if(ball.moving){ball.vy+=.28;ball.x+=ball.vx;ball.y+=ball.vy;ball.vx*=.992;if(ball.y>430){ball.y=430;ball.vy*=-.34;ball.vx*=.76;if(Math.abs(ball.vx)<.45){ball.moving=false;if(Math.hypot(ball.x-target.x,ball.y-target.y)<42)finishHole();else $('status').textContent='LINE UP THE NEXT SHOT'}}if(ball.x<20||ball.x>940){ball.moving=false;score=Math.max(0,score-150);$('status').textContent='OUT OF BOUNDS'}}}
function draw(){g.clearRect(0,0,960,540);const sky=g.createLinearGradient(0,0,0,270);sky.addColorStop(0,'#79c9ff');sky.addColorStop(1,'#d9f3ff');g.fillStyle=sky;g.fillRect(0,0,960,270);g.fillStyle='#245b2c';g.fillRect(0,270,960,270);g.fillStyle='#3fa34d';g.beginPath();g.ellipse(520,390,460,145,0,0,Math.PI*2);g.fill();g.fillStyle='#70c565';g.beginPath();g.ellipse(target.x,target.y+95,130,64,0,0,Math.PI*2);g.fill();g.fillStyle='#061006';g.beginPath();g.ellipse(target.x,target.y+95,14,7,0,0,Math.PI*2);g.fill();g.strokeStyle='#ffe58a';g.lineWidth=4;g.beginPath();g.moveTo(target.x,target.y+95);g.lineTo(target.x,target.y);g.stroke();g.fillStyle='#ffe58a';g.beginPath();g.moveTo(target.x,target.y);g.lineTo(target.x+46,target.y+14);g.lineTo(target.x,target.y+28);g.fill();g.fillStyle='#fff';g.beginPath();g.arc(ball.x,ball.y,12,0,Math.PI*2);g.fill();g.strokeStyle='rgba(255,229,138,.8)';g.lineWidth=3;g.beginPath();g.moveTo(ball.x,ball.y);g.lineTo(ball.x+110*Math.cos(-.68+aim*.012),ball.y+110*Math.sin(-.68+aim*.012));g.stroke();g.fillStyle='rgba(0,0,0,.55)';g.fillRect(20,20,250,54);g.fillStyle='#fff';g.font='bold 20px system-ui';g.fillText(`HOLE ${hole} • PAR 3`,38,54)}
function loop(){if(charging){power+=1.4;if(power>=100)power=0;sync()}physics();draw();requestAnimationFrame(loop)}
async function saveRun(){const state=await getAuthoritativeIdentity().catch(()=>({}));user=state.user||null;profile=state.profile||null;if(!user)return;const game=(await supabase.from('games').select('id').eq('slug','golf-green-gold').maybeSingle()).data;await supabase.from('game_sessions').insert({game_id:game?.id||null,game_slug:'golf-green-gold',user_id:user.id,username:profile?.username||null,display_name:profile?.display_name||null,score,result:'completed',platform_type:'web',metadata:{holes:hole,strokes,missions,verified:true,source:'games/golf-green-gold'}});await supabase.from('game_scores').insert({game_id:game?.id||null,game_slug:'golf-green-gold',user_id:user.id,username:profile?.username||null,display_name:profile?.display_name||null,score,is_verified:true,platform_type:'web',metadata:{holes:hole,strokes,source:'games/golf-green-gold'}});await awardXp('golf_green_gold_round',{section:'gaming',sourceTable:'games',sourceId:game?.id});loadBoard()}
async function loadBoard(){const {data}=await supabase.from('game_scores').select('display_name,username,score').eq('game_slug','golf-green-gold').eq('is_verified',true).order('score',{ascending:false}).limit(5);$('leaders').innerHTML=(data||[]).map((r,i)=>`<div class="leader"><b>#${i+1} ${r.display_name||r.username||'Rich Golfer'}</b><small>${Number(r.score||0).toLocaleString()} pts</small></div>`).join('')||'<div class="leader">No scores yet.</div>'}
$('charge').addEventListener('pointerdown',()=>charging=true);addEventListener('pointerup',()=>charging=false);$('swing').onclick=swing;$('left').onclick=()=>{aim=Math.max(-18,aim-2)};$('right').onclick=()=>{aim=Math.min(18,aim+2)};$('restart').onclick=resetGame;addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();if(e.repeat){charging=true}else if(!charging){charging=true}}if(e.key==='ArrowLeft')aim=Math.max(-18,aim-2);if(e.key==='ArrowRight')aim=Math.min(18,aim+2)});addEventListener('keyup',e=>{if(e.code==='Space'){charging=false;swing()}});
resetGame();loadBoard();loop();