import { supabase } from '../../core/supabase/client';
import '../../styles/deep-sections.css';

const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c));
const when=(v:unknown)=>v?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(String(v))):'';

export async function mount():Promise<void>{
 const root=document.querySelector<HTMLElement>('#app');if(!root)throw new Error('Missing #app');
 const {data:{session}}=await supabase.auth.getSession();if(!session){location.replace('/tap-in.html?next=/admin.html');return;}
 const {data:isAdmin}=await supabase.rpc('rb_is_admin',{p_min_permission:1});if(!isAdmin){root.innerHTML='<main class="deep-shell"><div class="deep-wrap"><header class="deep-top"><a href="/portal.html">←</a><div><p>RICH BIZNESS SECURITY</p><h1>Restricted</h1></div></header><section class="deep-hero"><div><small>ADMIN ACCESS REQUIRED</small><h2>FOUNDER GATE</h2><p>This command center is protected by Supabase admin roles and permission levels.</p></div></section></div></main>';return;}
 root.innerHTML=`<main class="deep-shell"><div class="deep-wrap"><header class="deep-top"><a href="/portal.html">←</a><div><p>RICH BIZNESS PLATFORM OPERATIONS</p><h1>Admin Core</h1></div><span class="deep-live">SECURE</span></header><section class="deep-hero"><div><small>MODERATION • HEALTH • JOBS • FLAGS • ANALYTICS</small><h2>CONTROL THE UNIVERSE</h2><p>One secured operations center connected to every administrative, moderation, trust, API, system-health, and platform-control table.</p><div class="deep-actions"><button id="refresh" class="deep-btn primary">REFRESH SYSTEM</button><a class="deep-btn" href="/notifications.html">ADMIN ALERTS</a></div></div></section><section id="stats" class="deep-stats"></section><nav id="tabs" class="deep-tabs"></nav><section id="content"></section><p id="status" class="deep-status"></p></div></main>`;
 const stats=document.querySelector<HTMLElement>('#stats')!,tabs=document.querySelector<HTMLElement>('#tabs')!,content=document.querySelector<HTMLElement>('#content')!,status=document.querySelector<HTMLElement>('#status')!;
 let lane='overview',reviews:any[]=[],reports:any[]=[],health:any[]=[],jobs:any[]=[],requests:any[]=[],webhooks:any[]=[],flags:any[]=[],announcements:any[]=[],audits:any[]=[],trust:any[]=[],analytics:any[]=[],roles:any[]=[];
 const setStatus=(v:string)=>{status.textContent=v;setTimeout(()=>{if(status.textContent===v)status.textContent=''},2600)};
 const lanes=[['overview','OVERVIEW'],['moderation','MODERATION'],['systems','SYSTEMS'],['platform','PLATFORM'],['audit','AUDIT + TRUST'],['roles','ROLES']];
 const badge=(v:string)=>`<span class="deep-badge ${['failed','critical','rejected','escalated','open'].includes(v)?'danger':['pending','queued','warning'].includes(v)?'warn':''}">${esc(v.toUpperCase())}</span>`;
 const renderTabs=()=>{tabs.innerHTML=lanes.map(([k,l])=>`<button class="deep-tab ${lane===k?'active':''}" data-lane="${k}">${l}</button>`).join('');tabs.querySelectorAll<HTMLButtonElement>('[data-lane]').forEach(b=>b.onclick=()=>{lane=b.dataset.lane!;renderTabs();render();});};
 const render=()=>{stats.innerHTML=`<article><small>PENDING REVIEW</small><strong>${reviews.filter(r=>r.status==='pending').length}</strong></article><article><small>OPEN REPORTS</small><strong>${reports.filter(r=>!['resolved','dismissed'].includes(r.status)).length}</strong></article><article><small>FAILED JOBS</small><strong>${jobs.filter(j=>j.status==='failed').length}</strong></article><article><small>ACTIVE FLAGS</small><strong>${flags.filter(f=>f.is_enabled).length}</strong></article>`;
 if(lane==='overview')content.innerHTML=`<section class="deep-grid">${[['Review Queue',reviews.length,'content_review_queue'],['Moderation Reports',reports.length,'moderation_reports'],['System Checks',health.length,'system_health_checks'],['API Jobs',jobs.length,'api_jobs'],['Webhook Events',webhooks.length,'api_webhook_events'],['Analytics Events',analytics.length,'platform_analytics_events'],['Feature Flags',flags.length,'feature_flags'],['Audit Logs',audits.length,'admin_audit_logs']].map(([t,n,s])=>`<article class="deep-card"><div class="deep-card-body"><span class="deep-badge">${esc(s)}</span><h3>${esc(t)}</h3><p>${Number(n).toLocaleString()} loaded records</p></div></article>`).join('')}</section>`;
 else if(lane==='moderation')content.innerHTML=`<section class="deep-section"><header><div><small>CONTENT REVIEW</small><h2>Moderation queue</h2></div></header><div class="deep-list">${reviews.length?reviews.map(r=>`<article><div><h3>${esc(r.review_type||r.target_table||'Content review')}</h3><p>${esc(r.flagged_reason||r.admin_note||r.target_id)} · ${when(r.created_at)}</p></div><div class="deep-actions">${badge(r.status||'pending')}<button class="deep-btn" data-review="approved" data-id="${r.id}">APPROVE</button><button class="deep-btn deep-danger" data-review="rejected" data-id="${r.id}">REJECT</button></div></article>`).join(''):'<div class="deep-empty">Review queue clear.</div>'}</div></section><section class="deep-section"><header><div><small>USER REPORTS</small><h2>Moderation reports</h2></div></header><div class="deep-list">${reports.length?reports.map(r=>`<article><div><h3>${esc(r.reason||'Report')}</h3><p>${esc(r.details||r.target_table||'')} · ${when(r.created_at)}</p></div>${badge(r.status||'open')}</article>`).join(''):'<div class="deep-empty">No active reports.</div>'}</div></section>`;
 else if(lane==='systems')content.innerHTML=`<section class="deep-section"><header><div><small>SERVICE HEALTH</small><h2>System checks</h2></div></header><div class="deep-list">${health.map(h=>`<article><div><h3>${esc(h.service)}</h3><p>${esc(h.message||'No message')} · ${h.latency_ms??0}ms · ${when(h.checked_at)}</p></div>${badge(h.status||'unknown')}</article>`).join('')||'<div class="deep-empty">No health data.</div>'}</div></section><section class="deep-section"><header><div><small>PROCESSING</small><h2>Jobs + webhooks</h2></div></header><div class="deep-list">${[...jobs.map(j=>({title:j.job_type,sub:j.error_message||j.target_table,state:j.status,time:j.created_at})),...webhooks.map(w=>({title:`${w.provider}: ${w.event_type}`,sub:w.error_message||w.event_id,state:w.status,time:w.created_at}))].map(r=>`<article><div><h3>${esc(r.title)}</h3><p>${esc(r.sub)} · ${when(r.time)}</p></div>${badge(r.state||'unknown')}</article>`).join('')||'<div class="deep-empty">No jobs or webhook events.</div>'}</div></section>`;
 else if(lane==='platform')content.innerHTML=`<section class="deep-section"><header><div><small>FEATURE CONTROL</small><h2>Flags</h2></div></header><div class="deep-list">${flags.map(f=>`<article><div><h3>${esc(f.title||f.flag_key)}</h3><p>${esc(f.description||f.section||'global')} · rollout ${f.rollout_percent??100}%</p></div><button class="deep-btn ${f.is_enabled?'primary':''}" data-flag="${f.id}" data-enabled="${String(!f.is_enabled)}">${f.is_enabled?'ENABLED':'DISABLED'}</button></article>`).join('')||'<div class="deep-empty">No feature flags.</div>'}</div></section><section class="deep-section"><header><div><small>ANNOUNCEMENTS</small><h2>Platform broadcasts</h2></div></header><div class="deep-list">${announcements.map(a=>`<article><div><h3>${esc(a.emoji||'')} ${esc(a.title)}</h3><p>${esc(a.body||'')} · ${esc(a.priority||'normal')}</p></div>${badge(a.is_active?'active':'inactive')}</article>`).join('')||'<div class="deep-empty">No announcements.</div>'}</div></section>`;
 else if(lane==='audit')content.innerHTML=`<section class="deep-section"><header><div><small>ADMIN AUDIT</small><h2>Recent actions</h2></div></header><div class="deep-list">${audits.map(a=>`<article><div><h3>${esc(a.action)}</h3><p>${esc(a.target_table||'platform')} · ${when(a.created_at)}</p></div>${badge(a.severity||'normal')}</article>`).join('')||'<div class="deep-empty">No audit records.</div>'}</div></section><section class="deep-section"><header><div><small>TRUST NETWORK</small><h2>Trust events</h2></div></header><div class="deep-list">${trust.map(t=>`<article><div><h3>${esc(t.event_type)}</h3><p>${esc(t.reason||t.target_table||'')} · ${when(t.created_at)}</p></div><strong class="${Number(t.score_delta)<0?'deep-danger':''}">${Number(t.score_delta)>0?'+':''}${t.score_delta??0}</strong></article>`).join('')||'<div class="deep-empty">No trust events.</div>'}</div></section>`;
 else content.innerHTML=`<section class="deep-section"><header><div><small>ADMIN RBAC</small><h2>Roles and permissions</h2></div></header><div class="deep-list">${roles.map(r=>`<article><div><h3>${esc(r.role_label||r.role_key)}</h3><p>Level ${r.permission_level??0} · users ${r.can_manage_users?'yes':'no'} · money ${r.can_manage_money?'yes':'no'} · platform ${r.can_manage_platform?'yes':'no'}</p></div>${badge(r.is_active?'active':'inactive')}</article>`).join('')||'<div class="deep-empty">No admin roles.</div>'}</div></section>`;
 content.querySelectorAll<HTMLButtonElement>('[data-review]').forEach(b=>b.onclick=async()=>{const {error}=await supabase.from('content_review_queue').update({status:b.dataset.review,reviewed_by:session.user.id,reviewed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',b.dataset.id!);if(error)setStatus(error.message);else{setStatus(`REVIEW ${b.dataset.review?.toUpperCase()}`);await load();}});content.querySelectorAll<HTMLButtonElement>('[data-flag]').forEach(b=>b.onclick=async()=>{const {error}=await supabase.from('feature_flags').update({is_enabled:b.dataset.enabled==='true',updated_at:new Date().toISOString()}).eq('id',b.dataset.flag!);if(error)setStatus(error.message);else await load();});};
 const load=async()=>{const q=await Promise.all([supabase.from('content_review_queue').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('moderation_reports').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('system_health_checks').select('*').order('checked_at',{ascending:false}).limit(50),supabase.from('api_jobs').select('*').order('created_at',{ascending:false}).limit(80),supabase.from('api_request_logs').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('api_webhook_events').select('*').order('created_at',{ascending:false}).limit(80),supabase.from('feature_flags').select('*').order('flag_key'),supabase.from('platform_announcements').select('*').order('created_at',{ascending:false}).limit(40),supabase.from('admin_audit_logs').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('trust_events').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('platform_analytics_events').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('admin_roles').select('*').order('permission_level',{ascending:false})]);[reviews,reports,health,jobs,requests,webhooks,flags,announcements,audits,trust,analytics,roles]=q.map(x=>x.data??[]);render();};
 document.querySelector<HTMLButtonElement>('#refresh')!.onclick=()=>void load();renderTabs();await load();
}
