import { supabase } from '../../core/supabase/client';
import '../../styles/media-universe.css';

type Row=Record<string,any>;
const esc=(v:any)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c));
const fmt=(n:any)=>Number(n??0).toLocaleString();

export async function mount():Promise<void>{
 const root=document.querySelector<HTMLElement>('#app');if(!root)throw new Error('Missing #app mount');
 const {data:{session}}=await supabase.auth.getSession();if(!session){location.replace('/tap-in.html?next=%2Fmusic.html');return;}
 const {data,error}=await supabase.rpc('rb_media_universe_snapshot',{});if(error)throw error;
 const snap=(data??{}) as Row;const lanes={tracks:snap.tracks??[],podcasts:snap.podcasts??[],radio:snap.radio??[],playlists:snap.playlists??[]} as Record<string,Row[]>;
 let lane='tracks';let active:Row|null=lanes.tracks[0]??lanes.podcasts[0]??lanes.radio[0]??null;
 root.innerHTML=`<main class="universe-shell"><div class="universe-wrap"><header class="universe-head"><a href="/portal.html">←</a><div><p>RICH BIZNESS AUDIO NETWORK</p><h1>MUSIC UNIVERSE</h1></div><span class="universe-sync">HI-FI</span></header>
 <section id="audioHero" class="universe-hero">${active?renderHero(active,lane):'<div class="universe-empty">No audio has been released.</div>'}</section>
 <section class="universe-metrics"><article><small>TRACKS</small><strong>${lanes.tracks.length}</strong></article><article><small>PODCASTS</small><strong>${lanes.podcasts.length}</strong></article><article><small>RADIO</small><strong>${lanes.radio.filter(r=>r.is_live).length} LIVE</strong></article><article><small>PLAYLISTS</small><strong>${lanes.playlists.length}</strong></article></section>
 <nav class="universe-tabs">${[['tracks','TRACKS'],['podcasts','PODCAST'],['radio','RADIO'],['playlists','PLAYLISTS']].map(([v,l],i)=>`<button class="universe-tab ${i===0?'active':''}" data-lane="${v}">${l}</button>`).join('')}</nav>
 <section class="universe-section"><header><div><h2 id="audioLaneTitle">New Music</h2><p>Independent drops, creator podcasts, live radio and premium playlists.</p></div><a class="universe-btn" href="/upload.html?section=music">DROP AUDIO</a></header><div id="audioGrid" class="universe-grid"></div></section>
 <section class="universe-side-grid universe-section"><article class="universe-panel"><header><h3>Top Rotation</h3></header><div id="audioRotation" class="universe-list"></div></article><article class="universe-panel"><header><h3>Now Playing Details</h3></header><div id="audioDetail" class="universe-list"></div></article></section>
 <aside id="audioPlayer" class="universe-player" hidden><img id="playerCover" alt=""><div><h3 id="playerTitle"></h3><p id="playerMeta"></p></div><audio id="playerAudio" controls preload="metadata"></audio></aside>
 </div></main>`;
 const grid=document.querySelector<HTMLElement>('#audioGrid')!;const rotation=document.querySelector<HTMLElement>('#audioRotation')!;const detail=document.querySelector<HTMLElement>('#audioDetail')!;const player=document.querySelector<HTMLElement>('#audioPlayer')!;const audio=document.querySelector<HTMLAudioElement>('#playerAudio')!;
 const laneTitle:Record<string,string>={tracks:'New Music',podcasts:'Podcast Network',radio:'Live Radio',playlists:'Curated Playlists'};
 const render=()=>{const rows=lanes[lane];document.querySelector<HTMLElement>('#audioLaneTitle')!.textContent=laneTitle[lane];grid.innerHTML=rows.length?rows.map(r=>`<article class="universe-card" data-id="${r.id}"><div class="universe-card__art"><img src="${esc(r.cover_url||'/images/brand/IMG_5997.png')}" alt=""><span class="universe-card__badge">${lane==='radio'?(r.is_live?'● LIVE':'STATION'):lane==='podcasts'?`EP ${r.episode_number??'—'}`:lane==='playlists'?'PLAYLIST':esc(r.genre||'TRACK')}</span></div><div class="universe-card__body"><h3>${esc(r.title||r.station_name||'Rich Audio')}</h3><p>${esc(r.display_name||r.show_title||r.station_tag||r.description||'Rich Creator')}</p><div class="universe-card__meta"><span>${fmt(r.play_count??r.listener_count)} plays</span><span>${fmt(r.like_count)} likes</span></div></div></article>`).join(''):'<div class="universe-empty">Nothing in this lane yet.</div>';grid.querySelectorAll<HTMLElement>('[data-id]').forEach(el=>el.onclick=()=>{const row=rows.find(r=>String(r.id)===el.dataset.id);if(row)void open(row);});rotation.innerHTML=[...rows].sort((a,b)=>Number(b.play_count??b.listener_count)-Number(a.play_count??a.listener_count)).slice(0,8).map((r,i)=>`<div class="universe-row" data-id="${r.id}"><img src="${esc(r.cover_url||'/images/brand/IMG_5997.png')}" alt=""><div><h4>${i+1}. ${esc(r.title||r.station_name)}</h4><p>${esc(r.display_name||r.show_title||r.genre||r.category||'Rich Audio')}</p></div><strong>${fmt(r.play_count??r.listener_count)}</strong></div>`).join('')||'<div class="universe-empty">No rotation data.</div>';rotation.querySelectorAll<HTMLElement>('[data-id]').forEach(el=>el.onclick=()=>{const row=rows.find(r=>String(r.id)===el.dataset.id);if(row)void open(row);});};
 const open=async(r:Row)=>{active=r;const src=r.audio_url||r.stream_url||'';document.querySelector<HTMLElement>('#audioHero')!.innerHTML=renderHero(r,lane);detail.innerHTML=`<div class="universe-row"><img src="${esc(r.cover_url||'/images/brand/IMG_5997.png')}" alt=""><div><h4>${esc(r.title||r.station_name)}</h4><p>${esc(r.description||r.genre||r.category||'Rich Audio')}</p></div><strong>${lane.toUpperCase()}</strong></div><div class="universe-row"><div><h4>Performance</h4><p>${fmt(r.play_count??r.listener_count)} plays · ${fmt(r.like_count)} likes · ${fmt(r.comment_count)} comments</p></div><strong>${r.is_explicit?'EXPLICIT':'CLEAN'}</strong></div><div class="universe-row"><div><h4>Audio Identity</h4><p>${esc(r.mood||r.visualizer_style||r.color_theme||'Emerald Gold')}</p></div><strong>${r.duration_seconds?`${Math.floor(r.duration_seconds/60)}:${String(r.duration_seconds%60).padStart(2,'0')}`:'LIVE'}</strong></div>`;if(src){player.hidden=false;document.querySelector<HTMLImageElement>('#playerCover')!.src=r.cover_url||'/images/brand/IMG_5997.png';document.querySelector<HTMLElement>('#playerTitle')!.textContent=r.title||r.station_name||'Rich Audio';document.querySelector<HTMLElement>('#playerMeta')!.textContent=r.display_name||r.show_title||r.station_tag||lane;audio.src=src;await audio.play().catch(()=>{});if(lane==='tracks')await supabase.from('music_play_events').insert({track_id:r.id,user_id:session.user.id,session_id:crypto.randomUUID(),seconds_played:0,completed:false});if(lane==='radio')await supabase.from('radio_sessions').insert({station_id:r.id,user_id:session.user.id,joined_at:new Date().toISOString(),listen_seconds:0});}};
 document.querySelectorAll<HTMLButtonElement>('[data-lane]').forEach(b=>b.onclick=()=>{lane=b.dataset.lane!;document.querySelectorAll('[data-lane]').forEach(x=>x.classList.toggle('active',x===b));render();const first=lanes[lane][0];if(first)void open(first);});
 audio.addEventListener('ended',async()=>{if(!active)return;if(lane==='tracks')await supabase.from('music_play_events').insert({track_id:active.id,user_id:session.user.id,session_id:crypto.randomUUID(),seconds_played:Math.floor(audio.duration||0),completed:true});});
 render();if(active)await open(active);
}

function renderHero(r:Row,lane:string){const title=r.title||r.station_name||'Rich Audio';return `<img class="universe-hero__media" src="${esc(r.cover_url||'/images/brand/IMG_5997.png')}" alt=""><div class="universe-hero__shade"></div><div class="universe-hero__content"><span class="universe-kicker">${lane==='radio'&&r.is_live?'● LIVE RADIO':lane==='podcasts'?'RICH PODCAST':lane==='playlists'?'CURATED UNIVERSE':'FEATURED RELEASE'}</span><h2>${esc(title)}</h2><p>${esc(r.description||r.display_name||r.show_title||'Independent sound from the Rich Bizness universe.')}</p><div class="universe-actions"><button class="universe-btn primary" type="button">▶ PLAY NOW</button><a class="universe-btn" href="/profile.html?id=${esc(r.creator_id||r.user_id)}">ARTIST</a><button class="universe-btn" type="button">♡ LIKE</button></div></div>`;}
