import { supabase } from '../../core/supabase/client';
import './search.css';

type SearchResult={category:string;id:string;title:string;subtitle:string|null;image_url:string|null;target_url:string;score:number};
const categories=['all','creator','post','music','podcast','radio','live','game','product','sports','world'];
const esc=(value:string|null|undefined)=>(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]??c));
const safeTarget=(value:string)=>{try{const url=new URL(value,location.origin);return url.origin===location.origin&&url.pathname.startsWith('/')?`${url.pathname}${url.search}${url.hash}`:'/search.html';}catch{return'/search.html';}};

export async function mount():Promise<void>{
 const root=document.querySelector<HTMLElement>('#app');if(!root)throw new Error('Missing #app mount');
 const {data:{session}}=await supabase.auth.getSession();if(!session){location.replace('/tap-in.html?next=%2Fsearch.html');return;}
 root.innerHTML=`<main class="search-shell"><div class="search-wrap"><header class="search-head"><a href="/portal.html">←</a><div><p>RICH DISCOVERY ENGINE</p><h1>Search the Universe</h1></div></header><form id="searchForm" class="search-box"><span>⌕</span><input id="searchInput" autocomplete="off" maxlength="100" placeholder="Creators, music, podcasts, radio, games, live, store, sports..."/><button id="clearSearch" type="button">×</button></form><div id="recentRow" class="recent-row"></div><div class="search-meta"><div id="filters" class="search-filters"></div><small id="resultCount">Ready</small></div><section id="results" class="search-grid"><div class="search-state">Search every connected section from one place.</div></section></div></main>`;
 const input=document.querySelector<HTMLInputElement>('#searchInput')!;const results=document.querySelector<HTMLElement>('#results')!;const count=document.querySelector<HTMLElement>('#resultCount')!;const filters=document.querySelector<HTMLElement>('#filters')!;const recentRow=document.querySelector<HTMLElement>('#recentRow')!;
 let rows:SearchResult[]=[];let active='all';let timer:number|undefined;let requestId=0;
 const recent=()=>{try{const parsed=JSON.parse(localStorage.getItem('rb_recent_searches')||'[]');return Array.isArray(parsed)?parsed.filter(x=>typeof x==='string').slice(0,6):[];}catch{return[];}};
 const saveRecent=(q:string)=>localStorage.setItem('rb_recent_searches',JSON.stringify([q,...recent().filter(x=>x.toLowerCase()!==q.toLowerCase())].slice(0,6)));
 const drawRecent=()=>{const list=recent();recentRow.innerHTML=list.map(q=>`<button type="button" data-recent="${esc(q)}">${esc(q)}</button>`).join('');recentRow.querySelectorAll<HTMLButtonElement>('[data-recent]').forEach(b=>b.addEventListener('click',()=>{input.value=b.dataset.recent||'';void runSearch();}));};
 const drawFilters=()=>{filters.innerHTML=categories.map(c=>`<button type="button" class="search-chip ${c===active?'active':''}" data-filter="${c}">${c==='all'?'ALL':c.toUpperCase()}</button>`).join('');filters.querySelectorAll<HTMLButtonElement>('[data-filter]').forEach(b=>b.addEventListener('click',()=>{active=b.dataset.filter||'all';drawFilters();draw();}));};
 const draw=()=>{const visible=active==='all'?rows:rows.filter(r=>r.category===active);count.textContent=`${visible.length} RESULT${visible.length===1?'':'S'}`;results.innerHTML=visible.length?visible.map(r=>`<a class="search-card" href="${esc(safeTarget(r.target_url))}"><div class="search-media" ${r.image_url?`style="background-image:linear-gradient(180deg,transparent,rgba(2,4,2,.4)),url('${esc(r.image_url)}')"`:''}></div><div class="search-body"><span class="search-type">${esc(r.category)}</span><h2>${esc(r.title)}</h2><p>${esc(r.subtitle||'Rich Bizness Universe')}</p></div></a>`).join(''):'<div class="search-state">No matches in this section.</div>';};
 const runSearch=async()=>{const query=input.value.trim();const current=++requestId;if(query.length<2){rows=[];count.textContent='TYPE 2+ CHARACTERS';results.innerHTML='<div class="search-state">Search every connected section from one place.</div>';return;}count.textContent='SEARCHING...';const {data,error}=await supabase.rpc('rb_global_search',{p_query:query,p_limit:80});if(current!==requestId)return;if(error){count.textContent='SEARCH ERROR';results.innerHTML=`<div class="search-state">${esc(error.message)}</div>`;return;}rows=(data??[]) as SearchResult[];saveRecent(query);drawRecent();draw();};
 document.querySelector<HTMLFormElement>('#searchForm')!.addEventListener('submit',e=>{e.preventDefault();void runSearch();});
 input.addEventListener('input',()=>{window.clearTimeout(timer);timer=window.setTimeout(()=>void runSearch(),320);});
 document.querySelector<HTMLButtonElement>('#clearSearch')!.addEventListener('click',()=>{requestId+=1;input.value='';rows=[];active='all';drawFilters();count.textContent='Ready';results.innerHTML='<div class="search-state">Search every connected section from one place.</div>';input.focus();});
 drawRecent();drawFilters();const initial=new URLSearchParams(location.search).get('q');if(initial){input.value=initial;await runSearch();}else input.focus();
}
