import { getAuthSnapshot } from '../../core/auth/auth-store';
import { supabase } from '../../core/supabase/client';
import './search.css';

type SearchResult={category:string;id:string;title:string;subtitle:string|null;image_url:string|null;target_url:string;score:number};
type SearchSnapshot={query?:string;category?:string;results?:SearchResult[];featured?:SearchResult[];counts?:Record<string,number>;inventory?:Record<string,number>;total?:number;recent?:Array<{query:string;last_used_at?:string}>;trending?:Array<{query:string;searches?:number;last_searched_at?:string}>};
type CategoryKey='all'|'people'|'creator'|'feed'|'gallery'|'watch'|'music'|'podcast'|'radio'|'live'|'sports'|'gaming'|'store'|'meta';
type Channel=ReturnType<typeof supabase.channel>;
type CleanupHost=Window & {__rbPageCleanup?:(()=>void|Promise<void>)|null};

const categories:ReadonlyArray<readonly[CategoryKey,string]>=[['all','ALL'],['creator','CREATORS'],['people','PEOPLE'],['gaming','GAMING'],['gallery','GALLERY'],['music','MUSIC'],['podcast','PODCAST'],['radio','RADIO'],['live','WE LIT 🔥'],['watch','WE 🔥 📺'],['feed','FEED'],['sports','SPORTS'],['store','STORE'],['meta','META']];
const aliases:Record<string,CategoryKey>={people:'people',profile:'people',user:'people',creator:'creator',feed:'feed',post:'feed',gallery:'gallery',image:'gallery',watch:'watch',video:'watch',music:'music',track:'music',podcast:'podcast',episode:'podcast',radio:'radio',station:'radio',live:'live',stream:'live',sports:'sports',gaming:'gaming',game:'gaming',store:'store',product:'store',meta:'meta',world:'meta'};
const indexedTables=['profiles','feed_posts','music_tracks','podcast_episodes','radio_stations','live_streams','sports_posts','games','products','meta_worlds'] as const;
const esc=(v:unknown)=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]??c));
const safeMedia=(v:unknown)=>{try{const u=new URL(String(v||''),location.origin);return['http:','https:'].includes(u.protocol)&&!/(\.mp4|\.webm|\.mov)(\?|$)/i.test(u.pathname+u.search)?u.href:'';}catch{return'';}};
const safeTarget=(v:unknown)=>{try{const u=new URL(String(v||''),location.origin);return u.origin===location.origin&&u.pathname.startsWith('/')?`${u.pathname}${u.search}${u.hash}`:'/search.html';}catch{return'/search.html';}};
const norm=(v:unknown):CategoryKey=>aliases[String(v||'').toLowerCase()]??'feed';
const compact=(v:string)=>v.trim().replace(/\s+/g,' ').slice(0,100);

export async function mount():Promise<void>{
 const root=document.querySelector<HTMLElement>('#app');if(!root)throw new Error('Missing #app mount');
 const epoch=root.dataset.pageEpoch??'';let disposed=false;const current=()=>!disposed&&root.dataset.pageEpoch===epoch&&root.dataset.pageOwner==='rich-bizness-search-v3';
 const userId=getAuthSnapshot().user?.id??null;
 const sessionId=sessionStorage.getItem('rb_search_session')||crypto.randomUUID();sessionStorage.setItem('rb_search_session',sessionId);
 root.innerHTML=`<main class="search-shell"><div class="search-atmosphere"></div><div class="search-wrap">
 <header class="search-head"><a href="/portal.html">←</a><div class="search-brand"><p>RICH BIZNESS GLOBAL DISCOVERY</p><h1>SEARCH THE UNIVERSE</h1><small>${userId?'RICH ID CONNECTED':'PUBLIC DISCOVERY'}</small></div><span class="search-signal"><i></i>LIVE INDEX</span></header>
 <section class="search-command"><div class="search-command-copy"><span>CONNECTED TO WHAT IS ALREADY HERE</span><h2>Search every Rich Bizness world from one place.</h2><p>Creators, people, 28 games, gallery, music, podcast, radio, WE LIT 🔥, WE 🔥 📺, feed, sports, store and Meta all stay in their own owners and routes.</p></div><form id="searchForm" class="search-box"><span class="search-icon">⌕</span><input id="searchInput" autocomplete="off" inputmode="search" enterkeyhint="search" maxlength="100" placeholder="Search the whole Rich Bizness universe..."/><button id="clearSearch" type="button">×</button></form></section>
 <section id="inventoryDeck" class="search-inventory"></section>
 <section id="trendingRow" class="discovery-row"></section><section id="recentRow" class="discovery-row"></section>
 <div class="search-meta"><div id="filters" class="search-filters"></div><small id="resultCount">SYNCING UNIVERSE…</small></div>
 <section id="results" class="search-grid"></section>
 <p id="searchStatus" class="search-status" role="status"></p></div></main>`;
 const q=<T extends Element>(s:string)=>root.querySelector<T>(s)!;const input=q<HTMLInputElement>('#searchInput'),results=q<HTMLElement>('#results'),count=q<HTMLElement>('#resultCount'),filters=q<HTMLElement>('#filters'),recentRow=q<HTMLElement>('#recentRow'),trendingRow=q<HTMLElement>('#trendingRow'),inventoryDeck=q<HTMLElement>('#inventoryDeck'),form=q<HTMLFormElement>('#searchForm'),clearBtn=q<HTMLButtonElement>('#clearSearch'),status=q<HTMLElement>('#searchStatus');
 let rows:SearchResult[]=[],featured:SearchResult[]=[],counts:Record<string,number>={},inventory:Record<string,number>={},recent:string[]=[],trending:Array<{query:string;searches:number}>=[],active:CategoryKey='all',lastQuery='',requestId=0,timer=0,refreshTimer=0,statusTimer=0,focused=-1,channel:Channel|null=null;
 const setStatus=(m:string,e=false)=>{if(!current())return;status.textContent=m;status.dataset.error=String(e);clearTimeout(statusTimer);if(m)statusTimer=window.setTimeout(()=>{if(current()&&status.textContent===m)status.textContent='';},2600)};
 const localRecent=()=>{try{const v=JSON.parse(localStorage.getItem('rb_recent_searches')||'[]');return Array.isArray(v)?v.filter(x=>typeof x==='string').slice(0,8):[];}catch{return[];}};
 const visible=(source:SearchResult[])=>active==='all'?source:source.filter(r=>norm(r.category)===active);
 const load=async(query:string,category:CategoryKey=active)=>{const{data,error}=await supabase.rpc('rb_search_snapshot',{p_query:query,p_category:category,p_limit:120});if(error)throw error;return(data??{}) as SearchSnapshot;};
 const apply=(s:SearchSnapshot)=>{rows=(s.results??[]).sort((a,b)=>Number(b.score||0)-Number(a.score||0));featured=(s.featured??[]).sort((a,b)=>Number(b.score||0)-Number(a.score||0));counts=s.counts??{};inventory=s.inventory??{};recent=[...new Set([...(s.recent??[]).map(x=>x.query),...localRecent()])].slice(0,8);trending=(s.trending??[]).map(x=>({query:x.query,searches:Number(x.searches??0)}));};
 const icon=(k:string)=>({creator:'👑',people:'👤',gaming:'🎮',gallery:'▣',music:'♪',podcast:'🎙',radio:'📡',live:'🔥',watch:'📺',feed:'✦',sports:'🏆',store:'🛒',meta:'◎'} as Record<string,string>)[k]||'✦';
 const inventoryOrder:ReadonlyArray<readonly[CategoryKey,string]>=[['creator','CREATORS'],['people','PEOPLE'],['gaming','GAMES'],['gallery','VISUALS'],['music','TRACKS'],['podcast','EPISODES'],['radio','STATIONS'],['live','LIVE NOW'],['watch','WATCH'],['feed','FEED'],['sports','SPORTS'],['store','STORE'],['meta','WORLDS']];
 const drawInventory=()=>{inventoryDeck.innerHTML=inventoryOrder.map(([k,l])=>`<button data-jump="${k}" class="${active===k?'active':''}"><span>${icon(k)}</span><b>${Number(inventory[k]??0).toLocaleString()}</b><small>${l}</small></button>`).join('');inventoryDeck.querySelectorAll<HTMLButtonElement>('[data-jump]').forEach(b=>b.onclick=()=>{active=(b.dataset.jump as CategoryKey)||'all';focused=-1;drawInventory();drawFilters();drawResults();root.querySelector('.search-meta')?.scrollIntoView({behavior:'smooth',block:'start'});});};
 const drawDiscovery=()=>{trendingRow.innerHTML=trending.length?`<div class="discovery-label"><small>TRENDING NOW</small><span>EXISTING CONTENT + SEARCH SIGNALS</span></div><div class="discovery-pills">${trending.slice(0,10).map((x,i)=>`<button data-trending="${esc(x.query)}"><b>${String(i+1).padStart(2,'0')}</b>${esc(x.query)}<small>${x.searches} signal${x.searches===1?'':'s'}</small></button>`).join('')}</div>`:'<div class="discovery-label"><small>TRENDING NOW</small><span>NO SIGNAL YET</span></div>';recentRow.innerHTML=recent.length?`<div class="discovery-label"><small>RECENT SEARCHES</small><span>RICH ID + DEVICE</span></div><div class="discovery-pills compact">${recent.map(x=>`<button data-recent="${esc(x)}">${esc(x)}</button>`).join('')}</div>`:'<div class="discovery-label"><small>RECENT SEARCHES</small><span>NONE YET</span></div>';trendingRow.querySelectorAll<HTMLButtonElement>('[data-trending]').forEach(b=>b.onclick=()=>{input.value=b.dataset.trending||'';void searchNow(true);});recentRow.querySelectorAll<HTMLButtonElement>('[data-recent]').forEach(b=>b.onclick=()=>{input.value=b.dataset.recent||'';void searchNow(true);});};
 const drawFilters=()=>{filters.innerHTML=categories.map(([k,l])=>{const n=k==='all'?Object.values(inventory).reduce((a,b)=>a+Number(b||0),0):Number(inventory[k]??counts[k]??0);return`<button class="search-chip ${active===k?'active':''}" data-filter="${k}"><span>${l}</span><b>${n}</b></button>`}).join('');filters.querySelectorAll<HTMLButtonElement>('[data-filter]').forEach(b=>b.onclick=()=>{active=(b.dataset.filter as CategoryKey)||'all';focused=-1;drawInventory();lastQuery?void searchNow(true,false):(drawFilters(),drawResults());});};
 const card=(r:SearchResult,i:number)=>{const cat=norm(r.category),img=safeMedia(r.image_url);return`<a class="search-card search-card--${cat} ${focused===i?'keyboard-focus':''}" href="${esc(safeTarget(r.target_url))}" data-result-index="${i}"><div class="search-media">${img?`<img src="${esc(img)}" alt="" loading="lazy">`:`<div class="search-media-fallback"><span>${icon(cat)}</span></div>`}</div><div class="search-body"><span class="search-type">${esc(cat)}</span><h2>${esc(r.title)}</h2><p>${esc(r.subtitle||'Rich Bizness Universe')}</p><footer><strong>OPEN ${cat==='live'?'WE LIT 🔥':cat==='watch'?'WE 🔥 📺':'↗'}</strong></footer></div></a>`;};
 const drawResults=()=>{if(!current())return;const source=visible(lastQuery?rows:featured);count.textContent=lastQuery?`${source.length} SEARCH RESULT${source.length===1?'':'S'}`:`${source.length} CONNECTED ITEM${source.length===1?'':'S'}`;results.innerHTML=source.length?source.map(card).join(''):`<div class="search-state"><strong>${Number(inventory[active]??0)>0?'THIS LANE HAS DATA — SEARCH IT ABOVE.':'NOTHING PUBLISHED IN THIS LANE YET.'}</strong><span>${Number(inventory[active]??0)>0?'The inventory is connected; type a title, creator, category or keyword.':'Search is connected to the existing source-of-truth tables and will populate as content is published.'}</span></div>`;results.querySelectorAll<HTMLAnchorElement>('[data-result-index]').forEach(a=>a.onclick=()=>{const r=source[Number(a.dataset.resultIndex)];if(lastQuery&&r)void supabase.rpc('rb_search_action',{p_action:'record_click',p_payload:{query:lastQuery,category:active,session_id:sessionId,result_type:norm(r.category),target_id:r.id,target_url:safeTarget(r.target_url),target_title:r.title}});});};
 const searchNow=async(immediate=false,record=true)=>{clearTimeout(timer);const query=compact(input.value);if(!immediate){timer=window.setTimeout(()=>void searchNow(true),180);return;}const id=++requestId;if(query.length<2){lastQuery='';rows=[];history.replaceState({},'','/search.html');drawInventory();drawFilters();drawResults();return;}count.textContent='SCANNING EXISTING UNIVERSE…';try{const s=await load(query,active);if(!current()||id!==requestId)return;apply(s);lastQuery=query;if(record){const vals=[query,...localRecent().filter(x=>x.toLowerCase()!==query.toLowerCase())].slice(0,8);localStorage.setItem('rb_recent_searches',JSON.stringify(vals));void supabase.rpc('rb_search_action',{p_action:'record_query',p_payload:{query,category:active,result_count:rows.length,session_id:sessionId}});}drawInventory();drawDiscovery();drawFilters();drawResults();const cq=active==='all'?'':`&category=${encodeURIComponent(active)}`;history.replaceState({},'',`/search.html?q=${encodeURIComponent(query)}${cq}`);}catch(e){setStatus(e instanceof Error?e.message:'Search unavailable',true);}};
 const refresh=()=>{clearTimeout(refreshTimer);refreshTimer=window.setTimeout(async()=>{try{const s=await load(lastQuery,active);if(!current())return;apply(s);drawInventory();drawDiscovery();drawFilters();drawResults();}catch{}},140);};
 form.onsubmit=e=>{e.preventDefault();void searchNow(true);};input.oninput=()=>void searchNow(false);clearBtn.onclick=()=>{input.value='';lastQuery='';active='all';history.replaceState({},'','/search.html');drawInventory();drawFilters();drawResults();};
 const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'){input.value='';lastQuery='';active='all';drawInventory();drawFilters();drawResults();return;}const source=visible(lastQuery?rows:featured);if(!source.length||!['ArrowDown','ArrowUp','Enter'].includes(e.key))return;if(e.key==='Enter'&&focused>=0){e.preventDefault();location.assign(safeTarget(source[focused].target_url));return;}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();focused=e.key==='ArrowDown'?(focused+1)%source.length:(focused<=0?source.length-1:focused-1);drawResults();}};window.addEventListener('keydown',onKey);
 channel=supabase.channel(`rich-search-catalog:${epoch}:${sessionId}`);indexedTables.forEach(table=>{channel=channel!.on('postgres_changes',{event:'*',schema:'public',table},refresh)});channel.subscribe();
 const cleanup=async()=>{if(disposed)return;disposed=true;requestId++;clearTimeout(timer);clearTimeout(refreshTimer);clearTimeout(statusTimer);window.removeEventListener('keydown',onKey);if(channel)await supabase.removeChannel(channel);};(window as CleanupHost).__rbPageCleanup=cleanup;
 try{const s=await load('','all');if(!current())return;apply(s);}catch(e){setStatus(e instanceof Error?e.message:'Discovery sync unavailable',true);}
 drawInventory();drawDiscovery();drawFilters();drawResults();
 const params=new URLSearchParams(location.search);active=aliases[String(params.get('category')||'').toLowerCase()]??'all';const initial=compact(params.get('q')||'');if(initial){input.value=initial;await searchNow(true,false);}else{drawInventory();drawFilters();drawResults();}
}
