import { supabase } from '../../src/supabase-client.js';
import { getAuthoritativeIdentity } from '../../src/rb-identity.js?v=profile-avatar-separate-1';

const $=id=>document.getElementById(id),canvas=$('field'),ctx=canvas.getContext('2d');
let score=0,outs=0,inning=1,streak=0,power=50,phase='ready',ball=null,last=0,identity={};
const leaderboard=$('leaderboard');

function resize(){const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=r.width*dpr;canvas.height=r.height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}
function sync(){ $('score').textContent=score;$('outs').textContent=outs;$('inning').textContent=inning;$('streak').textContent=streak;$('powerBar').style.width=power+'%'; }
function reset(){score=0;outs=0;inning=1;streak=0;power=50;phase='ready';ball=null;$('status').textContent='Tap PITCH to start the at-bat.';sync()}
function pitch(){if(phase!=='ready')return;phase='pitch';ball={x:canvas.clientWidth*.5,y:85,v:2.6+Math.random()*1.8,spin:(Math.random()-.5)*.6};$('status').textContent='Track the pitch. Swing in the green window.'}
function swing(){if(phase!=='pitch'||!ball)return;const plate=canvas.clientHeight-112,delta=Math.abs(ball.y-plate),quality=Math.max(0,1-delta/120),perfect=quality>.82;if(quality<.28){outs++;streak=0;$('status').textContent='Strike. Timing was late or early.'}else{const distance=Math.round((140+power*4)*(0.55+quality*.75));score+=distance+(perfect?500:0);streak++;power=Math.min(100,power+6);$('status').textContent=perfect?`GREEN RELEASE • ${distance} FT HOME RUN`:`Clean contact • ${distance} FT`;phase='flight';ball.vy=-(7+quality*5);ball.vx=(Math.random()-.5)*5;ball.hit=true}if(outs>=3){inning++;outs=0;power=Math.max(35,power-12)}if(phase!=='flight'){phase='ready';ball=null}sync()}
function boost(){if(power>=20){power-=20;power=Math.min(100,power+35);$('status').textContent='Diamond Power charged for the next swing.';sync()}}
function update(dt){if(ball&&phase==='pitch'){ball.y+=ball.v*dt*.06;ball.x+=ball.spin*dt*.05;if(ball.y>canvas.clientHeight-76){outs++;streak=0;phase='ready';ball=null;$('status').textContent='Called strike. Pitch the next ball.';sync()}}else if(ball&&phase==='flight'){ball.x+=ball.vx*dt*.06;ball.y+=ball.vy*dt*.06;ball.vy+=.28*dt*.06;if(ball.y>canvas.clientHeight+40){phase='ready';ball=null}}}
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);ctx.fillStyle='#143a1d';ctx.fillRect(0,0,w,h*.48);ctx.fillStyle='#84623a';ctx.fillRect(0,h*.48,w,h*.52);ctx.strokeStyle='rgba(255,255,255,.75)';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(w*.5,h-70);ctx.lineTo(w*.18,h*.48);ctx.moveTo(w*.5,h-70);ctx.lineTo(w*.82,h*.48);ctx.stroke();ctx.fillStyle='#f7f0dc';ctx.fillRect(w*.5-34,h-90,68,16);ctx.font='54px system-ui';ctx.fillText('⚾',w*.5-28,h-72);ctx.font='44px system-ui';ctx.fillText('🧍',w*.5-24,h-35);if(ball){ctx.font='28px system-ui';ctx.fillText('⚾',ball.x-14,ball.y)}ctx.fillStyle='rgba(157,255,99,.15)';ctx.fillRect(w*.5-65,h-155,130,65);ctx.strokeStyle='#9dff63';ctx.strokeRect(w*.5-65,h-155,130,65)}
function loop(t){const dt=Math.min(33,t-last||16);last=t;update(dt);draw();requestAnimationFrame(loop)}
async function saveRun(){identity=await getAuthoritativeIdentity().catch(()=>({}));if(!identity.user){location.href='/auth.html?next='+encodeURIComponent(location.pathname);return}const game=await supabase.from('games').select('id').eq('slug','diamond-bat-flip').maybeSingle();await supabase.from('game_sessions').insert({game_id:game.data?.id||null,game_slug:'diamond-bat-flip',user_id:identity.user.id,username:identity.profile?.username||null,display_name:identity.profile?.display_name||null,score,result:'completed',platform_type:'web',metadata:{source:'games/diamond-bat-flip',inning,streak,verified:true}});await supabase.from('game_scores').insert({game_id:game.data?.id||null,game_slug:'diamond-bat-flip',user_id:identity.user.id,score,is_verified:true,metadata:{source:'games/diamond-bat-flip',inning,streak}});$('status').textContent='Run saved to Rich Bizness leaderboard.';loadBoard()}
async function loadBoard(){const {data}=await supabase.from('game_scores').select('score,display_name,username').eq('game_slug','diamond-bat-flip').eq('is_verified',true).order('score',{ascending:false}).limit(5);leaderboard.innerHTML=(data||[]).map((r,i)=>`<div><span>#${i+1} ${r.display_name||r.username||'Rich Player'}</span><b>${Number(r.score||0).toLocaleString()}</b></div>`).join('')||'<small>No scores yet.</small>'}
$('pitch').onclick=pitch;$('swing').onclick=swing;$('boost').onclick=boost;$('restart').onclick=reset;$('save').onclick=saveRun;addEventListener('resize',resize);addEventListener('keydown',e=>{if(e.code==='Space')swing();if(e.key==='p')pitch()});resize();reset();loadBoard();requestAnimationFrame(loop);