import { supabase } from '../../core/supabase/client';
import './upload.css';

type RouteRow={route_key:string;section:string;bucket:string;target_table:string|null;target_column:string|null;media_type:string|null;max_file_size_mb:number|null;is_public:boolean|null;processing_type:string|null};
type UploadRow={id:string;title:string|null;section:string|null;bucket:string;public_url:string;media_type:string|null;processing_status:string|null;created_at:string|null};
const esc=(v:string|null|undefined)=>(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]??c));
const size=(n:number)=>n>1024*1024?`${(n/1024/1024).toFixed(1)} MB`:`${Math.ceil(n/1024)} KB`;
const media=(type:string)=>type.startsWith('image/')?'image':type.startsWith('video/')?'video':type.startsWith('audio/')?'audio':'file';
const acceptFor=(type:string|null)=>type==='image'?'image/*':type==='video'?'video/*':type==='audio'?'audio/*':type==='model'?'.glb,.gltf,model/gltf-binary,model/gltf+json,application/octet-stream':'*/*';
const matchesRoute=(file:File,route:RouteRow)=>{const kind=media(file.type);if(!route.media_type||route.media_type==='mixed')return true;if(route.media_type==='model')return /\.(glb|gltf)$/i.test(file.name)||['model/gltf-binary','model/gltf+json','application/octet-stream','application/json'].includes(file.type);return kind===route.media_type;};

export async function mount():Promise<void>{
 const root=document.querySelector<HTMLElement>('#app');if(!root)throw new Error('Missing #app mount');
 const {data:{session}}=await supabase.auth.getSession();if(!session){location.replace('/tap-in.html?next=%2Fupload.html');return;}
 const {data:routes,error}=await supabase.from('storage_bucket_routes').select('route_key,section,bucket,target_table,target_column,media_type,max_file_size_mb,is_public,processing_type').order('section').order('route_key');if(error)throw error;
 const routeRows=(routes??[]) as RouteRow[];
 root.innerHTML=`<main class="upload-shell"><div class="upload-wrap"><header class="upload-head"><a href="/portal.html">←</a><div><p>RICH BIZNESS CREATOR PIPELINE</p><h1>Upload Studio</h1></div><span id="uploadState">READY</span></header><section class="upload-grid"><form id="uploadForm" class="upload-card"><div class="field-grid"><label><span>DESTINATION</span><select id="routeKey" required>${routeRows.map(r=>`<option value="${esc(r.route_key)}">${esc(r.section.toUpperCase())} · ${esc(r.route_key)}</option>`).join('')}</select></label><label><span>VISIBILITY</span><select id="visibility"><option>public</option><option>followers</option><option>unlisted</option><option>private</option></select></label><label class="wide"><span>TITLE</span><input id="title" maxlength="120" placeholder="Name this drop"/></label><label class="wide"><span>DESCRIPTION</span><textarea id="description" maxlength="1000" rows="4" placeholder="Tell the universe what this is"></textarea></label></div><label id="dropZone" class="drop-zone"><input id="fileInput" type="file" hidden/><strong>DROP FILE HERE</strong><small id="routeHint">Choose a route and add media</small><button type="button" id="pickFile">BROWSE DEVICE</button></label><div id="preview" class="upload-preview"><span>No file selected</span></div><div class="meter"><i id="meterBar"></i></div><p id="uploadMessage" class="upload-message"></p><button id="uploadButton" class="upload-button" type="submit">UPLOAD TO RICH BIZNESS</button></form><aside class="upload-card recent-panel"><div class="panel-title"><div><p>YOUR PIPELINE</p><h2>Recent Uploads</h2></div><button id="refreshUploads">↻</button></div><div id="recentUploads" class="recent-list"></div></aside></section></div></main>`;
 const form=document.querySelector<HTMLFormElement>('#uploadForm')!,routeKey=document.querySelector<HTMLSelectElement>('#routeKey')!,fileInput=document.querySelector<HTMLInputElement>('#fileInput')!,dropZone=document.querySelector<HTMLElement>('#dropZone')!,preview=document.querySelector<HTMLElement>('#preview')!,hint=document.querySelector<HTMLElement>('#routeHint')!,message=document.querySelector<HTMLElement>('#uploadMessage')!,state=document.querySelector<HTMLElement>('#uploadState')!,bar=document.querySelector<HTMLElement>('#meterBar')!,button=document.querySelector<HTMLButtonElement>('#uploadButton')!;
 let selected:File|null=null;let previewUrl:string|null=null;
 const activeRoute=()=>routeRows.find(r=>r.route_key===routeKey.value)!;
 const clearPreviewUrl=()=>{if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=null;}};
 const updateHint=()=>{const r=activeRoute();fileInput.accept=acceptFor(r.media_type);hint.textContent=`${r.bucket} · ${r.media_type??'mixed'} · max ${r.max_file_size_mb??300} MB · ${r.processing_type??'metadata'}`;if(selected&&!matchesRoute(selected,r)){selected=null;clearPreviewUrl();preview.innerHTML='<span>Choose a file that matches this destination</span>';message.textContent='File cleared because it does not match the selected route.';}};
 const setFile=(file:File|null)=>{clearPreviewUrl();selected=file;if(!file){preview.innerHTML='<span>No file selected</span>';return;}const r=activeRoute();if(!matchesRoute(file,r)){selected=null;message.textContent=`This destination accepts ${r.media_type??'mixed'} files.`;preview.innerHTML='<span>File type does not match destination</span>';return;}previewUrl=URL.createObjectURL(file);const kind=media(file.type);preview.innerHTML=kind==='image'?`<img src="${previewUrl}" alt="Upload preview"/>`:kind==='video'?`<video src="${previewUrl}" controls playsinline></video>`:kind==='audio'?`<audio src="${previewUrl}" controls></audio>`:`<div><strong>${esc(file.name)}</strong><small>${size(file.size)}</small></div>`;message.textContent='';};
 routeKey.addEventListener('change',updateHint);document.querySelector('#pickFile')?.addEventListener('click',()=>fileInput.click());fileInput.addEventListener('change',()=>setFile(fileInput.files?.[0]??null));
 ['dragenter','dragover'].forEach(name=>dropZone.addEventListener(name,e=>{e.preventDefault();dropZone.classList.add('active');}));['dragleave','drop'].forEach(name=>dropZone.addEventListener(name,e=>{e.preventDefault();dropZone.classList.remove('active');}));dropZone.addEventListener('drop',e=>setFile(e.dataTransfer?.files?.[0]??null));updateHint();
 const loadRecent=async()=>{const {data}=await supabase.from('uploads').select('id,title,section,bucket,public_url,media_type,processing_status,created_at').eq('user_id',session.user.id).order('created_at',{ascending:false}).limit(20);const rows=(data??[]) as UploadRow[];document.querySelector<HTMLElement>('#recentUploads')!.innerHTML=rows.length?rows.map(r=>`<article><span>${r.media_type==='image'?'▣':r.media_type==='video'?'▶':r.media_type==='audio'?'♪':'⬆'}</span><div><strong>${esc(r.title||'Untitled upload')}</strong><small>${esc(r.section||r.bucket)} · ${esc(r.processing_status||'completed')}</small></div><time>${r.created_at?new Date(r.created_at).toLocaleDateString():''}</time></article>`).join(''):'<div class="empty">No uploads yet.</div>';};
 document.querySelector('#refreshUploads')?.addEventListener('click',()=>void loadRecent());
 form.addEventListener('submit',async e=>{e.preventDefault();if(!selected){message.textContent='Choose a file first.';return;}const r=activeRoute();if(!matchesRoute(selected,r)){message.textContent=`This destination accepts ${r.media_type??'mixed'} files.`;return;}const max=(r.max_file_size_mb??300)*1024*1024;if(selected.size>max){message.textContent=`File is too large. Limit is ${r.max_file_size_mb??300} MB.`;return;}button.disabled=true;state.textContent='UPLOADING';message.textContent='Preparing secure upload…';bar.style.width='12%';try{const ext=selected.name.split('.').pop()?.replace(/[^a-z0-9]/gi,'').toLowerCase()||'bin';const path=`${session.user.id}/${r.route_key}/${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}.${ext}`;bar.style.width='35%';const {error:uploadError}=await supabase.storage.from(r.bucket).upload(path,selected,{cacheControl:'3600',contentType:selected.type||'application/octet-stream',upsert:false});if(uploadError)throw uploadError;bar.style.width='72%';const publicUrl=r.is_public===false?`private://${r.bucket}/${path}`:supabase.storage.from(r.bucket).getPublicUrl(path).data.publicUrl;const {error:registerError}=await supabase.rpc('rb_register_upload',{p_route_key:r.route_key,p_title:(document.querySelector<HTMLInputElement>('#title')!.value||''),p_description:(document.querySelector<HTMLTextAreaElement>('#description')!.value||''),p_file_path:path,p_public_url:publicUrl,p_mime_type:selected.type||'application/octet-stream',p_file_size:selected.size,p_visibility:document.querySelector<HTMLSelectElement>('#visibility')!.value,p_metadata:{original_name:selected.name,source:'upload_studio',target_table:r.target_table,target_column:r.target_column}});if(registerError){await supabase.storage.from(r.bucket).remove([path]);throw registerError;}bar.style.width='100%';state.textContent='COMPLETE';message.textContent=`Uploaded to ${r.section}. ${r.processing_type&&r.processing_type!=='metadata'?'Processing queued.':'Ready now.'}`;form.reset();routeKey.value=r.route_key;setFile(null);updateHint();await loadRecent();}catch(err){state.textContent='ERROR';message.textContent=err instanceof Error?err.message:'Upload failed.';bar.style.width='0%';}finally{button.disabled=false;}});
 await loadRecent();
 const channel=supabase.channel(`uploads:${session.user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'uploads',filter:`user_id=eq.${session.user.id}`},()=>void loadRecent()).subscribe();
 window.addEventListener('beforeunload',()=>{clearPreviewUrl();void supabase.removeChannel(channel);},{once:true});
}
