import { supabase } from '../../core/supabase/client';
import './feed.css';

type FeedPost={id:string;user_id:string;username:string|null;display_name:string|null;body:string|null;title:string|null;media_url:string|null;file_url:string|null;thumbnail_url:string|null;cover_url:string|null;media_type:string|null;post_type:string|null;section:string|null;visibility:string|null;like_count:number|null;comment_count:number|null;view_count:number|null;is_featured:boolean|null;is_pinned:boolean|null;created_at:string};
type CommentRow={id:string;post_id:string;display_name:string|null;username:string|null;body:string;created_at:string};
type Profile={display_name:string|null;username:string|null;avatar_url:string|null;rich_level:number|null;rank_title:string|null};
const esc=(v:string|null|undefined)=>(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c));
const ago=(v:string)=>{const seconds=Math.max(1,Math.floor((Date.now()-new Date(v).getTime())/1000));if(seconds<60)return `${seconds}s`;if(seconds<3600)return `${Math.floor(seconds/60)}m`;if(seconds<86400)return `${Math.floor(seconds/3600)}h`;return `${Math.floor(seconds/86400)}d`;};
const mediaOf=(p:FeedPost)=>p.media_url||p.file_url||p.thumbnail_url||p.cover_url||'';

export async function mount():Promise<void>{
  const root=document.querySelector<HTMLElement>('#app');if(!root)throw new Error('Missing #app mount');
  const {data:{session}}=await supabase.auth.getSession();if(!session){location.replace('/tap-in.html?next=%2Ffeed.html');return;}
  const {data:profileData}=await supabase.from('profiles').select('display_name,username,avatar_url,rich_level,rank_title').eq('id',session.user.id).maybeSingle();
  const profile=(profileData??{}) as Profile;
  const sessionKey=localStorage.getItem('rb_feed_session')||crypto.randomUUID();localStorage.setItem('rb_feed_session',sessionKey);
  root.innerHTML=`<main class="feed-shell"><div class="feed-wrap"><header class="feed-top"><a href="/portal.html">←</a><div><small>RICH BIZNESS SOCIAL UNIVERSE</small><h1>Rich Feed</h1></div><nav><a href="/search.html">SEARCH</a><a href="/upload.html">UPLOAD</a><a href="/profile.html">PROFILE</a></nav></header><div class="feed-layout"><section class="feed-main"><form id="composer" class="feed-composer"><div class="feed-composer-head"><img src="${esc(profile.avatar_url||'/brand/icons/profile-placeholder.svg')}" alt=""><div><strong>${esc(profile.display_name||profile.username||'Rich Member')}</strong><small>LEVEL ${profile.rich_level??1} · ${esc(profile.rank_title||'Starter')}</small></div></div><textarea id="postBody" maxlength="4000" placeholder="Drop something into the universe..."></textarea><div class="feed-composer-actions"><div><a class="feed-button" href="/upload.html?route=feed">ADD MEDIA</a><select id="postSection" class="feed-button"><option value="feed">FEED</option><option value="gallery">GALLERY</option><option value="music">MUSIC</option><option value="sports">SPORTS</option><option value="gaming">GAMING</option></select></div><button class="feed-button primary" type="submit">DROP POST</button></div></form><div id="tabs" class="feed-tabs"></div><div id="posts"></div><p id="status" class="feed-status"></p></section><aside class="feed-side"><section class="feed-side-card"><h3>UNIVERSE LANES</h3><a href="/live.html"><span>LIVE NOW</span><b>◉</b></a><a href="/music.html"><span>MUSIC</span><b>♪</b></a><a href="/sports.html"><span>SPORTS</span><b>🏆</b></a><a href="/gaming.html"><span>GAMING</span><b>🎮</b></a><a href="/store.html"><span>STORE</span><b>🛒</b></a></section><section class="feed-side-card"><h3>YOUR CORE</h3><a href="/messages.html"><span>RICH DM</span><b>✦</b></a><a href="/notifications.html"><span>ALERTS</span><b>◌</b></a><a href="/avatar.html"><span>3D AVATAR</span><b>◎</b></a></section></aside></div></div></main>`;
  const postsEl=document.querySelector<HTMLElement>('#posts')!;const tabsEl=document.querySelector<HTMLElement>('#tabs')!;const status=document.querySelector<HTMLElement>('#status')!;
  let posts:FeedPost[]=[];let liked=new Set<string>();let filter='all';let channel:any=null;
  const setStatus=(m:string)=>{status.textContent=m;window.setTimeout(()=>{if(status.textContent===m)status.textContent='';},2200)};
  const loadLikes=async()=>{const {data}=await supabase.from('feed_post_likes').select('post_id').eq('user_id',session.user.id);liked=new Set((data??[]).map((r:any)=>r.post_id));};
  const loadPosts=async()=>{let query=supabase.from('feed_posts').select('id,user_id,username,display_name,body,title,media_url,file_url,thumbnail_url,cover_url,media_type,post_type,section,visibility,like_count,comment_count,view_count,is_featured,is_pinned,created_at').neq('moderation_state','blocked').order('is_pinned',{ascending:false}).order('is_featured',{ascending:false}).order('created_at',{ascending:false}).limit(80);if(filter!=='all')query=query.eq('section',filter);const {data,error}=await query;if(error){postsEl.innerHTML=`<div class="feed-empty">${esc(error.message)}</div>`;return;}posts=(data??[]) as FeedPost[];renderPosts();};
  const renderTabs=()=>{const tabs=[['all','FOR YOU'],['feed','FEED'],['gallery','GALLERY'],['music','MUSIC'],['sports','SPORTS'],['gaming','GAMING']];tabsEl.innerHTML=tabs.map(([v,label])=>`<button class="feed-tab ${filter===v?'active':''}" data-filter="${v}">${label}</button>`).join('');tabsEl.querySelectorAll<HTMLButtonElement>('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter!;renderTabs();void loadPosts();});};
  const renderMedia=(p:FeedPost)=>{const src=mediaOf(p);if(!src)return'';const type=(p.media_type||p.post_type||'').toLowerCase();if(type.includes('video')||/\.(mp4|webm|mov)(\?|$)/i.test(src))return `<video class="feed-media" controls playsinline poster="${esc(p.thumbnail_url||p.cover_url)}" src="${esc(src)}"></video>`;if(type.includes('audio')||/\.(mp3|wav|m4a|ogg)(\?|$)/i.test(src))return `<audio class="feed-media" controls src="${esc(src)}"></audio>`;return `<img class="feed-media" loading="lazy" src="${esc(src)}" alt="">`;};
  const renderPosts=()=>{postsEl.innerHTML=posts.length?posts.map(p=>`<article class="feed-card" data-post="${p.id}"><header class="feed-card-head"><img src="/brand/icons/profile-placeholder.svg" alt=""><div><a href="/profile.html?id=${p.user_id}"><strong>${esc(p.display_name||p.username||'Rich Creator')}</strong></a><span>@${esc(p.username||'member')} · ${ago(p.created_at)}</span></div>${p.is_featured?'<em>FEATURED</em>':`<em>${esc((p.section||'feed').toUpperCase())}</em>`}</header><div class="feed-card-copy">${p.title?`<h2>${esc(p.title)}</h2>`:''}${p.body?`<p>${esc(p.body)}</p>`:''}</div>${renderMedia(p)}<div class="feed-card-stats"><span>${p.like_count??0} likes</span><span>${p.comment_count??0} comments</span><span>${p.view_count??0} views</span></div><div class="feed-card-actions"><button data-like class="${liked.has(p.id)?'active':''}">${liked.has(p.id)?'♥ LIKED':'♡ LIKE'}</button><button data-comments>◌ COMMENT</button><a href="/messages.html?share=${p.id}">✦ SHARE</a></div><section class="feed-comments" data-comment-panel><div class="feed-comment-list"></div><form class="feed-comment-form"><input maxlength="2000" placeholder="Add to the conversation..."><button class="feed-button primary">POST</button></form></section></article>`).join(''):'<div class="feed-empty">No drops in this lane yet.</div>';
    postsEl.querySelectorAll<HTMLElement>('[data-post]').forEach(card=>{const id=card.dataset.post!;const post=posts.find(p=>p.id===id)!;void supabase.rpc('rb_feed_record_view',{p_post_id:id,p_session_id:sessionKey});card.querySelector<HTMLButtonElement>('[data-like]')!.onclick=async()=>{const {data,error}=await supabase.rpc('rb_feed_toggle_like',{p_post_id:id});if(error){setStatus(error.message);return;}const result=data as any;if(result?.liked)liked.add(id);else liked.delete(id);post.like_count=Number(result?.count??post.like_count??0);renderPosts();};const panel=card.querySelector<HTMLElement>('[data-comment-panel]')!;card.querySelector<HTMLButtonElement>('[data-comments]')!.onclick=()=>{panel.classList.toggle('open');if(panel.classList.contains('open'))void loadComments(id,panel);};const form=panel.querySelector<HTMLFormElement>('form')!;form.onsubmit=async e=>{e.preventDefault();const input=form.querySelector<HTMLInputElement>('input')!;const body=input.value.trim();if(!body)return;const {error}=await supabase.rpc('rb_feed_add_comment',{p_post_id:id,p_body:body});if(error){setStatus(error.message);return;}input.value='';post.comment_count=(post.comment_count??0)+1;await loadComments(id,panel);};});};
  const loadComments=async(postId:string,panel:HTMLElement)=>{const list=panel.querySelector<HTMLElement>('.feed-comment-list')!;const {data,error}=await supabase.from('feed_comments').select('id,post_id,display_name,username,body,created_at').eq('post_id',postId).order('created_at',{ascending:true}).limit(100);if(error){list.innerHTML=`<div class="feed-empty">${esc(error.message)}</div>`;return;}const rows=(data??[]) as CommentRow[];list.innerHTML=rows.length?rows.map(c=>`<div class="feed-comment"><strong>${esc(c.display_name||c.username||'Rich Member')}</strong><p>${esc(c.body)}</p></div>`).join(''):'<div class="feed-empty">Start the conversation.</div>';};
  document.querySelector<HTMLFormElement>('#composer')!.onsubmit=async e=>{e.preventDefault();const body=document.querySelector<HTMLTextAreaElement>('#postBody')!.value.trim();const section=document.querySelector<HTMLSelectElement>('#postSection')!.value;if(!body){setStatus('WRITE SOMETHING FIRST');return;}setStatus('DROPPING POST...');const {error}=await supabase.from('feed_posts').insert({user_id:session.user.id,username:profile.username,display_name:profile.display_name,body,section,visibility:'public',post_type:'text',media_type:'text',moderation_state:'approved',metadata:{source:'feed-composer'}});if(error){setStatus(error.message);return;}document.querySelector<HTMLTextAreaElement>('#postBody')!.value='';setStatus('POST LIVE');await loadPosts();};
  renderTabs();await loadLikes();await loadPosts();channel=supabase.channel('rich-feed-live').on('postgres_changes',{event:'*',schema:'public',table:'feed_posts'},()=>void loadPosts()).on('postgres_changes',{event:'*',schema:'public',table:'feed_comments'},payload=>{const postId=(payload.new as any)?.post_id||(payload.old as any)?.post_id;document.querySelectorAll<HTMLElement>(`[data-post="${postId}"] [data-comment-panel].open`).forEach(panel=>void loadComments(postId,panel));}).subscribe();window.addEventListener('pagehide',()=>{if(channel)void supabase.removeChannel(channel)},{once:true});
}
