import { getAuthSnapshot } from '../../core/auth/auth-store';
import { supabase } from '../../core/supabase/client';
import '../../styles/deep-sections.css';
import './gallery.css';

type Row=Record<string,any>;
type Snapshot={rows?:Row[];comments?:Row[];liked?:boolean;saved?:boolean;metrics?:Row};
type Channel=ReturnType<typeof supabase.channel>;
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c));
const safe=(v:unknown)=>{try{const u=new URL(String(v||''),location.origin);return['http:','https:'].includes(u.protocol)?u.href:'';}catch{return'';}};
const media=(r:Row)=>safe(r.media_url||r.file_url||r.thumbnail_url||r.cover_url);
const video=(r:Row)=>String(r.media_type||'').startsWith('video')||r.post_type==='video';
const ago=(v:unknown)=>{const s=Math.max(1,Math.floor((Date.now()-new Date(String(v||0)).getTime())/1000));return s<60?`${s}s`:s<3600?`${Math.floor(s/60)}m`:s<86400?`${Math.floor(s/3600)}h`:`${Math.floor(s/86400)}d`;};

export async function mount():Promise<void>{
 const root=document.querySelector<HTMLElement>('#app');if(!root)throw new Error('Missing #app');if(root.dataset.galleryOwner==='mounted')return;root.dataset.galleryOwner='mounted';
 const userId=getAuthSnapshot().user?.id??null;
 root.innerHTML=`<main class="deep-shell gallery-universe"><div class="gallery-gridlines" aria-hidden="true"></div><div class="deep-wrap"><header class="deep-top"><a href="/portal.html">←</a><div><p>RICH BIZNESS VISUAL DISTRICT</p><h1>Gallery</h1></div><span class="deep-live">REALTIME</span></header><section class="deep-hero gallery-hero" style="--hero-image:url('/images/brand/IMG_5997.png')"><div class="gallery-hero-copy"><small>ART • PHOTOS • MOTION • CREATOR DROPS</small><h2>THE VISUAL UNIVERSE</h2><p>A cinematic global district for original photography, artwork, motion, collections, creator drops, and visual conversation connected to every Rich ID.</p><div class="gallery-hero-badges"><span>HD VISUALS</span><span>PHOTO + MOTION</span><span>PRIVATE COLLECTIONS</span><span>REALTIME CONVERSATION</span></div><div class="deep-actions"><a class="deep-btn primary" href="/upload.html?route=gallery">DROP VISUAL</a><a class="deep-btn" href="/search.html?category=gallery">DISCOVER</a><a class="deep-btn" href="/feed.html?section=gallery">OPEN FEED</a><a class="deep-btn" href="/watch.html?source=gallery">WATCH</a></div></div></section><nav id="tabs" class="deep-tabs"></nav><section id="stats" class="deep-stats"></section><section id="grid" class="deep-grid gallery-grid"></section><p id="status" class="deep-status" role="status"></p></div><div id="viewer" class="gallery-lightbox" hidden><article class="gallery-lightbox-card"><button id="closeViewer" class="gallery-lightbox-close" aria-label="Close visual">×</button><div class="gallery-lightbox-layout"><div id="viewerMedia" class="gallery-lightbox-media"></div><aside class="gallery-lightbox-side"><div class="gallery-lightbox-copy"><span id="viewerType" class="gallery-viewer-type"></span><h2 id="viewerTitle"></h2><p id="viewerCreator"></p><div id="viewerMeta" class="gallery-lightbox-meta"></div><div class="gallery-viewer-actions"><button id="viewerLike" class="deep-btn"></button><button id="viewerSave" class="deep-btn"></button><a id="viewerProfile" class="deep-btn">CREATOR</a></div></div><div id="comments" class="gallery-comments"></div><form id="commentForm" class="gallery-comment-form"><input id="commentInput" maxlength="2000" placeholder="Add to the visual conversation..."><button class="deep-btn primary">POST</button></form></aside></div></article></div></main>`;
 const q=<T extends Element>(s:string)=>root.querySelector<T>(s)!;
 const tabs=q<HTMLElement>('#tabs'),stats=q<HTMLElement>('#stats'),grid=q<HTMLElement>('#grid'),status=q<HTMLElement>('#status'),viewer=q<HTMLElement>('#viewer'),viewerMedia=q<HTMLElement>('#viewerMedia'),viewerTitle=q<HTMLElement>('#viewerTitle'),viewerCreator=q<HTMLElement>('#viewerCreator'),viewerType=q<HTMLElement>('#viewerType'),viewerMeta=q<HTMLElement>('#viewerMeta'),comments=q<HTMLElement>('#comments'),form=q<HTMLFormElement>('#commentForm'),input=q<HTMLInputElement>('#commentInput');
 let snapshot:Snapshot={},rows:Row[]=[],active:Row|null=null,lane='all',channel:Channel|null=null,commentChannel:Channel|null=null,loading=false,queued=false,destroyed=false,timer=0;
 const lanes=[['all','ALL VISUALS'],['image','PHOTOS + ART'],['video','MOTION'],['featured','FEATURED'],['mine','MY DROPS']];
 const setStatus=(m:string,e=false)=>{status.textContent=m;status.dataset.error=String(e);window.setTimeout(()=>{if(status.textContent===m)status.textContent='';},3000);};
 const auth=()=>{if(userId)return true;location.assign(`/tap-in.html?next=${encodeURIComponent(location.pathname+location.search)}`);return false;};
 const action=async(name:string,payload:Row)=>{const{data,error}=await supabase.rpc('rb_gallery_action',{p_action:name,p_payload:payload});if(error)throw error;return(data??{}) as Row;};
 const visible=()=>rows.filter(r=>lane==='all'||lane==='image'&&!video(r)||lane==='video'&&video(r)||lane==='featured'&&r.is_featured||lane==='mine'&&r.user_id===userId);
 const renderTabs=()=>{tabs.innerHTML=lanes.map(([k,l])=>`<button class="deep-tab ${lane===k?'active':''}" data-lane="${k}">${l}</button>`).join('');tabs.querySelectorAll<HTMLButtonElement>('[data-lane]').forEach(b=>b.onclick=()=>{if(b.dataset.lane==='mine'&&!auth())return;lane=b.dataset.lane||'all';renderTabs();render();});};
 const renderComments=()=>{const list=snapshot.comments??[];comments.innerHTML=list.map(c=>`<article class="gallery-comment"><div><strong>${esc(c.display_name||c.username||'Rich Member')}</strong><span>${ago(c.created_at)}</span></div><p>${esc(c.body)}</p></article>`).join('')||'<div class="deep-empty">Start the visual conversation.</div>';comments.scrollTop=comments.scrollHeight;};
 const renderViewer=()=>{if(!active)return;const url=media(active),isVideo=video(active);viewerMedia.innerHTML=isVideo?`<video src="${esc(url)}" poster="${esc(safe(active.thumbnail_url||active.cover_url))}" controls autoplay playsinline></video>`:`<img src="${esc(url)}" alt="${esc(active.title||'Gallery visual')}">`;viewerTitle.textContent=active.title||active.body||'Rich Visual';viewerCreator.textContent=active.display_name||active.username||'Rich Creator';viewerType.textContent=isVideo?'MOTION DROP':'VISUAL DROP';viewerMeta.innerHTML=`<span>♥ ${active.like_count??0}</span><span>◌ ${active.comment_count??0}</span><span>◉ ${active.view_count??0}</span>`;q<HTMLButtonElement>('#viewerLike').textContent=snapshot.liked?'♥ LIKED':'♡ LIKE';q<HTMLButtonElement>('#viewerSave').textContent=snapshot.saved?'✓ SAVED':'+ SAVE';q<HTMLAnchorElement>('#viewerProfile').href=`/profile.html?id=${encodeURIComponent(active.user_id)}`;renderComments();};
 const render=()=>{const m=snapshot.metrics??{};stats.innerHTML=`<article><small>VISUAL DROPS</small><strong>${Number(m.visuals??rows.length).toLocaleString()}</strong></article><article><small>CREATORS</small><strong>${Number(m.creators??0).toLocaleString()}</strong></article><article><small>LIKES</small><strong>${Number(m.likes??0).toLocaleString()}</strong></article><article><small>VIEWS</small><strong>${Number(m.views??0).toLocaleString()}</strong></article>`;const list=visible();grid.innerHTML=list.map(r=>{const url=media(r);return`<article class="deep-card gallery-card"><div class="deep-card-media">${url?(video(r)?`<video src="${esc(url)}" poster="${esc(safe(r.thumbnail_url||r.cover_url))}" muted playsinline preload="metadata"></video>`:`<img src="${esc(url)}" alt="${esc(r.title||'Gallery visual')}" loading="lazy">`):'<div class="gallery-media-empty">RICH VISUAL</div>'}<span>${esc((r.post_type||r.media_type||'VISUAL').toUpperCase())}</span>${url?`<button class="gallery-open" data-open="${r.id}" aria-label="Open visual">↗</button>`:''}</div><div class="deep-card-body"><h3>${esc(r.title||r.body||'Rich Visual')}</h3><p>${esc(r.display_name||r.username||'Rich Creator')}</p><div class="deep-card-meta"><span>♥ ${r.like_count??0} · ◌ ${r.comment_count??0}</span><span>◉ ${r.view_count??0}</span></div><div class="deep-card-actions"><a href="/profile.html?id=${encodeURIComponent(r.user_id)}">CREATOR</a><button data-like="${r.id}">LIKE</button><button data-open="${r.id}">VIEW</button></div></div></article>`;}).join('')||'<div class="deep-empty">No visuals in this lane yet.</div>';grid.querySelectorAll<HTMLButtonElement>('[data-open]').forEach(b=>b.onclick=()=>{const r=rows.find(x=>x.id===b.dataset.open);if(r)void open(r);});grid.querySelectorAll<HTMLButtonElement>('[data-like]').forEach(b=>b.onclick=async()=>{if(!auth())return;try{await action('toggle_like',{post_id:b.dataset.like});await load(active?.id??null);}catch(e){setStatus(e instanceof Error?e.message:'Like failed',true);}});};
 const load=async(activeId:string|null=active?.id??null)=>{if(loading){queued=true;return;}loading=true;try{const{data,error}=await supabase.rpc('rb_gallery_snapshot',{p_active_id:activeId,p_limit:160});if(error)throw error;snapshot=(data??{}) as Snapshot;rows=snapshot.rows??[];if(activeId)active=rows.find(r=>r.id===activeId)??active;if(!destroyed){render();if(active)renderViewer();}}catch(e){setStatus(e instanceof Error?e.message:'Gallery sync failed',true);}finally{loading=false;if(queued&&!destroyed){queued=false;void load();}}};
 const schedule=()=>{window.clearTimeout(timer);timer=window.setTimeout(()=>void load(),180);};
 const replaceComments=async()=>{if(commentChannel)await supabase.removeChannel(commentChannel);commentChannel=null;if(!active)return;commentChannel=supabase.channel(`gallery-conversation:${active.id}`).on('postgres_changes',{event:'*',schema:'public',table:'feed_comments',filter:`post_id=eq.${active.id}`},()=>void load(active?.id??null)).subscribe();};
 const open=async(r:Row)=>{if(!media(r))return;active=r;viewer.hidden=false;document.body.style.overflow='hidden';history.replaceState({},'',`/gallery.html?id=${encodeURIComponent(r.id)}`);try{const key=`rb_gallery_session_${r.id}`;let sid=sessionStorage.getItem(key);if(!sid){sid=crypto.randomUUID();sessionStorage.setItem(key,sid);}await Promise.allSettled([action('view',{post_id:r.id,session_id:sid}),replaceComments()]);await load(r.id);}catch(e){setStatus(e instanceof Error?e.message:'Viewer failed',true);}};
 const close=async()=>{viewer.hidden=true;const v=viewerMedia.querySelector<HTMLVideoElement>('video');if(v){v.pause();v.removeAttribute('src');v.load();}viewerMedia.innerHTML='';document.body.style.overflow='';active=null;snapshot.comments=[];if(commentChannel)await supabase.removeChannel(commentChannel);commentChannel=null;history.replaceState({},'','/gallery.html');};
 q<HTMLButtonElement>('#closeViewer').onclick=()=>void close();viewer.onclick=e=>{if(e.target===viewer)void close();};window.addEventListener('keydown',e=>{if(e.key==='Escape'&&!viewer.hidden)void close();});
 q<HTMLButtonElement>('#viewerLike').onclick=async()=>{if(!active||!auth())return;try{await action('toggle_like',{post_id:active.id});await load(active.id);}catch(e){setStatus(e instanceof Error?e.message:'Like failed',true);}};
 q<HTMLButtonElement>('#viewerSave').onclick=async()=>{if(!active||!auth())return;try{const r=await action('toggle_save',{post_id:active.id,collection_name:'Saved Visuals'});setStatus(r.saved?'SAVED TO COLLECTION':'REMOVED FROM COLLECTION');await load(active.id);}catch(e){setStatus(e instanceof Error?e.message:'Save failed',true);}};
 form.onsubmit=async e=>{e.preventDefault();if(!active||!auth())return;const body=input.value.trim();if(!body)return;const b=form.querySelector<HTMLButtonElement>('button')!;b.disabled=true;try{await action('comment',{post_id:active.id,body});input.value='';await load(active.id);}catch(err){setStatus(err instanceof Error?err.message:'Comment failed',true);}finally{b.disabled=false;}};
 renderTabs();await load();const requested=new URLSearchParams(location.search).get('id'),initial=rows.find(r=>r.id===requested);if(initial)await open(initial);channel=supabase.channel('gallery-visual-catalog').on('postgres_changes',{event:'*',schema:'public',table:'feed_posts',filter:'section=eq.gallery'},schedule).subscribe();
 const cleanup=()=>{if(destroyed)return;destroyed=true;window.clearTimeout(timer);document.body.style.overflow='';const v=viewerMedia.querySelector<HTMLVideoElement>('video');if(v)v.pause();if(channel)void supabase.removeChannel(channel);if(commentChannel)void supabase.removeChannel(commentChannel);};window.addEventListener('pagehide',cleanup,{once:true});window.addEventListener('beforeunload',cleanup,{once:true});
}