export const TABLES = Object.freeze({
  profiles: 'profiles',
  publicProfileCards: 'public_profile_cards',
  followers: 'followers',
  feedPosts: 'feed_posts',
  feedComments: 'feed_comments',
  uploads: 'uploads',
  musicTracks: 'music_tracks',
  podcastEpisodes: 'podcast_episodes',
  radioStations: 'radio_stations',
  liveStreams: 'live_streams',
  liveMembers: 'live_stream_members',
  liveChatMessages: 'live_chat_messages',
  liveReactions: 'live_reactions',
  games: 'games',
  gameRuntimeManifests: 'game_runtime_manifests',
  gameSessions: 'game_sessions',
  gameScores: 'game_scores',
  gamePlayerProgress: 'game_player_progress',
  metaAvatars: 'meta_avatars',
  avatarModels: 'avatar_models',
  avatarAnimationClips: 'avatar_animation_clips',
  avatarControllerProfiles: 'avatar_controller_profiles',
  avatarLoadouts: 'user_avatar_loadouts',
  avatarMotionState: 'avatar_motion_state',
  metaWorlds: 'meta_worlds',
  dmThreads: 'dm_threads',
  dmMessages: 'dm_messages',
  products: 'products',
  storeOrders: 'store_orders',
  userLevels: 'user_levels',
  xpEvents: 'xp_events',
  xpQueue: 'xp_event_queue',
  xpSectionProgress: 'xp_section_progress',
  notifications: 'rich_notifications'
} as const);

export type TableName = (typeof TABLES)[keyof typeof TABLES];
