import { supabase } from '../../core/supabase/client';
import '../../styles/media-universe.css';
import '../../styles/gaming-universe.css';

type Row=Record<string,any>;type Lane='games'|'tournaments'|'missions'|'clips'|'progress'|'rooms';
const esc=(v:any)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c));
const money=(v:any)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(v??0)/100);
const compact=(v:any)=>new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(Number(v??0));
const label=(v:any)=>String(v||'elite').replace(/[_-]+/g,' ').toUpperCase();
const art=(r:Row)=>r.cover_url||r.thumbnail_url||r.banner_url||'/images/brand/IMG_5997.png';
const safeLaunch=(v:any,f='/gaming.html')=>{try{const u=new URL(String(v||f),location.origin);return u.origin===location.origin?`${u.pathname}${u.search}${u.hash}`:f}catch{return f}};

export async function mountGamingPage():Promise<void>{
 const root=document.querySelector<HTMLElement>('#app');if(!root)throw new Error('Missing #app mount');
 const {data:{session}}=await supabase.auth.getSession();if(!session){location.replace('/tap-in.html?next=%2Fgaming.html');return}
 const [{data,error},{data:profile}]=await Promise.all([supabase.rpc('rb_media_universe_snapshot',{}),supabase.from('profiles').select('username,display_name,avatar_url,rich_level,rich_points,rank_title').eq('id',session.user.id).maybeSingle()]);if(error)throw error;
 const g=(data as any)?.gaming??{},games=(g.games??[]) as Row[],tournaments=(g.tournaments??[]) as Row[],missions=(g.missions??[]) as Row[],clips=(g.clips??[]) as Row[],progress=(g.progress??[]) as Row[],rewards=(g.rewards??[]) as Row[],rooms=(g.rooms??[]) as Row[];
 const lanes:Record<Lane,Row[]>={games,tournaments,missions,clips,progress,rooms};const requested=new URLSearchParams(location.search).get('id');let featured=games.find(x=>String(x.id)===requested)??games.find(x=>x.is_featured)??games[0]??null;let lane:Lane='games',category='all',query='';
 const categories=[...new Set(games.map(x=>String(x.game_type||'other').toLowerCase()))].sort();const totalXp=progress.reduce((n,x)=>n+Number(x.xp||0),0),best=progress.reduce((n,x)=>Math.max(n,Number(x.best_score||0)),0),active=games.reduce((n,x)=>n+Number(x.active_players||0),0),pool=tournaments.reduce((n,x)=>n+Number(x.prize_pool_cents||0),0);
 root.innerHTML=`<main class="gaming-elite-shell"><div class="gaming-elite-wrap">
 <header class="gaming-command-bar"><a class="gaming-back" href="/">←</a><div class="gaming-command-brand"><span>RICH BIZNESS PLAY NETWORK</span><h1>GAMING UNIVERSE</h1></div><div class="gaming-player-chip"><img src="${esc(profile?.avatar_url||'/images/brand/IMG_5997.png')}" alt=""><div><strong>${esc(profile?.display_name||profile?.username||'Rich Player')}</strong><span>${esc(profile?.rank_title||`LEVEL ${profile?.rich_level||1}`)}</span></div></div></header>
 <section id="gamingHero" class="gaming-hero"></section>
 <section class="gaming-live-strip"><article><span class="pulse-dot"></span><small>PLAYABLE WORLDS</small><strong>${games.filter(x=>x.is_playable).length}</strong><p>Production-ready individual runtimes.</p></article><article><small>ACTIVE PLAYERS</small><strong>${compact(active)}</strong><p>Live across every world.</p></article><article><small>OPEN ROOMS</small><strong>${rooms.length}</strong><p>Realtime multiplayer sessions.</p></article><article><small>PRIZE POOLS</small><strong>${money(pool)}</strong><p>Elite tournament rewards.</p></article></section>
 <section class="gaming-player-deck"><article><small>RICH XP</small><strong>${compact(totalXp)}</strong><span>Synced progression</span></article><article><small>BEST SCORE</small><strong>${compact(best)}</strong><span>Across all worlds</span></article><article><small>RICH POINTS</small><strong>${compact(profile?.rich_points||0)}</strong><span>Player economy</span></article><article><small>REWARDS</small><strong>${rewards.length}</strong><span>Unlocked vault items</span></article></section>
 <nav class="gaming-lanes">${([['games','◈','GAME WORLDS'],['tournaments','♛','TOURNAMENTS'],['missions','✦','MISSIONS'],['rooms','◉','LIVE ROOMS'],['clips','▶','CLIPS'],['progress','↑','MY PROGRESS']] as [Lane,string,string][]).map(([v,i,t],n)=>`<button class="gaming-lane ${n?'':'active'}" data-lane="${v}"><span>${i}</span>${t}</button>`).join('')}</nav>
 <section class="gaming-catalog"><header class="gaming-catalog-head"><div><span class="eyebrow">ELITE GAME COMMAND</span><h2 id="gamingLaneTitle">Game Worlds</h2><p id="gamingLaneCopy">Twenty-eight advanced game worlds with direct launch, multiplayer, tournaments and persistent progression.</p></div><div class="gaming-tools"><label class="gaming-search"><span>⌕</span><input id="gamingSearch" type="search" placeholder="Search games, genres or modes"></label><a class="gaming-upload" href="/upload.html?section=gaming">UPLOAD CLIP</a></div></header><div id="gamingCategories" class="gaming-categories"></div><div class="gaming-main-grid"><div id="gamingGrid" class="gaming-world-grid"></div><aside id="gamingCommand" class="gaming-inspector"></aside></div></section>
 <section class="gaming-bottom-grid"><article class="gaming-panel"><header><div><span class="eyebrow">LIVE COMPETITION</span><h3>Elite Tournaments</h3></div></header><div>${tournaments.slice(0,5).map(x=>`<div class="gaming-mini-row"><div><strong>${esc(x.title||x.name||'Elite Tournament')}</strong><span>${esc(label(x.status||'OPEN'))}</span></div><b>${money(x.prize_pool_cents)}</b></div>`).join('')||'<div class="gaming-empty">No active tournaments yet.</div>'}</div></article><article class="gaming-panel"><header><div><span class="eyebrow">PLAYER VAULT</span><h3>Recent Rewards</h3></div></header><div>${rewards.slice(0,5).map(x=>`<div class="gaming-mini-row"><div><strong>${esc(x.reward_type||x.badge||'Game Reward')}</strong><span>${esc(x.status||'earned')}</span></div><b>${x.xp?`+${compact(x.xp)} XP`:money(x.amount_cents)}</b></div>`).join('')||'<div class="gaming-empty">Rewards will appear here.</div>'}</div></article></section>
 </div></main>`;
 const hero=document.querySelector<HTMLElement>('#gamingHero')!,grid=document.querySelector<HTMLElement>('#gamingGrid')!,command=document.querySelector<HTMLElement>('#gamingCommand')!,cats=document.querySelector<HTMLElement>('#gamingCategories')!,search=document.querySelector<HTMLInputElement>('#gamingSearch')!;
 const names:Record<Lane,[string,string]>={games:['Game Worlds','Twenty-eight advanced game worlds with direct launch, multiplayer, tournaments and persistent progression.'],tournaments:['Elite Tournaments','Ranked seasons, championship brackets and prize pools.'],missions:['Mission Control','Daily and world-specific objectives awarding Rich XP.'],clips:['Community Clips','Gameplay highlights, boss fights and record moments.'],progress:['Player Progress','Every level, score and checkpoint in one command view.'],rooms:['Live Rooms','Active realtime multiplayer rooms across the network.']};
 function renderHero(){if(!featured){hero.innerHTML='<div class="gaming-empty">No active worlds.</div>';return}const p=progress.find(x=>String(x.game_id)===String(featured.id));const launch=safeLaunch(featured.play_url||`/games/${featured.slug}/`);hero.innerHTML=`<article class="gaming-feature" style="--feature-art:url('${esc(art(featured))}')"><div class="gaming-feature-shade"></div><div class="gaming-feature-content"><div class="gaming-feature-badges"><span class="ready"><i></i>${featured.is_playable?'PRODUCTION READY':'BUILDING'}</span><span>${esc(label(featured.game_type))}</span><span>${esc(label(featured.engine_type||featured.platform_type||'WEB'))}</span></div><h2>${esc(featured.title)}</h2><p>${esc(featured.description||'Enter an advanced Rich Bizness world with multiplayer, progression and elite competition.')}</p><div class="gaming-feature-stats"><div><small>LEVEL</small><strong>${p?.current_level||1}</strong></div><div><small>BEST</small><strong>${compact(p?.best_score||0)}</strong></div><div><small>PLAYERS</small><strong>${compact(featured.active_players||0)}</strong></div><div><small>PLAYS</small><strong>${compact(featured.total_plays||0)}</strong></div></div><div class="gaming-feature-actions"><a class="gaming-primary" href="${esc(launch)}">PLAY NOW <span>→</span></a><button id="heroDetails">GAME DETAILS</button><a href="/watch.html?gaming=${esc(featured.id)}">WATCH CLIPS</a></div></div></article>`;document.querySelector<HTMLButtonElement>('#heroDetails')!.onclick=()=>open(featured)}
 function renderCats(){if(lane!=='games'){cats.hidden=true;cats.innerHTML='';return}cats.hidden=false;cats.innerHTML=[`<button class="${category==='all'?'active':''}" data-category="all">ALL <b>${games.length}</b></button>`,...categories.map(c=>`<button class="${category===c?'active':''}" data-category="${esc(c)}">${esc(label(c))} <b>${games.filter(x=>String(x.game_type||'other').toLowerCase()===c).length}</b></button>`)].join('');cats.querySelectorAll<HTMLButtonElement>('[data-category]').forEach(b=>b.onclick=()=>{category=b.dataset.category||'all';renderCats();render()})}
 function rows(){return lanes[lane].filter(r=>{const text=`${r.title||''} ${r.slug||''} ${r.description||''} ${r.game_type||''} ${r.status||''}`.toLowerCase();return(lane!=='games'||category==='all'||String(r.game_type||'other').toLowerCase()===category)&&(!query||text.includes(query))})}
 function render(){const [t,c]=names[lane];document.querySelector<HTMLElement>('#gamingLaneTitle')!.textContent=t;document.querySelector<HTMLElement>('#gamingLaneCopy')!.textContent=c;const list=rows();grid.innerHTML=list.length?list.map((r,i)=>card(r,lane,i)).join(''):'<div class="gaming-empty">No matching worlds.</div>';grid.querySelectorAll<HTMLElement>('[data-row]').forEach(el=>el.onclick=()=>{const r=list.find(x=>String(x.id)===el.dataset.row);if(r){if(lane==='games'){featured=r;renderHero()}open(r)}})}
 function open(r:Row){const p=progress.find(x=>String(x.game_id)===String(r.id))??r,xp=Number(p.xp||0),pct=Math.max(4,Math.min(100,Math.round((xp%500)/5))),launch=safeLaunch(r.play_url||`/games/${r.slug||''}/`);command.innerHTML=`<div class="gaming-inspector-art" style="background-image:linear-gradient(180deg,transparent,rgba(0,0,0,.94)),url('${esc(art(r))}')"><span>${esc(label(r.game_type||r.status))}</span><h3>${esc(r.title||r.game_slug||r.room_code||'Game World')}</h3></div><div class="gaming-inspector-body"><div class="gaming-detail-line"><span>RUNTIME STATUS</span><strong class="status-ready">${esc(label(r.is_playable?'READY':r.runtime_status||r.status))}</strong></div><div class="gaming-xp"><div><span>LEVEL ${p.current_level||1}</span><strong>${compact(xp)} XP</strong></div><i><b style="width:${pct}%"></b></i></div><div class="gaming-detail-grid"><article><small>BEST</small><strong>${compact(p.best_score||0)}</strong></article><article><small>PLAYS</small><strong>${compact(r.total_plays||0)}</strong></article><article><small>ACTIVE</small><strong>${compact(r.active_players||0)}</strong></article><article><small>ENGINE</small><strong>${esc(label(r.engine_type||r.platform_type||'WEB'))}</strong></article></div>${lane==='games'?`<a class="gaming-inspector-launch" href="${esc(launch)}">LAUNCH WORLD <span>→</span></a>`:''}</div>`;if(r.id&&lane==='games')history.replaceState({},'',`/gaming.html?id=${encodeURIComponent(String(r.id))}`)}
 document.querySelectorAll<HTMLButtonElement>('[data-lane]').forEach(b=>b.onclick=()=>{lane=b.dataset.lane as Lane;document.querySelectorAll('[data-lane]').forEach(x=>x.classList.toggle('active',x===b));category='all';query='';search.value='';renderCats();render();const first=lanes[lane][0];if(first)open(first)});search.oninput=()=>{query=search.value.trim().toLowerCase();render()};renderHero();renderCats();render();if(featured)open(featured)
}
function card(r:Row,lane:Lane,i:number){const title=r.title||r.game_slug||r.mission_key||r.room_code||'Rich Gaming',badge=lane==='games'?(r.is_playable?'PLAYABLE':r.runtime_status):lane==='tournaments'?r.status:lane==='missions'?`${r.xp_reward||0} XP`:lane==='clips'?'CLIP':lane==='progress'?`LEVEL ${r.current_level||1}`:r.status,metric=lane==='tournaments'?money(r.prize_pool_cents):lane==='missions'?`${r.target_value||0} TARGET`:lane==='clips'?`${compact(r.view_count||0)} VIEWS`:lane==='progress'?`${compact(r.best_score||0)} BEST`:lane==='rooms'?r.room_code:`${compact(r.active_players||0)} ACTIVE`;return`<article class="gaming-world-card" data-row="${esc(r.id)}"><div class="gaming-world-art"><img src="${esc(art(r))}" alt=""><span>${esc(label(badge||'ACTIVE'))}</span><i>${i+1<10?'0':''}${i+1}</i></div><div class="gaming-world-body"><div><small>${esc(label(r.game_type||lane))}</small><h3>${esc(title)}</h3></div><p>${esc(r.description||r.caption||r.mission_type||'Advanced Rich Bizness gaming world.')}</p><footer><span>${esc(String(metric||'ACTIVE'))}</span><b>${esc(label(r.engine_type||r.platform_type||r.status||'WEB'))}</b></footer></div></article>`}
