import { getAuthSnapshot } from '../../core/auth/auth-store';
import { supabase } from '../../core/supabase/client';
import { GAMES, GAME_BY_SLUG } from '../../../../../packages/config/src/games';
import '../../styles/gaming-v4.css';

type Row=Record<string,any>;
type Lane='games'|'tournaments'|'missions'|'rooms'|'clips'|'progress';
type Channel=ReturnType<typeof supabase.channel>;
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]??c));
const compact=(v:unknown)=>new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(Number(v??0));
const money=(v:unknown)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(v??0)/100);
const label=(v:unknown)=>String(v||'elite').replace(/[_-]+/g,' ').toUpperCase();
const sameOrigin=(v:unknown,fallback='/gaming')=>{try{const u=new URL(String(v||fallback),location.origin);return u.origin===location.origin?`${u.pathname}${u.search}${u.hash}`:fallback}catch{return fallback}};
const visual=(row:Row)=>{const identity=row.metadata?.visual_identity??{};const symbol=identity.symbol||({strategy:'♛',fighting:'⚔',sports:'🏆',rpg:'◆',party:'♣',arcade:'◈'} as Row)[row.game_type]||'◈';const a=identity.tone_a||'#31ff63',b=identity.tone_b||'#061008';const image=row.cover_url||row.thumbnail_url||row.banner_url||'';return `<div class="gv-visual ${image?'has-art':'procedural'}" style="--gv-a:${esc(a)};--gv-b:${esc(b)};${image?`--gv-image:url('${esc(image)}')`:''}"><i>${esc(symbol)}</i><span>${esc(String(row.title||'RB').split(/\s+/).map((x:string)=>x[0]).join('').slice(0,3))}</span></div>`};
const canonicalizeGames=(rows:Row[]):Row[]=>{const bySlug=new Map<string,Row>();for(const row of rows){const slug=String(row.slug||'').trim().toLowerCase();if(!slug||!GAME_BY_SLUG[slug as keyof typeof GAME_BY_SLUG])continue;const canonical=GAME_BY_SLUG[slug as keyof typeof GAME_BY_SLUG];const previous=bySlug.get(slug);const normalized={...previous,...row,slug,title:row.title||canonical.title,play_url:canonical.route,module_path:row.module_path||`/src/pages/games/${slug}.page.ts`,runtime_status:row.runtime_status||'production_ready',is_playable:row.is_playable!==false,is_active:row.is_active!==false};if(!previous||Number(row.updated_at?Date.parse(row.updated_at):0)>=Number(previous.updated_at?Date.parse(previous.updated_at):0))bySlug.set(slug,normalized)}return GAMES.map(game=>bySlug.get(game.slug)).filter(Boolean) as Row[]};

export async function mountGamingPage():Promise<void>{
 const root=document.querySelector<HTMLElement>('#app');if(!root)throw new Error('Missing #app mount');if(root.dataset.gamingOwner==='v5')return;root.dataset.gamingOwner='v5';
 const auth=getAuthSnapshot(),user=auth.user,userId=user?.id??null;let snap:Row={},games:Row[]=[],tournaments:Row[]=[],missions:Row[]=[],rooms:Row[]=[],clips:Row[]=[],progress:Row[]=[],rewards:Row[]=[],profile:Row={};let lane:Lane='games',category='all',query='',featured:Row|null=null,channel:Channel|null=null,disposed=false,loading:Promise<void>|null=null,queued=false,refreshTimer:number|undefined;const requested=new URLSearchParams(location.search).get('id');const launchChannel=typeof BroadcastChannel!=='undefined'?new BroadcastChannel('rb-gaming-runtime'):null;
 root.innerHTML=`<main class="gv-shell"><div class="gv-wrap"><header class="gv-top"><a href="/portal" aria-label="Back">←</a><div><small>RICH BIZNESS LLC • LIVE PLAY NETWORK</small><h1>GAMING UNIVERSE</h1></div><div id="gvPlayer" class="gv-player"></div></header><nav class="gv-network"><a href="/watch?lane=gaming">WE 🔥 📺</a><a href="/live">WE LIT 🔥</a><a href="/feed?section=gaming">FEED</a><a href="/upload?route=gaming-clips">CLIPS</a><a href="/store?lane=gaming">GAME STORE</a></nav><section id="gvHero" class="gv-hero"></section><section id="gvMetrics" class="gv-metrics"></section><nav class="gv-lanes">${([['games','◈','28 WORLDS'],['tournaments','♛','TOURNAMENTS'],['missions','✦','MISSIONS'],['rooms','◉','ROOMS'],['clips','▶','CLIPS'],['progress','↑','PROGRESS']] as [Lane,string,string][]).map(([v,i,t],n)=>`<button class="${n?'':'active'}" data-lane="${v}"><b>${i}</b>${t}</button>`).join('')}</nav><section class="gv-command"><header><div><small>ELITE GAME COMMAND</small><h2 id="gvTitle">All 28 Game Worlds</h2><p id="gvCopy">Exactly 28 canonical games. No duplicate titles, routes, slugs or runtime owners.</p></div><label><span>⌕</span><input id="gvSearch" type="search" placeholder="Search worlds, modes, genres"></label></header><div id="gvCategories" class="gv-categories"></div><div class="gv-layout"><div id="gvGrid" class="gv-grid"></div><aside id="gvInspector" class="gv-inspector"></aside></div></section><section class="gv-bottom"><article><header><small>LIVE COMPETITION</small><h3>Elite Tournaments</h3></header><div id="gvTournaments"></div></article><article><header><small>PLAYER VAULT</small><h3>Recent Rewards</h3></header><div id="gvRewards"></div></article></section><p id="gvStatus" class="gv-status"></p></div></main>`;
 const $=<T extends HTMLElement>(s:string)=>root.querySelector<T>(s)!;const sources=():Record<Lane,Row[]>=>({games,tournaments,missions,rooms,clips,progress});const rows=()=>sources()[lane].filter(r=>{const text=`${r.title||''} ${r.slug||''} ${r.description||''} ${r.game_type||''} ${r.status||''}`.toLowerCase();return(lane!=='games'||category==='all'||String(r.game_type||'other').toLowerCase()===category)&&(!query||text.includes(query))});const progressFor=(g:Row)=>progress.find(p=>String(p.game_id)===String(g.id));const runtimeReady=(g:Row)=>Boolean(g.is_active!==false&&g.is_playable!==false&&String(g.runtime_status)==='production_ready'&&GAME_BY_SLUG[String(g.slug) as keyof typeof GAME_BY_SLUG]);const setGameUrl=(g:Row|null)=>{const url=new URL(location.href);if(g?.id)url.searchParams.set('id',String(g.id));else url.searchParams.delete('id');history.replaceState({},'',`${url.pathname}${url.search}${url.hash}`)};const scheduleLoad=()=>{if(disposed)return;if(refreshTimer)clearTimeout(refreshTimer);refreshTimer=window.setTimeout(()=>void load(),180)};const runtimeStorageKey=(slug:string)=>`rb.game.session.${slug}`;
 async function launchGame(g:Row){if(!runtimeReady(g))return;const canonical=GAME_BY_SLUG[String(g.slug) as keyof typeof GAME_BY_SLUG];const destination=sameOrigin(canonical?.route||g.play_url||`/${g.slug}`);if(!user){location.href=`/tap-in?next=${encodeURIComponent(destination)}`;return}$('#gvStatus').textContent=`STARTING ${label(g.title)} SESSION…`;const deviceInfo={user_agent:navigator.userAgent,language:navigator.language,viewport:{width:innerWidth,height:innerHeight},touch:navigator.maxTouchPoints>0};const {data,error}=await supabase.rpc('rb_game_action',{p_action:'start_session',p_game_slug:g.slug,p_payload:{platform_type:'web',device_info:deviceInfo,metadata:{source:'gaming_v5',route:location.pathname}}});if(error){$('#gvStatus').textContent=`SESSION ERROR • ${error.message}`;return}const sessionKey=String((data as Row)?.session_key||'');if(!sessionKey){$('#gvStatus').textContent='SESSION ERROR • MISSING SESSION KEY';return}const startedAt=Date.now();sessionStorage.setItem(runtimeStorageKey(g.slug),JSON.stringify({sessionKey,gameId:g.id,slug:g.slug,startedAt}));launchChannel?.postMessage({type:'session-started',gameId:g.id,slug:g.slug,sessionKey,startedAt});const target=new URL(destination,location.origin);target.searchParams.set('session',sessionKey);target.searchParams.set('game',g.slug);location.href=`${target.pathname}${target.search}${target.hash}`}
 function bindLaunches(g:Row|null){if(!g)return;root.querySelectorAll<HTMLElement>('[data-launch-game]').forEach(el=>el.onclick=e=>{e.preventDefault();void launchGame(g)})}
 function renderPlayer(){const avatar=profile.avatar_url;$('#gvPlayer').innerHTML=`${avatar?`<img src="${esc(avatar)}" alt="">`:'<span>♛</span>'}<div><strong>${esc(profile.display_name||profile.username||(user?'Rich Player':'Public Player'))}</strong><small>${esc(user?(profile.rank_title||`LEVEL ${profile.rich_level||1}`):'PUBLIC ARCADE')}</small></div>`}
 function renderMetrics(){const m=snap.metrics??{};const ready=games.filter(runtimeReady).length;$('#gvMetrics').innerHTML=`<article><small>CANONICAL WORLDS</small><strong>${games.length}</strong><span>${games.length===28?'Exactly 28 unique':'Catalog check required'}</span></article><article><small>VERIFIED RUNTIMES</small><strong>${ready}</strong><span>Playable + production ready</span></article><article><small>ACTIVE PLAYERS</small><strong>${compact(m.active_players??0)}</strong><span>Across the network</span></article><article><small>OPEN ROOMS</small><strong>${m.open_rooms??rooms.length}</strong><span>Realtime sessions</span></article>`;$('#gvTournaments').innerHTML=tournaments.slice(0,5).map(t=>`<div class="gv-row"><div><strong>${esc(t.title||'Elite Tournament')}</strong><span>${esc(label(t.status||'open'))}</span></div><b>${money(t.prize_pool_cents)}</b></div>`).join('')||'<p class="gv-empty">No active tournaments.</p>';$('#gvRewards').innerHTML=user?(rewards.slice(0,5).map(r=>`<div class="gv-row"><div><strong>${esc(r.reward_type||r.badge||'Game Reward')}</strong><span>${esc(r.status||'earned')}</span></div><b>${r.xp?`+${compact(r.xp)} XP`:money(r.amount_cents)}</b></div>`).join('')||'<p class="gv-empty">Rewards appear here.</p>'):'<p class="gv-empty">Tap in to open your vault.</p>'}
 function renderHero(){if(!featured){$('#gvHero').innerHTML='<p class="gv-empty">No active worlds.</p>';return}const p=progressFor(featured),ready=runtimeReady(featured);$('#gvHero').innerHTML=`<article><div class="gv-hero-visual">${visual(featured)}</div><div class="gv-hero-copy"><div class="gv-badges"><span>● ${ready?'LIVE RUNTIME VERIFIED':'CHECKING'}</span><span>${esc(label(featured.game_type))}</span><span>${esc(label(featured.engine_type||featured.platform_type||'WEB'))}</span><span>WORLD ${String(featured.metadata?.catalog_order||GAMES.findIndex(x=>x.slug===featured?.slug)+1).padStart(2,'0')} / 28</span></div><h2>${esc(featured.title)}</h2><p>${esc(featured.description||'Advanced Rich Bizness game world with persistent progression, competition and multiplayer-ready architecture.')}</p><div class="gv-hero-stats"><div><small>LEVEL</small><strong>${p?.current_level||1}</strong></div><div><small>BEST</small><strong>${compact(p?.best_score||0)}</strong></div><div><small>PLAYS</small><strong>${compact(featured.total_plays||0)}</strong></div><div><small>ACTIVE</small><strong>${compact(featured.active_players||0)}</strong></div></div><div class="gv-actions"><a class="primary ${ready?'':'disabled'}" data-launch-game href="#launch">${ready?'PLAY NOW →':'RUNTIME CHECK'}</a><button id="gvDetail">GAME DETAILS</button><a href="/watch?gaming=${esc(featured.id)}">WATCH</a></div></div></article>`;$('#gvDetail').onclick=()=>open(featured!);bindLaunches(featured)}
 function renderCategories(){const host=$('#gvCategories');if(lane!=='games'){host.hidden=true;host.innerHTML='';return}host.hidden=false;const values=[...new Set(games.map(g=>String(g.game_type||'other').toLowerCase()))].sort();host.innerHTML=[`<button class="${category==='all'?'active':''}" data-cat="all">ALL <b>${games.length}</b></button>`,...values.map(v=>`<button class="${category===v?'active':''}" data-cat="${esc(v)}">${esc(label(v))} <b>${games.filter(g=>String(g.game_type||'other').toLowerCase()===v).length}</b></button>`)].join('');host.querySelectorAll<HTMLButtonElement>('[data-cat]').forEach(b=>b.onclick=()=>{category=b.dataset.cat||'all';renderCategories();renderGrid()})}
 function card(r:Row,index:number){const title=r.title||r.game_slug||r.mission_key||r.room_code||'Rich Gaming';const metric=lane==='games'?`${compact(r.active_players||0)} ACTIVE`:lane==='tournaments'?money(r.prize_pool_cents):lane==='missions'?`${r.xp_reward||0} XP`:lane==='progress'?`${compact(r.best_score||0)} BEST`:lane==='rooms'?(r.room_code||'ROOM'):`${compact(r.view_count||0)} VIEWS`;const ready=lane==='games'?runtimeReady(r):true;return `<article class="gv-card ${ready?'':'runtime-warning'}" data-id="${esc(r.id)}"><div class="gv-card-art">${lane==='games'?visual(r):`<div class="gv-visual procedural"><i>${lane==='tournaments'?'♛':lane==='missions'?'✦':lane==='rooms'?'◉':lane==='clips'?'▶':'↑'}</i><span>${String(index+1).padStart(2,'0')}</span></div>`}<em>${String(index+1).padStart(2,'0')}</em></div><div class="gv-card-body"><small>${esc(label(r.game_type||lane))}</small><h3>${esc(title)}</h3><p>${esc(r.description||r.caption||r.mission_type||'Advanced Rich Bizness game system.')}</p><footer><span>${esc(metric)}</span><b>${esc(ready?label(r.runtime_status||r.status||r.engine_type||'READY'):'ROUTE CHECK')}</b></footer></div></article>`}
 function renderGrid(){const list=rows();$('#gvGrid').innerHTML=list.map(card).join('')||'<p class="gv-empty">No matching worlds.</p>';$('#gvGrid').querySelectorAll<HTMLElement>('[data-id]').forEach(el=>el.onclick=()=>{const r=list.find(x=>String(x.id)===el.dataset.id);if(!r)return;if(lane==='games'){featured=r;renderHero()}open(r)})}
 function open(r:Row){const p=progressFor(r)??r,caps=r.capabilities&&typeof r.capabilities==='object'?Object.keys(r.capabilities).filter(k=>r.capabilities[k]):[],ready=lane==='games'?runtimeReady(r):true;$('#gvInspector').innerHTML=`${visual(r)}<div class="gv-inspector-body"><small>${esc(label(r.game_type||lane))}</small><h3>${esc(r.title||r.game_slug||r.room_code||'Game World')}</h3><p>${esc(r.description||'Persistent Rich Bizness game runtime.')}</p><div class="gv-detail"><span>RUNTIME <b>${esc(ready?'VERIFIED':label(r.runtime_status||r.status||'checking'))}</b></span><span>LEVEL <b>${p.current_level||1}</b></span><span>BEST <b>${compact(p.best_score||0)}</b></span><span>ENGINE <b>${esc(label(r.engine_type||r.platform_type||'web'))}</b></span></div>${caps.length?`<div class="gv-caps">${caps.slice(0,8).map(c=>`<span>${esc(label(c))}</span>`).join('')}</div>`:''}${lane==='games'&&ready?'<a data-launch-game href="#launch">LAUNCH WORLD →</a>':''}</div>`;if(r.id&&lane==='games'){setGameUrl(r);bindLaunches(r)}}
 function render(){const names:Record<Lane,[string,string]>={games:['All 28 Game Worlds','Exactly 28 canonical titles in manifest order, with duplicate rows filtered before rendering.'],tournaments:['Elite Tournaments','Ranked seasons, championship brackets and prize pools.'],missions:['Mission Control','Daily and world-specific objectives awarding Rich XP.'],rooms:['Live Rooms','Realtime multiplayer rooms across the network.'],clips:['Community Clips','Gameplay highlights and record moments.'],progress:['Player Progress',user?'Every level, score and checkpoint in one view.':'Tap in to synchronize progression.']};const [t,c]=names[lane];$('#gvTitle').textContent=t;$('#gvCopy').textContent=c;renderCategories();renderGrid();const first=rows()[0];if(first)open(first)}
 async function load(){if(disposed)return;if(loading){queued=true;return loading}loading=(async()=>{const {data,error}=await supabase.rpc('rb_gaming_snapshot',{p_user_id:userId,p_game_id:requested||null,p_limit:80});if(error){$('#gvStatus').textContent=`LOAD ERROR • ${error.message}`;return}snap=(data??{}) as Row;games=canonicalizeGames(Array.isArray(snap.games)?snap.games:[]);tournaments=Array.isArray(snap.tournaments)?snap.tournaments:[];missions=Array.isArray(snap.missions)?snap.missions:[];rooms=Array.isArray(snap.rooms)?snap.rooms:[];clips=Array.isArray(snap.clips)?snap.clips:[];progress=Array.isArray(snap.progress)?snap.progress:[];rewards=Array.isArray(snap.rewards)?snap.rewards:[];profile=snap.profile??{};featured=games.find(g=>String(g.id)===requested)||games.find(g=>g.is_featured)||games[0]||null;renderPlayer();renderMetrics();renderHero();render();$('#gvStatus').textContent=`${games.length}/28 UNIQUE WORLDS • ${games.filter(runtimeReady).length} VERIFIED RUNTIMES`})().finally(()=>{loading=null;if(queued){queued=false;void load()}});return loading}
 root.querySelectorAll<HTMLButtonElement>('[data-lane]').forEach(b=>b.onclick=()=>{lane=b.dataset.lane as Lane;root.querySelectorAll('[data-lane]').forEach(x=>x.classList.toggle('active',x===b));render()});$('#gvSearch').oninput=e=>{query=(e.currentTarget as HTMLInputElement).value.trim().toLowerCase();renderGrid()};await load();channel=supabase.channel(`gaming-v5-${userId||'public'}`).on('postgres_changes',{event:'*',schema:'public',table:'games'},scheduleLoad).on('postgres_changes',{event:'*',schema:'public',table:'game_sessions'},scheduleLoad).on('postgres_changes',{event:'*',schema:'public',table:'game_rooms'},scheduleLoad).subscribe();const cleanup=()=>{disposed=true;if(refreshTimer)clearTimeout(refreshTimer);if(channel)void supabase.removeChannel(channel);launchChannel?.close();root.dataset.gamingOwner='';window.removeEventListener('pagehide',cleanup)};window.addEventListener('pagehide',cleanup,{once:true})
}
