import { getAuthSnapshot } from '../../core/auth/auth-store';
import { supabase } from '../../core/supabase/client';
import './creator.css';

type Row=Record<string,any>;
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c));
const money=(v:unknown,c='usd')=>new Intl.NumberFormat('en-US',{style:'currency',currency:String(c||'usd').toUpperCase()}).format(Number(v??0)/100);
const safeMedia=(v:unknown)=>{try{const u=new URL(String(v||''),location.origin);return ['http:','https:'].includes(u.protocol)?u.href:'';}catch{return'';}};
const safeRoute=(v:string)=>{try{const u=new URL(v,location.origin);return u.origin===location.origin?`${u.pathname}${u.search}${u.hash}`:'/creator.html';}catch{return'/creator.html';}};

export async function mount():Promise<void>{
 const root=document.querySelector<HTMLElement>('#app');if(!root)throw new Error('Missing #app');if(root.dataset.creatorOwner==='mounted')return;root.dataset.creatorOwner='mounted';
 const user=getAuthSnapshot().user;if(!user){location.replace('/tap-in.html?next=%2Fcreator.html');return;}
 root.innerHTML=`<main class="creator-shell"><div class="creator-wrap"><header class="creator-head"><a href="/portal.html" aria-label="Back to portal">←</a><div><p>RICH BIZNESS CREATOR COMMAND</p><h1>Creator Universe</h1></div><span class="creator-live"><i></i> MONETIZATION LIVE</span></header><section id="creatorHero" class="creator-hero"><div class="creator-hero__copy"><span class="creator-kicker">BUILD · PUBLISH · EARN · CONTROL</span><h2 id="creatorTitle">YOUR CREATOR UNIVERSE</h2><p id="creatorTagline">Connect every section of your brand from one command center.</p><div class="creator-actions"><a class="creator-btn primary" href="/upload.html">CREATE DROP</a><a class="creator-btn" href="/live.html">GO LIVE</a><a class="creator-btn" href="/store.html">MANAGE STORE</a><a class="creator-btn" href="/creator-dimensions.html">SECRET DIMENSIONS</a><a class="creator-btn" href="/profile.html">VIEW PROFILE</a></div></div></section><section id="creatorMetrics" class="creator-metrics"></section><nav id="creatorTabs" class="creator-tabs"></nav><section id="creatorContent"></section><p id="creatorStatus" class="creator-status" role="status"></p></div></main>`;
 const hero=root.querySelector<HTMLElement>('#creatorHero')!,metrics=root.querySelector<HTMLElement>('#creatorMetrics')!,tabs=root.querySelector<HTMLElement>('#creatorTabs')!,content=root.querySelector<HTMLElement>('#creatorContent')!,status=root.querySelector<HTMLElement>('#creatorStatus')!;
 let lane='overview',profile:Row={},settings:Row={},balance:Row={},tracks:Row[]=[],products:Row[]=[],streams:Row[]=[],worlds:Row[]=[],games:Row[]=[],posts:Row[]=[],alerts=0,loading=false,queued=false,destroyed=false,refreshTimer:number|undefined;
 const channels:ReturnType<typeof supabase.channel>[]=[];
 const lanes=[['overview','OVERVIEW'],['brand','BRAND'],['content','CONTENT'],['money','MONEY'],['dimensions','SECRET DOOR']];
 const setStatus=(m:string,e=false)=>{if(destroyed)return;status.textContent=m;status.dataset.error=String(e);};
 const card=(title:string,subtitle:string,url:string,image?:unknown,badge='CREATOR',meta='')=>{const art=safeMedia(image)||'/images/brand/IMG_5997.png';return `<article class="creator-card"><div class="creator-card__media"><img src="${esc(art)}" alt="" loading="lazy"><span class="creator-card__badge">${esc(badge)}</span></div><div class="creator-card__body"><h3>${esc(title)}</h3><p>${esc(subtitle)}</p>${meta?`<div class="creator-card__meta"><span>${esc(meta)}</span></div>`:''}<div class="creator-card__actions"><a href="${esc(safeRoute(url))}">OPEN</a></div></div></article>`;};
 const drawTabs=()=>{tabs.innerHTML=lanes.map(([k,l])=>`<button class="creator-tab ${lane===k?'active':''}" data-lane="${k}">${l}</button>`).join('');tabs.querySelectorAll<HTMLButtonElement>('[data-lane]').forEach(b=>b.onclick=()=>{lane=b.dataset.lane||'overview';drawTabs();render();});};
 const render=()=>{
  const art=safeMedia(settings.hero_background_url)||safeMedia(profile.banner_url)||'/images/brand/IMG_5997.png';hero.style.setProperty('--creator-hero',`url("${art.replaceAll('"','%22')}")`);root.querySelector<HTMLElement>('#creatorTitle')!.textContent=settings.creator_title||profile.display_name||'YOUR CREATOR UNIVERSE';root.querySelector<HTMLElement>('#creatorTagline')!.textContent=settings.creator_tagline||profile.bio||'Connect every section of your brand from one command center.';
  metrics.innerHTML=`<article><small>AVAILABLE</small><strong>${money(balance.available_cents,balance.currency)}</strong></article><article><small>PENDING</small><strong>${money(balance.pending_cents,balance.currency)}</strong></article><article><small>TOTAL DROPS</small><strong>${posts.length+tracks.length+products.length}</strong></article><article><small>ALERT MEMBERS</small><strong>${alerts.toLocaleString()}</strong></article>`;
  if(lane==='overview')content.innerHTML=`<section class="creator-section"><header><div><p>FOUR CREATOR SYSTEMS</p><h2>Your creator command deck</h2></div><a class="creator-btn primary" href="/upload.html">NEW DROP</a></header><div class="creator-grid">${card('Brand Command','Public identity, theme and featured content','/creator.html?lane=brand',profile.banner_url,'01 BRAND')}${card('Content Engine',`${posts.length+tracks.length+products.length+streams.length} connected releases`,'/creator.html?lane=content',tracks[0]?.cover_url||products[0]?.image_url,'02 CONTENT')}${card('Money Position',`${money(balance.available_cents,balance.currency)} available`,'/creator.html?lane=money',profile.avatar_url,'03 MONEY')}${card('Secret Door','Four protected paid creator dimensions','/creator-dimensions.html',profile.banner_url,'04 SECRET')}</div></section>`;
  else if(lane==='brand'){
   content.innerHTML=`<section class="creator-section"><header><div><p>PUBLIC CREATOR IDENTITY</p><h2>Control your universe</h2></div></header><form id="creatorForm" class="creator-form"><div class="creator-form-row"><input id="creatorTitleInput" maxlength="100" placeholder="Creator title" value="${esc(settings.creator_title)}"><input id="creatorTaglineInput" maxlength="180" placeholder="Creator tagline" value="${esc(settings.creator_tagline)}"></div><div class="creator-form-row"><input id="heroBackground" placeholder="Hero background URL" value="${esc(settings.hero_background_url)}"><input id="heroVideo" placeholder="Hero video URL" value="${esc(settings.hero_video_url)}"></div><div class="creator-form-row"><select id="pageTheme"><option value="smoke-cloud">SMOKE CLOUD</option><option value="cinematic">CINEMATIC</option><option value="neon">NEON</option></select><select id="introStyle"><option value="cinematic">CINEMATIC</option><option value="clean">CLEAN</option><option value="portal">PORTAL</option></select></div><div class="creator-form-row"><select id="monetizationStyle"><option value="premium">PREMIUM</option><option value="balanced">BALANCED</option><option value="community">COMMUNITY</option></select><select id="featuredTrack"><option value="">NO FEATURED TRACK</option>${tracks.map(r=>`<option value="${r.id}">${esc(r.title)}</option>`).join('')}</select></div><div class="creator-form-row"><select id="featuredProduct"><option value="">NO FEATURED PRODUCT</option>${products.map(r=>`<option value="${r.id}">${esc(r.title)}</option>`).join('')}</select><select id="featuredLive"><option value="">NO FEATURED LIVE</option>${streams.map(r=>`<option value="${r.id}">${esc(r.title)}</option>`).join('')}</select></div><div class="creator-form-row"><select id="featuredWorld"><option value="">NO FEATURED WORLD</option>${worlds.map(r=>`<option value="${r.id}">${esc(r.title)}</option>`).join('')}</select><select id="featuredGame"><option value="">NO FEATURED GAME</option>${games.map(r=>`<option value="${r.id}">${esc(r.title)}</option>`).join('')}</select></div><div class="creator-form-row"><label><input id="showMusic" type="checkbox" ${settings.show_music!==false?'checked':''}> SHOW MUSIC</label><label><input id="showStore" type="checkbox" ${settings.show_store!==false?'checked':''}> SHOW STORE</label></div><div class="creator-form-row"><label><input id="showLive" type="checkbox" ${settings.show_live!==false?'checked':''}> SHOW LIVE</label><label><input id="showMeta" type="checkbox" ${settings.show_meta!==false?'checked':''}> SHOW META</label></div><div class="creator-form-row"><label><input id="showGallery" type="checkbox" ${settings.show_gallery!==false?'checked':''}> SHOW GALLERY</label><label><input id="showGames" type="checkbox" ${settings.show_games!==false?'checked':''}> SHOW GAMES</label></div><button class="creator-btn primary" type="submit">SAVE CREATOR UNIVERSE</button></form></section>`;
   const set=(id:string,v:unknown)=>{const el=root.querySelector<HTMLSelectElement>(`#${id}`);if(el&&v!=null)el.value=String(v);};set('pageTheme',settings.page_theme||'smoke-cloud');set('introStyle',settings.intro_style||'cinematic');set('monetizationStyle',settings.monetization_style||'premium');set('featuredTrack',settings.featured_track_id||'');set('featuredProduct',settings.featured_product_id||'');set('featuredLive',settings.featured_live_id||'');set('featuredWorld',settings.featured_world_id||'');set('featuredGame',settings.featured_game_id||'');
   root.querySelector<HTMLFormElement>('#creatorForm')!.onsubmit=async e=>{e.preventDefault();const heroBackground=root.querySelector<HTMLInputElement>('#heroBackground')!.value.trim(),heroVideo=root.querySelector<HTMLInputElement>('#heroVideo')!.value.trim();if(heroBackground&&!safeMedia(heroBackground))return setStatus('Hero background must use HTTP or HTTPS.',true);if(heroVideo&&!safeMedia(heroVideo))return setStatus('Hero video must use HTTP or HTTPS.',true);const payload={creator_title:root.querySelector<HTMLInputElement>('#creatorTitleInput')!.value.trim(),creator_tagline:root.querySelector<HTMLInputElement>('#creatorTaglineInput')!.value.trim(),hero_background_url:heroBackground||null,hero_video_url:heroVideo||null,page_theme:root.querySelector<HTMLSelectElement>('#pageTheme')!.value,intro_style:root.querySelector<HTMLSelectElement>('#introStyle')!.value,monetization_style:root.querySelector<HTMLSelectElement>('#monetizationStyle')!.value,featured_track_id:root.querySelector<HTMLSelectElement>('#featuredTrack')!.value||null,featured_product_id:root.querySelector<HTMLSelectElement>('#featuredProduct')!.value||null,featured_live_id:root.querySelector<HTMLSelectElement>('#featuredLive')!.value||null,featured_world_id:root.querySelector<HTMLSelectElement>('#featuredWorld')!.value||null,featured_game_id:root.querySelector<HTMLSelectElement>('#featuredGame')!.value||null,show_music:root.querySelector<HTMLInputElement>('#showMusic')!.checked,show_store:root.querySelector<HTMLInputElement>('#showStore')!.checked,show_live:root.querySelector<HTMLInputElement>('#showLive')!.checked,show_meta:root.querySelector<HTMLInputElement>('#showMeta')!.checked,show_gallery:root.querySelector<HTMLInputElement>('#showGallery')!.checked,show_games:root.querySelector<HTMLInputElement>('#showGames')!.checked};setStatus('SAVING CREATOR UNIVERSE…');const{error}=await supabase.rpc('rb_creator_save_page',{p_payload:payload});if(error)return setStatus(error.message,true);setStatus('CREATOR UNIVERSE SAVED — XP SYNCED');await load();};
  }else if(lane==='content'){const rows=[...posts.map(r=>card(r.title||r.body||'Feed Drop',r.section||r.post_type||'feed',`/feed.html?post=${r.id}`,r.thumbnail_url||r.cover_url||r.media_url,'FEED',`${Number(r.view_count??0).toLocaleString()} views`)),...tracks.map(r=>card(r.title||'Music Drop',r.genre||'music',`/music.html?track=${r.id}`,r.cover_url,'MUSIC',`${Number(r.play_count??0).toLocaleString()} plays`)),...products.map(r=>card(r.title||'Store Drop',money(r.price_cents,r.currency),`/store.html?product=${r.id}`,r.image_url||r.cover_url,'STORE',`${Number(r.sales_count??0).toLocaleString()} sold`)),...streams.map(r=>card(r.title||'Live Broadcast',r.status||'live',`/live.html?id=${r.id}`,r.thumbnail_url||r.cover_url,'LIVE',`${Number(r.viewer_count??0).toLocaleString()} viewers`))];content.innerHTML=`<section class="creator-section"><header><div><p>YOUR PUBLISHED UNIVERSE</p><h2>Content command</h2></div><a class="creator-btn primary" href="/upload.html">CREATE DROP</a></header><div class="creator-grid">${rows.join('')||'<div class="creator-empty">Your creator content will appear here.</div>'}</div></section>`;
  }else if(lane==='money')content.innerHTML=`<section class="creator-section"><header><div><p>CREATOR WALLET</p><h2>Revenue position</h2></div></header><div class="creator-metrics"><article><small>EARNED</small><strong>${money(balance.earned_cents,balance.currency)}</strong></article><article><small>AVAILABLE</small><strong>${money(balance.available_cents,balance.currency)}</strong></article><article><small>PENDING</small><strong>${money(balance.pending_cents,balance.currency)}</strong></article><article><small>PAID OUT</small><strong>${money(balance.paid_out_cents,balance.currency)}</strong></article></div><div class="creator-actions"><a class="creator-btn primary" href="/settings.html">PAYOUT SETTINGS</a><a class="creator-btn" href="/store.html">ORDER CENTER</a><a class="creator-btn" href="/notifications.html">${alerts.toLocaleString()} ALERT MEMBERS</a></div></section>`;
  else content.innerHTML=`<section class="creator-section"><header><div><p>SECRET CREATOR NETWORK</p><h2>Four paid dimensions</h2></div><a class="creator-btn primary" href="/creator-dimensions.html">ENTER GATE</a></header><div class="creator-grid">${card('On The Go','Mobile earning and dispatch dimension','/creator-dimensions.html?dimension=on_the_go',profile.banner_url,'PAID')}${card('Dash Businesses','Private business operations network','/creator-dimensions.html?dimension=dash_businesses',profile.banner_url,'PAID')}${card('Private World','Members-only social and Meta world','/creator-dimensions.html?dimension=private_world',profile.banner_url,'PAID')}${card('Movies','Premium cinema and screening dimension','/creator-dimensions.html?dimension=movies',profile.banner_url,'PAID')}</div></section>`;
 };
 const load=async()=>{if(destroyed)return;if(loading){queued=true;return;}loading=true;const id=user.id;const r=await Promise.all([supabase.from('profiles').select('*').eq('id',id).single(),supabase.from('creator_page_settings').select('*').eq('user_id',id).maybeSingle(),supabase.from('creator_available_balances').select('*').eq('artist_user_id',id).maybeSingle(),supabase.from('music_tracks').select('*').eq('user_id',id).order('created_at',{ascending:false}).limit(30),supabase.from('products').select('*').eq('seller_id',id).order('created_at',{ascending:false}).limit(30),supabase.from('live_streams').select('*').eq('creator_id',id).order('created_at',{ascending:false}).limit(30),supabase.from('meta_worlds').select('*').eq('owner_id',id).order('created_at',{ascending:false}).limit(30),supabase.from('feed_posts').select('*').eq('user_id',id).order('created_at',{ascending:false}).limit(30),supabase.from('creator_alert_subscriptions').select('id',{count:'exact',head:true}).eq('creator_id',id).eq('is_active',true),supabase.from('games').select('*').eq('is_active',true).order('is_featured',{ascending:false}).limit(30)]);loading=false;if(destroyed)return;const err=r.find(x=>x.error)?.error;if(err)return setStatus(err.message,true);profile=r[0].data??{};settings=r[1].data??{};balance=r[2].data??{};tracks=r[3].data??[];products=r[4].data??[];streams=r[5].data??[];worlds=r[6].data??[];posts=r[7].data??[];alerts=r[8].count??0;games=r[9].data??[];render();if(queued){queued=false;void load();}};
 const requested=new URLSearchParams(location.search).get('lane');if(requested&&lanes.some(([k])=>k===requested))lane=requested;drawTabs();await load();
 ['creator_page_settings','creator_available_balances','creator_alert_subscriptions','creator_dimension_access'].forEach(table=>channels.push(supabase.channel(`creator:${table}:${user.id}`).on('postgres_changes',{event:'*',schema:'public',table},()=>{clearTimeout(refreshTimer);refreshTimer=window.setTimeout(()=>void load(),180);}).subscribe()));
 const cleanup=()=>{if(destroyed)return;destroyed=true;clearTimeout(refreshTimer);channels.forEach(c=>void supabase.removeChannel(c));delete root.dataset.creatorOwner;};window.addEventListener('pagehide',cleanup,{once:true});window.addEventListener('beforeunload',cleanup,{once:true});
}
