import { supabase } from '../../core/supabase/client';
import '../../styles/deep-sections.css';

const esc=(v:string|null|undefined)=>(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c));
const money=(v:number|null|undefined)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format((v??0)/100);

export async function mount():Promise<void>{
 const root=document.querySelector<HTMLElement>('#app');if(!root)throw new Error('Missing #app');
 const {data:{session}}=await supabase.auth.getSession();if(!session){location.replace('/tap-in.html?next=/creator.html');return;}
 root.innerHTML=`<main class="deep-shell"><div class="deep-wrap"><header class="deep-top"><a href="/portal.html">←</a><div><p>RICH BIZNESS CREATOR COMMAND</p><h1>Creator Hub</h1></div><span class="deep-live">MONETIZATION</span></header><section id="hero" class="deep-hero"><div><small>BUILD • PUBLISH • EARN • CONTROL</small><h2 id="creatorTitle">YOUR CREATOR UNIVERSE</h2><p id="creatorTagline">Connect every section of your brand from one command center.</p><div class="deep-actions"><a class="deep-btn primary" href="/upload.html">CREATE DROP</a><a class="deep-btn" href="/live.html">GO LIVE</a><a class="deep-btn" href="/store.html">MANAGE STORE</a></div></div></section><section id="stats" class="deep-stats"></section><nav id="tabs" class="deep-tabs"></nav><section id="content"></section><p id="status" class="deep-status"></p></div></main>`;
 const hero=document.querySelector<HTMLElement>('#hero')!,stats=document.querySelector<HTMLElement>('#stats')!,tabs=document.querySelector<HTMLElement>('#tabs')!,content=document.querySelector<HTMLElement>('#content')!,status=document.querySelector<HTMLElement>('#status')!;
 let lane='dashboard',settings:any=null,profile:any=null,balance:any=null,tracks:any[]=[],products:any[]=[],streams:any[]=[],worlds:any[]=[],games:any[]=[],posts:any[]=[];
 const setStatus=(v:string)=>{status.textContent=v;setTimeout(()=>{if(status.textContent===v)status.textContent=''},2600)};
 const lanes=[['dashboard','DASHBOARD'],['page','CREATOR PAGE'],['content','CONTENT'],['earnings','EARNINGS'],['alerts','ALERTS']];
 const renderTabs=()=>{tabs.innerHTML=lanes.map(([k,l])=>`<button class="deep-tab ${lane===k?'active':''}" data-lane="${k}">${l}</button>`).join('');tabs.querySelectorAll<HTMLButtonElement>('[data-lane]').forEach(b=>b.onclick=()=>{lane=b.dataset.lane!;renderTabs();render();});};
 const card=(title:string,sub:string,url:string,img?:string|null)=>`<article class="deep-card"><div class="deep-card-media wide">${img?`<img src="${esc(img)}" alt="">`:''}<span>CREATOR</span></div><div class="deep-card-body"><h3>${esc(title)}</h3><p>${esc(sub)}</p><div class="deep-card-actions"><a href="${esc(url)}">OPEN</a></div></div></article>`;
 const render=()=>{hero.style.setProperty('--hero-image',settings?.hero_background_url?`url('${settings.hero_background_url}')`:`url('${profile?.banner_url||'/images/brand/IMG_5997.png'}')`);document.querySelector('#creatorTitle')!.textContent=settings?.creator_title||profile?.display_name||'YOUR CREATOR UNIVERSE';document.querySelector('#creatorTagline')!.textContent=settings?.creator_tagline||profile?.bio||'Connect every section of your brand from one command center.';stats.innerHTML=`<article><small>AVAILABLE</small><strong>${money(balance?.available_cents)}</strong></article><article><small>PENDING</small><strong>${money(balance?.pending_cents)}</strong></article><article><small>TOTAL DROPS</small><strong>${posts.length+tracks.length+products.length}</strong></article><article><small>RICH POINTS</small><strong>${Number(profile?.rich_points??0).toLocaleString()}</strong></article>`;
 if(lane==='dashboard')content.innerHTML=`<section class="deep-section"><header><div><small>CONNECTED CHANNELS</small><h2>Your active business lanes</h2></div></header><div class="deep-grid">${card('Creator Profile',profile?.rank_title||'Rich Creator','/profile.html',profile?.avatar_url)}${card('Music Catalog',`${tracks.length} tracks published`,'/music.html',tracks[0]?.cover_url)}${card('Storefront',`${products.length} products active`,'/store.html',products[0]?.image_url||products[0]?.cover_url)}${card('Live Network',`${streams.length} streams created`,'/live.html',streams[0]?.thumbnail_url||streams[0]?.cover_url)}${card('Meta Worlds',`${worlds.length} connected worlds`,'/meta.html',worlds[0]?.cover_url||worlds[0]?.background_url)}${card('Gaming',`${games.length} featured games`,'/gaming.html',games[0]?.cover_url||games[0]?.thumbnail_url)}</div></section>`;
 else if(lane==='page')content.innerHTML=`<form id="creatorForm" class="deep-form"><div class="deep-form-row"><input id="creatorTitleInput" maxlength="100" placeholder="Creator title" value="${esc(settings?.creator_title||'')}"><input id="creatorTaglineInput" maxlength="180" placeholder="Creator tagline" value="${esc(settings?.creator_tagline||'')}"></div><div class="deep-form-row"><input id="heroBackground" placeholder="Hero background URL" value="${esc(settings?.hero_background_url||'')}"><input id="heroVideo" placeholder="Hero video URL" value="${esc(settings?.hero_video_url||'')}"></div><div class="deep-form-row"><select id="pageTheme"><option value="smoke-cloud">SMOKE CLOUD</option><option value="cinematic">CINEMATIC</option><option value="neon">NEON</option></select><select id="introStyle"><option value="cinematic">CINEMATIC</option><option value="clean">CLEAN</option><option value="portal">PORTAL</option></select></div><div class="deep-form-row"><label><input id="showMusic" type="checkbox" ${settings?.show_music!==false?'checked':''}> SHOW MUSIC</label><label><input id="showStore" type="checkbox" ${settings?.show_store!==false?'checked':''}> SHOW STORE</label></div><div class="deep-form-row"><label><input id="showLive" type="checkbox" ${settings?.show_live!==false?'checked':''}> SHOW LIVE</label><label><input id="showMeta" type="checkbox" ${settings?.show_meta!==false?'checked':''}> SHOW META</label></div><button class="deep-btn primary">SAVE CREATOR PAGE</button></form>`;
 else if(lane==='content')content.innerHTML=`<section class="deep-grid">${[...posts.map(p=>card(p.title||p.body||'Feed Drop',p.section||'feed',`/feed.html?post=${p.id}`,p.thumbnail_url||p.cover_url||p.media_url)),...tracks.map(t=>card(t.title,t.genre||'music',`/music.html?track=${t.id}`,t.cover_url)),...products.map(p=>card(p.title,money(p.price_cents),`/store.html?product=${p.id}`,p.image_url||p.cover_url))].join('')||'<div class="deep-empty">Your creator content will appear here.</div>'}</section>`;
 else if(lane==='earnings')content.innerHTML=`<section class="deep-section"><header><div><small>CREATOR WALLET</small><h2>Revenue position</h2></div></header><div class="deep-stats"><article><small>EARNED</small><strong>${money(balance?.earned_cents)}</strong></article><article><small>AVAILABLE</small><strong>${money(balance?.available_cents)}</strong></article><article><small>PENDING</small><strong>${money(balance?.pending_cents)}</strong></article><article><small>PAID OUT</small><strong>${money(balance?.paid_out_cents)}</strong></article></div><div class="deep-actions"><a class="deep-btn primary" href="/settings.html">PAYOUT SETTINGS</a><a class="deep-btn" href="/store.html">ORDER CENTER</a></div></section>`;
 else content.innerHTML=`<section class="deep-section"><header><div><small>CREATOR ALERTS</small><h2>Audience subscriptions</h2></div></header><div id="alertList" class="deep-list"><article><div><h3>Creator alert controls</h3><p>Followers can subscribe to posts, live, store, and music activity.</p></div><a class="deep-btn" href="/notifications.html">OPEN ALERTS</a></article></div></section>`;
 if(lane==='page'){const form=document.querySelector<HTMLFormElement>('#creatorForm');form!.onsubmit=async e=>{e.preventDefault();const payload={user_id:session.user.id,creator_title:(document.querySelector<HTMLInputElement>('#creatorTitleInput')!).value.trim(),creator_tagline:(document.querySelector<HTMLInputElement>('#creatorTaglineInput')!).value.trim(),hero_background_url:(document.querySelector<HTMLInputElement>('#heroBackground')!).value.trim()||null,hero_video_url:(document.querySelector<HTMLInputElement>('#heroVideo')!).value.trim()||null,page_theme:(document.querySelector<HTMLSelectElement>('#pageTheme')!).value,intro_style:(document.querySelector<HTMLSelectElement>('#introStyle')!).value,show_music:(document.querySelector<HTMLInputElement>('#showMusic')!).checked,show_store:(document.querySelector<HTMLInputElement>('#showStore')!).checked,show_live:(document.querySelector<HTMLInputElement>('#showLive')!).checked,show_meta:(document.querySelector<HTMLInputElement>('#showMeta')!).checked,updated_at:new Date().toISOString()};const {error}=await supabase.from('creator_page_settings').upsert(payload,{onConflict:'user_id'});if(error)setStatus(error.message);else{await supabase.from('profiles').update({is_creator:true,updated_at:new Date().toISOString()}).eq('id',session.user.id);await supabase.rpc('rb_award_xp',{p_event_key:'creator_publish',p_section:'creator'});setStatus('CREATOR UNIVERSE SAVED — XP SYNCED');await load();}};}};
 const load=async()=>{const id=session.user.id;const [a,b,c,d,e,f,g,h]=await Promise.all([supabase.from('profiles').select('*').eq('id',id).single(),supabase.from('creator_page_settings').select('*').eq('user_id',id).maybeSingle(),supabase.from('creator_available_balances').select('*').eq('artist_user_id',id).maybeSingle(),supabase.from('music_tracks').select('*').eq('user_id',id).order('created_at',{ascending:false}).limit(20),supabase.from('products').select('*').eq('seller_id',id).order('created_at',{ascending:false}).limit(20),supabase.from('live_streams').select('*').eq('creator_id',id).order('created_at',{ascending:false}).limit(20),supabase.from('meta_worlds').select('*').eq('owner_id',id).order('created_at',{ascending:false}).limit(20),supabase.from('feed_posts').select('*').eq('user_id',id).order('created_at',{ascending:false}).limit(20)]);profile=a.data;settings=b.data;balance=c.data;tracks=d.data??[];products=e.data??[];streams=f.data??[];worlds=g.data??[];posts=h.data??[];const gameIds=settings?.featured_game_id?[settings.featured_game_id]:[];games=gameIds.length?(await supabase.from('games').select('*').in('id',gameIds)).data??[]:[];render();};
 renderTabs();await load();
}
