import { supabase } from '../../core/supabase/client';
import './messages.css';

type ThreadRow = { id:string; title:string|null; thread_type:string|null; last_message:string|null; last_message_at:string|null; dm_brand:string|null; typing_label:string|null };
type MessageRow = { id:string; sender_id:string; display_name:string|null; username:string|null; body:string|null; created_at:string|null };
const esc=(v:string|null|undefined)=>(v??'').replace(/[&<>'"]/g,c=>({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' })[c]??c);

export async function mount(): Promise<void> {
  const app=document.querySelector<HTMLElement>('#app'); if(!app) throw new Error('Missing #app mount');
  const {data:{session}}=await supabase.auth.getSession(); if(!session){location.replace(`/tap-in.html?next=${encodeURIComponent('/messages.html')}`);return;}
  app.innerHTML=`<main class="dm-shell"><header><a href="/">← PORTAL</a><div><p>RICH-DM'S</p><h1>Messages</h1></div></header><section class="dm-layout"><aside><div id="threadList" class="thread-list"></div></aside><section class="conversation"><header id="conversationHeader">SELECT A CONVERSATION</header><div id="messageList" class="message-list"></div><form id="messageForm"><input id="messageInput" maxlength="2000" placeholder="Type a message…" autocomplete="off"/><button type="submit">SEND</button></form></section></section></main>`;
  const threadList=document.querySelector<HTMLElement>('#threadList')!; const messageList=document.querySelector<HTMLElement>('#messageList')!; const form=document.querySelector<HTMLFormElement>('#messageForm')!; const input=document.querySelector<HTMLInputElement>('#messageInput')!; const header=document.querySelector<HTMLElement>('#conversationHeader')!;
  let activeThread:string|null=null; let messageChannel:ReturnType<typeof supabase.channel>|null=null;

  const loadThreads=async()=>{ const {data,error}=await supabase.from('dm_thread_members').select('thread_id,dm_threads!inner(id,title,thread_type,last_message,last_message_at,dm_brand,typing_label)').eq('user_id',session.user.id).eq('status','active'); if(error) throw error; const rows=(data??[]).map((r:any)=>r.dm_threads as ThreadRow).sort((a,b)=>new Date(b.last_message_at??0).getTime()-new Date(a.last_message_at??0).getTime()); threadList.innerHTML=rows.length?rows.map(t=>`<button class="thread-card${activeThread===t.id?' active':''}" data-thread="${t.id}"><strong>${esc(t.title??t.dm_brand??"Rich-DM's")}</strong><span>${esc(t.last_message??'No messages yet')}</span><time>${t.last_message_at?new Date(t.last_message_at).toLocaleString():''}</time></button>`).join(''):'<p class="dm-empty">No conversations yet.</p>'; };
  const loadMessages=async(threadId:string)=>{ const {data,error}=await supabase.from('dm_messages').select('id,sender_id,display_name,username,body,created_at').eq('thread_id',threadId).eq('is_deleted',false).order('created_at',{ascending:true}).limit(200); if(error) throw error; const rows=(data??[]) as MessageRow[]; messageList.innerHTML=rows.length?rows.map(m=>`<article class="bubble${m.sender_id===session.user.id?' mine':''}"><strong>${esc(m.display_name??m.username??'Member')}</strong><p>${esc(m.body)}</p><time>${m.created_at?new Date(m.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):''}</time></article>`).join(''):'<p class="dm-empty">Start the conversation.</p>'; messageList.scrollTop=messageList.scrollHeight; };
  const selectThread=async(threadId:string,title:string)=>{activeThread=threadId;header.textContent=title;await loadThreads();await loadMessages(threadId);if(messageChannel) await supabase.removeChannel(messageChannel);messageChannel=supabase.channel(`dm:${threadId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'dm_messages',filter:`thread_id=eq.${threadId}`},()=>loadMessages(threadId)).subscribe();};
  threadList.addEventListener('click',event=>{const button=(event.target as HTMLElement).closest<HTMLButtonElement>('[data-thread]');if(button) void selectThread(button.dataset.thread!,button.querySelector('strong')?.textContent??"Rich-DM's");});
  form.addEventListener('submit',async event=>{event.preventDefault();const body=input.value.trim();if(!activeThread||!body)return;input.disabled=true;const {data:profile}=await supabase.from('profiles').select('username,display_name').eq('id',session.user.id).single();const {error}=await supabase.from('dm_messages').insert({thread_id:activeThread,sender_id:session.user.id,username:profile?.username??null,display_name:profile?.display_name??null,body,message_type:'text'});if(!error){input.value='';await supabase.from('dm_threads').update({last_message:body,last_message_at:new Date().toISOString(),last_message_user_id:session.user.id}).eq('id',activeThread);await loadThreads();}input.disabled=false;input.focus();});
  await loadThreads(); window.addEventListener('pagehide',()=>{if(messageChannel)void supabase.removeChannel(messageChannel);},{once:true});
}
