import { supabase } from '../../core/supabase/client';
import './avatar.css';

type Preset={preset_key:string;title:string;aura:string;outfit:string;motion:string;config:Record<string,string>};
type Item={item_key:string;item_type:string;title:string;rarity:string};
type AvatarRow={display_name?:string|null;avatar_url?:string|null;aura?:string|null;level?:number|null;xp?:number|null;rank?:string|null;metadata?:Record<string,unknown>|null};
const esc=(v:string|null|undefined)=>(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]??c));
const auraMap:Record<string,string>={'Emerald Gold':'radial-gradient(circle,rgba(49,255,99,.95),rgba(247,201,72,.4),transparent 66%)','Diamond Mist':'radial-gradient(circle,rgba(197,233,255,.95),rgba(181,116,255,.35),transparent 66%)','Neon Phantom':'radial-gradient(circle,rgba(86,255,222,.9),rgba(119,64,255,.42),transparent 66%)','green-gold':'radial-gradient(circle,rgba(49,255,99,.95),rgba(247,201,72,.4),transparent 66%)'};

export async function mount():Promise<void>{
  const root=document.querySelector<HTMLElement>('#app');if(!root)throw new Error('Missing #app mount');
  const {data:{session}}=await supabase.auth.getSession();if(!session){location.replace('/tap-in.html?next=%2Favatar.html');return;}
  const [{data:profile},{data:avatar},{data:presets},{data:items}]=await Promise.all([
    supabase.from('profiles').select('display_name,username,avatar_url,rich_level,rank_title').eq('id',session.user.id).maybeSingle(),
    supabase.from('meta_avatars').select('display_name,avatar_url,aura,level,xp,rank,metadata').eq('user_id',session.user.id).maybeSingle(),
    supabase.from('avatar_character_presets').select('preset_key,title,aura,outfit,motion,config').eq('is_active',true).order('title'),
    supabase.from('avatar_items').select('item_key,item_type,title,rarity').eq('is_active',true).order('item_type').order('title')
  ]);
  const presetRows=(presets??[]) as Preset[];const itemRows=(items??[]) as Item[];const current=(avatar??{}) as AvatarRow;
  let selectedPreset=presetRows.find(p=>p.preset_key===String((current.metadata as any)?.preset_key??''))??presetRows[0];
  let selectedAura=current.aura||selectedPreset?.aura||'Emerald Gold';
  let selectedMotion=selectedPreset?.motion||'Boss Walk';
  const equipped:Record<string,string>={...(selectedPreset?.config??{}),...(((current.metadata as any)?.accessories??{}) as Record<string,string>)};
  const avatarImage=current.avatar_url||profile?.avatar_url||'/images/brand/Avatar-hero-Banner.png.jpeg';
  root.innerHTML=`<main class="avatar-shell"><div class="avatar-wrap"><header class="avatar-head"><a href="/portal.html">←</a><div><p>RICH BIZNESS IDENTITY ENGINE</p><h1>Avatar Studio</h1></div><span class="avatar-sync">REALTIME READY</span></header><div class="avatar-layout"><section class="avatar-stage"><div class="avatar-stars"></div><div class="avatar-smoke"></div><div id="auraGlow" class="avatar-aura"></div><div class="avatar-ring"></div><div id="avatarFigure" class="avatar-figure" data-motion="walk"><img src="${esc(avatarImage)}" alt="Your Rich Bizness avatar"></div><div class="avatar-stage-copy"><div><h2 id="stageName">${esc(current.display_name||profile?.display_name||profile?.username||'Rich Avatar')}</h2><p id="stagePreset">${esc(selectedPreset?.title||'Boss Walk')} · ${esc(selectedAura)}</p></div><span class="avatar-badge">CONTROLLABLE 3D IDENTITY</span></div></section><aside class="avatar-controls"><section class="avatar-panel"><h3>IDENTITY</h3><div class="avatar-panel-body"><div class="avatar-field"><label>DISPLAY NAME</label><input id="displayName" maxlength="80" value="${esc(current.display_name||profile?.display_name||profile?.username||'')}"></div><div class="avatar-stats"><div class="avatar-stat"><strong>${current.level??profile?.rich_level??1}</strong><span>LEVEL</span></div><div class="avatar-stat"><strong>${current.xp??0}</strong><span>XP</span></div><div class="avatar-stat"><strong>${esc(current.rank||profile?.rank_title||'Traveler')}</strong><span>RANK</span></div></div></div></section><section class="avatar-panel"><h3>CHARACTER PRESETS</h3><div id="presetOptions" class="avatar-panel-body avatar-options"></div></section><section class="avatar-panel"><h3>AURA + MOTION</h3><div class="avatar-panel-body"><div class="avatar-field"><label>AURA</label><select id="auraSelect"><option>Emerald Gold</option><option>Diamond Mist</option><option>Neon Phantom</option></select></div><div class="avatar-field"><label>MOTION</label><select id="motionSelect"><option>Boss Walk</option><option>Power Up</option><option>Dance Flex</option><option>Idle Street Pose</option></select></div><button id="smokeBurst" class="avatar-btn">TRIGGER SMOKE BURST</button></div></section><section class="avatar-panel"><h3>GEAR LOADOUT</h3><div id="gearOptions" class="avatar-panel-body avatar-options"></div></section><div class="avatar-actions"><button id="previewBtn" class="avatar-btn">PREVIEW MOTION</button><button id="saveBtn" class="avatar-btn primary">SAVE AVATAR</button></div><p id="status" class="avatar-status"></p></aside></div></div></main>`;
  const figure=document.querySelector<HTMLElement>('#avatarFigure')!;const glow=document.querySelector<HTMLElement>('#auraGlow')!;const stagePreset=document.querySelector<HTMLElement>('#stagePreset')!;const stageName=document.querySelector<HTMLElement>('#stageName')!;const status=document.querySelector<HTMLElement>('#status')!;const auraSelect=document.querySelector<HTMLSelectElement>('#auraSelect')!;const motionSelect=document.querySelector<HTMLSelectElement>('#motionSelect')!;const presetOptions=document.querySelector<HTMLElement>('#presetOptions')!;const gearOptions=document.querySelector<HTMLElement>('#gearOptions')!;
  auraSelect.value=[...auraSelect.options].some(o=>o.value===selectedAura)?selectedAura:'Emerald Gold';motionSelect.value=[...motionSelect.options].some(o=>o.value===selectedMotion)?selectedMotion:'Boss Walk';
  const motionKey=(v:string)=>v.includes('Power')?'power':v.includes('Dance')?'dance':v.includes('Idle')?'idle':'walk';
  const refresh=()=>{glow.style.background=auraMap[selectedAura]??auraMap['Emerald Gold'];figure.dataset.motion=motionKey(selectedMotion);stagePreset.textContent=`${selectedPreset?.title||'Custom'} · ${selectedAura}`;stageName.textContent=(document.querySelector<HTMLInputElement>('#displayName')!.value.trim()||'Rich Avatar');};
  const renderPresets=()=>{presetOptions.innerHTML=presetRows.map(p=>`<button class="avatar-option ${p.preset_key===selectedPreset?.preset_key?'active':''}" data-preset="${esc(p.preset_key)}">${esc(p.title)}<small>${esc(p.outfit)} · ${esc(p.motion)}</small></button>`).join('')||'<div>No presets loaded.</div>';presetOptions.querySelectorAll<HTMLButtonElement>('[data-preset]').forEach(btn=>btn.onclick=()=>{selectedPreset=presetRows.find(p=>p.preset_key===btn.dataset.preset)!;selectedAura=selectedPreset.aura;selectedMotion=selectedPreset.motion;Object.assign(equipped,selectedPreset.config??{});auraSelect.value=selectedAura;motionSelect.value=selectedMotion;renderPresets();renderGear();refresh();});};
  const renderGear=()=>{gearOptions.innerHTML=itemRows.map(i=>`<button class="avatar-option ${Object.values(equipped).includes(i.title)?'active':''}" data-item="${esc(i.item_key)}">${esc(i.title)}<small>${esc(i.item_type)} · ${esc(i.rarity)}</small></button>`).join('')||'<div>No gear loaded.</div>';gearOptions.querySelectorAll<HTMLButtonElement>('[data-item]').forEach(btn=>btn.onclick=()=>{const item=itemRows.find(i=>i.item_key===btn.dataset.item);if(!item)return;if(equipped[item.item_type]===item.title)delete equipped[item.item_type];else equipped[item.item_type]=item.title;renderGear();});};
  auraSelect.onchange=()=>{selectedAura=auraSelect.value;refresh();};motionSelect.onchange=()=>{selectedMotion=motionSelect.value;refresh();};document.querySelector<HTMLInputElement>('#displayName')!.oninput=refresh;
  document.querySelector<HTMLButtonElement>('#previewBtn')!.onclick=()=>{figure.dataset.motion='power';window.setTimeout(()=>figure.dataset.motion=motionKey(selectedMotion),900);};
  document.querySelector<HTMLButtonElement>('#smokeBurst')!.onclick=()=>{const smoke=document.querySelector<HTMLElement>('.avatar-smoke')!;smoke.animate([{transform:'scale(.8)',opacity:.25},{transform:'scale(1.35) translateY(-28px)',opacity:1},{transform:'scale(1)',opacity:.6}],{duration:1100,easing:'ease-out'});};
  document.querySelector<HTMLButtonElement>('#saveBtn')!.onclick=async()=>{status.textContent='Saving full identity loadout…';const displayName=document.querySelector<HTMLInputElement>('#displayName')!.value.trim();const outfit={preset:selectedPreset?.outfit??'Rich Default',motion:selectedMotion};const accessories={...equipped};const smoke={mode:selectedPreset?.config?.smoke??'cinematic',intensity:selectedPreset?.preset_key==='boss'?'heavy':'medium'};const emotes={idle:selectedMotion,smoke_burst:true,power_up:true};const {error}=await supabase.rpc('rb_save_avatar_studio',{p_display_name:displayName,p_preset_key:selectedPreset?.preset_key??'boss',p_aura:selectedAura,p_outfit:outfit,p_accessories:accessories,p_smoke:smoke,p_emotes:emotes,p_character_type:selectedPreset?.preset_key??'custom'});if(error){status.textContent=error.message;return;}status.textContent='Avatar loadout saved and synced.';document.querySelector<HTMLButtonElement>('#saveBtn')!.textContent='SAVED ✓';};
  renderPresets();renderGear();refresh();
}
