import * as THREE from 'three';
import { supabase } from '../../core/supabase/client';
import './avatar.css';

type Preset={preset_key:string;title:string;aura:string;outfit:string;motion:string;config:Record<string,string>};
type Item={item_key:string;item_type:string;title:string;rarity:string};
type AvatarRow={display_name?:string|null;aura?:string|null;level?:number|null;xp?:number|null;rank?:string|null;position?:Record<string,number>|null;metadata?:Record<string,unknown>|null};
const esc=(v:string|null|undefined)=>(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]??c));
const palettes:Record<string,{primary:number;secondary:number;smoke:number}>={
  'Emerald Gold':{primary:0x31ff63,secondary:0xf7c948,smoke:0x8dffad},
  'Diamond Mist':{primary:0xc5e9ff,secondary:0xb574ff,smoke:0xe2f7ff},
  'Neon Phantom':{primary:0x56ffde,secondary:0x7740ff,smoke:0x9f8cff}
};

export async function mount():Promise<void>{
  const root=document.querySelector<HTMLElement>('#app');if(!root)throw new Error('Missing #app mount');
  const {data:{session}}=await supabase.auth.getSession();if(!session){location.replace('/tap-in.html?next=%2Favatar.html');return;}
  const [{data:profile},{data:avatar},{data:presets},{data:items},{data:clips}]=await Promise.all([
    supabase.from('profiles').select('display_name,username,rich_level,rank_title').eq('id',session.user.id).maybeSingle(),
    supabase.from('meta_avatars').select('display_name,aura,level,xp,rank,position,metadata').eq('user_id',session.user.id).maybeSingle(),
    supabase.from('avatar_character_presets').select('preset_key,title,aura,outfit,motion,config').eq('is_active',true).order('title'),
    supabase.from('avatar_items').select('item_key,item_type,title,rarity').eq('is_active',true).order('item_type').order('title'),
    supabase.from('avatar_animation_clips').select('clip_key,title,state_group').eq('is_active',true).order('state_group')
  ]);
  const presetRows=(presets??[]) as Preset[];const itemRows=(items??[]) as Item[];const current=(avatar??{}) as AvatarRow;
  let selectedPreset=presetRows.find(p=>p.preset_key===String((current.metadata as any)?.preset_key??''))??presetRows[0];
  let selectedAura=current.aura||selectedPreset?.aura||'Emerald Gold';let selectedMotion=selectedPreset?.motion||'Boss Walk';
  const equipped:Record<string,string>={...(selectedPreset?.config??{}),...(((current.metadata as any)?.accessories??{}) as Record<string,string>)};
  root.innerHTML=`<main class="avatar-shell"><header class="avatar-top"><a href="/portal.html">←</a><div><p>RICH BIZNESS IDENTITY ENGINE</p><h1>Avatar Lab</h1></div><div class="avatar-live"><i></i>LIVE 3D</div></header><section class="avatar-workspace"><div class="avatar-stage"><canvas id="avatarCanvas"></canvas><div class="avatar-hud"><div><span id="motionState">IDLE</span><b id="stageName">${esc(current.display_name||profile?.display_name||profile?.username||'Rich Avatar')}</b><small id="stagePreset">${esc(selectedPreset?.title||'Boss Walk')} · ${esc(selectedAura)}</small></div><div class="avatar-meter"><span>LEVEL ${current.level??profile?.rich_level??1}</span><span>${current.xp??0} XP</span><span>${esc(current.rank||profile?.rank_title||'Traveler')}</span></div></div><div class="avatar-mobile-controls"><div id="joystick" class="avatar-joystick"><i></i></div><div><button data-action="jump">JUMP</button><button data-action="sprint">RUN</button><button data-action="power">POWER</button></div></div></div><aside class="avatar-console"><section><h3>IDENTITY</h3><label>DISPLAY NAME<input id="displayName" maxlength="80" value="${esc(current.display_name||profile?.display_name||profile?.username||'')}"></label></section><section><h3>CHARACTER PRESETS</h3><div id="presetOptions" class="avatar-grid"></div></section><section><h3>AURA + ANIMATION</h3><label>AURA<select id="auraSelect"><option>Emerald Gold</option><option>Diamond Mist</option><option>Neon Phantom</option></select></label><label>MOTION<select id="motionSelect">${(clips??[]).map((c:any)=>`<option value="${esc(c.title)}">${esc(c.title)}</option>`).join('')}</select></label><div class="avatar-command-row"><button data-emote="power">POWER UP</button><button data-emote="dance">DANCE FLEX</button><button data-emote="smoke">SMOKE BURST</button></div></section><section><h3>GEAR LOADOUT</h3><div id="gearOptions" class="avatar-grid"></div></section><div class="avatar-save-row"><button id="resetBtn">RESET VIEW</button><button id="saveBtn" class="primary">SAVE FULL IDENTITY</button></div><p id="status"></p></aside></section></main>`;

  const canvas=document.querySelector<HTMLCanvasElement>('#avatarCanvas')!;const stage=canvas.parentElement!;const status=document.querySelector<HTMLElement>('#status')!;const stateLabel=document.querySelector<HTMLElement>('#motionState')!;
  const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;
  const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x020402,.055);const camera=new THREE.PerspectiveCamera(45,1,.1,100);camera.position.set(0,2.6,7.8);
  const world=new THREE.Group();scene.add(world);const avatarRoot=new THREE.Group();avatarRoot.position.set((current.position?.x??0),0,(current.position?.z??0));world.add(avatarRoot);
  scene.add(new THREE.HemisphereLight(0xdfffe6,0x071008,2.3));const keyLight=new THREE.DirectionalLight(0xffffff,3.8);keyLight.position.set(3,7,4);keyLight.castShadow=true;scene.add(keyLight);const rim=new THREE.PointLight(0x31ff63,28,14);rim.position.set(-3,3,-2);scene.add(rim);const gold=new THREE.PointLight(0xf7c948,20,12);gold.position.set(3,2,2);scene.add(gold);
  const floor=new THREE.Mesh(new THREE.CylinderGeometry(4.6,5.3,.35,96),new THREE.MeshStandardMaterial({color:0x071108,metalness:.72,roughness:.28}));floor.position.y=-.22;floor.receiveShadow=true;world.add(floor);const ring=new THREE.Mesh(new THREE.TorusGeometry(3.65,.035,12,100),new THREE.MeshBasicMaterial({color:0x31ff63}));ring.rotation.x=Math.PI/2;ring.position.y=.01;world.add(ring);
  for(let i=0;i<75;i++){const star=new THREE.Mesh(new THREE.SphereGeometry(.009,5,5),new THREE.MeshBasicMaterial({color:i%4?0xffffff:0xf7c948}));star.position.set((Math.random()-.5)*22,Math.random()*10+1,(Math.random()-.5)*18-2);scene.add(star);}
  const bodyMat=new THREE.MeshStandardMaterial({color:0x171b18,metalness:.22,roughness:.48});const accentMat=new THREE.MeshStandardMaterial({color:0xf7c948,metalness:.82,roughness:.18});const skinMat=new THREE.MeshStandardMaterial({color:0x6f3e27,roughness:.72});const glassMat=new THREE.MeshStandardMaterial({color:0x050505,metalness:.85,roughness:.12});
  const torso=new THREE.Mesh(new THREE.CapsuleGeometry(.72,1.25,8,18),bodyMat);torso.position.y=2.55;torso.scale.set(1.05,1,.72);torso.castShadow=true;avatarRoot.add(torso);const head=new THREE.Mesh(new THREE.SphereGeometry(.48,32,24),skinMat);head.position.y=4.05;head.scale.set(.92,1.08,.92);head.castShadow=true;avatarRoot.add(head);const beanie=new THREE.Mesh(new THREE.SphereGeometry(.5,32,16,0,Math.PI*2,0,Math.PI*.52),bodyMat);beanie.position.y=4.24;avatarRoot.add(beanie);const shades=new THREE.Mesh(new THREE.BoxGeometry(.82,.16,.12),glassMat);shades.position.set(0,4.08,.43);avatarRoot.add(shades);
  const limbs:{leftArm:THREE.Group;rightArm:THREE.Group;leftLeg:THREE.Group;rightLeg:THREE.Group}={} as any;
  const limb=(x:number,y:number,len:number,r:number,mat:THREE.Material)=>{const pivot=new THREE.Group();pivot.position.set(x,y,0);const mesh=new THREE.Mesh(new THREE.CapsuleGeometry(r,len,6,14),mat);mesh.position.y=-len/2;mesh.castShadow=true;pivot.add(mesh);avatarRoot.add(pivot);return pivot;};
  limbs.leftArm=limb(-.82,3.05,1.45,.18,bodyMat);limbs.rightArm=limb(.82,3.05,1.45,.18,bodyMat);limbs.leftLeg=limb(-.37,1.95,1.85,.24,bodyMat);limbs.rightLeg=limb(.37,1.95,1.85,.24,bodyMat);
  const chain=new THREE.Mesh(new THREE.TorusGeometry(.35,.035,10,50),accentMat);chain.position.set(0,3.3,.62);chain.rotation.x=Math.PI/2;avatarRoot.add(chain);const pendant=new THREE.Mesh(new THREE.BoxGeometry(.2,.28,.07),accentMat);pendant.position.set(0,3.02,.67);avatarRoot.add(pendant);
  const aura=new THREE.Mesh(new THREE.SphereGeometry(1.85,36,26),new THREE.MeshBasicMaterial({color:0x31ff63,transparent:true,opacity:.06,side:THREE.BackSide,blending:THREE.AdditiveBlending,depthWrite:false}));aura.position.y=2.15;avatarRoot.add(aura);
  const smokeGroup=new THREE.Group();avatarRoot.add(smokeGroup);for(let i=0;i<24;i++){const puff=new THREE.Mesh(new THREE.SphereGeometry(.12+Math.random()*.16,12,10),new THREE.MeshBasicMaterial({color:0x8dffad,transparent:true,opacity:.12,depthWrite:false}));puff.userData={baseY:Math.random()*2.6,t:Math.random()*8,speed:.25+Math.random()*.35};smokeGroup.add(puff);}
  let locomotion='idle',action='none',sequence=0,dragging=false,lastX=0,lastY=0,yaw=0,pitch=.08,zoom=7.8;const keys=new Set<string>();const velocity=new THREE.Vector3();const clock=new THREE.Clock();let jumpVelocity=0,grounded=true,emoteUntil=0;
  const applyPalette=()=>{const p=palettes[selectedAura]??palettes['Emerald Gold'];(aura.material as THREE.MeshBasicMaterial).color.setHex(p.primary);ring.material=(ring.material as THREE.MeshBasicMaterial).clone();(ring.material as THREE.MeshBasicMaterial).color.setHex(p.primary);rim.color.setHex(p.primary);gold.color.setHex(p.secondary);accentMat.color.setHex(p.secondary);smokeGroup.children.forEach(m=>(m as THREE.Mesh).material=(new THREE.MeshBasicMaterial({color:p.smoke,transparent:true,opacity:.12,depthWrite:false})));};
  const resize=()=>{const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();};new ResizeObserver(resize).observe(stage);resize();
  const syncMotion=async()=>{await supabase.rpc('rb_sync_avatar_motion',{p_position:{x:+avatarRoot.position.x.toFixed(3),y:+avatarRoot.position.y.toFixed(3),z:+avatarRoot.position.z.toFixed(3)},p_rotation:{x:0,y:+avatarRoot.rotation.y.toFixed(3),z:0,w:1},p_velocity:{x:+velocity.x.toFixed(3),y:+jumpVelocity.toFixed(3),z:+velocity.z.toFixed(3)},p_locomotion_state:locomotion,p_action_state:action,p_active_clip_key:locomotion==='run'?'boss-run':locomotion==='walk'?'boss-walk':action==='power'?'power-up':action==='dance'?'dance-flex':action==='smoke'?'smoke-burst':'boss-idle',p_input_state:{keys:[...keys]},p_sequence:++sequence});};
  const trigger=(next:string)=>{action=next;emoteUntil=performance.now()+1400;stateLabel.textContent=next.toUpperCase();if(next==='smoke')smokeGroup.children.forEach((m:any)=>{m.userData.t=Math.random();m.scale.setScalar(1.8);});};
  window.addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='Space'&&grounded){jumpVelocity=6.8;grounded=false;}if(e.code==='Digit1')trigger('power');if(e.code==='Digit2')trigger('dance');if(e.code==='Digit3')trigger('smoke');});window.addEventListener('keyup',e=>keys.delete(e.code));
  canvas.addEventListener('pointerdown',e=>{dragging=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!dragging)return;yaw-=(e.clientX-lastX)*.008;pitch=Math.max(-.1,Math.min(.42,pitch+(e.clientY-lastY)*.004));lastX=e.clientX;lastY=e.clientY;});canvas.addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('wheel',e=>{zoom=Math.max(4.8,Math.min(10.5,zoom+e.deltaY*.006));},{passive:true});
  document.querySelectorAll<HTMLButtonElement>('[data-emote]').forEach(b=>b.onclick=()=>trigger(b.dataset.emote!));document.querySelectorAll<HTMLButtonElement>('[data-action]').forEach(b=>{const a=b.dataset.action!;b.onpointerdown=()=>{if(a==='jump'&&grounded){jumpVelocity=6.8;grounded=false;}else if(a==='sprint')keys.add('ShiftLeft');else trigger(a)};b.onpointerup=()=>{if(a==='sprint')keys.delete('ShiftLeft')}});
  const joystick=document.querySelector<HTMLElement>('#joystick')!;const stick=joystick.querySelector<HTMLElement>('i')!;let touchMove={x:0,y:0};const moveStick=(e:PointerEvent)=>{const r=joystick.getBoundingClientRect();touchMove={x:Math.max(-1,Math.min(1,(e.clientX-(r.left+r.width/2))/(r.width*.34))),y:Math.max(-1,Math.min(1,(e.clientY-(r.top+r.height/2))/(r.height*.34)))};stick.style.transform=`translate(${touchMove.x*34}px,${touchMove.y*34}px)`;};joystick.onpointerdown=e=>{joystick.setPointerCapture(e.pointerId);moveStick(e)};joystick.onpointermove=e=>{if(joystick.hasPointerCapture(e.pointerId))moveStick(e)};joystick.onpointerup=()=>{touchMove={x:0,y:0};stick.style.transform='translate(0,0)'};
  const animate=()=>{requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.033),t=clock.elapsedTime;const inputX=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+touchMove.x;const inputZ=(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0)+touchMove.y;const moving=Math.abs(inputX)+Math.abs(inputZ)>.08;const sprint=keys.has('ShiftLeft');locomotion=!grounded?'jump':moving?(sprint?'run':'walk'):'idle';if(performance.now()>emoteUntil)action='none';stateLabel.textContent=(action!=='none'?action:locomotion).toUpperCase();const speed=sprint?5.2:2.8;const target=new THREE.Vector3(inputX,0,inputZ).normalize().multiplyScalar(moving?speed:0);velocity.lerp(target,1-Math.exp(-10*dt));avatarRoot.position.addScaledVector(velocity,dt);if(moving)avatarRoot.rotation.y=Math.atan2(velocity.x,velocity.z);if(!grounded){jumpVelocity-=18*dt;avatarRoot.position.y+=jumpVelocity*dt;if(avatarRoot.position.y<=0){avatarRoot.position.y=0;jumpVelocity=0;grounded=true;void syncMotion();}}
    const cycle=t*(locomotion==='run'?11:locomotion==='walk'?7:2);const swing=moving?Math.sin(cycle)*(locomotion==='run'?.75:.48):Math.sin(cycle)*.035;limbs.leftArm.rotation.x=swing;limbs.rightArm.rotation.x=-swing;limbs.leftLeg.rotation.x=-swing;limbs.rightLeg.rotation.x=swing;torso.rotation.z=action==='dance'?Math.sin(t*7)*.12:Math.sin(cycle)*.012;avatarRoot.scale.setScalar(action==='power'?1+Math.sin(t*14)*.035:1);aura.scale.setScalar(action==='power'?1.15+Math.sin(t*10)*.08:1+Math.sin(t*2)*.025);aura.material instanceof THREE.MeshBasicMaterial&&(aura.material.opacity=action==='power'?.18:.065);chain.rotation.z=Math.sin(t*3)*.08;
    smokeGroup.children.forEach((m:any,i)=>{m.userData.t+=dt*m.userData.speed;m.position.set(Math.sin(m.userData.t*1.8+i)*.75,m.userData.baseY+(m.userData.t%3),Math.cos(m.userData.t+i)*.55);const fade=1-(m.userData.t%3)/3;(m.material as THREE.MeshBasicMaterial).opacity=.04+fade*(action==='smoke'?.28:.1);m.scale.setScalar(.7+fade*.8)});camera.position.set(Math.sin(yaw)*Math.cos(pitch)*zoom,2.5+Math.sin(pitch)*zoom,Math.cos(yaw)*Math.cos(pitch)*zoom);camera.lookAt(avatarRoot.position.x,2.15+avatarRoot.position.y,avatarRoot.position.z);renderer.render(scene,camera);};animate();window.setInterval(()=>{if(moving||action!=='none')void syncMotion();},4000);
  const auraSelect=document.querySelector<HTMLSelectElement>('#auraSelect')!,motionSelect=document.querySelector<HTMLSelectElement>('#motionSelect')!,presetOptions=document.querySelector<HTMLElement>('#presetOptions')!,gearOptions=document.querySelector<HTMLElement>('#gearOptions')!;auraSelect.value=selectedAura;motionSelect.value=selectedMotion;
  const refreshCopy=()=>{document.querySelector('#stageName')!.textContent=(document.querySelector<HTMLInputElement>('#displayName')!.value.trim()||'Rich Avatar');document.querySelector('#stagePreset')!.textContent=`${selectedPreset?.title||'Custom'} · ${selectedAura}`;applyPalette();};
  const renderPresets=()=>{presetOptions.innerHTML=presetRows.map(p=>`<button class="${p.preset_key===selectedPreset?.preset_key?'active':''}" data-preset="${esc(p.preset_key)}"><b>${esc(p.title)}</b><small>${esc(p.outfit)} · ${esc(p.motion)}</small></button>`).join('');presetOptions.querySelectorAll<HTMLButtonElement>('[data-preset]').forEach(b=>b.onclick=()=>{selectedPreset=presetRows.find(p=>p.preset_key===b.dataset.preset)!;selectedAura=selectedPreset.aura;selectedMotion=selectedPreset.motion;Object.assign(equipped,selectedPreset.config);auraSelect.value=selectedAura;motionSelect.value=selectedMotion;renderPresets();renderGear();refreshCopy();trigger(selectedPreset.preset_key==='creator'?'dance':selectedPreset.preset_key==='meta'?'power':'smoke');});};
  const renderGear=()=>{gearOptions.innerHTML=itemRows.map(i=>`<button class="${Object.values(equipped).includes(i.title)?'active':''}" data-item="${esc(i.item_key)}"><b>${esc(i.title)}</b><small>${esc(i.item_type)} · ${esc(i.rarity)}</small></button>`).join('');gearOptions.querySelectorAll<HTMLButtonElement>('[data-item]').forEach(b=>b.onclick=()=>{const i=itemRows.find(x=>x.item_key===b.dataset.item);if(!i)return;if(equipped[i.item_type]===i.title)delete equipped[i.item_type];else equipped[i.item_type]=i.title;renderGear();});};
  auraSelect.onchange=()=>{selectedAura=auraSelect.value;refreshCopy()};motionSelect.onchange=()=>{selectedMotion=motionSelect.value;trigger(selectedMotion.toLowerCase().includes('dance')?'dance':selectedMotion.toLowerCase().includes('power')?'power':selectedMotion.toLowerCase().includes('smoke')?'smoke':'none')};document.querySelector<HTMLInputElement>('#displayName')!.oninput=refreshCopy;document.querySelector<HTMLButtonElement>('#resetBtn')!.onclick=()=>{yaw=0;pitch=.08;zoom=7.8;avatarRoot.position.set(0,0,0)};
  document.querySelector<HTMLButtonElement>('#saveBtn')!.onclick=async()=>{status.textContent='Saving 3D identity, loadout, and motion state…';const displayName=document.querySelector<HTMLInputElement>('#displayName')!.value.trim();const {error}=await supabase.rpc('rb_save_avatar_studio',{p_display_name:displayName,p_preset_key:selectedPreset?.preset_key??'boss',p_aura:selectedAura,p_outfit:{preset:selectedPreset?.outfit??'Rich Default',motion:selectedMotion},p_accessories:{...equipped},p_smoke:{mode:selectedPreset?.config?.smoke??'cinematic',intensity:'elite'},p_emotes:{idle:selectedMotion,smoke_burst:true,power_up:true,dance_flex:true},p_character_type:selectedPreset?.preset_key??'custom'});if(error){status.textContent=error.message;return;}await syncMotion();status.textContent='Elite 3D identity synced across the universe.';};
  renderPresets();renderGear();refreshCopy();
}
