import * as THREE from 'three';
export type HumanRig={root:THREE.Group;spine:THREE.Group;head:THREE.Group;leftArm:THREE.Group;rightArm:THREE.Group;leftLeg:THREE.Group;rightLeg:THREE.Group;leftKnee:THREE.Group;rightKnee:THREE.Group};
type Palette={primary:number;secondary:number;skin:number};
const material=(color:number,metalness=.1,roughness=.6)=>new THREE.MeshStandardMaterial({color,metalness,roughness});
const add=(parent:THREE.Object3D,geometry:THREE.BufferGeometry,mat:THREE.Material,x:number,y:number,z:number,sx=1,sy=1,sz=1)=>{const mesh=new THREE.Mesh(geometry,mat);mesh.position.set(x,y,z);mesh.scale.set(sx,sy,sz);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh};
const limb=(parent:THREE.Object3D,x:number,y:number,z:number,length:number,radius:number,mat:THREE.Material)=>{const pivot=new THREE.Group();pivot.position.set(x,y,z);parent.add(pivot);add(pivot,new THREE.CapsuleGeometry(radius,length,8,14),mat,0,-length/2,0);return pivot};
export function createHumanRig(palette:Palette,female=false):HumanRig{
 const root=new THREE.Group(),skin=material(palette.skin,0,.72),cloth=material(0x111713,.12,.5),pants=material(0x17222d,.12,.58),shoe=material(0x080909,.25,.45),gold=material(palette.secondary,.8,.18);
 const hips=new THREE.Group();hips.position.y=2.12;root.add(hips);add(hips,new THREE.BoxGeometry(.98,.42,.55),pants,0,0,0,female?.9:1,1,1);
 const spine=new THREE.Group();spine.position.y=.26;hips.add(spine);add(spine,new THREE.CylinderGeometry(.42,.47,.78,20),cloth,0,.4,0,female?.9:1,1,.76);
 const chest=new THREE.Group();chest.position.y=.76;spine.add(chest);add(chest,new THREE.CylinderGeometry(female?.47:.58,.4,.88,24),cloth,0,.42,0,1,1,.76);add(chest,new THREE.BoxGeometry(1.18,.25,.68),cloth,0,.7,0);
 add(chest,new THREE.CylinderGeometry(.14,.16,.2,16),skin,0,1,0);const head=new THREE.Group();head.position.y=1.16;chest.add(head);add(head,new THREE.SphereGeometry(.42,30,22),skin,0,.22,0,.86,1.08,.9);add(head,new THREE.ConeGeometry(.43,.28,16),cloth,0,.63,0);add(head,new THREE.BoxGeometry(.58,.11,.07),material(0x080808),0,.31,.36);
 add(head,new THREE.SphereGeometry(.035,12,8),material(0xf5f5f5,0,.2),-.13,.3,.37);add(head,new THREE.SphereGeometry(.035,12,8),material(0xf5f5f5,0,.2),.13,.3,.37);
 const leftArm=limb(chest,-.66,.7,0,.7,.16,cloth),rightArm=limb(chest,.66,.7,0,.7,.16,cloth);const leftFore=limb(leftArm,0,-.7,0,.64,.14,skin),rightFore=limb(rightArm,0,-.7,0,.64,.14,skin);add(leftFore,new THREE.SphereGeometry(.14,14,10),skin,0,-.68,0);add(rightFore,new THREE.SphereGeometry(.14,14,10),skin,0,-.68,0);
 const leftLeg=limb(hips,-.29,-.1,0,.86,.21,pants),rightLeg=limb(hips,.29,-.1,0,.86,.21,pants),leftKnee=limb(leftLeg,0,-.86,0,.8,.18,pants),rightKnee=limb(rightLeg,0,-.86,0,.8,.18,pants);add(leftKnee,new THREE.BoxGeometry(.4,.2,.78),shoe,0,-.86,.17);add(rightKnee,new THREE.BoxGeometry(.4,.2,.78),shoe,0,-.86,.17);
 add(chest,new THREE.TorusGeometry(.33,.035,10,48),gold,0,.54,.45);return{root,spine,head,leftArm,rightArm,leftLeg,rightLeg,leftKnee,rightKnee};
}
export function animateHumanRig(rig:HumanRig,time:number,moving:boolean,sprinting:boolean,action:string){const stride=moving?Math.sin(time*(sprinting?12:7))*(sprinting?.72:.43):Math.sin(time*1.6)*.035;rig.leftArm.rotation.x=stride;rig.rightArm.rotation.x=-stride;rig.leftLeg.rotation.x=-stride;rig.rightLeg.rotation.x=stride;rig.leftKnee.rotation.x=Math.max(0,stride)*.5;rig.rightKnee.rotation.x=Math.max(0,-stride)*.5;rig.leftArm.rotation.z=action==='combat'?-1.05:0;rig.rightArm.rotation.z=action==='combat'?1.05:0;rig.spine.rotation.y=action==='dance'?Math.sin(time*7)*.2:action==='combat'?Math.sin(time*9)*.12:0;rig.head.rotation.y=Math.sin(time*.8)*.035;rig.root.scale.setScalar(action==='power'?1+Math.sin(time*18)*.018:1)}