export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

type Row = Record<string, Json | undefined>;
type Table = { Row: Row; Insert: Row; Update: Row; Relationships: [] };

export type Database = {
  public: {
    Tables: {
      admin_audit_logs: Table; admin_roles: Table; api_jobs: Table; api_request_logs: Table; api_webhook_events: Table;
      app_env_contract: Table; app_runtime_modules: Table; audio_listening_history: Table;
      avatar_animation_clips: Table; avatar_character_presets: Table; avatar_controller_profiles: Table; avatar_inventory: Table; avatar_items: Table; avatar_models: Table; avatar_motion_state: Table;
      background_presets: Table; badges: Table; brand_assets: Table;
      content_review_queue: Table; creator_alert_subscriptions: Table; creator_available_balances: Table; creator_page_settings: Table;
      dm_call_participants: Table; dm_call_sessions: Table; dm_message_attachments: Table; dm_message_reactions: Table; dm_message_reads: Table; dm_messages: Table; dm_thread_members: Table; dm_threads: Table; dm_typing_status: Table;
      feature_flags: Table; feed_comments: Table; feed_post_likes: Table; feed_post_views: Table; feed_posts: Table; followers: Table;
      game_alert_subscriptions: Table; game_categories: Table; game_challenges: Table; game_clips: Table; game_comments: Table; game_levels: Table; game_likes: Table; game_missions: Table; game_moves: Table; game_platform_accounts: Table; game_player_progress: Table; game_rewards: Table; game_room_members: Table; game_rooms: Table; game_runtime_manifests: Table; game_scores: Table; game_sessions: Table; game_stream_links: Table; game_tournaments: Table; gamer_profiles: Table; games: Table; gaming_uploads: Table;
      layout_presets: Table;
      live_alert_subscriptions: Table; live_chat_messages: Table; live_reactions: Table; live_recordings: Table; live_stream_bans: Table; live_stream_cards: Table; live_stream_members: Table; live_stream_purchases: Table; live_streams: Table; live_tips: Table; live_view_sessions: Table; livekit_room_events: Table;
      meta_avatars: Table; meta_chat_messages: Table; meta_inventory: Table; meta_items: Table; meta_portals: Table; meta_room_members: Table; meta_rooms: Table; meta_stream_links: Table; meta_visits: Table; meta_world_likes: Table; meta_worlds: Table;
      moderation_reports: Table;
      music_comments: Table; music_likes: Table; music_play_events: Table; music_tracks: Table;
      notification_groups: Table; notification_reads: Table;
      platform_analytics_events: Table; platform_announcements: Table; playlist_tracks: Table; playlists: Table;
      podcast_comments: Table; podcast_episodes: Table; podcast_likes: Table; podcast_shows: Table;
      product_likes: Table; product_views: Table; products: Table;
      profile_theme_settings: Table; profile_view_events: Table; profiles: Table; public_profile_cards: Table; push_devices: Table;
      radio_likes: Table; radio_sessions: Table; radio_stations: Table; rank_rules: Table; rb_personality_settings: Table; rb_secret_rooms: Table; rich_notifications: Table; route_access_rules: Table; route_registry: Table;
      search_clicks: Table; search_queries: Table; section_theme_settings: Table;
      sports_alert_subscriptions: Table; sports_brackets: Table; sports_broadcasts: Table; sports_comments: Table; sports_leagues: Table; sports_pick_results: Table; sports_picks: Table; sports_posts: Table; sports_profiles: Table; sports_reactions: Table; sports_teams: Table; sports_uploads: Table;
      storage_bucket_routes: Table; store_cart_items: Table; store_comments: Table; store_notifications: Table; store_orders: Table; store_seller_profiles: Table; stripe_sync_events: Table; system_health_checks: Table;
      tournament_players: Table; tracks: Table; trust_events: Table;
      upload_processing_queue: Table; uploads: Table; user_avatar_loadouts: Table; user_badges: Table; user_custom_screens: Table; user_levels: Table; user_product_unlocks: Table; user_sessions: Table; user_settings: Table; user_xp_ledger: Table;
      vip_live_access: Table; watch_comments: Table; watch_likes: Table; watch_progress: Table; watchlist_items: Table;
      xp_event_queue: Table; xp_events: Table; xp_rule_bindings: Table; xp_section_progress: Table;
    };
    Views: { active_brand_assets: Table; creator_products: Table };
    Functions: {
      rb_apply_xp_queue_row: { Args: { p_queue_id: string }; Returns: Json };
      rb_authorize_livekit_room: { Args: { p_room_name: string }; Returns: Json };
      rb_avatar_runtime_snapshot: { Args: Record<string, never>; Returns: Json };
      rb_avatar_set_item: { Args: { p_item_key: string; p_equipped?: boolean }; Returns: Json };
      rb_award_xp: { Args: { p_event_key: string; p_section?: string; p_source_table?: string | null; p_source_id?: string | null; p_amount?: number | null }; Returns: Json };
      rb_create_direct_thread: { Args: { p_other_user: string }; Returns: string };
      rb_enter_meta_world: { Args: { p_world_id: string }; Returns: Json };
      rb_feed_add_comment: { Args: { p_post_id: string; p_body: string }; Returns: Row };
      rb_feed_record_view: { Args: { p_post_id: string; p_session_id?: string | null }; Returns: undefined };
      rb_feed_toggle_like: { Args: { p_post_id: string }; Returns: Json };
      rb_global_search: { Args: { p_query: string; p_limit?: number }; Returns: Row[] };
      rb_is_admin: { Args: { p_min_permission?: number }; Returns: boolean };
      rb_is_dm_thread_member: { Args: { p_thread_id: string }; Returns: boolean };
      rb_join_game_room: { Args: { p_room_code: string }; Returns: Row };
      rb_join_meta_room: { Args: { p_room_id: string }; Returns: Json };
      rb_leave_meta_room: { Args: { p_room_id: string }; Returns: Json };
      rb_personality: { Args: { p_key?: string }; Returns: Json };
      rb_profile_record_view: { Args: { p_profile_id: string; p_session_id?: string | null; p_source?: string }; Returns: undefined };
      rb_profile_toggle_follow: { Args: { p_profile_id: string }; Returns: Json };
      rb_profile_universe_snapshot: { Args: { p_profile_id?: string | null }; Returns: Json };
      rb_rank_for_level: { Args: { p_level: number }; Returns: string };
      rb_reconcile_xp_identity: { Args: { p_user_id: string }; Returns: Json };
      rb_record_game_move: { Args: Record<string, Json | undefined>; Returns: Row };
      rb_register_upload: { Args: { p_route_key: string; p_title: string; p_description: string; p_file_path: string; p_public_url: string; p_mime_type: string; p_file_size: number; p_visibility?: string; p_metadata?: Json }; Returns: Row };
      rb_save_avatar_studio: { Args: { p_display_name: string; p_preset_key: string; p_aura: string; p_outfit?: Json; p_accessories?: Json; p_smoke?: Json; p_emotes?: Json; p_character_type?: string }; Returns: Json };
      rb_store_cart_set: { Args: { p_product_id: string; p_quantity?: number }; Returns: Json };
      rb_store_catalog: { Args: { p_limit?: number }; Returns: Row[] };
      rb_store_record_view: { Args: { p_product_id: string; p_anonymous_id?: string | null }; Returns: undefined };
      rb_store_toggle_like: { Args: { p_product_id: string }; Returns: Json };
      rb_sync_avatar_motion: { Args: { p_position: Json; p_rotation: Json; p_velocity: Json; p_locomotion_state: string; p_action_state?: string; p_active_clip_key?: string; p_input_state?: Json; p_sequence?: number }; Returns: Json };
      rb_watch_feed: { Args: { p_limit?: number }; Returns: Row[] };
      rb_xp_event_allowed: { Args: { p_user_id: string; p_event_key: string }; Returns: boolean };
      rb_xp_snapshot: { Args: { p_user_id?: string }; Returns: Json };
      save_meta_avatar: { Args: Record<string, Json | undefined>; Returns: Row };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
