export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

type Row = Record<string, Json | undefined>;
type Table = { Row: Row; Insert: Row; Update: Row; Relationships: [] };

export type Database = {
  public: {
    Tables: { [table: string]: Table };
    Views: { [view: string]: Table };
    Functions: {
      rb_admin_action: { Args: { p_action: string; p_target_id: string; p_value?: Json }; Returns: Json };
      rb_admin_snapshot: { Args: { p_limit?: number }; Returns: Json };
      rb_apply_xp_queue_row: { Args: { p_queue_id: string }; Returns: Json };
      rb_authorize_livekit_room: { Args: { p_room_name: string }; Returns: Json };
      rb_avatar_runtime_snapshot: { Args: Record<string, never>; Returns: Json };
      rb_avatar_set_item: { Args: { p_equipped?: boolean; p_item_key: string }; Returns: Json };
      rb_award_xp: { Args: { p_amount?: number; p_event_key: string; p_section?: string; p_source_id?: string; p_source_table?: string }; Returns: Json };
      rb_claim_upload_jobs: { Args: { p_limit?: number; p_worker: string }; Returns: Row[] };
      rb_create_direct_thread: { Args: { p_other_user: string }; Returns: string };
      rb_creator_dimension_snapshot: { Args: Record<string, never>; Returns: Json };
      rb_creator_request_dimension: { Args: { p_dimension_key: string }; Returns: Json };
      rb_creator_save_page: { Args: { p_payload: Json }; Returns: Json };
      rb_dm_assert_member: { Args: { p_thread_id: string; p_user_id?: string }; Returns: boolean };
      rb_dm_finalize_attachment: { Args: { p_file_name: string; p_file_size: number; p_file_url: string; p_mime_type: string; p_storage_path: string; p_thread_id: string }; Returns: string };
      rb_dm_mark_thread_read: { Args: { p_thread_id: string }; Returns: Json };
      rb_dm_search_profiles: { Args: { p_limit?: number; p_query: string }; Returns: Row[] };
      rb_dm_send_message: { Args: { p_body: string; p_reply_to?: string; p_thread_id: string }; Returns: string };
      rb_dm_set_typing: { Args: { p_is_typing: boolean; p_thread_id: string }; Returns: undefined };
      rb_dm_start_call: { Args: { p_call_type: string; p_thread_id: string }; Returns: Json };
      rb_dm_thread_snapshot: { Args: { p_limit?: number; p_thread_id: string }; Returns: Json };
      rb_dm_threads_snapshot: { Args: { p_limit?: number }; Returns: Json };
      rb_dm_toggle_reaction: { Args: { p_emoji: string; p_message_id: string }; Returns: Json };
      rb_end_live_stream: { Args: { p_stream_id: string }; Returns: Json };
      rb_enter_meta_world: { Args: { p_world_id: string }; Returns: Json };
      rb_feed_action: { Args: { p_action: string; p_payload?: Json }; Returns: Json };
      rb_feed_add_comment: { Args: { p_body: string; p_post_id: string }; Returns: Row };
      rb_feed_record_view: { Args: { p_post_id: string; p_session_id?: string }; Returns: undefined };
      rb_feed_snapshot: { Args: { p_limit?: number; p_post_id?: string; p_section?: string }; Returns: Json };
      rb_feed_toggle_like: { Args: { p_post_id: string }; Returns: Json };
      rb_finish_upload_job: { Args: { p_error?: string; p_job_id: string; p_result?: Json; p_success: boolean; p_worker: string }; Returns: Row };
      rb_gallery_action: { Args: { p_action: string; p_payload?: Json }; Returns: Json };
      rb_gallery_snapshot: { Args: { p_active_id?: string; p_limit?: number }; Returns: Json };
      rb_game_action: { Args: { p_action: string; p_game_slug: string; p_payload?: Json }; Returns: Json };
      rb_game_room_action: { Args: { p_action: string; p_game_slug: string; p_payload?: Json }; Returns: Json };
      rb_game_save_action: { Args: { p_action: string; p_game_slug: string; p_payload?: Json }; Returns: Json };
      rb_gaming_snapshot:
        | { Args: Record<string, never>; Returns: Json }
        | { Args: { p_game_id?: string; p_limit?: number; p_user_id?: string }; Returns: Json };
      rb_global_search: { Args: { p_limit?: number; p_query: string }; Returns: Row[] };
      rb_go_live_bootstrap: { Args: Record<string, never>; Returns: Json };
      rb_is_admin: { Args: { p_min_permission?: number }; Returns: boolean };
      rb_is_dm_thread_member: { Args: { p_thread_id: string }; Returns: boolean };
      rb_join_game_room: { Args: { p_room_code: string }; Returns: Row };
      rb_join_meta_room: { Args: { p_room_id: string }; Returns: Json };
      rb_leave_meta_room: { Args: { p_room_id: string }; Returns: Json };
      rb_live_action: { Args: { p_action: string; p_payload?: Json; p_stream_id: string }; Returns: Json };
      rb_live_can_access: { Args: { p_stream_id: string; p_user_id?: string }; Returns: boolean };
      rb_live_heartbeat: { Args: { p_stream_id: string }; Returns: Json };
      rb_live_join: { Args: { p_stream_id: string }; Returns: Json };
      rb_live_leave: { Args: { p_stream_id: string }; Returns: Json };
      rb_live_snapshot: { Args: { p_stream_id?: string }; Returns: Json };
      rb_live_watch_podcast_snapshot: { Args: Record<string, never>; Returns: Json };
      rb_media_universe_snapshot: { Args: Record<string, never>; Returns: Json };
      rb_meta_universe_snapshot: { Args: { p_world_id?: string }; Returns: Json };
      rb_music_action: { Args: { p_action: string; p_payload?: Json }; Returns: Json };
      rb_music_snapshot: { Args: { p_limit?: number; p_track_id?: string }; Returns: Json };
      rb_notifications_mark_read: { Args: { p_all?: boolean; p_notification_id?: string }; Returns: Json };
      rb_notifications_mark_seen: { Args: { p_ids?: string[] }; Returns: Json };
      rb_notifications_snapshot: { Args: { p_limit?: number }; Returns: Json };
      rb_personality: { Args: { p_key?: string }; Returns: Json };
      rb_podcast_action: { Args: { p_action: string; p_payload?: Json }; Returns: Json };
      rb_podcast_snapshot: { Args: { p_episode_id?: string; p_limit?: number }; Returns: Json };
      rb_portal_elite_snapshot: { Args: Record<string, never>; Returns: Json };
      rb_portal_universe_snapshot: { Args: Record<string, never>; Returns: Json };
      rb_profile_follow_action: { Args: { p_target_id: string }; Returns: Json };
      rb_profile_record_view: { Args: { p_profile_id: string; p_session_id?: string; p_source?: string }; Returns: undefined };
      rb_profile_toggle_follow: { Args: { p_profile_id: string }; Returns: Json };
      rb_profile_universe_snapshot: { Args: { p_profile_id?: string }; Returns: Json };
      rb_radio_action: { Args: { p_action: string; p_payload?: Json }; Returns: Json };
      rb_radio_snapshot: { Args: { p_limit?: number; p_station_id?: string }; Returns: Json };
      rb_rank_for_level: { Args: { p_level: number }; Returns: string };
      rb_reconcile_xp_identity: { Args: { p_user_id: string }; Returns: Json };
      rb_record_game_move: { Args: { p_board_state: Json; p_captured_piece: string; p_from_square: string; p_move_data?: Json; p_next_turn: string; p_piece: string; p_room_id: string; p_to_square: string }; Returns: Row };
      rb_recover_stale_upload_jobs: { Args: { p_stale_after?: string }; Returns: number };
      rb_register_upload: { Args: { p_description: string; p_file_path: string; p_file_size: number; p_metadata?: Json; p_mime_type: string; p_public_url: string; p_route_key: string; p_title: string; p_visibility?: string }; Returns: Row };
      rb_save_avatar_studio: { Args: { p_accessories?: Json; p_aura: string; p_character_type?: string; p_display_name: string; p_emotes?: Json; p_outfit?: Json; p_preset_key: string; p_smoke?: Json }; Returns: Json };
      rb_save_profile_identity: { Args: { p_avatar_url?: string; p_banner_url?: string; p_bio?: string; p_display_name: string; p_facebook_url?: string; p_favorite_section?: string; p_instagram_url?: string; p_snapchat_url?: string; p_tiktok_url?: string; p_username: string; p_website_url?: string; p_youtube_url?: string }; Returns: Json };
      rb_save_universe_settings: { Args: { p_accent_color: string; p_avatar_frame: string; p_background_style: string; p_banner_overlay: string; p_button_style: string; p_cinema_mode: boolean; p_default_theme: string; p_depth_3d: boolean; p_dm_privacy: string; p_font_style: string; p_glow_fx: boolean; p_language: string; p_motion_level: string; p_notification_config: Json; p_notification_level: string; p_privacy_config: Json; p_profile_layout: string; p_profile_visibility: string; p_smoke_fx: boolean; p_timezone: string; p_tv_mode: boolean }; Returns: Json };
      rb_search_action: { Args: { p_action: string; p_payload?: Json }; Returns: Json };
      rb_search_snapshot: { Args: { p_category?: string; p_limit?: number; p_query?: string }; Returns: Json };
      rb_send_meta_message: { Args: { p_body: string; p_room_id: string }; Returns: Json };
      rb_settle_live_payment: { Args: { p_amount_cents?: number; p_checkout_session_id?: string; p_kind: string; p_metadata?: Json; p_payment_intent_id: string; p_reference_id: string }; Returns: Json };
      rb_settle_store_payment: { Args: { p_amount_cents?: number; p_checkout_key: string; p_checkout_session_id?: string; p_currency?: string; p_metadata?: Json; p_payment_intent_id: string }; Returns: Json };
      rb_sports_action: { Args: { p_action: string; p_payload?: Json }; Returns: Json };
      rb_sports_snapshot: { Args: { p_limit?: number }; Returns: Json };
      rb_start_live_stream: { Args: { p_access_type?: string; p_category?: string; p_cover_url?: string; p_description?: string; p_is_chat_enabled?: boolean; p_is_cohost_enabled?: boolean; p_price_cents?: number; p_recording_enabled?: boolean; p_thumbnail_url?: string; p_title: string; p_transcription_enabled?: boolean }; Returns: Json };
      rb_store_cart_set: { Args: { p_product_id: string; p_quantity?: number }; Returns: Json };
      rb_store_catalog: { Args: { p_limit?: number }; Returns: Row[] };
      rb_store_checkout: { Args: { p_idempotency_key?: string }; Returns: Json };
      rb_store_record_view: { Args: { p_anonymous_id?: string; p_product_id: string }; Returns: undefined };
      rb_store_toggle_like: { Args: { p_product_id: string }; Returns: Json };
      rb_sync_avatar_motion: { Args: { p_action_state?: string; p_active_clip_key?: string; p_input_state?: Json; p_locomotion_state: string; p_position: Json; p_rotation: Json; p_sequence?: number; p_velocity: Json }; Returns: Json };
      rb_sync_processed_upload_destination: { Args: { p_result?: Json; p_upload_id: string }; Returns: Json };
      rb_upload_processing_claim: { Args: { p_limit?: number; p_worker: string }; Returns: Row[] };
      rb_upload_processing_finish: { Args: { p_error?: string; p_job_id: string; p_result?: Json; p_success: boolean; p_worker: string }; Returns: Row };
      rb_upload_processing_recover_stale: { Args: { p_timeout_minutes?: number }; Returns: number };
      rb_upload_route_requires_target: { Args: { p_route_key: string }; Returns: boolean };
      rb_upload_snapshot: { Args: { p_limit?: number }; Returns: Json };
      rb_watch_action: { Args: { p_action: string; p_payload?: Json; p_source_id: string; p_source_type: string }; Returns: Json };
      rb_watch_feed: { Args: { p_limit?: number }; Returns: Row[] };
      rb_watch_snapshot: { Args: { p_source_id?: string; p_source_type?: string }; Returns: Json };
      rb_xp_event_allowed: { Args: { p_event_key: string; p_user_id: string }; Returns: boolean };
      rb_xp_snapshot: { Args: { p_user_id?: string }; Returns: Json };
      save_meta_avatar: { Args: { p_aura?: string; p_avatar_config?: Json; p_avatar_url?: string; p_display_name?: string; p_level?: number; p_model_url?: string; p_motion?: string; p_outfit?: string; p_rank?: string; p_xp?: number }; Returns: Row };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
