import { supabase } from '../../core/supabase/client';
import '../../styles/media-universe.css';

type Row=Record<string,any>;
const esc=(v:any)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c));
const money=(v:any)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v??0)/100);

export async function mount():Promise<void>{
 const root=document.querySelector<HTMLElement>('#app');if(!root)throw new Error('Missing #app mount');
 const {data:{session}}=await supabase.auth.getSession();if(!session){location.replace('/tap-in.html?next=%2Flive.html');return;}
 const {data,error}=await supabase.rpc('rb_media_universe_snapshot',{});if(error)throw error;
 const snap=(data??{}) as Row;const streams=(snap.live??[]) as Row[];const recordings=(snap.recordings??[]) as Row[];
 const featured=streams.find(s=>String(s.status).toLowerCase()==='live')??streams[0]??null;
 root.innerHTML=`<main class="universe-shell"><div class="universe-wrap">
 <header class="universe-head"><a href="/portal.html">←</a><div><p>RICH BIZNESS BROADCAST NETWORK</p><h1>LIVE UNIVERSE</h1></div><span class="universe-sync">REALTIME</span></header>
 <section id="liveHero" class="universe-hero">${featured?renderHero(featured):'<div class="universe-empty">No live room is active yet.</div>'}</section>
 <section class="universe-metrics"><article><small>LIVE ROOMS</small><strong>${streams.filter(s=>String(s.status).toLowerCase()==='live').length}</strong></article><article><small>VIEWERS</small><strong>${streams.reduce((n,s)=>n+Number(s.viewer_count??0),0).toLocaleString()}</strong></article><article><small>REACTIONS</small><strong>${streams.reduce((n,s)=>n+Number(s.total_reactions??0),0).toLocaleString()}</strong></article><article><small>NETWORK REVENUE</small><strong>${money(streams.reduce((n,s)=>n+Number(s.total_revenue_cents??0),0))}</strong></article></section>
 <nav class="universe-tabs" id="liveTabs"><button class="universe-tab active" data-lane="live">LIVE NOW</button><button class="universe-tab" data-lane="upcoming">UPCOMING</button><button class="universe-tab" data-lane="recordings">REPLAYS</button><button class="universe-tab" data-lane="vip">VIP</button></nav>
 <section class="universe-section"><header><div><h2 id="laneTitle">Live Now</h2><p>Creator rooms, premium broadcasts, co-host sessions and realtime reactions.</p></div><a class="universe-btn" href="/creator.html">GO LIVE</a></header><div id="liveGrid" class="universe-grid"></div></section>
 <section class="universe-side-grid universe-section"><article class="universe-panel"><header><h3>Broadcast Control</h3></header><div id="liveDetail" class="universe-list"></div></article><article class="universe-panel"><header><h3>Live Chat</h3></header><div id="liveChat" class="universe-chat"><div class="universe-empty">Open a room to connect chat.</div></div><form id="chatForm" class="universe-form"><input id="chatInput" maxlength="800" placeholder="Say something rich..."><button class="universe-btn primary">SEND</button></form></article></section>
 </div></main>`;
 let lane='live';let active:Row|null=featured;let channel:any=null;
 const grid=document.querySelector<HTMLElement>('#liveGrid')!;const title=document.querySelector<HTMLElement>('#laneTitle')!;const detail=document.querySelector<HTMLElement>('#liveDetail')!;const chat=document.querySelector<HTMLElement>('#liveChat')!;
 const rows=()=>lane==='recordings'?recordings:streams.filter(s=>lane==='live'?String(s.status).toLowerCase()==='live':lane==='upcoming'?['scheduled','upcoming','ready'].includes(String(s.status).toLowerCase()):s.is_vip_enabled);
 const renderGrid=()=>{const list=rows();grid.innerHTML=list.length?list.map(r=>`<article class="universe-card" data-id="${r.id}"><div class="universe-card__art"><img src="${esc(r.thumbnail_url||r.cover_url||'/images/brand/IMG_5997.png')}" alt=""><span class="universe-card__badge">${esc((r.status||'REPLAY').toUpperCase())}</span></div><div class="universe-card__body"><h3>${esc(r.title||'Rich Broadcast')}</h3><p>${esc(r.description||r.category||'Creator broadcast')}</p><div class="universe-card__meta"><span>${Number(r.viewer_count??r.view_count??0).toLocaleString()} views</span><span>${r.is_vip_enabled?'VIP':esc(r.category||'LIVE')}</span></div></div></article>`).join(''):'<div class="universe-empty">Nothing in this lane yet.</div>';grid.querySelectorAll<HTMLElement>('[data-id]').forEach(el=>el.onclick=()=>{active=list.find(r=>String(r.id)===el.dataset.id)??null;if(active)void open(active);});};
 const loadChat=async()=>{if(!active||lane==='recordings'){chat.innerHTML='<div class="universe-empty">Replay chat is not active.</div>';return;}const {data:rows}=await supabase.from('live_chat_messages').select('id,user_id,display_name,username,message,body,is_pinned,created_at').eq('stream_id',active.id).eq('is_deleted',false).order('created_at',{ascending:true}).limit(100);chat.innerHTML=(rows??[]).length?(rows??[]).map((m:any)=>`<article><p>${esc(m.message||m.body)}</p><small>${esc(m.display_name||m.username||'Rich Member')}${m.is_pinned?' · PINNED':''}</small></article>`).join(''):'<div class="universe-empty">Start the live conversation.</div>';chat.scrollTop=chat.scrollHeight;};
 const open=async(r:Row)=>{active=r;document.querySelector<HTMLElement>('#liveHero')!.innerHTML=renderHero(r);detail.innerHTML=`<div class="universe-row"><img src="${esc(r.thumbnail_url||r.cover_url||'/images/brand/IMG_5997.png')}" alt=""><div><h4>${esc(r.title||'Rich Broadcast')}</h4><p>${esc(r.category||'Live')} · ${esc(r.access_type||'public')} · ${esc(r.latency_mode||'standard')}</p></div><strong>${Number(r.viewer_count??r.view_count??0).toLocaleString()}</strong></div><div class="universe-row"><div><h4>Broadcast Quality</h4><p>${r.recording_enabled?'Recording enabled':'No recording'} · ${r.transcription_enabled?'Transcription on':'Transcription off'}</p></div><strong>${esc(r.stream_protocol||'LiveKit')}</strong></div><div class="universe-row"><div><h4>Revenue</h4><p>${r.is_vip_enabled?'VIP monetization enabled':'Open access room'}</p></div><strong>${money(r.total_revenue_cents??0)}</strong></div>`;if(channel)await supabase.removeChannel(channel);if(lane!=='recordings'){await loadChat();channel=supabase.channel(`live-room:${r.id}`).on('postgres_changes',{event:'*',schema:'public',table:'live_chat_messages',filter:`stream_id=eq.${r.id}`},()=>void loadChat()).on('postgres_changes',{event:'INSERT',schema:'public',table:'live_reactions',filter:`stream_id=eq.${r.id}`},payload=>spawnReaction(String((payload.new as any).reaction??'💨'))).subscribe();}};
 document.querySelectorAll<HTMLButtonElement>('[data-lane]').forEach(b=>b.onclick=()=>{lane=b.dataset.lane!;document.querySelectorAll('[data-lane]').forEach(x=>x.classList.toggle('active',x===b));title.textContent=b.textContent??'Live';renderGrid();const first=rows()[0];if(first)void open(first);});
 document.querySelector<HTMLFormElement>('#chatForm')!.onsubmit=async e=>{e.preventDefault();if(!active||lane==='recordings')return;const input=document.querySelector<HTMLInputElement>('#chatInput')!;const body=input.value.trim();if(!body)return;const p=snap.profile??{};const {error}=await supabase.from('live_chat_messages').insert({stream_id:active.id,user_id:session.user.id,username:p.username,display_name:p.display_name,message:body,body});if(!error)input.value='';};
 const spawnReaction=(reaction:string)=>{const el=document.createElement('span');el.textContent=reaction;el.style.cssText='position:fixed;right:72px;bottom:110px;z-index:100;font-size:2rem;animation:portalSpark 2s ease-out forwards';document.body.append(el);setTimeout(()=>el.remove(),2000);};
 renderGrid();if(featured)await open(featured);
}

function renderHero(r:Row){const video=r.recording_url?`<video class="universe-hero__media" controls playsinline poster="${esc(r.thumbnail_url||r.cover_url)}" src="${esc(r.recording_url)}"></video>`:`<img class="universe-hero__media" src="${esc(r.cover_url||r.thumbnail_url||'/images/brand/IMG_5997.png')}" alt="">`;return `${video}<div class="universe-hero__shade"></div><div class="universe-hero__content"><span class="universe-kicker">${String(r.status).toLowerCase()==='live'?'● LIVE NOW':'▶ REPLAY'} · ${esc(r.category||'CREATOR')}</span><h2>${esc(r.title||'Rich Broadcast')}</h2><p>${esc(r.description||'Enter the Rich Bizness live universe.')}</p><div class="universe-actions"><a class="universe-btn primary" href="${r.livekit_room_name?`/api/live/token?room=${encodeURIComponent(r.livekit_room_name)}`:'#'}">${String(r.status).toLowerCase()==='live'?'ENTER ROOM':'WATCH NOW'}</a><a class="universe-btn" href="/profile.html?id=${esc(r.creator_id)}">CREATOR</a><button class="universe-btn" type="button">♡ REACT</button></div></div>`;}
