import { supabase } from '../../core/supabase/client';
import '../../styles/broadcast-cinema-podcast.css';

type Row=Record<string,any>;
const esc=(v:any)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c));
const money=(v:any)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v??0)/100);

export async function mount():Promise<void>{
 const root=document.querySelector<HTMLElement>('#app');if(!root)throw new Error('Missing #app mount');
 const {data:{session}}=await supabase.auth.getSession();if(!session){location.replace('/tap-in.html?next=%2Flive.html');return;}
 const {data,error}=await supabase.rpc('rb_live_watch_podcast_snapshot',{});if(error)throw error;
 const snap=(data??{}) as Row;const streams=(snap.live??[]) as Row[];const recordings=(snap.recordings??[]) as Row[];const cards=(snap.live_cards??[]) as Row[];const purchases=(snap.live_purchases??[]) as Row[];const vip=new Set(((snap.vip_access??[]) as Row[]).map(v=>String(v.stream_id)));const alerts=new Set(((snap.live_alerts??[]) as Row[]).map(v=>String(v.creator_id??v.stream_id)));
 let lane='live';let active:Row|null=streams.find(s=>String(s.status).toLowerCase()==='live')??streams[0]??recordings[0]??null;let channel:any=null;
 root.innerHTML=`<main class="media-ultimate"><div class="media-ultimate__wrap"><header class="media-ultimate__head"><a href="/portal.html">←</a><div><p>RICH BIZNESS GLOBAL BROADCAST NETWORK</p><h1>LIVE UNIVERSE</h1></div><span class="media-ultimate__status">● REALTIME</span></header><section id="liveHero" class="media-ultimate__hero">${active?hero(active):'<div class="media-ultimate__empty">No broadcast is active.</div>'}</section><section class="media-ultimate__metrics"><article><small>LIVE ROOMS</small><strong>${streams.filter(s=>String(s.status).toLowerCase()==='live').length}</strong></article><article><small>GLOBAL VIEWERS</small><strong>${streams.reduce((n,s)=>n+Number(s.viewer_count??0),0).toLocaleString()}</strong></article><article><small>VIP ACCESS</small><strong>${vip.size}</strong></article><article><small>CREATOR REVENUE</small><strong>${money(streams.reduce((n,s)=>n+Number(s.total_revenue_cents??0),0))}</strong></article></section><nav class="media-ultimate__tabs">${[['live','LIVE NOW'],['upcoming','UPCOMING'],['vip','VIP'],['replays','REPLAYS'],['network','NETWORK CARDS']].map(([v,l],i)=>`<button class="${i===0?'active':''}" data-lane="${v}">${l}</button>`).join('')}</nav><section class="media-ultimate__section"><header><div><h3 id="laneTitle">Live Now</h3><p>Interactive rooms, creator broadcasts, co-host sessions, VIP access, reactions and chat.</p></div><a class="media-ultimate__btn primary" href="/creator.html">START BROADCAST</a></header><div id="liveGrid" class="media-ultimate__grid"></div></section><section class="media-ultimate__split"><article class="media-ultimate__panel"><header><h4>BROADCAST INTELLIGENCE</h4></header><div id="liveDetail" class="media-ultimate__list"></div></article><article class="media-ultimate__panel"><header><h4>LIVE ROOM CHAT</h4></header><div id="liveChat" class="media-ultimate__chat"><div class="media-ultimate__empty">Open a room.</div></div><form id="chatForm" class="media-ultimate__form"><input id="chatInput" maxlength="800" placeholder="Say something rich..."><button class="media-ultimate__btn primary">SEND</button></form></article></section><section class="media-ultimate__section"><header><div><h3>Your Access</h3><p>Purchased rooms, VIP passes and creator alerts connected to your identity.</p></div></header><div class="media-ultimate__grid">${[...purchases.slice(0,4),...((snap.vip_access??[]) as Row[]).slice(0,4)].map(r=>card(r,'ACCESS')).join('')||'<div class="media-ultimate__empty">No premium access yet.</div>'}</div></section></div></main>`;
 const grid=document.querySelector<HTMLElement>('#liveGrid')!;const title=document.querySelector<HTMLElement>('#laneTitle')!;const detail=document.querySelector<HTMLElement>('#liveDetail')!;const chat=document.querySelector<HTMLElement>('#liveChat')!;
 const rows=()=>lane==='replays'?recordings:lane==='network'?cards:streams.filter(s=>lane==='live'?String(s.status).toLowerCase()==='live':lane==='upcoming'?['scheduled','upcoming','ready'].includes(String(s.status).toLowerCase()):s.is_vip_enabled||vip.has(String(s.id)));
 const render=()=>{const list=rows();grid.innerHTML=list.length?list.map(r=>card(r,lane.toUpperCase())).join(''):'<div class="media-ultimate__empty">Nothing in this lane yet.</div>';grid.querySelectorAll<HTMLElement>('[data-id]').forEach(el=>el.onclick=()=>{const r=list.find(x=>String(x.id)===el.dataset.id);if(r)void open(r);});};
 const loadChat=async()=>{if(!active||lane==='replays'||lane==='network'){chat.innerHTML='<div class="media-ultimate__empty">Chat is available inside active rooms.</div>';return;}const {data}=await supabase.from('live_chat_messages').select('id,display_name,username,message,body,is_pinned,created_at').eq('stream_id',active.id).eq('is_deleted',false).order('created_at',{ascending:true}).limit(120);chat.innerHTML=(data??[]).map((m:any)=>`<article><p>${esc(m.message||m.body)}</p><small>${esc(m.display_name||m.username||'Rich Member')}${m.is_pinned?' · PINNED':''}</small></article>`).join('')||'<div class="media-ultimate__empty">Start the conversation.</div>';chat.scrollTop=chat.scrollHeight;};
 const open=async(r:Row)=>{active=r;document.querySelector<HTMLElement>('#liveHero')!.innerHTML=hero(r);detail.innerHTML=[['Broadcast',`${r.category||'Creator'} · ${r.access_type||'public'} · ${r.latency_mode||'standard'}`],['Quality',`${r.stream_protocol||'LiveKit'} · ${r.recording_enabled?'recording on':'recording off'} · ${r.transcription_enabled?'captions on':'captions off'}`],['Audience',`${Number(r.viewer_count??r.view_count??0).toLocaleString()} watching · ${Number(r.peak_viewers??0).toLocaleString()} peak`],['Commerce',`${money(r.price_cents??0)} access · ${money(r.total_revenue_cents??0)} revenue`],['Controls',`${r.is_chat_enabled?'chat':'no chat'} · ${r.is_cohost_enabled?'co-host':'solo'} · ${r.is_vip_enabled?'VIP':'open'}`]].map(([a,b])=>`<div class="media-ultimate__row"><div><h5>${a}</h5><p>${esc(b)}</p></div></div>`).join('');if(channel)await supabase.removeChannel(channel);await loadChat();if(lane!=='replays'&&lane!=='network')channel=supabase.channel(`ultimate-live:${r.id}`).on('postgres_changes',{event:'*',schema:'public',table:'live_chat_messages',filter:`stream_id=eq.${r.id}`},()=>void loadChat()).on('postgres_changes',{event:'INSERT',schema:'public',table:'live_reactions',filter:`stream_id=eq.${r.id}`},p=>burst(String((p.new as any).reaction??'💨'))).subscribe();bindHero(r);};
 const bindHero=(r:Row)=>{document.querySelector<HTMLButtonElement>('#alertBtn')?.addEventListener('click',async()=>{if(alerts.has(String(r.creator_id))){await supabase.from('live_alert_subscriptions').delete().eq('user_id',session.user.id).eq('creator_id',r.creator_id);alerts.delete(String(r.creator_id));}else{await supabase.from('live_alert_subscriptions').insert({user_id:session.user.id,creator_id:r.creator_id,alert_level:'all'});alerts.add(String(r.creator_id));}await open(r);});document.querySelector<HTMLButtonElement>('#reactBtn')?.addEventListener('click',async()=>{await supabase.from('live_reactions').insert({stream_id:r.id,user_id:session.user.id,reaction:'💨'});burst('💨');});};
 document.querySelectorAll<HTMLButtonElement>('[data-lane]').forEach(b=>b.onclick=()=>{lane=b.dataset.lane!;document.querySelectorAll('[data-lane]').forEach(x=>x.classList.toggle('active',x===b));title.textContent=b.textContent??'Live';render();const first=rows()[0];if(first)void open(first);});
 document.querySelector<HTMLFormElement>('#chatForm')!.onsubmit=async e=>{e.preventDefault();if(!active||lane==='replays'||lane==='network')return;const input=document.querySelector<HTMLInputElement>('#chatInput')!;const body=input.value.trim();if(!body)return;const p=snap.profile??{};const {error}=await supabase.from('live_chat_messages').insert({stream_id:active.id,user_id:session.user.id,username:p.username,display_name:p.display_name,message:body,body});if(!error)input.value='';};
 render();if(active)await open(active);
}
function hero(r:Row){const media=r.recording_url?`<video class="media-ultimate__hero-media" controls playsinline poster="${esc(r.thumbnail_url||r.cover_url)}" src="${esc(r.recording_url)}"></video>`:`<img class="media-ultimate__hero-media" src="${esc(r.cover_url||r.thumbnail_url||'/images/brand/IMG_5997.png')}" alt="">`;return `${media}<div class="media-ultimate__hero-copy"><span class="media-ultimate__eyebrow">${String(r.status).toLowerCase()==='live'?'● LIVE NOW':'RICH BROADCAST'} · ${esc(r.category||'CREATOR')}</span><h2>${esc(r.title||'Rich Broadcast')}</h2><p>${esc(r.description||'Interactive creator broadcasting across the Rich Bizness universe.')}</p><div class="media-ultimate__actions"><a class="media-ultimate__btn primary" href="${r.livekit_room_name?`/api/live/token?room=${encodeURIComponent(r.livekit_room_name)}`:'#'}">${String(r.status).toLowerCase()==='live'?'ENTER LIVE ROOM':'WATCH REPLAY'}</a><a class="media-ultimate__btn" href="/profile.html?id=${esc(r.creator_id)}">CREATOR</a><button id="reactBtn" class="media-ultimate__btn">💨 REACT</button><button id="alertBtn" class="media-ultimate__btn">🔔 ALERTS</button></div></div>`;}
function card(r:Row,badge:string){return `<article class="media-ultimate__card" data-id="${esc(r.id)}"><img src="${esc(r.thumbnail_url||r.cover_url||'/images/brand/IMG_5997.png')}" alt=""><div class="media-ultimate__card-body"><h4>${esc(r.title||r.subtitle||'Rich Broadcast')}</h4><p>${esc(r.description||r.category||r.card_type||'Global broadcast')}</p><div class="media-ultimate__meta"><span>${badge}</span><span>${Number(r.viewer_count??r.view_count??0).toLocaleString()} views</span></div></div></article>`;}
function burst(v:string){const el=document.createElement('span');el.textContent=v;el.style.cssText='position:fixed;right:8vw;bottom:15vh;z-index:999;font-size:2.4rem;animation:portalSpark 2s ease-out forwards';document.body.append(el);setTimeout(()=>el.remove(),2000);}
