import { supabase } from '../../src/supabase-client.js';
import { getAuthoritativeIdentity } from '../../src/rb-identity.js?v=profile-avatar-separate-1';
import { awardXp } from '../../src/rb-xp.js?v=xp-idempotent-1';

const $=id=>document.getElementById(id),c=$('court'),g=c.getContext('2d'),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
let p,d,b,score,streak,time,energy,shots,perfects,running,paused,charging,charge,dir,last,identity={},game=null,raf;
function status(a,m){$('status').textContent=a;$('detail').textContent=m}
function sync(){
  $('score').textContent=score.toLocaleString();$('streak').textContent=streak;$('clock').textContent=Math.ceil(time);$('energy').textContent=Math.floor(energy);
  $('shotFill').style.width=`${charge}%`;$('shotLabel').textContent=charging?'RELEASE TO SHOOT':'HOLD SHOOT';
  $('missionShots').textContent=`${Math.min(shots,5)}/5`;$('missionPerfect').textContent=`${Math.min(perfects,3)}/3`;$('missionScore').textContent=`${Math.min(score,1500)}/1500`;
}
function reset(){cancelAnimationFrame(raf);p={x:250,y:405};d={x:610,y:405,v:-90};b={x:0,y:0,vx:0,vy:0,on:false};score=0;streak=0;time=60;energy=100;shots=0;perfects=0;running=true;paused=false;charging=false;charge=0;dir=1;last=performance.now();status('READY','Hold and release shoot inside the gold timing window.');sync();loop(last)}
function hold(){if(running&&!paused&&!b.on&&energy>=8)charging=true}
function release(){if(!charging)return;charging=false;shots++;const accuracy=100-Math.abs(70-charge)*2.6;b={x:p.x+44,y:p.y+18,vx:6.4+charge/35,vy:-11-charge/25,on:true,accuracy,perfect:charge>=64&&charge<=76};energy-=10;charge=0;sync()}
function act(a){if(!running||paused)return;if(a==='left')p.x=clamp(p.x-34,90,690);if(a==='right')p.x=clamp(p.x+34,90,690);if(a==='steal'){energy=clamp(energy-9,0,100);if(Math.abs(p.x-d.x)<95){score+=140;streak++;status('CLEAN STEAL','Possession secured.')}else{streak=0;status('MISSED STEAL','Defender slipped past.')}}if(a==='boost'&&energy>=18){energy-=18;p.x=clamp(p.x+90,90,690);score+=60;status('RICH BOOST','Explosive first step.')}sync()}
function resolve(){const made=Math.abs(b.x-820)<65&&Math.abs(b.y-176)<55&&b.vy>0&&b.accuracy>28;if(made){score+=(b.perfect?420:220)+streak*20;streak++;if(b.perfect){perfects++;status('PERFECT GREEN','Pure release. Gold splash.')}else status('BUCKET','Clean Rich Court finish.')}else{streak=0;status('MISS','Reset your timing and attack again.')}b.on=false;sync()}
function update(dt){if(!running||paused)return;time-=dt;energy=clamp(energy+dt*5.5,0,100);d.x+=d.v*dt;if(d.x<430||d.x>720)d.v*=-1;if(charging){charge+=dir*92*dt;if(charge>=100){charge=100;dir=-1}else if(charge<=0){charge=0;dir=1}}if(b.on){b.vy+=25*dt;b.x+=b.vx*60*dt;b.y+=b.vy*60*dt;if(b.y>500||b.x>900||(Math.abs(b.x-820)<68&&Math.abs(b.y-176)<60&&b.vy>0))resolve()}if(time<=0){time=0;running=false;status('RUN COMPLETE',`${score.toLocaleString()} points • ${perfects} perfect releases`);save(true)}sync()}
function draw(){const bg=g.createLinearGradient(0,0,960,540);bg.addColorStop(0,'#174d22');bg.addColorStop(1,'#061108');g.fillStyle=bg;g.fillRect(0,0,960,540);g.strokeStyle='rgba(255,229,138,.75)';g.lineWidth=5;g.strokeRect(48,48,864,444);g.beginPath();g.arc(480,270,80,0,Math.PI*2);g.stroke();g.strokeRect(700,110,212,320);g.fillStyle='#ffe58a';g.fillRect(810,116,8,100);g.strokeStyle='#9dff63';g.lineWidth=7;g.beginPath();g.ellipse(820,176,34,10,0,0,Math.PI*2);g.stroke();g.font='66px system-ui';g.fillText('🏀',p.x,p.y+58);g.fillText('🛡️',d.x,d.y+58);if(b.on){g.font='30px system-ui';g.fillText('🏀',b.x,b.y)}g.fillStyle='rgba(0,0,0,.5)';g.fillRect(20,18,260,42);g.fillStyle='#9dff63';g.font='900 18px system-ui';g.fillText(`STREAK x${streak} • ${Math.ceil(time)}s`,36,46);if(paused){g.fillStyle='rgba(0,0,0,.68)';g.fillRect(0,0,960,540);g.fillStyle='#ffe58a';g.font='900 58px system-ui';g.textAlign='center';g.fillText('PAUSED',480,275);g.textAlign='start'}}
function loop(now){const dt=Math.min(.033,(now-last)/1000||0);last=now;update(dt);draw();raf=requestAnimationFrame(loop)}
async function load(){identity=await getAuthoritativeIdentity().catch(()=>({}));const {data}=await supabase.from('games').select('id,slug').eq('slug','rich-court-king').maybeSingle();game=data;const r=await supabase.from('game_scores').select('display_name,username,score').eq('game_slug','rich-court-king').order('score',{ascending:false}).limit(8);$('leaderboard').innerHTML=(r.data||[]).map((x,i)=>`<li>#${i+1} ${x.display_name||x.username||'Rich Player'} <b>${Number(x.score||0).toLocaleString()}</b></li>`).join('')||'<li>No scores yet.</li>'}
async function save(auto=false){if(!identity.user&&!auto){location.href='/auth.html?next='+encodeURIComponent(location.pathname);return}if(!identity.user)return;const pr=identity.profile||{},base={game_id:game?.id||null,game_slug:'rich-court-king',user_id:identity.user.id,username:pr.username||null,display_name:pr.display_name||null,score,platform_type:'web'};await supabase.from('game_sessions').insert({...base,result:'completed',duration_seconds:60-Math.ceil(time),metadata:{shots,perfects,source:'games/rich-court-king'}});await supabase.from('game_scores').insert({...base,mode:'timing',is_verified:true,anti_cheat_status:'verified',metadata:{shots,perfects,source:'games/rich-court-king'}});await awardXp('rich_court_king_run',{section:'gaming',sourceTable:'games',sourceId:game?.id||null,metadata:{score,perfects}}).catch(()=>{});status('SCORE SAVED',`${score.toLocaleString()} points added to the leaderboard.`);load()}

document.querySelectorAll('[data-action]').forEach(x=>{const a=x.dataset.action;if(a==='shoot'){x.onpointerdown=e=>{e.preventDefault();hold()};x.onpointerup=release;x.onpointercancel=release;x.onpointerleave=()=>{if(charging)release()}}else x.onclick=()=>act(a)});
addEventListener('keydown',e=>{if(e.repeat)return;if(e.code==='Space')hold();else if(e.key==='ArrowLeft')act('left');else if(e.key==='ArrowRight')act('right');else if(e.key.toLowerCase()==='s')act('steal');else if(e.key.toLowerCase()==='b')act('boost')});addEventListener('keyup',e=>{if(e.code==='Space')release()});
$('pauseBtn').onclick=()=>{paused=!paused;$('pauseBtn').textContent=paused?'RESUME':'PAUSE';status(paused?'PAUSED':'BACK IN','Run resumed.')};$('restartBtn').onclick=reset;$('saveBtn').onclick=()=>save(false);
await load();reset();
