import { supabase } from '../../core/supabase/client';
import './meta.css';

type World={id:string;slug:string;title:string;description:string|null;world_type:string;access_type:string;cover_url:string|null;background_url:string|null;visit_count:number|null;like_count:number|null;room_count:number|null;voice_enabled:boolean|null;avatar_required:boolean|null};
type Portal={id:string;world_id:string|null;title:string;destination_type:string;destination_url:string|null;destination_world_id:string|null;icon:string|null;portal_style:string|null;sort_order:number|null};
type Room={id:string;world_id:string|null;title:string;room_type:string;status:string;max_members:number|null;active_members:number|null;cover_url:string|null};
type Message={id:string;room_id:string|null;user_id:string|null;display_name:string|null;username:string|null;body:string;created_at:string};
type Avatar={display_name:string|null;avatar_url:string|null;aura:string|null;rank:string|null;level:number|null};
type Inventory={id:string;equipped:boolean|null;meta_items:{title:string|null;item_type:string|null;rarity:string|null;image_url:string|null}|null};
const esc=(v:string|null|undefined)=>(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]??c));
const routeFor=(p:Portal)=>p.destination_url||({'live':'/live.html','game':'/gaming.html','music':'/music.html','store':'/store.html','gallery':'/gallery.html','world':'/meta.html'}[p.destination_type]??'/portal.html');

export async function mount():Promise<void>{
  const root=document.querySelector<HTMLElement>('#app');if(!root)throw new Error('Missing #app mount');
  const {data:{session}}=await supabase.auth.getSession();if(!session){location.replace('/tap-in.html?next=%2Fmeta.html');return;}
  const [{data:worldRows},{data:portalRows},{data:avatarRow},{data:inventoryRows},{data:likedRows},{data:membershipRows}]=await Promise.all([
    supabase.from('meta_worlds').select('id,slug,title,description,world_type,access_type,cover_url,background_url,visit_count,like_count,room_count,voice_enabled,avatar_required').eq('status','active').order('is_featured',{ascending:false}).order('created_at'),
    supabase.from('meta_portals').select('id,world_id,title,destination_type,destination_url,destination_world_id,icon,portal_style,sort_order').eq('is_active',true).order('sort_order'),
    supabase.from('meta_avatars').select('display_name,avatar_url,aura,rank,level').eq('user_id',session.user.id).maybeSingle(),
    supabase.from('meta_inventory').select('id,equipped,meta_items(title,item_type,rarity,image_url)').eq('user_id',session.user.id).order('unlocked_at',{ascending:false}).limit(12),
    supabase.from('meta_world_likes').select('world_id').eq('user_id',session.user.id),
    supabase.from('meta_room_members').select('room_id,status').eq('user_id',session.user.id)
  ]);
  const worlds=(worldRows??[]) as World[];const portals=(portalRows??[]) as Portal[];const avatar=(avatarRow??{}) as Avatar;const inventory=(inventoryRows??[]) as unknown as Inventory[];
  const liked=new Set((likedRows??[]).map((r:any)=>String(r.world_id)));const joined=new Set((membershipRows??[]).filter((r:any)=>r.status==='active').map((r:any)=>String(r.room_id)));
  let activeWorld=worlds[0]??null;let activeRoom:Room|null=null;let rooms:Room[]=[];let chatChannel:any=null;let roomChannel:any=null;
  root.innerHTML=`<main class="meta-shell"><div class="meta-wrap"><header class="meta-head"><a href="/portal.html">←</a><div><p>RICH BIZNESS UNIVERSE</p><h1>Meta</h1></div><span class="meta-live">WORLD SYNC LIVE</span></header><div class="meta-layout"><section id="stage" class="meta-stage"><div class="meta-scene"><div class="meta-world-ring"></div><div class="meta-world-core"></div><div id="portalNodes" class="meta-portals"></div></div><div class="meta-stage-copy"><div><h2 id="worldTitle">Loading world…</h2><p id="worldDescription"></p><div id="worldBadges" class="meta-badges"></div><div class="meta-actions"><button id="enterWorld" class="meta-btn primary">ENTER WORLD</button><button id="likeWorld" class="meta-btn">♡ LIKE</button><a class="meta-btn" href="/avatar.html">AVATAR LAB</a></div></div></div></section><aside class="meta-side"><section class="meta-panel"><h3>YOUR META IDENTITY</h3><div class="meta-avatar-chip"><img src="${esc(avatar.avatar_url||'/images/brand/Avatar-hero-Banner.png.jpeg')}" alt=""><div><strong>${esc(avatar.display_name||'Rich Traveler')}</strong><span>${esc(avatar.rank||'Traveler')} · Level ${avatar.level??1} · ${esc(avatar.aura||'Green Gold')}</span></div></div></section><section class="meta-panel"><h3>WORLDS</h3><div id="worldList" class="meta-list"></div></section><section class="meta-panel"><h3>ROOMS</h3><div id="roomList" class="meta-list"></div></section><section class="meta-panel chat-panel"><h3 id="chatTitle">ROOM CHAT</h3><div id="chat" class="meta-chat"><div class="meta-card"><p>Join a room to activate chat.</p></div></div><form id="chatForm" class="meta-chat-form"><input id="chatInput" maxlength="1000" placeholder="Send to the room…" disabled><button class="meta-btn primary" disabled>SEND</button></form></section><section class="meta-panel inventory-panel"><h3>INVENTORY</h3><div id="inventory" class="meta-inventory"></div></section><p id="status" class="meta-status"></p></aside></div></div></main>`;
  const stage=document.querySelector<HTMLElement>('#stage')!;const worldTitle=document.querySelector<HTMLElement>('#worldTitle')!;const worldDescription=document.querySelector<HTMLElement>('#worldDescription')!;const worldBadges=document.querySelector<HTMLElement>('#worldBadges')!;const worldList=document.querySelector<HTMLElement>('#worldList')!;const portalNodes=document.querySelector<HTMLElement>('#portalNodes')!;const roomList=document.querySelector<HTMLElement>('#roomList')!;const chat=document.querySelector<HTMLElement>('#chat')!;const chatTitle=document.querySelector<HTMLElement>('#chatTitle')!;const chatForm=document.querySelector<HTMLFormElement>('#chatForm')!;const chatInput=document.querySelector<HTMLInputElement>('#chatInput')!;const status=document.querySelector<HTMLElement>('#status')!;
  const setStatus=(v:string)=>{status.textContent=v;window.setTimeout(()=>{if(status.textContent===v)status.textContent='';},2500)};
  const renderInventory=()=>{document.querySelector<HTMLElement>('#inventory')!.innerHTML=inventory.length?inventory.map(i=>`<div class="meta-item"><strong>${esc(i.meta_items?.title||'Meta Item')}</strong><small>${esc(i.meta_items?.item_type||'collectible')} · ${esc(i.meta_items?.rarity||'common')}${i.equipped?' · EQUIPPED':''}</small></div>`).join(''):'<div class="meta-item"><strong>Inventory ready</strong><small>Unlock items across Meta and Store.</small></div>';};
  const renderWorlds=()=>{worldList.innerHTML=worlds.map(w=>`<button class="meta-card ${activeWorld?.id===w.id?'active':''}" data-world="${w.id}"><div class="meta-row"><h4>${esc(w.title)}</h4><span>${w.visit_count??0}</span></div><p>${esc(w.world_type)} · ${esc(w.access_type)} · ${w.room_count??0} rooms</p></button>`).join('');worldList.querySelectorAll<HTMLButtonElement>('[data-world]').forEach(b=>b.onclick=()=>{const w=worlds.find(x=>x.id===b.dataset.world);if(w)void selectWorld(w);});};
  const renderPortals=()=>{if(!activeWorld){portalNodes.innerHTML='';return;}const rows=portals.filter(p=>!p.world_id||p.world_id===activeWorld!.id);const positions=[[8,18],[72,12],[4,62],[76,60],[38,4],[39,67]];portalNodes.innerHTML=rows.slice(0,6).map((p,i)=>`<button class="meta-portal-node" data-portal="${p.id}" style="left:${positions[i][0]}%;top:${positions[i][1]}%"><div><strong>${esc(p.icon||'◎')}</strong><span>${esc(p.title)}</span></div></button>`).join('');portalNodes.querySelectorAll<HTMLButtonElement>('[data-portal]').forEach(b=>b.onclick=()=>{const p=rows.find(x=>x.id===b.dataset.portal);if(p)location.href=routeFor(p);});};
  const loadRooms=async()=>{if(!activeWorld)return;const {data}=await supabase.from('meta_rooms').select('id,world_id,title,room_type,status,max_members,active_members,cover_url').eq('world_id',activeWorld.id).eq('status','open').order('active_members',{ascending:false}).order('created_at');rooms=(data??[]) as Room[];renderRooms();};
  const renderRooms=()=>{roomList.innerHTML=rooms.length?rooms.map(r=>`<div class="meta-card ${activeRoom?.id===r.id?'active':''}"><div class="meta-row"><h4>${esc(r.title)}</h4><span>${r.active_members??0}/${r.max_members??50}</span></div><p>${esc(r.room_type)} room</p><div class="meta-room-actions"><button class="meta-btn ${joined.has(r.id)?'primary':''}" data-room="${r.id}">${joined.has(r.id)?'OPEN':'JOIN'}</button>${joined.has(r.id)?`<button class="meta-btn" data-leave="${r.id}">LEAVE</button>`:''}</div></div>`).join(''):'<div class="meta-card"><p>No active rooms.</p></div>';roomList.querySelectorAll<HTMLButtonElement>('[data-room]').forEach(b=>b.onclick=()=>{const r=rooms.find(x=>x.id===b.dataset.room);if(r)void joinRoom(r);});roomList.querySelectorAll<HTMLButtonElement>('[data-leave]').forEach(b=>b.onclick=()=>void leaveRoom(String(b.dataset.leave)));};
  const renderWorld=()=>{if(!activeWorld)return;stage.style.setProperty('--meta-bg',activeWorld.background_url||activeWorld.cover_url?`linear-gradient(180deg,rgba(4,12,7,.2),rgba(0,0,0,.92)),url("${activeWorld.background_url||activeWorld.cover_url}")`:'radial-gradient(circle at 50% 36%,rgba(49,255,99,.25),transparent 20%),#061007');worldTitle.textContent=activeWorld.title;worldDescription.textContent=activeWorld.description||'A connected cinematic world inside Rich Bizness.';worldBadges.innerHTML=`<span class="meta-badge">${esc(activeWorld.world_type)}</span><span class="meta-badge">${activeWorld.voice_enabled?'VOICE ON':'VOICE OFF'}</span><span class="meta-badge">${activeWorld.avatar_required?'AVATAR REQUIRED':'OPEN ACCESS'}</span><span class="meta-badge">${activeWorld.visit_count??0} VISITS</span>`;(document.querySelector<HTMLButtonElement>('#likeWorld')!).textContent=liked.has(activeWorld.id)?'♥ LIKED':'♡ LIKE';renderPortals();renderWorlds();};
  const selectWorld=async(w:World)=>{activeWorld=w;activeRoom=null;chatInput.disabled=true;chatForm.querySelector<HTMLButtonElement>('button')!.disabled=true;chatTitle.textContent='ROOM CHAT';chat.innerHTML='<div class="meta-card"><p>Join a room to activate chat.</p></div>';renderWorld();await loadRooms();};
  const loadChat=async()=>{if(!activeRoom)return;const {data}=await supabase.from('meta_chat_messages').select('id,room_id,user_id,display_name,username,body,created_at').eq('room_id',activeRoom.id).order('created_at',{ascending:true}).limit(100);const rows=(data??[]) as Message[];chat.innerHTML=rows.length?rows.map(m=>`<div class="meta-message"><strong>${esc(m.display_name||m.username||'Rich Traveler')}</strong><p>${esc(m.body)}</p></div>`).join(''):'<div class="meta-card"><p>No messages yet.</p></div>';chat.scrollTop=chat.scrollHeight;};
  const joinRoom=async(r:Room)=>{const {error}=await supabase.rpc('rb_join_meta_room',{p_room_id:r.id});if(error){setStatus(error.message);return;}joined.add(r.id);activeRoom=r;chatTitle.textContent=r.title.toUpperCase();chatInput.disabled=false;chatForm.querySelector<HTMLButtonElement>('button')!.disabled=false;renderRooms();await loadChat();if(chatChannel)await supabase.removeChannel(chatChannel);chatChannel=supabase.channel(`meta-chat:${r.id}`).on('postgres_changes',{event:'*',schema:'public',table:'meta_chat_messages',filter:`room_id=eq.${r.id}`},()=>void loadChat()).subscribe();setStatus(`Entered ${r.title}`);};
  const leaveRoom=async(id:string)=>{const {error}=await supabase.rpc('rb_leave_meta_room',{p_room_id:id});if(error){setStatus(error.message);return;}joined.delete(id);if(activeRoom?.id===id){activeRoom=null;chatInput.disabled=true;chatForm.querySelector<HTMLButtonElement>('button')!.disabled=true;chatTitle.textContent='ROOM CHAT';chat.innerHTML='<div class="meta-card"><p>Join a room to activate chat.</p></div>';}renderRooms();setStatus('Left room');};
  document.querySelector<HTMLButtonElement>('#enterWorld')!.onclick=async()=>{if(!activeWorld)return;const {error}=await supabase.rpc('rb_enter_meta_world',{p_world_id:activeWorld.id});if(error){setStatus(error.message);return;}activeWorld.visit_count=(activeWorld.visit_count??0)+1;renderWorld();setStatus('World entered and avatar synced');};
  document.querySelector<HTMLButtonElement>('#likeWorld')!.onclick=async()=>{if(!activeWorld)return;if(liked.has(activeWorld.id)){await supabase.from('meta_world_likes').delete().eq('world_id',activeWorld.id).eq('user_id',session.user.id);liked.delete(activeWorld.id);}else{const {error}=await supabase.from('meta_world_likes').insert({world_id:activeWorld.id,user_id:session.user.id});if(error){setStatus(error.message);return;}liked.add(activeWorld.id);}renderWorld();};
  chatForm.onsubmit=async e=>{e.preventDefault();if(!activeRoom)return;const body=chatInput.value.trim();if(!body)return;const {data:profile}=await supabase.from('profiles').select('username,display_name').eq('id',session.user.id).maybeSingle();const {error}=await supabase.from('meta_chat_messages').insert({room_id:activeRoom.id,world_id:activeRoom.world_id,user_id:session.user.id,username:profile?.username,display_name:profile?.display_name,body,message_type:'chat'});if(error){setStatus(error.message);return;}chatInput.value='';await loadChat();};
  roomChannel=supabase.channel('meta-room-presence').on('postgres_changes',{event:'*',schema:'public',table:'meta_rooms'},()=>void loadRooms()).on('postgres_changes',{event:'*',schema:'public',table:'meta_room_members'},()=>void loadRooms()).subscribe();
  renderInventory();renderWorlds();if(activeWorld){renderWorld();await loadRooms();}
}
