import { getAuthSnapshot } from '../../core/auth/auth-store';
import { ROUTES } from '../../core/config/routes';
import { supabase } from '../../core/supabase/client';
import './meta.css';

type World = { id:string; slug:string; title:string; description:string|null; world_type:string; access_type:string; cover_url:string|null; background_url:string|null; visit_count:number|null; like_count:number|null; room_count:number|null; voice_enabled:boolean|null; avatar_required:boolean|null };
type Portal = { id:string; world_id:string|null; title:string; destination_type:string; destination_url:string|null; destination_world_id:string|null; icon:string|null; portal_style:string|null; sort_order:number|null };
type Room = { id:string; world_id:string|null; title:string; room_type:string; status:string; max_members:number|null; active_members:number|null; cover_url:string|null };
type Message = { id:string; room_id:string|null; user_id:string|null; display_name:string|null; username:string|null; body:string; created_at:string };
type Avatar = { display_name:string|null; avatar_url:string|null; aura:string|null; rank:string|null; level:number|null };
type Profile = { username:string|null; display_name:string|null };
type Inventory = { id:string; equipped:boolean|null; meta_items:{ title:string|null; item_type:string|null; rarity:string|null; image_url:string|null }|null };

const portalRoutes:Record<string,string>={live:ROUTES.live,game:ROUTES.gaming,music:ROUTES.music,store:ROUTES.store,gallery:ROUTES.gallery,world:ROUTES.meta};
const esc=(value:string|null|undefined)=>(value??'').replace(/[&<>'"]/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[character]??character));
const safeAsset=(value:string|null|undefined)=>{try{if(!value)return'';const url=new URL(value,location.origin);return ['http:','https:'].includes(url.protocol)?url.href:'';}catch{return'';}};
const routeFor=(portal:Portal):string=>{if(portal.destination_type==='world'&&portal.destination_world_id)return `${ROUTES.meta}?world=${encodeURIComponent(portal.destination_world_id)}`;try{if(portal.destination_url){const url=new URL(portal.destination_url,location.origin);if(['http:','https:'].includes(url.protocol))return url.href;}}catch{/* invalid destination */}return portalRoutes[portal.destination_type]||ROUTES.portal;};

export async function mount():Promise<void>{
  const root=document.querySelector<HTMLElement>('#app');
  if(!root||root.dataset.metaOwner==='mounted')return;
  root.dataset.metaOwner='mounted';
  const user=getAuthSnapshot().user;
  if(!user){location.replace(`/tap-in.html?next=${encodeURIComponent(ROUTES.meta)}`);return;}

  const results=await Promise.all([
    supabase.from('meta_worlds').select('id,slug,title,description,world_type,access_type,cover_url,background_url,visit_count,like_count,room_count,voice_enabled,avatar_required').eq('status','active').order('is_featured',{ascending:false}).order('created_at'),
    supabase.from('meta_portals').select('id,world_id,title,destination_type,destination_url,destination_world_id,icon,portal_style,sort_order').eq('is_active',true).order('sort_order'),
    supabase.from('meta_avatars').select('display_name,avatar_url,aura,rank,level').eq('user_id',user.id).maybeSingle(),
    supabase.from('profiles').select('username,display_name').eq('id',user.id).maybeSingle(),
    supabase.from('meta_inventory').select('id,equipped,meta_items(title,item_type,rarity,image_url)').eq('user_id',user.id).order('unlocked_at',{ascending:false}).limit(12),
    supabase.from('meta_world_likes').select('world_id').eq('user_id',user.id),
    supabase.from('meta_room_members').select('room_id,status').eq('user_id',user.id)
  ]);
  const failed=results.find(result=>result.error);
  if(failed?.error){root.innerHTML=`<main class="meta-fail"><a href="${ROUTES.portal}">← PORTAL</a><small>META ENGINE</small><h1>WORLD SYNC OFFLINE</h1><p>${esc(failed.error.message)}</p></main>`;root.dataset.metaOwner='';return;}

  const [worldResult,portalResult,avatarResult,profileResult,inventoryResult,likedResult,membershipResult]=results;
  const worlds=(worldResult.data??[]) as World[];
  const portals=(portalResult.data??[]) as Portal[];
  const avatar=(avatarResult.data??{}) as Avatar;
  const profile=(profileResult.data??{}) as Profile;
  const inventory=(inventoryResult.data??[]) as unknown as Inventory[];
  const liked=new Set((likedResult.data??[]).map((row:any)=>String(row.world_id)));
  const joined=new Set((membershipResult.data??[]).filter((row:any)=>row.status==='active').map((row:any)=>String(row.room_id)));
  const requestedWorld=new URLSearchParams(location.search).get('world');
  let activeWorld=worlds.find(world=>world.id===requestedWorld||world.slug===requestedWorld)??worlds[0]??null;
  let activeRoom:Room|null=null;
  let rooms:Room[]=[];
  let chatChannel:any=null;
  let roomChannel:any=null;
  let destroyed=false;

  root.innerHTML=`<main class="meta-shell"><div class="meta-atmosphere" aria-hidden="true"><i></i><i></i><i></i></div><div class="meta-wrap"><header class="meta-head"><a href="${ROUTES.portal}" aria-label="Back to Portal">←</a><div><p>RICH BIZNESS UNIVERSE</p><h1>Meta World Command</h1></div><span class="meta-live"><i></i> WORLD SYNC LIVE</span></header><div class="meta-layout"><section id="stage" class="meta-stage"><div class="meta-scene" aria-hidden="true"><div class="meta-world-grid"></div><div class="meta-world-ring"></div><div class="meta-world-ring secondary"></div><div class="meta-world-core"></div><div id="portalNodes" class="meta-portals"></div></div><div class="meta-stage-copy"><div><small class="meta-kicker">ACTIVE DIMENSION</small><h2 id="worldTitle">Loading world…</h2><p id="worldDescription"></p><div id="worldBadges" class="meta-badges"></div><div class="meta-actions"><button id="enterWorld" class="meta-btn primary">ENTER WORLD</button><button id="likeWorld" class="meta-btn">♡ LIKE</button><a class="meta-btn" href="${ROUTES.avatar}">CHOOSE AVATAR</a><a class="meta-btn" href="${ROUTES.avatarCharacters}">3D LOBBY</a></div></div></div></section><aside class="meta-side"><section class="meta-panel identity-panel"><h3>YOUR META IDENTITY</h3><div class="meta-avatar-chip"><img src="${esc(safeAsset(avatar.avatar_url)||'/images/brand/Avatar-hero-Banner.png.jpeg')}" alt="Avatar for ${esc(avatar.display_name||profile.display_name||profile.username||'Rich Traveler')}" loading="lazy" decoding="async"><div><strong>${esc(avatar.display_name||profile.display_name||profile.username||'Rich Traveler')}</strong><span>${esc(avatar.rank||'Traveler')} · Level ${avatar.level??1}</span><em>${esc(avatar.aura||'Emerald Gold')} aura</em></div></div></section><section class="meta-panel worlds-panel"><h3>WORLDS <span>${worlds.length}</span></h3><div id="worldList" class="meta-list"></div></section><section class="meta-panel rooms-panel"><h3>ROOMS</h3><div id="roomList" class="meta-list"></div></section><section class="meta-panel chat-panel"><h3 id="chatTitle">ROOM CHAT</h3><div id="chat" class="meta-chat" aria-live="polite"><div class="meta-card"><p>Join a room to activate chat.</p></div></div><form id="chatForm" class="meta-chat-form"><input id="chatInput" maxlength="1000" autocomplete="off" placeholder="Send to the room…" disabled><button class="meta-btn primary" disabled>SEND</button></form></section><section class="meta-panel inventory-panel"><h3>INVENTORY</h3><div id="inventory" class="meta-inventory"></div></section><p id="status" class="meta-status" aria-live="polite"></p></aside></div></div></main>`;

  const stage=root.querySelector<HTMLElement>('#stage')!,worldTitle=root.querySelector<HTMLElement>('#worldTitle')!,worldDescription=root.querySelector<HTMLElement>('#worldDescription')!,worldBadges=root.querySelector<HTMLElement>('#worldBadges')!,worldList=root.querySelector<HTMLElement>('#worldList')!,portalNodes=root.querySelector<HTMLElement>('#portalNodes')!,roomList=root.querySelector<HTMLElement>('#roomList')!,chat=root.querySelector<HTMLElement>('#chat')!,chatTitle=root.querySelector<HTMLElement>('#chatTitle')!,chatForm=root.querySelector<HTMLFormElement>('#chatForm')!,chatInput=root.querySelector<HTMLInputElement>('#chatInput')!,status=root.querySelector<HTMLElement>('#status')!,sendButton=chatForm.querySelector<HTMLButtonElement>('button')!,enterButton=root.querySelector<HTMLButtonElement>('#enterWorld')!,likeButton=root.querySelector<HTMLButtonElement>('#likeWorld')!;
  let statusTimer=0;
  const setStatus=(value:string)=>{if(destroyed)return;window.clearTimeout(statusTimer);status.textContent=value;statusTimer=window.setTimeout(()=>{if(!destroyed&&status.textContent===value)status.textContent='';},3200);};
  const renderInventory=()=>{root.querySelector<HTMLElement>('#inventory')!.innerHTML=inventory.length?inventory.map(item=>`<article class="meta-item ${item.equipped?'equipped':''}"><strong>${esc(item.meta_items?.title||'Meta Item')}</strong><small>${esc(item.meta_items?.item_type||'collectible')} · ${esc(item.meta_items?.rarity||'common')}${item.equipped?' · EQUIPPED':''}</small></article>`).join(''):'<article class="meta-item"><strong>Inventory ready</strong><small>Unlock items across Meta and Store.</small></article>';};
  const renderWorlds=()=>{worldList.innerHTML=worlds.length?worlds.map(world=>`<button class="meta-card ${activeWorld?.id===world.id?'active':''}" data-world="${world.id}" aria-pressed="${activeWorld?.id===world.id}"><div class="meta-row"><h4>${esc(world.title)}</h4><span>${world.visit_count??0}</span></div><p>${esc(world.world_type)} · ${esc(world.access_type)} · ${world.room_count??0} rooms</p></button>`).join(''):'<div class="meta-card"><p>No active worlds are available yet.</p></div>';worldList.querySelectorAll<HTMLButtonElement>('[data-world]').forEach(button=>button.onclick=()=>{const world=worlds.find(item=>item.id===button.dataset.world);if(world)void selectWorld(world);});};
  const renderPortals=()=>{if(!activeWorld){portalNodes.innerHTML='';return;}const rows=portals.filter(portal=>!portal.world_id||portal.world_id===activeWorld!.id);const positions:Array<[number,number]>=[[7,18],[72,12],[3,61],[76,59],[39,2],[40,68]];portalNodes.innerHTML=rows.slice(0,6).map((portal,index)=>{const position=positions[index]??[50,50];return `<button class="meta-portal-node" data-portal="${portal.id}" style="left:${position[0]}%;top:${position[1]}%"><strong>${esc(portal.icon||'◎')}</strong><span>${esc(portal.title)}</span></button>`;}).join('');portalNodes.querySelectorAll<HTMLButtonElement>('[data-portal]').forEach(button=>button.onclick=()=>{const portal=rows.find(item=>item.id===button.dataset.portal);if(portal)location.href=routeFor(portal);});};
  const renderRooms=()=>{roomList.innerHTML=rooms.length?rooms.map(room=>`<article class="meta-card ${activeRoom?.id===room.id?'active':''}"><div class="meta-row"><h4>${esc(room.title)}</h4><span>${room.active_members??0}/${room.max_members??50}</span></div><p>${esc(room.room_type)} room</p><div class="meta-room-actions"><button class="meta-btn ${joined.has(room.id)?'primary':''}" data-room="${room.id}">${joined.has(room.id)?'OPEN':'JOIN'}</button>${joined.has(room.id)?`<button class="meta-btn" data-leave="${room.id}">LEAVE</button>`:''}</div></article>`).join(''):'<div class="meta-card"><p>No active rooms in this world.</p></div>';roomList.querySelectorAll<HTMLButtonElement>('[data-room]').forEach(button=>button.onclick=()=>{const room=rooms.find(item=>item.id===button.dataset.room);if(room)void joinRoom(room);});roomList.querySelectorAll<HTMLButtonElement>('[data-leave]').forEach(button=>button.onclick=()=>void leaveRoom(String(button.dataset.leave)));};
  const renderWorld=()=>{if(!activeWorld){worldTitle.textContent='No active worlds';worldDescription.textContent='Create or activate a Meta world to begin.';enterButton.disabled=true;likeButton.disabled=true;return;}const artwork=safeAsset(activeWorld.background_url||activeWorld.cover_url);stage.style.setProperty('--meta-bg',artwork?`linear-gradient(180deg,rgba(4,12,7,.1),rgba(0,0,0,.93)),url("${artwork.replace(/["\\]/g,'')}")`:'radial-gradient(circle at 50% 36%,rgba(49,255,99,.25),transparent 20%),#061007');worldTitle.textContent=activeWorld.title;worldDescription.textContent=activeWorld.description||'A connected cinematic world inside Rich Bizness.';worldBadges.innerHTML=`<span class="meta-badge">${esc(activeWorld.world_type)}</span><span class="meta-badge">${activeWorld.voice_enabled?'VOICE ON':'VOICE OFF'}</span><span class="meta-badge">${activeWorld.avatar_required?'AVATAR REQUIRED':'OPEN ACCESS'}</span><span class="meta-badge">${activeWorld.visit_count??0} VISITS</span>`;likeButton.textContent=liked.has(activeWorld.id)?'♥ LIKED':'♡ LIKE';enterButton.disabled=false;likeButton.disabled=false;renderPortals();renderWorlds();};
  const loadRooms=async()=>{if(!activeWorld||destroyed)return;const selectedId=activeWorld.id;const{data,error}=await supabase.from('meta_rooms').select('id,world_id,title,room_type,status,max_members,active_members,cover_url').eq('world_id',selectedId).eq('status','open').order('active_members',{ascending:false}).order('created_at');if(destroyed||activeWorld?.id!==selectedId)return;if(error){setStatus(error.message);return;}rooms=(data??[]) as Room[];renderRooms();};
  const bindRoomChannel=async()=>{if(roomChannel){await supabase.removeChannel(roomChannel);roomChannel=null;}if(!activeWorld||destroyed)return;roomChannel=supabase.channel(`meta-world:${activeWorld.id}:${user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'meta_rooms',filter:`world_id=eq.${activeWorld.id}`},()=>void loadRooms()).on('postgres_changes',{event:'*',schema:'public',table:'meta_room_members',filter:`user_id=eq.${user.id}`},()=>void loadRooms()).subscribe();};
  const selectWorld=async(world:World)=>{activeWorld=world;activeRoom=null;history.replaceState(null,'',`${location.pathname}?world=${encodeURIComponent(world.slug||world.id)}`);chatInput.disabled=true;sendButton.disabled=true;chatTitle.textContent='ROOM CHAT';chat.innerHTML='<div class="meta-card"><p>Join a room to activate chat.</p></div>';if(chatChannel){await supabase.removeChannel(chatChannel);chatChannel=null;}renderWorld();await Promise.all([loadRooms(),bindRoomChannel()]);};
  const loadChat=async()=>{if(!activeRoom||destroyed)return;const roomId=activeRoom.id;const{data,error}=await supabase.from('meta_chat_messages').select('id,room_id,user_id,display_name,username,body,created_at').eq('room_id',roomId).order('created_at',{ascending:true}).limit(100);if(destroyed||activeRoom?.id!==roomId)return;if(error){setStatus(error.message);return;}const rows=(data??[]) as Message[];chat.innerHTML=rows.length?rows.map(message=>`<article class="meta-message ${message.user_id===user.id?'mine':''}"><strong>${esc(message.display_name||message.username||'Rich Traveler')}</strong><p>${esc(message.body)}</p></article>`).join(''):'<div class="meta-card"><p>No messages yet.</p></div>';chat.scrollTop=chat.scrollHeight;};
  const joinRoom=async(room:Room)=>{const{error}=await supabase.rpc('rb_join_meta_room',{p_room_id:room.id});if(error){setStatus(error.message);return;}joined.add(room.id);activeRoom=room;chatTitle.textContent=room.title.toUpperCase();chatInput.disabled=false;sendButton.disabled=false;renderRooms();await loadChat();if(chatChannel)await supabase.removeChannel(chatChannel);chatChannel=supabase.channel(`meta-chat:${room.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'meta_chat_messages',filter:`room_id=eq.${room.id}`},()=>void loadChat()).subscribe();setStatus(`Entered ${room.title}`);};
  const leaveRoom=async(id:string)=>{const{error}=await supabase.rpc('rb_leave_meta_room',{p_room_id:id});if(error){setStatus(error.message);return;}joined.delete(id);if(activeRoom?.id===id){activeRoom=null;chatInput.disabled=true;sendButton.disabled=true;chatTitle.textContent='ROOM CHAT';chat.innerHTML='<div class="meta-card"><p>Join a room to activate chat.</p></div>';if(chatChannel){await supabase.removeChannel(chatChannel);chatChannel=null;}}renderRooms();setStatus('Left room');};

  enterButton.onclick=async()=>{if(!activeWorld||enterButton.disabled)return;enterButton.disabled=true;const{data,error}=await supabase.rpc('rb_enter_meta_world',{p_world_id:activeWorld.id});enterButton.disabled=false;if(error){setStatus(error.message);return;}if((data as any)?.counted)activeWorld.visit_count=(activeWorld.visit_count??0)+1;renderWorld();setStatus((data as any)?.counted?'World entered and avatar synced':'Avatar re-synced to your active world');};
  likeButton.onclick=async()=>{if(!activeWorld||likeButton.disabled)return;likeButton.disabled=true;const isLiked=liked.has(activeWorld.id);const query=isLiked?supabase.from('meta_world_likes').delete().eq('world_id',activeWorld.id).eq('user_id',user.id):supabase.from('meta_world_likes').insert({world_id:activeWorld.id,user_id:user.id});const{error}=await query;likeButton.disabled=false;if(error){setStatus(error.message);return;}if(isLiked)liked.delete(activeWorld.id);else liked.add(activeWorld.id);renderWorld();};
  chatForm.onsubmit=async event=>{event.preventDefault();if(!activeRoom)return;const body=chatInput.value.trim();if(!body)return;sendButton.disabled=true;const{error}=await supabase.rpc('rb_send_meta_message',{p_room_id:activeRoom.id,p_body:body});sendButton.disabled=false;if(error){setStatus(error.message);return;}chatInput.value='';await loadChat();};

  const cleanup=()=>{if(destroyed)return;destroyed=true;window.clearTimeout(statusTimer);if(chatChannel)void supabase.removeChannel(chatChannel);if(roomChannel)void supabase.removeChannel(roomChannel);chatChannel=null;roomChannel=null;root.dataset.metaOwner='';};
  window.addEventListener('pagehide',cleanup,{once:true});
  renderInventory();renderWorlds();renderWorld();if(activeWorld)await Promise.all([loadRooms(),bindRoomChannel()]);
}
