import { supabase } from '../../core/supabase/client';
import './store.css';

type Product={id:string;seller_id:string|null;title:string;description:string|null;category:string|null;product_type:string|null;fulfillment_type:string|null;price_cents:number|null;currency:string|null;image_url:string|null;cover_url:string|null;media_url:string|null;preview_url:string|null;inventory_count:number|null;is_digital:boolean|null;is_local:boolean|null;is_featured:boolean|null;city:string|null;state:string|null;location_label:string|null;views:number|null;likes:number|null;sales_count:number|null;marketing_emoji:string|null;created_at:string|null;seller_name:string|null;seller_avatar_url:string|null;seller_rank:string|null};
type CartRow={product_id:string;quantity:number;price_cents:number;currency:string};
const esc=(v:string|null|undefined)=>(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]??c));
const money=(c:number|null,currency='usd')=>new Intl.NumberFormat('en-US',{style:'currency',currency:(currency||'usd').toUpperCase()}).format((c??0)/100);

export async function mount():Promise<void>{
 const root=document.querySelector<HTMLElement>('#app');if(!root)throw new Error('Missing #app mount');
 const {data:{session}}=await supabase.auth.getSession();
 root.innerHTML=`<main class="store-shell"><div class="store-wrap"><header class="store-head"><a href="/portal.html">←</a><div><p>RICH BIZNESS MARKETPLACE</p><h1>Store</h1></div><button id="cartPill" class="store-cart-pill">CART · 0</button></header><section class="store-hero"><div class="store-hero-copy"><span>SELL · SHOP · UNLOCK</span><h2>Rich Drops Only.</h2><p>Physical products, digital unlocks, creator exclusives, tickets, collectibles, game items, and Meta inventory in one connected marketplace.</p></div></section><section class="store-toolbar"><input id="searchInput" class="store-search" placeholder="Search products, sellers, categories..."><div id="filters" class="store-filters"></div></section><section id="grid" class="store-grid"></section><p id="status" class="store-status"></p></div></main><div id="drawer" class="store-drawer"><section class="store-modal"><div id="modalContent"></div></section></div>`;
 const grid=document.querySelector<HTMLElement>('#grid')!;const filters=document.querySelector<HTMLElement>('#filters')!;const status=document.querySelector<HTMLElement>('#status')!;const drawer=document.querySelector<HTMLElement>('#drawer')!;const modal=document.querySelector<HTMLElement>('#modalContent')!;const cartPill=document.querySelector<HTMLButtonElement>('#cartPill')!;const search=document.querySelector<HTMLInputElement>('#searchInput')!;
 let products:Product[]=[];let cart=new Map<string,CartRow>();let liked=new Set<string>();let filter='all';let query='';let active:Product|null=null;let commentChannel:any=null;
 const note=(v:string)=>{status.textContent=v;setTimeout(()=>{if(status.textContent===v)status.textContent='';},2200)};
 const loadUserState=async()=>{if(!session)return;const [{data:c},{data:l}]=await Promise.all([supabase.from('store_cart_items').select('product_id,quantity,price_cents,currency').eq('user_id',session.user.id),supabase.from('product_likes').select('product_id').eq('user_id',session.user.id)]);cart=new Map((c??[]).map((r:any)=>[String(r.product_id),r]));liked=new Set((l??[]).map((r:any)=>String(r.product_id)));renderCartCount();};
 const renderCartCount=()=>{const n=[...cart.values()].reduce((a,b)=>a+Number(b.quantity||0),0);cartPill.textContent=`CART · ${n}`;};
 const categories=()=>['all','featured','digital','local',...Array.from(new Set(products.map(p=>p.category||'general')))].filter((v,i,a)=>a.indexOf(v)===i);
 const renderFilters=()=>{filters.innerHTML=categories().map(v=>`<button class="store-chip ${filter===v?'active':''}" data-filter="${esc(v)}">${v.toUpperCase()}</button>`).join('');filters.querySelectorAll<HTMLButtonElement>('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter!;renderFilters();renderGrid();});};
 const visible=()=>products.filter(p=>{const matches=filter==='all'||filter===p.category||(filter==='featured'&&p.is_featured)||(filter==='digital'&&p.is_digital)||(filter==='local'&&p.is_local);const hay=`${p.title} ${p.description??''} ${p.category??''} ${p.seller_name??''}`.toLowerCase();return matches&&hay.includes(query.toLowerCase());});
 const renderGrid=()=>{const rows=visible();grid.innerHTML=rows.length?rows.map(p=>`<article class="store-card"><div class="store-media"><img src="${esc(p.image_url||p.cover_url||'/images/brand/IMG_5997.png')}" alt=""><span class="store-badge">${esc(p.marketing_emoji||'💨')} ${esc(p.product_type||'DROP')}</span><button class="store-like ${liked.has(p.id)?'active':''}" data-like="${p.id}">${liked.has(p.id)?'♥':'♡'}</button></div><div class="store-card-body"><div class="store-seller"><img src="${esc(p.seller_avatar_url||'/images/brand/Avatar-hero-Banner.png.jpeg')}" alt=""><div><strong>${esc(p.seller_name||'Rich Seller')}</strong><small>${esc(p.seller_rank||'Seller')}</small></div></div><h3>${esc(p.title)}</h3><p>${esc((p.description||'').slice(0,120))}</p><div class="store-price-row"><span class="store-price">${money(p.price_cents,p.currency||'usd')}</span><span class="store-meta">${p.views??0} views · ${p.likes??0} likes</span></div><div class="store-actions"><button class="store-btn primary" data-add="${p.id}">${cart.has(p.id)?'IN CART':'ADD TO CART'}</button><button class="store-btn" data-open="${p.id}">VIEW</button></div></div></article>`).join(''):'<div class="store-empty">No products match this lane yet.</div>';grid.querySelectorAll<HTMLButtonElement>('[data-open]').forEach(b=>b.onclick=()=>{const p=products.find(x=>x.id===b.dataset.open);if(p)void openProduct(p);});grid.querySelectorAll<HTMLButtonElement>('[data-add]').forEach(b=>b.onclick=()=>void setCart(b.dataset.add!,1));grid.querySelectorAll<HTMLButtonElement>('[data-like]').forEach(b=>b.onclick=()=>void toggleLike(b.dataset.like!));};
 const setCart=async(id:string,qty:number)=>{if(!session){location.href='/tap-in.html?next=%2Fstore.html';return;}const {data,error}=await supabase.rpc('rb_store_cart_set',{p_product_id:id,p_quantity:qty});if(error){note(error.message);return;}if(qty<=0)cart.delete(id);else cart.set(id,{product_id:id,quantity:qty,price_cents:Number((data as any)?.price_cents??products.find(p=>p.id===id)?.price_cents??0),currency:String((data as any)?.currency??'usd')});renderCartCount();renderGrid();if(active?.id===id)void openProduct(active);note(qty<=0?'Removed from cart.':'Cart updated.');};
 const toggleLike=async(id:string)=>{if(!session){location.href='/tap-in.html?next=%2Fstore.html';return;}const {data,error}=await supabase.rpc('rb_store_toggle_like',{p_product_id:id});if(error){note(error.message);return;}const isLiked=Boolean((data as any)?.liked);isLiked?liked.add(id):liked.delete(id);const p=products.find(x=>x.id===id);if(p)p.likes=Number((data as any)?.count??p.likes??0);renderGrid();};
 const loadComments=async()=>{if(!active)return;const {data}=await supabase.from('store_comments').select('id,body,created_at,user_id,profiles(display_name,username)').eq('product_id',active.id).order('created_at',{ascending:true}).limit(100);const el=document.querySelector<HTMLElement>('#storeComments');if(el)el.innerHTML=(data??[]).length?(data as any[]).map(c=>`<div class="store-comment"><p>${esc(c.body)}</p><small>${esc(c.profiles?.display_name||c.profiles?.username||'Rich Member')}</small></div>`).join(''):'<div class="store-empty">No comments yet.</div>';};
 const openProduct=async(p:Product)=>{active=p;drawer.classList.add('open');void supabase.rpc('rb_store_record_view',{p_product_id:p.id,p_anonymous_id:session?null:crypto.randomUUID()});const c=cart.get(p.id);modal.innerHTML=`<div class="store-modal-media"><img src="${esc(p.cover_url||p.image_url||'/images/brand/IMG_5997.png')}" alt=""></div><div class="store-modal-body"><div class="store-modal-head"><div><small>${esc(p.category||'drop')} · ${esc(p.product_type||'product')}</small><h2>${esc(p.title)}</h2></div><button id="closeStore" class="store-close">×</button></div><div class="store-detail-grid"><section class="store-panel"><h3>About this drop</h3><p>${esc(p.description||'No description yet.')}</p><p><strong>${money(p.price_cents,p.currency||'usd')}</strong> · ${esc(p.fulfillment_type||'fulfillment')}</p><p>${p.is_local?`Local · ${esc(p.location_label||[p.city,p.state].filter(Boolean).join(', '))}`:''}${p.is_digital?' Digital unlock':''}</p><button id="detailAdd" class="store-btn primary">${c?'UPDATE CART':'ADD TO CART'}</button><section class="store-panel" style="margin-top:14px"><h3>Comments</h3><div id="storeComments" class="store-comments"></div><form id="storeCommentForm" class="store-comment-form"><input id="storeCommentInput" maxlength="2000" placeholder="Ask about this product..."><button class="store-btn primary">POST</button></form></section></section><aside class="store-panel"><h3>Seller</h3><div class="store-seller"><img src="${esc(p.seller_avatar_url)}" alt=""><div><strong>${esc(p.seller_name)}</strong><small>${esc(p.seller_rank)}</small></div></div><p>${p.inventory_count??0} available</p><p>${p.sales_count??0} sold · ${p.likes??0} likes</p></aside></div></div>`;document.querySelector<HTMLButtonElement>('#closeStore')!.onclick=()=>drawer.classList.remove('open');document.querySelector<HTMLButtonElement>('#detailAdd')!.onclick=()=>void setCart(p.id,(c?.quantity??0)+1);document.querySelector<HTMLFormElement>('#storeCommentForm')!.onsubmit=async e=>{e.preventDefault();if(!session){location.href='/tap-in.html?next=%2Fstore.html';return;}const input=document.querySelector<HTMLInputElement>('#storeCommentInput')!;const body=input.value.trim();if(!body)return;const {error}=await supabase.from('store_comments').insert({product_id:p.id,user_id:session.user.id,body});if(error){note(error.message);return;}input.value='';await loadComments();};await loadComments();if(commentChannel)await supabase.removeChannel(commentChannel);commentChannel=supabase.channel(`store-comments:${p.id}`).on('postgres_changes',{event:'*',schema:'public',table:'store_comments',filter:`product_id=eq.${p.id}`},()=>void loadComments()).subscribe();};
 const openCart=()=>{drawer.classList.add('open');const rows=[...cart.values()];const total=rows.reduce((a,b)=>a+b.price_cents*b.quantity,0);modal.innerHTML=`<div class="store-modal-body"><div class="store-modal-head"><div><small>RICH CART</small><h2>Your Bag</h2></div><button id="closeStore" class="store-close">×</button></div><div class="store-cart-list">${rows.length?rows.map(r=>{const p=products.find(x=>x.id===r.product_id);return `<div class="store-cart-item"><div><strong>${esc(p?.title||'Product')}</strong><small>${money(r.price_cents,r.currency)}</small></div><div class="store-qty"><button data-minus="${r.product_id}">−</button><span>${r.quantity}</span><button data-plus="${r.product_id}">+</button></div></div>`}).join(''):'<div class="store-empty">Your cart is empty.</div>'}</div><div class="store-price-row"><span>Total</span><span class="store-price">${money(total,'usd')}</span></div><button class="store-btn primary" style="width:100%;margin-top:14px" disabled>CHECKOUT CONNECTION PENDING</button></div>`;document.querySelector<HTMLButtonElement>('#closeStore')!.onclick=()=>drawer.classList.remove('open');modal.querySelectorAll<HTMLButtonElement>('[data-minus]').forEach(b=>b.onclick=()=>{const r=cart.get(b.dataset.minus!);void setCart(b.dataset.minus!,Math.max(0,(r?.quantity??1)-1)).then(openCart);});modal.querySelectorAll<HTMLButtonElement>('[data-plus]').forEach(b=>b.onclick=()=>{const r=cart.get(b.dataset.plus!);void setCart(b.dataset.plus!,(r?.quantity??0)+1).then(openCart);});};
 search.oninput=()=>{query=search.value.trim();renderGrid();};cartPill.onclick=openCart;drawer.onclick=e=>{if(e.target===drawer)drawer.classList.remove('open');};
 await loadUserState();const {data,error}=await supabase.rpc('rb_store_catalog',{p_limit:100});if(error){grid.innerHTML=`<div class="store-empty">${esc(error.message)}</div>`;return;}products=(data??[]) as unknown as Product[];renderFilters();renderGrid();
}
