import { getAuthSnapshot } from '../../core/auth/auth-store';
import { supabase } from '../../core/supabase/client';
import './store.css';

type Product={id:string;seller_id:string|null;title:string;description:string|null;category:string|null;product_type:string|null;fulfillment_type:string|null;price_cents:number|null;currency:string|null;image_url:string|null;cover_url:string|null;media_url:string|null;preview_url:string|null;inventory_count:number|null;is_digital:boolean|null;is_local:boolean|null;is_featured:boolean|null;city:string|null;state:string|null;location_label:string|null;views:number|null;likes:number|null;sales_count:number|null;marketing_emoji:string|null;created_at:string|null;seller_name:string|null;seller_avatar_url:string|null;seller_rank:string|null};
type CartRow={product_id:string;quantity:number;price_cents:number;currency:string};
type Row=Record<string,any>;
type Channel=ReturnType<typeof supabase.channel>;
const esc=(v:unknown)=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]??c));
const money=(c:unknown,currency='usd')=>new Intl.NumberFormat('en-US',{style:'currency',currency:String(currency||'usd').toUpperCase()}).format(Number(c??0)/100);
const art=(p:Product)=>p.image_url||p.cover_url||'/images/brand/IMG_5997.png';

export async function mount():Promise<void>{
 const root=document.querySelector<HTMLElement>('#app');if(!root)throw new Error('Missing #app mount');
 if(root.dataset.mounted==='store')return;root.dataset.mounted='store';
 const auth=getAuthSnapshot(),user=auth.user,userId=user?.id??null;
 const anonId=localStorage.getItem('rb_store_anon')||crypto.randomUUID();localStorage.setItem('rb_store_anon',anonId);
 root.innerHTML=`<main class="store-shell"><div class="store-wrap"><header class="store-head"><a href="/portal.html">←</a><div><p>RICH BIZNESS MARKETPLACE</p><h1>Store</h1></div><button id="cartPill" class="store-cart-pill">CART · 0</button></header><section class="store-network"><a href="/creator.html">CREATOR</a><a href="/upload.html?route=store-product">SELL A DROP</a><a href="/feed.html?section=store">STORE FEED</a><a href="/watch.html?store=1">WATCH DROPS</a><a href="/gaming.html">GAME STORE</a><a href="/messages.html">RICH-DM</a><a href="/profile.html${userId?`?id=${encodeURIComponent(userId)}`:''}">PROFILE</a></section><section class="store-hero"><div class="store-hero-copy"><span>SELL · SHOP · UNLOCK</span><h2>Rich Drops Only.</h2><p>Physical products, digital unlocks, creator exclusives, tickets, collectibles, game items and Meta inventory in one connected marketplace.</p></div></section><section id="storeMetrics" class="store-metrics"></section><section class="store-toolbar"><input id="searchInput" class="store-search" placeholder="Search products, sellers, categories..."><div id="filters" class="store-filters"></div></section><section id="grid" class="store-grid"></section><p id="status" class="store-status" role="status"></p></div></main><div id="drawer" class="store-drawer"><section class="store-modal"><div id="modalContent"></div></section></div>`;
 const grid=document.querySelector<HTMLElement>('#grid')!,filters=document.querySelector<HTMLElement>('#filters')!,status=document.querySelector<HTMLElement>('#status')!,drawer=document.querySelector<HTMLElement>('#drawer')!,modal=document.querySelector<HTMLElement>('#modalContent')!,cartPill=document.querySelector<HTMLButtonElement>('#cartPill')!,search=document.querySelector<HTMLInputElement>('#searchInput')!,metrics=document.querySelector<HTMLElement>('#storeMetrics')!;
 let products:Product[]=[],cart=new Map<string,CartRow>(),liked=new Set<string>(),orders:Row[]=[],seller:Row|null=null,balance:Row|null=null,filter='all',query='',active:Product|null=null,commentChannel:Channel|null=null,catalogChannel:Channel|null=null,loading=false,pending=false,commentLoading=false,disposed=false,statusTimer:number|undefined;
 const note=(v:string)=>{status.textContent=v;clearTimeout(statusTimer);statusTimer=window.setTimeout(()=>{if(status.textContent===v)status.textContent='';},2600)};
 const loadUserState=async()=>{if(!userId){cart.clear();liked.clear();orders=[];seller=null;balance=null;renderCartCount();return;}const [{data:c},{data:l},{data:o},{data:s},{data:b}]=await Promise.all([supabase.from('store_cart_items').select('product_id,quantity,price_cents,currency').eq('user_id',userId),supabase.from('product_likes').select('product_id').eq('user_id',userId),supabase.from('store_orders').select('*').or(`buyer_id.eq.${userId},seller_id.eq.${userId}`).order('created_at',{ascending:false}).limit(20),supabase.from('store_seller_profiles').select('*').eq('user_id',userId).maybeSingle(),supabase.from('creator_available_balances').select('*').eq('artist_user_id',userId).maybeSingle()]);cart=new Map((c??[]).map((r:any)=>[String(r.product_id),r]));liked=new Set((l??[]).map((r:any)=>String(r.product_id)));orders=(o??[]) as Row[];seller=(s??null) as Row|null;balance=(b??null) as Row|null;renderCartCount();};
 const renderCartCount=()=>{const n=[...cart.values()].reduce((a,b)=>a+Number(b.quantity||0),0);cartPill.textContent=`CART · ${n}`;};
 const renderMetrics=()=>{metrics.innerHTML=`<article><small>MARKET DROPS</small><strong>${products.length}</strong><span>Connected products</span></article><article><small>MY ORDERS</small><strong>${orders.length}</strong><span>${user?'Buyer + seller activity':'Tap In to sync'}</span></article><article><small>AVAILABLE</small><strong>${money(balance?.available_cents??0,balance?.currency??'usd')}</strong><span>Creator balance</span></article><article><small>SELLER</small><strong>${seller?'ACTIVE':'READY'}</strong><span>${seller?.store_name||'Build your storefront'}</span></article>`;};
 const categories=()=>['all','featured','digital','local',...Array.from(new Set(products.map(p=>p.category||'general')))].filter((v,i,a)=>a.indexOf(v)===i);
 const renderFilters=()=>{filters.innerHTML=categories().map(v=>`<button class="store-chip ${filter===v?'active':''}" data-filter="${esc(v)}">${esc(v).toUpperCase()}</button>`).join('');filters.querySelectorAll<HTMLButtonElement>('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter||'all';renderFilters();renderGrid();});};
 const visible=()=>products.filter(p=>{const matches=filter==='all'||filter===p.category||(filter==='featured'&&p.is_featured)||(filter==='digital'&&p.is_digital)||(filter==='local'&&p.is_local);return matches&&`${p.title} ${p.description??''} ${p.category??''} ${p.seller_name??''}`.toLowerCase().includes(query.toLowerCase());});
 const renderGrid=()=>{const rows=visible();grid.innerHTML=rows.length?rows.map(p=>`<article class="store-card"><div class="store-media"><img src="${esc(art(p))}" alt=""><span class="store-badge">${esc(p.marketing_emoji||'💨')} ${esc(p.product_type||'DROP')}</span><button class="store-like ${liked.has(p.id)?'active':''}" data-like="${p.id}">${liked.has(p.id)?'♥':'♡'}</button></div><div class="store-card-body"><div class="store-seller"><img src="${esc(p.seller_avatar_url||'/brand/icons/profile-placeholder.svg')}" alt=""><div><strong>${esc(p.seller_name||'Rich Seller')}</strong><small>${esc(p.seller_rank||'Seller')}</small></div></div><h3>${esc(p.title)}</h3><p>${esc((p.description||'').slice(0,120))}</p><div class="store-price-row"><span class="store-price">${money(p.price_cents,p.currency||'usd')}</span><span class="store-meta">${Number(p.views??0).toLocaleString()} views · ${Number(p.likes??0).toLocaleString()} likes</span></div><div class="store-actions"><button class="store-btn primary" data-add="${p.id}">${cart.has(p.id)?'IN CART':'ADD TO CART'}</button><button class="store-btn" data-open="${p.id}">VIEW</button></div></div></article>`).join(''):'<div class="store-empty">No products match this lane yet.</div>';grid.querySelectorAll<HTMLButtonElement>('[data-open]').forEach(b=>b.onclick=()=>{const p=products.find(x=>x.id===b.dataset.open);if(p)void openProduct(p);});grid.querySelectorAll<HTMLButtonElement>('[data-add]').forEach(b=>b.onclick=()=>void setCart(b.dataset.add||'',1));grid.querySelectorAll<HTMLButtonElement>('[data-like]').forEach(b=>b.onclick=()=>void toggleLike(b.dataset.like||''));};
 const refresh=async()=>{if(loading){pending=true;return;}loading=true;try{const [{data,error}]=await Promise.all([supabase.rpc('rb_store_catalog',{p_limit:120}),loadUserState()]);if(error)throw error;products=(data??[]) as Product[];renderMetrics();renderFilters();renderGrid();}catch(e){grid.innerHTML=`<div class="store-empty">${esc((e as Error).message)}</div>`;}finally{loading=false;if(pending&&!disposed){pending=false;void refresh();}}};
 const setCart=async(id:string,qty:number)=>{if(!userId){location.href='/tap-in.html?next=%2Fstore.html';return;}const {data,error}=await supabase.rpc('rb_store_cart_set',{p_product_id:id,p_quantity:qty});if(error){note(error.message);return;}if(qty<=0)cart.delete(id);else cart.set(id,{product_id:id,quantity:qty,price_cents:Number((data as any)?.price_cents??products.find(p=>p.id===id)?.price_cents??0),currency:String((data as any)?.currency??'usd')});renderCartCount();renderGrid();note(qty<=0?'Removed from cart.':'Cart updated.');};
 const toggleLike=async(id:string)=>{if(!userId){location.href='/tap-in.html?next=%2Fstore.html';return;}const {data,error}=await supabase.rpc('rb_store_toggle_like',{p_product_id:id});if(error){note(error.message);return;}Boolean((data as any)?.liked)?liked.add(id):liked.delete(id);const p=products.find(x=>x.id===id);if(p)p.likes=Number((data as any)?.count??p.likes??0);renderGrid();};
 const loadComments=async()=>{if(!active||commentLoading)return;commentLoading=true;try{const {data}=await supabase.from('store_comments').select('id,body,created_at,user_id,profiles(display_name,username)').eq('product_id',active.id).order('created_at',{ascending:true}).limit(100);const el=document.querySelector<HTMLElement>('#storeComments');if(el)el.innerHTML=(data??[]).length?(data as any[]).map(c=>`<div class="store-comment"><p>${esc(c.body)}</p><small>${esc(c.profiles?.display_name||c.profiles?.username||'Rich Member')}</small></div>`).join(''):'<div class="store-empty">No comments yet.</div>';}finally{commentLoading=false;}};
 const closeDrawer=async()=>{drawer.classList.remove('open');active=null;if(commentChannel){await supabase.removeChannel(commentChannel);commentChannel=null;}};
 const openProduct=async(p:Product)=>{await closeDrawer();active=p;drawer.classList.add('open');void supabase.rpc('rb_store_record_view',{p_product_id:p.id,p_anonymous_id:userId?null:anonId});const c=cart.get(p.id);modal.innerHTML=`<div class="store-modal-media"><img src="${esc(p.cover_url||p.image_url||art(p))}" alt=""></div><div class="store-modal-body"><div class="store-modal-head"><div><small>${esc(p.category||'drop')} · ${esc(p.product_type||'product')}</small><h2>${esc(p.title)}</h2></div><button id="closeStore" class="store-close">×</button></div><div class="store-detail-grid"><section class="store-panel"><h3>About this drop</h3><p>${esc(p.description||'No description yet.')}</p><p><strong>${money(p.price_cents,p.currency||'usd')}</strong> · ${esc(p.fulfillment_type||'fulfillment')}</p><p>${p.is_local?`Local · ${esc(p.location_label||[p.city,p.state].filter(Boolean).join(', '))}`:''}${p.is_digital?' Digital unlock':''}</p><button id="detailAdd" class="store-btn primary">${c?'UPDATE CART':'ADD TO CART'}</button><section class="store-panel" style="margin-top:14px"><h3>Comments</h3><div id="storeComments" class="store-comments"></div><form id="storeCommentForm" class="store-comment-form"><input id="storeCommentInput" maxlength="2000" placeholder="Ask about this product..."><button class="store-btn primary">POST</button></form></section></section><aside class="store-panel"><h3>Seller</h3><div class="store-seller"><img src="${esc(p.seller_avatar_url||'/brand/icons/profile-placeholder.svg')}" alt=""><div><strong>${esc(p.seller_name||'Rich Seller')}</strong><small>${esc(p.seller_rank||'Seller')}</small></div></div><p>${p.inventory_count??0} available</p><p>${p.sales_count??0} sold · ${p.likes??0} likes</p><a class="store-btn" href="/profile.html${p.seller_id?`?id=${encodeURIComponent(p.seller_id)}`:''}">SELLER PROFILE</a></aside></div></div>`;document.querySelector<HTMLButtonElement>('#closeStore')!.onclick=()=>void closeDrawer();document.querySelector<HTMLButtonElement>('#detailAdd')!.onclick=()=>void setCart(p.id,(c?.quantity??0)+1);document.querySelector<HTMLFormElement>('#storeCommentForm')!.onsubmit=async e=>{e.preventDefault();if(!userId){location.href='/tap-in.html?next=%2Fstore.html';return;}const input=document.querySelector<HTMLInputElement>('#storeCommentInput')!,body=input.value.trim();if(!body)return;const button=(e.currentTarget as HTMLFormElement).querySelector<HTMLButtonElement>('button')!;button.disabled=true;const {error}=await supabase.from('store_comments').insert({product_id:p.id,user_id:userId,body});button.disabled=false;if(error){note(error.message);return;}input.value='';await loadComments();};await loadComments();commentChannel=supabase.channel(`store-comments:${p.id}`).on('postgres_changes',{event:'*',schema:'public',table:'store_comments',filter:`product_id=eq.${p.id}`},()=>void loadComments()).subscribe();};
 const openCart=()=>{drawer.classList.add('open');const rows=[...cart.values()],total=rows.reduce((a,b)=>a+b.price_cents*b.quantity,0);modal.innerHTML=`<div class="store-modal-body"><div class="store-modal-head"><div><small>RICH CART</small><h2>Your Bag</h2></div><button id="closeStore" class="store-close">×</button></div><div class="store-cart-list">${rows.length?rows.map(r=>{const p=products.find(x=>x.id===r.product_id);return `<div class="store-cart-item"><div><strong>${esc(p?.title||'Product')}</strong><small>${money(r.price_cents,r.currency)}</small></div><div class="store-qty"><button data-minus="${r.product_id}">−</button><span>${r.quantity}</span><button data-plus="${r.product_id}">+</button></div></div>`}).join(''):'<div class="store-empty">Your cart is empty.</div>'}</div><div class="store-price-row"><span>Total</span><span class="store-price">${money(total,'usd')}</span></div><button id="checkoutBtn" class="store-btn primary" style="width:100%;margin-top:14px" ${rows.length?'':'disabled'}>SECURE CHECKOUT</button><p class="store-checkout-note">Payment endpoint verification is completed in the final Money + Webhook pass before orders can charge.</p></div>`;document.querySelector<HTMLButtonElement>('#closeStore')!.onclick=()=>void closeDrawer();modal.querySelectorAll<HTMLButtonElement>('[data-minus]').forEach(b=>b.onclick=()=>{const r=cart.get(b.dataset.minus||'');void setCart(b.dataset.minus||'',Math.max(0,(r?.quantity??1)-1)).then(openCart);});modal.querySelectorAll<HTMLButtonElement>('[data-plus]').forEach(b=>b.onclick=()=>{const r=cart.get(b.dataset.plus||'');void setCart(b.dataset.plus||'',(r?.quantity??0)+1).then(openCart);});document.querySelector<HTMLButtonElement>('#checkoutBtn')?.addEventListener('click',()=>note('Secure checkout is waiting for the verified payment endpoint.'));};
 search.oninput=()=>{query=search.value.trim();renderGrid();};cartPill.onclick=openCart;drawer.onclick=e=>{if(e.target===drawer)void closeDrawer();};
 const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')void closeDrawer();};document.addEventListener('keydown',onKey);
 catalogChannel=supabase.channel('store-catalog').on('postgres_changes',{event:'*',schema:'public',table:'products'},()=>void refresh()).on('postgres_changes',{event:'*',schema:'public',table:'product_likes'},()=>void refresh()).on('postgres_changes',{event:'*',schema:'public',table:'store_cart_items'},()=>void refresh()).on('postgres_changes',{event:'*',schema:'public',table:'store_orders'},()=>void refresh()).on('postgres_changes',{event:'*',schema:'public',table:'creator_available_balances'},()=>void refresh()).subscribe();
 const cleanup=()=>{if(disposed)return;disposed=true;clearTimeout(statusTimer);document.removeEventListener('keydown',onKey);if(commentChannel)void supabase.removeChannel(commentChannel);if(catalogChannel)void supabase.removeChannel(catalogChannel);};window.addEventListener('pagehide',cleanup,{once:true});window.addEventListener('beforeunload',cleanup,{once:true});
 await refresh();
}
