import { getAuthSnapshot } from '../../core/auth/auth-store';
import { supabase } from '../../core/supabase/client';
import '../../styles/deep-sections.css';
import '../../styles/sports-arena.css';

type Row=Record<string,any>;
type Snapshot={posts?:Row[];picks?:Row[];broadcasts?:Row[];leagues?:Row[];profile?:Row;metrics?:Row};
type CleanupHost=Window&{__rbPageCleanup?:(()=>void|Promise<void>)|null};
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]??c));
const date=(v:unknown)=>v?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(String(v))):'';
const safeRoute=(v:unknown)=>{try{const u=new URL(String(v||'/live.html'),location.origin);return u.origin===location.origin&&['http:','https:'].includes(u.protocol)?`${u.pathname}${u.search}${u.hash}`:'/live.html';}catch{return'/live.html';}};
const safeMedia=(v:unknown)=>{try{const u=new URL(String(v||''),location.origin);return ['http:','https:'].includes(u.protocol)?u.href:'';}catch{return'';}};
const mediaBox=(url:unknown,label:string)=>{const src=safeMedia(url);return src?`<img src="${esc(src)}" alt="" loading="lazy" decoding="async">`:`<div class="sports-media-empty">${esc(label)}</div>`};

export async function mount():Promise<void>{
 const root=document.querySelector<HTMLElement>('#app');if(!root)throw new Error('Missing #app');
 const mountEpoch=root.dataset.pageEpoch??'';let destroyed=false;let requestEpoch=0;
 const isCurrent=()=>!destroyed&&root.dataset.pageEpoch===mountEpoch&&root.dataset.pageOwner==='rich-bizness-sports-v3';
 const user=getAuthSnapshot().user;
 root.innerHTML=`<main class="deep-shell sports-arena"><div class="deep-wrap"><header class="deep-top"><a href="/portal.html">←</a><div><p>RICH BIZNESS SPORTS NETWORK</p><h1>Arena</h1></div><span id="sportsLiveState" class="deep-live">LIVE DATA</span></header><section class="deep-hero sports-hero"><div><small>HIGHLIGHTS • PICKS • BROADCASTS • TEAMS</small><h2>OWN THE MOMENT</h2><p>A cinematic sports universe for elite highlights, creator broadcasts, league conversation, premium picks, fan identity, and competition.</p><div class="deep-actions"><a class="deep-btn primary" href="/upload.html?route=sports">DROP HIGHLIGHT</a><button id="openPick" class="deep-btn">MAKE A PICK</button><a class="deep-btn" href="/live.html?category=sports">GO LIVE</a><a class="deep-btn" href="/watch.html?lane=sports">WATCH SPORTS</a></div></div></section><section id="commandDeck" class="sports-command-deck"></section><nav id="tabs" class="deep-tabs"></nav><section id="stats" class="deep-stats"></section><section id="content"></section><p id="status" class="deep-status" role="status"></p></div><div id="pickModal" class="deep-modal" hidden><section class="deep-modal-card"><header><div><small>SPORTS XP EVENT</small><h2>MAKE A PICK</h2></div><button id="closePick" type="button">×</button></header><form id="pickForm" class="deep-form"><div class="deep-form-row"><input id="pickTitle" required maxlength="120" placeholder="Pick title"><input id="pickSport" required maxlength="60" placeholder="Sport"></div><div class="deep-form-row"><input id="pickTeam" maxlength="80" placeholder="Team"><input id="pickOpponent" maxlength="80" placeholder="Opponent"></div><textarea id="pickPrediction" required maxlength="1000" placeholder="Prediction and reasoning"></textarea><div class="deep-form-row"><input id="pickConfidence" type="number" min="1" max="100" value="70"><input id="pickTime" type="datetime-local"></div><button class="deep-btn primary">LOCK PICK</button></form></section></div><div id="talkModal" class="deep-modal" hidden><section class="deep-modal-card sports-talk-card"><header><div><small>ARENA CONVERSATION</small><h2 id="talkTitle">SPORTS TALK</h2></div><button id="closeTalk" type="button">×</button></header><div id="talkList" class="sports-talk-list"></div><form id="talkForm" class="sports-talk-form"><textarea id="talkBody" maxlength="1200" required placeholder="Add to the sports conversation..."></textarea><button class="deep-btn primary">POST COMMENT</button></form></section></div></main>`;
 const q=<T extends Element>(s:string)=>root.querySelector<T>(s)!;
 const tabs=q<HTMLElement>('#tabs'),stats=q<HTMLElement>('#stats'),content=q<HTMLElement>('#content'),status=q<HTMLElement>('#status'),pickModal=q<HTMLElement>('#pickModal'),talkModal=q<HTMLElement>('#talkModal'),talkList=q<HTMLElement>('#talkList'),commandDeck=q<HTMLElement>('#commandDeck'),liveState=q<HTMLElement>('#sportsLiveState');
 let lane='highlights',snapshot:Snapshot={},activePost:string|null=null,channel:ReturnType<typeof supabase.channel>|null=null,loading=false,queued=false,refreshTimer:number|undefined,statusTimer:number|undefined;
 const lanes=[['highlights','HIGHLIGHTS'],['picks','PICKS'],['broadcasts','BROADCASTS'],['teams','LEAGUES + TEAMS'],['profile','MY SPORTS ID']];
 const isLane=(value:string|null)=>!!value&&lanes.some(([key])=>key===value);
 const setStatus=(v:string,error=false)=>{if(!isCurrent())return;status.textContent=v;status.dataset.error=String(error);window.clearTimeout(statusTimer);statusTimer=window.setTimeout(()=>{if(isCurrent()&&status.textContent===v)status.textContent='';},3000)};
 const syncLaneUrl=()=>{if(!isCurrent())return;const url=new URL(location.href);if(lane==='highlights')url.searchParams.delete('lane');else url.searchParams.set('lane',lane);history.replaceState(null,'',`${url.pathname}${url.search}${url.hash}`);};
 const action=async(name:string,payload:Row)=>{if(!isCurrent())return;const{error}=await supabase.rpc('rb_sports_action',{p_action:name,p_payload:payload});if(error)throw error;};
 const openComments=async(postId:string,title:string)=>{if(!isCurrent())return;activePost=postId;q<HTMLElement>('#talkTitle').textContent=title||'SPORTS TALK';talkModal.hidden=false;document.body.style.overflow='hidden';const epoch=++requestEpoch;const{data,error}=await supabase.from('sports_comments').select('id,username,display_name,body,created_at').eq('post_id',postId).order('created_at').limit(160);if(!isCurrent()||epoch!==requestEpoch)return;talkList.innerHTML=error?`<div class="deep-empty">${esc(error.message)}</div>`:(data??[]).map(r=>`<article><strong>${esc(r.display_name||r.username||'Rich Fan')}</strong><p>${esc(r.body)}</p><time>${date(r.created_at)}</time></article>`).join('')||'<div class="deep-empty">Start the arena conversation.</div>';talkList.scrollTop=talkList.scrollHeight;};
 const bind=()=>{if(!isCurrent())return;content.querySelectorAll<HTMLButtonElement>('[data-react]').forEach(b=>b.onclick=async()=>{if(!user)return location.assign('/tap-in.html?next=%2Fsports.html');try{b.disabled=true;await action('reaction',{post_id:b.dataset.post,reaction:b.dataset.react});await load();}catch(e){setStatus(e instanceof Error?e.message:'Reaction failed',true);}finally{b.disabled=false;}});content.querySelectorAll<HTMLButtonElement>('[data-talk]').forEach(b=>b.onclick=()=>void openComments(b.dataset.post!,b.dataset.title||'Sports Talk'));};
 const renderTabs=()=>{if(!isCurrent())return;tabs.innerHTML=lanes.map(([k,l])=>`<button class="deep-tab ${lane===k?'active':''}" data-lane="${k}">${l}</button>`).join('');tabs.querySelectorAll<HTMLButtonElement>('[data-lane]').forEach(b=>b.onclick=()=>{if(!isCurrent())return;const next=b.dataset.lane||'highlights';if(!isLane(next))return;lane=next;syncLaneUrl();renderTabs();render();});};
 const highlightCard=(p:Row)=>{const m=safeMedia(p.media_url||p.thumbnail_url||p.cover_url);const art=m?(String(p.media_type||'').startsWith('video')?`<video src="${esc(m)}" controls playsinline preload="metadata"></video>`:mediaBox(m,'RB SPORTS')):mediaBox(null,'RB SPORTS');return`<article class="deep-card sports-highlight"><div class="deep-card-media wide">${art}<span>${esc(p.sport||'SPORTS')}</span></div><div class="deep-card-body"><h3>${esc(p.title||'Sports Drop')}</h3><p>${esc(p.body||`${p.team_name||''} ${p.league||''}`)}</p><div class="deep-card-meta"><span>◌ ${p.comment_count??0} · 🔥 ${p.reaction_count??0}</span><span>◉ ${p.view_count??0}</span></div><div class="sports-reaction-row"><button data-react="🔥" data-post="${p.id}">🔥</button><button data-react="💯" data-post="${p.id}">💯</button><button data-react="🏆" data-post="${p.id}">🏆</button><button data-talk data-post="${p.id}" data-title="${esc(p.title||'Sports Talk')}">COMMENT</button></div><div class="deep-card-actions"><a href="/profile.html?id=${p.user_id}">CREATOR</a><a href="/watch.html?type=sports_clip&id=${p.id}&lane=sports">WATCH</a></div></div></article>`;};
 const pickCard=(p:Row)=>`<article class="deep-card sports-pick-card"><div class="deep-card-body"><span class="deep-badge ${p.result==='loss'?'danger':p.result==='win'?'':'warn'}">${esc((p.result||p.status||'OPEN').toUpperCase())}</span><h3>${esc(p.title)}</h3><p>${esc(p.prediction||'')}</p><div class="deep-card-meta"><span>${esc(p.team_name||'')} vs ${esc(p.opponent||'')}</span><span>${p.confidence??0}%</span></div><div class="sports-confidence"><i style="--confidence:${Math.min(100,Math.max(0,Number(p.confidence??0)))}%"></i></div><div class="deep-card-actions"><a href="/profile.html?id=${p.user_id}">${esc(p.display_name||'PICKER')}</a></div></div></article>`;
 const broadcastCard=(b:Row)=>{const status=String(b.status||'scheduled').toLowerCase();const href=status==='live'?`/live.html?category=sports${b.id?`&stream=${encodeURIComponent(b.id)}`:''}`:(b.id?`/watch.html?type=sports_replay&id=${encodeURIComponent(b.id)}&lane=sports`:'/watch.html?lane=sports');return`<article class="deep-card ${status==='live'?'sports-broadcast-live':''}"><div class="deep-card-media wide">${mediaBox(b.cover_url,'LIVE SPORTS')}<span>${esc(status.toUpperCase())}</span></div><div class="deep-card-body"><h3>${esc(b.title)}</h3><p>${esc(b.description||`${b.team_name||''} ${b.league||''}`)}</p><div class="deep-card-meta"><span>${date(b.scheduled_for)}</span><span>◉ ${b.viewer_count??0}</span></div><div class="deep-card-actions"><a href="${esc(href)}">${status==='live'?'ENTER LIVE':'WATCH REPLAY'}</a></div></div></article>`;};
 const leagueCard=(l:Row)=>`<article class="deep-card sports-league-card"><div class="deep-card-media wide">${mediaBox(l.cover_url||l.logo_url,l.sport||'LEAGUE')}<span>${esc(l.sport||'LEAGUE')}</span></div><div class="deep-card-body"><h3>${esc(l.title)}</h3><p>Follow coverage, teams, broadcasts, picks, and highlights.</p><div class="deep-card-actions"><a href="/search.html?q=${encodeURIComponent(String(l.title||l.sport||''))}">SEARCH COVERAGE</a><a href="/live.html?category=sports&league=${encodeURIComponent(String(l.title||''))}">LIVE</a></div></div></article>`;
 const render=()=>{if(!isCurrent())return;const posts=snapshot.posts??[],picks=snapshot.picks??[],broadcasts=snapshot.broadcasts??[],leagues=snapshot.leagues??[],profile=snapshot.profile??{},m=snapshot.metrics??{};const live=broadcasts.filter(row=>String(row.status).toLowerCase()==='live');const scheduled=broadcasts.filter(row=>String(row.status).toLowerCase()==='scheduled');const hot=posts.slice().sort((a,b)=>Number(b.reaction_count??0)-Number(a.reaction_count??0))[0];liveState.textContent=live.length?`${live.length} LIVE`:'LIVE DATA';commandDeck.innerHTML=`<article class="sports-command-card live"><small>LIVE NOW</small><strong>${live.length}</strong><span>${live[0]?esc(live[0].title):'No active broadcast'}</span></article><article class="sports-command-card"><small>NEXT EVENT</small><strong>${scheduled.length}</strong><span>${scheduled[0]?`${esc(scheduled[0].title)} · ${date(scheduled[0].scheduled_for)}`:'Schedule ready'}</span></article><article class="sports-command-card"><small>HOT MOMENT</small><strong>${hot?Number(hot.reaction_count??0).toLocaleString():'0'}</strong><span>${hot?esc(hot.title||'Sports Drop'):'No reactions yet'}</span></article><article class="sports-command-card"><small>FAN STATUS</small><strong>${esc(profile.rank_title||'ROOKIE')}</strong><span>${esc(profile.favorite_team||profile.favorite_sport||'Build your Sports ID')}</span></article>`;stats.innerHTML=`<article><small>HIGHLIGHTS</small><strong>${Number(m.highlights??posts.length).toLocaleString()}</strong></article><article><small>ACTIVE PICKS</small><strong>${Number(m.active_picks??0).toLocaleString()}</strong></article><article><small>BROADCASTS</small><strong>${Number(m.broadcasts??broadcasts.length).toLocaleString()}</strong></article><article><small>SPORTS XP</small><strong>${Number(m.sports_xp??profile.points??0).toLocaleString()}</strong></article>`;
 if(lane==='highlights')content.innerHTML=`<section class="deep-grid">${posts.map(highlightCard).join('')||'<div class="deep-empty">No highlights yet.</div>'}</section>`;else if(lane==='picks')content.innerHTML=`<section class="deep-grid">${picks.map(pickCard).join('')||'<div class="deep-empty">No picks locked yet.</div>'}</section>`;else if(lane==='broadcasts')content.innerHTML=`<section class="deep-grid">${broadcasts.map(broadcastCard).join('')||'<div class="deep-empty">No broadcasts scheduled.</div>'}</section>`;else if(lane==='teams')content.innerHTML=`<section class="deep-grid">${leagues.map(leagueCard).join('')||'<div class="deep-empty">League directory is ready for content.</div>'}</section>`;else content.innerHTML=Object.keys(profile).length?`<section class="deep-section sports-profile-panel"><header><div><small>CONNECTED SPORTS ID</small><h2>${esc(profile.display_name||profile.fan_tag||'Rich Fan')}</h2><p>${esc(profile.rank_title||'Rookie Fan')}</p></div><div class="deep-actions"><a class="deep-btn" href="/edit-profile.html">EDIT IDENTITY</a><a class="deep-btn" href="/creator.html">CREATOR HUB</a></div></header><div class="deep-stats"><article><small>FAVORITE SPORT</small><strong>${esc(profile.favorite_sport||'OPEN')}</strong></article><article><small>TEAM</small><strong>${esc(profile.favorite_team||'OPEN')}</strong></article><article><small>WINS</small><strong>${profile.win_count??0}</strong></article><article><small>STREAK</small><strong>${profile.pick_streak??0}</strong></article></div></section>`:'<div class="deep-empty">Create your Sports identity from Profile settings.</div>';bind();};
 const load=async()=>{if(!isCurrent())return;if(loading){queued=true;return;}loading=true;const epoch=++requestEpoch;try{const{data,error}=await supabase.rpc('rb_sports_snapshot',{p_limit:100});if(error)throw error;if(!isCurrent()||epoch!==requestEpoch)return;snapshot=(data??{}) as Snapshot;render();}catch(e){if(!isCurrent()||epoch!==requestEpoch)return;snapshot={};render();setStatus(e instanceof Error?e.message:'Sports sync failed',true);}finally{loading=false;if(queued&&isCurrent()){queued=false;void load();}}};
 const scheduleLoad=()=>{if(!isCurrent())return;window.clearTimeout(refreshTimer);refreshTimer=window.setTimeout(()=>void load(),180);};
 const close=(modal:HTMLElement)=>{modal.hidden=true;if(pickModal.hidden&&talkModal.hidden)document.body.style.overflow='';};
 q<HTMLButtonElement>('#openPick').onclick=()=>{if(!user)return location.assign('/tap-in.html?next=%2Fsports.html');pickModal.hidden=false;document.body.style.overflow='hidden';};q<HTMLButtonElement>('#closePick').onclick=()=>close(pickModal);q<HTMLButtonElement>('#closeTalk').onclick=()=>close(talkModal);
 q<HTMLFormElement>('#pickForm').onsubmit=async e=>{e.preventDefault();if(!user||!isCurrent())return;const form=e.currentTarget;const button=form.querySelector<HTMLButtonElement>('button');if(button)button.disabled=true;try{await action('create_pick',{title:q<HTMLInputElement>('#pickTitle').value.trim(),sport:q<HTMLInputElement>('#pickSport').value.trim(),team_name:q<HTMLInputElement>('#pickTeam').value.trim(),opponent:q<HTMLInputElement>('#pickOpponent').value.trim(),prediction:q<HTMLTextAreaElement>('#pickPrediction').value.trim(),confidence:Number(q<HTMLInputElement>('#pickConfidence').value),game_time:q<HTMLInputElement>('#pickTime').value||null});form.reset();close(pickModal);setStatus('PICK LOCKED — XP SYNCED');await load();}catch(err){setStatus(err instanceof Error?err.message:'Pick failed',true);}finally{if(button)button.disabled=false;}};
 q<HTMLFormElement>('#talkForm').onsubmit=async e=>{e.preventDefault();if(!user||!activePost||!isCurrent())return location.assign('/tap-in.html?next=%2Fsports.html');const box=q<HTMLTextAreaElement>('#talkBody');try{await action('comment',{post_id:activePost,body:box.value.trim()});box.value='';await openComments(activePost,q<HTMLElement>('#talkTitle').textContent||'Sports Talk');await load();}catch(err){setStatus(err instanceof Error?err.message:'Comment failed',true);}};
 const requestedLane=new URLSearchParams(location.search).get('lane');if(isLane(requestedLane))lane=requestedLane!;
 const onPopState=()=>{if(!isCurrent())return;const next=new URLSearchParams(location.search).get('lane');lane=isLane(next)?next!:'highlights';renderTabs();render();};window.addEventListener('popstate',onPopState);
 const cleanup=async()=>{if(destroyed)return;destroyed=true;requestEpoch++;queued=false;window.clearTimeout(refreshTimer);window.clearTimeout(statusTimer);window.removeEventListener('popstate',onPopState);window.removeEventListener('pagehide',onPageExit);window.removeEventListener('beforeunload',onPageExit);document.body.style.overflow='';root.querySelectorAll<HTMLMediaElement>('video,audio').forEach(m=>{m.pause();m.removeAttribute('src');m.load();});if(channel)await supabase.removeChannel(channel);channel=null;const host=window as CleanupHost;if(host.__rbPageCleanup===cleanup)host.__rbPageCleanup=null;};
 const onPageExit=()=>{void cleanup();};(window as CleanupHost).__rbPageCleanup=cleanup;window.addEventListener('pagehide',onPageExit,{once:true});window.addEventListener('beforeunload',onPageExit,{once:true});
 renderTabs();await load();if(!isCurrent())return;channel=supabase.channel(`sports-arena-live:${mountEpoch}`).on('postgres_changes',{event:'*',schema:'public',table:'sports_posts'},scheduleLoad).on('postgres_changes',{event:'*',schema:'public',table:'sports_picks'},scheduleLoad).on('postgres_changes',{event:'*',schema:'public',table:'sports_broadcasts'},scheduleLoad).on('postgres_changes',{event:'*',schema:'public',table:'sports_comments'},scheduleLoad).on('postgres_changes',{event:'*',schema:'public',table:'sports_reactions'},scheduleLoad).on('postgres_changes',{event:'*',schema:'public',table:'sports_profiles'},scheduleLoad).on('postgres_changes',{event:'*',schema:'public',table:'sports_leagues'},scheduleLoad).subscribe();
}
