import { supabase } from '../../core/supabase/client';
import '../../styles/deep-sections.css';

type Post={id:string;user_id:string;display_name:string|null;username:string|null;title:string|null;body:string|null;sport:string|null;league:string|null;team_name:string|null;media_url:string|null;cover_url:string|null;thumbnail_url:string|null;media_type:string|null;like_count:number|null;comment_count:number|null;view_count:number|null;created_at:string|null};
type Pick={id:string;user_id:string;display_name:string|null;title:string;prediction:string|null;sport:string|null;league:string|null;team_name:string|null;opponent:string|null;confidence:number|null;status:string|null;result:string|null;points:number|null;game_time:string|null};
type Broadcast={id:string;user_id:string;display_name:string|null;title:string;description:string|null;sport:string|null;league:string|null;team_name:string|null;status:string|null;viewer_count:number|null;scheduled_for:string|null;cover_url:string|null;stream_url:string|null;replay_url:string|null};
const esc=(v:string|null|undefined)=>(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c));
const date=(v:string|null|undefined)=>v?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(v)):'';

export async function mount():Promise<void>{
 const root=document.querySelector<HTMLElement>('#app');if(!root)throw new Error('Missing #app');
 const {data:{session}}=await supabase.auth.getSession();
 root.innerHTML=`<main class="deep-shell"><div class="deep-wrap"><header class="deep-top"><a href="/portal.html">←</a><div><p>RICH BIZNESS SPORTS NETWORK</p><h1>Arena</h1></div><span class="deep-live">LIVE DATA</span></header><section class="deep-hero" style="--hero-image:url('/images/brand/IMG_5997.png')"><div><small>HIGHLIGHTS • PICKS • BROADCASTS • TEAMS</small><h2>OWN THE MOMENT</h2><p>A connected sports universe for highlights, creator broadcasts, league conversation, premium picks, profiles, and fan competition.</p><div class="deep-actions"><a class="deep-btn primary" href="/upload.html?route=sports">DROP HIGHLIGHT</a><button id="openPick" class="deep-btn">MAKE A PICK</button><a class="deep-btn" href="/live.html?category=sports">GO LIVE</a></div></div></section><nav id="tabs" class="deep-tabs"></nav><section id="stats" class="deep-stats"></section><section id="content"></section><p id="status" class="deep-status"></p></div><div id="pickModal" class="deep-modal" hidden><section class="deep-modal-card"><header><div><small>SPORTS XP EVENT</small><h2>MAKE A PICK</h2></div><button id="closePick">×</button></header><form id="pickForm" class="deep-form"><div class="deep-form-row"><input id="pickTitle" required maxlength="120" placeholder="Pick title"><input id="pickSport" required maxlength="60" placeholder="Sport"></div><div class="deep-form-row"><input id="pickTeam" maxlength="80" placeholder="Team"><input id="pickOpponent" maxlength="80" placeholder="Opponent"></div><textarea id="pickPrediction" required maxlength="1000" placeholder="Prediction and reasoning"></textarea><div class="deep-form-row"><input id="pickConfidence" type="number" min="1" max="100" value="70" placeholder="Confidence"><input id="pickTime" type="datetime-local"></div><button class="deep-btn primary">LOCK PICK</button></form></section></div></main>`;
 const tabs=document.querySelector<HTMLElement>('#tabs')!,stats=document.querySelector<HTMLElement>('#stats')!,content=document.querySelector<HTMLElement>('#content')!,status=document.querySelector<HTMLElement>('#status')!;
 const modal=document.querySelector<HTMLElement>('#pickModal')!;let lane='highlights',posts:Post[]=[],picks:Pick[]=[],broadcasts:Broadcast[]=[],profiles:any[]=[],leagues:any[]=[];
 const setStatus=(v:string)=>{status.textContent=v;setTimeout(()=>{if(status.textContent===v)status.textContent=''},2600)};
 const lanes=[['highlights','HIGHLIGHTS'],['picks','PICKS'],['broadcasts','BROADCASTS'],['teams','LEAGUES + TEAMS'],['profile','MY SPORTS ID']];
 const renderTabs=()=>{tabs.innerHTML=lanes.map(([k,l])=>`<button class="deep-tab ${lane===k?'active':''}" data-lane="${k}">${l}</button>`).join('');tabs.querySelectorAll<HTMLButtonElement>('[data-lane]').forEach(b=>b.onclick=()=>{lane=b.dataset.lane!;renderTabs();render();});};
 const render=()=>{stats.innerHTML=`<article><small>HIGHLIGHTS</small><strong>${posts.length}</strong></article><article><small>ACTIVE PICKS</small><strong>${picks.filter(p=>p.status!=='settled').length}</strong></article><article><small>BROADCASTS</small><strong>${broadcasts.length}</strong></article><article><small>SPORTS XP</small><strong>${Number(profiles[0]?.points??0).toLocaleString()}</strong></article>`;
 if(lane==='highlights')content.innerHTML=`<section class="deep-grid">${posts.length?posts.map(p=>{const m=p.media_url||p.thumbnail_url||p.cover_url;return `<article class="deep-card"><div class="deep-card-media wide">${m?(p.media_type?.startsWith('video')?`<video src="${esc(m)}" controls playsinline></video>`:`<img src="${esc(m)}" alt="" loading="lazy">`):''}<span>${esc(p.sport||'SPORTS')}</span></div><div class="deep-card-body"><h3>${esc(p.title||'Sports Drop')}</h3><p>${esc(p.body||`${p.team_name||''} ${p.league||''}`)}</p><div class="deep-card-meta"><span>♥ ${p.like_count??0} · ◌ ${p.comment_count??0}</span><span>◉ ${p.view_count??0}</span></div><div class="deep-card-actions"><a href="/profile.html?id=${p.user_id}">CREATOR</a><a href="/watch.html?source=sports_clip&id=${p.id}">WATCH</a></div></div></article>`}).join(''):'<div class="deep-empty">No highlights yet.</div>'}</section>`;
 else if(lane==='picks')content.innerHTML=`<section class="deep-grid">${picks.length?picks.map(p=>`<article class="deep-card"><div class="deep-card-body"><span class="deep-badge ${p.result==='loss'?'danger':p.result==='win'?'':'warn'}">${esc((p.result||p.status||'OPEN').toUpperCase())}</span><h3>${esc(p.title)}</h3><p>${esc(p.prediction||'')}</p><div class="deep-card-meta"><span>${esc(p.team_name||'')} vs ${esc(p.opponent||'')}</span><span>${p.confidence??0}%</span></div><div class="deep-card-actions"><a href="/profile.html?id=${p.user_id}">${esc(p.display_name||'PICKER')}</a></div></div></article>`).join(''):'<div class="deep-empty">No picks locked yet.</div>'}</section>`;
 else if(lane==='broadcasts')content.innerHTML=`<section class="deep-grid">${broadcasts.length?broadcasts.map(b=>`<article class="deep-card"><div class="deep-card-media wide">${b.cover_url?`<img src="${esc(b.cover_url)}" alt="">`:''}<span>${esc((b.status||'SCHEDULED').toUpperCase())}</span></div><div class="deep-card-body"><h3>${esc(b.title)}</h3><p>${esc(b.description||`${b.team_name||''} ${b.league||''}`)}</p><div class="deep-card-meta"><span>${date(b.scheduled_for)}</span><span>◉ ${b.viewer_count??0}</span></div><div class="deep-card-actions"><a href="${esc(b.stream_url||b.replay_url||'/live.html')}">${b.status==='live'?'ENTER LIVE':'WATCH'}</a></div></div></article>`).join(''):'<div class="deep-empty">No broadcasts scheduled.</div>'}</section>`;
 else if(lane==='teams')content.innerHTML=`<section class="deep-grid">${leagues.length?leagues.map((l:any)=>`<article class="deep-card"><div class="deep-card-media wide">${l.cover_url||l.logo_url?`<img src="${esc(l.cover_url||l.logo_url)}" alt="">`:''}<span>${esc(l.sport||'LEAGUE')}</span></div><div class="deep-card-body"><h3>${esc(l.title)}</h3><p>Follow coverage, teams, broadcasts, picks, and highlights.</p></div></article>`).join(''):'<div class="deep-empty">League directory is ready for content.</div>'}</section>`;
 else content.innerHTML=profiles.length?`<section class="deep-section"><header><div><small>CONNECTED SPORTS ID</small><h2>${esc(profiles[0].display_name||profiles[0].fan_tag||'Rich Fan')}</h2></div></header><div class="deep-stats"><article><small>FAVORITE SPORT</small><strong>${esc(profiles[0].favorite_sport||'OPEN')}</strong></article><article><small>TEAM</small><strong>${esc(profiles[0].favorite_team||'OPEN')}</strong></article><article><small>WINS</small><strong>${profiles[0].win_count??0}</strong></article><article><small>STREAK</small><strong>${profiles[0].pick_streak??0}</strong></article></div></section>`:'<div class="deep-empty">Create your Sports identity from Profile settings.</div>';};
 const load=async()=>{const [a,b,c,d,e]=await Promise.all([supabase.from('sports_posts').select('*').order('created_at',{ascending:false}).limit(80),supabase.from('sports_picks').select('*').order('created_at',{ascending:false}).limit(80),supabase.from('sports_broadcasts').select('*').order('created_at',{ascending:false}).limit(50),session?supabase.from('sports_profiles').select('*').eq('user_id',session.user.id).limit(1):Promise.resolve({data:[]}),supabase.from('sports_leagues').select('*').eq('is_active',true).order('title')]);posts=(a.data??[]) as Post[];picks=(b.data??[]) as Pick[];broadcasts=(c.data??[]) as Broadcast[];profiles=d.data??[];leagues=e.data??[];render();};
 document.querySelector<HTMLButtonElement>('#openPick')!.onclick=()=>{if(!session){location.assign('/tap-in.html?next=/sports.html');return;}modal.hidden=false};document.querySelector<HTMLButtonElement>('#closePick')!.onclick=()=>modal.hidden=true;
 document.querySelector<HTMLFormElement>('#pickForm')!.onsubmit=async e=>{e.preventDefault();if(!session)return;const profile=(await supabase.from('profiles').select('username,display_name').eq('id',session.user.id).single()).data;const {error}=await supabase.from('sports_picks').insert({user_id:session.user.id,username:profile?.username,display_name:profile?.display_name,title:(document.querySelector<HTMLInputElement>('#pickTitle')!).value.trim(),sport:(document.querySelector<HTMLInputElement>('#pickSport')!).value.trim(),team_name:(document.querySelector<HTMLInputElement>('#pickTeam')!).value.trim(),opponent:(document.querySelector<HTMLInputElement>('#pickOpponent')!).value.trim(),prediction:(document.querySelector<HTMLTextAreaElement>('#pickPrediction')!).value.trim(),confidence:Number((document.querySelector<HTMLInputElement>('#pickConfidence')!).value),game_time:(document.querySelector<HTMLInputElement>('#pickTime')!).value||null,status:'open',metadata:{source:'sports-arena'}});if(error)setStatus(error.message);else{modal.hidden=true;setStatus('PICK LOCKED — XP SYNCED');await load();}};
 renderTabs();await load();['sports_posts','sports_picks','sports_broadcasts'].forEach(t=>supabase.channel(`sports:${t}`).on('postgres_changes',{event:'*',schema:'public',table:t},()=>void load()).subscribe());
}
