import { supabase } from '../../src/supabase-client.js';
import { getAuthoritativeIdentity } from '../../src/rb-identity.js?v=profile-avatar-separate-1';
const pieces={r:'♜',n:'♞',b:'♝',q:'♛',k:'♚',p:'♟',R:'♖',N:'♘',B:'♗',Q:'♕',K:'♔',P:'♙'};
const start=['rnbqkbnr','pppppppp','........','........','........','........','PPPPPPPP','RNBQKBNR'];
let board=start.map(r=>r.split('')),turn='white',selected=null,history=[],flipped=false;
const el=id=>document.getElementById(id);
const colorOf=p=>p==='.'?null:(p===p.toUpperCase()?'white':'black');
function legal(from,to){const [fr,fc]=from,[tr,tc]=to,p=board[fr][fc];if(!p||p==='.'||colorOf(p)!==turn||colorOf(board[tr][tc])===turn)return false;const dr=tr-fr,dc=tc-fc,a=p.toLowerCase();if(a==='p'){const dir=turn==='white'?-1:1,startRow=turn==='white'?6:1;if(dc===0&&board[tr][tc]==='.'&&(dr===dir||(fr===startRow&&dr===2*dir&&board[fr+dir][fc]==='.')))return true;if(Math.abs(dc)===1&&dr===dir&&board[tr][tc]!=='.')return true;return false}if(a==='n')return Math.abs(dr)*Math.abs(dc)===2;if(a==='k')return Math.max(Math.abs(dr),Math.abs(dc))===1;if(a==='r'&&!(dr===0||dc===0))return false;if(a==='b'&&Math.abs(dr)!==Math.abs(dc))return false;if(a==='q'&&!(dr===0||dc===0||Math.abs(dr)===Math.abs(dc)))return false;if(['r','b','q'].includes(a)){const sr=Math.sign(dr),sc=Math.sign(dc);for(let r=fr+sr,c=fc+sc;r!==tr||c!==tc;r+=sr,c+=sc)if(board[r][c]!=='.')return false;return true}return false}
function draw(){const root=el('board');root.innerHTML='';const rows=[...Array(8).keys()],cols=[...Array(8).keys()];if(flipped){rows.reverse();cols.reverse()}for(const r of rows)for(const c of cols){const s=document.createElement('button');s.className=`square ${(r+c)%2?'dark':'light'}`;s.dataset.r=r;s.dataset.c=c;s.textContent=pieces[board[r][c]]||'';if(selected&&selected[0]===r&&selected[1]===c)s.classList.add('selected');if(selected&&legal(selected,[r,c]))s.classList.add('target');s.onclick=()=>pick(r,c);root.appendChild(s)}}
function pick(r,c){if(!selected){if(colorOf(board[r][c])===turn){selected=[r,c];draw()}return}if(selected[0]===r&&selected[1]===c){selected=null;draw();return}if(!legal(selected,[r,c])){if(colorOf(board[r][c])===turn)selected=[r,c];draw();return}const [fr,fc]=selected,captured=board[r][c];history.push({board:board.map(x=>[...x]),turn,move:`${String.fromCharCode(97+fc)}${8-fr}-${String.fromCharCode(97+c)}${8-r}`,captured});board[r][c]=board[fr][fc];board[fr][fc]='.';turn=turn==='white'?'black':'white';selected=null;renderHistory();renderStatus();draw()}
function renderHistory(){el('moves').innerHTML=history.map((h,i)=>`<li>${i+1}. ${h.move}${h.captured!=='.'?` × ${pieces[h.captured]}`:''}</li>`).join('');el('whiteCaptured').textContent=history.filter(h=>h.captured!=='.'&&colorOf(h.captured)==='black').length;el('blackCaptured').textContent=history.filter(h=>h.captured!=='.'&&colorOf(h.captured)==='white').length}
function renderStatus(){el('status').textContent=`${turn[0].toUpperCase()+turn.slice(1)} to move`;el('whiteStatus').textContent=turn==='white'?'Your move':'Waiting';el('blackStatus').textContent=turn==='black'?'Your move':'Waiting'}
function reset(){board=start.map(r=>r.split(''));turn='white';selected=null;history=[];renderHistory();renderStatus();draw()}
async function save(){const state=await getAuthoritativeIdentity().catch(()=>({}));if(!state.user){location.href='/auth.html?next='+encodeURIComponent(location.pathname);return}const game=await supabase.from('games').select('id').in('slug',['rich-chess','rich-chess-boss']).limit(1).maybeSingle();await supabase.from('game_sessions').insert({game_id:game.data?.id||null,game_slug:'rich-chess',user_id:state.user.id,username:state.profile?.username||null,display_name:state.profile?.display_name||null,result:'in_progress',score:history.length,platform_type:'web',metadata:{source:'games/rich-chess',turn,position:board,move_history:history.map(h=>h.move)}});el('status').textContent='Match saved'}
el('newGame').onclick=reset;el('flipBoard').onclick=()=>{flipped=!flipped;draw()};el('undoMove').onclick=()=>{const h=history.pop();if(!h)return;board=h.board;turn=h.turn;selected=null;renderHistory();renderStatus();draw()};el('saveMatch').onclick=save;el('submitScore').onclick=save;reset();