import { getAuthoritativeIdentity, ensureProfile } from '../src/rb-identity.js?v=profile-avatar-separate-1';
import { listThreadIds, listThreads, listProfiles, createDirectThread, listMessages, createMessage, markThreadRead, reactToMessage, setTyping, startCall, listActiveCalls, watchMessages } from '../features/messages/api.js';
import { addDmAttachment, uploadDmAttachment } from '../features/messages/attachments.js';
import { installMessagesLayout, renderThreads, renderProfiles, renderMessages, renderCallParticipants, openAttachmentViewer, setComposerEnabled, setDmStatus } from '../features/messages/ui.js';
let user=null,profile=null,threads=[],active=null,messages=[],profiles=[],typingTimer=null,searchTimer=null;const $=(s)=>document.querySelector(s);
async function requireUser(){const state=await getAuthoritativeIdentity({fresh:true});user=state.user;profile=state.profile||(user?await ensureProfile(user):null);if(!user){location.href='/auth.html?next=/messages.html';return false;}return true;}
async function refreshCalls(){renderCallParticipants(active?await listActiveCalls(active.id):[]);}
async function openThread(threadId){active=threads.find((t)=>t.id===threadId)||active;renderThreads({threads,activeId:active?.id});setComposerEnabled(Boolean(active));if(!active)return;messages=await listMessages(active.id);renderMessages({thread:active,messages,userId:user.id});const last=messages[messages.length-1];if(last&&last.sender_id!==user.id)await markThreadRead({threadId:active.id,messageId:last.id,userId:user.id});await refreshCalls();}
async function loadProfiles(search=''){profiles=await listProfiles({userId:user.id,search});renderProfiles(profiles);}
async function openNewConversation(){await loadProfiles('');$('#dmNewDialog')?.showModal();$('#dmProfileSearch')?.focus();}
async function createConversation(profileId){const target=profiles.find((item)=>item.id===profileId);if(!target)return;setDmStatus('Creating conversation...');const thread=await createDirectThread({userId:user.id,profile:target});$('#dmNewDialog')?.close();await load(thread.id);setDmStatus('Conversation ready.');}
async function sendCurrentMessage(){const input=$('#dmBody'),urlInput=$('#dmAttachment'),fileInput=$('#dmAttachmentFile');const body=input?.value?.trim();const url=urlInput?.value?.trim();const file=fileInput?.files?.[0];if(!active||(!body&&!url&&!file))return;setDmStatus(file?'Uploading attachment...':'Sending...');let uploaded=null;if(file)uploaded=await uploadDmAttachment({threadId:active.id,userId:user.id,file});const messageType=uploaded?.file_type||'text';const msg=await createMessage({thread:active,user,profile,body:body||(uploaded?.file_name||'Attachment'),messageType:uploaded||url?messageType:'text',mediaUrl:uploaded?.file_url||url||null,mediaType:uploaded?.mime_type||null});const attachment=uploaded||url?await addDmAttachment({messageId:msg.id,userId:user.id,attachment:uploaded,url}):null;if(attachment)msg.attachments=[attachment];input.value='';if(urlInput)urlInput.value='';if(fileInput)fileInput.value='';await setTyping({threadId:active.id,userId:user.id,isTyping:false});messages.push(msg);renderMessages({thread:active,messages,userId:user.id});setDmStatus('Rich-DM sent.');}
function wire(){document.addEventListener('click',async(event)=>{const thread=event.target.closest('[data-thread-id]');if(thread)await openThread(thread.dataset.threadId);const profileButton=event.target.closest('[data-profile-id]');if(profileButton)await createConversation(profileButton.dataset.profileId);if(event.target.closest('#dmNew'))await openNewConversation();if(event.target.closest('[data-close-new]'))$('#dmNewDialog')?.close();const react=event.target.closest('[data-react]');if(react){const message=react.closest('[data-message-id]');if(message){await reactToMessage({messageId:message.dataset.messageId,userId:user.id,emoji:react.dataset.react});await openThread(active.id);}}const attachment=event.target.closest('[data-view-attachment]');if(attachment)openAttachmentViewer({url:attachment.dataset.url,type:attachment.dataset.type,name:attachment.dataset.name});if(event.target.closest('[data-close-viewer]'))$('#dmAttachmentViewer')?.close();if(event.target.closest('#dmCall')&&active){const call=await startCall({thread:active,user});if(call){setDmStatus('Rich Call started: '+call.livekit_room_name);await refreshCalls();}}});$('#dmForm')?.addEventListener('submit',async(event)=>{event.preventDefault();try{await sendCurrentMessage();}catch(error){console.error(error);setDmStatus(error.message||'Message failed.');}});$('#dmBody')?.addEventListener('input',()=>{if(!active||!user)return;setTyping({threadId:active.id,userId:user.id,isTyping:true});clearTimeout(typingTimer);typingTimer=setTimeout(()=>setTyping({threadId:active.id,userId:user.id,isTyping:false}),1200);});$('#dmProfileSearch')?.addEventListener('input',(event)=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>loadProfiles(event.target.value).catch(console.error),250);});}
async function load(preferredId=null){if(!user&&!await requireUser())return;const ids=await listThreadIds(user.id);if($('#memberCount'))$('#memberCount').textContent=ids.length.toLocaleString();threads=await listThreads(ids);if(preferredId)active=threads.find((thread)=>thread.id===preferredId)||active;if(active&&!threads.some((thread)=>thread.id===active.id))active=null;if(!active&&threads[0])active=threads[0];renderThreads({threads,activeId:active?.id});setComposerEnabled(Boolean(active));if(active)await openThread(active.id);else{messages=[];renderMessages({thread:null,messages:[],userId:user.id});}}
installMessagesLayout($('#messagesMount'));wire();load();watchMessages({onThreads:()=>load(active?.id),onMessages:()=>active?openThread(active.id):load(),onCalls:refreshCalls,onTyping:(payload)=>{if(payload.new?.thread_id===active?.id&&payload.new?.user_id!==user?.id)setDmStatus(payload.new?.is_typing?'They typing...':'Rich-DM ready.');}});