import { getAuthSnapshot } from '../../core/auth/auth-store';
import { supabase } from '../../core/supabase/client';
import '../../styles/broadcast-cinema-podcast.css';
import './podcast-universe.css';

type Row=Record<string,any>;
type Snapshot={shows?:Row[];episodes?:Row[];comments?:Row[];liked?:boolean;metrics?:Row};
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c));
const fmt=(v:unknown)=>Number(v??0).toLocaleString();
const safe=(v:unknown)=>{try{const u=new URL(String(v||''),location.origin);return['http:','https:'].includes(u.protocol)?u.href:'';}catch{return'';}};
const runtime=(v:unknown)=>Number(v??0)>0?`${Math.floor(Number(v)/60)}:${String(Number(v)%60).padStart(2,'0')}`:'VIDEO';

export async function mount():Promise<void>{
 const root=document.querySelector<HTMLElement>('#app');if(!root)throw new Error('Missing #app');if(root.dataset.podcastOwner==='mounted')return;root.dataset.podcastOwner='mounted';
 const user=getAuthSnapshot().user,userId=user?.id??null;
 root.innerHTML=`<main class="media-ultimate podcast-universe"><div class="media-ultimate__wrap"><header class="media-ultimate__head"><a href="/music.html">←</a><div><p>RICH BIZNESS VIDEO PODCAST NETWORK</p><h1>PODCAST UNIVERSE</h1></div><nav class="media-ultimate__tabs"><a href="/music.html">MUSIC</a><a class="active" href="/podcast.html">PODCAST</a><a href="/radio.html">RADIO</a></nav></header><section class="podcast-command"><article id="podcastStage" class="podcast-video-stage"></article><aside class="podcast-queue"><section id="podcastMetrics" class="media-ultimate__metrics"></section><nav class="media-ultimate__tabs" id="showTabs"></nav><div id="episodeQueue"></div></aside></section><section class="media-ultimate__split"><article class="media-ultimate__panel"><header><h4>EPISODE INTELLIGENCE</h4></header><div id="episodeDetail" class="media-ultimate__list"></div></article><article class="media-ultimate__panel"><header><h4>VIEWER CONVERSATION</h4></header><div id="podcastComments" class="media-ultimate__chat"></div><form id="podcastCommentForm" class="media-ultimate__form"><input id="podcastCommentInput" maxlength="2000" placeholder="Join the episode discussion..."><button class="media-ultimate__btn primary">POST</button></form></article></section><section class="media-ultimate__panel"><div class="media-ultimate__actions"><a class="media-ultimate__btn primary" href="/upload.html?route=podcast">DROP VIDEO EPISODE</a><a class="media-ultimate__btn" href="/live.html?category=podcast">GO LIVE PODCAST</a><a class="media-ultimate__btn" href="/creator.html">CREATOR HUB</a><a class="media-ultimate__btn" href="/watch.html?source=podcast">WATCH</a><a class="media-ultimate__btn" href="/portal.html">PORTAL</a></div></section><p id="podcastStatus" class="media-ultimate__empty" role="status"></p></div></main>`;
 const stage=root.querySelector<HTMLElement>('#podcastStage')!,metrics=root.querySelector<HTMLElement>('#podcastMetrics')!,tabs=root.querySelector<HTMLElement>('#showTabs')!,queue=root.querySelector<HTMLElement>('#episodeQueue')!,detail=root.querySelector<HTMLElement>('#episodeDetail')!,comments=root.querySelector<HTMLElement>('#podcastComments')!,form=root.querySelector<HTMLFormElement>('#podcastCommentForm')!,input=root.querySelector<HTMLInputElement>('#podcastCommentInput')!,status=root.querySelector<HTMLElement>('#podcastStatus')!;
 let snap:Snapshot={},active:Row|null=null,showId='all',channel:ReturnType<typeof supabase.channel>|null=null,commentChannel:ReturnType<typeof supabase.channel>|null=null,loading=false,queued=false,destroyed=false,timer:number|undefined,lastHistory=0,playCounted=false;
 const setStatus=(m:string,e=false)=>{status.textContent=m;status.dataset.error=String(e);window.setTimeout(()=>{if(status.textContent===m)status.textContent='';},3200)};
 const requireUser=()=>{if(userId)return true;location.assign(`/tap-in.html?next=${encodeURIComponent(location.pathname+location.search)}`);return false;};
 const action=async(name:string,payload:Row)=>{const{data,error}=await supabase.rpc('rb_podcast_action',{p_action:name,p_payload:payload});if(error)throw error;return data as Row;};
 const visible=()=>showId==='all'?(snap.episodes??[]):(snap.episodes??[]).filter(e=>String(e.show_id)===showId);
 const renderComments=()=>{comments.innerHTML=(snap.comments??[]).map(c=>`<article><p>${esc(c.body)}</p><small>${esc(c.display_name||c.username||'Rich Viewer')}</small></article>`).join('')||'<div class="media-ultimate__empty">Start the conversation.</div>';comments.scrollTop=comments.scrollHeight;};
 const renderTabs=()=>{tabs.innerHTML=`<button class="${showId==='all'?'active':''}" data-show="all">ALL SHOWS</button>${(snap.shows??[]).map(s=>`<button class="${showId===String(s.id)?'active':''}" data-show="${s.id}">${esc(s.title)}</button>`).join('')}`;tabs.querySelectorAll<HTMLButtonElement>('[data-show]').forEach(b=>b.onclick=()=>{showId=b.dataset.show||'all';renderTabs();renderQueue();const first=visible()[0];if(first)void openEpisode(first);});};
 const renderQueue=()=>{queue.innerHTML=visible().map(e=>`<button class="podcast-episode ${active?.id===e.id?'active':''}" data-id="${e.id}"><img src="${esc(safe(e.thumbnail_url||e.cover_url||e.show_cover_url||e.live_thumbnail_url)||'/images/brand/IMG_5997.png')}" alt=""><div><h4>${esc(e.title||'Rich Podcast')}</h4><p>${esc(e.show_title||e.display_name||'Rich Original')} · ${e.live_status==='live'?'● LIVE':runtime(e.duration_seconds)} · ${esc((e.media_type||'video').toUpperCase())}</p></div><strong>${fmt(e.play_count)} ▶</strong></button>`).join('')||'<div class="media-ultimate__empty">No episodes in this show.</div>';queue.querySelectorAll<HTMLButtonElement>('[data-id]').forEach(b=>b.onclick=()=>{const e=(snap.episodes??[]).find(x=>String(x.id)===b.dataset.id);if(e)void openEpisode(e);});};
 const persist=async(media:HTMLMediaElement,completed=false)=>{if(!userId||!active)return;const now=Date.now();if(!completed&&now-lastHistory<15000)return;lastHistory=now;try{await action('history',{episode_id:active.id,progress_seconds:Math.floor(completed?(media.duration||0):media.currentTime),completed,media_type:active.media_type||'video',started:!playCounted});playCounted=true;}catch{}};
 const openEpisode=async(e:Row)=>{active=e;playCounted=false;const video=safe(e.video_url||((e.media_type==='video'||!e.media_type)?e.file_url:''));const audio=safe(e.audio_url||((e.media_type==='audio')?e.file_url:''));const poster=safe(e.thumbnail_url||e.cover_url||e.show_cover_url||e.live_thumbnail_url)||'/images/brand/IMG_5997.png';const live=e.live_status==='live'&&e.live_stream_id;stage.innerHTML=`<div class="podcast-screen">${live?`<img src="${esc(poster)}" alt=""><a class="podcast-live-entry" href="/live.html?id=${e.live_stream_id}">● ENTER LIVE PODCAST</a>`:video?`<video id="podcastMedia" src="${esc(video)}" poster="${esc(poster)}" controls playsinline preload="metadata"></video>`:audio?`<img src="${esc(poster)}" alt=""><audio id="podcastMedia" src="${esc(audio)}" controls preload="metadata"></audio>`:`<img src="${esc(poster)}" alt=""><div class="podcast-unavailable">MEDIA PROCESSING</div>`}</div><div class="podcast-video-copy"><span>RICH ORIGINAL · ${esc(e.show_category||'VIDEO PODCAST')}</span><h2>${esc(e.title||'Rich Podcast')}</h2><p>${esc(e.description||'Long-form video conversation, culture and creator stories from the Rich Bizness universe.')}</p><div class="media-ultimate__actions"><button id="podcastLikeBtn" class="media-ultimate__btn">${snap.liked?'♥ LIKED':'♡ LIKE'}</button><a class="media-ultimate__btn" href="/profile.html?id=${esc(e.creator_id||e.user_id)}">HOST PROFILE</a>${e.live_stream_id?`<a class="media-ultimate__btn" href="/live.html?id=${e.live_stream_id}">LIVE ROOM</a>`:''}</div></div>`;
 detail.innerHTML=[['Format',`${esc((e.media_type||'video').toUpperCase())} · ${e.live_status==='live'?'LIVE NOW':runtime(e.duration_seconds)}`],['Show',`${e.show_title||'Rich Original'} · ${e.show_category||'Podcast'}`],['Audience',`${fmt(e.play_count)} plays · ${fmt(e.like_count)} likes · ${fmt(e.comment_count)} comments`],['Distribution',`${e.live_stream_id?'Live connected':'On-demand'} · ${e.is_featured?'Featured':'Original'}`]].map(([l,v])=>`<div class="media-ultimate__row"><div><h5>${l}</h5><p>${esc(v)}</p></div></div>`).join('');
 renderQueue();await load(e.id,false);const media=root.querySelector<HTMLMediaElement>('#podcastMedia');if(media){media.onplay=()=>void persist(media,false);media.ontimeupdate=()=>void persist(media,false);media.onended=()=>void persist(media,true);}root.querySelector<HTMLButtonElement>('#podcastLikeBtn')!.onclick=async()=>{if(!requireUser())return;try{const r=await action('toggle_like',{episode_id:e.id});snap.liked=Boolean(r.liked);await load(e.id,false);}catch(err){setStatus(err instanceof Error?err.message:'Like failed',true);}};history.replaceState({},'',`/podcast.html?id=${encodeURIComponent(e.id)}`);if(commentChannel)await supabase.removeChannel(commentChannel);commentChannel=supabase.channel(`podcast-comments:${e.id}`).on('postgres_changes',{event:'*',schema:'public',table:'podcast_comments',filter:`episode_id=eq.${e.id}`},()=>void load(e.id,false)).subscribe();};
 const render=()=>{const m=snap.metrics??{};metrics.innerHTML=`<article><small>SHOWS</small><strong>${fmt(m.shows)}</strong></article><article><small>VIDEO EPISODES</small><strong>${fmt(m.video_episodes)}</strong></article><article><small>LIVE NOW</small><strong>${fmt(m.live_now)}</strong></article><article><small>EPISODES</small><strong>${fmt(m.episodes)}</strong></article>`;renderTabs();renderQueue();renderComments();};
 const load=async(episodeId?:string,open=true)=>{if(loading){queued=true;return;}loading=true;try{const{data,error}=await supabase.rpc('rb_podcast_snapshot',{p_episode_id:episodeId||active?.id||null,p_limit:100});if(error)throw error;snap=(data??{}) as Snapshot;const requested=episodeId||new URLSearchParams(location.search).get('id')||new URLSearchParams(location.search).get('episode');active=(snap.episodes??[]).find(e=>String(e.id)===String(requested))??active??(snap.episodes??[])[0]??null;render();if(open&&active)await openEpisode(active);}catch(err){setStatus(err instanceof Error?err.message:'Podcast sync failed',true);}finally{loading=false;if(queued&&!destroyed){queued=false;void load(active?.id,false);}}};
 form.onsubmit=async ev=>{ev.preventDefault();if(!active||!requireUser())return;const body=input.value.trim();if(!body)return;const btn=form.querySelector<HTMLButtonElement>('button')!;btn.disabled=true;try{await action('comment',{episode_id:active.id,body});input.value='';await load(active.id,false);}catch(err){setStatus(err instanceof Error?err.message:'Comment failed',true);}finally{btn.disabled=false;}};
 await load(undefined,true);const schedule=()=>{window.clearTimeout(timer);timer=window.setTimeout(()=>void load(active?.id,false),180);};channel=supabase.channel('podcast-video-network').on('postgres_changes',{event:'*',schema:'public',table:'podcast_shows'},schedule).on('postgres_changes',{event:'*',schema:'public',table:'podcast_episodes'},schedule).on('postgres_changes',{event:'*',schema:'public',table:'live_streams',filter:'category=eq.podcast'},schedule).subscribe();
 const cleanup=()=>{if(destroyed)return;destroyed=true;window.clearTimeout(timer);if(channel)void supabase.removeChannel(channel);if(commentChannel)void supabase.removeChannel(commentChannel);delete root.dataset.podcastOwner;};window.addEventListener('pagehide',cleanup,{once:true});window.addEventListener('beforeunload',cleanup,{once:true});
}
