import { supabase } from '../../src/supabase-client.js';
import { getAuthoritativeIdentity } from '../../src/rb-identity.js?v=profile-avatar-separate-1';
import { awardXp } from '../../src/rb-xp.js?v=xp-idempotent-1';
const $=id=>document.getElementById(id),c=$('gymCanvas'),g=c.getContext('2d');
let reps=0,score=0,combo=0,energy=100,form=100,round=1,time=60,running=true,paused=false,phase=0,timer,identity={};
const actions=['push','hold','recover'];
function resize(){const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=r.width*d;c.height=r.height*d;g.setTransform(d,0,0,d,0,0)}
addEventListener('resize',resize);resize();
function sync(){for(const [id,v] of Object.entries({reps,score,combo,energy:Math.round(energy),form:Math.round(form),round,clock:time}))$(id).textContent=Number(v).toLocaleString();$('energyBar').style.width=energy+'%';$('status').textContent=paused?'PAUSED':running?actions[phase].toUpperCase():'WORKOUT COMPLETE';$('missionList').innerHTML='<div class="mission"><span>20 clean reps</span><b>'+Math.min(reps,20)+'/20</b></div><div class="mission"><span>10× combo</span><b>'+Math.min(combo,10)+'/10</b></div><div class="mission"><span>70+ form</span><b>'+Math.round(form)+'/70</b></div>'}
function note(text){$('log').innerHTML='<div>'+text+'</div>'+$('log').innerHTML}
function act(type){if(!running||paused)return;const ok=type===actions[phase];if(ok){if(type!=='recover')reps++;combo++;score+=100+combo*15;form=Math.min(100,form+2);energy=Math.min(100,Math.max(0,energy+(type==='recover'?16:-7)));phase=(phase+1)%3;note(type.toUpperCase()+' CLEAN • '+combo+'×');if(reps&&reps%10===0){round++;score+=500;energy=Math.min(100,energy+20)}}else{combo=0;form=Math.max(0,form-8);energy=Math.max(0,energy-5);note('MISSED FORM')}if(energy<=0){running=false;saveRun('exhausted')}sync()}
function draw(){const w=c.clientWidth,h=c.clientHeight;g.clearRect(0,0,w,h);g.fillStyle='#071009';g.fillRect(0,0,w,h);g.strokeStyle='rgba(157,255,99,.08)';for(let x=0;x<w;x+=42){g.beginPath();g.moveTo(x,0);g.lineTo(x,h);g.stroke()}for(let y=0;y<h;y+=42){g.beginPath();g.moveTo(0,y);g.lineTo(w,y);g.stroke()}g.fillStyle='#9dff63';g.beginPath();g.arc(w/2,h*.34,32,0,Math.PI*2);g.fill();g.strokeStyle='#ffe58a';g.lineWidth=20;g.lineCap='round';g.beginPath();g.moveTo(w/2,h*.42);g.lineTo(w/2,h*.65);g.moveTo(w/2,h*.48);g.lineTo(w/2-90,h*.56);g.moveTo(w/2,h*.48);g.lineTo(w/2+90,h*.56);g.moveTo(w/2,h*.65);g.lineTo(w/2-60,h*.82);g.moveTo(w/2,h*.65);g.lineTo(w/2+60,h*.82);g.stroke();g.fillStyle='#ffe58a';g.font='900 28px system-ui';g.textAlign='center';g.fillText(actions[phase].toUpperCase(),w/2,52);if(!running){g.fillStyle='rgba(0,0,0,.7)';g.fillRect(0,0,w,h);g.fillStyle='#ffe58a';g.font='900 42px system-ui';g.fillText('WORKOUT COMPLETE',w/2,h/2)}}
function loop(){if(running&&!paused)energy=Math.min(100,energy+.015);draw();requestAnimationFrame(loop)}
function reset(){clearInterval(timer);reps=0;score=0;combo=0;energy=100;form=100;round=1;time=60;running=true;paused=false;phase=0;sync();timer=setInterval(()=>{if(running&&!paused){time--;sync();if(time<=0){running=false;clearInterval(timer);saveRun('completed')}}},1000)}
async function saveRun(result){identity=Object.keys(identity).length?identity:await getAuthoritativeIdentity().catch(()=>({}));if(!identity.user)return;const {data:game}=await supabase.from('games').select('id').eq('slug','gym-grind-reps').maybeSingle();const metadata={source:'games/gym-grind-reps',reps,combo,energy:Math.round(energy),form:Math.round(form),round};await supabase.from('game_sessions').insert({game_id:game?.id||null,game_slug:'gym-grind-reps',user_id:identity.user.id,username:identity.profile?.username||null,display_name:identity.profile?.display_name||null,score,result,platform_type:'web',metadata});await supabase.from('game_scores').insert({game_id:game?.id||null,game_slug:'gym-grind-reps',user_id:identity.user.id,username:identity.profile?.username||null,display_name:identity.profile?.display_name||null,score,is_verified:true,platform_type:'web',metadata});await awardXp('gym_grind_reps_run',{section:'gaming',sourceTable:'games',sourceId:game?.id||null}).catch(()=>{});loadLeaderboard();note('RUN SAVED')}
async function loadLeaderboard(){const {data}=await supabase.from('game_scores').select('display_name,username,score').eq('game_slug','gym-grind-reps').eq('is_verified',true).order('score',{ascending:false}).limit(5);$('leaderboard').innerHTML=(data||[]).map((r,i)=>'<div><span>#'+(i+1)+' '+(r.display_name||r.username||'Rich Athlete')+'</span><b>'+Number(r.score||0).toLocaleString()+'</b></div>').join('')||'<div>No verified runs yet.</div>'}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>act(b.dataset.action));addEventListener('keydown',e=>{const m={a:'push',s:'hold',d:'recover'};if(m[e.key.toLowerCase()])act(m[e.key.toLowerCase()])});$('pause').onclick=()=>{paused=!paused;sync()};$('restart').onclick=reset;$('save').onclick=()=>saveRun('manual');loadLeaderboard();reset();loop();