import { supabase } from './supabase-client.js';

const $=(s)=>document.querySelector(s);const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=(v)=>{try{const u=new URL(String(v||''),location.origin);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}};
let mode='tracks',rows=[],selected=null,user=null,profile=null,busy=false,disposed=false,channels=[],reloadTimer=null;

function status(message,tone='ready'){const n=$('#audioStatus');if(n){n.textContent=message;n.dataset.tone=tone}}
function table(){return mode==='tracks'?'music_tracks':mode==='podcasts'?'podcast_episodes':'radio_stations'}
function titleOf(r){return r.title||r.station_name||'Untitled'}
function creatorOf(r){return r.display_name||r.username||'Rich Bizness Creator'}
function audioOf(r){return safeUrl(r.audio_url||r.file_url||r.stream_url)}
function coverOf(r){return safeUrl(r.cover_url)}
function metaOf(r){return [creatorOf(r),r.genre||r.station_tag||'',mode==='radio'?(r.is_live?'LIVE RADIO':'RADIO'):''].filter(Boolean).join(' • ')}
function card(r){const cover=coverOf(r);return `<button class="audio-card" data-id="${esc(r.id)}" aria-current="${selected?.id===r.id}">${cover?`<img src="${esc(cover)}" alt="" loading="lazy">`:'<span class="audio-fallback">RB</span>'}<span><b>${esc(titleOf(r))}</b><small>${esc(metaOf(r))}</small></span><span>▶</span></button>`}
function paintList(){const list=$('#audioList');if(list)list.innerHTML=rows.length?rows.map(card).join(''):'<div class="empty">This audio lane is ready for its first drop.</div>';const metric=$('#audioMetric');if(metric)metric.textContent=rows.length.toLocaleString()}
function paintPlayer(){const title=$('#nowTitle'),meta=$('#nowMeta'),cover=$('#nowCover'),player=$('#audioPlayer');if(!selected){if(title)title.textContent='SELECT A DROP';if(meta)meta.textContent='Tracks, podcasts, and radio live here.';if(player)player.removeAttribute('src');return}if(title)title.textContent=titleOf(selected);if(meta)meta.textContent=metaOf(selected);if(cover){cover.src=coverOf(selected)||'';cover.hidden=!coverOf(selected)}if(player){player.src=audioOf(selected)||'';player.load()}document.querySelectorAll('.audio-card').forEach(n=>n.setAttribute('aria-current',String(n.dataset.id===selected.id)))}
async function identity(){const {data}=await supabase.auth.getUser();user=data?.user||null;if(user){const p=await supabase.from('profiles').select('id,username,display_name').eq('id',user.id).maybeSingle();profile=p.data||null}}
async function load(){if(!supabase||disposed)return;status('SYNCING AUDIO');try{let q=supabase.from(table()).select('*').order('created_at',{ascending:false}).limit(50);if(mode==='tracks'||mode==='podcasts')q=q.eq('is_published',true);else q=q.eq('is_public',true);const {data,error}=await q;if(error)throw error;rows=data||[];if(selected)selected=rows.find(r=>r.id===selected.id)||rows[0]||null;else selected=rows[0]||null;paintList();paintPlayer();status('CONNECTED • ONE AUDIO OWNER')}catch(e){status(`SYNC ERROR • ${e.message}`,'error')}}
function schedule(){clearTimeout(reloadTimer);reloadTimer=setTimeout(load,180)}
function stopChannels(){channels.forEach(c=>supabase.removeChannel(c));channels=[]}
function realtime(){stopChannels();channels.push(supabase.channel(`rb-audio:${mode}`).on('postgres_changes',{event:'*',schema:'public',table:table()},schedule).subscribe())}
function switchMode(next){mode=next;selected=null;document.querySelectorAll('[data-mode]').forEach(n=>n.setAttribute('aria-pressed',String(n.dataset.mode===mode)));load();realtime()}
async function uploadTo(bucket,file,label){if(!file)return'';const ext=(file.name.split('.').pop()||'bin').replace(/[^a-z0-9]/gi,'').toLowerCase();const path=`${user.id}/${Date.now()}-${label}.${ext}`;const {error}=await supabase.storage.from(bucket).upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type||undefined});if(error)throw error;return supabase.storage.from(bucket).getPublicUrl(path).data.publicUrl||''}
async function publish(event){event.preventDefault();if(busy)return;if(!user)return status('TAP IN TO DROP AUDIO','error');if(mode==='radio')return status('RADIO STATIONS USE STREAM LINKS, NOT FILE DROPS','error');const title=String($('#dropTitle')?.value||'').trim();const audioFile=$('#audioFile')?.files?.[0];const coverFile=$('#coverFile')?.files?.[0];if(!title||!audioFile)return status('ADD A TITLE AND AUDIO FILE','error');if(!String(audioFile.type).startsWith('audio/'))return status('AUDIO FILE REQUIRED','error');busy=true;$('#dropSubmit').disabled=true;status('UPLOADING AUDIO');try{const audioBucket=mode==='podcasts'?'podcast-audio':'music-audio';const coverBucket=mode==='podcasts'?'podcast-covers':'music-covers';const audioUrl=await uploadTo(audioBucket,audioFile,'audio');const coverUrl=coverFile?await uploadTo(coverBucket,coverFile,'cover'):'';const common={user_id:user.id,username:profile?.username||user.email?.split('@')[0]||'member',display_name:profile?.display_name||user.user_metadata?.display_name||'Rich Bizness Creator',title,description:String($('#dropDescription')?.value||'').trim(),audio_url:audioUrl,file_url:audioUrl,cover_url:coverUrl||null,visibility:'public',metadata:{source:'audio-owner'}};let payload,insertTable;if(mode==='podcasts'){insertTable='podcast_episodes';payload={...common,creator_id:user.id,episode_number:Number($('#episodeNumber')?.value||1),season_number:1,is_published:true,is_featured:false,is_explicit:false}}else{insertTable='music_tracks';payload={...common,artist_user_id:user.id,genre:String($('#dropGenre')?.value||'').trim(),mood:'rich',is_published:true,is_featured:false,is_explicit:false}}const {error}=await supabase.from(insertTable).insert(payload);if(error)throw error;event.currentTarget.reset();status('AUDIO DROP LIVE');await load()}catch(e){status(`DROP FAILED • ${e.message}`,'error')}finally{busy=false;$('#dropSubmit').disabled=false}}
async function addComment(event){event.preventDefault();if(!user||!selected)return status('TAP IN AND SELECT AUDIO','error');const text=String($('#commentInput')?.value||'').trim();if(!text)return;if(mode==='radio')return status('RADIO COMMENTS ARE NOT ENABLED','error');const target=mode==='tracks'?'music_comments':'podcast_comments';const payload=mode==='tracks'?{track_id:selected.id,user_id:user.id,username:profile?.username||'member',display_name:profile?.display_name||'Rich Bizness Member',comment:text}:{episode_id:selected.id,user_id:user.id,username:profile?.username||'member',display_name:profile?.display_name||'Rich Bizness Member',body:text};const {error}=await supabase.from(target).insert(payload);if(error)return status(`COMMENT FAILED • ${error.message}`,'error');$('#commentInput').value='';status('COMMENT DROPPED')}
function bind(){document.addEventListener('click',e=>{const tab=e.target.closest('[data-mode]');if(tab)return switchMode(tab.dataset.mode);const item=e.target.closest('.audio-card');if(item){selected=rows.find(r=>r.id===item.dataset.id)||null;paintPlayer();$('#audioPlayer')?.play().catch(()=>{})}});$('#dropForm')?.addEventListener('submit',publish);$('#commentForm')?.addEventListener('submit',addComment)}
function cleanup(){disposed=true;clearTimeout(reloadTimer);stopChannels()}
async function boot(){if(!supabase)return status('SUPABASE ENV VARIABLES REQUIRED','error');await identity();bind();await load();realtime();window.addEventListener('pagehide',cleanup,{once:true})}
boot();