import { supabase } from './supabase-client.js';
import { awardXp } from './rb-xp.js?v=no-floating-badge-1';
import { getAuthoritativeIdentity } from './rb-identity.js?v=identity-public-1';
import { sectionFor } from './rb-schema-map.js';

const key = document.body?.dataset?.section || 'music';
const cfg = sectionFor(key) || sectionFor('music');
const ownerTables = cfg?.tables || [];
const primary = cfg?.primaryTable || 'music_tracks';
let records = [], counts = {}, active = null, audio = null, user = null;
const $ = (s) => document.querySelector(s);
const fmt = (n) => Number(n || 0).toLocaleString();
const titles = { music:'MUSIC DISTRICT', radio:'RB RADIO', podcast:'PODCAST ARENA' };
const subtitles = { music:'Tracks, playlists, plays, likes, comments, and creator audio.', radio:'Stations, sessions, listeners, and live radio likes.', podcast:'Shows, episodes, audio, covers, likes, and comments.' };
function addCss(){ if(document.getElementById('audioOwnerCss')) return; const l=document.createElement('link'); l.id='audioOwnerCss'; l.rel='stylesheet'; l.href='/src/audio-owner.css?v=audio-owner-1'; document.head.appendChild(l); }
function media(row){ return row.audio_url || row.stream_url || row.file_url || row.media_url || row.url || row.metadata?.audio_url || row.metadata?.stream_url || ''; }
function cover(row){ return row.cover_url || row.thumbnail_url || row.image_url || row.artwork_url || row.metadata?.cover_url || ''; }
function name(row){ return row.title || row.name || row.station_name || row.show_title || row.episode_title || 'Rich Audio'; }
function note(row){ return row.description || row.caption || row.genre || row.category || row.status || 'Rich Bizness audio record'; }
async function getUser(){ const state = await getAuthoritativeIdentity(); user = state.user || null; return user; }
async function countTable(table){ try { const { count } = await supabase.from(table).select('*', { count:'exact', head:true }); return count || 0; } catch(_) { return 0; } }
async function loadCounts(){ const pairs = await Promise.all(ownerTables.map(async (t)=>[t, await countTable(t)])); counts = Object.fromEntries(pairs); renderSystems(); const total = $('#audioOwnerCount') || $('#recordCount'); if(total) total.textContent = fmt(records.length || counts[primary] || 0); const owned = $('#audioTables'); if(owned) owned.textContent = String(ownerTables.length); }
async function loadRecords(){ let query = supabase.from(primary).select('*').limit(40); try { query = query.order('created_at', { ascending:false }); } catch(_) {} const { data } = await query; records = data || []; active = records[0] || null; render(); await loadCounts(); }
function mount(){ if(document.getElementById('audioOwner')) return; const main = document.querySelector('main') || document.body; const panel = document.createElement('section'); panel.id='audioOwner'; panel.className='audio-owner'; panel.innerHTML=`<div class="audio-head"><div><small>${key.toUpperCase()} OWNER</small><b>${titles[key] || 'RICH AUDIO'}</b><p>${subtitles[key] || 'Audio system connected.'}</p></div><small id="audioStatus">READY</small></div><div class="audio-player"><div class="audio-cover" id="audioCover">RB</div><div class="audio-meta"><b id="audioTitle">${titles[key] || 'RICH AUDIO'}</b><p id="audioNote">Pick a record to play.</p><audio id="audioEl" controls playsinline></audio></div></div><div class="audio-actions"><button id="playAudio" type="button">PLAY</button><button id="likeAudio" type="button">LIKE</button><button id="logPlay" type="button">LOG PLAY</button><a href="/upload.html?section=${key}">DROP AUDIO</a><a href="/music.html">MUSIC</a><a href="/radio.html">RADIO</a><a href="/podcast.html">PODCAST</a></div><div class="audio-systems" id="audioSystems"></div><div class="audio-list" id="audioList"></div>`; main.appendChild(panel); audio = $('#audioEl'); $('#playAudio')?.addEventListener('click', play); $('#likeAudio')?.addEventListener('click', like); $('#logPlay')?.addEventListener('click', logPlay); }
function renderSystems(){ const box = $('#audioSystems') || $('#schemaPanel'); if(!box) return; box.innerHTML = ownerTables.map((t)=>`<article class="audio-system"><b>${t.replaceAll('_',' ').toUpperCase()}</b><small>${fmt(counts[t])} records</small></article>`).join(''); }
function render(){ const list = $('#audioList') || $('#sectionCards'); if(list) list.innerHTML = records.length ? records.map((r,i)=>`<article class="audio-tile ${active?.id===r.id?'active':''}" data-audio-i="${i}">${cover(r)?`<img src="${cover(r)}" alt="">`:'<div class="audio-mini">RB</div>'}<div><b>${name(r)}</b><p>${note(r)}</p><small>${key.toUpperCase()} • ${media(r)?'PLAYABLE':'RECORD'}</small></div></article>`).join('') : `<article class="audio-tile"><b>No ${key} records yet</b><p>Use DROP AUDIO to route the first record.</p></article>`; document.querySelectorAll('[data-audio-i]').forEach(el=>el.addEventListener('click',()=>select(Number(el.dataset.audioI)))); if(active) select(records.indexOf(active)); }
function select(i){ active = records[i] || records[0] || null; if(!active) return; const url = media(active); const img = cover(active); if($('#audioTitle')) $('#audioTitle').textContent = name(active); if($('#audioNote')) $('#audioNote').textContent = note(active); if($('#audioCover')) { $('#audioCover').innerHTML = img ? `<img src="${img}" alt="">` : 'RB'; } if(audio) audio.src = url || ''; document.querySelectorAll('[data-audio-i]').forEach(el=>el.classList.toggle('active', Number(el.dataset.audioI)===i)); }
async function play(){ if(!active) return; if(audio?.src) audio.play().catch(()=>{}); await logPlay(); }
async function logPlay(){ await getUser(); if(!user || !active) { if(!user) location.href='/auth.html'; return; } const table = key === 'music' ? 'music_play_events' : key === 'radio' ? 'radio_sessions' : 'podcast_likes'; const row = key === 'music' ? { track_id: active.id, user_id:user.id, metadata:{source:'audio-owner'} } : key === 'radio' ? { station_id: active.id, user_id:user.id, metadata:{source:'audio-owner'} } : { episode_id: active.id, user_id:user.id, metadata:{source:'audio-owner', action:'play'} }; await supabase.from(table).insert(row).then(()=>{},()=>{}); await awardXp(`${key}_play`, { section:key, sourceTable:primary, sourceId:active.id }).catch(()=>{}); if($('#audioStatus')) $('#audioStatus').textContent='PLAY LOGGED'; loadCounts(); }
async function like(){ await getUser(); if(!user || !active) { if(!user) location.href='/auth.html'; return; } const table = key === 'music' ? 'music_likes' : key === 'radio' ? 'radio_likes' : 'podcast_likes'; const idKey = key === 'music' ? 'track_id' : key === 'radio' ? 'station_id' : 'episode_id'; await supabase.from(table).insert({ [idKey]: active.id, user_id:user.id, metadata:{source:'audio-owner'} }).then(()=>{},()=>{}); if($('#audioStatus')) $('#audioStatus').textContent='LIKED'; loadCounts(); }
addCss(); mount(); loadRecords(); supabase.channel('audio-owner-' + key).on('postgres_changes', { event:'*', schema:'public', table:primary }, loadRecords).subscribe();