import { supabase } from './supabase-client.js';

const $=(s)=>document.querySelector(s);const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=(v)=>{try{const u=new URL(String(v||''),location.origin);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}};
const params=new URLSearchParams(location.search);
let mode=['tracks','podcasts','radio'].includes(params.get('mode'))?params.get('mode'):'tracks',rows=[],selected=null,user=null,profile=null,busy=false,disposed=false,channels=[],reloadTimer=null,historyTimer=null,liked=false,inPlaylist=false,reconnectTimer=null;

function status(message,tone='ready'){const n=$('#audioStatus');if(n){n.textContent=message;n.dataset.tone=tone}}
function playerState(message,tone='ready'){const n=$('#playerState');if(n){n.textContent=message;n.dataset.tone=tone}}
function connection(message,tone='ready'){const n=$('#audioConnection');if(n){n.textContent=message;n.dataset.tone=tone}}
function table(){return mode==='tracks'?'music_tracks':mode==='podcasts'?'podcast_episodes':'radio_stations'}
function titleOf(r){return r?.title||r?.station_name||'Untitled'}
function creatorOf(r){return r?.display_name||r?.username||'Rich Bizness Creator'}
function audioOf(r){return safeUrl(r?.audio_url||r?.file_url||r?.stream_url)}
function coverOf(r){return safeUrl(r?.cover_url)}
function metaOf(r){return [creatorOf(r),r?.genre||r?.station_tag||'',mode==='radio'?(r?.is_live?'LIVE RADIO':'RADIO'):mode==='podcasts'&&r?.episode_number?`EPISODE ${r.episode_number}`:''].filter(Boolean).join(' • ')}
function card(r){const cover=coverOf(r);return `<button class="audio-card" data-id="${esc(r.id)}" aria-current="${selected?.id===r.id}">${cover?`<img src="${esc(cover)}" alt="" loading="lazy" decoding="async">`:'<span class="audio-fallback">RB</span>'}<span><b>${esc(titleOf(r))}</b><small>${esc(metaOf(r))}</small></span><span>▶</span></button>`}
function paintList(){const list=$('#audioList');if(list)list.innerHTML=rows.length?rows.map(card).join(''):'<div class="empty">This audio lane is ready for its first drop.</div>';const metric=$('#audioMetric');if(metric)metric.textContent=rows.length.toLocaleString()}
function currentIndex(){return selected?rows.findIndex(r=>r.id===selected.id):-1}
function setProgress(value){const n=$('#audioProgress');if(n)n.style.width=`${Math.max(0,Math.min(100,Number(value)||0))}%`}

async function identity(){const {data,error}=await supabase.auth.getUser();if(error)throw error;user=data?.user||null;if(user){const p=await supabase.from('profiles').select('id,username,display_name').eq('id',user.id).maybeSingle();profile=p.data||null}}
async function rotation(){inPlaylist=false;if(!user||!selected||mode!=='tracks')return paintLike();const {data:playlist}=await supabase.from('playlists').select('id').eq('user_id',user.id).eq('title','My Rotation').maybeSingle();if(!playlist)return paintLike();const {data}=await supabase.from('playlist_tracks').select('id').eq('playlist_id',playlist.id).eq('track_id',selected.id).maybeSingle();inPlaylist=!!data;paintLike()}
async function refreshLike(){liked=false;if(!user||!selected){paintLike();return}const likeTable=mode==='tracks'?'music_likes':mode==='podcasts'?'podcast_likes':'radio_likes';const key=mode==='tracks'?'track_id':mode==='podcasts'?'episode_id':'station_id';const {data}=await supabase.from(likeTable).select('id').eq(key,selected.id).eq('user_id',user.id).maybeSingle();liked=!!data;paintLike();if(mode==='tracks')rotation()}
function paintLike(){const button=$('#likeButton');if(button){button.textContent=liked?'LIKED':'LIKE';button.setAttribute('aria-pressed',String(liked))}const add=$('#playlistButton'),remove=$('#removePlaylistButton');if(add)add.hidden=mode!=='tracks'||inPlaylist;if(remove)remove.hidden=mode!=='tracks'||!inPlaylist}
function updateMediaSession(){if(!('mediaSession'in navigator)||!selected)return;try{navigator.mediaSession.metadata=new MediaMetadata({title:titleOf(selected),artist:creatorOf(selected),album:mode==='radio'?'Rich Radio':mode==='podcasts'?'Rich Podcasts':'Rich Sound',artwork:coverOf(selected)?[{src:coverOf(selected),sizes:'512x512'}]:[]})}catch{}}
async function restoreProgress(){if(!user||!selected||mode==='radio')return;const type=mode==='tracks'?'track':'podcast';const {data}=await supabase.from('audio_listening_history').select('progress_seconds,completed').eq('user_id',user.id).eq('source_type',type).eq('source_id',selected.id).maybeSingle();const player=$('#audioPlayer');if(data&&player&&!data.completed&&Number(data.progress_seconds)>0){const resume=()=>{player.currentTime=Math.max(0,Number(data.progress_seconds)||0);player.removeEventListener('loadedmetadata',resume)};player.addEventListener('loadedmetadata',resume)}}
function paintPlayer(){const title=$('#nowTitle'),meta=$('#nowMeta'),cover=$('#nowCover'),fallback=$('#coverFallback'),player=$('#audioPlayer');if(!selected){if(title)title.textContent='SELECT A DROP';if(meta)meta.textContent='Tracks, podcasts, and radio live here.';if(player){player.pause();player.removeAttribute('src');player.load()}if(cover)cover.hidden=true;if(fallback)fallback.hidden=false;paintLike();return}if(title)title.textContent=titleOf(selected);if(meta)meta.textContent=metaOf(selected);const coverUrl=coverOf(selected);if(cover){cover.src=coverUrl||'';cover.hidden=!coverUrl;cover.onerror=()=>{cover.hidden=true;if(fallback)fallback.hidden=false}}if(fallback)fallback.hidden=!!coverUrl;if(player){player.src=audioOf(selected)||'';player.load();playerState(audioOf(selected)?'READY TO PLAY':'AUDIO UNAVAILABLE',audioOf(selected)?'ready':'error')}document.querySelectorAll('.audio-card').forEach(n=>n.setAttribute('aria-current',String(n.dataset.id===selected.id)));updateMediaSession();refreshLike();restoreProgress();loadComments();history.replaceState({},'',`/music.html?mode=${encodeURIComponent(mode)}&id=${encodeURIComponent(selected.id)}`)}

async function loadComments(){const list=$('#commentList');if(!list)return;if(!selected||mode==='radio'){list.innerHTML=`<div class="empty">${mode==='radio'?'Radio comments are not enabled.':'Select audio to load comments.'}</div>`;return}const target=mode==='tracks'?'music_comments':'podcast_comments';const key=mode==='tracks'?'track_id':'episode_id';const {data,error}=await supabase.from(target).select('*').eq(key,selected.id).order('created_at',{ascending:false}).limit(40);if(error){list.innerHTML='<div class="empty">Comments could not load.</div>';return}list.innerHTML=(data||[]).length?(data||[]).map(r=>`<article class="comment"><b>${esc(r.display_name||r.username||'Rich Member')}</b><p>${esc(r.comment||r.body||'')}</p></article>`).join(''):'<div class="empty">Be the first to talk your talk.</div>'}
async function load(){if(!supabase||disposed)return;status('SYNCING AUDIO');try{let q=supabase.from(table()).select('*').order('created_at',{ascending:false}).limit(50);if(mode==='tracks'||mode==='podcasts')q=q.eq('is_published',true).eq('visibility','public');else q=q.eq('is_public',true);const {data,error}=await q;if(error)throw error;rows=data||[];const requested=params.get('id')||new URLSearchParams(location.search).get('id');selected=requested?rows.find(r=>r.id===requested)||selected: selected?rows.find(r=>r.id===selected.id):null;selected=selected||rows[0]||null;paintList();paintPlayer();status('CONNECTED • ONE AUDIO OWNER')}catch(e){status(`SYNC ERROR • ${e.message}`,'error')}}
function schedule(){clearTimeout(reloadTimer);reloadTimer=setTimeout(load,180)}
function stopChannels(){channels.forEach(c=>supabase.removeChannel(c));channels=[]}
function realtime(){stopChannels();const tables=[table()];if(mode==='tracks')tables.push('music_comments','music_likes');if(mode==='podcasts')tables.push('podcast_comments','podcast_likes');if(mode==='radio')tables.push('radio_likes');tables.forEach((name,i)=>channels.push(supabase.channel(`rb-audio:${mode}:${i}`).on('postgres_changes',{event:'*',schema:'public',table:name},schedule).subscribe(s=>connection(s==='SUBSCRIBED'?'REALTIME CONNECTED':s==='CHANNEL_ERROR'?'REALTIME RECOVERING':s,s==='CHANNEL_ERROR'?'error':'ready')))}
function switchMode(next){if(next===mode)return;mode=next;selected=null;params.set('mode',mode);params.delete('id');document.querySelectorAll('[data-mode]').forEach(n=>n.setAttribute('aria-pressed',String(n.dataset.mode===mode)));load();realtime()}
async function uploadTo(bucket,file,label){if(!file)return'';const ext=(file.name.split('.').pop()||'bin').replace(/[^a-z0-9]/gi,'').toLowerCase();const path=`${user.id}/${Date.now()}-${label}.${ext}`;const {error}=await supabase.storage.from(bucket).upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type||undefined});if(error)throw error;return supabase.storage.from(bucket).getPublicUrl(path).data.publicUrl||''}
async function publish(event){event.preventDefault();if(busy)return;if(!user)return status('TAP IN TO DROP AUDIO','error');if(mode==='radio')return status('RADIO STATIONS USE STREAM LINKS, NOT FILE DROPS','error');const title=String($('#dropTitle')?.value||'').trim();const audioFile=$('#audioFile')?.files?.[0];const coverFile=$('#coverFile')?.files?.[0];if(!title||!audioFile)return status('ADD A TITLE AND AUDIO FILE','error');if(!String(audioFile.type).startsWith('audio/'))return status('AUDIO FILE REQUIRED','error');busy=true;$('#dropSubmit').disabled=true;setProgress(8);status('UPLOADING AUDIO');try{const audioBucket=mode==='podcasts'?'podcast-audio':'music-audio';const coverBucket=mode==='podcasts'?'podcast-covers':'music-covers';const audioUrl=await uploadTo(audioBucket,audioFile,'audio');setProgress(55);const coverUrl=coverFile?await uploadTo(coverBucket,coverFile,'cover'):'';const common={user_id:user.id,username:profile?.username||user.email?.split('@')[0]||'member',display_name:profile?.display_name||user.user_metadata?.display_name||'Rich Bizness Creator',title,description:String($('#dropDescription')?.value||'').trim(),audio_url:audioUrl,file_url:audioUrl,cover_url:coverUrl||null,visibility:'public',metadata:{source:'audio-owner'}};const insertTable=mode==='podcasts'?'podcast_episodes':'music_tracks';const payload=mode==='podcasts'?{...common,creator_id:user.id,episode_number:Number($('#episodeNumber')?.value||1),season_number:1,is_published:true,is_featured:false,is_explicit:false}:{...common,artist_user_id:user.id,genre:String($('#dropGenre')?.value||'').trim(),mood:'rich',is_published:true,is_featured:false,is_explicit:false};const {error}=await supabase.from(insertTable).insert(payload);if(error)throw error;setProgress(100);event.currentTarget.reset();status('AUDIO DROP LIVE');await load()}catch(e){status(`DROP FAILED • ${e.message}`,'error')}finally{busy=false;$('#dropSubmit').disabled=false;setTimeout(()=>setProgress(0),900)}}
async function addComment(event){event.preventDefault();if(!user||!selected)return status('TAP IN AND SELECT AUDIO','error');const text=String($('#commentInput')?.value||'').trim();if(!text)return;if(mode==='radio')return status('RADIO COMMENTS ARE NOT ENABLED','error');const target=mode==='tracks'?'music_comments':'podcast_comments';const payload=mode==='tracks'?{track_id:selected.id,user_id:user.id,username:profile?.username||'member',display_name:profile?.display_name||'Rich Bizness Member',comment:text}:{episode_id:selected.id,user_id:user.id,username:profile?.username||'member',display_name:profile?.display_name||'Rich Bizness Member',body:text};const {error}=await supabase.from(target).insert(payload);if(error)return status(`COMMENT FAILED • ${error.message}`,'error');$('#commentInput').value='';status('COMMENT DROPPED');loadComments()}
async function toggleLike(){if(!user||!selected)return status('TAP IN TO LIKE AUDIO','error');const likeTable=mode==='tracks'?'music_likes':mode==='podcasts'?'podcast_likes':'radio_likes';const key=mode==='tracks'?'track_id':mode==='podcasts'?'episode_id':'station_id';const result=liked?await supabase.from(likeTable).delete().eq(key,selected.id).eq('user_id',user.id):await supabase.from(likeTable).insert({[key]:selected.id,user_id:user.id});if(result.error)return status(`LIKE FAILED • ${result.error.message}`,'error');liked=!liked;paintLike();status(liked?'ADDED TO LIKES':'REMOVED FROM LIKES')}
async function ensureRotation(){let {data:playlist,error}=await supabase.from('playlists').select('id').eq('user_id',user.id).eq('title','My Rotation').maybeSingle();if(error)throw error;if(!playlist){const created=await supabase.from('playlists').insert({user_id:user.id,username:profile?.username||'member',display_name:profile?.display_name||'Rich Bizness Member',title:'My Rotation',description:'Saved from Rich Sound',visibility:'private',track_count:0,like_count:0,play_count:0,is_featured:false,metadata:{source:'audio-owner'}}).select('id').single();if(created.error)throw created.error;playlist=created.data}return playlist}
async function addToPlaylist(){if(!user||!selected||mode!=='tracks')return status('SELECT A TRACK FIRST','error');try{const playlist=await ensureRotation();const {error}=await supabase.from('playlist_tracks').upsert({playlist_id:playlist.id,track_id:selected.id,position:0},{onConflict:'playlist_id,track_id',ignoreDuplicates:true});if(error)throw error;inPlaylist=true;paintLike();status('TRACK SAVED TO MY ROTATION')}catch(e){status(`PLAYLIST FAILED • ${e.message}`,'error')}}
async function removeFromPlaylist(){if(!user||!selected||mode!=='tracks')return;try{const playlist=await ensureRotation();const {error}=await supabase.from('playlist_tracks').delete().eq('playlist_id',playlist.id).eq('track_id',selected.id);if(error)throw error;inPlaylist=false;paintLike();status('TRACK REMOVED FROM MY ROTATION')}catch(e){status(`PLAYLIST FAILED • ${e.message}`,'error')}}
async function recordHistory(completed=false){if(!user||!selected)return;const player=$('#audioPlayer');await supabase.from('audio_listening_history').upsert({user_id:user.id,source_type:mode==='tracks'?'track':mode==='podcasts'?'podcast':'radio',source_id:selected.id,progress_seconds:Math.floor(player?.currentTime||0),completed,last_played_at:new Date().toISOString(),metadata:{title:titleOf(selected)}},{onConflict:'user_id,source_type,source_id'})}
async function shareSelected(){if(!selected)return status('SELECT AUDIO FIRST','error');const url=`${location.origin}/music.html?mode=${encodeURIComponent(mode)}&id=${encodeURIComponent(selected.id)}`;if(navigator.share)await navigator.share({title:titleOf(selected),url}).catch(()=>{});else await navigator.clipboard?.writeText(url);status('SHARE LINK READY')}
function selectRelative(delta){if(!rows.length)return;const index=currentIndex();selected=rows[(index+delta+rows.length)%rows.length];paintPlayer();$('#audioPlayer')?.play().catch(()=>playerState('TAP PLAY TO START','error'))}
function bindMediaSession(){if(!('mediaSession'in navigator))return;try{navigator.mediaSession.setActionHandler('play',()=>$('#audioPlayer')?.play());navigator.mediaSession.setActionHandler('pause',()=>$('#audioPlayer')?.pause());navigator.mediaSession.setActionHandler('previoustrack',()=>selectRelative(-1));navigator.mediaSession.setActionHandler('nexttrack',()=>selectRelative(1));navigator.mediaSession.setActionHandler('seekto',e=>{const p=$('#audioPlayer');if(p&&Number.isFinite(e.seekTime))p.currentTime=e.seekTime})}catch{}}
function bind(){document.addEventListener('click',e=>{const tab=e.target.closest('[data-mode]');if(tab)return switchMode(tab.dataset.mode);const item=e.target.closest('.audio-card');if(item){selected=rows.find(r=>r.id===item.dataset.id)||null;paintPlayer();$('#audioPlayer')?.play().catch(()=>playerState('TAP PLAY TO START','error'))}});$('#dropForm')?.addEventListener('submit',publish);$('#commentForm')?.addEventListener('submit',addComment);$('#likeButton')?.addEventListener('click',toggleLike);$('#playlistButton')?.addEventListener('click',addToPlaylist);$('#removePlaylistButton')?.addEventListener('click',removeFromPlaylist);$('#shareButton')?.addEventListener('click',shareSelected);$('#previousButton')?.addEventListener('click',()=>selectRelative(-1));$('#nextButton')?.addEventListener('click',()=>selectRelative(1));$('#playButton')?.addEventListener('click',()=>{const p=$('#audioPlayer');if(!p)return;p.paused?p.play():p.pause()});const p=$('#audioPlayer');p?.addEventListener('play',()=>{playerState(mode==='radio'?'RADIO LIVE':'PLAYING');$('#playButton').textContent='PAUSE';recordHistory()});p?.addEventListener('pause',()=>{playerState('PAUSED');$('#playButton').textContent='PLAY';recordHistory()});p?.addEventListener('waiting',()=>playerState('BUFFERING'));p?.addEventListener('playing',()=>playerState(mode==='radio'?'RADIO LIVE':'PLAYING'));p?.addEventListener('error',()=>{playerState('AUDIO UNAVAILABLE','error');if(mode==='radio'){clearTimeout(reconnectTimer);reconnectTimer=setTimeout(()=>{if(selected&&!disposed){p.load();p.play().catch(()=>{})}},3000)}});p?.addEventListener('ended',()=>{recordHistory(true);mode==='radio'?playerState('RADIO DISCONNECTED','error'):selectRelative(1)});p?.addEventListener('timeupdate',()=>{clearTimeout(historyTimer);historyTimer=setTimeout(()=>recordHistory(false),1500)});window.addEventListener('online',()=>{connection('ONLINE');if(mode==='radio'&&selected&&p?.paused)p.play().catch(()=>{})});window.addEventListener('offline',()=>connection('OFFLINE','error'));document.addEventListener('visibilitychange',()=>{if(!document.hidden&&mode==='radio'&&selected&&p?.paused)p.play().catch(()=>{})});bindMediaSession()}
function cleanup(){disposed=true;clearTimeout(reloadTimer);clearTimeout(historyTimer);clearTimeout(reconnectTimer);recordHistory(false);stopChannels()}
async function boot(){if(!supabase)return status('SUPABASE ENV VARIABLES REQUIRED','error');try{await identity();bind();document.querySelectorAll('[data-mode]').forEach(n=>n.setAttribute('aria-pressed',String(n.dataset.mode===mode)));await load();realtime();connection(navigator.onLine?'ONLINE':'OFFLINE',navigator.onLine?'ready':'error');window.addEventListener('pagehide',cleanup,{once:true})}catch(e){status(`BOOT FAILED • ${e.message}`,'error')}}
boot();