const env = import.meta.env || {};

export const RB_CONFIG = Object.freeze({
  app: Object.freeze({ name: 'Rich Bizness Universe', brand: 'Rich Bizness LLC', version: '1.0.0-rebuild' }),
  supabase: Object.freeze({ url: env.VITE_SUPABASE_URL || '', publishableKey: env.VITE_SUPABASE_PUBLISHABLE_KEY || '' }),
  routes: Object.freeze({ home:'/',feed:'/feed.html',live:'/live.html',watch:'/watch.html',gallery:'/gallery.html',music:'/music.html',upload:'/upload.html',gaming:'/gaming.html',sports:'/sports.html',meta:'/meta.html',store:'/store.html',creator:'/creator.html',admin:'/admin.html',messages:'/messages.html',notifications:'/notifications.html',search:'/search.html',profile:'/profile.html',edit:'/edit.html',avatar:'/avatar.html',settings:'/settings.html',auth:'/auth.html',onboarding:'/onboarding.html',health:'/health.html' }),
  tables: Object.freeze({
    profiles:'profiles',followers:'followers',feedPosts:'feed_posts',feedLikes:'feed_post_likes',feedComments:'feed_comments',feedViews:'feed_post_views',
    liveStreams:'live_streams',liveRecordings:'live_recordings',liveChatMessages:'live_chat_messages',liveReactions:'live_reactions',
    musicTracks:'music_tracks',musicLikes:'music_likes',musicComments:'music_comments',podcastEpisodes:'podcast_episodes',podcastComments:'podcast_comments',podcastLikes:'podcast_likes',radioStations:'radio_stations',radioLikes:'radio_likes',playlists:'playlists',playlistTracks:'playlist_tracks',audioHistory:'audio_listening_history',
    games:'games',gameRooms:'game_rooms',gameScores:'game_scores',gameComments:'game_comments',gameLikes:'game_likes',gameClips:'game_clips',gamingUploads:'gaming_uploads',gamerProfiles:'gamer_profiles',
    sportsPosts:'sports_posts',sportsComments:'sports_comments',sportsUploads:'sports_uploads',sportsProfiles:'sports_profiles',
    metaWorlds:'meta_worlds',metaWorldLikes:'meta_world_likes',metaPortals:'meta_portals',metaAvatars:'meta_avatars',
    products:'products',productLikes:'product_likes',productViews:'product_views',storeComments:'store_comments',storeCartItems:'store_cart_items',storeOrders:'store_orders',storeSellerProfiles:'store_seller_profiles',productUnlocks:'user_product_unlocks',creatorBalances:'creator_available_balances',
    dmThreads:'dm_threads',dmMembers:'dm_thread_members',dmMessages:'dm_messages',dmAttachments:'dm_message_attachments',dmReactions:'dm_message_reactions',dmReads:'dm_message_reads',dmTyping:'dm_typing_status',dmCalls:'dm_call_sessions',dmCallParticipants:'dm_call_participants',richNotifications:'rich_notifications',notificationGroups:'notification_groups',notificationReads:'notification_reads',searchQueries:'search_queries',searchClicks:'search_clicks',uploads:'uploads',storageRoutes:'storage_bucket_routes',userLevels:'user_levels',userXpLedger:'user_xp_ledger',badges:'badges',userBadges:'user_badges',userSettings:'user_settings',profileThemes:'profile_theme_settings',creatorPages:'creator_page_settings',creatorAlerts:'creator_alert_subscriptions',announcements:'platform_announcements',moderationReports:'moderation_reports',contentReview:'content_review_queue',featureFlags:'feature_flags',systemHealth:'system_health_checks',adminRoles:'admin_roles',adminAuditLogs:'admin_audit_logs'
  })
});