import { supabase } from './supabase-client.js';
import { awardXp } from './rb-xp.js?v=xp-idempotent-1';
import { getAuthoritativeIdentity, ensureProfile } from './rb-identity.js?v=profile-avatar-separate-1';
import './section-language-foundation.js?v=copy-only-1';

const key = document.body?.dataset?.section || 'feed';
const isUpload = key === 'upload';
const $ = (s) => document.querySelector(s);
let user = null;
let profile = null;
let pickedFile = null;
let selectedRoute = new URL(location.href).searchParams.get('section') || 'feed';
const routes = [['feed','feed_posts','RICH FEED'],['gallery','feed_posts','GALLERY'],['music','music_tracks','MUSIC'],['podcast','podcast_episodes','PODCAST'],['radio','radio_stations','RB RADIO'],['sports','sports_posts','SPORTS'],['gaming','game_clips','GAMING'],['store-product','products','STORE'],['store-digital','products','DIGITAL']];
const esc = (v = '') => String(v ?? '').replace(/[&<>"']/g, (m) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[m]));
function authProfileUrl(row){ if(row.user_id) return `/profile.html?id=${encodeURIComponent(row.user_id)}`; if(row.username) return `/profile.html?u=${encodeURIComponent(row.username)}`; return '/profile.html'; }
async function auth(){ const state = await getAuthoritativeIdentity(); user = state.user || null; profile = user ? await ensureProfile(user) : null; return state; }
function bucketFor(route){ if(route==='music') return 'music-audio'; if(route==='podcast') return 'podcast-audio'; if(route==='sports') return 'sports-media'; if(route==='gaming') return 'game-clips'; if(route==='store-product') return 'store-products'; if(route==='store-digital') return 'store-digital'; if(route==='gallery') return 'gallery-media'; return 'general-uploads'; }
function mediaType(file){ const type = file?.type || ''; if(type.startsWith('image/')) return 'image'; if(type.startsWith('video/')) return 'video'; if(type.startsWith('audio/')) return 'audio'; return file ? 'file' : 'text'; }
function identity(){ return { user_id:user.id, username:profile?.username || user.email?.split('@')[0] || 'rich_user', display_name:profile?.display_name || user.email?.split('@')[0] || 'Rich Bizness' }; }
function meta(extra={}){ return { username:profile?.username || '', display_name:profile?.display_name || '', avatar_url:profile?.avatar_url || '', route:selectedRoute, ...extra }; }
function uploadMarkup(){ return `<div id="dropFeedShell" class="drop-feed-shell"><form class="df-form" id="dropForm"><input id="dropTitle" placeholder="Title"><select id="dropRoute">${routes.map(r=>`<option value="${r[0]}">${r[2]}</option>`).join('')}</select><textarea id="dropCaption" placeholder="Description"></textarea><label class="df-dropzone" for="dropFile"><span><b>Pick file</b><small>Image, video, audio, cover, clip, product</small></span><input id="dropFile" type="file" hidden></label><div class="df-actions"><button class="primary" type="submit">DROP IT</button><a href="/feed.html">OPEN FEED</a></div><small class="df-status" id="dropStatus">Router ready.</small></form></div>`; }
function feedMarkup(){ return `<div id="dropFeedShell" class="drop-feed-shell"><form class="df-form" id="feedForm"><input id="feedTitle" placeholder="Title"><textarea id="feedBody" placeholder="Say it Rich..."></textarea><input id="feedMedia" placeholder="Optional media URL"><div class="df-actions"><button class="primary" type="submit">DROP POST</button><a href="/upload.html?section=feed">UPLOAD FILE</a></div><small class="df-status" id="dropStatus">Feed ready.</small></form><div class="df-feed-list" id="dfFeedList"></div></div>`; }
function mount(){ if($('#dropFeedShell')) return; const target = $('#sectionCards') || $('.cards'); if(target) target.innerHTML = isUpload ? uploadMarkup() : feedMarkup(); wire(); }
function wire(){ if(isUpload){ const select=$('#dropRoute'); if(select) select.value=selectedRoute; select?.addEventListener('change',()=>selectedRoute=select.value); $('#dropFile')?.addEventListener('change',(e)=>pickedFile=e.target.files?.[0]||null); $('#dropForm')?.addEventListener('submit',submitUpload); } else { $('#feedForm')?.addEventListener('submit',submitFeed); } }
async function uploadFile(){ if(!pickedFile) return { publicUrl:'', bucket:'', filePath:'', mimeType:'', fileSize:0, mediaType:'text' }; const bucket=bucketFor(selectedRoute); const ext=pickedFile.name.split('.').pop() || 'bin'; const filePath=`${user.id}/${Date.now()}.${ext}`; const up=await supabase.storage.from(bucket).upload(filePath,pickedFile,{contentType:pickedFile.type||undefined}); if(up.error) throw up.error; return { publicUrl:supabase.storage.from(bucket).getPublicUrl(filePath).data.publicUrl, bucket, filePath, mimeType:pickedFile.type||'', fileSize:pickedFile.size||0, mediaType:mediaType(pickedFile) }; }
async function insert(table,row){ const {data,error}=await supabase.from(table).insert(row).select('*').maybeSingle(); if(error) throw error; return data; }
async function safeInsert(table,row){ try { return await insert(table,row); } catch (error) { console.warn('[RB Upload route failed]', table, error.message); return null; } }
function baseRows(title, description, file, upload){ const who = identity(); const source = meta({ upload_id:upload?.id, bucket:file.bucket, file_path:file.filePath, public_url:file.publicUrl, media_type:file.mediaType }); return { who, source, common:{...who,title,description,media_url:file.publicUrl,file_url:file.publicUrl,cover_url:file.mediaType==='image'?file.publicUrl:'',metadata:source} }; }
async function routeUpload(title, description, file, upload){ const { who, source, common } = baseRows(title, description, file, upload); if(selectedRoute === 'feed' || selectedRoute === 'gallery') return safeInsert('feed_posts',{...who,title,body:description,section:selectedRoute,post_type:file.mediaType || 'text',media_url:file.publicUrl,file_url:file.publicUrl,cover_url:file.mediaType==='image'?file.publicUrl:'',visibility:'public',metadata:source}); if(selectedRoute === 'music') return safeInsert('music_tracks',{...who,title,description,audio_url:file.publicUrl,file_url:file.publicUrl,cover_url:file.mediaType==='image'?file.publicUrl:'',is_published:true,visibility:'public',metadata:source}); if(selectedRoute === 'podcast') return safeInsert('podcast_episodes',{...who,title,description,audio_url:file.publicUrl,file_url:file.publicUrl,cover_url:file.mediaType==='image'?file.publicUrl:'',is_published:true,metadata:source}); if(selectedRoute === 'radio') return safeInsert('radio_stations',{...who,station_name:title,description,stream_url:file.publicUrl,cover_url:file.mediaType==='image'?file.publicUrl:'',is_live:false,is_public:true,metadata:source}); if(selectedRoute === 'sports') return safeInsert('sports_posts',{...who,title,body:description,media_url:file.publicUrl,media_type:file.mediaType,cover_url:file.mediaType==='image'?file.publicUrl:'',metadata:source}); if(selectedRoute === 'gaming') return safeInsert('game_clips',{...who,title,caption:description,clip_url:file.publicUrl,thumbnail_url:file.mediaType==='image'?file.publicUrl:null,metadata:source}); if(selectedRoute === 'store-product' || selectedRoute === 'store-digital') return safeInsert('products',{seller_id:user.id,title,description,image_url:file.mediaType==='image'?file.publicUrl:null,media_url:file.publicUrl,product_type:selectedRoute==='store-digital'?'digital':'physical',is_digital:selectedRoute==='store-digital',is_public:true,status:'active',price_cents:0,currency:'usd',metadata:source}); return null; }
async function submitUpload(e){ e.preventDefault(); try{ await auth(); if(!user){ location.href='/auth.html?next=/upload.html'; return; } const title=$('#dropTitle')?.value?.trim() || 'Rich Bizness Drop'; const description=$('#dropCaption')?.value?.trim() || ''; const file=await uploadFile(); const base={user_id:user.id,title,description,section:selectedRoute,category:selectedRoute,bucket:file.bucket,file_path:file.filePath,public_url:file.publicUrl,mime_type:file.mimeType,file_size:file.fileSize,media_type:file.mediaType,visibility:'public',processing_status:file.publicUrl?'uploaded':'text-only',metadata:meta(file)}; const upload=await safeInsert('uploads',base); const routed = await routeUpload(title, description, file, upload); await awardXp('drop_zone_upload',{section:selectedRoute,sourceTable:routed ? selectedRoute : 'uploads',sourceId:routed?.id || upload?.id}).catch(()=>{}); if($('#dropStatus')) $('#dropStatus').textContent=routed || upload ? 'Uploaded to ' + selectedRoute + '.' : 'Saved locally but route table blocked.'; e.target.reset(); pickedFile=null; }catch(err){ if($('#dropStatus')) $('#dropStatus').textContent=err.message||String(err); } }
async function submitFeed(e){ e.preventDefault(); try{ await auth(); if(!user){ location.href='/auth.html?next=/feed.html'; return; } const title=$('#feedTitle')?.value?.trim() || 'Rich Bizness Post'; const body=$('#feedBody')?.value?.trim() || ''; const media=$('#feedMedia')?.value?.trim() || ''; const post=await insert('feed_posts',{...identity(),title,body,media_url:media,section:'feed',post_type:media?'media':'text',visibility:'public',metadata:meta({source:'feed-composer'})}); await awardXp('feed_post_create',{section:'feed',sourceTable:'feed_posts',sourceId:post?.id}).catch(()=>{}); e.target.reset(); loadFeed(); }catch(err){ if($('#dropStatus')) $('#dropStatus').textContent=err.message||String(err); } }
function postCard(p){ const author=esc(p.display_name || p.username || 'Rich Bizness'); const handle=esc(p.username ? '@'+p.username : 'profile'); const media=p.media_url?`<div class="df-post-media"><img src="${esc(p.media_url)}" alt=""></div>`:''; return `<article class="df-post"><a class="df-author" href="${authProfileUrl(p)}"><span>${author.slice(0,2).toUpperCase()}</span><b>${author}</b><small>${handle}</small></a><h3>${esc(p.title||'Rich Bizness Post')}</h3><p>${esc(p.body||'')}</p>${media}</article>`; }
async function loadFeed(){ if(isUpload) return; const {data}=await supabase.from('feed_posts').select('*').order('created_at',{ascending:false}).limit(24); const list=$('#dfFeedList'); if($('#recordCount')) $('#recordCount').textContent=String((data||[]).length); if(list) list.innerHTML=(data||[]).map(postCard).join('') || '<div class="df-status">No feed posts yet.</div>'; }
mount(); auth().catch(()=>{}); loadFeed(); supabase.channel('drop-feed-live').on('postgres_changes',{event:'*',schema:'public',table:'feed_posts'},loadFeed).subscribe();