import { supabase } from './supabase-client.js';
import { awardXp } from './rb-xp.js?v=realtime-1';
import { getAuthoritativeIdentity } from './rb-identity.js?v=identity-public-1';
import './rb-personality.js?v=drop-feed-1';

const key = document.body?.dataset?.section || 'feed';
const isUpload = key === 'upload';
const $ = (s) => document.querySelector(s);
const fmt = (n) => Number(n || 0).toLocaleString();
const routes = [
  ['feed','feed_posts','RICH FEED'],['gallery','feed_posts','GALLERY'],['music','music_tracks','MUSIC'],['podcast','podcast_episodes','PODCAST'],['radio','radio_stations','RB RADIO'],['sports','sports_posts','SPORTS'],['gaming','game_clips','GAMING'],['store-product','products','STORE'],['store-digital','products','DIGITAL'],['live-thumbnail','live_streams','LIVE THUMB'],['live-recording','live_recordings','REPLAY'],['meta','meta_worlds','META']
];
let user = null, profile = null, posts = [], selectedRoute = new URL(location.href).searchParams.get('section') || (isUpload ? 'feed' : 'feed'), pickedFile = null;
function addCss(){ if($('#dropFeedCss')) return; const l=document.createElement('link'); l.id='dropFeedCss'; l.rel='stylesheet'; l.href='/src/drop-feed.css?v=drop-feed-1'; document.head.appendChild(l); }
async function auth(){ const state = await getAuthoritativeIdentity(); user = state.user || null; profile = state.profile || null; return state; }
function routeInfo(){ return routes.find(r=>r[0]===selectedRoute) || routes[0]; }
function mediaOf(row){ return row.media_url || row.image_url || row.cover_url || row.thumbnail_url || row.video_url || row.file_url || row.audio_url || row.metadata?.media_url || row.metadata?.public_url || ''; }
function nameOf(row){ return row.title || row.caption || row.body || 'Rich Bizness Drop'; }
function authorOf(row){ return row.display_name || row.username || row.metadata?.display_name || 'Rich Bizness'; }
function faceOf(row){ return row.avatar_url || row.metadata?.avatar_url || ''; }
function mount(){ if($('#dropFeedShell')) return; const main = document.querySelector('main') || document.body; const shell = document.createElement('section'); shell.id='dropFeedShell'; shell.className='drop-feed-shell'; shell.innerHTML = isUpload ? uploadMarkup() : feedMarkup(); main.appendChild(shell); wire(); }
function uploadMarkup(){ return `<section class="df-hero"><small>DROP ZONE • ROUTE IT RIGHT</small><h1>DROP ZONE</h1><p>Drop it once and let Rich Bizness route the file to feed, gallery, music, podcast, sports, gaming, store, live, or meta without breaking profile lock.</p><div class="df-metrics"><div class="df-metric"><b id="dfRecordCount">0</b><span>DROPS</span></div><div class="df-metric"><b id="dfRouteName">FEED</b><span>ROUTE</span></div><div class="df-metric"><b id="dfStatusTop">READY</b><span>STATUS</span></div></div></section><section class="df-layout"><section class="df-panel"><h2>Drop Control</h2><form class="df-form" id="dropForm"><input id="dropTitle" placeholder="Title this drop"><select id="dropRoute">${routes.map(r=>`<option value="${r[0]}">${r[2]}</option>`).join('')}</select><textarea id="dropCaption" placeholder="Talk that Rich Bizness language..."></textarea><label class="df-dropzone" for="dropFile"><span><b>Tap to pick file</b><small>Image, video, audio, cover, clip, product, replay</small></span><input id="dropFile" type="file" hidden></label><div class="df-preview"><div class="df-preview-box" id="dfPreviewBox">RB</div><div><b id="dfPreviewTitle">No file yet</b><p id="dfPreviewMeta">Pick a route and file.</p><small class="df-status" id="dropStatus">Router ready.</small></div></div><div class="df-actions"><button class="primary" type="submit">DROP IT</button><a href="/feed.html">OPEN FEED</a><a href="/profile.html">PROFILE LOCK</a></div></form></section><aside class="df-panel"><h2>Auto Route</h2><div class="df-route-grid" id="dfRoutes"></div><div class="df-status" id="routeStatus">Every lane keeps RB language and identity metadata.</div></aside></section>`; }
function feedMarkup(){ return `<section class="df-hero"><small>RICH FEED • REAL DROPS</small><h1>RICH FEED</h1><p>Posts, visuals, drops, likes, comments, follows, XP, and creator movement — all tied to the same Rich Bizness identity.</p><div class="df-metrics"><div class="df-metric"><b id="dfRecordCount">0</b><span>POSTS</span></div><div class="df-metric"><b id="dfRouteName">LIVE</b><span>SYNC</span></div><div class="df-metric"><b id="dfStatusTop">READY</b><span>STATUS</span></div></div></section><section class="df-layout"><section class="df-panel"><h2>Say It Rich</h2><form class="df-form" id="feedForm"><input id="feedTitle" placeholder="Title / headline"><textarea id="feedBody" placeholder="Drop something for the universe..."></textarea><input id="feedMedia" placeholder="Optional image/video/audio URL"><div class="df-actions"><button class="primary" type="submit">DROP POST</button><a href="/upload.html?section=feed">UPLOAD FILE</a><a href="/profile.html">PROFILE LOCK</a></div><small class="df-status" id="dropStatus">Feed ready.</small></form></section><aside class="df-panel"><h2>Live Drops</h2><div class="df-feed-list" id="dfFeedList"><div class="df-status">Checking live records...</div></div></aside></section>`; }
function wire(){ if(isUpload){ $('#dropRoute').value = selectedRoute; renderRouteTiles(); $('#dropRoute')?.addEventListener('change',()=>{selectedRoute=$('#dropRoute').value; renderRouteTiles();}); $('#dropFile')?.addEventListener('change',(e)=>{pickedFile=e.target.files?.[0]||null; previewFile();}); $('#dropForm')?.addEventListener('submit',submitUpload); } else { $('#feedForm')?.addEventListener('submit',submitFeed); } }
function renderRouteTiles(){ const box=$('#dfRoutes'); if(!box) return; box.innerHTML = routes.map(r=>`<article class="df-route ${r[0]===selectedRoute?'active':''}" data-route-pick="${r[0]}"><b>${r[2]}</b><small>${r[1]}</small></article>`).join(''); document.querySelectorAll('[data-route-pick]').forEach(el=>el.addEventListener('click',()=>{selectedRoute=el.dataset.routePick; if($('#dropRoute')) $('#dropRoute').value=selectedRoute; renderRouteTiles(); updateRouteLabel();})); updateRouteLabel(); }
function updateRouteLabel(){ const r=routeInfo(); if($('#dfRouteName')) $('#dfRouteName').textContent = r[2].split(' ')[0]; if($('#routeStatus')) $('#routeStatus').textContent = `${r[2]} routes into ${r[1]}.`; }
function previewFile(){ const box=$('#dfPreviewBox'), title=$('#dfPreviewTitle'), meta=$('#dfPreviewMeta'); if(!pickedFile){ if(box) box.textContent='RB'; return; } if(title) title.textContent = pickedFile.name; if(meta) meta.textContent = `${pickedFile.type || 'file'} • ${fmt(pickedFile.size)} bytes`; if(!box) return; const url=URL.createObjectURL(pickedFile); if(pickedFile.type.startsWith('image/')) box.innerHTML = `<img src="${url}" alt="">`; else if(pickedFile.type.startsWith('video/')) box.innerHTML = `<video src="${url}" muted playsinline></video>`; else box.textContent = pickedFile.type.startsWith('audio/') ? '♪' : 'RB'; }
async function insertFirst(rows){ for(const [table,row] of rows){ try{ const { data, error } = await supabase.from(table).insert(row).select('*').maybeSingle(); if(!error) return { table, data }; }catch(_){} } return null; }
async function submitUpload(e){ e.preventDefault(); await auth(); if(!user){ location.href='/auth.html'; return; } const title=$('#dropTitle')?.value?.trim() || 'Rich Bizness Drop'; const caption=$('#dropCaption')?.value?.trim() || 'They’re here Rich'; const r=routeInfo(); let publicUrl=''; if(pickedFile){ const ext=pickedFile.name.split('.').pop() || 'bin'; const path=`${user.id}/${Date.now()}-${Math.random().toString(16).slice(2)}.${ext}`; const bucket = selectedRoute.includes('music') ? 'music-audio' : selectedRoute.includes('podcast') ? 'podcast-audio' : selectedRoute.includes('sports') ? 'sports-media' : selectedRoute.includes('gaming') ? 'game-clips' : selectedRoute.includes('store') ? 'store-products' : selectedRoute.includes('live-recording') ? 'live-recordings' : selectedRoute.includes('live-thumbnail') ? 'live-thumbnails' : selectedRoute.includes('meta') ? 'meta-avatars' : selectedRoute.includes('gallery') ? 'gallery-media' : 'general-uploads'; const up = await supabase.storage.from(bucket).upload(path,pickedFile,{upsert:false}); if(up.error) { $('#dropStatus').textContent = up.error.message; return; } publicUrl = supabase.storage.from(bucket).getPublicUrl(path).data.publicUrl; }
 const meta = { section:selectedRoute, display_name:profile?.display_name, username:profile?.username, avatar_url:profile?.avatar_url, rb_language:'They’re here Rich', route_table:r[1] };
 const common = { user_id:user.id, title, caption, description:caption, section:selectedRoute, post_type:selectedRoute, media_url:publicUrl, image_url:publicUrl, file_url:publicUrl, visibility:'public', metadata:meta };
 const result = await insertFirst([[r[1], common],['feed_posts', common]]); if(result){ $('#dropStatus').textContent = `Dropped into ${result.table}.`; await awardXp('upload_drop',{section:'upload',sourceTable:result.table,sourceId:result.data?.id}).catch(()=>{}); $('#dfStatusTop').textContent='DROPPED'; loadFeed(); } else $('#dropStatus').textContent='Drop blocked by table policy.'; }
async function submitFeed(e){ e.preventDefault(); await auth(); if(!user){ location.href='/auth.html'; return; } const title=$('#feedTitle')?.value?.trim() || 'Rich Bizness Drop'; const body=$('#feedBody')?.value?.trim() || 'They’re here Rich'; const media=$('#feedMedia')?.value?.trim() || ''; const row={user_id:user.id,title,body,caption:body,description:body,section:'feed',post_type:'feed',media_url:media,image_url:media,visibility:'public',metadata:{display_name:profile?.display_name,username:profile?.username,avatar_url:profile?.avatar_url,rb_language:'They’re here Rich'}}; const { data,error } = await supabase.from('feed_posts').insert(row).select('*').maybeSingle(); if(error){ $('#dropStatus').textContent=error.message; return; } $('#dropStatus').textContent='Dropped into Rich Feed.'; await awardXp('feed_post',{section:'feed',sourceTable:'feed_posts',sourceId:data?.id}).catch(()=>{}); $('#feedForm').reset(); loadFeed(); }
function renderFeed(){ const box=$('#dfFeedList'); if(!box) return; box.innerHTML = posts.length ? posts.map(p=>{ const m=mediaOf(p), face=faceOf(p); return `<article class="df-post"><div class="df-author"><div class="df-face">${face?`<img src="${face}" alt="">`:'RB'}</div><div><b>${authorOf(p)}</b><small>${p.section || 'feed'} • ${new Date(p.created_at || Date.now()).toLocaleString()}</small></div></div><h3>${nameOf(p)}</h3><p>${p.body || p.caption || p.description || 'They’re here Rich'}</p>${m?`<div class="df-media">${String(m).match(/\.(mp4|mov|webm)(\?|$)/i)?`<video src="${m}" controls playsinline></video>`:`<img src="${m}" alt="">`}</div>`:''}<div class="df-post-actions"><button type="button">💨 Like</button><button type="button">Comment</button><button type="button">Share</button></div></article>`; }).join('') : '<div class="df-status">No drops yet. Drop the first one Rich.</div>'; }
async function loadFeed(){ try{ const { data,count } = await supabase.from('feed_posts').select('*',{count:'exact'}).order('created_at',{ascending:false}).limit(20); posts=data||[]; if($('#dfRecordCount')) $('#dfRecordCount').textContent=fmt(count || posts.length); if($('#dfStatusTop')) $('#dfStatusTop').textContent='LIVE'; renderFeed(); }catch(e){ if($('#dfStatusTop')) $('#dfStatusTop').textContent='READY'; } }
addCss(); mount(); auth().catch(()=>{}); loadFeed(); supabase.channel('drop-feed-live').on('postgres_changes',{event:'*',schema:'public',table:'feed_posts'},loadFeed).subscribe();