import { supabase } from './supabase-client.js';
import { awardXp } from './rb-xp.js';
import './rb-game-play.js';

let games = [];
let user = null;
let selected = null;
let score = 0;
const fmt = (n) => Number(n || 0).toLocaleString();
const $ = (s) => document.querySelector(s);

function addCss(){ if(document.getElementById('gameRoomCss')) return; const l=document.createElement('link'); l.id='gameRoomCss'; l.rel='stylesheet'; l.href='/src/game-room.css?v=game-room-2'; document.head.appendChild(l); }
function mount(){ if(document.getElementById('gameRoom')) return; const r=document.createElement('section'); r.id='gameRoom'; r.className='game-room'; r.innerHTML='<div class="game-room-head"><div><small>RICH BIZNESS GAME HUB</small><b id="gameTitle">RICH BIZNESS ARCADE</b><p id="gameDesc">All games loaded from Supabase.</p></div><small id="gameStatus">READY</small></div><div class="game-board"><div class="game-player" id="gamePlayer">RB</div><div class="game-score"><b id="gameScore">0</b><small>SCORE</small></div></div><div class="game-actions"><button id="joinGameRoom" type="button">JOIN ROOM</button><button id="playGameMove" type="button">PLAY MOVE</button><button id="submitScore" type="button">SUBMIT SCORE</button><a id="playLink" href="/gaming.html">LAUNCH</a><a href="/watch.html">STREAM TV</a><a href="/meta.html">FREE ROAM</a></div><div class="game-list" id="gameList"></div>'; document.querySelector('main')?.appendChild(r); $('#joinGameRoom')?.addEventListener('click', joinRoom); $('#playGameMove')?.addEventListener('click', playMove); $('#submitScore')?.addEventListener('click', submitScore); }
function render(){ const list=$('#gameList'); if(!list) return; list.innerHTML=games.length?games.map(g=>`<article class="game-tile ${selected?.id===g.id?'active':''}" data-slug="${g.slug}"><div class="game-tile-top"><b>${g.title}</b><em>${g.is_featured?'FEATURED':(g.game_type||'GAME').toUpperCase()}</em></div><p>${g.description||''}</p><small>${g.game_categories?.title||g.game_type||'Game'} • ${fmt(g.total_plays)} plays • ${fmt(g.active_players)} active</small></article>`).join(''):'<article class="game-tile"><b>No games yet</b><small>Seed Supabase games.</small></article>'; document.querySelectorAll('[data-slug]').forEach(el=>el.addEventListener('click',()=>selectGame(el.dataset.slug))); if(!selected&&games.length) selectGame(new URL(location.href).searchParams.get('game')||games[0].slug); }
function selectGame(slug){ selected=games.find(g=>g.slug===slug)||games[0]||null; score=0; $('#gameTitle').textContent=selected?.title||'RICH BIZNESS ARCADE'; $('#gameDesc').textContent=selected?.description||'Pick a game.'; $('#gameStatus').textContent=selected?`${selected.game_type||'GAME'} READY`.toUpperCase():'NO GAME'; $('#gameScore').textContent=fmt(score); $('#playLink').href=selected?.play_url||'/gaming.html'; $('#gamePlayer').textContent=selected?.game_type==='racing'?'🏎️':selected?.game_type==='sports'?'🏆':selected?.game_type==='fighting'?'🥊':'RB'; document.querySelectorAll('[data-slug]').forEach(el=>el.classList.toggle('active',el.dataset.slug===selected?.slug)); window.dispatchEvent(new CustomEvent('rb-game-selected',{detail:selected})); }
async function load(){ const { data } = await supabase.from('games').select('id,slug,title,description,game_type,play_url,total_plays,high_score,active_players,is_featured,color_theme,visual_style,metadata,game_categories(title,slug,icon)').eq('is_active',true).order('is_featured',{ascending:false}).order('created_at',{ascending:false}).limit(60); games=data||[]; render(); }
async function getUser(){ const { data }=await supabase.auth.getUser(); user=data?.user||null; return user; }
async function joinRoom(){ await getUser(); if(!user){ location.href='/auth.html'; return; } if(!selected) return; await awardXp('game_room_join',{section:'gaming',sourceTable:'games',sourceId:selected.id}); $('#gameStatus').textContent='ROOM JOINED'; }
async function playMove(){ await getUser(); if(!user){ location.href='/auth.html'; return; } if(!selected) return; score+=100; $('#gameScore').textContent=fmt(score); await supabase.from('game_sessions').insert({game_id:selected.id,game_slug:selected.slug,user_id:user.id,score,result:'move',metadata:{source:'game-room'}}); await awardXp('game_move',{section:'gaming',sourceTable:'games',sourceId:selected.id}); $('#gameStatus').textContent='MOVE SAVED'; }
async function submitScore(){ await getUser(); if(!user){ location.href='/auth.html'; return; } if(!selected) return; await supabase.from('game_scores').insert({game_id:selected.id,game_slug:selected.slug,user_id:user.id,score,mode:selected.game_type||'arcade',platform_type:'web',metadata:{source:'game-room'}}); await awardXp('game_score_submit',{section:'gaming',sourceTable:'games',sourceId:selected.id}); $('#gameStatus').textContent='SCORE SUBMITTED'; }
addCss(); mount(); load(); supabase.channel('game-room-ui').on('postgres_changes',{event:'*',schema:'public',table:'games'},load).subscribe();
