import { supabase } from './supabase-client.js';
import { awardXp } from './rb-xp.js?v=realtime-2';
import { getAuthoritativeIdentity } from './rb-identity.js?v=tap-in-foundation-3';
import './section-language-foundation.js?v=language-foundation-4';
import './rb-game-play.js';
import './rb-elite-games.js';

const OWNED = ['games','gamer_profiles','game_categories','game_sessions','game_scores','game_moves','game_rooms','game_room_members','game_rewards','game_clips','game_comments','game_likes','game_challenges','game_tournaments','game_platform_accounts','game_stream_links','game_alert_subscriptions','gaming_uploads'];
let games = [], counts = {}, user = null, selected = null, score = 0;
const fmt = (n) => Number(n || 0).toLocaleString();
const $ = (s) => document.querySelector(s);
const next = encodeURIComponent(location.pathname + location.search);

function addCss(){ if(document.getElementById('gameRoomCss')) return; const l=document.createElement('link'); l.id='gameRoomCss'; l.rel='stylesheet'; l.href='/src/game-room.css?v=gaming-owner-2'; document.head.appendChild(l); }
function mount(){ if(document.getElementById('gameRoom')) return; const r=document.createElement('section'); r.id='gameRoom'; r.className='game-room'; r.innerHTML='<div class="game-room-head"><div><small>RICH BIZNESS GAME HUB</small><b id="gameTitle">RICH BIZNESS ARCADE</b><p id="gameDesc">All games are featured and connected to the whole gaming system.</p></div><small id="gameStatus">READY</small></div><div class="game-board"><div class="game-player" id="gamePlayer">RB</div><div class="game-score"><b id="gameScore">0</b><small>SCORE</small></div></div><div class="game-actions"><button id="joinGameRoom" type="button">JOIN ROOM</button><button id="playGameMove" type="button">PLAY MOVE</button><button id="submitScore" type="button">SUBMIT SCORE</button><button id="saveClip" type="button">SAVE CLIP</button><a id="playLink" href="/gaming.html">LAUNCH</a><a href="/watch.html">We 🔥📺</a><a href="/upload.html?section=gaming">DROP CLIP</a><a href="/games/">PLAY ROOM</a></div><div class="game-systems" id="gameSystems"></div><div class="game-list" id="gameList"></div>'; document.querySelector('main')?.appendChild(r); $('#joinGameRoom')?.addEventListener('click', joinRoom); $('#playGameMove')?.addEventListener('click', playMove); $('#submitScore')?.addEventListener('click', submitScore); $('#saveClip')?.addEventListener('click', saveClip); window.dispatchEvent(new CustomEvent('rb-page-rendered')); }
function renderSystems(){ const target = $('#gameSystems') || $('#gamingSystems'); if(!target) return; target.innerHTML = OWNED.map(t=>`<article class="game-system"><b>${t.replaceAll('_',' ').toUpperCase()}</b><small>${fmt(counts[t])} records</small></article>`).join(''); const owner = $('#gamingOwnerCount'); if(owner) owner.textContent = OWNED.length; }
function render(){ const list=$('#gameList') || $('#sectionCards'); if(!list) return; list.innerHTML=games.length?games.map(g=>`<article class="game-tile ${selected?.id===g.id?'active':''}" data-slug="${g.slug}"><div class="game-tile-top"><b>${g.title}</b><em>FEATURED</em></div><p>${g.description||'Rich Bizness featured game lane.'}</p><small>${(g.game_type||g.category||'game').toUpperCase()} • ${fmt(g.total_plays||g.view_count)} plays • ${fmt(g.active_players||0)} active</small></article>`).join(''):'<article class="game-tile"><b>No games yet</b><small>Seed Supabase games.</small></article>'; document.querySelectorAll('[data-slug]').forEach(el=>el.addEventListener('click',()=>selectGame(el.dataset.slug))); if(!selected&&games.length) selectGame(new URL(location.href).searchParams.get('game')||games[0].slug); }
function selectGame(slug){ selected=games.find(g=>g.slug===slug)||games[0]||null; score=0; $('#gameTitle').textContent=selected?.title||'RICH BIZNESS ARCADE'; $('#gameDesc').textContent=selected?.description||'Pick a featured game.'; $('#gameStatus').textContent=selected?`FEATURED ${(selected.game_type||selected.category||'GAME')} READY`.toUpperCase():'NO GAME'; $('#gameScore').textContent=fmt(score); $('#playLink').href=selected?.play_url||'/gaming.html'; $('#gamePlayer').textContent=(selected?.game_type||selected?.category)==='racing'?'🏎️':(selected?.game_type||selected?.category)==='sports'?'🏆':(selected?.game_type||selected?.category)==='fighting'?'🥊':(selected?.game_type||selected?.category)==='strategy'?'♟️':'RB'; document.querySelectorAll('[data-slug]').forEach(el=>el.classList.toggle('active',el.dataset.slug===selected?.slug)); window.dispatchEvent(new CustomEvent('rb-game-selected',{detail:selected})); }
async function countTable(table){ try{ const { count } = await supabase.from(table).select('*',{count:'exact',head:true}); return count || 0; } catch(_) { return 0; } }
async function loadCounts(){ const pairs = await Promise.all(OWNED.map(async t=>[t, await countTable(t)])); counts = Object.fromEntries(pairs); renderSystems(); }
async function load(){ const { data } = await supabase.from('games').select('*').order('is_featured',{ascending:false}).order('created_at',{ascending:false}).limit(80); games=(data||[]).map(g=>({...g,is_featured:true})); render(); const c=$('#recordCount'); if(c) c.textContent=fmt(games.length); }
async function getUser(){ const state=await getAuthoritativeIdentity(); user=state.user||null; return user; }
async function needUser(){ await getUser(); if(!user){ location.href='/auth.html?next=' + next; return null; } return user; }
async function joinRoom(){ if(!await needUser()) return; if(!selected) return; await supabase.from('game_rooms').insert({game_id:selected.id,game_slug:selected.slug,created_by:user.id,title:selected.title+' Room',status:'active',metadata:{source:'gaming-owner'}}).then(()=>{},()=>{}); await awardXp('game_room_join',{section:'gaming',sourceTable:'games',sourceId:selected.id}); $('#gameStatus').textContent='ROOM JOINED'; loadCounts(); }
async function playMove(){ if(!await needUser()) return; if(!selected) return; score+=175; $('#gameScore').textContent=fmt(score); await supabase.from('game_sessions').insert({game_id:selected.id,game_slug:selected.slug,user_id:user.id,score,result:'move',metadata:{source:'game-room',featured:true}}).then(()=>{},()=>{}); await supabase.from('game_moves').insert({game_id:selected.id,game_slug:selected.slug,user_id:user.id,move_type:'tap',score_delta:175,metadata:{source:'game-room'}}).then(()=>{},()=>{}); await awardXp('game_move',{section:'gaming',sourceTable:'games',sourceId:selected.id}); $('#gameStatus').textContent='MOVE SAVED'; loadCounts(); }
async function submitScore(){ if(!await needUser()) return; if(!selected) return; await supabase.from('game_scores').insert({game_id:selected.id,game_slug:selected.slug,user_id:user.id,score,mode:selected.game_type||selected.category||'arcade',platform_type:'web',metadata:{source:'game-room',featured:true}}).then(()=>{},()=>{}); await awardXp('game_score_submit',{section:'gaming',sourceTable:'games',sourceId:selected.id}); $('#gameStatus').textContent='SCORE SUBMITTED'; loadCounts(); }
async function saveClip(){ if(!await needUser()) return; if(!selected) return; await supabase.from('game_clips').insert({game_id:selected.id,game_slug:selected.slug,user_id:user.id,title:selected.title+' Clip',caption:'Rich Bizness arcade clip',metadata:{score,source:'game-room'}}).then(()=>{},()=>{}); $('#gameStatus').textContent='CLIP QUEUED'; loadCounts(); }
addCss(); mount(); load(); loadCounts(); supabase.channel('gaming-owner-ui').on('postgres_changes',{event:'*',schema:'public',table:'games'},load).on('postgres_changes',{event:'*',schema:'public',table:'game_scores'},loadCounts).on('postgres_changes',{event:'*',schema:'public',table:'game_sessions'},loadCounts).subscribe();
