import { supabase } from './supabase-client.js';

const $=(s)=>document.querySelector(s);const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safePath=(slug)=>`/games/${String(slug||'').replace(/[^a-z0-9-]/g,'')}/`;
let user=null,profile=null,games=[],game=null,score=0,busy=false,disposed=false,paused=false,room=null,channels=[],lastTap=0;
function status(message,tone='ready'){const n=$('#gameStatus');if(n){n.textContent=message;n.dataset.tone=tone}}
function setState(value){if($('#gameState'))$('#gameState').textContent=value}
function connection(){const n=$('#gameConnection');if(n)n.textContent=navigator.onLine?'ONLINE':'OFFLINE'}
async function identity(){const {data}=await supabase.auth.getUser();user=data?.user||null;if(user){const {data:p}=await supabase.from('profiles').select('id,username,display_name').eq('id',user.id).maybeSingle();profile=p||null}}
function cover(row){try{const u=new URL(String(row.cover_url||row.thumbnail_url||''),location.origin);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}}
function card(row){const image=cover(row);return `<a class="game-card" href="${safePath(row.slug)}">${image?`<img class="game-cover" src="${esc(image)}" alt="" loading="lazy">`:'<span class="game-fallback">RB</span>'}<span><b>${esc(row.title)}</b><small>${esc(row.game_type||'arcade')} • ${Number(row.total_plays||0).toLocaleString()} plays</small></span><span>PLAY</span></a>`}
async function loadVault(){const {data,error}=await supabase.from('games').select('*').eq('is_active',true).order('title').limit(24);if(error)throw error;games=data||[];$('#gameVault').innerHTML=games.map(card).join('')||'<div>No games registered.</div>';$('#gameMetric').textContent=games.length.toLocaleString();status(`ARCADE CONNECTED • ${games.length} LANES`)}
async function loadGame(){const slug=document.body.dataset.gameSlug||new URLSearchParams(location.search).get('game');if(!slug)return loadVault();const {data,error}=await supabase.from('games').select('*').eq('slug',slug).maybeSingle();if(error)throw error;if(!data)throw new Error('GAME NOT REGISTERED');game=data;$('#gameTitle').textContent=game.title;$('#gameDescription').textContent=game.description||'Rich Bizness arcade challenge.';document.title=`${game.title} | Rich Bizness`;await Promise.all([loadLeaderboard(),loadComments()]);startRealtime();setState('READY');status('GAME READY • TAP TO BUILD SCORE')}
async function loadLeaderboard(){if(!game)return;const {data,error}=await supabase.from('game_scores').select('display_name,username,score,created_at').eq('game_id',game.id).order('score',{ascending:false}).limit(10);if(error)throw error;$('#leaderboard').innerHTML=(data||[]).map((row,i)=>`<div class="leader"><span>${i+1}. ${esc(row.display_name||row.username||'Player')}</span><b>${Number(row.score||0).toLocaleString()}</b></div>`).join('')||'<div class="leader"><span>NO SCORES YET</span><b>0</b></div>'}
async function loadComments(){if(!game||!$('#gameComments'))return;const {data}=await supabase.from('game_comments').select('display_name,username,body,created_at').eq('game_id',game.id).is('clip_id',null).order('created_at',{ascending:false}).limit(20);$('#gameComments').innerHTML=(data||[]).map(r=>`<div class="leader"><span><b>${esc(r.display_name||r.username||'Player')}</b><br>${esc(r.body)}</span></div>`).join('')||'<div class="leader"><span>NO COMMENTS YET</span></div>'}
function clearChannels(){channels.forEach(c=>supabase?.removeChannel(c));channels=[]}
function startRealtime(){if(!game)return;clearChannels();channels=[supabase.channel(`rb-game-score:${game.id}`).on('postgres_changes',{event:'*',schema:'public',table:'game_scores',filter:`game_id=eq.${game.id}`},loadLeaderboard).subscribe(),supabase.channel(`rb-game-comments:${game.id}`).on('postgres_changes',{event:'*',schema:'public',table:'game_comments',filter:`game_id=eq.${game.id}`},loadComments).subscribe()];if(room)channels.push(supabase.channel(`rb-game-room:${room.id}`).on('postgres_changes',{event:'*',schema:'public',table:'game_room_members',filter:`room_id=eq.${room.id}`},loadRoomMembers).subscribe())}
function tap(){if(paused||!navigator.onLine)return status(paused?'GAME PAUSED':'OFFLINE • RECONNECT TO PLAY','error');const now=performance.now();if(now-lastTap<45)return;lastTap=now;score+=1;$('#scoreValue').textContent=score.toLocaleString();$('#tapCore')?.animate([{transform:'scale(1)'},{transform:'scale(.94)'},{transform:'scale(1)'}],{duration:120});setState('PLAYING')}
function togglePause(){paused=!paused;$('#playPause').textContent=paused?'RESUME':'PAUSE';setState(paused?'PAUSED':'PLAYING');status(paused?'GAME PAUSED':'GAME RESUMED')}
function restart(){score=0;paused=false;$('#scoreValue').textContent='0';$('#playPause').textContent='PAUSE';setState('READY');status('GAME RESTARTED')}
async function submitScore(){if(busy)return;if(!user)return location.href=`/auth.html?next=${encodeURIComponent(location.pathname+location.search)}`;if(!game||score<1)return status('BUILD A SCORE FIRST','error');busy=true;$('#saveScore').disabled=true;try{const maxReasonable=60000;if(score>maxReasonable)throw new Error('SCORE REVIEW REQUIRED');const {error}=await supabase.from('game_scores').insert({game_id:game.id,game_slug:game.slug,user_id:user.id,username:profile?.username||'member',display_name:profile?.display_name||'Rich Bizness Player',score,mode:'solo',platform_type:'web',is_verified:false,anti_cheat_status:'pending',metadata:{source:'game-owner',elapsed_ms:Math.round(performance.now())}});if(error)throw error;status('SCORE LOCKED IN');setState('SAVED');await loadLeaderboard()}catch(e){status(`SCORE FAILED • ${e.message}`,'error')}finally{busy=false;$('#saveScore').disabled=false}}
async function createRoom(){if(!user||!game)return location.href=`/auth.html?next=${encodeURIComponent(location.pathname+location.search)}`;const code=Math.random().toString(36).slice(2,8).toUpperCase();const {data,error}=await supabase.from('game_rooms').insert({room_code:code,game_key:game.slug,host_user_id:user.id,status:'open',current_turn:String(user.id),board_state:{},game_state:{score:0},metadata:{source:'game-owner'}}).select('*').single();if(error)return status(`ROOM FAILED • ${error.message}`,'error');room=data;await joinCurrentRoom('host');status('ROOM OPEN • SHARE THE CODE')}
async function joinRoom(){if(!user||!game)return location.href=`/auth.html?next=${encodeURIComponent(location.pathname+location.search)}`;const code=String($('#joinCode')?.value||'').trim().toUpperCase();if(!code)return status('ENTER A ROOM CODE','error');const {data,error}=await supabase.from('game_rooms').select('*').eq('room_code',code).eq('game_key',game.slug).in('status',['open','active']).maybeSingle();if(error||!data)return status('ROOM NOT FOUND','error');room=data;await joinCurrentRoom('player');status('ROOM JOINED')}
async function joinCurrentRoom(role){await supabase.from('game_room_members').upsert({room_id:room.id,user_id:user.id,username:profile?.username||'member',display_name:profile?.display_name||'Rich Bizness Player',role,status:'active',updated_at:new Date().toISOString()},{onConflict:'room_id,user_id'});$('#roomCode').textContent=room.room_code;$('#leaveRoom').hidden=false;await loadRoomMembers();startRealtime()}
async function leaveRoom(){if(!room||!user)return;await supabase.from('game_room_members').update({status:'left',updated_at:new Date().toISOString()}).eq('room_id',room.id).eq('user_id',user.id);room=null;$('#roomCode').textContent='NO ROOM OPEN';$('#leaveRoom').hidden=true;$('#roomMembers').innerHTML='';startRealtime();status('ROOM LEFT')}
async function loadRoomMembers(){if(!room||!$('#roomMembers'))return;const {data}=await supabase.from('game_room_members').select('display_name,username,role,status').eq('room_id',room.id).eq('status','active').order('joined_at');$('#roomMembers').innerHTML=(data||[]).map(r=>`<div class="leader"><span>${esc(r.display_name||r.username||'Player')}</span><b>${esc(r.role||'player')}</b></div>`).join('')}
async function toggleLike(){if(!user||!game)return location.href=`/auth.html?next=${encodeURIComponent(location.pathname+location.search)}`;const {data}=await supabase.from('game_likes').select('id').eq('game_id',game.id).eq('user_id',user.id).is('clip_id',null).maybeSingle();if(data){const {error}=await supabase.from('game_likes').delete().eq('id',data.id);if(error)return status(`LIKE FAILED • ${error.message}`,'error');$('#likeGame').textContent='LIKE';status('GAME UNLIKED')}else{const {error}=await supabase.from('game_likes').insert({game_id:game.id,user_id:user.id});if(error)return status(`LIKE FAILED • ${error.message}`,'error');$('#likeGame').textContent='LIKED';status('GAME LIKED')}}
async function comment(event){event.preventDefault();if(!user||!game)return location.href=`/auth.html?next=${encodeURIComponent(location.pathname+location.search)}`;const body=String($('#commentInput')?.value||'').trim();if(!body)return;const {error}=await supabase.from('game_comments').insert({game_id:game.id,user_id:user.id,username:profile?.username||'member',display_name:profile?.display_name||'Rich Bizness Player',body});if(error)return status(`COMMENT FAILED • ${error.message}`,'error');event.currentTarget.reset();status('COMMENT DROPPED');loadComments()}
function bind(){$('#tapCore')?.addEventListener('click',tap);$('#playPause')?.addEventListener('click',togglePause);$('#restartGame')?.addEventListener('click',restart);$('#saveScore')?.addEventListener('click',submitScore);$('#createRoom')?.addEventListener('click',createRoom);$('#joinRoom')?.addEventListener('click',joinRoom);$('#leaveRoom')?.addEventListener('click',leaveRoom);$('#likeGame')?.addEventListener('click',toggleLike);$('#commentForm')?.addEventListener('submit',comment);addEventListener('online',()=>{connection();status('CONNECTION RESTORED')});addEventListener('offline',()=>{connection();status('OFFLINE • GAME PAUSED','error');paused=true;setState('PAUSED')});document.addEventListener('visibilitychange',()=>{if(document.hidden&&!paused){paused=true;$('#playPause')&&( $('#playPause').textContent='RESUME');setState('PAUSED')}})}
function cleanup(){disposed=true;clearChannels()}
async function boot(){connection();if(!supabase)return status('SUPABASE ENV VARIABLES REQUIRED','error');try{await identity();bind();await loadGame();window.addEventListener('pagehide',cleanup,{once:true})}catch(e){status(`ARCADE FAILED • ${e.message}`,'error')}}
boot();