import { supabase } from './supabase-client.js';

const $=(s)=>document.querySelector(s);const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safePath=(slug)=>`/games/${String(slug||'').replace(/[^a-z0-9-]/g,'')}/`;
let user=null,profile=null,games=[],game=null,score=0,busy=false,disposed=false,channels=[];
function status(message,tone='ready'){const n=$('#gameStatus');if(n){n.textContent=message;n.dataset.tone=tone}}
async function identity(){const {data}=await supabase.auth.getUser();user=data?.user||null;if(user){const {data:p}=await supabase.from('profiles').select('id,username,display_name').eq('id',user.id).maybeSingle();profile=p||null}}
function cover(row){try{const u=new URL(String(row.cover_url||row.thumbnail_url||''),location.origin);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}}
function card(row){const image=cover(row);return `<a class="game-card" href="${safePath(row.slug)}">${image?`<img class="game-cover" src="${esc(image)}" alt="" loading="lazy">`:'<span class="game-fallback">RB</span>'}<span><b>${esc(row.title)}</b><small>${esc(row.game_type||'arcade')} • ${Number(row.total_plays||0).toLocaleString()} plays</small></span><span>PLAY</span></a>`}
async function loadVault(){const {data,error}=await supabase.from('games').select('*').eq('is_active',true).order('title').limit(24);if(error)throw error;games=data||[];$('#gameVault').innerHTML=games.map(card).join('')||'<div>No games registered.</div>';$('#gameMetric').textContent=games.length.toLocaleString();status('ARCADE CONNECTED • 24 LANES')}
async function loadGame(){const slug=document.body.dataset.gameSlug||new URLSearchParams(location.search).get('game');if(!slug)return loadVault();const {data,error}=await supabase.from('games').select('*').eq('slug',slug).maybeSingle();if(error)throw error;if(!data)throw new Error('GAME NOT REGISTERED');game=data;$('#gameTitle').textContent=game.title;$('#gameDescription').textContent=game.description||'Rich Bizness arcade challenge.';document.title=`${game.title} | Rich Bizness`;await loadLeaderboard();startRealtime();status('GAME READY • TAP TO BUILD SCORE')}
async function loadLeaderboard(){if(!game)return;const {data,error}=await supabase.from('game_scores').select('display_name,username,score,created_at').eq('game_id',game.id).order('score',{ascending:false}).limit(10);if(error)throw error;$('#leaderboard').innerHTML=(data||[]).map((row,i)=>`<div class="leader"><span>${i+1}. ${esc(row.display_name||row.username||'Player')}</span><b>${Number(row.score||0).toLocaleString()}</b></div>`).join('')||'<div class="leader"><span>NO SCORES YET</span><b>0</b></div>'}
function startRealtime(){if(!game)return;channels.push(supabase.channel(`rb-game-score:${game.id}`).on('postgres_changes',{event:'*',schema:'public',table:'game_scores',filter:`game_id=eq.${game.id}`},loadLeaderboard).subscribe())}
function tap(){score+=1;$('#scoreValue').textContent=score.toLocaleString();$('#tapCore')?.animate([{transform:'scale(1)'},{transform:'scale(.94)'},{transform:'scale(1)'}],{duration:120})}
async function submitScore(){if(busy)return;if(!user)return status('TAP IN TO SAVE SCORE','error');if(!game||score<1)return status('BUILD A SCORE FIRST','error');busy=true;try{const {error}=await supabase.from('game_scores').insert({game_id:game.id,game_slug:game.slug,user_id:user.id,username:profile?.username||'member',display_name:profile?.display_name||'Rich Bizness Player',score,mode:'solo',platform_type:'web',is_verified:false,anti_cheat_status:'unverified',metadata:{source:'game-owner'}});if(error)throw error;status('SCORE LOCKED IN');await loadLeaderboard()}catch(e){status(`SCORE FAILED • ${e.message}`,'error')}finally{busy=false}}
async function createRoom(){if(!user||!game)return status('TAP IN TO CREATE A ROOM','error');const code=Math.random().toString(36).slice(2,8).toUpperCase();const {error}=await supabase.from('game_rooms').insert({room_code:code,game_key:game.slug,host_user_id:user.id,status:'open',current_turn:user.id,board_state:{},game_state:{score:0},metadata:{source:'game-owner'}});if(error)return status(`ROOM FAILED • ${error.message}`,'error');$('#roomCode').textContent=code;status('ROOM OPEN • SHARE THE CODE')}
async function toggleLike(){if(!user||!game)return status('TAP IN TO LIKE THIS GAME','error');const {data}=await supabase.from('game_likes').select('id').eq('game_id',game.id).eq('user_id',user.id).is('clip_id',null).maybeSingle();if(data){const {error}=await supabase.from('game_likes').delete().eq('id',data.id);if(error)return status(`LIKE FAILED • ${error.message}`,'error');status('GAME UNLIKED')}else{const {error}=await supabase.from('game_likes').insert({game_id:game.id,user_id:user.id});if(error)return status(`LIKE FAILED • ${error.message}`,'error');status('GAME LIKED')}}
async function comment(event){event.preventDefault();if(!user||!game)return status('TAP IN TO COMMENT','error');const body=String($('#commentInput')?.value||'').trim();if(!body)return;const {error}=await supabase.from('game_comments').insert({game_id:game.id,user_id:user.id,username:profile?.username||'member',display_name:profile?.display_name||'Rich Bizness Player',body});if(error)return status(`COMMENT FAILED • ${error.message}`,'error');event.currentTarget.reset();status('COMMENT DROPPED')}
function bind(){$('#tapCore')?.addEventListener('click',tap);$('#saveScore')?.addEventListener('click',submitScore);$('#createRoom')?.addEventListener('click',createRoom);$('#likeGame')?.addEventListener('click',toggleLike);$('#commentForm')?.addEventListener('submit',comment)}
function cleanup(){disposed=true;channels.forEach(c=>supabase.removeChannel(c));channels=[]}
async function boot(){if(!supabase)return status('SUPABASE ENV VARIABLES REQUIRED','error');try{await identity();bind();await loadGame();window.addEventListener('pagehide',cleanup,{once:true})}catch(e){status(`ARCADE FAILED • ${e.message}`,'error')}}
boot();