import { supabase } from './supabase-client.js';
import { awardXp } from './rb-xp.js?v=xp-idempotent-1';
import { getAuthoritativeIdentity } from './rb-identity.js?v=tap-in-foundation-3';
import './section-language-foundation.js?v=copy-only-1';

const GAME_TABLES = ['games','gamer_profiles','game_categories','game_sessions','game_scores','game_moves','game_rooms','game_room_members','game_rewards','game_clips','game_comments','game_likes','game_challenges','game_tournaments','game_platform_accounts','game_stream_links','game_alert_subscriptions','gaming_uploads'];
let games = [], counts = {}, user = null, selected = null, score = 0;
const fmt = (n) => Number(n || 0).toLocaleString();
const $ = (s) => document.querySelector(s);
const next = encodeURIComponent(location.pathname + location.search);

function addCss(){ if(document.getElementById('gameRoomCss')) return; const l=document.createElement('link'); l.id='gameRoomCss'; l.rel='stylesheet'; l.href='/src/game-room.css?v=game-room-6'; document.head.appendChild(l); }
function ensureControls(){
  const panel = $('#schemaPanel') || $('#gamingSystems')?.closest('.panel') || document.querySelector('.layout .panel:last-child');
  if (!panel || $('#gameControls')) return;
  panel.insertAdjacentHTML('beforeend','<div class="game-room compact" id="gameControls"><div class="game-room-head"><div><small>SELECTED GAME</small><b id="gameTitle">RICH BIZNESS ARCADE</b><p id="gameDesc">Pick a game from the list.</p></div><small id="gameStatus">READY</small></div><div class="game-board"><div class="game-player" id="gamePlayer">RB</div><div class="game-score"><b id="gameScore">0</b><small>SCORE</small></div></div><div class="game-actions"><button id="joinGameRoom" type="button">JOIN ROOM</button><button id="playGameMove" type="button">PLAY MOVE</button><button id="submitScore" type="button">SUBMIT SCORE</button><button id="saveClip" type="button">SAVE CLIP</button><a id="playLink" href="/gaming.html">LAUNCH</a><a href="/upload.html?section=gaming">DROP CLIP</a></div></div>');
  $('#joinGameRoom')?.addEventListener('click', joinRoom); $('#playGameMove')?.addEventListener('click', playMove); $('#submitScore')?.addEventListener('click', submitScore); $('#saveClip')?.addEventListener('click', saveClip);
}
function renderSystems(){ const target = $('#gamingSystems') || $('#gameSystems'); if(!target) return; target.innerHTML = GAME_TABLES.map(t=>`<article class="game-system"><b>${t.replaceAll('_',' ').toUpperCase()}</b><small>${fmt(counts[t])} records</small></article>`).join(''); const count = $('#gamingSystemCount'); if(count) count.textContent = GAME_TABLES.length; }
function render(){ ensureControls(); const list=$('#sectionCards') || $('#gameList'); if(!list) return; list.innerHTML=games.length?games.map(g=>`<article class="game-tile ${selected?.id===g.id?'active':''}" data-slug="${g.slug}"><div class="game-tile-top"><b>${g.title}</b><em>FEATURED</em></div><p>${g.description||'Rich Bizness featured game lane.'}</p><small>${(g.game_type||g.category||'game').toUpperCase()} • ${fmt(g.total_plays||g.view_count)} plays • ${fmt(g.active_players||0)} active</small></article>`).join(''):'<article class="game-tile"><b>No games yet</b><small>Seed Supabase games.</small></article>'; document.querySelectorAll('[data-slug]').forEach(el=>el.addEventListener('click',()=>selectGame(el.dataset.slug))); if(!selected&&games.length) selectGame(new URL(location.href).searchParams.get('game')||games[0].slug); }
function selectGame(slug){ selected=games.find(g=>g.slug===slug)||games[0]||null; score=0; if ($('#gameTitle')) $('#gameTitle').textContent=selected?.title||'RICH BIZNESS ARCADE'; if ($('#gameDesc')) $('#gameDesc').textContent=selected?.description||'Pick a featured game.'; if ($('#gameStatus')) $('#gameStatus').textContent=selected?`FEATURED ${(selected.game_type||selected.category||'GAME')} READY`.toUpperCase():'NO GAME'; if ($('#gameScore')) $('#gameScore').textContent=fmt(score); if ($('#playLink')) $('#playLink').href=selected?.play_url||'/gaming.html'; if ($('#gamePlayer')) $('#gamePlayer').textContent=(selected?.game_type||selected?.category)==='racing'?'🏎️':(selected?.game_type||selected?.category)==='sports'?'🏆':(selected?.game_type||selected?.category)==='fighting'?'🥊':(selected?.game_type||selected?.category)==='strategy'?'♟️':'RB'; document.querySelectorAll('[data-slug]').forEach(el=>el.classList.toggle('active',el.dataset.slug===selected?.slug)); window.dispatchEvent(new CustomEvent('rb-game-selected',{detail:selected})); }
async function countTable(table){ try{ const { count } = await supabase.from(table).select('*',{count:'exact',head:true}); return count || 0; } catch(_) { return 0; } }
async function loadCounts(){ const pairs = await Promise.all(GAME_TABLES.map(async t=>[t, await countTable(t)])); counts = Object.fromEntries(pairs); renderSystems(); }
async function load(){ const { data } = await supabase.from('games').select('*').order('is_featured',{ascending:false}).order('created_at',{ascending:false}).limit(80); games=(data||[]).map(g=>({...g,is_featured:true})); render(); const c=$('#recordCount'); if(c) c.textContent=fmt(games.length); }
async function getUser(){ const state=await getAuthoritativeIdentity(); user=state.user||null; return user; }
async function needUser(){ await getUser(); if(!user){ location.href='/auth.html?next=' + next; return null; } return user; }
async function joinRoom(){ if(!await needUser()) return; if(!selected) return; await supabase.from('game_rooms').insert({game_id:selected.id,game_slug:selected.slug,created_by:user.id,title:selected.title+' Room',status:'active',metadata:{source:'game-room'}}).then(()=>{},()=>{}); await awardXp('game_room_join',{section:'gaming',sourceTable:'games',sourceId:selected.id}); if ($('#gameStatus')) $('#gameStatus').textContent='ROOM JOINED'; loadCounts(); }
async function playMove(){ if(!await needUser()) return; if(!selected) return; score+=175; if ($('#gameScore')) $('#gameScore').textContent=fmt(score); await supabase.from('game_sessions').insert({game_id:selected.id,game_slug:selected.slug,user_id:user.id,score,result:'move',metadata:{source:'game-room',featured:true}}).then(()=>{},()=>{}); await supabase.from('game_moves').insert({game_id:selected.id,game_slug:selected.slug,user_id:user.id,move_type:'tap',score_delta:175,metadata:{source:'game-room'}}).then(()=>{},()=>{}); await awardXp('game_move',{section:'gaming',sourceTable:'games',sourceId:selected.id}); if ($('#gameStatus')) $('#gameStatus').textContent='MOVE SAVED'; loadCounts(); }
async function submitScore(){ if(!await needUser()) return; if(!selected) return; await supabase.from('game_scores').insert({game_id:selected.id,game_slug:selected.slug,user_id:user.id,score,mode:selected.game_type||selected.category||'arcade',platform_type:'web',metadata:{source:'game-room',featured:true}}).then(()=>{},()=>{}); await awardXp('game_score_submit',{section:'gaming',sourceTable:'games',sourceId:selected.id}); if ($('#gameStatus')) $('#gameStatus').textContent='SCORE SUBMITTED'; loadCounts(); }
async function saveClip(){ if(!await needUser()) return; if(!selected) return; await supabase.from('game_clips').insert({game_id:selected.id,game_slug:selected.slug,user_id:user.id,title:selected.title+' Clip',caption:'Rich Bizness arcade clip',metadata:{score,source:'game-room'}}).then(()=>{},()=>{}); if ($('#gameStatus')) $('#gameStatus').textContent='CLIP QUEUED'; loadCounts(); }
addCss(); ensureControls(); load(); loadCounts(); supabase.channel('game-room-ui').on('postgres_changes',{event:'*',schema:'public',table:'games'},load).on('postgres_changes',{event:'*',schema:'public',table:'game_scores'},loadCounts).on('postgres_changes',{event:'*',schema:'public',table:'game_sessions'},loadCounts).subscribe();