import { Room, createLocalTracks } from 'livekit-client';
import { supabase } from './supabase-client.js';
import { awardXp } from './rb-xp.js?v=xp-idempotent-1';
import { getAuthoritativeIdentity } from './rb-identity.js?v=tap-in-foundation-3';
import './rb-personality.js?v=copy-only-2';
import './section-language-foundation.js?v=copy-only-1';

const LIVE_TITLE = 'WE LIT🔥';
const LIVE_ROOM = 'Bizness Party';
const $ = (s) => document.querySelector(s);
let stream = null, user = null, profile = null, room = null, localTracks = [], previewing = false, live = false;

function roomName() { return user ? 'we-lit-' + user.id.slice(0, 8) : 'bizness-party'; }
function setStatus(text) { const el = $('#liveStudioStatus') || $('#tvStatus'); if (el) el.textContent = text; const state = $('#tvState'); if (state) state.textContent = text.includes('WE LIT') ? LIVE_TITLE : text.includes('ready') || text.includes('Ready') || text.includes('GET RIGHT') || text.includes('CAMERA') ? 'READY' : 'WORKING'; }
async function auth() { const state = await getAuthoritativeIdentity(); user = state.user; profile = state.profile || null; return state; }
async function getLiveKitToken(payload) { const res = await fetch('/api/livekit-token', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const data = await res.json().catch(() => ({})); if (!res.ok || !data?.token || !data?.livekitUrl) throw new Error(data?.error || 'Vercel LiveKit token failed'); return data; }
function registerMedia(){ window.__RB_LIVE_ROOM__ = room; window.__RB_LIVE_TRACKS__ = localTracks; }
function forceStopMedia() { try { window.__RB_LIVE_ROOM__?.disconnect?.(); } catch (_) {} try { room?.disconnect(); } catch (_) {} room = null; window.__RB_LIVE_ROOM__ = null; live = false; previewing = false; const allTracks = [...localTracks, ...(window.__RB_LIVE_TRACKS__ || [])]; allTracks.forEach((t) => { try { t.stop?.(); } catch (_) {} try { t.mediaStreamTrack?.stop?.(); } catch (_) {} try { t.detach?.().forEach((el) => el.remove()); } catch (_) {} }); localTracks = []; window.__RB_LIVE_TRACKS__ = []; document.querySelectorAll('video,audio').forEach((el) => { try { el.pause(); } catch (_) {} try { el.srcObject?.getTracks?.().forEach((track) => track.stop()); } catch (_) {} try { el.srcObject = null; } catch (_) {} try { el.removeAttribute('src'); el.load?.(); } catch (_) {} if (el.closest('#holoScreen')) el.remove(); }); const screen = $('#holoScreen'); if (screen) screen.innerHTML = idleScreen(); }
function attachVideo(track) { const screen = $('#holoScreen'); if (!screen || !track) return; screen.innerHTML = ''; const el = track.attach(); el.autoplay = true; el.muted = true; el.playsInline = true; el.setAttribute('data-rb-live-preview','true'); el.style.width = '100%'; el.style.height = '100%'; el.style.objectFit = 'cover'; el.style.borderRadius = '24px'; screen.appendChild(el); registerMedia(); }
function idleScreen() { return `<div class="holo-empty"><div class="holo-orb">RB</div><b>${LIVE_TITLE} READY</b><p>${LIVE_ROOM} • Get Right • camera + mic ready</p></div>`; }
function paint() { if (!previewing && !live && $('#holoScreen')) $('#holoScreen').innerHTML = idleScreen(); if ($('#tvTitle')) $('#tvTitle').textContent = stream?.title || LIVE_TITLE; if ($('#tvRoom')) $('#tvRoom').textContent = stream?.display_room_name || LIVE_ROOM; }
async function logEvent(type, payload = {}) { if (!stream?.id) return; await supabase.from('livekit_room_events').insert({ room_name: stream.livekit_room_name, stream_id: stream.id, event_type: type, participant_identity: user?.id || null, participant_name: profile?.display_name || user?.email || null, user_id: user?.id || null, payload }).catch(() => {}); }
async function saveHostMember() { if (!stream?.id || !user?.id) return; await supabase.from('live_stream_members').upsert({ stream_id: stream.id, user_id: user.id, role: 'host', status: 'active', joined_at: new Date().toISOString(), metadata: { source: 'live-studio', display_name: profile?.display_name || null, username: profile?.username || null } }, { onConflict: 'stream_id,user_id,role' }).catch(() => {}); }
async function preview() { try { await auth(); if (!user) { location.href = '/auth.html?next=' + encodeURIComponent('/live.html'); return; } if (!stream) paint(); if (localTracks.length) return; setStatus('CAMERA READY'); localTracks = await createLocalTracks({ audio: true, video: true }); registerMedia(); previewing = true; attachVideo(localTracks.find((t) => t.kind === 'video')); } catch (err) { setStatus(String(err.message || err)); console.warn(err); } }
async function goLive() { try { const state = await auth(); if (!state.session || !user) { location.href = '/auth.html?next=' + encodeURIComponent('/live.html'); return; } if (!localTracks.length) await preview(); setStatus(LIVE_TITLE); const lkRoom = roomName(); const lk = await getLiveKitToken({ room: lkRoom, role: 'host', identity: user.id, name: profile?.display_name || user.email || 'Rich Bizness Host' }); room = new Room({ adaptiveStream: true, dynacast: true }); registerMedia(); await room.connect(lk.livekitUrl, lk.token); for (const track of localTracks) await room.localParticipant.publishTrack(track); registerMedia(); const row = { creator_id: user.id, slug: lkRoom, display_slug: lkRoom, title: LIVE_TITLE, description: 'Bizness Party live room.', category: 'live', display_room_name: LIVE_ROOM, livekit_room_name: lkRoom, status: 'live', status_label: LIVE_TITLE, access_type: 'free', price_cents: 0, currency: 'usd', viewer_count: 0, peak_viewers: 0, total_chat_messages: 0, total_reactions: 0, is_chat_enabled: true, is_cohost_enabled: true, is_featured: true, started_at: new Date().toISOString(), last_activity_at: new Date().toISOString(), metadata: { brand: 'Rich Bizness', screen: 'live', token_source: 'vercel', livekit_url_source: 'vercel_env' } }; const upsert = await supabase.from('live_streams').upsert(row, { onConflict: 'slug' }).select().maybeSingle(); if (upsert.error) throw upsert.error; stream = upsert.data; await saveHostMember(); await logEvent('host_started', { room: lkRoom }); live = true; setStatus(LIVE_TITLE); paint(); await awardXp('live_started', { section: 'live', sourceTable: 'live_streams', sourceId: stream?.id }).catch(() => {}); } catch (err) { setStatus(String(err.message || err)); console.warn(err); } }
async function endLive() { try { if (stream?.id) { await logEvent('host_ended', { room: stream.livekit_room_name }); await supabase.from('live_stream_members').update({ status: 'left', left_at: new Date().toISOString() }).eq('stream_id', stream.id).eq('user_id', user?.id).eq('role', 'host').catch(() => {}); await supabase.from('live_streams').update({ status: 'ended', status_label: 'ROOM ENDED', ended_at: new Date().toISOString(), last_activity_at: new Date().toISOString() }).eq('id', stream.id); } forceStopMedia(); setStatus('READY'); paint(); } catch (err) { setStatus(String(err.message || err)); } }
$('#previewCam')?.addEventListener('click', preview);
$('#goLiveBtn')?.addEventListener('click', goLive);
$('#endLiveBtn')?.addEventListener('click', endLive);
$('#watchXp')?.addEventListener('click', () => { forceStopMedia(); location.href = '/watch.html'; });
$('#imOut')?.addEventListener('click', () => { forceStopMedia(); location.href = '/'; });
document.addEventListener('click', (event) => { const link = event.target.closest?.('a[href]'); if (link && !link.href.includes('/live.html')) forceStopMedia(); }, true);
window.addEventListener('pagehide', forceStopMedia);
window.addEventListener('beforeunload', forceStopMedia);
window.addEventListener('popstate', forceStopMedia);
document.addEventListener('visibilitychange', () => { if (document.hidden) forceStopMedia(); });
paint();
