import { supabase } from './supabase-client.js';

const mode=document.body.dataset.livePage||'live';
const $=(s)=>document.querySelector(s);
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=(v)=>{try{const u=new URL(String(v||''),location.origin);return ['http:','https:'].includes(u.protocol)?u.href:'';}catch{return '';}};
const slug=(v)=>String(v||'room').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,52)||'room';
let user=null,profile=null,selectedId=new URLSearchParams(location.search).get('stream')||'',disposed=false,busy=false,loading=false,queued=false,timer=null,channels=[],joined=false,lastReactionAt=0;

function status(message,tone='ready'){const n=$('#liveStatus');if(!n)return;n.textContent=message;n.dataset.tone=tone;}
function connection(message,tone='ready'){const n=$('#connectionState');if(!n)return;n.textContent=message;n.dataset.tone=tone;}
function clearChannels(){channels.forEach(c=>supabase?.removeChannel(c));channels=[];}
function schedule(){clearTimeout(timer);timer=setTimeout(load,160);}
function media(url,kind='image'){const s=safeUrl(url);if(!s)return '<div class="stage-empty">MEDIA NOT CONNECTED YET</div>';if(kind==='video')return `<video class="player" src="${esc(s)}" controls playsinline preload="metadata"></video>`;return `<img src="${esc(s)}" alt="" loading="lazy" decoding="async">`;}
function syncControls(){$('#joinRoom')?.toggleAttribute('hidden',joined);$('#leaveRoom')?.toggleAttribute('hidden',!joined);const input=$('#chatInput');if(input)input.disabled=!joined;}

async function identity(){const {data,error}=await supabase.auth.getUser();if(error)throw error;user=data?.user||null;if(!user)return;const r=await supabase.from('profiles').select('id,username,display_name,avatar_url').eq('id',user.id).maybeSingle();if(r.error)throw r.error;profile=r.data||null;}
function roomCard(r){const img=safeUrl(r.thumbnail_url||r.cover_url);const live=r.status==='live';return `<article class="room" tabindex="0" role="button" data-room="${esc(r.id)}">${img?`<img src="${esc(img)}" alt="">`:'<span class="room-media">RB</span>'}<span><h3>${esc(r.title||'Untitled Room')}</h3><small>${live?'<span class="live-dot"></span> LIVE NOW':esc(r.status_label||r.status||'ready')} • ${Number(r.viewer_count||0).toLocaleString()} watching</small></span><span>›</span></article>`;}
function recordingCard(r){const img=safeUrl(r.thumbnail_url||r.cover_url);return `<article class="recording" tabindex="0" role="button" data-recording="${esc(r.id)}">${img?`<img src="${esc(img)}" alt="">`:'<span class="recording-media">RB</span>'}<div><h3>${esc(r.title||'Rich Replay')}</h3><small>${Number(r.view_count||0).toLocaleString()} views • ${esc(r.status||'ready')}</small></div></article>`;}
function messageCard(m){return `<div class="message"><b>${esc(m.display_name||m.username||'Rich Member')}</b>${esc(m.message||m.body||'')}</div>`;}

async function loadMembership(){if(!user||!selectedId){joined=false;syncControls();return;}const {data,error}=await supabase.from('live_stream_members').select('id,status').eq('stream_id',selectedId).eq('user_id',user.id).maybeSingle();if(error)throw error;joined=Boolean(data&&data.status==='active');syncControls();}
async function joinRoom(){if(busy)return;if(!user){location.href=`/auth.html?next=${encodeURIComponent(location.pathname+location.search)}`;return;}if(!selectedId)return status('SELECT A ROOM FIRST','error');busy=true;connection('JOINING ROOM');try{const {error}=await supabase.from('live_stream_members').upsert({stream_id:selectedId,user_id:user.id,role:'viewer',status:'active',joined_at:new Date().toISOString(),left_at:null,metadata:{source:'live-owner'}},{onConflict:'stream_id,user_id'});if(error)throw error;joined=true;syncControls();connection('ROOM JOINED');status('YOU ARE IN THE ROOM');}catch(e){connection('JOIN FAILED','error');status(`JOIN FAILED • ${e.message}`,'error');}finally{busy=false;}}
async function leaveRoom(){if(busy||!user||!selectedId)return;busy=true;try{const {error}=await supabase.from('live_stream_members').update({status:'left',left_at:new Date().toISOString()}).eq('stream_id',selectedId).eq('user_id',user.id);if(error)throw error;joined=false;syncControls();connection('ROOM LEFT');status('YOU LEFT THE ROOM');}catch(e){status(`LEAVE FAILED • ${e.message}`,'error');}finally{busy=false;}}

async function loadRooms(){const {data,error,count}=await supabase.from('live_streams').select('*',{count:'exact'}).order('is_featured',{ascending:false}).order('created_at',{ascending:false}).limit(30);if(error)throw error;const rows=data||[];$('#liveMetric').textContent=Number(count??rows.length).toLocaleString();$('#roomList').innerHTML=rows.length?rows.map(roomCard).join(''):'<div class="stage-empty">No rooms are on the air yet.</div>';if(!selectedId&&rows[0])selectedId=rows[0].id;if(selectedId)await loadSelected();}
async function loadRecordings(){const {data,error,count}=await supabase.from('live_recordings').select('*',{count:'exact'}).eq('visibility','public').order('created_at',{ascending:false}).limit(36);if(error)throw error;const rows=data||[];$('#liveMetric').textContent=Number(count??rows.length).toLocaleString();$('#recordingList').innerHTML=rows.length?rows.map(recordingCard).join(''):'<div class="stage-empty">The replay vault is ready.</div>';const requested=new URLSearchParams(location.search).get('recording');if(requested&&rows.some(r=>r.id===requested))await openRecording(requested);}
async function loadSelected(){if(!selectedId)return;const {data:r,error}=await supabase.from('live_streams').select('*').eq('id',selectedId).maybeSingle();if(error)throw error;if(!r){status('ROOM NOT FOUND','error');return;}const ended=['ended','offline','completed'].includes(String(r.status||'').toLowerCase());$('#stage').innerHTML=media(r.recording_url||r.thumbnail_url||r.cover_url,r.recording_url?'video':'image');$('#roomTitle').textContent=r.title||'Rich Bizness Live';$('#roomMeta').textContent=`${r.status_label||r.status||'READY'} • ${Number(r.viewer_count||0).toLocaleString()} WATCHING`;if(ended)status('STREAM ENDED • REPLAY MAY BE AVAILABLE','error');const chat=await supabase.from('live_chat_messages').select('*').eq('stream_id',selectedId).eq('is_deleted',false).order('created_at',{ascending:true}).limit(100);if(chat.error)throw chat.error;$('#chatList').innerHTML=(chat.data||[]).map(messageCard).join('')||'<div class="stage-empty">Chat is ready.</div>';await loadMembership();restartScopedRealtime();}
async function openRecording(id){const {data,error}=await supabase.from('live_recordings').select('*').eq('id',id).maybeSingle();if(error)return status(`PLAYBACK FAILED • ${error.message}`,'error');if(!data)return status('REPLAY NOT FOUND','error');const url=safeUrl(data.recording_url);$('#watchStage').innerHTML=url?media(url,'video'):'<div class="stage-empty">Recording file is not connected yet.</div>';$('#watchTitle').textContent=data.title||'Rich Replay';history.replaceState({},'',`/watch.html?recording=${encodeURIComponent(id)}`);}

async function load(){if(loading){queued=true;return;}loading=true;queued=false;status(mode==='watch'?'SYNCING REPLAY VAULT':'SYNCING LIVE UNIVERSE');try{if(mode==='watch')await loadRecordings();else await loadRooms();if(!disposed)status(navigator.onLine?'CONNECTED • ONE LIVE OWNER':'OFFLINE • WAITING TO RECONNECT',navigator.onLine?'ready':'error');}catch(e){if(!disposed)status(`SYNC ERROR • ${e.message}`,'error');}finally{loading=false;if(queued&&!disposed)load();}}
function restartScopedRealtime(){clearChannels();const base=[['live_streams',null],['live_recordings',null]];if(selectedId&&mode==='live')base.push(['live_chat_messages',`stream_id=eq.${selectedId}`],['live_reactions',`stream_id=eq.${selectedId}`],['live_stream_members',`stream_id=eq.${selectedId}`]);base.forEach(([table,filter],i)=>{const cfg={event:'*',schema:'public',table};if(filter)cfg.filter=filter;channels.push(supabase.channel(`rb-live:${mode}:${i}`).on('postgres_changes',cfg,schedule).subscribe(state=>{if(state==='SUBSCRIBED')connection('REALTIME CONNECTED');if(['CHANNEL_ERROR','TIMED_OUT'].includes(state))connection('REALTIME RECOVERING','error');}));});}

async function createRoom(e){e.preventDefault();if(busy)return;if(!user)return status('TAP IN BEFORE STARTING A ROOM','error');const title=String($('#roomName')?.value||'').trim();const description=String($('#roomDescription')?.value||'').trim();const category=$('#roomCategory')?.value||'general';if(!title)return status('NAME THE ROOM','error');busy=true;$('#roomSubmit').disabled=true;try{const roomSlug=`${slug(title)}-${Date.now().toString(36)}`;const {data,error}=await supabase.from('live_streams').insert({creator_id:user.id,slug:roomSlug,display_slug:roomSlug,title,description,category,status:'scheduled',status_label:'ROOM READY',access_type:'free',price_cents:0,currency:'usd',livekit_room_name:`rb-${user.id}-${Date.now()}`,display_room_name:title,viewer_count:0,peak_viewers:0,total_chat_messages:0,total_reactions:0,is_chat_enabled:true,is_cohost_enabled:true,is_vip_enabled:false,is_featured:false,metadata:{source:'live-owner',livekit_token_state:'required'}}).select('id').single();if(error)throw error;selectedId=data.id;e.currentTarget.reset();status('ROOM CREATED • LIVEKIT TOKEN REQUIRED');await load();}catch(err){status(`ROOM FAILED • ${err.message}`,'error');}finally{busy=false;$('#roomSubmit').disabled=false;}}
async function sendChat(e){e.preventDefault();if(!user)return status('TAP IN TO CHAT','error');if(!selectedId)return status('SELECT A ROOM','error');if(!joined)return status('JOIN THE ROOM TO CHAT','error');const input=$('#chatInput');const body=String(input?.value||'').trim().slice(0,500);if(!body)return;const {error}=await supabase.from('live_chat_messages').insert({stream_id:selectedId,user_id:user.id,username:profile?.username||user.email?.split('@')[0]||'member',display_name:profile?.display_name||user.user_metadata?.display_name||'Rich Member',message:body,body,is_pinned:false,is_deleted:false,metadata:{source:'live-owner'}});if(error)return status(`CHAT FAILED • ${error.message}`,'error');input.value='';}
async function react(value){if(!user)return status('TAP IN TO REACT','error');if(!selectedId)return status('SELECT A ROOM','error');if(!joined)return status('JOIN THE ROOM TO REACT','error');const now=Date.now();if(now-lastReactionAt<900)return status('REACTIONS COOLING DOWN','error');lastReactionAt=now;const {error}=await supabase.from('live_reactions').insert({stream_id:selectedId,user_id:user.id,reaction:value,metadata:{source:'live-owner'}});if(error)status(`REACTION FAILED • ${error.message}`,'error');}

function bindMediaStates(){document.addEventListener('play',e=>{if(e.target.matches('video,audio'))status(mode==='watch'?'REPLAY PLAYING':'LIVE MEDIA PLAYING');},true);document.addEventListener('waiting',e=>{if(e.target.matches('video,audio'))status('MEDIA BUFFERING');},true);document.addEventListener('error',e=>{if(e.target.matches('video,audio'))status('MEDIA PLAYBACK FAILED','error');},true);document.addEventListener('ended',e=>{if(e.target.matches('video,audio'))status(mode==='watch'?'REPLAY ENDED':'STREAM ENDED');},true);}
function bind(){
  $('#roomForm')?.addEventListener('submit',createRoom);$('#chatForm')?.addEventListener('submit',sendChat);$('#joinRoom')?.addEventListener('click',joinRoom);$('#leaveRoom')?.addEventListener('click',leaveRoom);
  document.addEventListener('click',async e=>{const room=e.target.closest('[data-room]');if(room){selectedId=room.dataset.room;history.replaceState({},'',`/live.html?stream=${encodeURIComponent(selectedId)}`);await loadSelected();return;}const rec=e.target.closest('[data-recording]');if(rec){await openRecording(rec.dataset.recording);return;}const reaction=e.target.closest('[data-reaction]');if(reaction)await react(reaction.dataset.reaction);});
  document.addEventListener('keydown',e=>{if(!['Enter',' '].includes(e.key))return;const room=e.target.closest('[data-room]');const rec=e.target.closest('[data-recording]');if(room){e.preventDefault();room.click();}if(rec){e.preventDefault();rec.click();}});
  addEventListener('online',()=>{connection('ONLINE');status('CONNECTION RESTORED');schedule();restartScopedRealtime();});addEventListener('offline',()=>{connection('OFFLINE','error');status('OFFLINE • LIVE WILL RETRY','error');});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){connection(navigator.onLine?'ACTIVE':'OFFLINE',navigator.onLine?'ready':'error');schedule();}else connection('BACKGROUND MODE');});
  bindMediaStates();
}
function cleanup(){disposed=true;clearTimeout(timer);clearChannels();}
async function boot(){if(!supabase)return status('SUPABASE ENV VARIABLES REQUIRED','error');try{connection(navigator.onLine?'ONLINE':'OFFLINE',navigator.onLine?'ready':'error');await identity();bind();syncControls();await load();restartScopedRealtime();window.addEventListener('pagehide',cleanup,{once:true});}catch(e){status(`BOOT FAILED • ${e.message}`,'error');}}
boot();
