import { supabase } from './supabase-client.js';

const mode = document.body.dataset.livePage || 'live';
const $ = (s) => document.querySelector(s);
const esc = (v='') => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl = (v) => { try { const u = new URL(String(v||''), location.origin); return ['http:','https:'].includes(u.protocol) ? u.href : ''; } catch { return ''; } };
const slug = (v) => String(v||'room').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,52) || 'room';
let user=null, profile=null, selectedId=new URLSearchParams(location.search).get('stream') || '', disposed=false, busy=false, loading=false, queued=false, timer=null, channels=[];

function status(message,tone='ready'){ const n=$('#liveStatus'); if(!n)return; n.textContent=message; n.dataset.tone=tone; }
function clearChannels(){ channels.forEach(c=>supabase?.removeChannel(c)); channels=[]; }
function schedule(){ clearTimeout(timer); timer=setTimeout(load,160); }
function media(url,kind='image'){ const s=safeUrl(url); if(!s)return '<div class="stage-empty">ROOM VISUAL READY</div>'; if(kind==='video')return `<video class="player" src="${esc(s)}" controls playsinline preload="metadata"></video>`; return `<img src="${esc(s)}" alt="" loading="lazy" decoding="async">`; }

async function identity(){ const {data}=await supabase.auth.getUser(); user=data?.user||null; if(!user)return; const r=await supabase.from('profiles').select('id,username,display_name,avatar_url').eq('id',user.id).maybeSingle(); profile=r.data||null; }

function roomCard(r){ const img=safeUrl(r.thumbnail_url||r.cover_url); const live=r.status==='live'; return `<article class="room" data-room="${esc(r.id)}">${img?`<img src="${esc(img)}" alt="">`:'<span class="room-media">RB</span>'}<span><h3>${esc(r.title||'Untitled Room')}</h3><small>${live?'<span class="live-dot"></span> LIVE NOW':esc(r.status_label||r.status||'ready')} • ${Number(r.viewer_count||0).toLocaleString()} watching</small></span><span>›</span></article>`; }
function recordingCard(r){ const img=safeUrl(r.thumbnail_url||r.cover_url); return `<article class="recording" data-recording="${esc(r.id)}">${img?`<img src="${esc(img)}" alt="">`:'<span class="recording-media">RB</span>'}<div><h3>${esc(r.title||'Rich Replay')}</h3><small>${Number(r.view_count||0).toLocaleString()} views • ${esc(r.status||'ready')}</small></div></article>`; }
function messageCard(m){ return `<div class="message"><b>${esc(m.display_name||m.username||'Rich Member')}</b>${esc(m.message||m.body||'')}</div>`; }

async function loadRooms(){ const {data,error,count}=await supabase.from('live_streams').select('*',{count:'exact'}).order('is_featured',{ascending:false}).order('created_at',{ascending:false}).limit(30); if(error)throw error; const rows=data||[]; $('#liveMetric').textContent=Number(count??rows.length).toLocaleString(); $('#roomList').innerHTML=rows.length?rows.map(roomCard).join(''):'<div class="stage-empty">No rooms are on the air yet.</div>'; if(!selectedId&&rows[0])selectedId=rows[0].id; if(selectedId)await loadSelected(); }
async function loadRecordings(){ const {data,error,count}=await supabase.from('live_recordings').select('*',{count:'exact'}).eq('visibility','public').order('created_at',{ascending:false}).limit(36); if(error)throw error; const rows=data||[]; $('#liveMetric').textContent=Number(count??rows.length).toLocaleString(); $('#recordingList').innerHTML=rows.length?rows.map(recordingCard).join(''):'<div class="stage-empty">The replay vault is ready.</div>'; }
async function loadSelected(){ if(!selectedId)return; const {data:r,error}=await supabase.from('live_streams').select('*').eq('id',selectedId).maybeSingle(); if(error)throw error; if(!r)return; $('#stage').innerHTML=media(r.thumbnail_url||r.cover_url||r.recording_url,r.recording_url?'video':'image'); $('#roomTitle').textContent=r.title||'Rich Bizness Live'; $('#roomMeta').textContent=`${r.status_label||r.status||'READY'} • ${Number(r.viewer_count||0).toLocaleString()} WATCHING`;
 const chat=await supabase.from('live_chat_messages').select('*').eq('stream_id',selectedId).eq('is_deleted',false).order('created_at',{ascending:true}).limit(100); if(chat.error)throw chat.error; $('#chatList').innerHTML=(chat.data||[]).map(messageCard).join('')||'<div class="stage-empty">Chat is ready.</div>'; restartScopedRealtime(); }

async function load(){ if(loading){queued=true;return;} loading=true; queued=false; status('SYNCING LIVE UNIVERSE'); try{ if(mode==='watch')await loadRecordings(); else await loadRooms(); status('CONNECTED • ONE LIVE OWNER'); }catch(e){ if(!disposed)status(`SYNC ERROR • ${e.message}`,'error'); }finally{loading=false;if(queued&&!disposed)load();} }

function restartScopedRealtime(){ clearChannels(); const base=[['live_streams',null],['live_recordings',null]]; if(selectedId)base.push(['live_chat_messages',`stream_id=eq.${selectedId}`],['live_reactions',`stream_id=eq.${selectedId}`]); base.forEach(([table,filter],i)=>{const cfg={event:'*',schema:'public',table};if(filter)cfg.filter=filter;channels.push(supabase.channel(`rb-live:${mode}:${i}`).on('postgres_changes',cfg,schedule).subscribe());}); }

async function createRoom(e){ e.preventDefault(); if(busy)return; if(!user)return status('TAP IN BEFORE STARTING A ROOM','error'); const title=String($('#roomName')?.value||'').trim(); const description=String($('#roomDescription')?.value||'').trim(); const category=$('#roomCategory')?.value||'general'; if(!title)return status('NAME THE ROOM','error'); busy=true; $('#roomSubmit').disabled=true; try{const roomSlug=`${slug(title)}-${Date.now().toString(36)}`; const {data,error}=await supabase.from('live_streams').insert({creator_id:user.id,slug:roomSlug,display_slug:roomSlug,title,description,category,status:'scheduled',status_label:'ROOM READY',access_type:'free',price_cents:0,currency:'usd',livekit_room_name:`rb-${user.id}-${Date.now()}`,display_room_name:title,viewer_count:0,peak_viewers:0,total_chat_messages:0,total_reactions:0,is_chat_enabled:true,is_cohost_enabled:true,is_vip_enabled:false,is_featured:false,metadata:{source:'live-owner'}}).select('id').single(); if(error)throw error; selectedId=data.id; e.currentTarget.reset(); status('ROOM CREATED • READY TO CONNECT LIVEKIT'); await load(); }catch(err){status(`ROOM FAILED • ${err.message}`,'error');}finally{busy=false;$('#roomSubmit').disabled=false;} }

async function sendChat(e){ e.preventDefault(); if(!user)return status('TAP IN TO CHAT','error'); if(!selectedId)return status('SELECT A ROOM','error'); const input=$('#chatInput'); const body=String(input?.value||'').trim().slice(0,500); if(!body)return; const {error}=await supabase.from('live_chat_messages').insert({stream_id:selectedId,user_id:user.id,username:profile?.username||user.email?.split('@')[0]||'member',display_name:profile?.display_name||user.user_metadata?.display_name||'Rich Member',message:body,body,is_pinned:false,is_deleted:false,metadata:{source:'live-owner'}}); if(error)return status(`CHAT FAILED • ${error.message}`,'error'); input.value=''; }
async function react(value){ if(!user)return status('TAP IN TO REACT','error'); if(!selectedId)return; const {error}=await supabase.from('live_reactions').insert({stream_id:selectedId,user_id:user.id,reaction:value,metadata:{source:'live-owner'}}); if(error)status(`REACTION FAILED • ${error.message}`,'error'); }

function bind(){ $('#roomForm')?.addEventListener('submit',createRoom); $('#chatForm')?.addEventListener('submit',sendChat); document.addEventListener('click',async e=>{const room=e.target.closest('[data-room]'); if(room){selectedId=room.dataset.room; history.replaceState({},'',`/live.html?stream=${encodeURIComponent(selectedId)}`); await loadSelected(); return;} const rec=e.target.closest('[data-recording]'); if(rec){const {data,error}=await supabase.from('live_recordings').select('*').eq('id',rec.dataset.recording).maybeSingle(); if(error)return status(`PLAYBACK FAILED • ${error.message}`,'error'); const url=safeUrl(data?.recording_url); $('#watchStage').innerHTML=url?media(url,'video'):'<div class="stage-empty">Recording file is not connected yet.</div>'; $('#watchTitle').textContent=data?.title||'Rich Replay'; return;} const reaction=e.target.closest('[data-reaction]'); if(reaction)await react(reaction.dataset.reaction);}); }
function cleanup(){disposed=true;clearTimeout(timer);clearChannels();}
async function boot(){ if(!supabase)return status('SUPABASE ENV VARIABLES REQUIRED','error'); try{await identity();bind();await load();restartScopedRealtime();window.addEventListener('pagehide',cleanup,{once:true});}catch(e){status(`BOOT FAILED • ${e.message}`,'error');}}
boot();