import { supabase } from './supabase-client.js';
import { awardXp } from './rb-xp.js?v=realtime-1';
import './rb-personality.js?v=rb-live-owner-1';

const OWNED = ['live_streams','live_stream_members','live_view_sessions','live_chat_messages','live_reactions','live_recordings','livekit_room_events'];
const $ = (s) => document.querySelector(s);
const fmt = (n) => Number(n || 0).toLocaleString();
let counts = {}, streams = [];
function addCss(){ if($('#liveOwnerCss')) return; const l=document.createElement('link'); l.id='liveOwnerCss'; l.rel='stylesheet'; l.href='/src/live-owner.css?v=live-owner-1'; document.head.appendChild(l); }
async function countTable(table){ try { const { count } = await supabase.from(table).select('*',{count:'exact',head:true}); return count || 0; } catch(_) { return 0; } }
async function loadCounts(){ const pairs = await Promise.all(OWNED.map(async t => [t, await countTable(t)])); counts = Object.fromEntries(pairs); renderSystems(); }
async function loadStreams(){ const { data } = await supabase.from('live_streams').select('id,title,status,status_label,display_room_name,livekit_room_name,viewer_count,total_chat_messages,total_reactions,created_at').order('created_at',{ascending:false}).limit(8); streams = data || []; renderStreams(); }
function mount(){ if($('#liveOwner')) return; const main = document.querySelector('main') || document.body; const panel = document.createElement('section'); panel.id='liveOwner'; panel.className='live-owner'; panel.innerHTML = `<div class="live-owner-head"><div><small>WE LIT🔥 OWNER</small><b>Bizness Party Control</b><p>Get Right — streams, members, viewers, chat, reactions, recordings, and LiveKit room events tied together.</p></div><small id="liveOwnerStatus">READY</small></div><div class="live-owner-actions"><a href="/live.html">GO LIVE</a><a href="/watch.html">WATCHING</a><a href="/messages.html">Rich-DM’s</a><a href="/upload.html?section=live-thumbnail">DROP THUMBNAIL</a><a href="/upload.html?section=live-recording">DROP REPLAY</a><button id="liveOwnerRefresh" type="button">REFRESH</button></div><div class="live-owner-systems" id="liveOwnerSystems"></div><div class="live-owner-grid" id="liveOwnerGrid"></div>`; main.appendChild(panel); $('#liveOwnerRefresh')?.addEventListener('click',refresh); }
function renderSystems(){ const box=$('#liveOwnerSystems'); if(!box) return; box.innerHTML = OWNED.map(t=>`<article class="live-owner-system"><b>${t.replaceAll('_',' ').toUpperCase()}</b><small>${fmt(counts[t])} records</small></article>`).join(''); }
function renderStreams(){ const box=$('#liveOwnerGrid'); if(!box) return; box.innerHTML = streams.length ? streams.map(s=>`<article class="live-owner-card"><b>${s.title || 'WE LIT🔥'}</b><p>${s.display_room_name || 'Bizness Party'} • ${s.status_label || 'Get Right'}</p><small>${String(s.status || 'ready').toUpperCase()} • ${fmt(s.viewer_count)} viewers • ${fmt(s.total_chat_messages)} chat • ${fmt(s.total_reactions)} reactions</small></article>`).join('') : '<article class="live-owner-card"><b>No room live yet</b><p>Start WE LIT🔥 from Live and Watch will join the same Bizness Party room.</p></article>'; }
async function refresh(){ await loadCounts(); await loadStreams(); $('#liveOwnerStatus') && ($('#liveOwnerStatus').textContent='SYNCED'); awardXp('live_owner_view',{section:document.body?.dataset?.section || 'live',sourceTable:'live_streams'}).catch(()=>{}); }
addCss(); mount(); refresh(); supabase.channel('live-owner-all').on('postgres_changes',{event:'*',schema:'public',table:'live_streams'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'live_chat_messages'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'live_reactions'},refresh).subscribe();
