import { supabase } from './supabase-client.js';
const q=s=>document.querySelector(s);
let user=null,threads=[],active=null,channel=null;
function text(id,value){const n=q(id);if(n)n.textContent=value}
async function boot(){if(!supabase){text('#messageStatus','SUPABASE ENV REQUIRED');return}const auth=await supabase.auth.getUser();user=auth.data?.user||null;if(!user){text('#messageStatus','SIGN IN REQUIRED');return}bind();await loadThreads();text('#messageStatus','MESSAGES CONNECTED')}
async function loadThreads(){const m=await supabase.from('dm_thread_members').select('thread_id').eq('user_id',user.id).eq('status','active');const ids=(m.data||[]).map(x=>x.thread_id);threads=[];if(ids.length){const r=await supabase.from('dm_threads').select('*').in('id',ids).order('last_message_at',{ascending:false,nullsFirst:false});threads=r.data||[]}text('#threadCount',String(threads.length));const box=q('#threadList');box.replaceChildren();for(const row of threads){const b=document.createElement('button');b.className='thread';b.dataset.thread=row.id;b.textContent=row.title||'Conversation';box.append(b)}if(!threads.length)text('#threadList','No conversations yet.')}
async function choose(id){active=threads.find(x=>x.id===id)||null;text('#activeThread',active?.title||'SELECT A THREAD');await loadMessages();if(channel)await supabase.removeChannel(channel);channel=supabase.channel('messages-'+id).on('postgres_changes',{event:'*',schema:'public',table:'dm_messages',filter:'thread_id=eq.'+id},loadMessages).subscribe()}
async function loadMessages(){if(!active)return;const r=await supabase.from('dm_messages').select('*').eq('thread_id',active.id).eq('is_deleted',false).order('created_at');const box=q('#messageList');box.replaceChildren();for(const row of r.data||[]){const d=document.createElement('div');d.className='message'+(row.sender_id===user.id?' mine':'');const b=document.createElement('b');b.textContent=row.display_name||row.username||'Member';const p=document.createElement('p');p.textContent=row.body||'';d.append(b,p);box.append(d)}if(!(r.data||[]).length)text('#messageList','Start the conversation.')}
async function send(e){e.preventDefault();if(!active)return;const input=q('#messageBody');const body=input.value.trim();if(!body)return;const p=await supabase.from('profiles').select('username,display_name').eq('id',user.id).maybeSingle();await supabase.from('dm_messages').insert({thread_id:active.id,sender_id:user.id,username:p.data?.username||'member',display_name:p.data?.display_name||'Rich Bizness Member',body,message_type:'text',bubble_style:'smoke-cloud'});await supabase.from('dm_threads').update({last_message:body,last_message_at:new Date().toISOString(),last_message_user_id:user.id}).eq('id',active.id);input.value=''}
async function group(e){e.preventDefault();const title=q('#threadTitle').value.trim();if(!title)return;const r=await supabase.from('dm_threads').insert({title,thread_type:'group',created_by:user.id,dm_brand:'Rich DMs',bubble_theme:'smoke-cloud'}).select().single();if(r.data){await supabase.from('dm_thread_members').insert({thread_id:r.data.id,user_id:user.id,role:'owner',status:'active'});q('#threadTitle').value='';await loadThreads();await choose(r.data.id)}}
async function call(){if(!active)return;await supabase.from('dm_call_sessions').insert({thread_id:active.id,started_by:user.id,call_type:'video',call_status:'ringing',livekit_room_name:'rb-'+active.id+'-'+Date.now(),call_theme:'Rich Call'});text('#messageStatus','CALL SESSION CREATED')}
function bind(){document.addEventListener('click',e=>{const n=e.target.closest('[data-thread]');if(n)choose(n.dataset.thread)});q('#messageForm').addEventListener('submit',send);q('#threadForm').addEventListener('submit',group);q('#callButton').addEventListener('click',call)}
boot();