import { supabase } from './supabase-client.js';
const q=s=>document.querySelector(s),esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let user=null,profile=null,threads=[],active=null,channels=[],typingTimer=null,replyTo=null,disposed=false,busy=false;
function text(id,value){const n=q(id);if(n)n.textContent=value}
function status(m,t='ready'){text('#messageStatus',m);const n=q('#messageStatus');if(n)n.dataset.tone=t}
function safeUrl(v){try{const u=new URL(String(v||''),location.origin);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}}
async function identity(){const a=await supabase.auth.getUser();user=a.data?.user||null;if(!user){location.href='/auth.html?next=%2Fmessages.html';return false}const p=await supabase.from('profiles').select('username,display_name').eq('id',user.id).maybeSingle();profile=p.data||null;return true}
async function loadThreads(){status('SYNCING THREADS');const m=await supabase.from('dm_thread_members').select('thread_id,last_read_at').eq('user_id',user.id).eq('status','active');if(m.error)throw m.error;const map=new Map((m.data||[]).map(x=>[x.thread_id,x.last_read_at]));const ids=[...map.keys()];threads=[];if(ids.length){const r=await supabase.from('dm_threads').select('*').in('id',ids).eq('is_archived',false).order('last_message_at',{ascending:false,nullsFirst:false});if(r.error)throw r.error;threads=r.data||[]}text('#threadCount',String(threads.length));q('#threadList').innerHTML=threads.length?threads.map(row=>`<button class="thread" data-thread="${esc(row.id)}"><b>${esc(row.title||'Conversation')}</b><small>${esc(row.last_message||row.thread_type||'No messages yet')}</small></button>`).join(''):'<div class="empty">No conversations yet.</div>';status('MESSAGES CONNECTED')}
async function choose(id){active=threads.find(x=>x.id===id)||null;text('#activeThread',active?.title||'SELECT A THREAD');replyTo=null;q('#replyBar').hidden=true;await loadMessages();channels.forEach(c=>supabase.removeChannel(c));channels=[];if(!active)return;channels.push(supabase.channel('messages-'+id).on('postgres_changes',{event:'*',schema:'public',table:'dm_messages',filter:'thread_id=eq.'+id},loadMessages).on('postgres_changes',{event:'*',schema:'public',table:'dm_typing_status',filter:'thread_id=eq.'+id},loadTyping).on('postgres_changes',{event:'*',schema:'public',table:'dm_call_sessions',filter:'thread_id=eq.'+id},loadCallState).subscribe(s=>{text('#messageConnection',s==='SUBSCRIBED'?'LIVE':'RECONNECTING')}));await Promise.all([markRead(),loadTyping(),loadCallState()])}
async function loadMessages(){if(!active)return;const r=await supabase.from('dm_messages').select('*').eq('thread_id',active.id).eq('is_deleted',false).order('created_at').limit(200);if(r.error)return status('MESSAGE LOAD FAILED','error');q('#messageList').innerHTML=(r.data||[]).map(row=>`<article class="message${row.sender_id===user.id?' mine':''}" data-message="${esc(row.id)}"><b>${esc(row.display_name||row.username||'Member')}</b>${row.reply_to_message_id?'<small>↪ reply</small>':''}<p>${esc(row.body||'')}</p>${safeUrl(row.media_url)?`<a href="${esc(safeUrl(row.media_url))}" target="_blank" rel="noreferrer">OPEN ATTACHMENT</a>`:''}<div class="message-actions"><button type="button" data-reply="${esc(row.id)}">REPLY</button><button type="button" data-react="${esc(row.id)}">💨</button></div></article>`).join('')||'<div class="empty">Start the conversation.</div>';q('#messageList').scrollTop=q('#messageList').scrollHeight;await markRead()}
async function markRead(){if(!active)return;const now=new Date().toISOString();await supabase.from('dm_thread_members').update({last_read_at:now}).eq('thread_id',active.id).eq('user_id',user.id);const r=await supabase.from('dm_messages').select('id').eq('thread_id',active.id).neq('sender_id',user.id).eq('is_deleted',false).order('created_at',{ascending:false}).limit(50);for(const row of r.data||[])await supabase.from('dm_message_reads').upsert({message_id:row.id,thread_id:active.id,user_id:user.id,read_at:now},{onConflict:'message_id,user_id'})}
async function send(e){e.preventDefault();if(!active||busy)return;const body=q('#messageBody').value.trim(),media=safeUrl(q('#messageAttachment').value);if(!body&&!media)return;busy=true;const r=await supabase.from('dm_messages').insert({thread_id:active.id,sender_id:user.id,username:profile?.username||'member',display_name:profile?.display_name||'Rich Bizness Member',body,media_url:media||null,media_type:media?'link':null,message_type:media?'file':'text',reply_to_message_id:replyTo,bubble_style:'smoke-cloud'});if(!r.error)await supabase.from('dm_threads').update({last_message:body||'Attachment',last_message_at:new Date().toISOString(),last_message_user_id:user.id}).eq('id',active.id);busy=false;if(r.error)return status('SEND FAILED • '+r.error.message,'error');e.currentTarget.reset();replyTo=null;q('#replyBar').hidden=true;await setTyping(false)}
async function group(e){e.preventDefault();const title=q('#threadTitle').value.trim();if(!title)return;const r=await supabase.from('dm_threads').insert({title,thread_type:'group',created_by:user.id,dm_brand:'Rich DMs',bubble_theme:'smoke-cloud'}).select().single();if(r.error)return status('GROUP FAILED • '+r.error.message,'error');await supabase.from('dm_thread_members').insert({thread_id:r.data.id,user_id:user.id,role:'owner',status:'active'});e.currentTarget.reset();await loadThreads();await choose(r.data.id)}
async function direct(e){e.preventDefault();const name=q('#directUser').value.trim().toLowerCase();if(!name)return;const p=await supabase.from('profiles').select('id,display_name,username').eq('username',name).maybeSingle();if(!p.data)return status('USER NOT FOUND','error');const r=await supabase.from('dm_threads').insert({title:p.data.display_name||p.data.username,thread_type:'direct',created_by:user.id,dm_brand:'Rich DMs',bubble_theme:'smoke-cloud'}).select().single();if(r.error)return status('DIRECT FAILED','error');await supabase.from('dm_thread_members').insert([{thread_id:r.data.id,user_id:user.id,role:'owner',status:'active'},{thread_id:r.data.id,user_id:p.data.id,role:'member',status:'active'}]);e.currentTarget.reset();q('#directForm').hidden=true;await loadThreads();await choose(r.data.id)}
async function react(id){if(!id)return;const existing=await supabase.from('dm_message_reactions').select('id').eq('message_id',id).eq('user_id',user.id).eq('emoji','💨').maybeSingle();const r=existing.data?await supabase.from('dm_message_reactions').delete().eq('id',existing.data.id):await supabase.from('dm_message_reactions').insert({message_id:id,user_id:user.id,emoji:'💨',reaction_style:'smoke-cloud'});status(r.error?'REACTION FAILED':'REACTION UPDATED',r.error?'error':'ready')}
async function setTyping(flag){if(!active)return;await supabase.from('dm_typing_status').upsert({thread_id:active.id,user_id:user.id,is_typing:flag,typing_label:'rolling smoke…',updated_at:new Date().toISOString()},{onConflict:'thread_id,user_id'})}
async function loadTyping(){if(!active)return;const r=await supabase.from('dm_typing_status').select('user_id,typing_label,updated_at').eq('thread_id',active.id).eq('is_typing',true).neq('user_id',user.id);const live=(r.data||[]).filter(x=>Date.now()-new Date(x.updated_at).getTime()<8000);text('#typingState',live.length?(live[0].typing_label||'typing…'):'')}
async function call(){if(!active)return;const r=await supabase.from('dm_call_sessions').insert({thread_id:active.id,started_by:user.id,call_type:'video',call_status:'ringing',livekit_room_name:'rb-'+active.id+'-'+Date.now(),call_theme:'Rich Call'});status(r.error?'CALL FAILED':'CALL INVITATION CREATED',r.error?'error':'ready')}
async function loadCallState(){if(!active)return;const r=await supabase.from('dm_call_sessions').select('call_status,call_type').eq('thread_id',active.id).order('created_at',{ascending:false}).limit(1).maybeSingle();text('#callState',r.data?`${r.data.call_type||'call'} • ${r.data.call_status||'ready'}`:'')}
function bind(){document.addEventListener('click',e=>{const t=e.target.closest('[data-thread]');if(t)return choose(t.dataset.thread);const r=e.target.closest('[data-reply]');if(r){replyTo=r.dataset.reply;text('#replyLabel','Replying to message');q('#replyBar').hidden=false}const x=e.target.closest('[data-react]');if(x)react(x.dataset.react)});q('#messageForm').addEventListener('submit',send);q('#threadForm').addEventListener('submit',group);q('#directForm').addEventListener('submit',direct);q('#newDirect').addEventListener('click',()=>q('#directForm').hidden=!q('#directForm').hidden);q('#cancelReply').addEventListener('click',()=>{replyTo=null;q('#replyBar').hidden=true});q('#callButton').addEventListener('click',call);q('#reactButton').addEventListener('click',()=>{const last=q('#messageList [data-message]:last-child');if(last)react(last.dataset.message)});q('#messageBody').addEventListener('input',()=>{clearTimeout(typingTimer);setTyping(true);typingTimer=setTimeout(()=>setTyping(false),1500)});addEventListener('online',()=>{text('#messageConnection','LIVE');active&&choose(active.id)});addEventListener('offline',()=>text('#messageConnection','OFFLINE'))}
function cleanup(){disposed=true;clearTimeout(typingTimer);channels.forEach(c=>supabase.removeChannel(c));channels=[];setTyping(false)}
async function boot(){if(!supabase)return status('SUPABASE ENV REQUIRED','error');if(!await identity())return;bind();await loadThreads();if(threads[0])await choose(threads[0].id);addEventListener('pagehide',cleanup,{once:true})}boot();