import { supabase } from './supabase-client.js';
const $=s=>document.querySelector(s);let worlds=[],selected=null,user=null,channel=null,timer=null,disposed=false;
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function status(m,t='ready'){const n=$('#metaStatus');if(n){n.textContent=m;n.dataset.tone=t}}
function safe(v){try{const u=new URL(String(v||''),location.origin);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}}
function card(w){const img=safe(w.cover_url||w.background_url);return `<article class="card">${img?`<img src="${esc(img)}" alt="" loading="lazy">`:'<span class="fallback">RB</span>'}<span><b>${esc(w.title||'Untitled world')}</b><small>${esc([w.world_type,w.access_type,w.status].filter(Boolean).join(' • '))}</small></span><button type="button" data-world="${esc(w.id)}">SELECT</button></article>`}
async function identity(){const {data}=await supabase.auth.getUser();user=data?.user||null}
async function paint(){if(!selected){$('#worldTitle').textContent='SELECT A WORLD';$('#worldDescription').textContent='Portals, avatars, and creator worlds live here.';$('#portalList').innerHTML='';return}$('#worldTitle').textContent=selected.title||'Untitled world';$('#worldDescription').textContent=selected.description||'Rich Bizness creator world.';const {data}=await supabase.from('meta_portals').select('title,icon,portal_style').eq('world_id',selected.id).eq('is_active',true).order('sort_order').limit(20);$('#portalList').innerHTML=(data||[]).map(p=>`<div class="portal"><b>${esc(p.icon||'◎')} ${esc(p.title)}</b><small>${esc(p.portal_style||'portal')}</small></div>`).join('')||'<div class="empty">No active portals yet.</div>'}
async function load(){if(disposed)return;status('SYNCING META WORLDS');const {data,error}=await supabase.from('meta_worlds').select('*').order('is_featured',{ascending:false}).order('created_at',{ascending:false}).limit(50);if(error)return status(`META ERROR • ${error.message}`,'error');worlds=data||[];selected=selected?worlds.find(w=>w.id===selected.id)||worlds[0]||null:worlds[0]||null;$('#worldList').innerHTML=worlds.length?worlds.map(card).join(''):'<div class="empty">The Meta map is ready for its first world.</div>';$('#worldMetric').textContent=worlds.length.toLocaleString();await paint();status('META UNIVERSE CONNECTED')}
function schedule(){clearTimeout(timer);timer=setTimeout(load,180)}
async function likeWorld(){if(!user||!selected)return status('TAP IN AND SELECT A WORLD','error');const {data}=await supabase.from('meta_world_likes').select('id').eq('world_id',selected.id).eq('user_id',user.id).maybeSingle();const result=data?await supabase.from('meta_world_likes').delete().eq('id',data.id):await supabase.from('meta_world_likes').insert({world_id:selected.id,user_id:user.id});if(result.error)return status(`WORLD LIKE FAILED • ${result.error.message}`,'error');status(data?'WORLD UNLIKED':'WORLD LIKED')}
function bind(){document.addEventListener('click',e=>{const n=e.target.closest('[data-world]');if(n){selected=worlds.find(w=>w.id===n.dataset.world)||null;paint()}});$('#likeWorld')?.addEventListener('click',likeWorld)}
async function boot(){if(!supabase)return status('SUPABASE ENV VARIABLES REQUIRED','error');await identity();bind();await load();channel=supabase.channel('rb-meta-owner').on('postgres_changes',{event:'*',schema:'public',table:'meta_worlds'},schedule).on('postgres_changes',{event:'*',schema:'public',table:'meta_portals'},schedule).subscribe();addEventListener('pagehide',()=>{disposed=true;clearTimeout(timer);if(channel)supabase.removeChannel(channel)},{once:true})}boot();