import { supabase } from './supabase-client.js';
const $=s=>document.querySelector(s),esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe=v=>{try{const u=new URL(String(v||''),location.origin);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}};
let worlds=[],selected=null,rooms=[],room=null,user=null,profile=null,avatar=null,filter='all',channels=[],timer=null,disposed=false,busy=false,lastReaction=0,visitId=null;
function status(m,t='ready'){const n=$('#metaStatus');if(n){n.textContent=m;n.dataset.tone=t}}
function authRoute(){location.href=`/auth.html?next=${encodeURIComponent(location.pathname+location.search)}`}
function clearChannels(){channels.forEach(c=>supabase.removeChannel(c));channels=[]}
function schedule(){clearTimeout(timer);timer=setTimeout(load,180)}
function worldCard(w){const img=safe(w.cover_url||w.background_url);return `<article class="card" data-selected="${selected?.id===w.id}">${img?`<img src="${esc(img)}" alt="" loading="lazy">`:'<span class="fallback">RB</span>'}<span><b>${esc(w.title||'Untitled world')}</b><small>${esc([w.world_type,w.access_type,w.status,`${Number(w.visit_count||0).toLocaleString()} visits`].filter(Boolean).join(' • '))}</small></span><button type="button" data-world="${esc(w.id)}">OPEN</button></article>`}
function roomCard(r){return `<article class="meta-room" data-active="${room?.id===r.id}"><div><b>${esc(r.title)}</b><small>${esc(r.room_type||'social')} • ${Number(r.active_members||0)}/${Number(r.max_members||50)}</small></div><button type="button" data-room="${esc(r.id)}">${room?.id===r.id?'OPEN':'JOIN'}</button></article>`}
async function identity(){const {data}=await supabase.auth.getUser();user=data?.user||null;if(!user)return;const p=await supabase.from('profiles').select('id,username,display_name').eq('id',user.id).maybeSingle();profile=p.data||null;const a=await supabase.from('meta_avatars').select('*').eq('user_id',user.id).maybeSingle();avatar=a.data||null;paintAvatar()}
function paintAvatar(){const n=$('#avatarState');if(!n)return;if(!user)n.innerHTML='<div class="empty">Sign in to connect an avatar.</div>';else if(!avatar)n.innerHTML='<div class="empty">No Meta avatar yet. Open Avatar to build one.</div>';else n.innerHTML=`<b>${esc(avatar.display_name||profile?.display_name||'Rich Avatar')}</b><small>${esc(avatar.rank||'Traveler')} • Level ${Number(avatar.level||1)} • ${esc(avatar.aura||'green-gold')}</small>`}
async function loadWorlds(){let q=supabase.from('meta_worlds').select('*').eq('status','active').order('is_featured',{ascending:false}).order('created_at',{ascending:false}).limit(60);if(filter!=='all')q=q.eq('world_type',filter);const {data,error}=await q;if(error)throw error;worlds=data||[];selected=selected?worlds.find(w=>w.id===selected.id)||worlds[0]||null:worlds[0]||null;$('#worldList').innerHTML=worlds.length?worlds.map(worldCard).join(''):'<div class="empty">No worlds match this lane.</div>';$('#worldMetric').textContent=worlds.length.toLocaleString()}
async function loadSelected(){if(!selected){$('#worldTitle').textContent='SELECT A WORLD';$('#worldDescription').textContent='Portals, rooms, avatars, streams, and creator worlds live here.';return}$('#worldTitle').textContent=selected.title||'Untitled world';$('#worldDescription').textContent=selected.description||'Rich Bizness creator world.';const bg=safe(selected.background_url||selected.cover_url);$('#metaStage').style.backgroundImage=bg?`linear-gradient(rgba(2,4,2,.42),rgba(2,4,2,.86)),url("${bg.replace(/"/g,'')}")`:'';await Promise.all([loadRooms(),loadPortals(),loadStreams(),refreshLike()])}
async function loadRooms(){if(!selected)return;const {data,error}=await supabase.from('meta_rooms').select('*').eq('world_id',selected.id).neq('status','closed').order('created_at',{ascending:false}).limit(30);if(error)throw error;rooms=data||[];room=room?rooms.find(r=>r.id===room.id)||null:null;$('#roomList').innerHTML=rooms.length?rooms.map(roomCard).join(''):'<div class="empty">No open rooms yet.</div>';await paintRoom()}
async function loadPortals(){const {data,error}=await supabase.from('meta_portals').select('*').eq('world_id',selected.id).eq('is_active',true).order('sort_order').limit(20);if(error)throw error;$('#portalList').innerHTML=(data||[]).map(p=>`<button class="portal" type="button" data-portal="${esc(p.id)}" data-url="${esc(p.destination_url||'')}" data-world-target="${esc(p.destination_world_id||'')}"><b>${esc(p.icon||'◎')} ${esc(p.title)}</b><small>${esc(p.portal_style||'portal')}</small></button>`).join('')||'<div class="empty">No active portals yet.</div>'}
async function loadStreams(){const {data,error}=await supabase.from('meta_stream_links').select('*').eq('world_id',selected.id).eq('status','active').order('created_at',{ascending:false}).limit(12);if(error)throw error;$('#streamList').innerHTML=(data||[]).map(s=>`<button class="meta-stream" type="button" data-stream="${esc(s.id)}"><b>${esc(s.title||'Meta Stream')}</b><small>OPEN STREAM</small></button>`).join('')||'<div class="empty">No active streams.</div>';$('#streamList').dataset.rows=JSON.stringify(data||[])}
async function refreshLike(){const b=$('#likeWorld');if(!b||!user||!selected){if(b)b.textContent='LIKE WORLD';return}const {data}=await supabase.from('meta_world_likes').select('id').eq('world_id',selected.id).eq('user_id',user.id).maybeSingle();b.textContent=data?'LIKED':'LIKE WORLD';b.dataset.liked=String(!!data)}
async function paintRoom(){const members=$('#roomMembers'),chat=$('#metaChat'),input=$('#metaChatInput'),leave=$('#leaveRoom');if(!room){members.innerHTML='<div class="empty">No room joined.</div>';chat.innerHTML='<div class="empty">Join a room to open chat.</div>';input.disabled=true;leave.hidden=true;return}const [m,c]=await Promise.all([supabase.from('meta_room_members').select('user_id,role,status,metadata').eq('room_id',room.id).eq('status','active').order('joined_at'),supabase.from('meta_chat_messages').select('*').eq('room_id',room.id).order('created_at').limit(100)]);members.innerHTML=(m.data||[]).map(x=>`<div class="meta-member"><b>${esc(x.metadata?.display_name||x.metadata?.username||'Meta Member')}</b><small>${esc(x.role||'member')}</small></div>`).join('')||'<div class="empty">Room is empty.</div>';chat.innerHTML=(c.data||[]).map(x=>`<div class="meta-message"><b>${esc(x.display_name||x.username||'Meta Member')}</b><span>${esc(x.body)}</span></div>`).join('')||'<div class="empty">Chat is ready.</div>';chat.scrollTop=chat.scrollHeight;input.disabled=!user;input.placeholder=user?'Talk in this room':'Sign in to chat';leave.hidden=!user;restartRealtime()}
async function loadInventory(){if(!user)return;const {data,error}=await supabase.from('meta_inventory').select('id,equipped,item_id,meta_items(title,item_type,rarity,image_url)').eq('user_id',user.id).order('unlocked_at',{ascending:false}).limit(24);if(error)return;$('#inventoryList').innerHTML=(data||[]).map(x=>`<div class="inventory-item"><b>${esc(x.meta_items?.title||'Meta Item')}</b><small>${esc(x.meta_items?.rarity||'common')} • ${x.equipped?'EQUIPPED':esc(x.meta_items?.item_type||'item')}</small></div>`).join('')||'<div class="empty">Inventory is ready for its first item.</div>'}
async function load(){if(disposed)return;status('SYNCING META UNIVERSE');try{await loadWorlds();await loadSelected();await loadInventory();status('META UNIVERSE CONNECTED')}catch(e){status(`META ERROR • ${e.message}`,'error')}}
async function enterWorld(){if(!user)return authRoute();if(!selected)return status('SELECT A WORLD','error');if(visitId)return;const {data,error}=await supabase.from('meta_visits').insert({world_id:selected.id,user_id:user.id,username:profile?.username||'member',display_name:profile?.display_name||'Rich Member',metadata:{source:'meta-owner'}}).select('id').single();if(error)return status(`ENTRY FAILED • ${error.message}`,'error');visitId=data.id;$('#enterWorld').hidden=true;$('#exitWorld').hidden=false;$('#worldPresence').textContent='WORLD ENTERED • PRESENCE ACTIVE';if(avatar)await supabase.from('meta_avatars').update({current_world_id:selected.id,is_active:true}).eq('user_id',user.id)}
async function exitWorld(){if(visitId)await supabase.from('meta_visits').update({exited_at:new Date().toISOString()}).eq('id',visitId);visitId=null;$('#enterWorld').hidden=false;$('#exitWorld').hidden=true;$('#worldPresence').textContent='WORLD NOT ENTERED';if(avatar&&user)await supabase.from('meta_avatars').update({current_world_id:null}).eq('user_id',user.id)}
async function joinRoom(id){if(!user)return authRoute();const next=rooms.find(r=>r.id===id);if(!next)return;room=next;const {error}=await supabase.from('meta_room_members').upsert({room_id:room.id,user_id:user.id,role:room.owner_id===user.id?'owner':'member',status:'active',left_at:null,metadata:{username:profile?.username,display_name:profile?.display_name}},{onConflict:'room_id,user_id'});if(error)return status(`ROOM JOIN FAILED • ${error.message}`,'error');await paintRoom();status(`JOINED • ${room.title}`)}
async function leaveRoom(){if(!user||!room)return;await supabase.from('meta_room_members').update({status:'left',left_at:new Date().toISOString()}).eq('room_id',room.id).eq('user_id',user.id);room=null;await paintRoom();status('LEFT META ROOM')}
async function createRoom(e){e.preventDefault();if(!user)return authRoute();if(!selected)return status('SELECT A WORLD','error');if(busy)return;busy=true;const payload={world_id:selected.id,owner_id:user.id,title:$('#roomTitle').value.trim(),room_type:$('#roomType').value,status:'open',max_members:Number($('#roomCapacity').value||20),active_members:0,metadata:{source:'meta-owner'}};const {data,error}=await supabase.from('meta_rooms').insert(payload).select('*').single();busy=false;if(error)return status(`ROOM FAILED • ${error.message}`,'error');e.currentTarget.reset();e.currentTarget.hidden=true;await loadRooms();await joinRoom(data.id)}
async function sendChat(e){e.preventDefault();if(!user)return authRoute();if(!room)return status('JOIN A ROOM FIRST','error');const body=$('#metaChatInput').value.trim();if(!body)return;const {error}=await supabase.from('meta_chat_messages').insert({room_id:room.id,world_id:selected?.id,user_id:user.id,username:profile?.username||'member',display_name:profile?.display_name||'Rich Member',body,message_type:'chat',metadata:{source:'meta-owner'}});if(error)return status(`CHAT FAILED • ${error.message}`,'error');e.currentTarget.reset()}
async function react(value){if(Date.now()-lastReaction<900)return;lastReaction=Date.now();if(!user)return authRoute();if(!room)return status('JOIN A ROOM FIRST','error');await supabase.from('meta_chat_messages').insert({room_id:room.id,world_id:selected?.id,user_id:user.id,username:profile?.username||'member',display_name:profile?.display_name||'Rich Member',body:value,message_type:'reaction',metadata:{source:'meta-owner'}})}
async function likeWorld(){if(!user)return authRoute();if(!selected)return;const {data}=await supabase.from('meta_world_likes').select('id').eq('world_id',selected.id).eq('user_id',user.id).maybeSingle();const r=data?await supabase.from('meta_world_likes').delete().eq('id',data.id):await supabase.from('meta_world_likes').insert({world_id:selected.id,user_id:user.id});if(r.error)return status(`WORLD LIKE FAILED • ${r.error.message}`,'error');refreshLike()}
function move(direction){if(!avatar||!user)return status('CONNECT AN AVATAR FIRST','error');const p=avatar.position||{x:0,y:0,z:0};const next={x:Number(p.x||0),y:Number(p.y||0),z:Number(p.z||0)};if(direction==='up')next.z-=1;if(direction==='down')next.z+=1;if(direction==='left')next.x-=1;if(direction==='right')next.x+=1;if(direction==='center'){next.x=0;next.y=0;next.z=0}avatar.position=next;$('#worldPresence').textContent=`POSITION • X ${next.x} Z ${next.z}`;clearTimeout(move.t);move.t=setTimeout(()=>supabase.from('meta_avatars').update({position:next}).eq('user_id',user.id),300)}
function restartRealtime(){clearChannels();const base=[['meta_worlds',null],['meta_rooms',selected?`world_id=eq.${selected.id}`:null],['meta_portals',selected?`world_id=eq.${selected.id}`:null]];if(room)base.push(['meta_room_members',`room_id=eq.${room.id}`],['meta_chat_messages',`room_id=eq.${room.id}`]);base.forEach(([table,filter],i)=>{const cfg={event:'*',schema:'public',table};if(filter)cfg.filter=filter;channels.push(supabase.channel(`rb-meta:${i}`).on('postgres_changes',cfg,room&&['meta_room_members','meta_chat_messages'].includes(table)?paintRoom:schedule).subscribe(s=>{$('#metaConnection').textContent=s==='SUBSCRIBED'?'REALTIME CONNECTED':s}))})}
function bind(){document.addEventListener('click',async e=>{const wf=e.target.closest('[data-world-filter]');if(wf){filter=wf.dataset.worldFilter;document.querySelectorAll('[data-world-filter]').forEach(n=>n.setAttribute('aria-pressed',String(n===wf)));selected=null;room=null;await load();return}const w=e.target.closest('[data-world]');if(w){selected=worlds.find(x=>x.id===w.dataset.world)||null;room=null;history.replaceState({},'',`/meta.html?world=${encodeURIComponent(selected?.id||'')}`);await loadSelected();restartRealtime();return}const r=e.target.closest('[data-room]');if(r)return joinRoom(r.dataset.room);const p=e.target.closest('[data-portal]');if(p){if(p.dataset.worldTarget){selected=worlds.find(x=>x.id===p.dataset.worldTarget)||selected;await loadSelected()}else if(p.dataset.url&&safe(p.dataset.url))location.href=p.dataset.url;return}const s=e.target.closest('[data-stream]');if(s){const rows=JSON.parse($('#streamList').dataset.rows||'[]');const found=rows.find(x=>x.id===s.dataset.stream);const url=safe(found?.metadata?.stream_url||found?.metadata?.url||'');$('#streamStage').innerHTML=url?`<iframe src="${esc(url)}" title="Meta stream" allow="autoplay; fullscreen" loading="lazy"></iframe>`:'<div class="empty">Stream source is not connected yet.</div>';return}const reaction=e.target.closest('[data-meta-reaction]');if(reaction)return react(reaction.dataset.metaReaction);const m=e.target.closest('[data-move]');if(m)return move(m.dataset.move)});$('#enterWorld')?.addEventListener('click',enterWorld);$('#exitWorld')?.addEventListener('click',exitWorld);$('#likeWorld')?.addEventListener('click',likeWorld);$('#leaveRoom')?.addEventListener('click',leaveRoom);$('#createRoomButton')?.addEventListener('click',()=>{$('#roomForm').hidden=!$('#roomForm').hidden});$('#roomForm')?.addEventListener('submit',createRoom);$('#metaChatForm')?.addEventListener('submit',sendChat);addEventListener('online',()=>{status('RECONNECTED • SYNCING');load();restartRealtime()});addEventListener('offline',()=>{status('OFFLINE • META PAUSED','error');$('#metaConnection').textContent='OFFLINE'});document.addEventListener('visibilitychange',()=>{if(!document.hidden){load();restartRealtime()}})}
async function boot(){if(!supabase)return status('SUPABASE ENV VARIABLES REQUIRED','error');await identity();bind();const requested=new URLSearchParams(location.search).get('world');await load();if(requested){selected=worlds.find(w=>w.id===requested)||selected;await loadSelected()}restartRealtime();addEventListener('pagehide',()=>{disposed=true;clearTimeout(timer);clearChannels();if(visitId)exitWorld()},{once:true})}boot();