import { supabase } from './supabase-client.js';
import { awardXp } from './rb-xp.js?v=no-floating-badge-1';
import { getAuthoritativeIdentity } from './rb-identity.js?v=identity-public-1';

const OWNED = ['meta_avatars','meta_worlds','meta_portals','meta_visits','meta_rooms','meta_room_members','meta_chat_messages','meta_world_likes','meta_items','meta_inventory','meta_stream_links'];
const primary = 'meta_worlds';
const $ = (s) => document.querySelector(s);
const fmt = (n) => Number(n || 0).toLocaleString();
let worlds = [], counts = {}, active = null, user = null;
function addCss(){ if(document.getElementById('metaOwnerCss')) return; const l=document.createElement('link'); l.id='metaOwnerCss'; l.rel='stylesheet'; l.href='/src/meta-owner.css?v=meta-owner-1'; document.head.appendChild(l); }
function name(row){ return row.title || row.name || row.world_name || row.display_name || 'Rich Meta World'; }
function note(row){ return row.description || row.bio || row.status || row.world_type || row.created_at || 'Meta world connected to rooms, portals, inventory, chat, and stream links.'; }
function img(row){ return row.cover_url || row.thumbnail_url || row.image_url || row.avatar_url || row.banner_url || row.metadata?.cover_url || ''; }
async function getUser(){ const state = await getAuthoritativeIdentity(); user = state.user || null; return user; }
async function countTable(table){ try { const { count } = await supabase.from(table).select('*', { count:'exact', head:true }); return count || 0; } catch(_) { return 0; } }
async function loadCounts(){ const pairs = await Promise.all(OWNED.map(async t => [t, await countTable(t)])); counts = Object.fromEntries(pairs); renderSystems(); const c = $('#metaRecordCount') || $('#recordCount'); if(c) c.textContent = fmt(worlds.length || counts[primary] || 0); const o = $('#metaTableCount'); if(o) o.textContent = String(OWNED.length); }
async function loadWorlds(){ let q = supabase.from(primary).select('*').limit(48); try{ q = q.order('created_at', { ascending:false }); }catch(_){} const { data } = await q; worlds = data || []; active = worlds[0] || null; render(); await loadCounts(); }
function mount(){ if($('#metaOwner')) return; const main = document.querySelector('main') || document.body; const panel = document.createElement('section'); panel.id = 'metaOwner'; panel.className = 'meta-owner'; panel.innerHTML = `<div class="meta-head"><div><small>META OWNER</small><b>META WORLD</b><p>Avatars, worlds, rooms, portals, inventory, chat, stream links, visits, and private-world energy.</p></div><small id="metaStatus">READY</small></div><div class="meta-actions"><a href="/avatar.html">BUILD AVATAR</a><a href="/avatar-characters/">CHARACTERS</a><a href="/gaming.html">GAMING</a><a href="/watch.html">WATCH</a><a href="/rb-secret-door.html?room=private-worlds">PRIVATE WORLDS</a><button id="metaRefresh" type="button">REFRESH</button></div><div class="meta-systems" id="metaSystems"></div><div class="meta-feature"><div class="meta-spot" id="metaSpot">◇</div><div><small>ACTIVE WORLD</small><b id="metaTitle">META WORLD</b><p id="metaNote">Pick a world to enter.</p><div class="meta-actions slim"><button id="enterWorld" type="button">ENTER WORLD</button><button id="likeWorld" type="button">LIKE WORLD</button><button id="openRoom" type="button">OPEN ROOM</button></div></div></div><div class="meta-list" id="metaList"></div>`; main.appendChild(panel); $('#metaRefresh')?.addEventListener('click', refresh); $('#enterWorld')?.addEventListener('click', enterWorld); $('#likeWorld')?.addEventListener('click', likeWorld); $('#openRoom')?.addEventListener('click', openRoom); }
function renderSystems(){ const box = $('#metaSystems') || $('#schemaPanel'); if(!box) return; box.innerHTML = OWNED.map(t => `<article class="meta-system"><b>${t.replaceAll('_',' ').toUpperCase()}</b><small>${fmt(counts[t])} records</small></article>`).join(''); }
function render(){ const list = $('#metaList') || $('#sectionCards'); if(list) list.innerHTML = worlds.length ? worlds.map((w,i)=>`<article class="meta-card ${active?.id===w.id?'active':''}" data-meta-i="${i}">${img(w)?`<img src="${img(w)}" alt="">`:'<div class="meta-mini">◇</div>'}<div><b>${name(w)}</b><p>${note(w)}</p><small>META WORLD • ROOM READY</small></div></article>`).join('') : '<article class="meta-card"><b>No worlds yet</b><p>Meta is ready for worlds, rooms, portals, inventory, and private-world links.</p></article>'; document.querySelectorAll('[data-meta-i]').forEach(el => el.addEventListener('click',()=>select(Number(el.dataset.metaI)))); if(active) select(worlds.indexOf(active)); }
function select(i){ active = worlds[i] || worlds[0] || null; if(!active) return; const media = img(active); if($('#metaTitle')) $('#metaTitle').textContent = name(active); if($('#metaNote')) $('#metaNote').textContent = note(active); if($('#metaSpot')) $('#metaSpot').innerHTML = media ? `<img src="${media}" alt="">` : '◇'; document.querySelectorAll('[data-meta-i]').forEach(el => el.classList.toggle('active', Number(el.dataset.metaI) === i)); }
async function enterWorld(){ await getUser(); if(!user){ location.href='/auth.html'; return; } const worldId = active?.id || null; if(worldId) await supabase.from('meta_visits').insert({ world_id: worldId, user_id: user.id, metadata:{ source:'meta-owner' } }).then(()=>{},()=>{}); await awardXp('meta_enter', { section:'meta', sourceTable:'meta_worlds', sourceId:worldId }).catch(()=>{}); if($('#metaStatus')) $('#metaStatus').textContent = 'WORLD ENTERED'; loadCounts(); }
async function likeWorld(){ await getUser(); if(!user || !active){ if(!user) location.href='/auth.html'; return; } await supabase.from('meta_world_likes').insert({ world_id: active.id, user_id: user.id, metadata:{ source:'meta-owner' } }).then(()=>{},()=>{}); await awardXp('meta_like', { section:'meta', sourceTable:'meta_worlds', sourceId:active.id }).catch(()=>{}); if($('#metaStatus')) $('#metaStatus').textContent = 'WORLD LIKED'; loadCounts(); }
async function openRoom(){ await getUser(); if(!user){ location.href='/auth.html'; return; } if(!active){ if($('#metaStatus')) $('#metaStatus').textContent='NO WORLD YET'; return; } await supabase.from('meta_rooms').insert({ world_id: active.id, created_by: user.id, title: name(active) + ' Room', status:'open', metadata:{ source:'meta-owner' } }).then(()=>{},()=>{}); if($('#metaStatus')) $('#metaStatus').textContent = 'ROOM OPENED'; loadCounts(); }
async function refresh(){ await loadWorlds(); await loadCounts(); }
addCss(); mount(); refresh(); supabase.channel('meta-owner-ui').on('postgres_changes',{event:'*',schema:'public',table:primary},refresh).subscribe();