import { supabase } from './supabase-client.js';
import { ensureProfile, getMetaAvatar, getSessionUser } from './rb-identity.js?v=profile-avatar-separate-1';
import { bootXp, loadXp } from './rb-xp.js?v=realtime-1';

const $ = (s) => document.querySelector(s);
const fmt = (n) => Number(n || 0).toLocaleString();
const money = (n) => '$' + (Number(n || 0) / 100).toFixed(2);
const safe = (v, fallback = '') => String(v ?? fallback);
const set = (s, v) => { const el = $(s); if (el) el.textContent = v; };
const params = new URLSearchParams(location.search);
const requestedId = params.get('id') || params.get('user_id') || '';
const requestedUsername = params.get('u') || params.get('user') || params.get('username') || '';
let ownerUser = null;
let viewedProfile = null;
let isOwner = false;
function say(text) { set('#profileStatus', text); }
function calmProfileArtifacts() { document.querySelectorAll('.rb-overlay:not([data-rb-keep]),.rb-blocker:not([data-rb-keep])').forEach((el) => { el.style.pointerEvents = 'none'; el.setAttribute('aria-hidden', 'true'); }); document.body?.removeAttribute('data-rich-money'); }
function miniCard(row, type = 'post') { const img = row.media_url || row.public_url || row.thumbnail_url || row.cover_url || row.file_url || ''; return `<article class="card">${img ? `<img src="${img}" alt="">` : ''}<b>${safe(row.title, type === 'post' ? 'Rich Bizness Post' : 'Upload')}</b><p>${safe(row.body || row.description, 'Profile-owned content.')}</p><small>${safe(row.section || row.category || type, type)}</small></article>`; }
async function getProfileTarget(currentUser) { if (requestedId) { const { data, error } = await supabase.from('profiles').select('*').eq('id', requestedId).maybeSingle(); if (error) throw error; return data || null; } if (requestedUsername) { const clean = requestedUsername.replace(/^@/, '').trim(); const { data, error } = await supabase.from('profiles').select('*').eq('username', clean).maybeSingle(); if (error) throw error; return data || null; } return await ensureProfile(currentUser); }
async function counts(userId) { const [posts, uploads, followers, following] = await Promise.all([supabase.from('feed_posts').select('id', { count: 'exact', head: true }).eq('user_id', userId), supabase.from('uploads').select('id', { count: 'exact', head: true }).eq('user_id', userId), supabase.from('followers').select('id', { count: 'exact', head: true }).eq('following_id', userId), supabase.from('followers').select('id', { count: 'exact', head: true }).eq('follower_id', userId)]); set('#postsCount', fmt(posts.count)); set('#uploadsCount', fmt(uploads.count)); set('#followersCount', fmt(followers.count)); return { posts: posts.count || 0, uploads: uploads.count || 0, followers: followers.count || 0, following: following.count || 0 }; }
async function loadOwnedContent(userId) { const [posts, uploads] = await Promise.all([supabase.from('feed_posts').select('*').eq('user_id', userId).order('created_at', { ascending: false }).limit(8), supabase.from('uploads').select('*').eq('user_id', userId).order('created_at', { ascending: false }).limit(8)]); const postBox = $('#profilePosts'), uploadBox = $('#profileUploads'); if (postBox) postBox.innerHTML = posts.error ? `<div class="empty">${posts.error.message}</div>` : (posts.data || []).length ? posts.data.map((r) => miniCard(r, 'post')).join('') : '<div class="empty">No posts yet.</div>'; if (uploadBox) uploadBox.innerHTML = uploads.error ? `<div class="empty">${uploads.error.message}</div>` : (uploads.data || []).length ? uploads.data.map((r) => miniCard(r, 'upload')).join('') : '<div class="empty">No uploads yet.</div>'; }
async function access(profile, userId) { const [admin, creator, secret] = await Promise.all([supabase.from('admin_roles').select('role_key,can_manage_money,can_manage_platform').eq('user_id', userId).eq('is_active', true).maybeSingle(), supabase.from('creator_available_balances').select('available_cents,earned_cents,pending_cents').eq('artist_user_id', userId).maybeSingle(), supabase.from('rb_secret_rooms').select('room_key,required_role,entry_cost_cents').eq('is_active', true).limit(8)]); const creatorText = profile.is_creator || profile.is_artist || profile.is_seller || creator.data ? money(creator.data?.available_cents || 0) : 'Creator locked'; const secretText = profile.vault_unlocked ? `${profile.rb_secret_rank || 'VAULT'} • ${(secret.data || []).length} rooms` : `${Math.max(0, 500 - Number(profile.rich_points || 0))} XP to unlock`; set('#creatorAccess', isOwner ? creatorText : (profile.is_creator || profile.is_artist || profile.is_seller ? 'Creator profile' : 'Public profile')); set('#secretAccess', isOwner ? secretText : (profile.vault_unlocked ? profile.rb_secret_rank || 'VAULT' : 'Public view')); return { admin: admin.data, creator: creator.data, secret: secret.data }; }
function tuneOwnerControls() { document.querySelectorAll('a[href="/edit.html"],a[href="/settings.html"]').forEach((el) => { if (!isOwner) { el.textContent = el.getAttribute('href') === '/edit.html' ? 'FOLLOW' : 'MESSAGE'; el.href = el.textContent === 'FOLLOW' ? '#' : `/messages.html?user=${encodeURIComponent(viewedProfile?.id || '')}`; el.dataset.profileAction = el.textContent.toLowerCase(); } }); const creatorBtn = document.querySelector('a[href="/creator.html"]'); if (creatorBtn && !isOwner) { creatorBtn.textContent = 'View Feed'; creatorBtn.href = `/feed.html?user=${encodeURIComponent(viewedProfile?.id || '')}`; } }
function render(profile, meta) { calmProfileArtifacts(); viewedProfile = profile; isOwner = !!ownerUser?.id && ownerUser.id === profile.id; const cfg = meta?.metadata || {}; const lvl = Number(profile.rich_level || meta?.level || 1); const points = Number(profile.rich_points || meta?.xp || 0); set('#displayName', safe(profile.display_name, 'Rich Bizness User').toUpperCase()); set('#username', '@' + safe(profile.username, 'rich_user')); set('#bio', safe(profile.bio, 'Building a Rich Bizness lane across the universe.')); set('#rank', safe(profile.rank_title, 'BIZ LEGEND')); set('#level', lvl); set('#xp', fmt(points)); set('#balance', isOwner ? money(profile.balance_cents) : 'PUBLIC'); if ($('#xpFill')) $('#xpFill').style.width = Math.max(0, Math.min(100, (points % 1000) / 10)) + '%'; const card = $('#profileCard'); if (card) card.style.backgroundImage = profile.banner_url ? `url(${profile.banner_url})` : ''; const avatarFace = $('#avatarFace'); if (avatarFace) { avatarFace.classList.add('live-avatar'); avatarFace.dataset.aura = meta?.aura || cfg.aura || 'Emerald Gold'; avatarFace.dataset.motion = cfg.motion || 'Boss Idle'; avatarFace.title = `${isOwner ? 'Your profile' : 'Viewing public profile'} • profile photo separate from avatar character`; if (profile.avatar_url) { avatarFace.textContent = ''; avatarFace.style.backgroundImage = 'url(' + profile.avatar_url + ')'; } else { avatarFace.textContent = safe(profile.display_name || profile.username || 'RB').split(/\s+/).map(x=>x[0]).filter(Boolean).slice(0,2).join('').toUpperCase() || 'RB'; avatarFace.style.backgroundImage = ''; } } tuneOwnerControls(); }
async function paint(currentUser) { calmProfileArtifacts(); ownerUser = currentUser; const profile = await getProfileTarget(currentUser); if (!profile) { say('Profile not found.'); return; } const meta = await getMetaAvatar(profile.id).catch(() => null); render(profile, meta); await Promise.all([counts(profile.id), loadOwnedContent(profile.id), access(profile, profile.id)]); if (isOwner) { try { await loadXp(profile.id); } catch (_) {} } say(isOwner ? 'Profile empire connected.' : 'Viewing public profile.'); }
async function boot() { try { calmProfileArtifacts(); const user = await getSessionUser(); if (!user) { location.href = '/auth.html?next=' + encodeURIComponent(location.pathname + location.search); return; } try { await bootXp(); } catch (_) {} await paint(user); const targetId = viewedProfile?.id || user.id; supabase.channel('profile-view-' + targetId).on('postgres_changes', { event: '*', schema: 'public', table: 'profiles', filter: 'id=eq.' + targetId }, () => paint(user)).on('postgres_changes', { event: '*', schema: 'public', table: 'meta_avatars', filter: 'user_id=eq.' + targetId }, () => paint(user)).on('postgres_changes', { event: '*', schema: 'public', table: 'feed_posts', filter: 'user_id=eq.' + targetId }, () => paint(user)).on('postgres_changes', { event: '*', schema: 'public', table: 'uploads', filter: 'user_id=eq.' + targetId }, () => paint(user)).on('postgres_changes', { event: '*', schema: 'public', table: 'user_levels', filter: 'user_id=eq.' + targetId }, () => paint(user)).subscribe(); } catch (error) { console.warn(error); say(error.message || String(error)); } }
boot();