import { supabase } from './supabase-client.js';
const $=s=>document.querySelector(s),esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const safe=v=>{try{const u=new URL(String(v||''),location.origin);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}};
let lane='all',posts=[],selected=null,user=null,profile=null,disposed=false,channel=null,timer=null,busy=false;
function status(m,t='ready'){const n=$('#sportsStatus');if(n){n.textContent=m;n.dataset.tone=t}}
function card(p){const media=safe(p.cover_url||p.thumbnail_url||p.media_url);return `<article class="card" data-id="${esc(p.id)}">${media?`<img src="${esc(media)}" alt="" loading="lazy">`:'<span class="fallback">RB</span>'}<span><b>${esc(p.title||'Untitled highlight')}</b><small>${esc([p.sport,p.team_name,p.display_name||p.username].filter(Boolean).join(' • '))}</small></span><button type="button" data-select="${esc(p.id)}">OPEN</button></article>`}
async function identity(){const {data}=await supabase.auth.getUser();user=data?.user||null;if(user){const {data:p}=await supabase.from('profiles').select('id,username,display_name').eq('id',user.id).maybeSingle();profile=p||null}}
async function load(){if(disposed)return;status('SYNCING RICH ARENA');let q=supabase.from('sports_posts').select('*').order('created_at',{ascending:false}).limit(60);if(lane!=='all')q=q.eq('sport',lane);const {data,error}=await q;if(error)return status(`SPORTS ERROR • ${error.message}`,'error');posts=data||[];selected=selected?posts.find(p=>p.id===selected.id)||posts[0]||null:posts[0]||null;$('#sportsFeed').innerHTML=posts.length?posts.map(card).join(''):'<div class="empty">The arena is ready for its first drop.</div>';$('#sportsMetric').textContent=posts.length.toLocaleString();await loadComments();status('RICH ARENA CONNECTED')}
async function loadComments(){if(!selected)return $('#sportsComments').innerHTML='';const {data}=await supabase.from('sports_comments').select('display_name,username,body,created_at').eq('post_id',selected.id).order('created_at',{ascending:false}).limit(20);$('#sportsComments').innerHTML=(data||[]).map(r=>`<div class="comment"><b>${esc(r.display_name||r.username||'Member')}</b><div>${esc(r.body)}</div></div>`).join('')}
function schedule(){clearTimeout(timer);timer=setTimeout(load,180)}
function realtime(){channel=supabase.channel('rb-sports-owner').on('postgres_changes',{event:'*',schema:'public',table:'sports_posts'},schedule).on('postgres_changes',{event:'*',schema:'public',table:'sports_comments'},schedule).subscribe()}
async function createPost(e){e.preventDefault();if(busy)return;if(!user)return status('TAP IN TO DROP SPORTS CONTENT','error');const title=$('#sportsTitle').value.trim(),sport=$('#sportsLane').value,body=$('#sportsBody').value.trim();if(!title)return;busy=true;const {error}=await supabase.from('sports_posts').insert({user_id:user.id,username:profile?.username||'member',display_name:profile?.display_name||'Rich Bizness Member',title,body,sport,media_type:'text',is_featured:false,metadata:{source:'sports-owner'}});busy=false;if(error)return status(`DROP FAILED • ${error.message}`,'error');e.currentTarget.reset();status('SPORTS DROP LIVE');load()}
async function comment(e){e.preventDefault();if(!user||!selected)return status('TAP IN AND OPEN A SPORTS POST','error');const body=$('#sportsComment').value.trim();if(!body)return;const {error}=await supabase.from('sports_comments').insert({post_id:selected.id,user_id:user.id,username:profile?.username||'member',display_name:profile?.display_name||'Rich Bizness Member',body});if(error)return status(`COMMENT FAILED • ${error.message}`,'error');e.currentTarget.reset();loadComments()}
function bind(){document.addEventListener('click',e=>{const tab=e.target.closest('[data-lane]');if(tab){lane=tab.dataset.lane;document.querySelectorAll('[data-lane]').forEach(n=>n.setAttribute('aria-pressed',String(n===tab)));load()}const pick=e.target.closest('[data-select]');if(pick){selected=posts.find(p=>p.id===pick.dataset.select)||null;loadComments()}});$('#sportsForm')?.addEventListener('submit',createPost);$('#sportsCommentForm')?.addEventListener('submit',comment)}
async function boot(){if(!supabase)return status('SUPABASE ENV VARIABLES REQUIRED','error');await identity();bind();await load();realtime();addEventListener('pagehide',()=>{disposed=true;clearTimeout(timer);if(channel)supabase.removeChannel(channel)},{once:true})}boot();