import { supabase } from './supabase-client.js';

const $=(s)=>document.querySelector(s);
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe=v=>{try{const u=new URL(String(v||''),location.origin);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}};
let lane='all',posts=[],selected=null,user=null,profile=null,disposed=false,busy=false,channels=[],timer=null,online=navigator.onLine;

function status(m,t='ready'){const n=$('#sportsStatus');if(n){n.textContent=m;n.dataset.tone=t}}
function connection(){const n=$('#sportsConnection');if(n)n.textContent=online?'REALTIME READY':'OFFLINE'}
function authRoute(){location.href=`/auth.html?next=${encodeURIComponent(location.pathname+location.search)}`}
function mediaMarkup(row){const url=safe(row.media_url||row.cover_url||row.thumbnail_url);if(!url)return '<span class="fallback">RB</span>';return row.media_type==='video'?`<video src="${esc(url)}" controls playsinline preload="metadata"></video>`:`<img src="${esc(url)}" alt="" loading="lazy" decoding="async">`}
function card(p){return `<article class="card sports-card" data-id="${esc(p.id)}" aria-current="${selected?.id===p.id}">${mediaMarkup(p)}<span><b>${esc(p.title||'Untitled highlight')}</b><small>${esc([p.sport,p.league,p.team_name,p.display_name||p.username].filter(Boolean).join(' • '))}</small><small>${Number(p.reaction_count||0).toLocaleString()} reactions • ${Number(p.comment_count||0).toLocaleString()} comments</small></span><button type="button" data-select="${esc(p.id)}">OPEN</button></article>`}
function broadcastCard(r){const state=String(r.status||'scheduled').toUpperCase();const url=safe(r.status==='ended'?r.replay_url:r.stream_url);return `<article class="broadcast" data-broadcast="${esc(r.id)}"><div><b>${esc(r.title||'Sports Broadcast')}</b><small>${esc([r.sport,r.league,r.team_name].filter(Boolean).join(' • '))}</small></div><span class="chip">${esc(state)}</span>${url?`<button type="button" data-play-broadcast="${esc(r.id)}">${r.status==='ended'?'REPLAY':'WATCH'}</button>`:''}<div class="broadcast-player" id="broadcast-${esc(r.id)}"></div></article>`}
function bracketCard(r){const data=r.bracket_data&&typeof r.bracket_data==='object'?JSON.stringify(r.bracket_data):'{}';return `<article class="bracket"><b>${esc(r.title||'Bracket')}</b><small>${esc([r.sport,r.league,r.status].filter(Boolean).join(' • '))}</small><code>${esc(data.slice(0,140))}</code></article>`}
function pickCard(r){return `<article class="pick"><b>${esc(r.title)}</b><small>${esc([r.team_name,r.opponent,r.prediction].filter(Boolean).join(' • '))}</small><span>${Number(r.confidence||0)}% confidence • ${esc(r.result||r.status||'pending')}</span></article>`}
function commentCard(r){return `<div class="comment"><b>${esc(r.display_name||r.username||'Member')}</b><div>${esc(r.body)}</div></div>`}

async function identity(){const {data}=await supabase.auth.getUser();user=data?.user||null;if(user){const {data:p}=await supabase.from('profiles').select('id,username,display_name').eq('id',user.id).maybeSingle();profile=p||null}}
async function loadPosts(){let q=supabase.from('sports_posts').select('*').order('is_featured',{ascending:false}).order('created_at',{ascending:false}).limit(60);if(lane!=='all')q=q.eq('sport',lane);const {data,error}=await q;if(error)throw error;posts=data||[];selected=selected?posts.find(p=>p.id===selected.id)||posts[0]||null:posts[0]||null;$('#sportsFeed').innerHTML=posts.length?posts.map(card).join(''):'<div class="empty">The arena is ready for its first drop.</div>';$('#sportsMetric').textContent=posts.length.toLocaleString();await loadComments()}
async function loadComments(){if(!selected){$('#sportsComments').innerHTML='<div class="empty">Open a post to load comments.</div>';return}const {data,error}=await supabase.from('sports_comments').select('display_name,username,body,created_at').eq('post_id',selected.id).order('created_at',{ascending:false}).limit(30);if(error)throw error;$('#sportsComments').innerHTML=(data||[]).map(commentCard).join('')||'<div class="empty">No comments yet.</div>'}
async function loadBroadcasts(){const {data,error}=await supabase.from('sports_broadcasts').select('*').order('scheduled_for',{ascending:true}).order('created_at',{ascending:false}).limit(12);if(error)throw error;$('#sportsBroadcasts').innerHTML=(data||[]).map(broadcastCard).join('')||'<div class="empty">No broadcasts scheduled.</div>'}
async function loadBrackets(){const {data,error}=await supabase.from('sports_brackets').select('*').order('created_at',{ascending:false}).limit(8);if(error)throw error;$('#sportsBrackets').innerHTML=(data||[]).map(bracketCard).join('')||'<div class="empty">No active brackets.</div>'}
async function loadPicks(){let q=supabase.from('sports_picks').select('*').order('created_at',{ascending:false}).limit(20);if(user)q=q.eq('user_id',user.id);const {data,error}=await q;if(error)throw error;$('#sportsPicks').innerHTML=(data||[]).map(pickCard).join('')||'<div class="empty">No picks locked yet.</div>'}
async function load(){if(disposed)return;status('SYNCING RICH ARENA');try{await Promise.all([loadPosts(),loadBroadcasts(),loadBrackets(),loadPicks()]);status('RICH ARENA CONNECTED')}catch(e){status(`SPORTS ERROR • ${e.message}`,'error')}}
function schedule(){clearTimeout(timer);timer=setTimeout(load,180)}
function realtime(){channels.forEach(c=>supabase.removeChannel(c));channels=[];['sports_posts','sports_comments','sports_reactions','sports_picks','sports_brackets','sports_broadcasts','sports_alert_subscriptions'].forEach((table,i)=>channels.push(supabase.channel(`rb-sports:${i}`).on('postgres_changes',{event:'*',schema:'public',table},schedule).subscribe()))}

async function createPost(e){e.preventDefault();if(busy)return;if(!user){status('TAP IN TO DROP SPORTS CONTENT','error');return authRoute()}const title=$('#sportsTitle').value.trim(),sport=$('#sportsLane').value,body=$('#sportsBody').value.trim();if(!title)return;busy=true;const {error}=await supabase.from('sports_posts').insert({user_id:user.id,username:profile?.username||'member',display_name:profile?.display_name||'Rich Bizness Member',title,body,sport,league:$('#sportsLeague').value.trim()||null,team_name:$('#sportsTeam').value.trim()||null,media_type:'text',is_featured:false,metadata:{source:'sports-owner'}});busy=false;if(error)return status(`DROP FAILED • ${error.message}`,'error');e.currentTarget.reset();status('SPORTS DROP LIVE');load()}
async function comment(e){e.preventDefault();if(!user||!selected){status('TAP IN AND OPEN A SPORTS POST','error');if(!user)authRoute();return}const body=$('#sportsComment').value.trim();if(!body)return;const {error}=await supabase.from('sports_comments').insert({post_id:selected.id,user_id:user.id,username:profile?.username||'member',display_name:profile?.display_name||'Rich Bizness Member',body});if(error)return status(`COMMENT FAILED • ${error.message}`,'error');e.currentTarget.reset();loadComments();status('COMMENT POSTED')}
async function react(value){if(!user||!selected){status('TAP IN AND OPEN A SPORTS POST','error');if(!user)authRoute();return}const {error}=await supabase.from('sports_reactions').upsert({post_id:selected.id,user_id:user.id,reaction:value},{onConflict:'post_id,user_id'});if(error)return status(`REACTION FAILED • ${error.message}`,'error');status('REACTION LOCKED')}
async function createPick(e){e.preventDefault();if(!user){status('TAP IN TO LOCK A PICK','error');return authRoute()}const title=$('#pickTitle').value.trim(),prediction=$('#pickPrediction').value.trim();if(!title||!prediction)return;const {error}=await supabase.from('sports_picks').insert({user_id:user.id,username:profile?.username||'member',display_name:profile?.display_name||'Rich Bizness Member',title,sport:lane==='all'?'general':lane,team_name:$('#pickTeam').value.trim()||null,opponent:$('#pickOpponent').value.trim()||null,prediction,confidence:Number($('#pickConfidence').value||50),status:'open',result:'pending',pick_type:'standard',is_premium:false,is_featured:false,metadata:{source:'sports-owner'}});if(error)return status(`PICK FAILED • ${error.message}`,'error');e.currentTarget.reset();$('#pickConfidence').value='50';status('PICK LOCKED');loadPicks()}
async function followTeam(e){e.preventDefault();if(!user){status('TAP IN TO FOLLOW A TEAM','error');return authRoute()}const team=$('#followTeam').value.trim(),league=$('#followLeague').value.trim();if(!team)return;const {error}=await supabase.from('sports_alert_subscriptions').upsert({user_id:user.id,sport:lane==='all'?null:lane,league:league||null,team_name:team,alert_level:'all',is_active:true},{onConflict:'user_id,team_name'});if(error)return status(`FOLLOW FAILED • ${error.message}`,'error');$('#teamFollowState').textContent=`FOLLOWING ${team.toUpperCase()}`;status('TEAM ALERTS ON')}
async function playBroadcast(id){const {data,error}=await supabase.from('sports_broadcasts').select('*').eq('id',id).maybeSingle();if(error)return status(`BROADCAST FAILED • ${error.message}`,'error');const url=safe(data?.status==='ended'?data?.replay_url:data?.stream_url);const host=$(`#broadcast-${CSS.escape(id)}`);if(!url||!host)return status('BROADCAST MEDIA NOT CONNECTED','error');host.innerHTML=`<video src="${esc(url)}" controls playsinline preload="metadata"></video>`;host.querySelector('video')?.play().catch(()=>{});status(data.status==='ended'?'REPLAY READY':'LIVE BROADCAST READY')}

function bind(){document.addEventListener('click',e=>{const tab=e.target.closest('[data-lane]');if(tab){lane=tab.dataset.lane;document.querySelectorAll('[data-lane]').forEach(n=>n.setAttribute('aria-pressed',String(n===tab)));load()}const pick=e.target.closest('[data-select]');if(pick){selected=posts.find(p=>p.id===pick.dataset.select)||null;document.querySelectorAll('.sports-card').forEach(n=>n.setAttribute('aria-current',String(n.dataset.id===selected?.id)));loadComments()}const reaction=e.target.closest('[data-sports-reaction]');if(reaction)react(reaction.dataset.sportsReaction);const watch=e.target.closest('[data-play-broadcast]');if(watch)playBroadcast(watch.dataset.playBroadcast)});$('#sportsForm')?.addEventListener('submit',createPost);$('#sportsCommentForm')?.addEventListener('submit',comment);$('#sportsPickForm')?.addEventListener('submit',createPick);$('#teamFollowForm')?.addEventListener('submit',followTeam);addEventListener('online',()=>{online=true;connection();load()});addEventListener('offline',()=>{online=false;connection();status('OFFLINE • SPORTS PAUSED','error')});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&online)load()})}
function cleanup(){disposed=true;clearTimeout(timer);channels.forEach(c=>supabase.removeChannel(c));channels=[]}
async function boot(){if(!supabase)return status('SUPABASE ENV VARIABLES REQUIRED','error');try{connection();await identity();bind();await load();realtime();addEventListener('pagehide',cleanup,{once:true})}catch(e){status(`SPORTS FAILED • ${e.message}`,'error')}}
boot();