import { supabase } from './supabase-client.js';
import { getSessionUser } from './rb-identity.js?v=identity-owner-2';
import { addToCart, likeProduct, viewProduct, listCart, updateCartQuantity, removeCartItem, listProductCounts, listProductComments, commentProduct, createOrder, listOrders, listSellerNotifications, markStoreNotificationRead } from '../features/store/actions.js?v=store-phase-2';

const $=s=>document.querySelector(s);
const money=n=>'$'+(Number(n||0)/100).toFixed(2);
const img=r=>r?.image_url||r?.cover_url||r?.media_url||r?.preview_url||'';
const safe=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let products=[],counts={},cart=[],orders=[],activeProduct=null,channel=null,userChannel=null,timer=null,loading=false;
const say=t=>{if($('#storeStatus'))$('#storeStatus').textContent=t};

function card(r){const u=img(r),c=counts[r.id]||{likes:0,comments:0,views:Number(r.views||0)};return `<article class="card market-card" data-product="${safe(r.id)}">${u?`<img src="${safe(u)}" alt="${safe(r.title||'Product')}">`:''}<b>${safe(r.title||'Store Product')}</b><p>${safe(r.description||'Rich Bizness product.')}</p><small>${money(r.price_cents)} • ${safe(r.product_type||'product')} • ${safe(r.status||'active')}</small><div class="product-counts"><span>♥ ${c.likes}</span><span>💬 ${c.comments}</span><span>👁 ${c.views}</span></div><div class="store-actions"><button data-store-action="like">LIKE</button><button data-store-action="cart">CART</button><button class="primary" data-store-action="buy">ORDER</button><button data-store-action="comment">COMMENTS</button></div></article>`}

async function seller(){const user=await getSessionUser().catch(()=>null);if(!user){$('#sellerStrip').innerHTML='<span><b>GUEST</b><small>Tap in to sell</small></span>';return}const {data}=await supabase.from('store_seller_profiles').select('*').eq('user_id',user.id).maybeSingle();$('#sellerStrip').innerHTML=`<span><b>${safe(data?.seller_name||data?.display_name||'Seller')}</b><small>Seller</small></span><span><b>${money(data?.available_balance_cents)}</b><small>Available</small></span><span><b>${money(data?.pending_balance_cents)}</b><small>Pending</small></span><span><b>${money(data?.total_sales_cents)}</b><small>Total Sales</small></span>`}
async function loadProducts(){if(loading)return;loading=true;try{const {data,error}=await supabase.from('products').select('*').or('is_public.is.true,is_public.is.null').order('is_featured',{ascending:false}).order('created_at',{ascending:false}).limit(36);products=data||[];counts=await listProductCounts(products.map(p=>p.id)).catch(()=>({}));$('#recordCount').textContent=products.length.toLocaleString();$('#sectionCards').innerHTML=error?`<div class="empty">${safe(error.message)}</div>`:products.length?products.map(card).join(''):'<div class="empty">No products yet.</div>';say('Store ready.')}finally{loading=false}}
const scheduleProducts=()=>{clearTimeout(timer);timer=setTimeout(loadProducts,180)};
async function refreshCart(){cart=await listCart().catch(()=>[]);$('#cartCount').textContent=cart.reduce((n,i)=>n+Number(i.quantity||1),0).toLocaleString();$('#cartList').innerHTML=cart.length?cart.map(i=>`<article class="store-row" data-cart-id="${safe(i.id)}"><span><b>${safe(i.product?.title||'Product')}</b><small>${money(i.price_cents)} × ${i.quantity}</small></span><div><button data-cart-action="minus">−</button><button data-cart-action="plus">+</button><button data-cart-action="remove">REMOVE</button></div></article>`).join(''):'<div class="empty">Your cart is empty.</div>';$('#cartTotal').textContent=money(cart.reduce((s,i)=>s+Number(i.price_cents||0)*Number(i.quantity||1),0))}
async function refreshOrders(){orders=await listOrders().catch(()=>[]);$('#orderCount').textContent=orders.length.toLocaleString();$('#ordersList').innerHTML=orders.length?orders.map(o=>`<article class="store-row"><span><b>${safe(o.product_name||o.product?.title||'Order')}</b><small>${money(o.amount_total)} • ${safe(o.order_status||'pending')}</small></span></article>`).join(''):'<div class="empty">No orders yet.</div>'}
async function openComments(product){activeProduct=product;$('#commentsTitle').textContent=product.title||'Comments';const rows=await listProductComments(product.id).catch(()=>[]);$('#commentsList').innerHTML=rows.length?rows.map(r=>`<article class="store-row"><span><b>${safe(r.profile?.display_name||r.profile?.username||'Rich User')}</b><small>${safe(r.body)}</small></span></article>`).join(''):'<div class="empty">No comments yet.</div>';$('#commentsDialog').showModal();await viewProduct(product.id).catch(()=>{})}
async function openAlerts(){const rows=await listSellerNotifications().catch(()=>[]);$('#alertsList').innerHTML=rows.length?rows.map(r=>`<article class="store-row ${r.is_read?'':'notification-unread'}" data-alert-id="${safe(r.id)}"><span><b>${safe(r.title||'Store Alert')}</b><small>${safe(r.body||'Store activity')}</small></span><button data-read-alert>READ</button></article>`).join(''):'<div class="empty">No seller alerts yet.</div>';$('#alertsDialog').showModal()}

document.addEventListener('click',async e=>{const close=e.target.closest('[data-close-dialog]');if(close)document.getElementById(close.dataset.closeDialog)?.close();if(e.target.closest('#openCart')){await refreshCart();$('#cartDialog').showModal()}if(e.target.closest('#openOrders')){await refreshOrders();$('#ordersDialog').showModal()}if(e.target.closest('#openAlerts'))await openAlerts();const b=e.target.closest('[data-store-action]'),box=e.target.closest('[data-product]');if(b&&box){const p=products.find(x=>String(x.id)===box.dataset.product);if(!p)return;if(b.dataset.storeAction==='like')await likeProduct(p.id);if(b.dataset.storeAction==='cart')await addToCart(p);if(b.dataset.storeAction==='buy')await createOrder(p);if(b.dataset.storeAction==='comment')await openComments(p);await Promise.all([refreshCart(),refreshOrders()]);scheduleProducts()}const cb=e.target.closest('[data-cart-action]');if(cb){const row=cb.closest('[data-cart-id]'),item=cart.find(i=>String(i.id)===row?.dataset.cartId);if(!item)return;if(cb.dataset.cartAction==='plus')await updateCartQuantity(item.id,Number(item.quantity||1)+1);if(cb.dataset.cartAction==='minus')await updateCartQuantity(item.id,Math.max(1,Number(item.quantity||1)-1));if(cb.dataset.cartAction==='remove')await removeCartItem(item.id);await refreshCart()}const read=e.target.closest('[data-read-alert]');if(read){const row=read.closest('[data-alert-id]');await markStoreNotificationRead(row.dataset.alertId);row.classList.remove('notification-unread')}});
$('#commentForm')?.addEventListener('submit',async e=>{e.preventDefault();const body=$('#commentBody').value.trim();if(!activeProduct||!body)return;await commentProduct(activeProduct.id,body);$('#commentBody').value='';await openComments(activeProduct);scheduleProducts()});
async function boot(){const user=await getSessionUser().catch(()=>null);await Promise.all([loadProducts(),seller(),refreshCart(),refreshOrders()]);channel=supabase.channel('store-owner:products').on('postgres_changes',{event:'*',schema:'public',table:'products'},scheduleProducts).on('postgres_changes',{event:'*',schema:'public',table:'product_likes'},scheduleProducts).on('postgres_changes',{event:'*',schema:'public',table:'store_comments'},scheduleProducts).subscribe();if(user?.id){const filter=`user_id=eq.${user.id}`;userChannel=supabase.channel(`store-owner:user:${user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'store_cart_items',filter},refreshCart).on('postgres_changes',{event:'*',schema:'public',table:'store_orders',filter},refreshOrders).subscribe()}}
function cleanup(){clearTimeout(timer);if(channel)supabase.removeChannel(channel);if(userChannel)supabase.removeChannel(userChannel);channel=null;userChannel=null}
window.addEventListener('pagehide',cleanup,{once:true});
boot().catch(e=>say(e.message||String(e)));
