import { supabase } from './supabase-client.js';
const $=(s)=>document.querySelector(s);const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=(v)=>{try{const u=new URL(String(v||''),location.origin);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}};
let lane='all',products=[],selected=null,user=null,profile=null,cart=[],disposed=false,busy=false,channels=[],timer=null;
function status(m,t='ready'){const n=$('#storeStatus');if(n){n.textContent=m;n.dataset.tone=t}}
function money(c=0){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(c||0)/100)}
function imageOf(r){return safeUrl(r.image_url||r.cover_url||r.media_url||r.preview_url)}
function visible(r){if(lane==='all')return true;if(lane==='digital')return !!r.is_digital||r.product_type==='digital';if(lane==='local')return !!r.is_local;return !r.is_digital&&r.product_type!=='digital'}
function card(r){const img=imageOf(r),stock=Number(r.inventory_count??r.quantity??0);return `<article class="product-card" aria-current="${selected?.id===r.id}">${img?`<img src="${esc(img)}" alt="" loading="lazy">`:'<span class="fallback">RB</span>'}<button type="button" data-product="${esc(r.id)}" style="all:unset;cursor:pointer"><b>${esc(r.title||'Untitled')}</b><small>${esc(r.category||r.product_type||'product')} • ${stock>0?`${stock} available`:'sold out'}</small><span class="price">${money(r.price_cents)}</span></button><div class="actions"><button class="btn" type="button" data-cart="${esc(r.id)}">ADD</button></div></article>`}
function paintProducts(){const rows=products.filter(visible);$('#productList').innerHTML=rows.length?rows.map(card).join(''):'<div class="empty">No products in this lane yet.</div>';$('#productMetric').textContent=rows.length.toLocaleString()}
function paintSelected(){if(!selected){$('#selectedTitle').textContent='SELECT A PRODUCT';$('#selectedDescription').textContent='Product details will show here.';return}$('#selectedTitle').textContent=selected.title||'Untitled';$('#selectedDescription').textContent=[selected.description,`Price ${money(selected.price_cents)}`,selected.fulfillment_type||selected.product_type].filter(Boolean).join(' • ');document.querySelectorAll('.product-card').forEach(n=>n.setAttribute('aria-current',String(n.querySelector('[data-product]')?.dataset.product===selected.id)))}
async function identity(){const {data}=await supabase.auth.getUser();user=data?.user||null;if(user){const {data:p}=await supabase.from('profiles').select('id,username,display_name,email').eq('id',user.id).maybeSingle();profile=p||null}}
async function loadProducts(){status('SYNCING MARKET');const {data,error}=await supabase.from('products').select('*').eq('is_public',true).eq('status','active').order('is_featured',{ascending:false}).order('created_at',{ascending:false}).limit(80);if(error)throw error;products=data||[];if(selected)selected=products.find(x=>x.id===selected.id)||products[0]||null;else selected=products[0]||null;paintProducts();paintSelected();status('MARKET CONNECTED • ONE STORE OWNER')}
async function loadComments(){if(!selected)return $('#commentList').innerHTML='';const {data}=await supabase.from('store_comments').select('id,body,created_at,user_id').eq('product_id',selected.id).order('created_at',{ascending:false}).limit(20);$('#commentList').innerHTML=(data||[]).map(r=>`<div class="comment">${esc(r.body)}</div>`).join('')}
async function loadCart(){if(!user)return;const {data,error}=await supabase.from('store_cart_items').select('id,product_id,quantity,price_cents,currency,products(title,image_url,cover_url)').eq('user_id',user.id).order('created_at');if(error)throw error;cart=data||[];$('#cartList').innerHTML=cart.length?cart.map(r=>`<div class="cart-item"><b>${esc(r.products?.title||'Product')}</b><span>${Number(r.quantity||1)} × ${money(r.price_cents)}</span></div>`).join(''):'<div class="empty">Your cart is empty.</div>';$('#cartTotal').textContent=money(cart.reduce((a,r)=>a+Number(r.price_cents||0)*Number(r.quantity||1),0))}
async function loadSeller(){if(!user)return;const {data}=await supabase.from('store_seller_profiles').select('seller_name,seller_rank,status,available_balance_cents,pending_balance_cents').eq('user_id',user.id).maybeSingle();$('#sellerBalance').textContent=data?`${data.seller_name||profile?.display_name||'Seller'} • ${data.seller_rank||'Seller'} • Available ${money(data.available_balance_cents)} • Pending ${money(data.pending_balance_cents)}`:'Seller profile not created yet.'}
async function addToCart(productId){if(!user)return status('TAP IN TO USE CART','error');const p=products.find(x=>x.id===productId);if(!p)return;const stock=Number(p.inventory_count??p.quantity??0);if(!p.is_digital&&stock<1)return status('PRODUCT SOLD OUT','error');const {data:existing}=await supabase.from('store_cart_items').select('id,quantity').eq('user_id',user.id).eq('product_id',p.id).maybeSingle();const q=Number(existing?.quantity||0)+1;const result=existing?await supabase.from('store_cart_items').update({quantity:q,price_cents:p.price_cents,currency:p.currency||'usd'}).eq('id',existing.id):await supabase.from('store_cart_items').insert({user_id:user.id,product_id:p.id,seller_id:p.seller_id,quantity:1,price_cents:p.price_cents,currency:p.currency||'usd',metadata:{source:'store-owner'}});if(result.error)return status(`CART FAILED • ${result.error.message}`,'error');status('ADDED TO CART');await loadCart()}
async function toggleLike(){if(!user||!selected)return status('TAP IN AND SELECT A PRODUCT','error');const {data}=await supabase.from('product_likes').select('id').eq('product_id',selected.id).eq('user_id',user.id).maybeSingle();const result=data?await supabase.from('product_likes').delete().eq('id',data.id):await supabase.from('product_likes').insert({product_id:selected.id,user_id:user.id,reaction:'like'});if(result.error)return status(`LIKE FAILED • ${result.error.message}`,'error');status(data?'PRODUCT UNLIKED':'PRODUCT LIKED')}
async function comment(e){e.preventDefault();if(!user||!selected)return status('TAP IN AND SELECT A PRODUCT','error');const body=String($('#commentInput').value||'').trim();if(!body)return;const {error}=await supabase.from('store_comments').insert({product_id:selected.id,user_id:user.id,body});if(error)return status(`COMMENT FAILED • ${error.message}`,'error');e.currentTarget.reset();await loadComments();status('COMMENT DROPPED')}
async function listProduct(e){e.preventDefault();if(busy)return;if(!user)return status('TAP IN TO LIST PRODUCTS','error');busy=true;try{const type=$('#productType').value;const price=Math.max(0,Math.round(Number($('#productPrice').value||0)*100));const image=safeUrl($('#productImage').value);const payload={seller_id:user.id,title:String($('#productTitle').value||'').trim(),description:String($('#productDescription').value||'').trim(),category:String($('#productCategory').value||'').trim()||'creator',product_type:type,fulfillment_type:type==='digital'?'digital':'shipping',price_cents:price,currency:'usd',image_url:image||null,cover_url:image||null,inventory_count:Number($('#productInventory').value||0),quantity:Number($('#productInventory').value||0),is_digital:type==='digital',is_local:false,is_featured:false,is_public:true,status:'active',metadata:{source:'store-owner'}};const {error}=await supabase.from('products').insert(payload);if(error)throw error;e.currentTarget.reset();status('PRODUCT LISTED');await loadProducts()}catch(err){status(`LISTING FAILED • ${err.message}`,'error')}finally{busy=false}}
async function createOrders(){if(!user||!cart.length)return status('CART IS EMPTY','error');if(busy)return;busy=true;try{for(const item of cart){const p=products.find(x=>x.id===item.product_id);if(!p)continue;const total=Number(item.price_cents||0)*Number(item.quantity||1);const fee=Math.round(total*.1);const {error}=await supabase.from('store_orders').insert({buyer_id:user.id,seller_id:p.seller_id,product_id:p.id,product_name:p.title,quantity:item.quantity,amount_total:total,platform_fee_cents:fee,seller_amount_cents:total-fee,currency:p.currency||'usd',payment_status:'pending',order_status:'processing',customer_email:user.email||null,fulfillment_type:p.fulfillment_type||'shipping',metadata:{source:'store-owner',payment_required:true}});if(error)throw error}await supabase.from('store_cart_items').delete().eq('user_id',user.id);await loadCart();status('ORDER CREATED • PAYMENT CONNECTION REQUIRED')}catch(err){status(`ORDER FAILED • ${err.message}`,'error')}finally{busy=false}}
function schedule(){clearTimeout(timer);timer=setTimeout(async()=>{await loadProducts();if(user)await loadCart()},180)}
function realtime(){channels.push(supabase.channel('rb-store-products').on('postgres_changes',{event:'*',schema:'public',table:'products'},schedule).subscribe());if(user)channels.push(supabase.channel(`rb-store-cart:${user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'store_cart_items',filter:`user_id=eq.${user.id}`},loadCart).subscribe())}
function bind(){document.addEventListener('click',async e=>{const tab=e.target.closest('[data-lane]');if(tab){lane=tab.dataset.lane;document.querySelectorAll('[data-lane]').forEach(n=>n.setAttribute('aria-pressed',String(n.dataset.lane===lane)));return paintProducts()}const pick=e.target.closest('[data-product]');if(pick){selected=products.find(x=>x.id===pick.dataset.product)||null;paintSelected();return loadComments()}const add=e.target.closest('[data-cart]');if(add)return addToCart(add.dataset.cart)});$('#addCart').addEventListener('click',()=>selected&&addToCart(selected.id));$('#likeProduct').addEventListener('click',toggleLike);$('#shareProduct').addEventListener('click',()=>selected&&navigator.share?.({title:selected.title,url:`${location.origin}/store.html?product=${selected.id}`}).catch(()=>{}));$('#commentForm').addEventListener('submit',comment);$('#productForm').addEventListener('submit',listProduct);$('#orderButton').addEventListener('click',createOrders)}
function cleanup(){disposed=true;clearTimeout(timer);channels.forEach(c=>supabase.removeChannel(c));channels=[]}
async function boot(){if(!supabase)return status('SUPABASE ENV VARIABLES REQUIRED','error');try{await identity();bind();await loadProducts();await loadComments();if(user){await loadCart();await loadSeller()}realtime();window.addEventListener('pagehide',cleanup,{once:true})}catch(e){status(`STORE FAILED • ${e.message}`,'error')}}
boot();