import { supabase } from './supabase-client.js';
const $=s=>document.querySelector(s),esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=v=>{try{const u=new URL(String(v||''),location.origin);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}};
let lane='all',query='',products=[],selected=null,user=null,profile=null,cart=[],disposed=false,busy=false,channels=[],timer=null,liked=false,online=navigator.onLine;
function status(m,t='ready'){const n=$('#storeStatus');if(n){n.textContent=m;n.dataset.tone=t}}
function connection(){const n=$('#storeConnection');if(n)n.textContent=online?'ONLINE • REALTIME READY':'OFFLINE • CART SAVED IN CLOUD'}
function authRoute(){location.href=`/auth.html?next=${encodeURIComponent(location.pathname+location.search)}`}
function money(c=0){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(c||0)/100)}
function imageOf(r){return safeUrl(r.image_url||r.cover_url||r.media_url||r.preview_url)}
function digital(r){return !!r.is_digital||r.product_type==='digital'}
function stockOf(r){return digital(r)?999999:Number(r.inventory_count??r.quantity??0)}
function visible(r){const q=query.trim().toLowerCase();const laneOk=lane==='all'||(lane==='digital'&&digital(r))||(lane==='local'&&r.is_local)||(lane==='physical'&&!digital(r)&&!r.is_local);const searchOk=!q||[r.title,r.description,r.category,r.location_label].some(v=>String(v||'').toLowerCase().includes(q));return laneOk&&searchOk}
function card(r){const img=imageOf(r),stock=stockOf(r),sold=stock<1;return `<article class="product-card" aria-current="${selected?.id===r.id}" data-sold="${sold}">${img?`<img src="${esc(img)}" alt="${esc(r.title||'Product')}" loading="lazy">`:'<span class="fallback">RB</span>'}<button type="button" data-product="${esc(r.id)}"><b>${esc(r.title||'Untitled')}</b><small>${esc([r.category,digital(r)?'digital':r.is_local?'local':'physical',sold?'sold out':digital(r)?'instant unlock':`${stock} available`].filter(Boolean).join(' • '))}</small><span class="price">${money(r.price_cents)}</span></button><button class="btn" type="button" data-cart="${esc(r.id)}" ${sold?'disabled':''}>${sold?'SOLD OUT':'ADD'}</button></article>`}
function paintProducts(){const rows=products.filter(visible);$('#productList').innerHTML=rows.length?rows.map(card).join(''):'<div class="empty">No products match this lane or search.</div>';$('#productMetric').textContent=rows.length.toLocaleString()}
async function refreshLike(){liked=false;if(user&&selected){const {data}=await supabase.from('product_likes').select('id').eq('product_id',selected.id).eq('user_id',user.id).maybeSingle();liked=!!data}const b=$('#likeProduct');if(b){b.textContent=liked?'LIKED':'LIKE';b.setAttribute('aria-pressed',String(liked))}}
async function recordView(){if(!selected)return;const anonymousId=localStorage.getItem('rb-store-anon')||crypto.randomUUID();localStorage.setItem('rb-store-anon',anonymousId);await supabase.from('product_views').insert({product_id:selected.id,user_id:user?.id||null,anonymous_id:user?null:anonymousId}).then(()=>{})}
async function paintSelected(){if(!selected){$('#selectedTitle').textContent='SELECT A PRODUCT';$('#selectedDescription').textContent='Product details will show here.';$('#selectedFacts').innerHTML='';$('#sellerIdentity').textContent='SELECT A PRODUCT TO LOAD SELLER';return}const img=imageOf(selected),stock=stockOf(selected),sold=stock<1;$('#selectedTitle').textContent=selected.title||'Untitled';$('#selectedDescription').textContent=selected.description||'Rich Bizness creator product.';$('#selectedFacts').innerHTML=[money(selected.price_cents),digital(selected)?'DIGITAL UNLOCK':selected.is_local?'LOCAL FULFILLMENT':'SHIPPING',sold?'SOLD OUT':digital(selected)?'READY AFTER PAYMENT':`${stock} IN STOCK`].map(x=>`<span>${esc(x)}</span>`).join('');$('#selectedMedia').innerHTML=img?`<img src="${esc(img)}" alt="${esc(selected.title||'Product')}">`:'<span class="fallback">RB</span>';$('#addCart').disabled=sold;document.querySelectorAll('.product-card').forEach(n=>n.setAttribute('aria-current',String(n.querySelector('[data-product]')?.dataset.product===selected.id)));const {data:seller}=await supabase.from('store_seller_profiles').select('seller_name,seller_rank,status,location_label').eq('user_id',selected.seller_id).maybeSingle();$('#sellerIdentity').textContent=seller?`${seller.seller_name||'Rich Seller'} • ${seller.seller_rank||'Seller'} • ${seller.status||'active'}${seller.location_label?` • ${seller.location_label}`:''}`:'RICH BIZNESS SELLER';await Promise.all([refreshLike(),loadComments(),recordView()])}
async function identity(){const {data}=await supabase.auth.getUser();user=data?.user||null;if(user){const {data:p}=await supabase.from('profiles').select('id,username,display_name,email').eq('id',user.id).maybeSingle();profile=p||null}}
async function loadProducts(){if(disposed)return;status('SYNCING MARKET');const {data,error}=await supabase.from('products').select('*').eq('is_public',true).eq('status','active').order('is_featured',{ascending:false}).order('created_at',{ascending:false}).limit(100);if(error)throw error;products=data||[];const deep=new URLSearchParams(location.search).get('product');selected=products.find(x=>x.id===(deep||selected?.id))||products[0]||null;paintProducts();await paintSelected();status('MARKET CONNECTED • ONE STORE OWNER')}
async function loadComments(){if(!selected)return $('#commentList').innerHTML='<div class="empty">Select a product to load comments.</div>';const {data}=await supabase.from('store_comments').select('id,body,created_at,user_id').eq('product_id',selected.id).order('created_at',{ascending:false}).limit(20);$('#commentList').innerHTML=(data||[]).map(r=>`<div class="comment">${esc(r.body)}</div>`).join('')||'<div class="empty">No comments yet.</div>'}
function cartItem(r){const max=stockOf(products.find(p=>p.id===r.product_id)||{});return `<div class="cart-item"><div><b>${esc(r.products?.title||'Product')}</b><small>${money(r.price_cents)} each</small></div><div class="quantity"><button type="button" data-qty="${esc(r.id)}" data-delta="-1">−</button><span>${Number(r.quantity||1)}</span><button type="button" data-qty="${esc(r.id)}" data-delta="1" ${Number(r.quantity||1)>=max?'disabled':''}>+</button></div><button type="button" data-remove="${esc(r.id)}">REMOVE</button></div>`}
async function loadCart(){if(!user){$('#cartList').innerHTML='<div class="empty">Sign in to load your cart.</div>';return}const {data,error}=await supabase.from('store_cart_items').select('id,product_id,quantity,price_cents,currency,products(title,image_url,cover_url,is_digital,inventory_count,quantity)').eq('user_id',user.id).order('created_at');if(error)throw error;cart=data||[];$('#cartList').innerHTML=cart.length?cart.map(cartItem).join(''):'<div class="empty">Your cart is empty.</div>';const total=cart.reduce((a,r)=>a+Number(r.price_cents||0)*Number(r.quantity||1),0);$('#cartTotal').textContent=money(total);$('#checkoutState').textContent=cart.length&&online?'READY FOR SECURE PAYMENT SESSION':cart.length?'OFFLINE • CHECKOUT PAUSED':'CART NOT READY';$('#orderButton').disabled=!cart.length||!online}
async function loadOrders(){if(!user)return;const {data}=await supabase.from('store_orders').select('id,product_name,quantity,amount_total,payment_status,order_status,fulfillment_type,created_at').eq('buyer_id',user.id).order('created_at',{ascending:false}).limit(20);$('#orderList').innerHTML=(data||[]).map(o=>`<div class="order"><b>${esc(o.product_name||'Order')}</b><small>${money(o.amount_total)} • ${esc(o.payment_status||'pending')} • ${esc(o.order_status||'processing')} • ${esc(o.fulfillment_type||'shipping')}</small></div>`).join('')||'<div class="empty">No orders yet.</div>'}
async function loadSeller(){if(!user)return;const {data}=await supabase.from('store_seller_profiles').select('seller_name,seller_rank,status,available_balance_cents,pending_balance_cents,stripe_onboarding_complete,payouts_enabled').eq('user_id',user.id).maybeSingle();$('#sellerBalance').textContent=data?`${data.seller_name||profile?.display_name||'Seller'} • ${data.seller_rank||'Seller'} • Available ${money(data.available_balance_cents)} • Pending ${money(data.pending_balance_cents)} • ${data.payouts_enabled?'Payouts ready':data.stripe_onboarding_complete?'Payout review':'Seller payout setup required'}`:'Seller profile not created yet.'}
async function addToCart(productId){if(!user)return authRoute();const p=products.find(x=>x.id===productId);if(!p)return;const stock=stockOf(p);if(stock<1)return status('PRODUCT SOLD OUT','error');const {data:existing}=await supabase.from('store_cart_items').select('id,quantity').eq('user_id',user.id).eq('product_id',p.id).maybeSingle();const q=Math.min(stock,Number(existing?.quantity||0)+1);const result=existing?await supabase.from('store_cart_items').update({quantity:q,price_cents:p.price_cents,currency:p.currency||'usd',updated_at:new Date().toISOString()}).eq('id',existing.id):await supabase.from('store_cart_items').insert({user_id:user.id,product_id:p.id,seller_id:p.seller_id,quantity:1,price_cents:p.price_cents,currency:p.currency||'usd',metadata:{source:'store-owner'}});if(result.error)return status(`CART FAILED • ${result.error.message}`,'error');status('ADDED TO CART');await loadCart()}
async function changeQuantity(id,delta){const item=cart.find(x=>x.id===id);if(!item)return;const p=products.find(x=>x.id===item.product_id);const next=Number(item.quantity||1)+Number(delta);if(next<1)return removeCart(id);if(p&&next>stockOf(p))return status('NO MORE STOCK AVAILABLE','error');const {error}=await supabase.from('store_cart_items').update({quantity:next,updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',user.id);if(error)return status(`CART FAILED • ${error.message}`,'error');await loadCart()}
async function removeCart(id){const {error}=await supabase.from('store_cart_items').delete().eq('id',id).eq('user_id',user.id);if(error)return status(`REMOVE FAILED • ${error.message}`,'error');await loadCart();status('REMOVED FROM CART')}
async function toggleLike(){if(!user)return authRoute();if(!selected)return status('SELECT A PRODUCT','error');const result=liked?await supabase.from('product_likes').delete().eq('product_id',selected.id).eq('user_id',user.id):await supabase.from('product_likes').insert({product_id:selected.id,user_id:user.id,reaction:'like'});if(result.error)return status(`LIKE FAILED • ${result.error.message}`,'error');liked=!liked;await refreshLike();status(liked?'PRODUCT LIKED':'PRODUCT UNLIKED')}
async function comment(e){e.preventDefault();if(!user)return authRoute();if(!selected)return status('SELECT A PRODUCT','error');const body=String($('#commentInput').value||'').trim();if(!body)return;const {error}=await supabase.from('store_comments').insert({product_id:selected.id,user_id:user.id,body});if(error)return status(`COMMENT FAILED • ${error.message}`,'error');e.currentTarget.reset();await loadComments();status('COMMENT DROPPED')}
async function listProduct(e){e.preventDefault();if(busy)return;if(!user)return authRoute();busy=true;try{const type=$('#productType').value,price=Math.max(0,Math.round(Number($('#productPrice').value||0)*100)),image=safeUrl($('#productImage').value),file=safeUrl($('#digitalFileUrl').value),inventory=Math.max(0,Number($('#productInventory').value||0));if(type==='digital'&&!file)throw new Error('DIGITAL FILE URL REQUIRED');const payload={seller_id:user.id,title:String($('#productTitle').value||'').trim(),description:String($('#productDescription').value||'').trim(),category:String($('#productCategory').value||'').trim()||'creator',product_type:type==='local'?'physical':type,fulfillment_type:type==='digital'?'digital':type==='local'?'local':'shipping',price_cents:price,currency:'usd',image_url:image||null,cover_url:image||null,digital_file_url:type==='digital'?file:null,inventory_count:type==='digital'?999999:inventory,quantity:type==='digital'?999999:inventory,is_digital:type==='digital',is_local:type==='local',is_featured:false,is_public:true,status:'active',metadata:{source:'store-owner'}};const {error}=await supabase.from('products').insert(payload);if(error)throw error;e.currentTarget.reset();status('PRODUCT LISTED');await loadProducts()}catch(err){status(`LISTING FAILED • ${err.message}`,'error')}finally{busy=false}}
async function createOrders(){if(!user)return authRoute();if(!cart.length)return status('CART IS EMPTY','error');if(!online)return status('CHECKOUT REQUIRES CONNECTION','error');if(busy)return;busy=true;try{const created=[];for(const item of cart){const p=products.find(x=>x.id===item.product_id);if(!p)throw new Error('PRODUCT NO LONGER AVAILABLE');if(!digital(p)&&Number(item.quantity)>stockOf(p))throw new Error(`${p.title} STOCK CHANGED`);const total=Number(item.price_cents||0)*Number(item.quantity||1),fee=Math.round(total*.1);const {data,error}=await supabase.from('store_orders').insert({buyer_id:user.id,seller_id:p.seller_id,product_id:p.id,product_name:p.title,quantity:item.quantity,amount_total:total,platform_fee_cents:fee,seller_amount_cents:total-fee,currency:p.currency||'usd',payment_status:'pending',order_status:'pending_payment',customer_email:user.email||null,fulfillment_type:p.fulfillment_type||'shipping',metadata:{source:'store-owner',payment_required:true,digital:digital(p)}}).select('id').single();if(error)throw error;created.push(data.id)}status(`ORDER READY • ${created.length} PAYMENT SESSION${created.length===1?'':'S'} REQUIRED`);await loadOrders()}catch(err){status(`CHECKOUT FAILED • ${err.message}`,'error')}finally{busy=false}}
function schedule(){clearTimeout(timer);timer=setTimeout(async()=>{await loadProducts();if(user){await loadCart();await loadOrders()}},220)}
function realtime(){channels.push(supabase.channel('rb-store-owner').on('postgres_changes',{event:'*',schema:'public',table:'products'},schedule).on('postgres_changes',{event:'*',schema:'public',table:'store_comments'},()=>selected&&loadComments()).subscribe());if(user)channels.push(supabase.channel(`rb-store-user:${user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'store_cart_items',filter:`user_id=eq.${user.id}`},loadCart).on('postgres_changes',{event:'*',schema:'public',table:'store_orders',filter:`buyer_id=eq.${user.id}`},loadOrders).subscribe())}
function bind(){document.addEventListener('click',async e=>{const tab=e.target.closest('[data-lane]');if(tab){lane=tab.dataset.lane;document.querySelectorAll('[data-lane]').forEach(n=>n.setAttribute('aria-pressed',String(n.dataset.lane===lane)));return paintProducts()}const pick=e.target.closest('[data-product]');if(pick){selected=products.find(x=>x.id===pick.dataset.product)||null;history.replaceState({},'',`/store.html?product=${encodeURIComponent(selected?.id||'')}`);return paintSelected()}const add=e.target.closest('[data-cart]');if(add)return addToCart(add.dataset.cart);const qty=e.target.closest('[data-qty]');if(qty)return changeQuantity(qty.dataset.qty,qty.dataset.delta);const remove=e.target.closest('[data-remove]');if(remove)return removeCart(remove.dataset.remove)});$('#productSearch')?.addEventListener('input',e=>{query=e.target.value;paintProducts()});$('#addCart')?.addEventListener('click',()=>selected&&addToCart(selected.id));$('#likeProduct')?.addEventListener('click',toggleLike);$('#shareProduct')?.addEventListener('click',async()=>{if(!selected)return;const url=`${location.origin}/store.html?product=${selected.id}`;if(navigator.share)await navigator.share({title:selected.title,url}).catch(()=>{});else await navigator.clipboard?.writeText(url);status('PRODUCT LINK READY')});$('#commentForm')?.addEventListener('submit',comment);$('#productForm')?.addEventListener('submit',listProduct);$('#orderButton')?.addEventListener('click',createOrders);addEventListener('online',()=>{online=true;connection();schedule()});addEventListener('offline',()=>{online=false;connection();loadCart()});document.addEventListener('visibilitychange',()=>{if(!document.hidden)schedule()})}
function cleanup(){disposed=true;clearTimeout(timer);channels.forEach(c=>supabase.removeChannel(c));channels=[]}
async function boot(){if(!supabase)return status('SUPABASE ENV VARIABLES REQUIRED','error');try{connection();await identity();bind();await loadProducts();if(user){await Promise.all([loadCart(),loadSeller(),loadOrders()])}else await loadCart();realtime();window.addEventListener('pagehide',cleanup,{once:true})}catch(e){status(`STORE FAILED • ${e.message}`,'error')}}
boot();