import { supabase } from '../../core/supabase/client';
import './communications.css';

type Thread={id:string;title:string|null;thread_type:string|null;last_message:string|null;last_message_at:string|null;typing_label:string|null};
type Message={id:string;thread_id:string;sender_id:string|null;display_name:string|null;username:string|null;body:string|null;message_type:string|null;media_url:string|null;created_at:string|null};
type Profile={id:string;username:string|null;display_name:string|null;avatar_url:string|null;online_status:string|null};
const esc=(v:string|null|undefined)=>(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]??c));
const stamp=(v:string|null)=>v?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(v)):'';

export async function mount():Promise<void>{
 const root=document.querySelector<HTMLElement>('#app');if(!root)throw new Error('Missing #app mount');
 const {data:{session}}=await supabase.auth.getSession();if(!session){location.replace('/tap-in.html?next=%2Fmessages.html');return;}
 root.innerHTML=`<main class="comm-shell"><div class="comm-wrap"><header class="comm-head"><a href="/portal.html">←</a><div><p>RICH-DM’S • PRIVATE REALTIME</p><h1>Messages</h1></div><span class="comm-pill">LIVE</span></header><section class="message-layout"><aside class="comm-card thread-list-shell"><div class="thread-toolbar"><input id="threadSearch" placeholder="Search conversations"/><button id="newThread" class="comm-button primary">＋</button></div><div id="threadList" class="comm-list thread-list"></div></aside><section id="threadPanel" class="comm-card thread-panel"><div class="comm-empty">Choose a conversation or start a new one.</div></section></section></div></main>`;
 const threadList=document.querySelector<HTMLElement>('#threadList')!;const panel=document.querySelector<HTMLElement>('#threadPanel')!;const search=document.querySelector<HTMLInputElement>('#threadSearch')!;
 let activeThread:string|null=new URLSearchParams(location.search).get('thread');let threadChannel:any=null;let typingTimer:number|undefined;let cachedThreads:Thread[]=[];
 const loadThreads=async()=>{const {data:members,error}=await supabase.from('dm_thread_members').select('thread_id,is_pinned,last_read_at').eq('user_id',session.user.id).eq('status','active');if(error)throw error;const ids=(members??[]).map((m:any)=>m.thread_id);if(!ids.length){cachedThreads=[];drawThreads();return;}const {data,error:threadError}=await supabase.from('dm_threads').select('id,title,thread_type,last_message,last_message_at,typing_label').in('id',ids).eq('is_archived',false).order('last_message_at',{ascending:false,nullsFirst:false});if(threadError)throw threadError;cachedThreads=(data??[]) as Thread[];drawThreads();if(activeThread&&ids.includes(activeThread))await openThread(activeThread);};
 const drawThreads=()=>{const q=search.value.trim().toLowerCase();const rows=cachedThreads.filter(t=>!q||(t.title??'').toLowerCase().includes(q)||(t.last_message??'').toLowerCase().includes(q));threadList.innerHTML=rows.length?rows.map(t=>`<button class="comm-item ${activeThread===t.id?'active':''}" data-thread="${t.id}"><span class="comm-icon">${t.thread_type==='group'?'👥':'💨'}</span><div><h3>${esc(t.title||'Rich Conversation')}</h3><p>${esc(t.last_message||t.typing_label||'Start the smoke...')}</p></div><time>${stamp(t.last_message_at)}</time></button>`).join(''):'<div class="comm-empty">No conversations found.</div>';threadList.querySelectorAll<HTMLElement>('[data-thread]').forEach(el=>el.addEventListener('click',()=>void openThread(el.dataset.thread!)));};
 const fetchMessages=async(threadId:string)=>{const {data,error}=await supabase.from('dm_messages').select('id,thread_id,sender_id,display_name,username,body,message_type,media_url,created_at').eq('thread_id',threadId).eq('is_deleted',false).order('created_at',{ascending:true}).limit(250);if(error)throw error;return(data??[]) as Message[];};
 const openThread=async(threadId:string)=>{activeThread=threadId;drawThreads();history.replaceState({},'',`/messages.html?thread=${threadId}`);if(threadChannel)await supabase.removeChannel(threadChannel);const [{data:thread},{data:members},messages]=await Promise.all([supabase.from('dm_threads').select('id,title,typing_label,call_theme').eq('id',threadId).single(),supabase.from('dm_thread_members').select('user_id,role,status').eq('thread_id',threadId).eq('status','active'),fetchMessages(threadId)]);panel.innerHTML=`<header class="thread-title"><div><strong>${esc((thread as any)?.title||'Rich Conversation')}</strong><p id="typingText">${esc((thread as any)?.typing_label||'encrypted realtime room')}</p></div><div class="thread-actions"><button id="audioCall" title="Audio call">☎</button><button id="videoCall" title="Video call">◉</button><button id="threadInfo" title="Thread info">⋯</button></div></header><div id="messageFeed" class="message-feed"></div><div id="typingRow" class="typing-row"></div><form id="composer" class="composer"><button id="attachButton" class="icon-button" type="button">＋</button><input id="messageInput" maxlength="2000" autocomplete="off" placeholder="Send a Rich-DM..."/><button class="comm-button primary">SEND</button><input id="attachmentInput" type="file" hidden accept="image/*,video/*,audio/*,.pdf,.doc,.docx"/></form>`;
 const feed=panel.querySelector<HTMLElement>('#messageFeed')!;const input=panel.querySelector<HTMLInputElement>('#messageInput')!;const attachmentInput=panel.querySelector<HTMLInputElement>('#attachmentInput')!;
 const draw=async(rows:Message[])=>{const ids=rows.map(m=>m.id);let reactions:any[]=[];if(ids.length){const{data}=await supabase.from('dm_message_reactions').select('message_id,emoji,user_id').in('message_id',ids);reactions=data??[];}feed.innerHTML=rows.length?rows.map(m=>{const counts=reactions.filter(r=>r.message_id===m.id).reduce((a:any,r:any)=>(a[r.emoji]=(a[r.emoji]||0)+1,a),{});const media=m.media_url?`<a href="${esc(m.media_url)}" target="_blank" rel="noopener">Open ${esc(m.message_type||'attachment')}</a>`:'';return`<article class="bubble ${m.sender_id===session.user.id?'mine':''}" data-message="${m.id}"><p>${esc(m.body||'')}</p>${media}<small>${esc(m.display_name||m.username||'Rich Member')} · ${stamp(m.created_at)}</small><div class="bubble-tools"><button data-react="💨">💨 ${counts['💨']||''}</button><button data-react="🔥">🔥 ${counts['🔥']||''}</button><button data-react="💯">💯 ${counts['💯']||''}</button></div></article>`;}).join(''):'<div class="comm-empty">Start the conversation.</div>';feed.scrollTop=feed.scrollHeight;feed.querySelectorAll<HTMLElement>('[data-react]').forEach(btn=>btn.addEventListener('click',async()=>{const article=btn.closest<HTMLElement>('[data-message]');if(!article)return;await supabase.from('dm_message_reactions').upsert({message_id:article.dataset.message!,user_id:session.user.id,emoji:btn.dataset.react!},{onConflict:'message_id,user_id,emoji'});draw(await fetchMessages(threadId));}));};
 await draw(messages);
 panel.querySelector<HTMLFormElement>('#composer')!.addEventListener('submit',async e=>{e.preventDefault();const body=input.value.trim();if(!body)return;input.value='';const {data:profile}=await supabase.from('profiles').select('username,display_name').eq('id',session.user.id).single();const {error}=await supabase.from('dm_messages').insert({thread_id:threadId,sender_id:session.user.id,username:(profile as any)?.username??null,display_name:(profile as any)?.display_name??null,body,message_type:'text'});if(error)throw error;await stopTyping(threadId);});
 input.addEventListener('input',()=>{void setTyping(threadId,true);clearTimeout(typingTimer);typingTimer=window.setTimeout(()=>void stopTyping(threadId),1400);});
 panel.querySelector('#attachButton')?.addEventListener('click',()=>attachmentInput.click());attachmentInput.addEventListener('change',async()=>{const file=attachmentInput.files?.[0];if(!file)return;if(file.size>25*1024*1024)throw new Error('Attachment must be 25 MB or smaller.');const path=`${session.user.id}/${threadId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const{error:uploadError}=await supabase.storage.from('general-uploads').upload(path,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError;const url=supabase.storage.from('general-uploads').getPublicUrl(path).data.publicUrl;const{data:profile}=await supabase.from('profiles').select('username,display_name').eq('id',session.user.id).single();await supabase.from('dm_messages').insert({thread_id:threadId,sender_id:session.user.id,username:(profile as any)?.username??null,display_name:(profile as any)?.display_name??null,body:file.name,media_url:url,media_type:file.type,message_type:file.type.startsWith('image/')?'image':file.type.startsWith('video/')?'video':file.type.startsWith('audio/')?'audio':'file'});attachmentInput.value='';});
 const startCall=async(type:'audio'|'video')=>{const room=`rich-call-${crypto.randomUUID().slice(0,8)}`;const{data,error}=await supabase.from('dm_call_sessions').insert({thread_id:threadId,started_by:session.user.id,call_type:type,call_status:'ringing',livekit_room_name:room}).select('id').single();if(error)throw error;await supabase.from('dm_call_participants').insert((members??[]).map((m:any)=>({call_id:(data as any).id,user_id:m.user_id,role:m.user_id===session.user.id?'host':'participant',status:m.user_id===session.user.id?'joined':'invited',audio_enabled:true,video_enabled:type==='video'})));location.href=`/messages.html?thread=${threadId}&call=${(data as any).id}`;};
 panel.querySelector('#audioCall')?.addEventListener('click',()=>void startCall('audio'));panel.querySelector('#videoCall')?.addEventListener('click',()=>void startCall('video'));
 await supabase.from('dm_thread_members').update({last_read_at:new Date().toISOString()}).eq('thread_id',threadId).eq('user_id',session.user.id);
 threadChannel=supabase.channel(`dm-premium:${threadId}`).on('postgres_changes',{event:'*',schema:'public',table:'dm_messages',filter:`thread_id=eq.${threadId}`},async()=>draw(await fetchMessages(threadId))).on('postgres_changes',{event:'*',schema:'public',table:'dm_typing_status',filter:`thread_id=eq.${threadId}`},async()=>{const{data}=await supabase.from('dm_typing_status').select('user_id,is_typing,typing_label').eq('thread_id',threadId).eq('is_typing',true).neq('user_id',session.user.id);panel.querySelector<HTMLElement>('#typingRow')!.textContent=(data??[]).length?((data as any[])[0].typing_label||'rolling smoke...'):'';}).subscribe();};
 const setTyping=async(threadId:string,isTyping:boolean)=>{await supabase.from('dm_typing_status').upsert({thread_id:threadId,user_id:session.user.id,is_typing:isTyping,typing_label:'rolling smoke...',updated_at:new Date().toISOString()},{onConflict:'thread_id,user_id'});};
 const stopTyping=(threadId:string)=>setTyping(threadId,false);
 const openNewThread=()=>{const modal=document.createElement('div');modal.className='new-thread-modal';modal.innerHTML=`<section class="comm-card new-thread-card"><header class="thread-title"><div><strong>New Rich-DM</strong><p>Search people by name or username.</p></div><button id="closeNew" class="comm-button">✕</button></header><input id="profileSearch" placeholder="Search Rich Bizness members"/><div id="profileResults" class="profile-results"></div></section>`;document.body.append(modal);const box=modal.querySelector<HTMLInputElement>('#profileSearch')!;const results=modal.querySelector<HTMLElement>('#profileResults')!;modal.querySelector('#closeNew')?.addEventListener('click',()=>modal.remove());box.addEventListener('input',async()=>{const q=box.value.trim();if(q.length<2){results.innerHTML='';return;}const{data}=await supabase.from('profiles').select('id,username,display_name,avatar_url,online_status').neq('id',session.user.id).or(`username.ilike.%${q}%,display_name.ilike.%${q}%`).limit(20);results.innerHTML=((data??[]) as Profile[]).map(p=>`<article class="profile-result"><img src="${esc(p.avatar_url||'/brand/icons/profile-placeholder.svg')}"/><div><strong>${esc(p.display_name||p.username||'Rich Member')}</strong><p>@${esc(p.username||'member')} · ${esc(p.online_status||'offline')}</p></div><button class="comm-button primary" data-user="${p.id}">MESSAGE</button></article>`).join('');results.querySelectorAll<HTMLElement>('[data-user]').forEach(b=>b.addEventListener('click',async()=>{const{data,error}=await supabase.rpc('rb_create_direct_thread',{p_other_user:b.dataset.user});if(error)throw error;modal.remove();activeThread=data as string;await loadThreads();}));});};
 search.addEventListener('input',drawThreads);document.querySelector('#newThread')?.addEventListener('click',openNewThread);await loadThreads();
 supabase.channel(`thread-list:${session.user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'dm_thread_members',filter:`user_id=eq.${session.user.id}`},()=>void loadThreads()).on('postgres_changes',{event:'*',schema:'public',table:'dm_threads'},()=>void loadThreads()).subscribe();
}
