import { supabase } from '../../core/supabase/client';
import './communications.css';

type Thread={id:string;title:string|null;thread_type:string|null;last_message:string|null;last_message_at:string|null;typing_label:string|null};
type Message={id:string;thread_id:string;sender_id:string|null;display_name:string|null;username:string|null;body:string|null;created_at:string|null};
function esc(v:string|null|undefined){return (v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]??c));}
function stamp(v:string|null){return v?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(v)):'';}

export async function mount():Promise<void>{
 const root=document.querySelector<HTMLElement>('#app');if(!root)throw new Error('Missing #app mount');
 const {data:{session}}=await supabase.auth.getSession();if(!session){location.replace('/tap-in.html?next=%2Fmessages.html');return;}
 root.innerHTML=`<main class="comm-shell"><div class="comm-wrap"><header class="comm-head"><a href="/portal.html">←</a><div><p>RICH-DM’S</p><h1>Messages</h1></div><span class="comm-pill">REALTIME</span></header><section class="message-layout"><aside id="threadList" class="comm-card comm-list thread-list"></aside><section id="threadPanel" class="comm-card thread-panel"><div class="comm-empty">Choose a conversation.</div></section></section></div></main>`;
 const threadList=document.querySelector<HTMLElement>('#threadList')!;const panel=document.querySelector<HTMLElement>('#threadPanel')!;
 let activeThread:string|null=new URLSearchParams(location.search).get('thread');
 let channel:any=null;
 const loadThreads=async()=>{const {data:members,error}=await supabase.from('dm_thread_members').select('thread_id,is_pinned,last_read_at').eq('user_id',session.user.id).eq('status','active');if(error)throw error;const ids=(members??[]).map((m:any)=>m.thread_id);if(!ids.length){threadList.innerHTML='<div class="comm-empty">No conversations yet.</div>';return;}const {data,error:threadError}=await supabase.from('dm_threads').select('id,title,thread_type,last_message,last_message_at,typing_label').in('id',ids).eq('is_archived',false).order('last_message_at',{ascending:false,nullsFirst:false});if(threadError)throw threadError;const rows=(data??[]) as Thread[];threadList.innerHTML=rows.map(t=>`<button class="comm-item" data-thread="${t.id}"><span class="comm-icon">💨</span><div><h3>${esc(t.title||'Rich Conversation')}</h3><p>${esc(t.last_message||t.typing_label||'Start the smoke...')}</p></div><time>${stamp(t.last_message_at)}</time></button>`).join('');threadList.querySelectorAll<HTMLElement>('[data-thread]').forEach(el=>el.addEventListener('click',()=>void openThread(el.dataset.thread!)));if(activeThread&&ids.includes(activeThread))await openThread(activeThread);};
 const openThread=async(threadId:string)=>{activeThread=threadId;history.replaceState({},'',`/messages.html?thread=${threadId}`);if(channel)await supabase.removeChannel(channel);const [{data:thread},{data:messages,error}]=await Promise.all([supabase.from('dm_threads').select('id,title,typing_label').eq('id',threadId).single(),supabase.from('dm_messages').select('id,thread_id,sender_id,display_name,username,body,created_at').eq('thread_id',threadId).eq('is_deleted',false).order('created_at',{ascending:true}).limit(200)]);if(error)throw error;panel.innerHTML=`<header class="thread-title"><strong>${esc((thread as any)?.title||'Rich Conversation')}</strong><p>${esc((thread as any)?.typing_label||'rolling smoke...')}</p></header><div id="messageFeed" class="message-feed"></div><form id="composer" class="composer"><input id="messageInput" maxlength="2000" autocomplete="off" placeholder="Send a Rich-DM..."/><button class="comm-button primary">SEND</button></form>`;const feed=panel.querySelector<HTMLElement>('#messageFeed')!;const draw=(rows:Message[])=>{feed.innerHTML=rows.length?rows.map(m=>`<article class="bubble ${m.sender_id===session.user.id?'mine':''}"><p>${esc(m.body||'')}</p><small>${esc(m.display_name||m.username||'Rich Member')} · ${stamp(m.created_at)}</small></article>`).join(''):'<div class="comm-empty">Start the conversation.</div>';feed.scrollTop=feed.scrollHeight;};draw((messages??[]) as Message[]);panel.querySelector<HTMLFormElement>('#composer')!.addEventListener('submit',async e=>{e.preventDefault();const input=panel.querySelector<HTMLInputElement>('#messageInput')!;const body=input.value.trim();if(!body)return;input.value='';const {data:profile}=await supabase.from('profiles').select('username,display_name').eq('id',session.user.id).single();const {error:sendError}=await supabase.from('dm_messages').insert({thread_id:threadId,sender_id:session.user.id,username:(profile as any)?.username??null,display_name:(profile as any)?.display_name??null,body,message_type:'text'});if(sendError)throw sendError;await supabase.from('dm_threads').update({last_message:body,last_message_at:new Date().toISOString(),last_message_user_id:session.user.id,updated_at:new Date().toISOString()}).eq('id',threadId);});channel=supabase.channel(`dm:${threadId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'dm_messages',filter:`thread_id=eq.${threadId}`},async()=>{const {data}=await supabase.from('dm_messages').select('id,thread_id,sender_id,display_name,username,body,created_at').eq('thread_id',threadId).eq('is_deleted',false).order('created_at',{ascending:true}).limit(200);draw((data??[]) as Message[]);}).subscribe();await supabase.from('dm_thread_members').update({last_read_at:new Date().toISOString()}).eq('thread_id',threadId).eq('user_id',session.user.id);};
 await loadThreads();
 supabase.channel(`thread-list:${session.user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'dm_thread_members',filter:`user_id=eq.${session.user.id}`},()=>void loadThreads()).subscribe();
}