import { supabase } from '../../core/supabase/client';
import './communications.css';

type JsonMap=Record<string,unknown>;
function bool(obj:JsonMap,key:string,fallback:boolean){return typeof obj[key]==='boolean'?obj[key] as boolean:fallback;}

export async function mount():Promise<void>{
 const root=document.querySelector<HTMLElement>('#app');if(!root)throw new Error('Missing #app mount');
 const {data:{session}}=await supabase.auth.getSession();if(!session){location.replace('/tap-in.html?next=%2Fsettings.html');return;}
 const {data,error}=await supabase.from('profiles').select('privacy_config,notification_config,online_status').eq('id',session.user.id).single();if(error)throw error;
 const privacy=((data as any)?.privacy_config??{}) as JsonMap;const notify=((data as any)?.notification_config??{}) as JsonMap;
 root.innerHTML=`<main class="comm-shell"><div class="comm-wrap"><header class="comm-head"><a href="/profile.html">←</a><div><p>RICH BIZNESS CONTROL CENTER</p><h1>Settings</h1></div><span id="saveState" class="comm-pill">READY</span></header><form id="settingsForm" class="comm-card comm-form"><section><h2>Notifications</h2><label class="toggle-row"><span><strong>Direct messages</strong><br/>Alert me when Rich-DM’s arrive.</span><input type="checkbox" name="dm" ${bool(notify,'dm',true)?'checked':''}></label><label class="toggle-row"><span><strong>Live alerts</strong><br/>Creators, VIP rooms, and broadcasts.</span><input type="checkbox" name="live" ${bool(notify,'live',true)?'checked':''}></label><label class="toggle-row"><span><strong>Store alerts</strong><br/>Orders, sales, comments, and drops.</span><input type="checkbox" name="store" ${bool(notify,'store',true)?'checked':''}></label><label class="toggle-row"><span><strong>Sports alerts</strong><br/>Picks, broadcasts, and team activity.</span><input type="checkbox" name="sports" ${bool(notify,'sports',true)?'checked':''}></label><label class="toggle-row"><span><strong>Game alerts</strong><br/>Challenges, rewards, and tournaments.</span><input type="checkbox" name="gaming" ${bool(notify,'gaming',true)?'checked':''}></label></section><section><h2>Privacy & Presence</h2><label class="toggle-row"><span><strong>Show online status</strong><br/>Let members see when you are active.</span><input type="checkbox" name="show_online" ${bool(privacy,'show_online',true)?'checked':''}></label><label class="toggle-row"><span><strong>Allow messages</strong><br/>Members can start conversations with you.</span><input type="checkbox" name="allow_messages" ${bool(privacy,'allow_messages',true)?'checked':''}></label><label class="toggle-row"><span><strong>Allow follows</strong><br/>Members can follow your profile.</span><input type="checkbox" name="allow_follows" ${bool(privacy,'allow_follows',true)?'checked':''}></label></section><p id="status" class="status-line" role="status"></p><button class="comm-button primary" type="submit">SAVE SETTINGS</button></form></div></main>`;
 const form=document.querySelector<HTMLFormElement>('#settingsForm')!;const status=document.querySelector<HTMLElement>('#status')!;const saveState=document.querySelector<HTMLElement>('#saveState')!;
 form.addEventListener('submit',async e=>{e.preventDefault();saveState.textContent='SAVING';status.textContent='';const fd=new FormData(form);const notification_config={...notify,dm:fd.has('dm'),live:fd.has('live'),store:fd.has('store'),sports:fd.has('sports'),gaming:fd.has('gaming')};const privacy_config={...privacy,show_online:fd.has('show_online'),allow_messages:fd.has('allow_messages'),allow_follows:fd.has('allow_follows')};const {error:updateError}=await supabase.from('profiles').update({notification_config,privacy_config,online_status:fd.has('show_online')?'online':'hidden',updated_at:new Date().toISOString()}).eq('id',session.user.id);if(updateError){saveState.textContent='ERROR';status.textContent=updateError.message;return;}saveState.textContent='SAVED';status.textContent='Settings saved.';});
}