import { createClient } from '@supabase/supabase-js';

function json(res,status,body){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store, max-age=0');res.end(JSON.stringify(body));}
function env(...names){return names.map((name)=>process.env[name]).find((value)=>typeof value==='string'&&value.trim())?.trim();}
function bearer(req){const value=String(req.headers.authorization||'');return value.startsWith('Bearer ')?value.slice(7).trim():'';}
async function parseBody(req){if(req.body&&typeof req.body==='object')return req.body;if(typeof req.body==='string')return JSON.parse(req.body||'{}');const chunks=[];for await(const chunk of req)chunks.push(Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk));return JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}');}
function clients(token){const url=env('SUPABASE_URL','NEXT_PUBLIC_SUPABASE_URL','VITE_SUPABASE_URL');const publicKey=env('SUPABASE_PUBLISHABLE_KEY','NEXT_PUBLIC_SUPABASE_ANON_KEY','NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY','VITE_SUPABASE_ANON_KEY');const serviceKey=env('SUPABASE_SERVICE_ROLE_KEY');if(!url||!publicKey||!serviceKey)throw new Error('supabase_live_checkout_not_configured');return{auth:createClient(url,publicKey,{auth:{persistSession:false,autoRefreshToken:false}}),user:createClient(url,publicKey,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false,autoRefreshToken:false}}),admin:createClient(url,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}})};}
async function createStripeSession(secret,payload,userId,streamId,appUrl){const params=new URLSearchParams();const kind=String(payload.kind);const referenceId=String(payload.reference_id);const amount=Number(payload.amount_cents||0);const currency=String(payload.currency||'usd').toLowerCase();params.set('mode','payment');params.set('client_reference_id',userId);params.set('success_url',`${appUrl}/live.html?stream=${encodeURIComponent(streamId)}&payment=success&kind=${encodeURIComponent(kind)}&session_id={CHECKOUT_SESSION_ID}`);params.set('cancel_url',`${appUrl}/live.html?stream=${encodeURIComponent(streamId)}&payment=cancelled&kind=${encodeURIComponent(kind)}`);params.set('line_items[0][quantity]','1');params.set('line_items[0][price_data][currency]',currency);params.set('line_items[0][price_data][unit_amount]',String(amount));params.set('line_items[0][price_data][product_data][name]',kind==='tip'?'Rich Bizness Live Tip':'Rich Bizness Live Access');params.set('line_items[0][price_data][product_data][description]',kind==='tip'?'Support this Rich Bizness creator live.':'Unlock this Rich Bizness live room.');params.set('metadata[live_kind]',kind);params.set('metadata[reference_id]',referenceId);params.set('metadata[stream_id]',streamId);params.set('metadata[user_id]',userId);params.set('payment_intent_data[metadata][live_kind]',kind);params.set('payment_intent_data[metadata][reference_id]',referenceId);params.set('payment_intent_data[metadata][stream_id]',streamId);params.set('payment_intent_data[metadata][user_id]',userId);const response=await fetch('https://api.stripe.com/v1/checkout/sessions',{method:'POST',headers:{Authorization:`Bearer ${secret}`,'Content-Type':'application/x-www-form-urlencoded','Idempotency-Key':`rb-live-${kind}-${referenceId}`},body:params});const data=await response.json();if(!response.ok||!data?.id||!data?.url)throw new Error(data?.error?.message||`stripe_checkout_failed_${response.status}`);return data;}

export default async function handler(req,res){
 if(req.method==='GET')return json(res,200,{ok:true,service:'rich-bizness-live-checkout',kinds:['tip','purchase']});
 if(req.method!=='POST'){res.setHeader('Allow','GET, POST');return json(res,405,{ok:false,error:'method_not_allowed'});}
 const token=bearer(req);if(!token)return json(res,401,{ok:false,error:'missing_bearer_token'});
 const stripeSecret=env('STRIPE_SECRET_KEY');const appUrl=(env('APP_URL','VERCEL_PROJECT_PRODUCTION_URL')||'https://rich-bizness.com').replace(/\/$/,'');if(!stripeSecret)return json(res,503,{ok:false,error:'stripe_not_configured'});
 let body;try{body=await parseBody(req);}catch{return json(res,400,{ok:false,error:'invalid_json'});}
 const streamId=String(body?.streamId||'').trim();const kind=body?.kind==='tip'?'tip':body?.kind==='purchase'?'purchase':'';const requestedAmount=Number(body?.amountCents||0);if(!/^[0-9a-f-]{36}$/i.test(streamId)||!kind)return json(res,400,{ok:false,error:'stream_and_kind_required'});if(kind==='tip'&&(!Number.isFinite(requestedAmount)||requestedAmount<100||requestedAmount>100000))return json(res,400,{ok:false,error:'tip_amount_invalid'});
 let auth,userClient,admin;try{({auth,user:userClient,admin}=clients(token));}catch(error){return json(res,503,{ok:false,error:String(error?.message||error)});}
 const{data:userData,error:userError}=await auth.auth.getUser(token);const user=userData?.user;if(userError||!user)return json(res,401,{ok:false,error:'invalid_or_expired_session'});
 const{data:pending,error:pendingError}=await userClient.rpc('rb_live_action',{p_action:kind==='tip'?'tip':'purchase',p_stream_id:streamId,p_payload:kind==='tip'?{amount_cents:Math.round(requestedAmount)}:{}});if(pendingError||!pending?.ok)return json(res,400,{ok:false,error:pendingError?.message||'live_payment_contract_failed'});if(pending.already_open)return json(res,200,{ok:true,alreadyOpen:true,requiresPayment:false});
 const referenceId=String(pending.reference_id||'');const amount=Number(pending.amount_cents||0);const currency=String(pending.currency||'usd').toLowerCase();if(!referenceId)return json(res,500,{ok:false,error:'live_payment_reference_missing'});
 if(amount<=0){const freePaymentId=`free_live_${referenceId}`.slice(0,240);const{data:settlement,error:settlementError}=await admin.rpc('rb_settle_live_payment',{p_kind:kind,p_reference_id:referenceId,p_payment_intent_id:freePaymentId,p_checkout_session_id:null,p_amount_cents:0,p_metadata:{processor:'free-live-checkout',user_id:user.id,stream_id:streamId}});if(settlementError)return json(res,500,{ok:false,error:settlementError.message||'free_live_settlement_failed'});return json(res,200,{ok:true,requiresPayment:false,referenceId,settlement});}
 try{const session=await createStripeSession(stripeSecret,{...pending,kind,reference_id:referenceId,amount_cents:amount,currency},user.id,streamId,appUrl);return json(res,200,{ok:true,requiresPayment:true,kind,referenceId,amountCents:amount,currency,sessionId:session.id,checkoutUrl:session.url});}catch(error){return json(res,502,{ok:false,error:'stripe_checkout_session_failed',message:String(error?.message||error).slice(0,300),referenceId});}
}
