update public.games
set is_playable=true,runtime_status='production_ready',runtime_key='portal-dash-v1',engine_type='canvas2d',module_path='/src/pages/gaming/portal-dash.ts',version='1.0.0',play_url='/games/portal-dash/',is_tournament_enabled=true,is_meta_enabled=true,controls='{"keyboard":["arrows","wasd","space","e"],"touch":true,"pointer":true}'::jsonb,capabilities='["solo","offline","local","realtime_multiplayer","ranked","tournaments","xp","leaderboards","cloud_progress","meta_sync"]'::jsonb,save_schema='{"version":1,"fields":["best","xp","level","wins","tokens","unlocked"]}'::jsonb,netcode_config='{"provider":"supabase_realtime","mode":"score_race","presence":true}'::jsonb,mobile_config='{"orientation":"adaptive","touch_controls":true,"safe_area":true,"reduced_motion":true}'::jsonb,metadata=coalesce(metadata,'{}'::jsonb)||'{"runtime":"portal-dash-v1","module_owner":"/games/portal-dash/","features":["phase_movement","portal_chains","hazards","boss_gates","campaign","endless","local","realtime","xp","tournaments"]}'::jsonb,updated_at=now()
where id='14a071ea-a48f-44cf-a69d-c521bab0a101';

update public.game_runtime_manifests set is_active=false,updated_at=now() where game_id='14a071ea-a48f-44cf-a69d-c521bab0a101';
insert into public.game_runtime_manifests(game_id,version,engine_type,entry_module,asset_manifest,controls,gameplay_rules,scoring_rules,save_schema,network_schema,mobile_config,required_env,checksum,is_active)
values('14a071ea-a48f-44cf-a69d-c521bab0a101','1.0.0','canvas2d','/src/pages/gaming/portal-dash.ts','{"styles":["/src/pages/gaming/portal-dash.css"]}'::jsonb,'{"keyboard":["arrows","wasd","space","e"],"touch":true,"pointer":true}'::jsonb,'{"modes":["campaign","endless","local","online"],"gates":12,"difficulty":[1,2,3]}'::jsonb,'{"gate_chain":300,"boss_bonus":2200,"combo_max":20}'::jsonb,'{"version":1,"storage":"local_and_cloud"}'::jsonb,'{"provider":"supabase_realtime","channel":"portal-dash","presence":true}'::jsonb,'{"responsive":true,"safe_area":true,"reduced_motion":true}'::jsonb,'[]'::jsonb,'portal-dash-v1',true);

insert into public.route_registry(route_key,route_path,page_type,section,auth_mode,canonical_file,rewrite_target,nav_label,is_home,is_enabled,metadata)
values('game_portal_dash','/games/portal-dash/','game','gaming','public','apps/web/portal-dash.html','/portal-dash','Portal Dash',false,true,'{"game_slug":"portal-dash","runtime":"production_ready"}'::jsonb)
on conflict(route_key) do update set route_path=excluded.route_path,page_type=excluded.page_type,section=excluded.section,auth_mode=excluded.auth_mode,canonical_file=excluded.canonical_file,rewrite_target=excluded.rewrite_target,nav_label=excluded.nav_label,is_enabled=true,metadata=excluded.metadata,updated_at=now();