insert into public.avatar_character_presets (preset_key,title,aura,outfit,motion,config,is_active)
values
('street_king_hd','Street King HD','Emerald Gold','Luxury street armor','Boss Street Idle',jsonb_build_object('body_type','male','build','heroic','voice','deep-boss','hair','fade-crown','smoke','heavy','style','gta-street','detail','ultra'),true),
('street_queen_hd','Street Queen HD','Diamond Mist','Diamond city fit','Elite City Walk',jsonb_build_object('body_type','female','build','heroic','voice','elite','hair','long-wave','smoke','cinematic','style','gta-street','detail','ultra'),true),
('smoke_lord_elite','Smoke Lord Elite','Neon Phantom','Void smoke tactical','Heavy Smoke Idle',jsonb_build_object('body_type','male','build','athletic','voice','dark-boss','hair','shadow-crown','smoke','maximum','style','crime-boss','detail','ultra'),true),
('golden_enforcer','Golden Enforcer','Emerald Gold','Gold tactical suit','Combat Ready',jsonb_build_object('body_type','male','build','heroic','voice','command','hair','clean-cut','smoke','low','style','elite-enforcer','detail','ultra'),true),
('diamond_vixen','Diamond Vixen','Diamond Mist','Diamond combat couture','Power Stance',jsonb_build_object('body_type','female','build','athletic','voice','command','hair','long-wave','smoke','mist','style','elite-villain','detail','ultra'),true),
('neon_ronin','Neon Ronin','Neon Phantom','Cyber street ronin','Ronin Combat Flow',jsonb_build_object('body_type','male','build','stylized','voice','calm','hair','spiked','smoke','energy','style','future-street','detail','ultra'),true)
on conflict (preset_key) do update set title=excluded.title,aura=excluded.aura,outfit=excluded.outfit,motion=excluded.motion,config=excluded.config,is_active=true,updated_at=now();

insert into public.avatar_animation_clips (clip_key,title,animation_url,animation_format,state_group,loop_mode,blend_in_ms,blend_out_ms,root_motion,speed_multiplier,compatible_rigs,event_markers,metadata,is_active)
values
('boss_street_idle','Boss Street Idle','procedural://avatar/boss-street-idle.glb','glb','idle','repeat',180,220,false,1.0,array['rb-humanoid'],jsonb_build_array(),jsonb_build_object('quality','elite','style','gta-street','runtime','procedural'),true),
('elite_city_walk','Elite City Walk','procedural://avatar/elite-city-walk.glb','glb','locomotion','repeat',120,180,true,1.0,array['rb-humanoid'],jsonb_build_array(jsonb_build_object('event','footstep','time',0.25),jsonb_build_object('event','footstep','time',0.75)),jsonb_build_object('quality','elite','runtime','procedural'),true),
('heavy_smoke_idle','Heavy Smoke Idle','procedural://avatar/heavy-smoke-idle.glb','glb','smoke','repeat',220,260,false,0.9,array['rb-humanoid'],jsonb_build_array(jsonb_build_object('event','smoke_pulse','time',0.5)),jsonb_build_object('quality','elite','fx','volumetric-smoke','runtime','procedural'),true),
('combat_ready','Combat Ready','procedural://avatar/combat-ready.glb','glb','combat','repeat',100,140,false,1.0,array['rb-humanoid'],jsonb_build_array(),jsonb_build_object('quality','elite','runtime','procedural'),true),
('power_stance','Power Stance','procedural://avatar/power-stance.glb','glb','emote','repeat',160,180,false,1.0,array['rb-humanoid'],jsonb_build_array(jsonb_build_object('event','aura_burst','time',0.42)),jsonb_build_object('quality','elite','fx','aura','runtime','procedural'),true),
('ronin_combat_flow','Ronin Combat Flow','procedural://avatar/ronin-combat-flow.glb','glb','combat','repeat',90,120,true,1.08,array['rb-humanoid'],jsonb_build_array(jsonb_build_object('event','weapon_trail','time',0.33),jsonb_build_object('event','weapon_trail','time',0.72)),jsonb_build_object('quality','elite','style','ronin','runtime','procedural'),true),
('boss_vehicle_pose','Boss Vehicle Pose','procedural://avatar/boss-vehicle-pose.glb','glb','vehicle','repeat',180,220,false,1.0,array['rb-humanoid'],jsonb_build_array(),jsonb_build_object('quality','elite','style','gta-vehicle','runtime','procedural'),true)
on conflict (clip_key) do update set title=excluded.title,animation_url=excluded.animation_url,animation_format=excluded.animation_format,state_group=excluded.state_group,loop_mode=excluded.loop_mode,blend_in_ms=excluded.blend_in_ms,blend_out_ms=excluded.blend_out_ms,root_motion=excluded.root_motion,speed_multiplier=excluded.speed_multiplier,compatible_rigs=excluded.compatible_rigs,event_markers=excluded.event_markers,metadata=excluded.metadata,is_active=true,updated_at=now();
