create table if not exists public.watch_progress (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  source_type text not null check (source_type in ('live_recording','feed_video','game_clip','sports_clip','sports_replay')),
  source_id uuid not null,
  position_seconds integer not null default 0 check (position_seconds >= 0),
  duration_seconds integer not null default 0 check (duration_seconds >= 0),
  completed boolean not null default false,
  last_watched_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  unique(user_id,source_type,source_id)
);
create table if not exists public.watch_likes (id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,source_type text not null check (source_type in ('live_recording','feed_video','game_clip','sports_clip','sports_replay')),source_id uuid not null,created_at timestamptz not null default now(),unique(user_id,source_type,source_id));
create table if not exists public.watch_comments (id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,source_type text not null check (source_type in ('live_recording','feed_video','game_clip','sports_clip','sports_replay')),source_id uuid not null,body text not null check (char_length(trim(body)) between 1 and 2000),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.watchlist_items (id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,source_type text not null check (source_type in ('live_recording','feed_video','game_clip','sports_clip','sports_replay')),source_id uuid not null,created_at timestamptz not null default now(),unique(user_id,source_type,source_id));
alter table public.watch_progress enable row level security; alter table public.watch_likes enable row level security; alter table public.watch_comments enable row level security; alter table public.watchlist_items enable row level security;
create policy watch_progress_owner_all on public.watch_progress for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy watch_likes_owner_all on public.watch_likes for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy watch_comments_read on public.watch_comments for select to authenticated using (true);
create policy watch_comments_owner_insert on public.watch_comments for insert to authenticated with check (user_id=auth.uid());
create policy watch_comments_owner_update on public.watch_comments for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy watch_comments_owner_delete on public.watch_comments for delete to authenticated using (user_id=auth.uid());
create policy watchlist_owner_all on public.watchlist_items for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
create index if not exists watch_progress_user_recent_idx on public.watch_progress(user_id,last_watched_at desc); create index if not exists watch_comments_source_recent_idx on public.watch_comments(source_type,source_id,created_at desc); create index if not exists watch_likes_source_idx on public.watch_likes(source_type,source_id); create index if not exists watchlist_user_recent_idx on public.watchlist_items(user_id,created_at desc);
create or replace function public.rb_watch_feed(p_limit integer default 60) returns table(source_type text,source_id uuid,creator_id uuid,creator_name text,title text,description text,media_url text,thumbnail_url text,duration_seconds integer,view_count integer,created_at timestamptz,section text) language sql security invoker set search_path=public as $$ select * from (select 'live_recording'::text,r.id,coalesce(r.creator_id,r.user_id),coalesce(p.display_name,p.username,'Rich Creator'),coalesce(r.title,'Live Replay'),coalesce(r.description,''),r.recording_url,coalesce(r.thumbnail_url,r.cover_url),coalesce(r.duration_seconds,0),coalesce(r.view_count,0),r.created_at,'live'::text from public.live_recordings r left join public.profiles p on p.id=coalesce(r.creator_id,r.user_id) where r.recording_url is not null and coalesce(r.visibility,'public')='public' union all select 'feed_video',f.id,f.user_id,coalesce(f.display_name,f.username,'Rich Creator'),coalesce(f.title,'Rich Video'),coalesce(f.body,''),coalesce(f.media_url,f.file_url),coalesce(f.thumbnail_url,f.cover_url),0,coalesce(f.view_count,0),f.created_at,coalesce(f.section,'feed') from public.feed_posts f where coalesce(f.media_url,f.file_url) is not null and (f.media_type like 'video%' or f.post_type='video') and coalesce(f.visibility,'public')='public' union all select 'game_clip',g.id,g.user_id,coalesce(g.display_name,g.username,'Rich Gamer'),coalesce(g.title,'Game Clip'),coalesce(g.caption,''),g.clip_url,g.thumbnail_url,0,coalesce(g.view_count,0),g.created_at,'gaming' from public.game_clips g where g.clip_url is not null union all select 'sports_clip',s.id,s.user_id,coalesce(s.display_name,s.username,'Rich Sports'),coalesce(s.title,'Sports Highlight'),coalesce(s.caption,''),s.file_url,s.thumbnail_url,0,coalesce(s.views,0),s.created_at,'sports' from public.sports_uploads s where s.file_url is not null union all select 'sports_replay',b.id,b.user_id,coalesce(b.display_name,b.username,'Rich Sports'),b.title,coalesce(b.description,''),coalesce(b.replay_url,b.stream_url),b.cover_url,0,coalesce(b.viewer_count,0),b.created_at,'sports' from public.sports_broadcasts b where coalesce(b.replay_url,b.stream_url) is not null and b.status in ('live','ended')) q order by created_at desc limit greatest(1,least(coalesce(p_limit,60),100)); $$;
grant execute on function public.rb_watch_feed(integer) to authenticated; revoke execute on function public.rb_watch_feed(integer) from anon;
do $$ begin alter publication supabase_realtime add table public.watch_comments; exception when duplicate_object then null; end $$;