create unique index if not exists store_cart_items_user_product_unique on public.store_cart_items(user_id,product_id);
create unique index if not exists product_likes_user_product_unique on public.product_likes(user_id,product_id);
create unique index if not exists user_product_unlocks_user_product_unique on public.user_product_unlocks(user_id,product_id) where product_id is not null;
create index if not exists products_public_status_featured_created_idx on public.products(is_public,status,is_featured desc,created_at desc);
create index if not exists products_lane_created_idx on public.products(product_type,is_digital,is_local,created_at desc);
create index if not exists store_cart_items_user_created_idx on public.store_cart_items(user_id,created_at);
create index if not exists store_orders_buyer_created_idx on public.store_orders(buyer_id,created_at desc);
create index if not exists store_orders_seller_status_created_idx on public.store_orders(seller_id,payment_status,order_status,created_at desc);
create index if not exists store_comments_product_created_idx on public.store_comments(product_id,created_at desc);
create index if not exists product_views_product_created_idx on public.product_views(product_id,created_at desc);
insert into public.system_health_checks(service,status,message,metadata) values ('store-owner','ok','Step 27 Store and checkout interaction states hardened',jsonb_build_object('step',27,'owner','store','payment_owner','server-required','checked_at',now()));