update public.games
set play_url='/games/empire-builder/', runtime_key='empire-builder', engine_type='vite-typescript', module_path='/games/empire-builder/', version='1.0.0', is_playable=true, runtime_status='production_ready', is_tournament_enabled=true, is_active=true, controls=jsonb_build_object('keyboard',jsonb_build_array('Enter end turn','U upgrade','A attack'),'touch',true), capabilities=jsonb_build_object('solo',true,'offline',true,'local_multiplayer',true,'online_multiplayer',true,'xp',true,'scores',true,'rooms',true,'persistent_progress',true,'tournaments',true,'ai_rivals',true,'economy',true,'city_building',true), save_schema=jsonb_build_object('version',1,'fields',jsonb_build_array('board','gold','food','ore','power','army','turn','score')), netcode_config=jsonb_build_object('transport','supabase_realtime','sync','state_moves','max_players',2), anti_cheat_config=jsonb_build_object('server_scores',true,'move_audit',true), mobile_config=jsonb_build_object('touch',true,'safe_area',true,'responsive_grid',true), metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('production_runtime',true,'advanced_strategy',true,'economy',true,'ai_rivals',true,'empire_grid',true), updated_at=now()
where slug='empire-builder';

insert into public.game_runtime_manifests (game_id,version,engine_type,entry_module,asset_manifest,controls,gameplay_rules,scoring_rules,save_schema,network_schema,mobile_config,required_env,checksum,is_active,updated_at)
select id,'1.0.0','vite-typescript','/src/pages/games/empire-builder.page.ts','{}'::jsonb,jsonb_build_object('keyboard',true,'touch',true),jsonb_build_object('turn_based',true,'economy',true,'territory',true,'ai_rivals',true),jsonb_build_object('victory_bonus',2500,'turn_bonus',120,'building_score',true),jsonb_build_object('local_storage',true,'supabase_progress',true),jsonb_build_object('realtime_rooms',true,'state_sync',true),jsonb_build_object('responsive',true,'safe_area',true),'[]'::jsonb,'empire-builder-v1',true,now()
from public.games where slug='empire-builder'
on conflict (game_id,version) do update set entry_module=excluded.entry_module,controls=excluded.controls,gameplay_rules=excluded.gameplay_rules,scoring_rules=excluded.scoring_rules,save_schema=excluded.save_schema,network_schema=excluded.network_schema,mobile_config=excluded.mobile_config,checksum=excluded.checksum,is_active=true,updated_at=now();

insert into public.route_registry (route_key,route_path,page_type,section,auth_mode,canonical_file,rewrite_target,nav_label,is_home,is_enabled,metadata,updated_at)
values ('game_empire_builder','/games/empire-builder/','game','gaming','public','empire-builder.html','/empire-builder','Empire Builder',false,true,jsonb_build_object('game_slug','empire-builder','production_runtime',true),now())
on conflict (route_key) do update set route_path=excluded.route_path,page_type=excluded.page_type,section=excluded.section,auth_mode=excluded.auth_mode,canonical_file=excluded.canonical_file,rewrite_target=excluded.rewrite_target,nav_label=excluded.nav_label,is_enabled=true,metadata=excluded.metadata,updated_at=now();