create or replace function public.rb_media_universe_snapshot()
returns jsonb
language sql
security definer
set search_path=public
as $$
with me as (select auth.uid() uid),
profile as (select to_jsonb(p.*) j from profiles p,me where p.id=me.uid),
live_rows as (
 select coalesce(jsonb_agg(to_jsonb(x) order by x.is_featured desc,x.started_at desc nulls last,x.created_at desc),'[]'::jsonb) j
 from (select id,creator_id,slug,title,description,category,status,status_label,access_type,price_cents,currency,livekit_room_name,thumbnail_url,cover_url,recording_url,viewer_count,peak_viewers,total_chat_messages,total_reactions,total_revenue_cents,is_chat_enabled,is_cohost_enabled,is_vip_enabled,is_featured,started_at,ended_at,stream_protocol,latency_mode,recording_enabled,transcription_enabled,layout_config,quality_config,created_at from live_streams where lower(coalesce(status,'active')) not in ('deleted','hidden') limit 40) x
),
recordings as (select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc),'[]'::jsonb) j from (select id,stream_id,creator_id,title,description,recording_url,thumbnail_url,cover_url,duration_seconds,status,visibility,view_count,created_at from live_recordings where coalesce(visibility,'public')='public' limit 30) x),
tracks as (select coalesce(jsonb_agg(to_jsonb(x) order by x.is_featured desc,x.created_at desc),'[]'::jsonb) j from (select id,coalesce(artist_user_id,user_id) creator_id,username,display_name,title,description,coalesce(audio_url,file_url) audio_url,cover_url,genre,mood,duration_seconds,color_theme,visualizer_style,play_count,like_count,comment_count,is_explicit,is_featured,created_at from music_tracks where coalesce(is_published,true)=true and coalesce(visibility,'public')='public' limit 60) x),
podcasts as (select coalesce(jsonb_agg(to_jsonb(x) order by x.is_featured desc,x.created_at desc),'[]'::jsonb) j from (select e.id,e.show_id,coalesce(e.creator_id,e.user_id) creator_id,e.display_name,e.title,e.description,coalesce(e.audio_url,e.file_url) audio_url,e.cover_url,e.episode_number,e.season_number,e.duration_seconds,e.play_count,e.like_count,e.comment_count,e.is_explicit,e.is_featured,e.created_at,s.title show_title,s.category,s.subscriber_count from podcast_episodes e left join podcast_shows s on s.id=e.show_id where coalesce(e.is_published,true)=true and coalesce(e.visibility,'public')='public' limit 60) x),
radio as (select coalesce(jsonb_agg(to_jsonb(x) order by x.is_featured desc,x.listener_count desc,x.created_at desc),'[]'::jsonb) j from (select id,user_id creator_id,display_name,station_name,station_tag,description,stream_url,cover_url,genre,mood,is_live,is_featured,listener_count,peak_listeners,like_count,play_count,color_theme,visualizer_style,created_at from radio_stations where coalesce(is_public,true)=true limit 40) x),
playlists_row as (select coalesce(jsonb_agg(to_jsonb(x) order by x.is_featured desc,x.created_at desc),'[]'::jsonb) j from (select id,user_id,display_name,title,description,cover_url,visibility,color_theme,track_count,like_count,play_count,is_featured,created_at from playlists where coalesce(visibility,'public')='public' limit 30) x),
watch_state as (select jsonb_build_object('progress',coalesce((select jsonb_agg(to_jsonb(w) order by w.last_watched_at desc) from watch_progress w,me where w.user_id=me.uid),'[]'::jsonb),'likes',coalesce((select jsonb_agg(to_jsonb(w)) from watch_likes w,me where w.user_id=me.uid),'[]'::jsonb),'watchlist',coalesce((select jsonb_agg(to_jsonb(w) order by w.created_at desc) from watchlist_items w,me where w.user_id=me.uid),'[]'::jsonb)) j),
gaming as (select jsonb_build_object('games',coalesce((select jsonb_agg(to_jsonb(g) order by g.is_featured desc,g.active_players desc,g.title) from games g where g.is_active=true),'[]'::jsonb),'categories',coalesce((select jsonb_agg(to_jsonb(c) order by c.sort_order,c.title) from game_categories c where c.is_active=true),'[]'::jsonb),'clips',coalesce((select jsonb_agg(to_jsonb(c) order by c.is_featured desc,c.created_at desc) from game_clips c limit 40),'[]'::jsonb),'tournaments',coalesce((select jsonb_agg(to_jsonb(t) order by t.is_featured desc,t.starts_at asc nulls last) from game_tournaments t where lower(coalesce(t.status,'active')) not in ('deleted','cancelled') limit 30),'[]'::jsonb),'missions',coalesce((select jsonb_agg(to_jsonb(m) order by m.created_at desc) from game_missions m where m.is_active=true limit 30),'[]'::jsonb),'progress',coalesce((select jsonb_agg(to_jsonb(p) order by p.last_played_at desc) from game_player_progress p,me where p.user_id=me.uid),'[]'::jsonb),'rewards',coalesce((select jsonb_agg(to_jsonb(r) order by r.created_at desc) from game_rewards r,me where r.user_id=me.uid limit 30),'[]'::jsonb),'rooms',coalesce((select jsonb_agg(to_jsonb(r) order by r.updated_at desc) from game_rooms r where lower(coalesce(r.status,'open')) in ('open','waiting','active') limit 30),'[]'::jsonb)) j)
select jsonb_build_object('profile',coalesce((select j from profile),'{}'::jsonb),'live',coalesce((select j from live_rows),'[]'::jsonb),'recordings',coalesce((select j from recordings),'[]'::jsonb),'tracks',coalesce((select j from tracks),'[]'::jsonb),'podcasts',coalesce((select j from podcasts),'[]'::jsonb),'radio',coalesce((select j from radio),'[]'::jsonb),'playlists',coalesce((select j from playlists_row),'[]'::jsonb),'watch_state',coalesce((select j from watch_state),'{}'::jsonb),'gaming',coalesce((select j from gaming),'{}'::jsonb),'generated_at',now());
$$;
revoke all on function public.rb_media_universe_snapshot() from public,anon;
grant execute on function public.rb_media_universe_snapshot() to authenticated;
create index if not exists idx_live_streams_status_featured on public.live_streams(status,is_featured,started_at desc);
create index if not exists idx_music_tracks_published_featured on public.music_tracks(is_published,is_featured,created_at desc);
create index if not exists idx_podcast_episodes_published_featured on public.podcast_episodes(is_published,is_featured,created_at desc);
create index if not exists idx_radio_stations_public_featured on public.radio_stations(is_public,is_featured,listener_count desc);
create index if not exists idx_games_active_featured on public.games(is_active,is_featured,active_players desc);
create index if not exists idx_game_tournaments_status_starts on public.game_tournaments(status,starts_at);