insert into public.avatar_controller_profiles(controller_key,title,input_scheme,move_speed,sprint_speed,jump_force,gravity,turn_speed,acceleration,deceleration,camera_mode,camera_config,touch_config,keyboard_config,gamepad_config,animation_state_map,metadata,is_active)
values('rich-free-roam','Rich Free Roam','hybrid',4.8,8.2,6.8,18,8,20,16,'third_person',jsonb_build_object('distance',5.4,'height',2.2,'fov',48),jsonb_build_object('joystick',true,'jump',true,'sprint',true,'emote',true),jsonb_build_object('forward','KeyW','back','KeyS','left','KeyA','right','KeyD','jump','Space','sprint','ShiftLeft'),jsonb_build_object('move','left_stick','look','right_stick','jump','button_south','sprint','left_stick_press'),jsonb_build_object('idle','boss-idle','walk','boss-walk','run','boss-run','jump','boss-jump','power','power-up','dance','dance-flex','smoke','smoke-burst'),jsonb_build_object('version','1.0.0','engine','three-procedural'),true)
on conflict(controller_key) do update set title=excluded.title,input_scheme=excluded.input_scheme,move_speed=excluded.move_speed,sprint_speed=excluded.sprint_speed,jump_force=excluded.jump_force,gravity=excluded.gravity,turn_speed=excluded.turn_speed,acceleration=excluded.acceleration,deceleration=excluded.deceleration,camera_mode=excluded.camera_mode,camera_config=excluded.camera_config,touch_config=excluded.touch_config,keyboard_config=excluded.keyboard_config,gamepad_config=excluded.gamepad_config,animation_state_map=excluded.animation_state_map,metadata=excluded.metadata,is_active=true,updated_at=now();
insert into public.avatar_animation_clips(clip_key,title,animation_url,animation_format,state_group,loop_mode,blend_in_ms,blend_out_ms,root_motion,speed_multiplier,compatible_rigs,event_markers,metadata,is_active) values
('boss-idle','Boss Idle','procedural://boss-idle','glb','idle','repeat',180,180,false,1,array['rich-humanoid'],jsonb_build_array(jsonb_build_object('time',2.4,'event','smoke-puff')),jsonb_build_object('engine','three-procedural'),true),
('boss-walk','Boss Walk','procedural://boss-walk','glb','locomotion','repeat',140,160,true,1,array['rich-humanoid'],jsonb_build_array(jsonb_build_object('time',0.2,'event','step'),jsonb_build_object('time',0.7,'event','step')),jsonb_build_object('engine','three-procedural'),true),
('boss-run','Boss Run','procedural://boss-run','glb','locomotion','repeat',110,140,true,1.35,array['rich-humanoid'],jsonb_build_array(jsonb_build_object('time',0.15,'event','step'),jsonb_build_object('time',0.55,'event','step')),jsonb_build_object('engine','three-procedural'),true),
('boss-jump','Boss Jump','procedural://boss-jump','glb','jump','once',90,180,true,1,array['rich-humanoid'],jsonb_build_array(jsonb_build_object('time',0.05,'event','launch'),jsonb_build_object('time',0.85,'event','land')),jsonb_build_object('engine','three-procedural'),true),
('power-up','Power Up','procedural://power-up','glb','cinematic','once',120,220,false,1,array['rich-humanoid'],jsonb_build_array(jsonb_build_object('time',0.4,'event','aura-burst')),jsonb_build_object('engine','three-procedural'),true),
('dance-flex','Dance Flex','procedural://dance-flex','glb','emote','repeat',180,180,false,1,array['rich-humanoid'],'[]'::jsonb,jsonb_build_object('engine','three-procedural'),true),
('smoke-burst','Smoke Burst','procedural://smoke-burst','glb','smoke','once',80,160,false,1,array['rich-humanoid'],jsonb_build_array(jsonb_build_object('time',0.1,'event','smoke-burst')),jsonb_build_object('engine','three-procedural'),true)
on conflict(clip_key) do update set title=excluded.title,animation_url=excluded.animation_url,animation_format=excluded.animation_format,state_group=excluded.state_group,loop_mode=excluded.loop_mode,blend_in_ms=excluded.blend_in_ms,blend_out_ms=excluded.blend_out_ms,root_motion=excluded.root_motion,speed_multiplier=excluded.speed_multiplier,compatible_rigs=excluded.compatible_rigs,event_markers=excluded.event_markers,metadata=excluded.metadata,is_active=true,updated_at=now();
create or replace function public.rb_sync_avatar_motion(p_position jsonb,p_rotation jsonb,p_velocity jsonb,p_locomotion_state text,p_action_state text default 'none',p_active_clip_key text default 'boss-idle',p_input_state jsonb default '{}'::jsonb,p_sequence integer default 0) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_user uuid:=auth.uid(); begin if v_user is null then raise exception 'Authentication required'; end if; insert into public.avatar_motion_state(user_id,position,rotation,velocity,locomotion_state,action_state,active_clip_key,grounded,in_vehicle,input_state,sequence,client_timestamp,server_timestamp,metadata) values(v_user,coalesce(p_position,'{"x":0,"y":0,"z":0}'::jsonb),coalesce(p_rotation,'{"x":0,"y":0,"z":0,"w":1}'::jsonb),coalesce(p_velocity,'{"x":0,"y":0,"z":0}'::jsonb),coalesce(nullif(trim(p_locomotion_state),''),'idle'),coalesce(nullif(trim(p_action_state),''),'none'),coalesce(nullif(trim(p_active_clip_key),''),'boss-idle'),true,false,coalesce(p_input_state,'{}'::jsonb),greatest(coalesce(p_sequence,0),0),now(),now(),jsonb_build_object('source','avatar-studio','engine','three-procedural')) on conflict(user_id) do update set position=excluded.position,rotation=excluded.rotation,velocity=excluded.velocity,locomotion_state=excluded.locomotion_state,action_state=excluded.action_state,active_clip_key=excluded.active_clip_key,input_state=excluded.input_state,sequence=greatest(public.avatar_motion_state.sequence+1,excluded.sequence),client_timestamp=excluded.client_timestamp,server_timestamp=now(),metadata=excluded.metadata; update public.meta_avatars set position=coalesce(p_position,position),animation_state=jsonb_build_object('state',coalesce(nullif(trim(p_locomotion_state),''),'idle'),'action',coalesce(nullif(trim(p_action_state),''),'none'),'clip',coalesce(nullif(trim(p_active_clip_key),''),'boss-idle')),is_controllable=true,is_realistic_3d=true,updated_at=now() where user_id=v_user; return jsonb_build_object('saved',true,'sequence',greatest(coalesce(p_sequence,0),0),'server_timestamp',now()); end $$;
grant execute on function public.rb_sync_avatar_motion(jsonb,jsonb,jsonb,text,text,text,jsonb,integer) to authenticated; revoke execute on function public.rb_sync_avatar_motion(jsonb,jsonb,jsonb,text,text,text,jsonb,integer) from anon;
do $$ begin alter publication supabase_realtime add table public.avatar_motion_state; exception when duplicate_object then null; end $$;