import { supabase } from '../../core/supabase/client';
import '../../styles/broadcast-cinema-podcast.css';

type Row=Record<string,any>;
const esc=(v:any)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c));
const key=(r:Row)=>`${r.source_type}:${r.source_id}`;
const pct=(p:Row|undefined)=>p&&p.duration_seconds?Math.min(100,Math.round(Number(p.position_seconds)/Number(p.duration_seconds)*100)):0;

export async function mount():Promise<void>{
 const root=document.querySelector<HTMLElement>('#app');if(!root)throw new Error('Missing #app mount');
 const {data:{session}}=await supabase.auth.getSession();if(!session){location.replace('/tap-in.html?next=%2Fwatch.html');return;}
 const {data,error}=await supabase.rpc('rb_live_watch_podcast_snapshot',{});if(error)throw error;
 const snap=(data??{}) as Row;const items=(snap.watch_feed??[]) as Row[];const progress=new Map(((snap.watch_progress??[]) as Row[]).map(p=>[`${p.source_type}:${p.source_id}`,p]));const liked=new Set(((snap.watch_likes??[]) as Row[]).map(x=>`${x.source_type}:${x.source_id}`));const saved=new Set(((snap.watchlist??[]) as Row[]).map(x=>`${x.source_type}:${x.source_id}`));let lane='featured';let active=items[0]??null;let channel:any=null;let timer:number|undefined;
 const continueRows=items.filter(i=>{const p=progress.get(key(i));return p&&Number(p.position_seconds)>0&&!p.completed;});
 root.innerHTML=`<main class="media-ultimate"><div class="media-ultimate__wrap"><header class="media-ultimate__head"><a href="/portal.html">←</a><div><p>RICH BIZNESS CINEMA NETWORK</p><h1>WATCH UNIVERSE</h1></div><span class="media-ultimate__status">4K READY</span></header><section id="watchHero" class="media-ultimate__hero">${active?hero(active):'<div class="media-ultimate__empty">No cinema content available.</div>'}</section><section class="media-ultimate__metrics"><article><small>GLOBAL LIBRARY</small><strong>${items.length}</strong></article><article><small>CONTINUE WATCHING</small><strong>${continueRows.length}</strong></article><article><small>MY LIST</small><strong>${saved.size}</strong></article><article><small>COMPLETED</small><strong>${[...progress.values()].filter(p=>p.completed).length}</strong></article></section><nav class="media-ultimate__tabs">${[['featured','FEATURED'],['continue','CONTINUE'],['live','LIVE REPLAYS'],['gaming','GAMING'],['sports','SPORTS'],['feed','CREATOR FEED'],['saved','MY LIST']].map(([v,l],i)=>`<button class="${i===0?'active':''}" data-lane="${v}">${l}</button>`).join('')}</nav><section class="media-ultimate__section"><header><div><h3 id="watchLaneTitle">Featured Cinema</h3><p>Replays, creator films, game clips, sports moments and saved universes.</p></div></header><div id="watchRail" class="cinema-rail"></div></section><section class="media-ultimate__split"><article class="media-ultimate__panel"><header><h4>NOW WATCHING INTELLIGENCE</h4></header><div id="watchDetail" class="media-ultimate__list"></div></article><article class="media-ultimate__panel"><header><h4>RICH REACTIONS</h4></header><div id="watchComments" class="media-ultimate__chat"></div><form id="watchCommentForm" class="media-ultimate__form"><input id="watchCommentInput" maxlength="2000" placeholder="React to this drop..."><button class="media-ultimate__btn primary">POST</button></form></article></section><section class="media-ultimate__section"><header><div><h3>Because You Watch</h3><p>More from the sections and creators already in your history.</p></div></header><div id="recommendGrid" class="media-ultimate__grid"></div></section></div></main>`;
 const rail=document.querySelector<HTMLElement>('#watchRail')!;const detail=document.querySelector<HTMLElement>('#watchDetail')!;const comments=document.querySelector<HTMLElement>('#watchComments')!;const recs=document.querySelector<HTMLElement>('#recommendGrid')!;
 const visible=()=>lane==='continue'?continueRows:lane==='saved'?items.filter(i=>saved.has(key(i))):lane==='featured'?items:items.filter(i=>String(i.section)===lane);
 const card=(i:Row)=>`<article class="media-ultimate__card" data-key="${key(i)}"><img src="${esc(i.thumbnail_url||'/images/brand/IMG_5997.png')}" alt=""><div class="watch-progress"><span style="width:${pct(progress.get(key(i)))}%"></span></div><div class="media-ultimate__card-body"><h4>${esc(i.title||'Rich Cinema')}</h4><p>${esc(i.creator_name||'Rich Creator')} · ${Number(i.view_count??0).toLocaleString()} views</p><div class="media-ultimate__meta"><span>${esc((i.section||'WATCH').toUpperCase())}</span><span>${progress.get(key(i))?.completed?'COMPLETED':pct(progress.get(key(i)))+'%'}</span></div></div></article>`;
 const bindCards=(host:HTMLElement)=>host.querySelectorAll<HTMLElement>('[data-key]').forEach(el=>el.onclick=()=>{const i=items.find(x=>key(x)===el.dataset.key);if(i)void open(i);});
 const render=()=>{const rows=visible();rail.innerHTML=rows.map(card).join('')||'<div class="media-ultimate__empty">Nothing in this lane yet.</div>';bindCards(rail);const basis=active?.section?items.filter(i=>i.section===active!.section&&key(i)!==key(active!)):items.slice(1);recs.innerHTML=basis.slice(0,8).map(card).join('')||'<div class="media-ultimate__empty">Recommendations build as you watch.</div>';bindCards(recs);};
 const loadComments=async()=>{if(!active)return;const {data}=await supabase.from('watch_comments').select('id,body,created_at,profiles(display_name,username)').eq('source_type',active.source_type).eq('source_id',active.source_id).order('created_at',{ascending:true}).limit(120);comments.innerHTML=(data??[]).map((c:any)=>`<article><p>${esc(c.body)}</p><small>${esc(c.profiles?.display_name||c.profiles?.username||'Rich Viewer')}</small></article>`).join('')||'<div class="media-ultimate__empty">Start the conversation.</div>';};
 const sync=async(video:HTMLVideoElement,force=false)=>{if(!active||(!force&&video.currentTime<1))return;const row={user_id:session.user.id,source_type:active.source_type,source_id:active.source_id,position_seconds:Math.floor(video.currentTime),duration_seconds:Number.isFinite(video.duration)?Math.floor(video.duration):Number(active.duration_seconds??0),completed:video.duration>0&&video.currentTime/video.duration>.92,last_watched_at:new Date().toISOString()};await supabase.from('watch_progress').upsert(row,{onConflict:'user_id,source_type,source_id'});progress.set(key(active),row);render();};
 const open=async(i:Row)=>{active=i;document.querySelector<HTMLElement>('#watchHero')!.innerHTML=hero(i);detail.innerHTML=[['Title',`${i.title||'Rich Cinema'} · ${i.section||'watch'}`],['Creator',i.creator_name||'Rich Creator'],['Audience',`${Number(i.view_count??0).toLocaleString()} views`],['Progress',`${pct(progress.get(key(i)))}% watched · ${progress.get(key(i))?.completed?'completed':'in progress'}`],['Library',`${liked.has(key(i))?'liked':'not liked'} · ${saved.has(key(i))?'saved':'not saved'}`]].map(([a,b])=>`<div class="media-ultimate__row"><div><h5>${a}</h5><p>${esc(b)}</p></div></div>`).join('');const video=document.querySelector<HTMLVideoElement>('#watchPlayer');if(video){video.disablePictureInPicture=true;video.setAttribute('disableRemotePlayback','');video.playsInline=true;}const p=progress.get(key(i));video?.addEventListener('loadedmetadata',()=>{if(p?.position_seconds&&Number(p.position_seconds)<video.duration-5)video.currentTime=Number(p.position_seconds);});video?.addEventListener('timeupdate',()=>{clearTimeout(timer);timer=window.setTimeout(()=>void sync(video),900);});video?.addEventListener('pause',()=>void sync(video,true));video?.addEventListener('ended',()=>void sync(video,true));document.querySelector<HTMLButtonElement>('#watchLikeBtn')?.addEventListener('click',async()=>{if(liked.has(key(i))){await supabase.from('watch_likes').delete().eq('user_id',session.user.id).eq('source_type',i.source_type).eq('source_id',i.source_id);liked.delete(key(i));}else{await supabase.from('watch_likes').insert({user_id:session.user.id,source_type:i.source_type,source_id:i.source_id});liked.add(key(i));}await open(i);});document.querySelector<HTMLButtonElement>('#watchSaveBtn')?.addEventListener('click',async()=>{if(saved.has(key(i))){await supabase.from('watchlist_items').delete().eq('user_id',session.user.id).eq('source_type',i.source_type).eq('source_id',i.source_id);saved.delete(key(i));}else{await supabase.from('watchlist_items').insert({user_id:session.user.id,source_type:i.source_type,source_id:i.source_id});saved.add(key(i));}render();await open(i);});if(channel)await supabase.removeChannel(channel);await loadComments();channel=supabase.channel(`watch-comments:${i.source_id}`).on('postgres_changes',{event:'*',schema:'public',table:'watch_comments',filter:`source_id=eq.${i.source_id}`},()=>void loadComments()).subscribe();render();};
 document.querySelectorAll<HTMLButtonElement>('[data-lane]').forEach(b=>b.onclick=()=>{lane=b.dataset.lane!;document.querySelectorAll('[data-lane]').forEach(x=>x.classList.toggle('active',x===b));document.querySelector<HTMLElement>('#watchLaneTitle')!.textContent=b.textContent??'Watch';render();const first=visible()[0];if(first)void open(first);});
 document.querySelector<HTMLFormElement>('#watchCommentForm')!.onsubmit=async e=>{e.preventDefault();if(!active)return;const input=document.querySelector<HTMLInputElement>('#watchCommentInput')!;const body=input.value.trim();if(!body)return;const {error}=await supabase.from('watch_comments').insert({user_id:session.user.id,source_type:active.source_type,source_id:active.source_id,body});if(!error){input.value='';await loadComments();}};
 render();if(active)await open(active);
}
function hero(i:Row){return `<video id="watchPlayer" class="media-ultimate__hero-media" controls playsinline webkit-playsinline disablePictureInPicture disableRemotePlayback preload="metadata" poster="${esc(i.thumbnail_url)}" src="${esc(i.media_url)}"></video><div class="media-ultimate__hero-copy"><span class="media-ultimate__eyebrow">RICH CINEMA · ${esc((i.section||'WATCH').toUpperCase())}</span><h2>${esc(i.title||'Rich Cinema')}</h2><p>${esc(i.description||'Premium creator video from across the Rich Bizness universe.')}</p><div class="media-ultimate__actions"><button class="media-ultimate__btn primary" onclick="document.querySelector('#watchPlayer')?.play()">▶ WATCH NOW</button><button id="watchLikeBtn" class="media-ultimate__btn">♡ LIKE</button><button id="watchSaveBtn" class="media-ultimate__btn">+ MY LIST</button><a class="media-ultimate__btn" href="/profile.html?id=${esc(i.creator_id)}">CREATOR</a></div></div>`;}
