import { supabase } from '../../core/supabase/client';
import './watch.css';

type WatchItem={source_type:string;source_id:string;creator_id:string|null;creator_name:string|null;title:string|null;description:string|null;media_url:string|null;thumbnail_url:string|null;duration_seconds:number|null;view_count:number|null;created_at:string|null;section:string|null};
type Progress={source_type:string;source_id:string;position_seconds:number;duration_seconds:number;completed:boolean};
type CommentRow={id:string;user_id:string;body:string;created_at:string;profiles?:{display_name?:string|null;username?:string|null}|null};
const esc=(v:string|null|undefined)=>(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]??c));
const stamp=(v:string|null)=>v?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric'}).format(new Date(v)):'';

export async function mount():Promise<void>{
  const root=document.querySelector<HTMLElement>('#app');if(!root)throw new Error('Missing #app mount');
  const {data:{session}}=await supabase.auth.getSession();if(!session){location.replace('/tap-in.html?next=%2Fwatch.html');return;}
  root.innerHTML=`<main class="watch-shell"><div class="watch-wrap"><header class="watch-head"><a href="/portal.html">←</a><div><p>RICH BIZNESS CINEMA</p><h1>Watch</h1></div><span class="watch-pill">SYNCED</span></header><section id="hero" class="watch-hero"><div class="watch-empty">Choose something to watch.</div></section><nav id="filters" class="watch-controls"></nav><section id="grid" class="watch-grid"></section><section id="commentsPanel" class="watch-panel" hidden><h3>Rich Reactions</h3><div id="comments" class="watch-comments"></div><form id="commentForm" class="watch-comment-form"><input id="commentInput" maxlength="2000" placeholder="Drop a comment..."><button class="watch-btn primary">POST</button></form></section><p id="status" class="watch-status"></p></div></main>`;
  const hero=document.querySelector<HTMLElement>('#hero')!;const grid=document.querySelector<HTMLElement>('#grid')!;const filters=document.querySelector<HTMLElement>('#filters')!;const panel=document.querySelector<HTMLElement>('#commentsPanel')!;const comments=document.querySelector<HTMLElement>('#comments')!;const status=document.querySelector<HTMLElement>('#status')!;
  let items:WatchItem[]=[];let active:WatchItem|null=null;let progress=new Map<string,Progress>();let liked=new Set<string>();let saved=new Set<string>();let filter='all';let commentChannel:any=null;let saveTimer:number|undefined;
  const key=(i:Pick<WatchItem,'source_type'|'source_id'>)=>`${i.source_type}:${i.source_id}`;
  const setStatus=(v:string)=>{status.textContent=v;window.setTimeout(()=>{if(status.textContent===v)status.textContent='';},2200)};
  const loadState=async()=>{const [{data:p},{data:l},{data:s}]=await Promise.all([supabase.from('watch_progress').select('source_type,source_id,position_seconds,duration_seconds,completed').eq('user_id',session.user.id),supabase.from('watch_likes').select('source_type,source_id').eq('user_id',session.user.id),supabase.from('watchlist_items').select('source_type,source_id').eq('user_id',session.user.id)]);progress=new Map((p??[]).map((r:any)=>[`${r.source_type}:${r.source_id}`,r]));liked=new Set((l??[]).map((r:any)=>`${r.source_type}:${r.source_id}`));saved=new Set((s??[]).map((r:any)=>`${r.source_type}:${r.source_id}`));};
  const renderFilters=()=>{const rows=[['all','All'],['live','Live Replays'],['feed','Feed'],['gaming','Gaming'],['sports','Sports'],['saved','My List'],['continue','Continue Watching']];filters.innerHTML=rows.map(([v,label])=>`<button class="watch-chip ${filter===v?'active':''}" data-filter="${v}">${label}</button>`).join('');filters.querySelectorAll<HTMLButtonElement>('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter!;renderFilters();renderGrid();});};
  const visible=()=>items.filter(i=>filter==='all'||filter===i.section||(filter==='saved'&&saved.has(key(i)))||(filter==='continue'&&(progress.get(key(i))?.position_seconds??0)>0&&!progress.get(key(i))?.completed));
  const renderGrid=()=>{const rows=visible();grid.innerHTML=rows.length?rows.map(i=>{const p=progress.get(key(i));const pct=p&&p.duration_seconds?Math.min(100,Math.round(p.position_seconds/p.duration_seconds*100)):0;return `<article class="watch-card" data-key="${key(i)}"><img class="watch-thumb" src="${esc(i.thumbnail_url||'/images/brand/IMG_5997.png')}" alt=""><div class="watch-progress"><span style="width:${pct}%"></span></div><div class="watch-card-body"><h3>${esc(i.title||'Rich Video')}</h3><p>${esc(i.creator_name||'Rich Creator')} · ${stamp(i.created_at)} · ${(i.view_count??0).toLocaleString()} views</p></div></article>`}).join(''):'<div class="watch-empty">Nothing in this lane yet.</div>';grid.querySelectorAll<HTMLElement>('[data-key]').forEach(el=>el.onclick=()=>{const i=items.find(x=>key(x)===el.dataset.key);if(i)void openItem(i);});};
  const loadComments=async()=>{if(!active)return;const {data}=await supabase.from('watch_comments').select('id,user_id,body,created_at,profiles(display_name,username)').eq('source_type',active.source_type).eq('source_id',active.source_id).order('created_at',{ascending:true}).limit(100);comments.innerHTML=(data??[]).length?(data as any[]).map((c:CommentRow)=>`<div class="watch-comment"><p>${esc(c.body)}</p><small>${esc(c.profiles?.display_name||c.profiles?.username||'Rich Member')} · ${stamp(c.created_at)}</small></div>`).join(''):'<div class="watch-empty">Start the conversation.</div>';};
  const syncProgress=async(video:HTMLVideoElement,force=false)=>{if(!active)return;if(!force&&video.currentTime<1)return;await supabase.from('watch_progress').upsert({user_id:session.user.id,source_type:active.source_type,source_id:active.source_id,position_seconds:Math.floor(video.currentTime),duration_seconds:Number.isFinite(video.duration)?Math.floor(video.duration):(active.duration_seconds??0),completed:video.duration>0&&video.currentTime/video.duration>.92,last_watched_at:new Date().toISOString()},{onConflict:'user_id,source_type,source_id'});progress.set(key(active),{source_type:active.source_type,source_id:active.source_id,position_seconds:Math.floor(video.currentTime),duration_seconds:Number.isFinite(video.duration)?Math.floor(video.duration):(active.duration_seconds??0),completed:video.duration>0&&video.currentTime/video.duration>.92});renderGrid();};
  const openItem=async(i:WatchItem)=>{active=i;panel.hidden=false;if(commentChannel)await supabase.removeChannel(commentChannel);const k=key(i);hero.innerHTML=`<video id="watchPlayer" class="watch-player" controls playsinline poster="${esc(i.thumbnail_url)}" src="${esc(i.media_url)}"></video><div class="watch-overlay"><h2>${esc(i.title||'Rich Video')}</h2><p>${esc(i.description||'')}</p><div class="watch-meta"><span>${esc(i.creator_name||'Rich Creator')}</span><span>${esc(i.section||'watch')}</span><span>${(i.view_count??0).toLocaleString()} views</span></div><div class="watch-actions"><button id="likeBtn" class="watch-btn ${liked.has(k)?'primary':''}">${liked.has(k)?'♥ LIKED':'♡ LIKE'}</button><button id="saveBtn" class="watch-btn ${saved.has(k)?'primary':''}">${saved.has(k)?'✓ MY LIST':'+ MY LIST'}</button><a class="watch-btn" href="/profile.html?id=${esc(i.creator_id)}">CREATOR</a></div></div>`;const video=hero.querySelector<HTMLVideoElement>('#watchPlayer')!;const p=progress.get(k);video.addEventListener('loadedmetadata',()=>{if(p?.position_seconds&&p.position_seconds<video.duration-5)video.currentTime=p.position_seconds;});video.addEventListener('timeupdate',()=>{clearTimeout(saveTimer);saveTimer=window.setTimeout(()=>void syncProgress(video),1000);});video.addEventListener('pause',()=>void syncProgress(video,true));video.addEventListener('ended',()=>void syncProgress(video,true));hero.querySelector<HTMLButtonElement>('#likeBtn')!.onclick=async()=>{if(liked.has(k)){await supabase.from('watch_likes').delete().eq('user_id',session.user.id).eq('source_type',i.source_type).eq('source_id',i.source_id);liked.delete(k);}else{await supabase.from('watch_likes').insert({user_id:session.user.id,source_type:i.source_type,source_id:i.source_id});liked.add(k);}void openItem(i);};hero.querySelector<HTMLButtonElement>('#saveBtn')!.onclick=async()=>{if(saved.has(k)){await supabase.from('watchlist_items').delete().eq('user_id',session.user.id).eq('source_type',i.source_type).eq('source_id',i.source_id);saved.delete(k);}else{await supabase.from('watchlist_items').insert({user_id:session.user.id,source_type:i.source_type,source_id:i.source_id});saved.add(k);}renderGrid();void openItem(i);};await loadComments();commentChannel=supabase.channel(`watch-comments:${k}`).on('postgres_changes',{event:'*',schema:'public',table:'watch_comments',filter:`source_id=eq.${i.source_id}`},()=>void loadComments()).subscribe();};
  document.querySelector<HTMLFormElement>('#commentForm')!.onsubmit=async e=>{e.preventDefault();if(!active)return;const input=document.querySelector<HTMLInputElement>('#commentInput')!;const body=input.value.trim();if(!body)return;const {error}=await supabase.from('watch_comments').insert({user_id:session.user.id,source_type:active.source_type,source_id:active.source_id,body});if(error){setStatus(error.message);return;}input.value='';await loadComments();};
  await loadState();const {data,error}=await supabase.rpc('rb_watch_feed',{p_limit:80});if(error){grid.innerHTML=`<div class="watch-empty">${esc(error.message)}</div>`;return;}items=(data??[]) as WatchItem[];renderFilters();renderGrid();if(items[0])await openItem(items[0]);
}
