import { getAuthSnapshot } from '../../core/auth/auth-store';
import { supabase } from '../../core/supabase/client';
import '../../styles/broadcast-cinema-podcast.css';
import './watch.css';

type Row=Record<string,any>;
type Channel=ReturnType<typeof supabase.channel>;
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c));
const key=(r:Row)=>`${r.source_type}:${r.source_id}`;
const pct=(p:Row|undefined)=>p&&Number(p.duration_seconds)>0?Math.min(100,Math.round(Number(p.position_seconds)/Number(p.duration_seconds)*100)):0;
const safeUrl=(v:unknown)=>{try{const u=new URL(String(v||''),location.origin);return ['http:','https:'].includes(u.protocol)?u.href:'';}catch{return'';}};

export async function mount():Promise<void>{
 const root=document.querySelector<HTMLElement>('#app');
 if(!root)throw new Error('Missing #app mount');
 if(root.dataset.watchOwner==='true')return;
 root.dataset.watchOwner='true';
 const auth=getAuthSnapshot();
 const user=auth.user;
 const userId=user?.id??null;
 const sessionId=localStorage.getItem('rb_watch_session')||crypto.randomUUID();
 localStorage.setItem('rb_watch_session',sessionId);
 let items:Row[]=[],progress=new Map<string,Row>(),liked=new Set<string>(),saved=new Set<string>(),comments:Row[]=[];
 let metrics:Row={},lane='featured',active:Row|null=null,player:HTMLVideoElement|null=null,progressTimer:number|null=null;
 let catalogChannel:Channel|null=null,interactionChannel:Channel|null=null,loading=false,queued=false,disposed=false;
 const requireUser=()=>{if(userId)return true;location.href='/tap-in.html?next=%2Fwatch.html';return false;};
 const action=async(name:string,item:Row,payload:Row={})=>supabase.rpc('rb_watch_action',{p_action:name,p_source_type:item.source_type,p_source_id:item.source_id,p_payload:payload});
 const apply=(data:unknown)=>{const snap=(data??{}) as Row;items=(snap.items??[]) as Row[];progress=new Map(((snap.progress??[]) as Row[]).map(r=>[`${r.source_type}:${r.source_id}`,r]));liked=new Set(((snap.likes??[]) as Row[]).map(r=>`${r.source_type}:${r.source_id}`));saved=new Set(((snap.watchlist??[]) as Row[]).map(r=>`${r.source_type}:${r.source_id}`));comments=(snap.comments??[]) as Row[];metrics=snap.metrics??{};if(!active||!items.some(i=>key(i)===key(active!)))active=items[0]??null;};
 const load=async(selected:Row|null=active)=>{if(loading){queued=true;return;}loading=true;try{const {data,error}=await supabase.rpc('rb_watch_snapshot',{p_source_type:selected?.source_type??null,p_source_id:selected?.source_id??null});if(error)throw error;apply(data);renderMetrics();render();if(active)await open(active,false,false);}finally{loading=false;if(queued&&!disposed){queued=false;void load();}}};
 root.innerHTML=`<main class="media-ultimate watch-universe"><div class="media-ultimate__wrap">
 <header class="media-ultimate__head"><a href="/portal.html" aria-label="Back to Portal">←</a><div><p>RICH BIZNESS CINEMA NETWORK</p><h1>WE 🔥 📺</h1></div><span class="media-ultimate__status">${user?'● PERSONALIZED':'PUBLIC CINEMA'}</span></header>
 <nav class="watch-command"><a href="/live.html">WE LIT 🔥</a><a href="/feed.html">FEED</a><a href="/gallery.html">GALLERY</a><a href="/sports.html">SPORTS</a><a href="/gaming.html">GAMING</a><a href="/podcast.html">PODCAST</a><a href="/creator.html">CREATOR</a><a href="${user?'/upload.html?route=feed':'/tap-in.html?next=%2Fupload.html'}">DROP VIDEO</a></nav>
 <section id="watchHero" class="media-ultimate__hero"><div class="media-ultimate__empty">Loading the cinema network…</div></section>
 <section class="media-ultimate__metrics"><article><small>GLOBAL LIBRARY</small><strong id="watchLibraryCount">0</strong></article><article><small>CONTINUE WATCHING</small><strong id="watchContinueCount">0</strong></article><article><small>MY LIST</small><strong id="watchSavedCount">0</strong></article><article><small>COMPLETED</small><strong id="watchCompletedCount">0</strong></article></section>
 <nav class="media-ultimate__tabs">${[['featured','FEATURED'],['continue','CONTINUE'],['live','LIVE REPLAYS'],['podcast','PODCAST'],['gaming','GAMING'],['sports','SPORTS'],['feed','CREATOR FEED'],['saved','MY LIST']].map(([v,l],i)=>`<button class="${i===0?'active':''}" data-lane="${v}">${l}</button>`).join('')}</nav>
 <section class="media-ultimate__section"><header><div><h3 id="watchLaneTitle">Featured Cinema</h3><p>Replays, podcasts, creator films, game clips and sports moments in one ranked network.</p></div></header><div id="watchRail" class="cinema-rail"></div></section>
 <section class="media-ultimate__split"><article class="media-ultimate__panel"><header><h4>NOW WATCHING INTELLIGENCE</h4></header><div id="watchDetail" class="media-ultimate__list"></div></article><article class="media-ultimate__panel"><header><h4>RICH REACTIONS</h4></header><div id="watchComments" class="media-ultimate__chat"><div class="media-ultimate__empty">Choose a video.</div></div><form id="watchCommentForm" class="media-ultimate__form"><input id="watchCommentInput" maxlength="2000" placeholder="React to this drop..." ${user?'':'disabled'}><button class="media-ultimate__btn primary">${user?'POST':'TAP IN'}</button></form></article></section>
 <section class="media-ultimate__section"><header><div><h3>Because You Watch</h3><p>More from the sections and creators already in your history.</p></div></header><div id="recommendGrid" class="media-ultimate__grid"></div></section>
 </div></main>`;
 const rail=document.querySelector<HTMLElement>('#watchRail')!,detail=document.querySelector<HTMLElement>('#watchDetail')!,commentsEl=document.querySelector<HTMLElement>('#watchComments')!,recs=document.querySelector<HTMLElement>('#recommendGrid')!;
 const continueRows=()=>items.filter(i=>{const p=progress.get(key(i));return p&&Number(p.position_seconds)>0&&!p.completed;});
 const visible=()=>lane==='continue'?continueRows():lane==='saved'?items.filter(i=>saved.has(key(i))):lane==='featured'?items:items.filter(i=>String(i.section)===lane);
 const card=(i:Row)=>`<article class="media-ultimate__card" data-key="${esc(key(i))}"><img src="${esc(safeUrl(i.thumbnail_url)||'/images/brand/IMG_5997.png')}" alt=""><div class="watch-progress"><span style="width:${pct(progress.get(key(i)))}%"></span></div><div class="media-ultimate__card-body"><h4>${esc(i.title||'Rich Cinema')}</h4><p>${esc(i.creator_name||'Rich Creator')} · ${Number(i.view_count??0).toLocaleString()} views</p><div class="media-ultimate__meta"><span>${esc((i.section||'WATCH').toUpperCase())}</span><span>${progress.get(key(i))?.completed?'COMPLETED':pct(progress.get(key(i)))+'%'}</span></div></div></article>`;
 const bind=(host:HTMLElement)=>host.querySelectorAll<HTMLElement>('[data-key]').forEach(el=>el.onclick=()=>{const i=items.find(x=>key(x)===el.dataset.key);if(i)void open(i);});
 const renderMetrics=()=>{document.querySelector<HTMLElement>('#watchLibraryCount')!.textContent=String(metrics.library_count??items.length);document.querySelector<HTMLElement>('#watchContinueCount')!.textContent=String(metrics.continue_count??continueRows().length);document.querySelector<HTMLElement>('#watchSavedCount')!.textContent=String(metrics.saved_count??saved.size);document.querySelector<HTMLElement>('#watchCompletedCount')!.textContent=String(metrics.completed_count??[...progress.values()].filter(p=>p.completed).length);};
 const renderComments=()=>{commentsEl.innerHTML=comments.length?comments.map(c=>`<article><p>${esc(c.body)}</p><small>${esc(c.display_name||c.username||'Rich Viewer')} · ${new Date(c.created_at).toLocaleString()}</small></article>`).join(''):'<div class="media-ultimate__empty">Start the conversation.</div>';commentsEl.scrollTop=commentsEl.scrollHeight;};
 const render=()=>{const rows=visible();rail.innerHTML=rows.map(card).join('')||'<div class="media-ultimate__empty">Nothing in this lane yet.</div>';bind(rail);const basis=active?.section?items.filter(i=>i.section===active!.section&&key(i)!==key(active!)):items.slice(1);recs.innerHTML=basis.slice(0,8).map(card).join('')||'<div class="media-ultimate__empty">Recommendations build as you watch.</div>';bind(recs);renderComments();};
 const sync=async(force=false)=>{if(!userId||!active||!player||(!force&&player.currentTime<1))return;const duration=Number.isFinite(player.duration)?Math.floor(player.duration):Number(active.duration_seconds??0);const position=Math.floor(player.currentTime);const completed=duration>0&&position/duration>.92;const {data,error}=await action('progress',active,{position_seconds:position,duration_seconds:duration,completed,session_id:sessionId,device_type:/Mobi|Android/i.test(navigator.userAgent)?'mobile':'desktop'});if(!error){const row={source_type:active.source_type,source_id:active.source_id,position_seconds:position,duration_seconds:duration,completed,last_watched_at:new Date().toISOString()};progress.set(key(active),row);metrics.continue_count=continueRows().length;metrics.completed_count=[...progress.values()].filter(p=>p.completed).length;renderMetrics();render();return data;}};
 const teardown=async(save=true)=>{if(progressTimer){clearInterval(progressTimer);progressTimer=null;}if(player){if(save)await sync(true);player.pause();player.removeAttribute('src');player.load();player=null;}};
 const replaceChannel=async(i:Row)=>{if(interactionChannel){await supabase.removeChannel(interactionChannel);interactionChannel=null;}interactionChannel=supabase.channel(`watch-owner:${i.source_type}:${i.source_id}`).on('postgres_changes',{event:'*',schema:'public',table:'watch_comments',filter:`source_id=eq.${i.source_id}`},()=>void load(i)).subscribe();};
 const open=async(i:Row,savePrevious=true,refreshComments=true)=>{if(savePrevious)await teardown(true);active=i;if(refreshComments){const {data,error}=await supabase.rpc('rb_watch_snapshot',{p_source_type:i.source_type,p_source_id:i.source_id});if(!error)apply(data);}document.querySelector<HTMLElement>('#watchHero')!.innerHTML=hero(i,liked.has(key(i)),saved.has(key(i)),Boolean(userId));detail.innerHTML=[['TITLE',`${i.title||'Rich Cinema'} · ${i.section||'watch'}`],['CREATOR',i.creator_name||'Rich Creator'],['AUDIENCE',`${Number(i.view_count??0).toLocaleString()} views`],['PROGRESS',`${pct(progress.get(key(i)))}% watched · ${progress.get(key(i))?.completed?'completed':'in progress'}`],['LIBRARY',`${liked.has(key(i))?'liked':'not liked'} · ${saved.has(key(i))?'saved':'not saved'}`]].map(([a,b])=>`<div class="media-ultimate__row"><div><h5>${a}</h5><p>${esc(b)}</p></div></div>`).join('');player=document.querySelector<HTMLVideoElement>('#watchPlayer');if(player){player.disablePictureInPicture=true;player.disableRemotePlayback=true;player.playsInline=true;const p=progress.get(key(i));player.addEventListener('loadedmetadata',()=>{if(p?.position_seconds&&Number(p.position_seconds)<player!.duration-5)player!.currentTime=Number(p.position_seconds);},{once:true});player.addEventListener('pause',()=>void sync(true));player.addEventListener('ended',()=>void sync(true));progressTimer=window.setInterval(()=>void sync(false),15000);}document.querySelector<HTMLButtonElement>('#watchPlayBtn')?.addEventListener('click',()=>void player?.play());document.querySelector<HTMLButtonElement>('#watchLikeBtn')?.addEventListener('click',async()=>{if(!requireUser())return;const {data,error}=await action('toggle_like',i);if(!error){if((data as Row)?.active)liked.add(key(i));else liked.delete(key(i));await open(i,false,false);}});document.querySelector<HTMLButtonElement>('#watchSaveBtn')?.addEventListener('click',async()=>{if(!requireUser())return;const {data,error}=await action('toggle_save',i);if(!error){if((data as Row)?.active)saved.add(key(i));else saved.delete(key(i));metrics.saved_count=saved.size;renderMetrics();render();await open(i,false,false);}});render();await replaceChannel(i);};
 document.querySelectorAll<HTMLButtonElement>('[data-lane]').forEach(button=>button.onclick=()=>{lane=button.dataset.lane!;document.querySelectorAll('[data-lane]').forEach(n=>n.classList.toggle('active',n===button));document.querySelector<HTMLElement>('#watchLaneTitle')!.textContent=button.textContent??'Watch';render();const first=visible()[0];if(first)void open(first);});
 document.querySelector<HTMLFormElement>('#watchCommentForm')!.onsubmit=async event=>{event.preventDefault();if(!requireUser()||!active)return;const input=document.querySelector<HTMLInputElement>('#watchCommentInput')!;const body=input.value.trim();if(!body)return;const submit=event.submitter as HTMLButtonElement|null;if(submit)submit.disabled=true;try{const {error}=await action('comment',active,{body});if(error)throw error;input.value='';await load(active);}finally{if(submit)submit.disabled=false;}};
 catalogChannel=supabase.channel('watch-catalog-owner').on('postgres_changes',{event:'*',schema:'public',table:'live_recordings'},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'podcast_episodes'},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'feed_posts'},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'game_clips'},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'sports_uploads'},()=>void load()).subscribe();
 const cleanup=async()=>{if(disposed)return;disposed=true;if(active&&userId)await action('end_session',active,{session_id:sessionId});await teardown(true);if(catalogChannel)await supabase.removeChannel(catalogChannel);if(interactionChannel)await supabase.removeChannel(interactionChannel);catalogChannel=null;interactionChannel=null;};
 window.addEventListener('pagehide',()=>void cleanup(),{once:true});window.addEventListener('beforeunload',()=>void cleanup(),{once:true});await load();
}

function hero(i:Row,isLiked:boolean,isSaved:boolean,signedIn:boolean){const poster=safeUrl(i.thumbnail_url)||'/images/brand/IMG_5997.png';const media=safeUrl(i.media_url);return `<video id="watchPlayer" class="media-ultimate__hero-media" controls playsinline webkit-playsinline disablePictureInPicture disableRemotePlayback preload="metadata" poster="${esc(poster)}" src="${esc(media)}"></video><div class="media-ultimate__hero-copy"><span class="media-ultimate__eyebrow">WE 🔥 📺 · ${esc((i.section||'WATCH').toUpperCase())}</span><h2>${esc(i.title||'Rich Cinema')}</h2><p>${esc(i.description||'Premium creator video from across the Rich Bizness universe.')}</p><div class="media-ultimate__actions"><button id="watchPlayBtn" class="media-ultimate__btn primary" type="button">▶ WATCH NOW</button><button id="watchLikeBtn" class="media-ultimate__btn" type="button">${isLiked?'♥ LIKED':'♡ LIKE'}</button><button id="watchSaveBtn" class="media-ultimate__btn" type="button">${isSaved?'✓ MY LIST':'+ MY LIST'}</button><a class="media-ultimate__btn" href="${signedIn?`/profile.html?id=${encodeURIComponent(String(i.creator_id||''))}`:'/tap-in.html?next=%2Fwatch.html'}">CREATOR</a></div></div>`;}