import { supabase } from '../../src/supabase-client.js';
import { getAuthoritativeIdentity } from '../../src/rb-identity.js?v=profile-avatar-separate-1';

const $=id=>document.getElementById(id),canvas=$('world'),ctx=canvas.getContext('2d');
let identity={},game=null,player,shards,portals,npcs,particles,keys={},running=true,score=0,aura=0,distance=0,mission=0,last=0,startedAt=Date.now();
const missions=[{title:'Collect 5 aura shards',target:5,type:'shard'},{title:'Talk to the district guide',target:1,type:'talk'},{title:'Reach the gold portal',target:1,type:'portal'}];
function reset(){player={x:180,y:360,r:22,speed:220,dash:0};shards=Array.from({length:12},(_,i)=>({x:120+Math.random()*720,y:90+Math.random()*330,r:10,hit:false}));portals=[{x:840,y:130,r:42,kind:'gold'},{x:760,y:410,r:34,kind:'green'}];npcs=[{x:470,y:245,r:24,name:'District Guide',talked:false}];particles=[];score=0;aura=0;distance=0;mission=0;running=true;startedAt=Date.now();sync();}
function sync(msg){$('score').textContent=score.toLocaleString();$('aura').textContent=aura;$('distance').textContent=Math.floor(distance);$('mission').textContent=`${mission+1}/3`;$('status').textContent=msg||missions[Math.min(mission,2)].title;document.querySelectorAll('.mission').forEach((n,i)=>n.classList.toggle('done',i<mission));}
function burst(x,y,color='#9dff63'){for(let i=0;i<16;i++)particles.push({x,y,vx:(Math.random()-.5)*180,vy:(Math.random()-.5)*180,life:1,color});}
function move(dt){let dx=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0),dy=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0);if(dx||dy){const len=Math.hypot(dx,dy)||1,m=player.dash>0?2.2:1;dx/=len;dy/=len;player.x+=dx*player.speed*m*dt;player.y+=dy*player.speed*m*dt;distance+=player.speed*m*dt/100;player.x=Math.max(35,Math.min(925,player.x));player.y=Math.max(45,Math.min(495,player.y));}player.dash=Math.max(0,player.dash-dt);}
function collide(){for(const s of shards){if(!s.hit&&Math.hypot(player.x-s.x,player.y-s.y)<player.r+s.r+6){s.hit=true;aura++;score+=250;burst(s.x,s.y);if(mission===0&&aura>=5){mission=1;score+=1000;sync('Mission complete • Find the guide')}else sync('Aura shard collected')}}for(const n of npcs){if(!n.talked&&Math.hypot(player.x-n.x,player.y-n.y)<55&&(keys.e||keys.Enter)){n.talked=true;score+=750;burst(n.x,n.y,'#ffe58a');if(mission===1){mission=2;sync('Guide met • Reach the gold portal')}}}for(const p of portals){if(Math.hypot(player.x-p.x,player.y-p.y)<p.r+player.r){if(p.kind==='gold'&&mission===2){mission=3;score+=2000;running=false;burst(p.x,p.y,'#ffe58a');sync('DISTRICT CLEARED • SAVE YOUR RUN');saveRun('completed')}}}}
function updateParticles(dt){for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt}particles=particles.filter(p=>p.life>0)}
function drawWorld(){ctx.clearRect(0,0,960,540);const g=ctx.createLinearGradient(0,0,0,540);g.addColorStop(0,'#102718');g.addColorStop(1,'#071009');ctx.fillStyle=g;ctx.fillRect(0,0,960,540);ctx.fillStyle='#0d1610';for(let x=0;x<960;x+=120)ctx.fillRect(x,0,70,540);ctx.fillStyle='#26331f';ctx.fillRect(0,210,960,120);ctx.fillStyle='rgba(255,229,138,.35)';for(let x=30;x<960;x+=95)ctx.fillRect(x,265,46,5);for(const p of portals){const grd=ctx.createRadialGradient(p.x,p.y,5,p.x,p.y,p.r);grd.addColorStop(0,p.kind==='gold'?'#fff3b0':'#d7ffd0');grd.addColorStop(.45,p.kind==='gold'?'#ffe58a':'#9dff63');grd.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=grd;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();ctx.strokeStyle=p.kind==='gold'?'#ffe58a':'#9dff63';ctx.lineWidth=5;ctx.beginPath();ctx.arc(p.x,p.y,p.r*.72,0,Math.PI*2);ctx.stroke()}for(const s of shards){if(s.hit)continue;ctx.fillStyle='#9dff63';ctx.shadowBlur=18;ctx.shadowColor='#9dff63';ctx.beginPath();ctx.moveTo(s.x,s.y-12);ctx.lineTo(s.x+9,s.y);ctx.lineTo(s.x,s.y+12);ctx.lineTo(s.x-9,s.y);ctx.closePath();ctx.fill();ctx.shadowBlur=0}for(const n of npcs){ctx.fillStyle=n.talked?'#5f6d62':'#ffe58a';ctx.beginPath();ctx.arc(n.x,n.y,n.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#061006';ctx.font='bold 12px system-ui';ctx.textAlign='center';ctx.fillText('GUIDE',n.x,n.y+4);ctx.textAlign='start'}for(const p of particles){ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,4,4)}ctx.globalAlpha=1;ctx.fillStyle='#0b0f0b';ctx.shadowBlur=24;ctx.shadowColor='#9dff63';ctx.beginPath();ctx.arc(player.x,player.y,player.r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ffe58a';ctx.lineWidth=4;ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#ffe58a';ctx.font='bold 15px system-ui';ctx.textAlign='center';ctx.fillText('RB',player.x,player.y+5);ctx.textAlign='start';if(mission===1)ctx.fillStyle='rgba(255,229,138,.12)',ctx.fillRect(420,195,100,100)}
function frame(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;if(running){move(dt);collide()}updateParticles(dt);drawWorld();requestAnimationFrame(frame)}
function dash(){if(player.dash<=0){player.dash=.42;burst(player.x,player.y)}}
async function loadIdentity(){identity=await getAuthoritativeIdentity().catch(()=>({}));const p=identity.profile||{};$('playerName').textContent=p.display_name||p.username||'Rich Traveler';$('rank').textContent=p.rank_title||'Traveler';const avatar=$('avatar');if(p.avatar_url)avatar.innerHTML=`<img src="${p.avatar_url}" alt="">`;if(identity.user){const {data}=await supabase.from('meta_avatars').select('aura,level,avatar_url').eq('user_id',identity.user.id).maybeSingle();$('level').textContent=data?.level||p.rich_level||1;$('auraName').textContent=data?.aura||'green-gold';if(data?.avatar_url)avatar.innerHTML=`<img src="${data.avatar_url}" alt="">`}}
async function getGame(){const {data}=await supabase.from('games').select('id,slug').eq('slug','avatar-free-roam').maybeSingle();game=data||null}
async function saveRun(result='completed'){if(!identity.user)await loadIdentity();if(!identity.user){location.href='/auth.html?next='+encodeURIComponent(location.pathname);return}if(!game)await getGame();const seconds=Math.floor((Date.now()-startedAt)/1000),payload={game_id:game?.id||null,game_slug:'avatar-free-roam',user_id:identity.user.id,username:identity.profile?.username||null,display_name:identity.profile?.display_name||null,result,score,platform_type:'web',duration_seconds:seconds,metadata:{source:'games/avatar-free-roam',aura_shards:aura,distance:Math.floor(distance),mission,position:{x:player.x,y:player.y}}};await supabase.from('game_sessions').insert(payload);await supabase.from('game_scores').insert({...payload,mode:'free-roam',is_verified:true,anti_cheat_status:'verified'});await supabase.rpc('rb_award_xp',{p_event_key:'avatar_free_roam_clear',p_source_table:'game_sessions',p_source_id:null,p_metadata:{score,aura,distance:Math.floor(distance)}}).catch(()=>{});sync('RUN SAVED • XP AWARDED')}
function bind(){addEventListener('keydown',e=>{keys[e.key]=true;if(e.key===' ')dash();if(e.key.toLowerCase()==='p')running=!running});addEventListener('keyup',e=>keys[e.key]=false);document.querySelectorAll('[data-move]').forEach(b=>{const k=b.dataset.move;b.onpointerdown=()=>keys[k]=true;b.onpointerup=b.onpointerleave=()=>keys[k]=false});$('dash').onclick=dash;$('interact').onclick=()=>{keys.e=true;setTimeout(()=>keys.e=false,150)};$('pause').onclick=()=>{running=!running;sync(running?'RUN RESUMED':'PAUSED')};$('reset').onclick=reset;$('save').onclick=()=>saveRun('completed')}
await loadIdentity();await getGame();bind();reset();requestAnimationFrame(frame);